export const PROGRESS_TRACKS = [
  { id: 'hear_sounds', reportStrandId: 'hear_sounds', name: 'Hear sounds', construct: 'spoken_initial_phoneme_discrimination', modality: 'audio', formatType: 'PROGRESS_SPOKEN_INITIAL_MATCH', tierRationales: ['Familiar unclustered anchors with widely separated initial sounds.', 'Familiar unclustered anchors with a voiced/unvoiced or nearby place contrast.', 'Consonant-cluster anchors require isolating the initial phoneme, not the whole cluster.'], unsampled: ['rhyme', 'segmentation', 'blending', 'phoneme manipulation'], allowsChoiceAudio: true },
  { id: 'printed_words', reportStrandId: 'printed_words', name: 'Read words and spellings', construct: 'heard_regular_word_to_print_recognition', modality: 'audio+print', formatType: 'HEARD_WORD_TO_PRINT_MINIMAL_PAIR', tierRationales: ['Short-vowel words with one written consonant at each edge, including x.', 'Regular words containing a consonant cluster or consonant digraph.', 'Regular long-vowel spellings require choosing the complete written word.'], unsampled: ['oral decoding', 'fluency', 'encoding', 'multisyllabic reading'], allowsChoiceAudio: false },
  { id: 'common_words', reportStrandId: 'common_words', name: 'Recognize common words', construct: 'heard_common_word_to_print_recognition', modality: 'audio+print', formatType: 'HFW_AUDIO_FIND_WORD', tierRationales: ['Short common words with clearly distinct written competitors.', 'Common words with closer length and letter-neighbour competitors.', 'Longer common words with orthographically close competitors. List position is not a difficulty parameter.'], unsampled: ['spelling', 'contextual use', 'automaticity'], allowsChoiceAudio: false },
  { id: 'word_meaning', reportStrandId: 'word_meaning', name: 'Understand words and sentences', construct: 'spoken_synonym_recognition', modality: 'audio', formatType: 'PROGRESS_SPOKEN_SYNONYM', tierRationales: ['A familiar concrete sense contrasted with clear opposite or unrelated degrees in the same meaning domain.', 'A familiar sense contrasted with plausible neighbouring meanings in the same domain.', 'A more precise action or state contrasted with related but non-equivalent actions or states.'], unsampled: ['grammar', 'morphology', 'antonyms', 'sentence integration'], allowsChoiceAudio: true },
  { id: 'listening_stories', reportStrandId: 'listening_stories', name: 'Understand spoken stories', construct: 'heard_literal_detail_retrieval', modality: 'audio', formatType: 'PROGRESS_LISTENING_DETAIL', tierRationales: ['Retrieve one explicit detail from a single recorded sentence.', 'Retrieve one explicit detail among several events in a short recorded passage.', 'Select a precise explicit detail in a longer passage with competing stated details.'], unsampled: ['inference', 'main idea', 'theme', 'independent reading'], allowsChoiceAudio: true },
  { id: 'reading_stories', reportStrandId: 'reading_stories', name: 'Read and understand', construct: 'printed_literal_detail_retrieval', modality: 'print', formatType: 'PROGRESS_READING_DETAIL', tierRationales: ['Retrieve one explicit detail from a short printed sentence.', 'Retrieve one explicit detail from a short printed passage.', 'Retrieve a precise explicit detail across several printed sentences with competing details.'], unsampled: ['inference', 'main idea', 'theme', 'oral reading fluency'], allowsChoiceAudio: true }
].map(track => ({ ...track, minTier: 0, maxTier: 2, defaultTier: 0, difficultyVersion: 'progress-ordinal-2026-10-02.1' }));

export const wordRows = (trackId, tiers) => tiers.flatMap((rows, tier) => rows.map(([target, key, ...distractors], index) => ({
  trackId, tier, sourceKey: `${tier}-${index + 1}-${target}`, target,
  prompt: trackId === 'hear_sounds' ? 'Which word starts with the same sound?'
    : trackId === 'word_meaning' ? 'Which word means about the same?'
      : 'Find the word you hear.',
  options: [key, ...distractors].map((text, i) => ({ text, key: i === 0, rationale: i === 0 ? 'KEY' : trackId === 'word_meaning' ? 'D-SAME-DOMAIN' : trackId === 'hear_sounds' ? 'D-ONSET' : 'D-VISUAL-NEIGHBOR' })),
  note: trackId === 'hear_sounds' ? `Compare the first phoneme of ${target} with ${key}; distractors have different first phonemes.`
    : trackId === 'word_meaning' ? `Use the ordinary isolated-word sense of ${target}; ${key} is equivalent, competitors differ in that same meaning domain.`
      : `Recognize the complete written form of the independently spoken ${target}; competitors differ in spelling and pronunciation.`
})));
