export const curatedPublicDomainBooks = [
  {
    id: "mcguffeys-eclectic-primer",
    title: "McGuffey's Eclectic Primer",
    author: "William Holmes McGuffey",
    band: "Pre-reader",
    guidedReadingLevel: "A",
    readingLevel: "emergent",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/14642",
    downloadUrl: "https://www.gutenberg.org/cache/epub/14642/pg14642.txt",
    priority: 1,
    ocrCleanupLikely: false,
    illustrationQuality: "Limited, primer-style support.",
    notes: "Highly controlled primer language; useful for early decoding and repeated structures.",
    tags: ["primer", "phonics", "decoding"]
  },
  {
    id: "a-apple-pie",
    title: "A Apple Pie",
    author: "Kate Greenaway",
    band: "Pre-reader",
    guidedReadingLevel: "A",
    readingLevel: "emergent",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/15809",
    downloadUrl: "https://www.gutenberg.org/cache/epub/15809/pg15809.txt",
    priority: 1,
    ocrCleanupLikely: false,
    illustrationQuality: "Strong alphabet-picture-book source when image edition is available.",
    notes: "Alphabet structure supports pre-reader concepts and vocabulary.",
    tags: ["alphabet", "vocabulary", "pre-reader"]
  },
  {
    id: "diverting-history-john-gilpin",
    title: "The Diverting History of John Gilpin",
    author: "William Cowper",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/2513",
    downloadUrl: "https://www.gutenberg.org/cache/epub/2513/pg2513.txt",
    priority: 4,
    ocrCleanupLikely: false,
    illustrationQuality: "Illustrated editions exist, but text is more advanced.",
    notes: "Use cautiously as read-aloud or fluency extension, not core early reader.",
    tags: ["humor", "rhyme", "read-aloud"]
  },
  {
    id: "tale-of-peter-rabbit",
    title: "The Tale of Peter Rabbit",
    author: "Beatrix Potter",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "E",
    readingLevel: "developing",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/14838",
    downloadUrl: "https://www.gutenberg.org/cache/epub/14838/pg14838.txt",
    priority: 1,
    ocrCleanupLikely: false,
    illustrationQuality: "Excellent original illustrations in illustrated editions.",
    notes: "Beloved animal story; some longer sentences need page-level scaffolding.",
    tags: ["animals", "classic", "sequencing"]
  },
  {
    id: "tale-of-benjamin-bunny",
    title: "The Tale of Benjamin Bunny",
    author: "Beatrix Potter",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "E",
    readingLevel: "developing",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/14407",
    downloadUrl: "https://www.gutenberg.org/cache/epub/14407/pg14407.txt",
    priority: 1,
    ocrCleanupLikely: false,
    illustrationQuality: "Excellent original illustrations in illustrated editions.",
    notes: "Animal adventure with familiar characters; review for sentence length.",
    tags: ["animals", "classic", "adventure"]
  },
  {
    id: "tale-of-squirrel-nutkin",
    title: "The Tale of Squirrel Nutkin",
    author: "Beatrix Potter",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "E",
    readingLevel: "developing",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/14872",
    downloadUrl: "https://www.gutenberg.org/cache/epub/14872/pg14872.txt",
    priority: 1,
    ocrCleanupLikely: false,
    illustrationQuality: "Excellent original illustrations in illustrated editions.",
    notes: "Strong comprehension sequence; check archaic phrasing.",
    tags: ["animals", "classic", "comprehension"]
  },
  {
    id: "tale-of-mrs-tiggy-winkle",
    title: "The Tale of Mrs. Tiggy-Winkle",
    author: "Beatrix Potter",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "E",
    readingLevel: "developing",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/14837",
    downloadUrl: "https://www.gutenberg.org/cache/epub/14837/pg14837.txt",
    priority: 1,
    ocrCleanupLikely: false,
    illustrationQuality: "Excellent original illustrations in illustrated editions.",
    notes: "Gentle animal/fantasy story; useful for character and setting.",
    tags: ["animals", "classic", "setting"]
  },
  {
    id: "tailor-of-gloucester",
    title: "The Tailor of Gloucester",
    author: "Beatrix Potter",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/14868",
    downloadUrl: "https://www.gutenberg.org/cache/epub/14868/pg14868.txt",
    priority: 2,
    ocrCleanupLikely: false,
    illustrationQuality: "Excellent original illustrations in illustrated editions.",
    notes: "Richer language; likely read-aloud or advanced guided reading.",
    tags: ["classic", "animals", "kindness"]
  },
  {
    id: "johnny-crows-garden",
    title: "Johnny Crow's Garden",
    author: "L. Leslie Brooke",
    band: "Early reader",
    guidedReadingLevel: "B",
    readingLevel: "early",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/10469",
    downloadUrl: "https://www.gutenberg.org/cache/epub/10469/pg10469.txt",
    priority: 2,
    ocrCleanupLikely: false,
    illustrationQuality: "Strong picture-book illustrations in source editions.",
    notes: "Animal cast and repeating structure; check for older vocabulary.",
    tags: ["animals", "rhyme", "vocabulary"]
  },
  {
    id: "johnny-crows-party",
    title: "Johnny Crow's Party",
    author: "L. Leslie Brooke",
    band: "Early reader",
    guidedReadingLevel: "B",
    readingLevel: "early",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/10557",
    downloadUrl: "https://www.gutenberg.org/cache/epub/10557/pg10557.txt",
    priority: 2,
    ocrCleanupLikely: false,
    illustrationQuality: "Strong picture-book illustrations in source editions.",
    notes: "Short, playful animal text; useful for fluency and vocabulary.",
    tags: ["animals", "humor", "fluency"]
  },
  {
    id: "three-little-pigs",
    title: "The Story of the Three Little Pigs",
    author: "L. Leslie Brooke",
    band: "Late K / Grade 1",
    guidedReadingLevel: "C",
    readingLevel: "early",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/18155",
    downloadUrl: "https://www.gutenberg.org/cache/epub/18155/pg18155.txt",
    priority: 2,
    ocrCleanupLikely: false,
    illustrationQuality: "Strong classic illustrations.",
    notes: "Strong sequencing and problem/solution; soften scary details if adapted later.",
    tags: ["folk tale", "sequencing", "problem-solution"]
  },
  {
    id: "golden-goose-book",
    title: "The Golden Goose Book",
    author: "L. Leslie Brooke",
    band: "Late K / Grade 1",
    guidedReadingLevel: "D",
    readingLevel: "developing",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/15661",
    downloadUrl: "https://www.gutenberg.org/cache/epub/15661/pg15661.txt",
    priority: 3,
    ocrCleanupLikely: false,
    illustrationQuality: "Strong fairy-tale illustrations.",
    notes: "Collection source; ingest selected stories only after review.",
    tags: ["fairy tale", "collection", "sequencing"]
  },
  {
    id: "nursery-rhyme-book",
    title: "The Nursery Rhyme Book",
    author: "Andrew Lang",
    band: "Pre-reader",
    guidedReadingLevel: "B",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/26197",
    downloadUrl: "https://www.gutenberg.org/cache/epub/26197/pg26197.txt",
    priority: 3,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies by edition.",
    notes: "Use selected rhymes only; avoid obscure/outdated rhymes.",
    tags: ["rhyme", "phonological-awareness", "fluency"]
  },
  {
    id: "baby-days",
    title: "Baby Days",
    author: "Mary Mapes Dodge",
    band: "Pre-reader",
    guidedReadingLevel: "B",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/24734",
    downloadUrl: "https://www.gutenberg.org/cache/epub/24734/pg24734.txt",
    priority: 4,
    ocrCleanupLikely: false,
    illustrationQuality: "Mixed; selection needed.",
    notes: "Collection source; only short, school-safe pieces should be used.",
    tags: ["poetry", "family", "read-aloud"]
  },
  {
    id: "little-black-sambo-excluded",
    title: "The Story of Little Black Sambo",
    author: "Helen Bannerman",
    band: "Rejected but reviewed",
    guidedReadingLevel: "",
    readingLevel: "",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/17824",
    downloadUrl: "",
    priority: 99,
    ocrCleanupLikely: false,
    illustrationQuality: "Not suitable.",
    notes: "Rejected for culturally outdated/racist stereotypes despite public-domain status.",
    tags: ["rejected", "cultural-safety"]
  },
  {
    id: "velveteen-rabbit",
    title: "The Velveteen Rabbit",
    author: "Margery Williams",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/11757",
    downloadUrl: "https://www.gutenberg.org/cache/epub/11757/pg11757.txt",
    priority: 4,
    ocrCleanupLikely: false,
    illustrationQuality: "Good in illustrated editions.",
    notes: "Beautiful but text-heavy; read-aloud/teacher-supported only.",
    tags: ["toys", "emotional-literacy", "read-aloud"]
  },
  {
    id: "little-wizard-stories-of-oz",
    title: "Little Wizard Stories of Oz",
    author: "L. Frank Baum",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/25519",
    downloadUrl: "https://www.gutenberg.org/cache/epub/25519/pg25519.txt",
    priority: 5,
    ocrCleanupLikely: false,
    illustrationQuality: "Illustrated editions available.",
    notes: "Shorter than chapter Oz books, but still advanced for guided reading.",
    tags: ["fantasy", "read-aloud", "adventure"]
  },
  {
    id: "aesops-fables-for-children",
    title: "Aesop's Fables for Children",
    author: "Aesop",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "E",
    readingLevel: "developing",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/19994",
    downloadUrl: "https://www.gutenberg.org/cache/epub/19994/pg19994.txt",
    priority: 3,
    ocrCleanupLikely: false,
    illustrationQuality: "Useful in illustrated editions.",
    notes: "Use selected short fables; avoid harsh morals or violent details.",
    tags: ["fables", "moral", "comprehension"]
  },
  {
    id: "book-of-nonsense",
    title: "A Book of Nonsense",
    author: "Edward Lear",
    band: "Early reader",
    guidedReadingLevel: "C",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/13646",
    downloadUrl: "https://www.gutenberg.org/cache/epub/13646/pg13646.txt",
    priority: 5,
    ocrCleanupLikely: false,
    illustrationQuality: "Good line art in source editions.",
    notes: "Useful for rhyme/play, but nonsense language is not ideal for decoding assessment.",
    tags: ["rhyme", "humor", "read-aloud"]
  },
  {
    id: "english-fairy-tales",
    title: "English Fairy Tales",
    author: "Joseph Jacobs",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/7439",
    downloadUrl: "https://www.gutenberg.org/cache/epub/7439/pg7439.txt",
    priority: 5,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies by edition.",
    notes: "Collection source only; many stories need adaptation/softening.",
    tags: ["fairy tale", "collection", "read-aloud"]
  },
  {
    id: "celtic-fairy-tales",
    title: "Celtic Fairy Tales",
    author: "Joseph Jacobs",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/7885",
    downloadUrl: "https://www.gutenberg.org/cache/epub/7885/pg7885.txt",
    priority: 5,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies by edition.",
    notes: "Use only carefully reviewed selections; many are too advanced.",
    tags: ["folk tale", "collection", "read-aloud"]
  },
  {
    id: "blue-fairy-book",
    title: "The Blue Fairy Book",
    author: "Andrew Lang",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/503",
    downloadUrl: "https://www.gutenberg.org/cache/epub/503/pg503.txt",
    priority: 5,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies by edition.",
    notes: "Collection source only; select and adapt cautiously.",
    tags: ["fairy tale", "collection", "read-aloud"]
  },
  {
    id: "red-fairy-book",
    title: "The Red Fairy Book",
    author: "Andrew Lang",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/540",
    downloadUrl: "https://www.gutenberg.org/cache/epub/540/pg540.txt",
    priority: 5,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies by edition.",
    notes: "Collection source only; review for violence and complexity.",
    tags: ["fairy tale", "collection", "read-aloud"]
  },
  {
    id: "grimm-fairy-tales",
    title: "Grimm's Fairy Tales",
    author: "Jacob Grimm and Wilhelm Grimm",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/2591",
    downloadUrl: "https://www.gutenberg.org/cache/epub/2591/pg2591.txt",
    priority: 5,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies by edition.",
    notes: "Collection source only; many stories need softening/removal.",
    tags: ["fairy tale", "collection", "read-aloud"]
  },
  {
    id: "andersen-fairy-tales",
    title: "Andersen's Fairy Tales",
    author: "Hans Christian Andersen",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/1597",
    downloadUrl: "https://www.gutenberg.org/cache/epub/1597/pg1597.txt",
    priority: 5,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies by edition.",
    notes: "Use selected gentle stories only; many are advanced/sad.",
    tags: ["fairy tale", "collection", "read-aloud"]
  },
  {
    id: "just-so-stories",
    title: "Just So Stories",
    author: "Rudyard Kipling",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/2781",
    downloadUrl: "https://www.gutenberg.org/cache/epub/2781/pg2781.txt",
    priority: 6,
    ocrCleanupLikely: false,
    illustrationQuality: "Line illustrations in some editions.",
    notes: "Advanced syntax and colonial-era voice; use cautiously if at all.",
    tags: ["animals", "read-aloud", "caution"]
  },
  {
    id: "old-mother-west-wind",
    title: "Old Mother West Wind",
    author: "Thornton W. Burgess",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/2557",
    downloadUrl: "https://www.gutenberg.org/cache/epub/2557/pg2557.txt",
    priority: 4,
    ocrCleanupLikely: false,
    illustrationQuality: "Some illustrated editions available.",
    notes: "Animal nature stories; text can be long for K-2 independent reading.",
    tags: ["animals", "nature", "read-aloud"]
  },
  {
    id: "mother-west-winds-children",
    title: "Mother West Wind's Children",
    author: "Thornton W. Burgess",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/2558",
    downloadUrl: "https://www.gutenberg.org/cache/epub/2558/pg2558.txt",
    priority: 4,
    ocrCleanupLikely: false,
    illustrationQuality: "Some illustrated editions available.",
    notes: "Nature/animal comprehension; likely teacher read-aloud.",
    tags: ["animals", "nature", "comprehension"]
  },
  {
    id: "light-princess",
    title: "The Light Princess",
    author: "George MacDonald",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/697",
    downloadUrl: "https://www.gutenberg.org/cache/epub/697/pg697.txt",
    priority: 6,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies.",
    notes: "Too advanced for independent K-2, but possible read-aloud excerpt source.",
    tags: ["fairy tale", "read-aloud", "advanced"]
  },
  {
    id: "rootabaga-stories",
    title: "Rootabaga Stories",
    author: "Carl Sandburg",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/27085",
    downloadUrl: "https://www.gutenberg.org/cache/epub/27085/pg27085.txt",
    priority: 6,
    ocrCleanupLikely: false,
    illustrationQuality: "Limited.",
    notes: "Imaginative but too linguistically odd for core early reading.",
    tags: ["fantasy", "read-aloud", "caution"]
  },
  {
    id: "baldwin-primer",
    title: "The Baldwin Primer",
    author: "May Kirk",
    band: "Pre-reader",
    guidedReadingLevel: "A",
    readingLevel: "emergent",
    source: "Internet Archive",
    sourceUrl: "https://archive.org/details/baldwinprimer",
    downloadUrl: "",
    priority: 2,
    ocrCleanupLikely: true,
    illustrationQuality: "Primer scans vary; inspect before activation.",
    notes: "Early reader/primer candidate with controlled language; needs exact scan selection.",
    tags: ["primer", "phonics", "controlled-text"]
  },
  {
    id: "holton-primer",
    title: "The Holton Primer",
    author: "Martha Adelaide Holton",
    band: "Pre-reader",
    guidedReadingLevel: "A",
    readingLevel: "emergent",
    source: "Internet Archive",
    sourceUrl: "https://archive.org/search?query=title%3A%28Holton%20Primer%29",
    downloadUrl: "",
    priority: 2,
    ocrCleanupLikely: true,
    illustrationQuality: "Primer scans vary; inspect before activation.",
    notes: "Controlled primer candidate; requires scan-quality review.",
    tags: ["primer", "phonics", "controlled-text"]
  },
  {
    id: "free-treadwell-primer",
    title: "The Free and Treadwell Primer",
    author: "Harriette Taylor Treadwell and Margaret Free",
    band: "Pre-reader",
    guidedReadingLevel: "A",
    readingLevel: "emergent",
    source: "Internet Archive",
    sourceUrl: "https://archive.org/search?query=title%3A%28Free%20and%20Treadwell%20Primer%29",
    downloadUrl: "",
    priority: 2,
    ocrCleanupLikely: true,
    illustrationQuality: "Often strong for antique reader scans; verify selected copy.",
    notes: "Strong early-reader candidate; needs direct PDF selected from best scan.",
    tags: ["primer", "phonics", "school-reader"]
  },
  {
    id: "elson-primary-reader-book-one",
    title: "Elson Primary School Reader, Book One",
    author: "William H. Elson",
    band: "Late K / Grade 1",
    guidedReadingLevel: "C",
    readingLevel: "early",
    source: "Internet Archive",
    sourceUrl: "https://archive.org/search?query=title%3A%28Elson%20Primary%20School%20Reader%20Book%20One%29",
    downloadUrl: "",
    priority: 3,
    ocrCleanupLikely: true,
    illustrationQuality: "Varies by scan.",
    notes: "Public-domain school-reader source; use selected short lessons only.",
    tags: ["school-reader", "comprehension", "fluency"]
  },
  {
    id: "progressive-road-to-reading-book-one",
    title: "Progressive Road to Reading, Book One",
    author: "Georgine Burchill and William L. Ettinger",
    band: "Late K / Grade 1",
    guidedReadingLevel: "C",
    readingLevel: "early",
    source: "Internet Archive",
    sourceUrl: "https://archive.org/search?query=title%3A%28Progressive%20Road%20to%20Reading%20Book%20One%29",
    downloadUrl: "",
    priority: 3,
    ocrCleanupLikely: true,
    illustrationQuality: "Varies by scan.",
    notes: "Candidate for controlled early-reader lessons; needs direct source selected.",
    tags: ["school-reader", "phonics", "fluency"]
  },
  {
    id: "art-literature-readers-primer",
    title: "The Art-Literature Readers: Primer",
    author: "Frances Elizabeth Chutter",
    band: "Pre-reader",
    guidedReadingLevel: "B",
    readingLevel: "emergent",
    source: "Internet Archive",
    sourceUrl: "https://archive.org/search?query=title%3A%28Art-Literature%20Readers%20Primer%29",
    downloadUrl: "",
    priority: 3,
    ocrCleanupLikely: true,
    illustrationQuality: "Potentially strong, but scan selection required.",
    notes: "Candidate primer with literary selections; needs content safety review.",
    tags: ["primer", "illustrated", "vocabulary"]
  },
  {
    id: "little-lame-prince",
    title: "The Little Lame Prince",
    author: "Dinah Maria Mulock Craik",
    band: "Grade 1-2 bridge",
    guidedReadingLevel: "F",
    readingLevel: "read-aloud",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/496",
    downloadUrl: "https://www.gutenberg.org/cache/epub/496/pg496.txt",
    priority: 6,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies.",
    notes: "Advanced and dated language; review title/content carefully before classroom use.",
    tags: ["fairy tale", "read-aloud", "caution"]
  },
  {
    id: "water-babies",
    title: "The Water-Babies",
    author: "Charles Kingsley",
    band: "Rejected but reviewed",
    guidedReadingLevel: "",
    readingLevel: "",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/1018",
    downloadUrl: "",
    priority: 99,
    ocrCleanupLikely: false,
    illustrationQuality: "Illustrated editions exist.",
    notes: "Rejected for dense, dated, culturally problematic Victorian prose.",
    tags: ["rejected", "dated-content"]
  },
  {
    id: "alice-in-wonderland",
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    band: "Rejected but reviewed",
    guidedReadingLevel: "",
    readingLevel: "",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/11",
    downloadUrl: "",
    priority: 99,
    ocrCleanupLikely: false,
    illustrationQuality: "Excellent in illustrated editions.",
    notes: "Rejected for this K-2 guided-reading corpus because it is too long and linguistically complex.",
    tags: ["rejected", "too-advanced"]
  },
  {
    id: "princess-and-the-goblin",
    title: "The Princess and the Goblin",
    author: "George MacDonald",
    band: "Rejected but reviewed",
    guidedReadingLevel: "",
    readingLevel: "",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/708",
    downloadUrl: "",
    priority: 99,
    ocrCleanupLikely: false,
    illustrationQuality: "Varies.",
    notes: "Rejected for length, scary elements, and Grade 3+ complexity.",
    tags: ["rejected", "too-advanced"]
  },
  {
    id: "secret-garden",
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    band: "Rejected but reviewed",
    guidedReadingLevel: "",
    readingLevel: "",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/17396",
    downloadUrl: "",
    priority: 99,
    ocrCleanupLikely: false,
    illustrationQuality: "Some editions illustrated.",
    notes: "Rejected for length and Grade 3+ independent reading level.",
    tags: ["rejected", "too-long"]
  },
  {
    id: "little-lord-fauntleroy",
    title: "Little Lord Fauntleroy",
    author: "Frances Hodgson Burnett",
    band: "Rejected but reviewed",
    guidedReadingLevel: "",
    readingLevel: "",
    source: "Project Gutenberg",
    sourceUrl: "https://www.gutenberg.org/ebooks/479",
    downloadUrl: "",
    priority: 99,
    ocrCleanupLikely: false,
    illustrationQuality: "Some editions illustrated.",
    notes: "Rejected for length, dense prose, and dated social context.",
    tags: ["rejected", "too-long"]
  }
];

export const pilotPublicDomainBookIds = [
  "mcguffeys-eclectic-primer",
  "a-apple-pie",
  "tale-of-peter-rabbit",
  "tale-of-benjamin-bunny",
  "tale-of-squirrel-nutkin"
];
