import fs from "node:fs";
import path from "node:path";
import {
  discoverBookIds,
  generatedRegistryPath,
  getBookManifestPath,
  manifestsDir,
  parseArgs,
  publicPathFromAbsolute,
  repoRoot,
  writeJson
} from "./shared.js";

function existsPublicPath(publicPath) {
  if (!publicPath || !String(publicPath).startsWith("/")) return false;
  return fs.existsSync(path.join(repoRoot, "public", String(publicPath).slice(1)));
}

export function validateManifest(manifest) {
  const errors = [];
  const warnings = [];
  ["id", "title", "source", "readingLevel", "guidedReadingLevel", "coverImage"].forEach(field => {
    if (!manifest[field]) errors.push(`Missing field: ${field}`);
  });
  if (manifest.publicDomain !== true) errors.push("publicDomain must be true.");
  if (!existsPublicPath(manifest.coverImage)) errors.push(`Missing cover image: ${manifest.coverImage || "(blank)"}`);
  if (!Array.isArray(manifest.pages) || manifest.pages.length === 0) {
    errors.push("No pages in manifest.");
  } else {
    manifest.pages.forEach((page, index) => {
      if (page.pageNumber !== index + 1) errors.push(`Page ${index + 1}: pageNumber is not sequential.`);
      if (!page.image) errors.push(`Page ${index + 1}: missing image path.`);
      if (page.image && !existsPublicPath(page.image)) errors.push(`Page ${index + 1}: missing image file ${page.image}.`);
      if (!String(page.text || "").trim()) errors.push(`Page ${index + 1}: missing text.`);
    });
  }
  if (!manifest.source) warnings.push("Source URL/path is blank; add a stable public-domain source before activation.");
  return { errors, warnings };
}

function readManifests() {
  if (!fs.existsSync(manifestsDir)) return [];
  return fs.readdirSync(manifestsDir)
    .filter(file => file.endsWith(".json"))
    .sort()
    .map(file => {
      const manifestPath = path.join(manifestsDir, file);
      return {
        manifestPath,
        manifest: JSON.parse(fs.readFileSync(manifestPath, "utf8"))
      };
    });
}

export function writeGeneratedRegistry(validManifests) {
  const books = validManifests.map(({ manifest }) => ({
    id: manifest.id,
    title: manifest.title,
    author: manifest.author || "",
    type: manifest.type || "fiction",
    level: manifest.guidedReadingLevel || manifest.level || "A",
    guidedReadingLevel: manifest.guidedReadingLevel || manifest.level || "A",
    readingLevel: manifest.readingLevel || "early",
    source: manifest.source,
    publicDomain: true,
    coverImage: manifest.coverImage,
    tags: manifest.tags || [],
    active: manifest.active === true,
    qaStatus: manifest.qaStatus || "needs_review",
    pages: (manifest.pages || []).map(page => ({
      pageNumber: page.pageNumber,
      image: page.image,
      text: page.text,
      imageAlt: `${manifest.title} page ${page.pageNumber}`,
      pageDescription: `${manifest.title} page ${page.pageNumber}`,
      embeddedImageText: "",
      targetWords: [],
      highFrequencyWords: [],
      decodableWords: [],
      qaStatus: manifest.qaStatus || "needs_review",
      active: manifest.active === true
    }))
  }));

  fs.mkdirSync(path.dirname(generatedRegistryPath), { recursive: true });
  fs.writeFileSync(
    generatedRegistryPath,
    `// Generated by tools/public-domain/validateBook.js. Do not edit by hand.\nexport const publicDomainGuidedReadingBooks = ${JSON.stringify(books, null, 2)};\n`,
    "utf8"
  );
  return books;
}

export function validateBooks({ bookId = "", all = false } = {}) {
  const manifestPaths = all
    ? readManifests()
    : [{ manifestPath: getBookManifestPath(bookId), manifest: JSON.parse(fs.readFileSync(getBookManifestPath(bookId), "utf8")) }];

  const rows = manifestPaths.map(item => {
    const result = validateManifest(item.manifest);
    return { ...item, ...result, valid: result.errors.length === 0 };
  });

  const validRows = rows.filter(row => row.valid);
  const registeredBooks = writeGeneratedRegistry(validRows);
  const report = {
    generatedAt: new Date().toISOString(),
    rawBookFolders: discoverBookIds(),
    manifestsChecked: rows.length,
    validBooks: validRows.length,
    activeBooks: registeredBooks.filter(book => book.active).length,
    rows: rows.map(row => ({
      id: row.manifest.id,
      title: row.manifest.title,
      manifest: publicPathFromAbsolute(row.manifestPath).replace(/^\/guided-reading\//, "/guided-reading/"),
      valid: row.valid,
      active: row.manifest.active === true,
      pageCount: row.manifest.pages?.length || 0,
      errors: row.errors,
      warnings: row.warnings
    }))
  };
  writeJson(path.join(repoRoot, "docs/guided-reading/public_domain_pipeline_validation.json"), report);
  return report;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = parseArgs();
  try {
    const report = validateBooks({ bookId: args.book || "", all: args.all || !args.book });
    console.log(`Checked ${report.manifestsChecked} public-domain manifest(s).`);
    console.log(`Valid books registered: ${report.validBooks}. Active: ${report.activeBooks}.`);
    const failures = report.rows.filter(row => !row.valid);
    failures.forEach(row => {
      console.warn(`- ${row.id}: ${row.errors.join("; ")}`);
    });
    if (failures.length) process.exitCode = 1;
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}

