// Generates the FINAL audio/image production request for the v3 banks.
// Output: docs/skills-assessment-rebuild/MEDIA_REQUEST.md (+ .json) — the
// hand-off document for the external media pass (Codex). Regenerated by
// gate.mjs --write on every run, and runnable standalone from the shipped
// generated banks:  node tools/assessmentRebuild/mediaRequest.mjs
// Never edit the outputs by hand.
//
// The request covers EVERYTHING (Benjamin's rule: "everything available via
// audio too and everything should have images — even instructions should
// have audio"):
//   audio — every instruction/prompt line, every cloze sentence, every
//           passage, every single-word choice/target, every multi-word
//           phrase choice;
//   images — every image slot on image-tier items, with drawing briefs for
//            anything not already on disk.

import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./lib.mjs";

const BANKS_DIR = path.join(ROOT, "src", "data", "v3", "banks");

function slugify(text, max = 44) {
  const base = String(text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, max)
    .replace(/-+$/, "");
  // djb2 — stable short hash so trimmed slugs can never collide.
  let h = 5381;
  const s = String(text || "");
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) >>> 0;
  return `${base || "line"}-${h.toString(16).slice(0, 6)}`;
}

const AUDIO_ROOT = "/audio/assessment/v3";
const promptAudioPath = text => `${AUDIO_ROOT}/prompts/${slugify(text)}.mp3`;
const sentenceAudioPath = text => `${AUDIO_ROOT}/sentences/${slugify(text)}.mp3`;
const passageAudioPath = text => `${AUDIO_ROOT}/passages/${slugify(text)}.mp3`;
const wordAudioPath = word => `/audio/child-mode/words/${String(word).toLowerCase().replace(/[^a-z0-9']/g, "")}.mp3`;
const phraseAudioPath = text => `/audio/child-mode/phrases/${slugify(text)}.mp3`;

const existsInPublic = webPath =>
  Boolean(webPath) && fs.existsSync(path.join(ROOT, "public", String(webPath).replace(/^\//, "")));

const spokenCloze = text => String(text || "").replace(/_{2,}/g, "…");

export function buildMediaRequest(allBanks, results) {
  const skills = [];
  const prompts = new Map();   // text -> {file, has, ids:[], skills:Set}
  const sentences = new Map();
  const passages = new Map();
  const words = new Map();     // word -> {file, has, ids:[]}
  const phrases = new Map();   // phrase -> {file, has, ids:[]}
  const images = new Map();    // key -> {alt, ids:[], path, has, brief}
  const itemMap = [];          // per-item full mapping (JSON)

  const addLine = (map, text, fileFor, id, skillId) => {
    const key = String(text || "").trim();
    if (!key) return null;
    const row = map.get(key) || { file: fileFor(key), has: existsInPublic(fileFor(key)), ids: [], skills: new Set() };
    row.ids.push(id);
    row.skills.add(skillId);
    map.set(key, row);
    return row.file;
  };

  for (const [skillId, items] of allBanks) {
    const row = results?.find(r => r.skillId === skillId);
    if (results && !row?.ready) continue;
    const summary = {
      skillId, items: items.length,
      promptLines: 0, sentenceLines: 0, passageLines: 0,
      wordRecordings: 0, phraseRecordings: 0,
      imageSlots: 0, missingImages: 0
    };

    for (const item of items) {
      const mapping = { id: item.id, skillId, audio: {}, images: [] };

      // 1. Instruction/prompt audio — EVERY item, verbatim spokenPrompt.
      const promptText = spokenCloze(item.spokenPrompt || item.prompt);
      mapping.audio.prompt = { text: promptText, file: addLine(prompts, promptText, promptAudioPath, item.id, skillId) };
      summary.promptLines++;

      // 2. Sentence read-aloud (cloze frames voiced with a pause at the blank).
      if (item.sentence) {
        const sentenceText = spokenCloze(item.sentence);
        mapping.audio.sentence = { text: sentenceText, file: addLine(sentences, sentenceText, sentenceAudioPath, item.id, skillId) };
        summary.sentenceLines++;
      }

      // 3. Passage read-aloud.
      if (item.passage) {
        mapping.audio.passage = { text: item.passage, file: addLine(passages, item.passage, passageAudioPath, item.id, skillId) };
        summary.passageLines++;
      }

      // 4. Choice + target audio — single words to the shared word pool,
      //    multi-word choices (phrases, homonym sentences) to the phrase pool.
      const choiceTexts = [
        ...(item.imageCards || []).map(c => c.word),
        ...(item.choices || []),
        ...(item.targetWord && !/[\/_]/.test(item.targetWord) ? [item.targetWord] : [])
      ].map(v => String(v).trim()).filter(Boolean);
      mapping.audio.choices = [];
      for (const text of new Set(choiceTexts)) {
        if (/^[a-z']+$/i.test(text)) {
          const file = wordAudioPath(text);
          const w = words.get(text.toLowerCase()) || { file, has: existsInPublic(file), ids: [] };
          w.ids.push(item.id);
          words.set(text.toLowerCase(), w);
          mapping.audio.choices.push({ text, file, kind: "word" });
          summary.wordRecordings++;
        } else {
          const file = addLine(phrases, text, phraseAudioPath, item.id, skillId);
          mapping.audio.choices.push({ text, file, kind: "phrase" });
          summary.phraseRecordings++;
        }
      }

      // 5. Images — every card and target slot on image-tier items.
      for (const card of (item.imageCards || [])) {
        const has = existsInPublic(card.image);
        const key = `card:${card.word}`;
        const img = images.get(key) || {
          alt: card.imageAlt || card.word, ids: [], path: card.image || `/images/objects/${slugify(card.word, 30)}.png`, has,
          brief: `Single clear "${card.word}" on a plain warm background — instantly nameable by a 5-year-old, no text, no other objects.`
        };
        img.ids.push(item.id); img.has = img.has || has;
        images.set(key, img);
        mapping.images.push({ word: card.word, path: img.path, exists: img.has });
        summary.imageSlots++;
        if (!has) summary.missingImages++;
      }
      // Target-image slot ONLY when the item actually renders a target image:
      // card-based items carry a targetWord too, but their art lives on the
      // cards — requesting a second target image for them is a phantom slot.
      const mediaTier = item.mediaTier || item.media;
      if (mediaTier === "image-required" && item.imagePath && !(item.imageCards || []).length) {
        const has = existsInPublic(item.imagePath);
        const key = `target:${item.targetWord || item.imagePath}`;
        const img = images.get(key) || {
          alt: item.imageAlt || item.targetWord || "", ids: [], path: item.imagePath || `/images/objects/${slugify(item.targetWord || item.id, 30)}.png`, has,
          brief: item.imageAlt && item.imageAlt !== item.targetWord
            ? `Scene: ${item.imageAlt} — one unambiguous spatial/semantic reading, no text.`
            : `Single clear "${item.targetWord}" — instantly nameable, no text, no competing objects.`
        };
        img.ids.push(item.id); img.has = img.has || has;
        images.set(key, img);
        mapping.images.push({ word: item.targetWord || "", path: img.path, exists: img.has });
        summary.imageSlots++;
        if (!has) summary.missingImages++;
      }

      itemMap.push(mapping);
    }
    skills.push(summary);
  }

  const missingImages = [...images.entries()].filter(([, v]) => !v.has);
  const missingWords = [...words.entries()].filter(([, v]) => !v.has);
  const missingPhrases = [...phrases.entries()].filter(([, v]) => !v.has);
  const missingPrompts = [...prompts.entries()].filter(([, v]) => !v.has);
  const missingSentences = [...sentences.entries()].filter(([, v]) => !v.has);
  const missingPassages = [...passages.entries()].filter(([, v]) => !v.has);

  const json = {
    generatedAt: new Date().toISOString(),
    audioSpec: {
      voice: "One consistent child-friendly voice for the whole set (warm, natural, clear UK-neutral accent, ~150 wpm, no character voices).",
      format: "mp3, 44.1 kHz, mono, normalized to -16 LUFS integrated, < 1 dB true peak, no leading/trailing silence beyond 150 ms.",
      style: "Natural full sentences exactly as scripted. Cloze blanks are voiced as a short beat of silence (the … marks), never the word 'blank'. No isolated robotic phonemes — letter-sound lines say the sound naturally.",
      wiring: "Wire prompts/sentences/passages via audioPreferenceManifest keyed by the exact script text; words land in the existing /audio/child-mode/words pool; phrases in /audio/child-mode/phrases."
    },
    imageSpec: {
      style: "Flat, warm, friendly illustration matching public/images/assessment house style. 512x512 minimum, png or webp. No embedded text, no letters, no numbers.",
      law: "Answer-neutral: an image must never reveal the answer of the item it appears in (see AUTHORING_STANDARDS.md). Scene images must have exactly ONE unambiguous reading of the target relation."
    },
    skills,
    prompts: [...prompts.entries()].map(([text, v]) => ({ text, file: v.file, exists: v.has, usedBy: v.ids.length, skills: [...v.skills] })),
    sentences: [...sentences.entries()].map(([text, v]) => ({ text, file: v.file, exists: v.has, usedBy: v.ids.length, skills: [...v.skills] })),
    passages: [...passages.entries()].map(([text, v]) => ({ text, file: v.file, exists: v.has, usedBy: v.ids.length, skills: [...v.skills] })),
    words: [...words.entries()].map(([word, v]) => ({ word, file: v.file, exists: v.has, usedBy: v.ids.length })),
    phrases: [...phrases.entries()].map(([text, v]) => ({ text, file: v.file, exists: v.has, usedBy: v.ids.length })),
    images: [...images.entries()].map(([key, v]) => ({ key, alt: v.alt, path: v.path, exists: v.has, usedBy: v.ids.length, brief: v.brief })),
    items: itemMap
  };

  const outDir = path.join(ROOT, "docs", "skills-assessment-rebuild");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "MEDIA_REQUEST.json"), JSON.stringify(json, null, 1));

  const fmtLine = ([text, v]) => `| ${v.file} | ${text.replace(/\|/g, "/")} | ${v.ids.length} |`;
  const md = [
    `# FINAL media production request — Skills assessments v3 (all 30 skills)`,
    ``,
    `Generated ${json.generatedAt} from the shipped v3 banks. Regenerate with \`node tools/assessmentRebuild/mediaRequest.mjs\` after any bank change — never edit by hand. Machine-readable copy with the FULL per-item mapping: \`MEDIA_REQUEST.json\` (\`items[]\` maps every question id to its exact audio files and image paths).`,
    ``,
    `## Audio spec (applies to every recording)`,
    ``,
    `- **Voice:** ${json.audioSpec.voice}`,
    `- **Format:** ${json.audioSpec.format}`,
    `- **Style:** ${json.audioSpec.style}`,
    `- **Wiring:** ${json.audioSpec.wiring}`,
    ``,
    `## Image spec (applies to every illustration)`,
    ``,
    `- **Style:** ${json.imageSpec.style}`,
    `- **Law:** ${json.imageSpec.law}`,
    ``,
    `## Volume summary`,
    ``,
    `| Asset class | Unique assets | Still missing |`,
    `|---|---|---|`,
    `| Instruction/prompt lines | ${json.prompts.length} | ${missingPrompts.length} |`,
    `| Sentence read-alouds | ${json.sentences.length} | ${missingSentences.length} |`,
    `| Passage read-alouds | ${json.passages.length} | ${missingPassages.length} |`,
    `| Single-word recordings | ${json.words.length} | ${missingWords.length} |`,
    `| Phrase recordings | ${json.phrases.length} | ${missingPhrases.length} |`,
    `| Image slots | ${json.images.length} | ${missingImages.length} |`,
    ``,
    `## Per-skill volume`,
    ``,
    `| Skill | Items | Prompts | Sentences | Passages | Words | Phrases | Image slots | Missing images |`,
    `|---|---|---|---|---|---|---|---|---|`,
    ...skills.map(s => `| ${s.skillId} | ${s.items} | ${s.promptLines} | ${s.sentenceLines} | ${s.passageLines} | ${s.wordRecordings} | ${s.phraseRecordings} | ${s.imageSlots} | ${s.missingImages} |`),
    ``,
    `## 1. Instruction/prompt recordings — record each line verbatim`,
    ``,
    `| File | Script (read exactly) | Used by |`,
    `|---|---|---|`,
    ...[...prompts.entries()].map(fmtLine),
    ``,
    `## 2. Sentence read-alouds — voice the … as a short pause`,
    ``,
    `| File | Script | Used by |`,
    `|---|---|---|`,
    ...[...sentences.entries()].map(fmtLine),
    ``,
    `## 3. Passage read-alouds`,
    ``,
    `| File | Script | Used by |`,
    `|---|---|---|`,
    ...[...passages.entries()].map(fmtLine),
    ``,
    `## 4. Single-word recordings (shared pool /audio/child-mode/words)`,
    ``,
    `${missingWords.length} of ${json.words.length} are missing — record the missing set below; the rest already exist in the pool.`,
    ``,
    `| File | Word | Used by |`,
    `|---|---|---|`,
    ...missingWords.map(([word, v]) => `| ${v.file} | ${word} | ${v.ids.length} |`),
    ``,
    `## 5. Phrase recordings (shared pool /audio/child-mode/phrases)`,
    ``,
    `| File | Script | Used by |`,
    `|---|---|---|`,
    ...[...phrases.entries()].filter(([, v]) => !v.has).map(fmtLine),
    ``,
    `## 6. Images — missing slots with drawing briefs`,
    ``,
    ...(missingImages.length
      ? [
          `| Path | Alt text | Brief | Used by |`,
          `|---|---|---|---|`,
          ...missingImages.map(([key, v]) => `| ${v.path} | ${v.alt.replace(/\|/g, "/")} | ${v.brief.replace(/\|/g, "/")} | ${v.ids.length} |`)
        ]
      : [`All ${json.images.length} image slots resolve to existing art on disk. Any NEW art must follow the image spec above.`]),
    ``,
    `## Delivery`,
    ``,
    `1. Land audio under \`public/audio/…\` and images under \`public/images/…\` at the exact paths above.`,
    `2. Wire prompt/sentence/passage audio in \`audioPreferenceManifest\` keyed by script text; word/phrase pools are picked up by the existing resolvers.`,
    `3. Run \`node tools/assessmentRebuild/mediaRequest.mjs\` — the missing counts above must all reach 0.`,
    `4. Run the media QA pass; nothing ships with \`qaStatus\` below approved.`,
    ``
  ].join("\n");
  fs.writeFileSync(path.join(outDir, "MEDIA_REQUEST.md"), md);
  return json;
}

// Standalone mode: rebuild the request straight from the shipped generated
// banks (no 20-minute gate run needed).
const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname);
if (isMain) {
  const allBanks = new Map();
  for (const file of fs.readdirSync(BANKS_DIR)) {
    if (!file.endsWith(".v3.generated.js")) continue;
    const skillId = file.replace(".v3.generated.js", "");
    const module = await import(path.join(BANKS_DIR, file));
    allBanks.set(skillId, module.questions || []);
  }
  const json = buildMediaRequest(allBanks, null);
  console.log(`MEDIA_REQUEST regenerated: ${json.prompts.length} prompts, ${json.sentences.length} sentences, ${json.passages.length} passages, ${json.words.length} words, ${json.phrases.length} phrases, ${json.images.length} image slots.`);
}
