// Generates the standing audio/image production request for the v3 banks.
// Output: docs/skills-assessment-rebuild/MEDIA_REQUEST.md (+ .json) — the
// hand-off document for the external media pass (Codex). Regenerated by
// gate.mjs --write on every run, so it always matches the shipped banks.

import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./lib.mjs";

export function buildMediaRequest(allBanks, results) {
  const skills = [];
  const audioLines = new Map(); // text -> {kind, ids}
  const wordAudio = new Map();  // word -> ids
  const images = new Map();     // word -> {alt, ids, has}

  const addAudio = (map, key, kind, id) => {
    if (!key) return;
    const row = map.get(key) || { kind, ids: [] };
    row.ids.push(id);
    map.set(key, row);
  };

  for (const [skillId, items] of allBanks) {
    const row = results.find(r => r.skillId === skillId);
    if (!row?.ready) continue;
    const summary = { skillId, items: items.length, instructionLines: 0, wordRecordings: 0, imageSlots: 0, missingImages: 0 };
    for (const item of items) {
      // 1. Instruction/prompt audio — EVERY item's spoken prompt gets a recording.
      addAudio(audioLines, item.spokenPrompt || item.prompt, "instruction", item.id);
      summary.instructionLines++;
      // Sentences and passages read aloud for support / listen formats.
      if (item.sentence) addAudio(audioLines, item.sentence.replace(/___/g, "…"), "sentence", item.id);
      if (item.passage) addAudio(audioLines, item.passage, "passage", item.id);
      // 2. Word audio — every choice word and target word.
      const words = new Set([
        ...(item.imageCards || []).map(c => c.word),
        ...((item.choices || []).filter(c => /^[a-z']+$/i.test(String(c)))),
        ...(item.targetWord ? [item.targetWord] : [])
      ]);
      for (const word of words) {
        const list = wordAudio.get(word) || [];
        list.push(item.id);
        wordAudio.set(word, list);
        summary.wordRecordings++;
      }
      // 3. Images — every card + target slot, with existence check.
      for (const card of (item.imageCards || [])) {
        const has = card.image ? fs.existsSync(path.join(ROOT, "public", String(card.image).replace(/^\//, ""))) : false;
        const rowImg = images.get(card.word) || { alt: card.imageAlt || card.word, ids: [], has };
        rowImg.ids.push(item.id);
        rowImg.has = rowImg.has || has;
        images.set(card.word, rowImg);
        summary.imageSlots++;
        if (!has) summary.missingImages++;
      }
      if (item.targetWord && item.imagePath) {
        const has = fs.existsSync(path.join(ROOT, "public", String(item.imagePath).replace(/^\//, "")));
        const rowImg = images.get(item.targetWord) || { alt: item.imageAlt || item.targetWord, ids: [], has };
        rowImg.ids.push(item.id);
        rowImg.has = rowImg.has || has;
        images.set(item.targetWord, rowImg);
        summary.imageSlots++;
        if (!has) summary.missingImages++;
      }
    }
    skills.push(summary);
  }

  const missingImages = [...images.entries()].filter(([, v]) => !v.has);
  const json = {
    generatedAt: new Date().toISOString(),
    spec: "Every prompt/instruction, sentence, passage, and choice word needs recorded human audio (child-friendly UK/neutral voice, natural pace, no isolated phonemes). Every image slot needs a clean flat-style illustration matching /images/assessment house style, no embedded text, answer-neutral.",
    skills,
    instructionAudio: [...audioLines.entries()].map(([text, v]) => ({ text, kind: v.kind, usedBy: v.ids.length })),
    wordAudio: [...wordAudio.entries()].map(([word, ids]) => ({ word, usedBy: ids.length })),
    images: [...images.entries()].map(([word, v]) => ({ word, alt: v.alt, exists: v.has, usedBy: v.ids.length }))
  };

  const outDir = path.join(ROOT, "docs", "skills-assessment-rebuild");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "MEDIA_REQUEST.json"), JSON.stringify(json, null, 1));

  const md = [
    `# Media production request — Skills assessments v3`,
    ``,
    `Generated ${json.generatedAt} by \`tools/assessmentRebuild/gate.mjs\`. Regenerate after any bank change — never edit by hand. Machine-readable copy: \`MEDIA_REQUEST.json\`.`,
    ``,
    `## What is needed (spec for Codex)`,
    ``,
    `1. **Audio for everything.** Recorded human audio (or approved premium TTS), child-friendly voice, natural full sentences, no isolated phonemes, no robotic notation:`,
    `   - **Instruction/prompt audio** for every item (\`spokenPrompt\`) — including instructions, ${json.instructionAudio.filter(a => a.kind === "instruction").length} unique lines.`,
    `   - **Sentence audio** (${json.instructionAudio.filter(a => a.kind === "sentence").length} lines) and **passage read-aloud** (${json.instructionAudio.filter(a => a.kind === "passage").length} passages).`,
    `   - **Word audio** for every choice/target word: ${json.wordAudio.length} unique words.`,
    `   - File convention: follow \`public/audio/child-mode/\` existing layout; wire via \`audioPreferenceManifest\`.`,
    `2. **Images for everything.** ${json.images.length} unique word/scene slots; ${missingImages.length} have NO existing asset (listed in the JSON with alt text). House style: flat, warm, no embedded text, answer-neutral (an image must never reveal the answer of the item it appears in — see docs/skills-assessment-rebuild/AUTHORING_STANDARDS.md).`,
    `3. **Delivery.** Land assets under \`public/\`, register them (media registry / audio manifest), then run \`npm run check:audit:assessment-rebuild -- --write\` — items tagged \`mediaTier: "audio-required"\` unlock automatically once their audio resolves.`,
    ``,
    `## Per-skill volume`,
    ``,
    `| Skill | Items | Instruction lines | Word recordings | Image slots | Missing images |`,
    `|---|---|---|---|---|---|`,
    ...skills.map(s => `| ${s.skillId} | ${s.items} | ${s.instructionLines} | ${s.wordRecordings} | ${s.imageSlots} | ${s.missingImages} |`),
    ``,
    `## Missing images (top of queue)`,
    ``,
    ...missingImages.slice(0, 60).map(([word, v]) => `- \`${word}\` — alt: "${v.alt}" (used by ${v.ids.length} item${v.ids.length === 1 ? "" : "s"})`),
    missingImages.length > 60 ? `- …and ${missingImages.length - 60} more (see JSON)` : ``
  ].join("\n");
  fs.writeFileSync(path.join(outDir, "MEDIA_REQUEST.md"), md);
}
