// Build the durable exact-pixel rejection map from the severe active-v3 audit.
//
// Usage:
//   node tools/assessmentRebuild/recordAssessmentMediaAuditRejections.mjs
//   node tools/assessmentRebuild/recordAssessmentMediaAuditRejections.mjs --check
//
// The TSV is historical review evidence. Its rejected hashes remain useful
// after a path is repaired, because the gate must still prevent the old bitmap
// from returning under either its former path or a different filename.

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const SOURCE = path.join(
  ROOT,
  "docs",
  "assessment-media",
  "active-v3-rejected-image-evidence.tsv"
);
const DESTINATION = path.join(
  ROOT,
  "src",
  "content",
  "assessments",
  "v3",
  "assessmentMediaAuditRejectedHashes.generated.js"
);
const VERSION = "active-v3-severe-audit-2026-08-31-v4";
const EXPECTED_REJECTION_COUNT = 320;
const EXPECTED_HEADER = "asset_path\tsha256\tsource_scope\treason_code\treason";
const checkOnly = process.argv.includes("--check");

const fail = message => {
  throw new Error(`Assessment media audit rejections: ${message}`);
};

const sourceText = fs.readFileSync(SOURCE, "utf8").trim();
const [header, ...lines] = sourceText.split("\n");
if (header !== EXPECTED_HEADER) fail("unexpected evidence header");
if (lines.length !== EXPECTED_REJECTION_COUNT) {
  fail(`expected ${EXPECTED_REJECTION_COUNT} rejected paths, received ${lines.length}`);
}

const rejectedByHash = {};
const seenPaths = new Set();

for (const [index, line] of lines.entries()) {
  const [assetPath, sha256, sourceScope, reasonCode, reason, ...extra] = line.split("\t");
  if (extra.length) fail(`row ${index + 2} contains an unexpected tab`);
  if (!/^\/images\/assessment\/.+\.webp$/.test(assetPath || "")) {
    fail(`row ${index + 2} has an invalid assessment image path`);
  }
  if (!/^[a-f0-9]{64}$/.test(sha256 || "")) fail(`row ${index + 2} has an invalid SHA-256`);
  if (!sourceScope || !reasonCode || !reason) fail(`row ${index + 2} lacks review evidence`);
  if (seenPaths.has(assetPath)) fail(`duplicate path ${assetPath}`);
  if (rejectedByHash[sha256]) fail(`duplicate rejected hash ${sha256}`);

  seenPaths.add(assetPath);
  rejectedByHash[sha256] = {
    path: assetPath,
    reason,
    reasonCode,
    sourceScope,
    reviewVersion: VERSION
  };
}

const output = "// GENERATED by tools/assessmentRebuild/recordAssessmentMediaAuditRejections.mjs\n"
  + `export const ASSESSMENT_MEDIA_AUDIT_REVIEW_VERSION = ${JSON.stringify(VERSION)};\n`
  + `export const ASSESSMENT_MEDIA_AUDIT_REJECTED_HASHES = Object.freeze(${JSON.stringify(rejectedByHash, null, 2)});\n`;

if (checkOnly) {
  if (!fs.existsSync(DESTINATION) || fs.readFileSync(DESTINATION, "utf8") !== output) {
    fail("generated rejection map is stale; run the recorder without --check");
  }
  console.log(`Verified ${lines.length} severe-audit image rejections.`);
} else {
  fs.writeFileSync(DESTINATION, output);
  console.log(`Recorded ${lines.length} severe-audit image rejections.`);
}
