// Synchronise the exact media-path evidence for one authored v3 skill.
//
// Usage:
//   node tools/assessmentRebuild/syncAssessmentItemMediaDecisions.mjs --skill antonyms_synonyms
//
// This does not approve new art. Every resulting path must already have a
// direct visual decision in the composite assessmentImageStyleDecisions.js.

import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import {
  AUTHORING_DIR,
  ROOT,
  expandBank,
  makeImageResolver,
  syncItemMediaDecision
} from "./lib.mjs";
import { skillBlueprints } from "../../src/content/blueprints/skillBlueprints.js";
import { ASSESSMENT_IMAGE_STYLE_DECISIONS } from "../../src/content/assessments/v3/assessmentImageStyleDecisions.js";
import { ASSESSMENT_ITEM_MEDIA_DECISIONS } from "../../src/content/assessments/v3/assessmentItemMediaDecisions.generated.js";

const args = process.argv.slice(2);
const skillIndex = args.indexOf("--skill");
const skillId = skillIndex >= 0 ? args[skillIndex + 1] : "";

if (!skillId || !skillBlueprints[skillId]) {
  throw new Error("Pass a valid --skill <skillId>");
}

const sourcePath = path.join(AUTHORING_DIR, `${skillId}.mjs`);
if (!fs.existsSync(sourcePath)) throw new Error(`Missing authored source: ${sourcePath}`);

const { default: source } = await import(pathToFileURL(sourcePath));
const items = expandBank(
  source,
  skillBlueprints[skillId],
  source.imageResolver || makeImageResolver()
);

const imagePaths = item => [...new Set([
  item.imagePath,
  item.imageUrl,
  item.targetImage,
  item.targetImagePath,
  ...(item.imageCards || []).flatMap(card => [card.image, card.imagePath]),
  ...(item.sequenceCards || []).flatMap(card => [card.image, card.imagePath])
].filter(Boolean))];

const activeItemIds = new Set(items.map(item => item.id));
const skillPrefix = `lp3.${skillId}.`;
const next = Object.fromEntries(Object.entries(ASSESSMENT_ITEM_MEDIA_DECISIONS).filter(([itemId]) =>
  !itemId.startsWith(skillPrefix) || activeItemIds.has(itemId)
));
for (const [index, item] of items.entries()) {
  const decision = next[item.id];
  const paths = imagePaths(item);
  next[item.id] = syncItemMediaDecision({
    item,
    authoredItem: source.items[index],
    decision,
    actualPaths: paths,
    styleDecisions: ASSESSMENT_IMAGE_STYLE_DECISIONS
  });
}

const destination = path.join(
  ROOT,
  "src/content/assessments/v3/assessmentItemMediaDecisions.generated.js"
);
const banner = `// GENERATED by tools/assessmentRebuild/syncAssessmentItemMediaDecisions.mjs\n`;
fs.writeFileSync(
  destination,
  `${banner}export const ASSESSMENT_ITEM_MEDIA_DECISIONS = Object.freeze(${JSON.stringify(next, null, 2)});\n`
);

console.log(`Synchronised ${items.length} ${skillId} media decisions; ${Object.keys(next).length} active decisions retained.`);
