// Synchronise the exact media-path evidence for one authored v3 skill.
//
// Usage:
//   node tools/assessmentRebuild/syncAssessmentItemMediaDecisions.mjs --skill antonyms_synonyms
//
// This does not approve new art. Every resulting path must already have a
// direct visual decision in assessmentImageStyleDecisions.generated.js.

import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import {
  AUTHORING_DIR,
  ROOT,
  expandBank,
  makeImageResolver
} from "./lib.mjs";
import { skillBlueprints } from "../../src/content/blueprints/skillBlueprints.js";
import { ASSESSMENT_IMAGE_STYLE_DECISIONS } from "../../src/content/assessments/v3/assessmentImageStyleDecisions.generated.js";
import { ASSESSMENT_ITEM_MEDIA_DECISIONS } from "../../src/content/assessments/v3/assessmentItemMediaDecisions.generated.js";

const args = process.argv.slice(2);
const skillIndex = args.indexOf("--skill");
const skillId = skillIndex >= 0 ? args[skillIndex + 1] : "";

if (!skillId || !skillBlueprints[skillId]) {
  throw new Error("Pass a valid --skill <skillId>");
}

const sourcePath = path.join(AUTHORING_DIR, `${skillId}.mjs`);
if (!fs.existsSync(sourcePath)) throw new Error(`Missing authored source: ${sourcePath}`);

const { default: source } = await import(pathToFileURL(sourcePath));
const items = expandBank(
  source,
  skillBlueprints[skillId],
  source.imageResolver || makeImageResolver()
);

const imagePaths = item => [...new Set([
  item.imagePath,
  item.imageUrl,
  item.targetImage,
  item.targetImagePath,
  ...(item.imageCards || []).flatMap(card => [card.image, card.imagePath]),
  ...(item.sequenceCards || []).flatMap(card => [card.image, card.imagePath])
].filter(Boolean))];

const next = { ...ASSESSMENT_ITEM_MEDIA_DECISIONS };
for (const item of items) {
  const decision = next[item.id];
  if (!decision) throw new Error(`${item.id} has no reviewed media decision to synchronise`);
  const paths = imagePaths(item);
  if (!paths.length) throw new Error(`${item.id} expands without meaningful media`);
  for (const assetPath of paths) {
    if (!ASSESSMENT_IMAGE_STYLE_DECISIONS[assetPath]) {
      throw new Error(`${item.id} uses art without direct visual approval: ${assetPath}`);
    }
  }
  next[item.id] = { ...decision, paths };
}

const destination = path.join(
  ROOT,
  "src/content/assessments/v3/assessmentItemMediaDecisions.generated.js"
);
const banner = `// GENERATED by tools/assessmentRebuild/syncAssessmentItemMediaDecisions.mjs\n`;
fs.writeFileSync(
  destination,
  `${banner}export const ASSESSMENT_ITEM_MEDIA_DECISIONS = Object.freeze(${JSON.stringify(next, null, 2)});\n`
);

console.log(`Synchronised ${items.length} ${skillId} media decisions; ${Object.keys(next).length} total retained.`);
