export const MATHS_STAGE_CHOICES_BY_SKILL = Object.freeze({
  "F-N-SEQ-20": Object.freeze({ retrieve: ["I started at a number I knew", "I moved one step for each next number"], notice: ["I found the number before the gap", "I checked the number after the gap"], model: ["I kept every number in order", "I changed only the missing place"], explain: ["I can point to before, missing and after", "I can read the path forwards and backwards"] }),
  "F-N-COUNT-10": Object.freeze({ retrieve: ["I moved each counter once", "I matched one number word to each counter"], notice: ["I kept counted and uncounted counters apart", "I used the last number to name the total"], model: ["I changed the arrangement, not the amount", "I checked that no counter was missed or counted twice"], explain: ["I can show where counting starts", "I can explain why the last number tells how many"] }),
  "F-N-COUNT-20": Object.freeze({ retrieve: ["I made one complete ten first", "I counted on from ten for the extras"], notice: ["I saw ten and some more", "I kept the full ten separate from the extras"], model: ["The complete ten stayed the same", "Only the number of extras changed"], explain: ["I can point to the ten and the extras", "I can say ten and some more makes the total"] }),
  "F-N-SUBITISE-5": Object.freeze({ retrieve: ["I saw a familiar part without counting each dot", "I joined smaller parts to name the whole"], notice: ["I saw two smaller parts", "I saw empty spaces as well as filled spaces"], model: ["The dots moved but the amount stayed the same", "Different patterns showed the same whole"], explain: ["I can point to the smaller parts I saw", "I can recombine the parts to name the whole"] }),
  "F-N-MATCH": Object.freeze({ retrieve: ["I said the numeral as a number word", "I built one object for each count"], notice: ["The numeral and collection name the same amount", "I checked the collection instead of guessing from its shape"], model: ["I changed the collection until it matched", "I kept the numeral fixed while I built"], explain: ["I can connect the numeral, number word and collection", "I can prove the collection matches the numeral"] }),
  "F-N-COMPARE": Object.freeze({ retrieve: ["I paired one object from each group", "I lined both groups up from the same start"], notice: ["I looked for objects left without a partner", "I ignored spacing and compared the amounts"], model: ["I changed the spacing, not the quantity", "The unmatched objects proved which group had more"], explain: ["I can show every one-to-one pair", "I can use the leftovers to say more, fewer or same"] }),
  "F-N-PART-5": Object.freeze({ retrieve: ["I kept the whole fixed at five", "I named both parts before recombining them"], notice: ["The parts changed but the whole stayed five", "I checked that every one of the five spaces was used"], model: ["Moving one changed both parts", "Recombining the parts still made five"], explain: ["I can point to each part and the whole five", "I can show a different split that still makes five"] }),
  "F-N-PART-10": Object.freeze({ retrieve: ["I kept the whole fixed at ten", "I used the full ten-frame to check the whole"], notice: ["The two colours showed complementary parts", "The empty spaces showed the missing part"], model: ["Changing one part changed its partner", "Every split still filled exactly ten spaces"], explain: ["I can name both parts and the whole ten", "I can prove the parts fill the ten-frame"] })
});

export function mathsLessonStageChoices(skillId, stage) {
  return MATHS_STAGE_CHOICES_BY_SKILL[skillId]?.[stage] || [];
}
