import { useEffect, useState } from "react";
import { listPressWork } from "../../../data/decodablePress/decodablePress.js";
import { PressProjectDialog } from "./PressProjectDialog.jsx";
import { PressReviewDrawer } from "./PressReviewDrawer.jsx";
import "../../../styles/decodable-press.css";

export function PressReviewQueuePage({ client, classId, cycleId, students, onClose }) {
  const [data,setData]=useState({projects:[],books:[]}); const [status,setStatus]=useState(client?"loading":"unavailable"); const [message,setMessage]=useState(client?"":"Private Press projects are not connected in this preview."); const [creating,setCreating]=useState(false); const [reviewing,setReviewing]=useState(null);
  async function load(){if(!client){setMessage("Private Press projects are not connected in this preview.");setStatus("unavailable");return}try{const next=await listPressWork(client,classId);setData({projects:next.projects,books:next.books});setMessage("");setStatus("ready");}catch{setMessage("Press work could not be loaded. Try again without leaving this page.");setStatus("error");}}
  useEffect(()=>{if(!client)return;listPressWork(client,classId).then(next=>{setData({projects:next.projects,books:next.books});setMessage("");setStatus("ready");}).catch(()=>{setMessage("Press work could not be loaded. Try again without leaving this page.");setStatus("error");});},[classId,client]);
  const submitted=data.books.filter(book=>book.status==="submitted");
  return <main className="press-teacher"><header><div><p>Class Decodable Press</p><h1>Projects and exact-revision review</h1><span>Student drafts stay private. Publication requires your review of the exact submitted revision.</span></div><button type="button" onClick={onClose}>Back to Resources</button></header><div className="press-teacher-actions"><button type="button" onClick={()=>setCreating(true)}>Create project</button><button type="button" disabled={status==="loading"} onClick={load}>Refresh queue</button></div>{message&&<p role={status==="error"?"alert":"status"}>{message}</p>}<section><h2>Waiting for review <span>{submitted.length}</span></h2>{status==="loading"?<p aria-busy="true">Loading private submissions…</p>:!submitted.length?<p>No exact revisions are waiting.</p>:<div className="press-review-list">{submitted.map(book=><article key={book.id}><div><span>Revision {book.revision}</span><h3>{book.title}</h3><p>{book.student_name} · {book.validation?.pages?.flatMap(page=>page.needsReview||[]).length||0} word requests</p></div><button type="button" onClick={()=>setReviewing(book)}>Review exact version</button></article>)}</div>}</section><section><h2>Projects</h2><div className="press-card-grid">{data.projects.map(project=><article key={project.id}><span>{project.status}</span><h3>{project.title}</h3><p>{project.allow_class_library?"Class-library approval available":"Private approval only"}</p></article>)}</div></section><section><h2>All student books</h2><div className="press-card-grid">{data.books.map(book=><article key={book.id}><span>{book.status.replaceAll("_"," ")}</span><h3>{book.title}</h3><p>{book.student_name} · revision {book.revision||"not saved"}</p></article>)}</div></section>{creating&&<PressProjectDialog client={client} classId={classId} cycleId={cycleId} students={students} onClose={()=>setCreating(false)} onCreated={load}/>} {reviewing&&<PressReviewDrawer client={client} book={reviewing} project={data.projects.find(project=>project.id===reviewing.project_id)} onClose={()=>setReviewing(null)} onReviewed={load}/>}</main>;
}
