import { expect, test } from '@playwright/test';

test('compiled MAP practice renders promptly on a cold tablet profile without importing the full question stock',async({page,browserName},info)=>{
  test.skip(!process.env.LP_PRODUCTION_MAP_PREVIEW || browserName!=='chromium','Requires the compiled private MAP preview and Chromium network/CPU controls.');
  test.setTimeout(90000);
  await page.setViewportSize({width:1024,height:768});
  const protocol=await page.context().newCDPSession(page);
  await protocol.send('Network.enable');
  await protocol.send('Network.setCacheDisabled',{cacheDisabled:true});
  await protocol.send('Network.emulateNetworkConditions',{offline:false,latency:100,downloadThroughput:384*1024,uploadThroughput:128*1024});
  await protocol.send('Emulation.setCPUThrottlingRate',{rate:4});
  const began=Date.now();await page.goto('/tests/fixtures/literacy-practice.html');
  await expect(page.locator('[data-child-primary-action]')).toBeVisible();
  const homeMs=Date.now()-began,start=Date.now();await page.locator('[data-child-primary-action]').click();
  await expect(page.locator('.skills-practice-play')).toBeVisible();
  const firstRenderMs=Date.now()-start;
  await expect.poll(()=>page.locator('img[data-assessment-media-kind="evidence"]').evaluateAll(images=>images.length>0&&images.every(image=>image.complete&&image.naturalWidth>0))).toBe(true);
  const firstPicturesMs=Date.now()-start;
  const first=await page.evaluate(()=>window.__literacy.session());
  expect(first.questionIds).toHaveLength(40);expect(first.responseEpisode.question.skillId).toBe('initial_sounds');
  expect(first.responseEpisode.question.formatType).toBe('FIRST_SOUND');
  await expect(page.locator('[data-skills-practice-ready="true"]')).toBeVisible();
  const audioDoneMs=Date.now()-start;
  const before=await page.evaluate(()=>performance.getEntriesByType('resource').map(entry=>({name:entry.name,bytes:entry.encodedBodySize,ms:entry.duration})));
  expect(before.filter(entry=>/literacyReferenceBank|literacy-reference\/questions/.test(entry.name))).toHaveLength(0);
  expect(before.filter(entry=>/questAudio|guided-reading/.test(entry.name))).toHaveLength(0);
  const question=first.responseEpisode.question;
  const values=question.answerOptions.map(option=>String(option.value)),wrong=values.findIndex(value=>value!==String(question.answer));
  expect(wrong).toBeGreaterThanOrEqual(0);
  const choices=page.locator('.assessment-answer-card, .ixl-answer-button, .initial-sound-image-button');
  expect(await choices.count()).toBe(values.length);
  const submitted=Date.now();await choices.nth(wrong).click();await page.getByRole("button",{name:"Check answer",exact:true}).click();
  await expect(page.getByRole('heading',{name:'Incorrect',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Next question',exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>window.__literacy.session()?.index)).toBe(1);
  await expect(page.getByRole('progressbar',{name:'Assessment progress'})).toHaveAttribute('aria-valuetext','Question 2 of 40');
  const next=await page.evaluate(()=>window.__literacy.session().responseEpisode.question);
  if(next.imagePath||next.imageUrl||next.targetImage||next.imageCards?.length)expect(await page.locator('img[data-assessment-media-kind="evidence"]').count()).toBeGreaterThan(0);
  await expect.poll(()=>page.locator('img[data-assessment-media-kind="evidence"]').evaluateAll(images=>images.every(image=>image.complete&&image.naturalWidth>0))).toBe(true);
  const nextCard = page.locator(`[data-assessment-question-id="${next.id}"]`);
  const nextChoices = nextCard.getByRole('group',{name:next.mapInteraction?'Tiles to move':'Answer choices',exact:true});
  await expect(nextChoices).toBeVisible();
  const expectedChoiceCount = (next.answerOptions || next.choices || []).length;
  expect(expectedChoiceCount).toBeGreaterThan(0);
  const nextButtons = nextChoices.locator('button[aria-pressed]');
  await expect(nextButtons).toHaveCount(expectedChoiceCount);
  // Visibility alone accepts an opacity-zero preloaded card. The evidence gate
  // must finish before this metric claims that the child can see the choices.
  await expect(page.locator('.assessment-media-loading')).toHaveCount(0);
  await expect(nextCard).toHaveAttribute('aria-busy', 'false');
  await expect(nextCard).toHaveCSS('opacity', '1');
  for (const button of await nextButtons.all()) await expect(button).toBeVisible();
  const nextContentMs=Date.now()-submitted;
  const report={profile:{viewport:'1024x768',latencyMs:100,downloadKiBPerSecond:384,cpuSlowdown:4,coldCache:true},homeMs,firstRenderMs,firstPicturesMs,audioDoneMs,nextContentMs,
    entryEncodedScriptBytes:before.filter(entry=>/\.js(?:\?|$)/.test(entry.name)).reduce((sum,entry)=>sum+entry.bytes,0),entryQuestionStock:'initial-sounds only',note:'Required speech and brief feedback time are separate from rendering/loading; this is a simulated tablet, not a physical iPad.'};
  await info.attach('loading-metrics.json',{body:JSON.stringify(report,null,2),contentType:'application/json'});
  console.log('Cold tablet loading:',JSON.stringify(report));
  await page.screenshot({path:info.outputPath('cold-tablet-next-question.png')});
  expect(homeMs).toBeLessThan(8000);expect(report.entryEncodedScriptBytes).toBeLessThan(2500000);
  expect(firstRenderMs).toBeLessThan(5000);expect(firstPicturesMs).toBeLessThan(5000);expect(nextContentMs).toBeLessThan(6000);
});
