import { author, text, key as K, wrong as W } from "./builders.mjs";
export default author("adjectives", [
  text("adj_size", 1, "GRAMMAR_WORD_CHOICE", "Which word describes something? A narrow path twists.", [K("narrow"), W("path"), W("twists"), W("a")], "Width description in context; all choices are visible words from that sentence."),
  text("adj_color", 1, "GRAMMAR_WORD_CHOICE", "Which word describes something? Her silver necklace sparkles.", [K("silver"), W("necklace"), W("sparkles"), W("her")], "Colour adjective in use rather than selecting a subjective image."),
  text("adj_texture_state", 1, "GRAMMAR_SENTENCE_FIT", "Which describing word fits?", [K("rough"), W("smooth", "D-OPPOSITE"), W("damp", "D-SAME-DOMAIN"), W("sticky", "D-SAME-DOMAIN")], "Texture clue distinguishes roughness from wetness and stickiness.", { sentence: "The ___ wood scratched my hand with splinters." }),
  text("adj_feeling", 1, "GRAMMAR_SENTENCE_FIT", "Which describing word fits?", [K("proud"), W("afraid", "D-SAME-DOMAIN"), W("lonely", "D-SAME-DOMAIN"), W("bored", "D-SAME-DOMAIN")], "Achievement feeling supported by an explicit success and smile.", { sentence: "I felt ___ and smiled at my medal." }),
  text("adj_in_sentence", 2, "GRAMMAR_CONTRAST", "Which word describes something? ‘The fragile ornament broke when it fell.’", [K("fragile"), W("ornament"), W("broke"), W("fell")], "Descriptive function applied to a less common but context-supported word."),
  text("adj_precision", 2, "GRAMMAR_SENTENCE_FIT", "Which describing word fits best?", [K("transparent"), W("cloudy", "D-SAME-DOMAIN"), W("striped", "D-SAME-DOMAIN"), W("shiny", "D-SAME-DOMAIN")], "Seeing clearly through something supplies the defining property; shine alone is insufficient.", { sentence: "The ___ sheet let us see every detail behind it." }),
  text("adj_vs_noun_verb", 2, "GRAMMAR_CONTRAST", "Where is ‘light’ a describing word?", [K("The light bag was easy to lift."), W("We light the candle carefully."), W("The light shone through the window."), W("Please turn off that bright light.")], "One familiar spelling used as adjective, verb and noun; sentence function determines the answer."),
  text("adj_vs_noun_verb", 2, "GRAMMAR_CONTRAST", "Which word describes the dancer? ‘The graceful dancer moved gracefully.’", [K("graceful"), W("dancer"), W("moved"), W("gracefully")], "Distinguish adjective from related adverb, not just from unrelated words.")
]);
