import { author, text, key as K, wrong as W } from "./builders.mjs";
export default author("verbs", [
  text("verb_action_body", 1, "GRAMMAR_WORD_CHOICE", "Which word tells an action? The baby crawls slowly.", [K("crawls"), W("baby"), W("slowly"), W("the")], "Every choice occurs in the sentence; separate action from person and manner.", { sentence: "The baby crawls slowly." }),
  text("verb_action_object", 1, "GRAMMAR_WORD_CHOICE", "Which word tells an action? Dad folds the blanket.", [K("folds"), W("Dad"), W("the"), W("blanket")], "Folding is a concrete action on an object, without an answer-revealing picture.", { sentence: "Dad folds the blanket." }),
  text("verb_everyday", 1, "GRAMMAR_WORD_CHOICE", "Which word tells an action? We share our lunch.", [K("share"), W("we"), W("our"), W("lunch")], "Everyday social action contrasted with pronouns and a naming word.", { sentence: "We share our lunch." }),
  text("verb_everyday", 1, "GRAMMAR_WORD_CHOICE", "Which word tells an action? Grandma mends my sock.", [K("mends"), W("Grandma"), W("my"), W("sock")], "Extends everyday action vocabulary to repair rather than repeating run/jump.", { sentence: "Grandma mends my sock." }),
  text("verb_in_sentence", 2, "GRAMMAR_CONTRAST", "Which word tells what happens? ‘Deep snow blocked the mountain road.’", [K("blocked"), W("snow"), W("mountain"), W("road")], "An inanimate subject can perform the grammatical action."),
  text("verb_vs_noun", 2, "GRAMMAR_CONTRAST", "Where is ‘plant’ a doing word?", [K("We plant beans in spring."), W("The plant has new leaves."), W("A small plant needs water."), W("That plant is growing fast.")], "Same spelling, different grammatical function; identify the verb in use."),
  text("verb_precision", 2, "GRAMMAR_SENTENCE_FIT", "Which action fits best?", [K("sprinkled"), W("poured", "D-SAME-DOMAIN"), W("spilled", "D-SAME-DOMAIN"), W("scooped", "D-SAME-DOMAIN")], "Fine controlled scattering contrasts with stream, accident and collecting.", { sentence: "Mia ___ tiny drops evenly over the seeds." }),
  text("verb_precision", 2, "GRAMMAR_SENTENCE_FIT", "Which action fits best?", [K("whispered"), W("announced", "D-SAME-DOMAIN"), W("exclaimed", "D-SAME-DOMAIN"), W("chanted", "D-SAME-DOMAIN")], "Audible clue specifies quiet speech rather than another plausible speaking verb.", { sentence: "He ___ the secret so only I could hear." })
]);
