import { useEffect, useState } from "react";
import { listStudentPressProjects, readClassPressLibrary } from "../../data/decodablePress/decodablePress.js";
import { DecodableBookEditorPage } from "./DecodableBookEditorPage.jsx";
import { BookPreview } from "./BookPreview.jsx";
import "../../styles/decodable-press.css";

export function DecodablePressHomePage({ client, token, onClose }) {
  const [state,setState]=useState({status:"loading",projects:[],library:[],error:""}); const [active,setActive]=useState(null); const [reading,setReading]=useState(null);
  async function load(){try{const [work,library]=await Promise.all([listStudentPressProjects(client,token),readClassPressLibrary(client,token)]);setState({status:"ready",projects:work.projects,library:library.books,error:""});}catch(error){setState({status:"error",projects:[],library:[],error:error?.message||"Your press shelf could not be opened."});}}
  useEffect(()=>{Promise.all([listStudentPressProjects(client,token),readClassPressLibrary(client,token)]).then(([work,library])=>setState({status:"ready",projects:work.projects,library:library.books,error:""})).catch(error=>setState({status:"error",projects:[],library:[],error:error?.message||"Your press shelf could not be opened."}));},[client,token]);
  if(active)return <DecodableBookEditorPage client={client} token={token} project={active} onClose={()=>setActive(null)} onSaved={load}/>;
  if(reading)return <main className="press-home"><button type="button" onClick={()=>setReading(null)}>Back to class books</button><BookPreview book={reading.content} authorName={reading.author_name}/></main>;
  return <main className="press-home"><header><div><p>Class Decodable Press</p><h1>Make a tiny book</h1><span>Your drafts are private. A class book appears only after your teacher approves that exact version.</span></div><button type="button" onClick={onClose}>Back to reading books</button></header>{state.status==="loading"&&<p aria-busy="true">Opening your private press shelf…</p>}{state.error&&<p role="alert">{state.error}</p>}<section aria-labelledby="press-projects"><h2 id="press-projects">Your projects</h2>{state.status==="ready"&&!state.projects.length?<p>Your teacher has not assigned a book project yet.</p>:<div className="press-card-grid">{state.projects.map(project=><article key={project.id}><span>{project.book?.status?.replaceAll("_"," ")||"Not started"}</span><h3>{project.title}</h3><p>{project.rules.templateDescription}</p>{project.book?.review?.child_feedback&&<p><strong>Teacher note:</strong> {project.book.review.child_feedback}</p>}<button type="button" disabled={project.book?.status==="submitted"} onClick={()=>setActive(project)}>{project.book?.status==="submitted"?"Waiting for teacher":project.book?"Keep making":"Start my book"}</button></article>)}</div>}</section><section aria-labelledby="press-library"><h2 id="press-library">Class-made books</h2>{state.status==="ready"&&!state.library.length?<p>No class books have been approved yet.</p>:<div className="press-card-grid">{state.library.map(book=><article key={book.revision_id}><span>Teacher approved</span><h3>{book.title}</h3><p>By {book.author_name}</p><button type="button" onClick={()=>setReading(book)}>Read this book</button></article>)}</div>}</section></main>;
}
