export const APP_VIEWS = {
  ENTRY: "entry",
  SELECT: "select",
  STUDENT_LOGIN: "studentLogin",
  STUDENT_HOME: "studentHome",
  STUDENT_REWARDS: "studentRewards",
  ASSESSMENTS: "assessments",
  EL_BENCHMARK: "elBenchmark",
  GUIDED_READING: "guidedReading",
  REPORTS: "reports",
  LEARN: "learn",
  PHONICS_LEARN: "phonicsLearn",
  SKILLS_BLOCK_QUEST: "skillsBlockQuest",
  PHONICS_QUEST: "phonicsQuest",
  ASSESSMENT: "assessment",
  CHECKPOINT: "checkpoint",
  FINISHED: "finished",
  LETTERS: "letters",
  ADVANCED_PHONICS: "advancedPhonics",
  TEACHER_DASHBOARD: "teacherDashboard",
  TEACHER_CLASSES: "teacherClasses",
  TEACHER_RESOURCES: "teacherResources",
  // The whole-class reader on the Resources shelf. GUIDED_READING is the
  // per-student conference and only renders once a student is chosen; this one
  // needs no student, because a class read has no single reader.
  TEACHER_GUIDED_READING: "teacherGuidedReading",
  TEACHER_SETTINGS: "teacherSettings",
  WORKSHEETS: "worksheets",
  PRESENT: "present",
  MATHS_STUDENT_HOME: "mathsStudentHome",
  MATHS_LEARN: "mathsLearn",
  MATHS_STORIES: "mathsStories",
  MATHS_ARCADE: "mathsArcade",
  MATHS_ASSESSMENT: "mathsAssessment",
  MATHS_TEACHER_DASHBOARD: "mathsTeacherDashboard",
  MATHS_TEACHER_ASSESSMENTS: "mathsTeacherAssessments",
  MATHS_TEACHER_REPORTS: "mathsTeacherReports",
  MATHS_TEACHER_RESOURCES: "mathsTeacherResources",
  MATHS_PRESENT: "mathsPresent",
  MATHS_WORKSHEETS: "mathsWorksheets",
  MATHS_SMALL_GROUPS: "mathsSmallGroups",
  ADMIN_DASHBOARD: "admin"
};

export const REQUIRED_APP_VIEWS = Object.freeze(Object.values(APP_VIEWS));
