import { GAME_VERTICAL_SLICE_BRIEF_SCHEMA_VERSION, validateGameVerticalSliceBrief } from '../shared/premiumGameStandard.js';
function freeze(value) { if (value && typeof value === 'object') { Object.values(value).forEach(freeze); Object.freeze(value); } return value; }
export const RHYME_POP_VERTICAL_SLICE_BRIEF = freeze({
  schemaVersion: GAME_VERTICAL_SLICE_BRIEF_SCHEMA_VERSION, gameId: 'rhyme-pop', version: '3.0',
  audience: 'Early readers practising reviewed rhyme relationships with printed and recorded support.',
  experiencePromise: 'Pop the rhyming balloons at a night carnival to fill six tethers and lift each parade basket.',
  learning: { targetConstruct: 'Printed-word rhyme selection using reviewed phonological groups, including cross-spelling rhymes.',
    childGoal: 'Find every rhyme and lift the balloon basket.', integratedAction: 'Releasing a named balloon pops that exact word and adds it to the basket when it rhymes.',
    nonTargetDemands: 'Pointer aiming, pop animation and basket movement are presentation or motor demands.',
    evidenceEvent: 'chooseRhyme retains one frozen first deliberate response per round/word plus separate assisted retries and exact cue/support snapshots. All events are supported practice, never independent mastery.', movementCreatesEvidence: false },
  loop: { onboard: 'The exact visible instruction has a replayable Leda recording and an explicit muted/failed reading-support route.',
    perceive: 'The target and five, six or seven equally styled stationary word balloons stay in a quiet answer plane. Target and current choices are spoken before audio-enabled selection.',
    act: 'Release a balloon or activate its native keyboard button; no Check gate and no projectile collision decide the answer.',
    feedback: 'The chosen word is compared with the retained target using recorded rhymes with or does not rhyme with. A correct balloon pops and its word joins the visible collection.',
    retry: 'A mismatch remains in its slot. Correct selections replenish only their own slots with unresolved authored rhymes; each of six valid words can count once.',
    complete: 'Six collected balloons lift the basket. The last accepted rhyme fixes the receipt before its animation; the shared player presents one final result.' },
  prompt: { visible: 'Pop every word that rhymes with the target. Each rhyme adds a balloon to the basket.',
    spoken: 'Pop every word that rhymes with the target. Each rhyme adds a balloon to the basket.',
    replay: 'Hear replays the retained target and all current options, or the selected-word comparison during feedback. Failed delivery exposes Hear again and explicit Read the words support.' },
  controls: { keyboard: ['Tab and arrow keys focus stable balloon buttons', 'Enter or Space activates the focused balloon'],
    touch: ['A valid released tap pops that exact balloon', 'Hear, recovery and next-basket actions are native released buttons'], minimumTargetCssPixels: 56,
    pointerReleaseEvents: ['pointerup', 'pointercancel', 'lostpointercapture', 'blur', 'pause', 'unmount'] },
  difficulty: { curriculumBeforePressure: true, ladder: 'Preserve all ten authored rounds at each difficulty. Vocabulary, five/six/seven choices and harder near-rime distractors increase demand; no deadline, movement penalty or minimum play timer.' },
  gameFeel: { movement: 'Balloon centres stay fixed during decisions. Selected-target pop or shake and six collected tethers make the action visible; a basket lift marks each checkpoint.',
    forgiveness: ['No decision deadline', 'Cancelled and outside releases create no response', 'Completed rhymes survive a mismatch', 'Replay or explicit print support recovers unavailable sound'],
    camera: 'A stationary carnival composition reserves separate mission, stable answer and character/basket layers at landscape, portrait and short-landscape sizes.',
    successFeedback: 'The selected faceted balloon pops; its word remains in the collected row and another tether fills.', errorFeedback: 'The chosen balloon shakes and both selected word and target are accurately contrasted without moving untouched answers.' },
  world: { artDirection: 'Dark blue low-poly carnival, muted scenery, pastel faceted balloons with knots, warm striped wicker basket and existing orange dinosaur-hooded helper.',
    route: 'Six balloons accumulate at each of ten basket stops; the stable native slot layout is also the visual hit geometry.',
    character: 'Retain the reviewed dinosaur-hooded child with the existing blaster. Authored cutout recoil, retry lean and checkpoint hop provide action reactions; this is not a new articulated rig. No unrelated second launcher or generic replacement figure.',
    assetFallback: 'Missing decorative background/helper art retains authored balloon, tether and basket geometry and all native reading decisions.' },
  state: { pauseResume: 'Pause, visibility loss and blur invalidate held pointers, interrupt audio and freeze feedback/lift time. Resume replays interrupted cues without changing the target or inventing delivery.',
    checkpoint: 'The existing next-round checkpoint preserves completed baskets; a resumed run records only words actually selected during that run.',
    completion: 'The immutable final-action receipt is sent via onResultReady once. The shared player owns completion, persistence and exit, so animation and dismissal cannot replace evidence.' },
  accessibility: { reducedMotion: 'Pop, shake and lift animation are suppressed; text, collection count and state changes communicate every action.',
    soundOff: 'Explicit reading support permits play and records printed_rhyme_support. Muted or failed recordings are never reported as heard.',
    nonColourCue: 'Colour is determined by slot and seed, never correctness. Written comparison, collection and remaining count explain outcomes.',
    semanticFallback: 'All balloons and actions are native named buttons with 56-pixel minimum bounds and a polite feedback status.' },
  performance: { lowPowerFallback: 'DOM/SVG scene has no WebGL dependency, shader compilation, frame-dependent physics or decorative asset requirement.',
    inputSafety: 'Pointer ownership, release bounds and an input epoch reject multi-touch theft, cancelled/lost holds and stale interactions across feedback, pause or unmount.',
    assetFailure: 'Missing or stalled recordings block audio-led decisions until retry or explicit print support. A per-clip delivery watchdog exposes stalled recovery; it is not a learner deadline. Decorative image failure cannot remove choices or break completion.' },
  privacy: { dataWritten: ['Existing score, stars and actual rhyme count', 'Existing next-round checkpoint', 'Existing practice evidence with first responses, retries and cue/support snapshots'],
    network: ['Existing local app art/audio files', 'Existing progress sync'], newIdentifier: false, newExternalService: false },
  validation: { unit: ['tests/unit/rhymePopRules.test.js', 'tests/unit/rhymePopAudio.test.js', 'tests/unit/rhymePopScene.test.js'],
    browser: ['tests/release/rhyme-pop-parade.spec.js', 'tests/release/rhyme-pop-full-parade.spec.js'], physicalDevice: { status: 'unknown', note: 'Browser rendering and recorded-media delivery are separate from physical iPad, human listening and child observation; those are not claimed by these checks.' } }
});
const issues = validateGameVerticalSliceBrief(RHYME_POP_VERTICAL_SLICE_BRIEF);
if (issues.length) throw new Error(`Rhyme Pop vertical-slice brief: ${issues.join('; ')}`);
