// Blends — v3 authored bank (wave W5, paired with short_vowel_discrimination).
// Curated from the audit's 38-key sprawl to 12 units per level (D-small, 4
// variants each). L1: beginning blends. L2: harder beginnings + final blends
// (decode-the-cluster framing; Final Sounds keeps isolate-the-sound framing).
// Formats:
//   BLEND_COMPLETE_WORD — the child hears the target word and supplies the
//     missing blend. Audio pins the word, avoiding an unnecessary picture-
//     naming demand in a spelling-pattern assessment. Closed-set.
//   BLEND_IMAGE_CHOICE — same-blend matching over picture cards; a
//     rhyme-of-anchor or shared-chunk card always ties the scanner.
//   MPD — picture → printed near-words. Every set carries the cluster
//     REDUCTION word where a real one exists (lock for block, fog for frog,
//     soon for spoon, tuck for truck) — the audit-mandated blend error.
// Spec: docs/skills-assessment-rebuild/BLUEPRINTS_PHONICS.md §10.

import { makeImageResolver } from "../lib.mjs";

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const sentenceCase = value => value ? `${value[0].toUpperCase()}${value.slice(1)}` : value;

const resolver = makeImageResolver(["blends", "digraphs", "long-vowels", "hfw", "cvc", "rhyming"]);

// BLEND_COMPLETE_WORD.
// Keep the visible instruction free of the assessed blend. In particular,
// "complete" contains pl and mp, so it cannot be used as a shared prompt.
const cw = (u, lvl, ph, v, word, blanked, patterns, note = "") => ({
  u, lvl, ph, v, fmt: "BLEND_COMPLETE_WORD",
  prompt: `Choose the missing letters for ${blanked}.`,
  spoken: `${sentenceCase(word)}. Choose the missing letters.`,
  choices: patterns.map((p, i) => (i === 0 ? K(p) : P(p, "D-PATTERN-TRAP"))),
  media: "audio-required",
  target: word,
  audioRole: "target_word",
  evidenceModality: "audio+print",
  constructClaim: "map_spoken_word_to_blend_spelling",
  pos: u.length === 2 && ["nd", "nt", "mp", "nk", "lt", "ft"].includes(u) ? "final" : "initial",
  note
});

// BLEND_IMAGE_CHOICE.
const ic = (u, lvl, ph, v, anchor, cards, keyWord, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "BLEND_IMAGE_CHOICE",
  prompt: "Which word begins with the same blend?",
  spoken: `${sentenceCase(anchor)}. Which word begins with the same blend?`,
  cards,
  choices: cards.map(w => (w === keyWord ? K(w) : P(w, rationales[w]))),
  media: "image-required",
  evidenceModality: "audio+image",
  constructClaim: "spoken_blend_discrimination",
  hideWrittenLabels: true,
  pos: "initial",
  target: anchor,
  note
});

// Audio target -> printed near-words. Keep the established MPD format key so
// item identity, blueprint coverage, and evidence history remain stable while
// removing a subjective action/relationship picture from the scoring path.
const apd = (u, lvl, ph, v, word, words, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "MPD", questionType: "listen_and_find_word",
  prompt: "Which printed word matches the recording?",
  spoken: `${sentenceCase(word)}. Which printed word matches the recording?`,
  choices: words.map(w => (w === word ? K(w) : P(w, rationales[w]))),
  media: "audio-required",
  target: word,
  audioRole: "target_word",
  evidenceModality: "audio+print",
  constructClaim: "map_spoken_word_to_blend_spelling",
  note
});

// MPD: picture → printed near-words.
const mpd = (u, lvl, ph, v, word, words, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "MPD",
  prompt: "Which word names the picture?",
  spoken: "Which word names the picture?",
  choices: words.map(w => (w === word ? K(w) : P(w, rationales[w]))),
  media: "image-required",
  img: word,
  target: word,
  note
});

export default {
  skillId: "blends",
  skillName: "Blends",
  imageResolver: resolver,
  items: [
    // ================= L1 phase 1: bl cl fl pl sl br =================
    cw("bl", 1, 1, 1, "block", "__ock", ["bl", "cl", "fl", "st"]),
    apd("bl", 1, 1, 2, "blue", ["blue", "glue", "drum", "star"],
      { glue: "D-PATTERN-TRAP", drum: "D-PATTERN-TRAP", star: "D-PATTERN-TRAP" },
      "audio pins the colour word without asking a child to infer an attribute from a picture"),
    apd("bl", 1, 1, 3, "block", ["block", "lock", "black", "clock"],
      { lock: "D-ONSET", black: "D-PATTERN-TRAP", clock: "D-RIME-NEAR" },
      "audio pins the intended word and avoids an arbitrary block-versus-cube naming judgement; lock is the b-dropped reduction"),
    cw("bl", 1, 1, 4, "blue", "__ue", ["bl", "cl", "fl", "gl"],
      "glue is real — the blue image pins the target"),
    cw("cl", 1, 1, 1, "clap", "__ap", ["cl", "fl", "sl", "tr"]),
    ic("cl", 1, 1, 2, "clap", ["clock", "lamp", "crab", "map"], "clock",
      { lamp: "D-ONSET", crab: "D-PATTERN-TRAP", map: "D-RIME-NEAR" },
      "lamp is the l-only reduction and ties the clap overlap; map rhymes with the anchor"),
    mpd("cl", 1, 1, 3, "clock", ["clock", "lock", "click", "sock"],
      { lock: "D-ONSET", click: "D-PATTERN-TRAP", sock: "D-RIME-NEAR" }),
    cw("cl", 1, 1, 4, "cloth", "__oth", ["cl", "bl", "sl", "br"]),
    cw("fl", 1, 1, 1, "flag", "__ag", ["fl", "bl", "cr", "st"]),
    ic("fl", 1, 1, 2, "flower", ["flag", "frog", "crown", "lamp"], "flag",
      { frog: "D-PATTERN-TRAP", crown: "D-PATTERN-TRAP", lamp: "D-ONSET" },
      "crown carries the anchor's ow letters — the scanner tie"),
    mpd("fl", 1, 1, 3, "flag", ["flag", "lag", "flap", "bag"],
      { lag: "D-ONSET", flap: "D-PATTERN-TRAP", bag: "D-RIME-NEAR" }),
    cw("fl", 1, 1, 4, "flute", "__ute", ["fl", "cl", "br", "gr"]),
    cw("pl", 1, 1, 1, "plug", "__ug", ["pl", "bl", "sl", "dr"]),
    apd("pl", 1, 1, 2, "plate", ["plate", "late", "plant", "gate"],
      { late: "D-ONSET", plant: "D-PATTERN-TRAP", gate: "D-RIME-NEAR" },
      "audio and print remove the plane-versus-airplane naming dependency; late is the p-dropped reduction"),
    apd("pl", 1, 1, 3, "plug", ["plug", "lug", "plum", "rug"],
      { lug: "D-ONSET", plum: "D-PATTERN-TRAP", rug: "D-RIME-NEAR" }),
    cw("pl", 1, 1, 4, "plant", "__ant", ["pl", "gr", "sl", "fr"],
      "grant is real — the plant image pins the target"),
    cw("sl", 1, 1, 1, "sled", "__ed", ["sl", "fl", "br", "st"]),
    ic("sl", 1, 1, 2, "slip", ["sled", "ship", "spoon", "lamp"], "sled",
      { ship: "D-RIME-NEAR", spoon: "D-PATTERN-TRAP", lamp: "D-ONSET" },
      "ship shares the anchor's ip — the scanner tie and the rhyme trap"),
    apd("sl", 1, 1, 3, "sled", ["sled", "led", "slid", "red"],
      { led: "D-ONSET", slid: "D-PATTERN-TRAP", red: "D-RIME-NEAR" }),
    cw("sl", 1, 1, 4, "slide", "__ide", ["sl", "gl", "br", "cr"]),
    cw("br", 1, 1, 1, "bread", "__ead", ["br", "dr", "cr", "tr"]),
    ic("br", 1, 1, 2, "brown", ["bread", "crown", "glass", "rat"], "bread",
      { crown: "D-RIME-NEAR", glass: "D-PATTERN-TRAP", rat: "D-ONSET" },
      "crown rhymes with the anchor and out-chunks the key — the scanner falls for it"),
    mpd("br", 1, 1, 3, "bread", ["bread", "red", "brown", "bed"],
      { red: "D-ONSET", brown: "D-PATTERN-TRAP", bed: "D-RIME-NEAR" },
      "red is the b-dropped reduction"),
    cw("br", 1, 1, 4, "brick", "__ick", ["br", "tr", "st", "cl"]),

    // ================= L1 phase 2: cr dr fr gr st sw =================
    cw("cr", 1, 2, 1, "crab", "__ab", ["cr", "gr", "dr", "st"]),
    ic("cr", 1, 2, 2, "crown", ["crab", "bread", "clock", "rat"], "crab",
      { bread: "D-PATTERN-TRAP", clock: "D-PATTERN-TRAP", rat: "D-ONSET" },
      "bread supplies a rival r-blend; rat is the c-dropped reduction"),
    mpd("cr", 1, 2, 3, "crab", ["crab", "cab", "crib", "grab"],
      { cab: "D-ONSET", crib: "D-PATTERN-TRAP", grab: "D-RIME-NEAR" },
      "cab is the r-dropped reduction"),
    cw("cr", 1, 2, 4, "crown", "__own", ["cr", "br", "fr", "dr"],
      "brown and drown are real — the crown image pins the target"),
    cw("dr", 1, 2, 1, "drum", "__um", ["dr", "br", "pl", "gr"]),
    ic("dr", 1, 2, 2, "dress", ["drum", "vest", "crab", "rat"], "drum",
      { vest: "D-RIME-NEAR", crab: "D-PATTERN-TRAP", rat: "D-ONSET" },
      "vest shares the anchor's es letters — the scanner tie"),
    apd("dr", 1, 2, 3, "draw", ["draw", "raw", "drum", "paw"],
      { raw: "D-ONSET", drum: "D-PATTERN-TRAP", paw: "D-RIME-NEAR" },
      "audio pins draw without asking a child to infer an action from a still picture"),
    cw("dr", 1, 2, 4, "draw", "__aw", ["dr", "cr", "st", "cl"],
      "claw is real — the draw image pins the target"),
    cw("fr", 1, 2, 1, "frog", "__og", ["fr", "fl", "dr", "cl"],
      "clog is real — the frog image pins the target"),
    ic("fr", 1, 2, 2, "fruit", ["frog", "flag", "ring", "sit"], "frog",
      { flag: "D-PATTERN-TRAP", ring: "D-ONSET", sit: "D-RIME-NEAR" },
      "sit carries the anchor's it letters — the scanner tie"),
    mpd("fr", 1, 2, 3, "frog", ["frog", "fog", "frown", "log"],
      { fog: "D-ONSET", frown: "D-PATTERN-TRAP", log: "D-RIME-NEAR" },
      "fog is the r-dropped reduction — the spec's own example"),
    cw("fr", 1, 2, 4, "fruit", "__uit", ["fr", "gr", "br", "tr"]),
    cw("gr", 1, 2, 1, "grapes", "__apes", ["gr", "dr", "cr", "tr"]),
    ic("gr", 1, 2, 2, "green", ["grapes", "sheep", "brick", "rat"], "grapes",
      { sheep: "D-RIME-NEAR", brick: "D-PATTERN-TRAP", rat: "D-ONSET" },
      "sheep carries the anchor's ee — the scanner tie"),
    apd("gr", 1, 2, 3, "ground", ["ground", "round", "grand", "sound"],
      { round: "D-ONSET", grand: "D-PATTERN-TRAP", sound: "D-RIME-NEAR" },
      "audio removes the relational ground-scene naming demand; round remains the g-dropped reduction"),
    cw("gr", 1, 2, 4, "green", "__een", ["gr", "br", "cr", "sc"]),
    cw("st", 1, 2, 1, "star", "__ar", ["st", "sc", "sp", "tr"]),
    ic("st", 1, 2, 2, "stone", ["star", "cone", "spoon", "tie"], "star",
      { cone: "D-RIME-NEAR", spoon: "D-PATTERN-TRAP", tie: "D-ONSET" },
      "the spoken stone anchor leads to an objectively nameable star card"),
    mpd("st", 1, 2, 3, "star", ["star", "tar", "scar", "car"],
      { tar: "D-ONSET", scar: "D-PATTERN-TRAP", car: "D-RIME-NEAR" },
      "tar is the s-dropped reduction"),
    cw("st", 1, 2, 4, "stop", "__op", ["st", "sh", "dr", "cr"],
      "shop, drop and crop are real — the stop image pins the target"),
    cw("sw", 1, 2, 1, "swim", "__im", ["sw", "st", "sl", "br"]),
    ic("sw", 1, 2, 2, "sweet", ["swing", "feet", "star", "wasp"], "swing",
      { feet: "D-RIME-NEAR", star: "D-PATTERN-TRAP", wasp: "D-ONSET" },
      "feet rhymes with the anchor; the empty swing is an objectively nameable concrete card"),
    apd("sw", 1, 2, 3, "swim", ["swim", "win", "swam", "dim"],
      { win: "D-DEVELOPMENTAL", swam: "D-PATTERN-TRAP", dim: "D-RIME-NEAR" }),
    cw("sw", 1, 2, 4, "swing", "__ing", ["sw", "gr", "cr", "sn"],
      "no swing image — but sning, gring and cring are non-words, so the completion is pinned"),

    // ================= L2 phase 1: sc sk sm sn sp tr =================
    cw("sc", 2, 1, 1, "scarf", "__arf", ["sc", "sk", "sm", "st"]),
    apd("sc", 2, 1, 2, "scarf", ["scarf", "scar", "card", "sharp"],
      { scar: "D-DEVELOPMENTAL", card: "D-RIME-NEAR", sharp: "D-PATTERN-TRAP" },
      "audio pins scarf without asking a child to distinguish folded fabric from a towel; scar is the f-dropped ending error"),
    cw("sc", 2, 1, 3, "scooter", "__ooter", ["sc", "sm", "sn", "tr"],
      "no scooter image — smooter, snooter and trooter are non-words"),
    cw("sc", 2, 1, 4, "score", "__ore", ["sc", "sn", "sm", "dr"],
      "no score image — snore is deliberately absent from the set; smore and drore are non-words"),
    cw("sk", 2, 1, 1, "skateboard", "__ateboard", ["sk", "sc", "sp", "st"]),
    mpd("sk", 2, 1, 2, "skateboard", ["skateboard", "snowboard", "surfboard", "scoreboard"],
      { snowboard: "D-PATTERN-TRAP", surfboard: "D-RIME-NEAR", scoreboard: "D-PATTERN-TRAP" },
      "the board family — same frame, different front"),
    cw("sk", 2, 1, 3, "skip", "__ip", ["sk", "sc", "sm", "sp"],
      "no skip image — scip, smip and spip are non-words"),
    cw("sk", 2, 1, 4, "skin", "__in", ["sk", "sc", "sm", "sn"],
      "no skin image — scin and smin are non-words; snin too"),
    cw("sm", 2, 1, 1, "smile", "__ile", ["sm", "sn", "sw", "sc"]),
    apd("sm", 2, 1, 2, "smile", ["smile", "mile", "smell", "tile"],
      { mile: "D-ONSET", smell: "D-PATTERN-TRAP", tile: "D-RIME-NEAR" },
      "audio replaces subjective facial-expression evidence; mile remains the s-dropped reduction"),
    cw("sm", 2, 1, 3, "smell", "__ell", ["sm", "sn", "sc", "gr"],
      "no smell image — snell, scell and grell are non-words (spell and swell stay out)"),
    cw("sm", 2, 1, 4, "smoke", "__oke", ["sm", "sn", "sc", "gl"],
      "no smoke image — snoke, scoke and gloke are non-words"),
    cw("sn", 2, 1, 1, "snake", "__ake", ["sn", "sm", "sc", "cl"],
      "smake, scake and clake are non-words; the snake image pins it anyway"),
    mpd("sn", 2, 1, 2, "snake", ["snake", "snack", "rake", "sack"],
      { snack: "D-PATTERN-TRAP", rake: "D-RIME-NEAR", sack: "D-ONSET" },
      "snack is the classic snake/snack near-word"),
    cw("sn", 2, 1, 3, "snail", "__ail", ["sn", "sm", "sc", "sw"],
      "no snail image — smail, scail and swail are non-words (trail stays out)"),
    cw("sn", 2, 1, 4, "snow", "__ow", ["sn", "sm", "sk", "dr"],
      "no snow image — smow, skow and drow are non-words (glow and crow stay out)"),
    cw("sp", 2, 1, 1, "spoon", "__oon", ["sp", "sm", "sn", "sc"],
      "smoon, snoon and scoon are non-words; the spoon image pins it anyway"),
    mpd("sp", 2, 1, 2, "spoon", ["spoon", "soon", "moon", "spin"],
      { soon: "D-ONSET", moon: "D-RIME-NEAR", spin: "D-PATTERN-TRAP" },
      "soon is the p-dropped reduction"),
    cw("sp", 2, 1, 3, "sport", "__ort", ["sp", "sn", "sm", "sc"],
      "no sport image — snort is deliberately absent; smort and scort are non-words"),
    cw("sp", 2, 1, 4, "spot", "__ot", ["sp", "sm", "sk", "gl"],
      "no spot image — smot, skot and glot are non-words (slot and trot stay out)"),
    cw("tr", 2, 1, 1, "truck", "__uck", ["tr", "dr", "st", "cl"],
      "cluck is real — the truck image pins the target"),
    apd("tr", 2, 1, 2, "truck", ["truck", "tuck", "track", "duck"],
      { tuck: "D-ONSET", track: "D-PATTERN-TRAP", duck: "D-RIME-NEAR" },
      "the recording pins truck without requiring a child to choose truck rather than lorry; tuck is the r-dropped reduction"),
    cw("tr", 2, 1, 3, "train", "__ain", ["tr", "dr", "gr", "br"],
      "drain, grain and brain are all real — the train image pins the target"),
    cw("tr", 2, 1, 4, "tray", "__ay", ["tr", "sm", "sk", "gl"],
      "no tray image — smay, skay and glay are non-words (gray, play and clay stay out)"),

    // ================= L2 phase 2: nd nt mp nk lt ft (final blends) =================
    cw("nd", 2, 2, 1, "hand", "ha__", ["nd", "nt", "mp", "nk"]),
    apd("nd", 2, 2, 2, "hand", ["hand", "had", "ham", "band"],
      { had: "D-ONSET", ham: "D-ONSET", band: "D-RIME-NEAR" },
      "audio removes the body-part crop judgement; had and ham drop the cluster two different ways"),
    cw("nd", 2, 2, 3, "pond", "po__", ["nd", "nt", "nk", "lt"],
      "no pond image — pont, ponk and polt are non-words"),
    cw("nd", 2, 2, 4, "sand", "sa__", ["nd", "mp", "nt", "sk"],
      "no sand image — samp, sant and sask are non-words (salt stays out)"),
    cw("nt", 2, 2, 1, "tent", "te__", ["nt", "nd", "mp", "nk"],
      "tend is real — the tent image pins the target"),
    mpd("nt", 2, 2, 2, "tent", ["tent", "ten", "tin", "bent"],
      { ten: "D-ONSET", tin: "D-RIME-NEAR", bent: "D-RIME-NEAR" },
      "ten is the t-dropped reduction"),
    cw("nt", 2, 2, 3, "print", "pri__", ["nt", "nd", "nk", "ft"],
      "no print image — prind, prink and prift are non-words"),
    cw("nt", 2, 2, 4, "paint", "pai__", ["nt", "nd", "nk", "mp"],
      "paind, paink and paimp are non-words"),
    cw("mp", 2, 2, 1, "lamp", "la__", ["mp", "nd", "nt", "nk"],
      "land is real — the lamp image pins the target"),
    mpd("mp", 2, 2, 2, "lamp", ["lamp", "lap", "lab", "camp"],
      { lap: "D-ONSET", lab: "D-RIME-NEAR", camp: "D-RIME-NEAR" },
      "lap is the m-dropped reduction"),
    cw("mp", 2, 2, 3, "jump", "ju__", ["mp", "nd", "nt", "lt"],
      "no jump image — jund, junt and jult are non-words (just and junk stay out)"),
    cw("mp", 2, 2, 4, "camp", "ca__", ["mp", "nd", "lt", "sk"],
      "no camp image — cand, calt and cask are non-words (cant stays out)"),
    cw("nk", 2, 2, 1, "ink", "i__", ["nk", "nd", "nt", "ft"],
      "ind, int and ift are non-words; the ink image pins it anyway"),
    mpd("nk", 2, 2, 2, "ink", ["ink", "in", "inch", "pink"],
      { in: "D-ONSET", inch: "D-PATTERN-TRAP", pink: "D-RIME-NEAR" },
      "in is the k-dropped reduction; inch swaps the cluster"),
    cw("nk", 2, 2, 3, "think", "thi__", ["nk", "nd", "nt", "ft"],
      "no think image — thind, thint and thift are non-words"),
    cw("nk", 2, 2, 4, "bank", "ba__", ["nk", "lt", "ft", "sc"],
      "no bank image — balt, baft and basc are non-words (band and bath stay out)"),
    cw("lt", 2, 2, 1, "belt", "be__", ["lt", "nd", "nt", "mp"],
      "bend and bent are real — the belt image pins the target"),
    mpd("lt", 2, 2, 2, "belt", ["belt", "bet", "bell", "melt"],
      { bet: "D-ONSET", bell: "D-PATTERN-TRAP", melt: "D-RIME-NEAR" },
      "bet is the l-dropped reduction; bell drops the t instead"),
    cw("lt", 2, 2, 3, "quilt", "qui__", ["lt", "nt", "nd", "mp"],
      "quint, quind and quimp are non-words; the quilt image pins it anyway"),
    cw("lt", 2, 2, 4, "tilt", "ti__", ["lt", "nd", "nk", "ft"],
      "no tilt image — tind, tink and tift are non-words (tint stays out)"),
    cw("ft", 2, 2, 1, "gift", "gi__", ["ft", "nt", "nd", "nk"],
      "gint, gind and gink are non-words; the gift image pins it anyway"),
    mpd("ft", 2, 2, 2, "gift", ["gift", "lift", "left", "give"],
      { lift: "D-RIME-NEAR", left: "D-VOWEL", give: "D-SEMANTIC" },
      "give is the gift's own verb — semantic pull with the wrong ending"),
    cw("ft", 2, 2, 3, "left", "le__", ["ft", "sk", "mp", "lt"],
      "no left image — lesk, lemp and lelt are non-words (lent and lend stay out)"),
    cw("ft", 2, 2, 4, "soft", "so__", ["ft", "nd", "lt", "mp"],
      "no soft image — sond, solt and somp are non-words"),

    // ================= Retention reserve (form R) =================
    cw("br", 1, 1, 5, "brush", "__ush", ["br", "cr", "fl", "pl"],
      "crush, flush and plush are real — the brush image pins the target"),
    cw("br", 1, 1, 6, "broom", "__oom", ["br", "gl", "dr", "sp"],
      "gloom is real — the broom image pins the target"),
    apd("cl", 1, 1, 5, "clap", ["clap", "lap", "clip", "cap"],
      { lap: "D-ONSET", clip: "D-PATTERN-TRAP", cap: "D-RIME-NEAR" }),
    apd("sp", 2, 1, 5, "spring", ["spring", "ring", "string", "sing"],
      { ring: "D-ONSET", string: "D-PATTERN-TRAP", sing: "D-RIME-NEAR" },
      "audio disambiguates the polysemous word spring; ring is the sp-dropped reduction"),
    ic("pl", 1, 1, 5, "plate", ["plant", "gate", "frog", "lamp"], "plant",
      { gate: "D-RIME-NEAR", frog: "D-PATTERN-TRAP", lamp: "D-ONSET" },
      "gate rhymes with the anchor — the scanner tie"),
    cw("sn", 2, 1, 5, "snack", "__ack", ["sn", "sc", "sw", "gl"],
      "no snack image — scack, swack and glack are non-words (smack stays out)"),
    cw("ft", 2, 2, 5, "raft", "ra__", ["ft", "nd", "lt", "sc"],
      "no raft image — rand, ralt and rasc are non-words for this age (ramp and rant stay out)"),
    cw("nd", 2, 2, 5, "stand", "sta__", ["nd", "ft", "lt", "sc"],
      "no stand image — staft, stalt and stasc are non-words (stamp stays out)"),
    apd("st", 1, 2, 5, "stop", ["stop", "top", "shop", "step"],
      { top: "D-ONSET", shop: "D-RIME-NEAR", step: "D-PATTERN-TRAP" },
      "audio replaces an action/sign interpretation; top is the s-dropped reduction"),
    ic("cl", 1, 1, 6, "clown", ["cloud", "crown", "lamp", "drum"], "cloud",
      { crown: "D-RIME-NEAR", lamp: "D-ONSET", drum: "D-PATTERN-TRAP" },
      "crown rhymes with the anchor and out-chunks the key")
  ].map(item => {
    if (item.v >= 5) item.retention = true;
    return item;
  })
};
