// Cause & Effect — v3 authored bank (wave W2). Six rotating cause-pairs are
// dead: every passage has its own causal mechanism (physical, social, animal,
// weather, mechanical, plant), and L2 carries chains, multiple causes, and
// reversal traps (D-CAUSE-REVERSE = the effect posing as the cause).
//
// Topic registry: ice on pond, dropped seeds & pigeons, squeaky door oil,
// sunflower lean, salt on chips, ferry horn fog, moth and porch light, tight
// shoes, bread left out, whistling kettle, chalk rain, dog and doorbell,
// power-cut fridge, marble ramp, sunscreen stripe, worm rain surfacing, damp
// matches, echo in tunnel, jam wasp, static balloon, tired legs stairs, plant
// no water, melted crayons car, popcorn lid, frost cracked pot, bike rust,
// library fine, muddy paw prints, ice cream drip, wind kite snap, spilled
// glitter, magnet compass, hiccups fizzy, candle draught, shadow puppet,
// snow school closed, batteries cold, seagull sandwich, overwatered cactus,
// squeanky trolley wheel, sunburn cloud myth, honey crystallise, tide sand
// castle, laughing contagious, allergy sneeze cat, torn kite tail, warm milk
// sleepy, crowded lift button, paint left open, football flat, birthday
// balloon ceiling, plug chain bath, moldy strawberry, curtains faded.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, prompt, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage, prompt, choices, media: "text", ...extra
});

export default {
  skillId: "cause_effect",
  skillName: "Cause and Effect",
  items: [
    // ============ LEVEL 1 · find_effect (8) ============
    it("find_effect", 1, 1, 1,
      "All week the nights were freezing cold. By Saturday, the park pond wore a lid of grey ice. The ducks stood on top of it, looking puzzled, and slid about on flat orange feet.",
      "What happened BECAUSE the nights were so cold?",
      [K("the pond froze over"),
       P("the ducks flew south", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the park closed", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the nights were freezing", "D-CAUSE-REVERSE")]),
    it("find_effect", 1, 1, 2,
      "Zack tipped the seed packet too fast. Seeds sprayed all over the path instead of the flower bed. Within a minute, six pigeons landed and began pecking up every last one.",
      "What happened because the seeds spilled on the path?",
      [K("pigeons came to eat them"),
       P("the flowers grew on the path", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Zack tipped the packet fast", "D-CAUSE-REVERSE"),
       P("it began to rain", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("find_effect", 1, 1, 3,
      "Gran put three drops of oil on the door hinge. She swung the door back and forth to work the oil in. After that, the door opened without its awful screech, and the baby could nap in peace.",
      "What happened after Gran oiled the hinge?",
      [K("the door stopped screeching"),
       P("the door screeched louder", "D-OPPOSITE"),
       P("Gran bought a new door", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the baby woke up crying", "D-OPPOSITE")]),
    it("find_effect", 1, 1, 4,
      "Nobody watered the classroom plant over half term. When the children came back, its leaves hung down like tired flags, and the soil in the pot was hard and pale.",
      "What happened because the plant had no water?",
      [K("its leaves drooped"),
       P("it grew taller", "D-OPPOSITE"),
       P("the children came back", "D-CAUSE-REVERSE"),
       P("its flowers turned blue", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("find_effect", 1, 2, 5,
      "Dad left the crayon box on the back seat of the car on the hottest day of summer. When Mina opened the door after lunch, the crayons had melted together into one rainbow lump.",
      "What did the hot car do to the crayons?",
      [K("melted them into one lump"),
       P("snapped them in half", "D-PLAUSIBLE-UNSUPPORTED"),
       P("made them longer", "D-OPPOSITE"),
       P("left them on the seat", "D-CAUSE-REVERSE")]),
    it("find_effect", 1, 2, 6,
      "Leah rubbed the balloon on her jumper ten times. Then she held it just above her head. Her hair rose up toward the balloon in thin strands, as if it wanted to follow it around the room.",
      "What happened because Leah rubbed the balloon?",
      [K("her hair stuck up toward it"),
       P("the balloon popped", "D-PLAUSIBLE-UNSUPPORTED"),
       P("her jumper changed colour", "D-PLAUSIBLE-UNSUPPORTED"),
       P("she held it above her head", "D-CAUSE-REVERSE")]),
    it("find_effect", 1, 2, 7,
      "Snow fell all night without stopping. By morning it lay deeper than Papa's boots. The radio read a list of closed schools, and Amini's school was third on the list.",
      "What happened because of the deep snow?",
      [K("school was closed"),
       P("the radio broke", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Papa lost his boots", "D-PLAUSIBLE-UNSUPPORTED"),
       P("snow fell all night", "D-CAUSE-REVERSE")]),
    it("find_effect", 1, 2, 8,
      "Omar forgot to press the lid onto the popcorn pot. When the corn began to pop, it leapt from the pot like tiny white fireworks, bouncing off the counter and skittering across the kitchen floor.",
      "What happened because the lid was off?",
      [K("popcorn jumped out of the pot"),
       P("the corn would not pop", "D-OPPOSITE"),
       P("the pot went cold", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Omar pressed the lid on", "D-OPPOSITE")]),

    // ============ LEVEL 1 · find_cause (8) ============
    it("find_cause", 1, 1, 1,
      "The kettle began to whistle, high and loud. Auntie hurried in from the garden, still holding her trowel, and lifted it off the heat. The whistling faded to a sigh.",
      "WHY did the kettle whistle?",
      [K("the water inside had boiled"),
       P("Auntie hurried inside", "D-CAUSE-REVERSE"),
       P("the garden was noisy", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the trowel banged it", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("find_cause", 1, 1, 2,
      "Bruno barked before anyone knocked. Two seconds later, the doorbell rang, and the delivery man stood on the step. Bruno's ears had heard the gate creak long before any human did.",
      "How did Bruno know someone was coming?",
      [K("he heard the gate creak first"),
       P("he saw the doorbell ring", "D-SEQUENCE-SWAP"),
       P("he smelled the dinner", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the delivery man called his name", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("find_cause", 1, 1, 3,
      "Hana's chalk drawing of a rocket covered the whole path. That night, rain fell for hours. In the morning only a faint pink cloud remained where the rocket had been.",
      "Why did the rocket drawing disappear?",
      [K("the rain washed the chalk away"),
       P("someone rubbed it out", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the chalk was invisible", "D-OPPOSITE"),
       P("a faint cloud remained", "D-CAUSE-REVERSE")]),
    it("find_cause", 1, 1, 4,
      "By the end of the walk, Milly was carrying her ice cream cone at a slant, licking fast. Sweet white drips raced down her fingers and dotted the pavement behind her like a trail.",
      "Why was the ice cream dripping?",
      [K("the warm day was melting it"),
       P("the cone had a hole", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Milly licked too fast", "D-CAUSE-REVERSE"),
       P("the pavement was sticky", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "licking fast is the RESPONSE to melting, not the cause of drips" }),
    it("find_cause", 1, 2, 5,
      "In the tunnel under the railway, Finn shouted 'HELLO!' His own voice bounced straight back at him, twice. He grinned and tried a bark, a whoop, and a tiny polite cough.",
      "Why did Finn's voice come back to him?",
      [K("the tunnel walls bounced the sound"),
       P("someone else was hiding there", "D-PLAUSIBLE-UNSUPPORTED"),
       P("he shouted hello", "D-CAUSE-REVERSE"),
       P("a train was passing", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("find_cause", 1, 2, 6,
      "Mo's bike had spent the whole winter outside under no cover. In spring, the chain was stiff and the handlebars wore freckles of orange rust that had not been there before.",
      "Why did the bike get rusty?",
      [K("it stood out in the wet all winter"),
       P("Mo rode it too fast", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the chain was stiff", "D-CAUSE-REVERSE"),
       P("someone painted it orange", "D-OPPOSITE")]),
    it("find_cause", 1, 2, 7,
      "At the beach, Rosa built her sandcastle close to the shining wet sand. She worked on it all afternoon. By teatime, the sea had crept up the beach, and her castle softened into a smooth little hill.",
      "Why did the castle turn into a smooth hill?",
      [K("the tide came in over it"),
       P("Rosa stamped on it", "D-OPPOSITE"),
       P("she built it all afternoon", "D-CAUSE-REVERSE"),
       P("a dog dug it up", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("find_cause", 1, 2, 8,
      "All the curtains in the front room used to be deep blue. The pair by the big sunny window are now pale, almost grey, while the pair in the shady corner still look brand new.",
      "Why did one pair of curtains go pale?",
      [K("years of sunlight faded them"),
       P("they were washed wrong once", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the shady corner protected them", "D-CAUSE-REVERSE"),
       P("someone swapped the curtains", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ============ LEVEL 1 · because_sentence (8) ============
    it("because_sentence", 1, 1, 1,
      "The moth circled the porch light for the tenth time. Round and round it went, tapping the warm glass, ignoring the whole dark garden behind it.",
      "Choose the sentence that says it best.",
      [K("The moth circled because the light attracted it."),
       P("The light glowed because the moth circled it.", "D-CAUSE-REVERSE"),
       P("The moth circled because the garden was loud.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The moth slept because the light was warm.", "D-OPPOSITE")]),
    it("because_sentence", 1, 1, 2,
      "Pia's shoes had fitted at the start of summer. Now her toes pressed the ends, and by home time her feet ached. Mum measured her feet and laughed: a whole size bigger.",
      "Choose the sentence that says it best.",
      [K("Pia's shoes hurt because her feet had grown."),
       P("Pia's feet grew because her shoes hurt.", "D-CAUSE-REVERSE"),
       P("Pia's shoes hurt because they got wet.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Pia's feet ached because she skipped lunch.", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("because_sentence", 1, 1, 3,
      "Nobody wrapped the bread after breakfast. It sat on the board all day and all night. By morning the slices were hard at the edges and curled up like little rooftops.",
      "Choose the sentence that says it best.",
      [K("The bread went hard because it was left uncovered."),
       P("The bread was left out because it went hard.", "D-CAUSE-REVERSE"),
       P("The bread went hard because the board was old.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The bread stayed soft because it was covered.", "D-OPPOSITE")]),
    it("because_sentence", 1, 1, 4,
      "The little ramp was set up on the rug. Kip let go of the marble at the top. It rolled faster and faster, shot off the end, and did not stop until it clicked against the skirting board.",
      "Choose the sentence that says it best.",
      [K("The marble rolled because the ramp sloped down."),
       P("The ramp sloped because the marble rolled.", "D-CAUSE-REVERSE"),
       P("The marble rolled because the rug was red.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The marble stopped because Kip let go.", "D-SEQUENCE-SWAP")]),
    it("because_sentence", 1, 2, 5,
      "It rained hard all morning. When it stopped, the path through the grass was dotted with worms, dozens of them, stretched out on the wet stones.",
      "Choose the sentence that says it best.",
      [K("The worms came up because their soil filled with rain."),
       P("The rain fell because the worms came up.", "D-CAUSE-REVERSE"),
       P("The worms came up because the stones were warm.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The worms hid because the path was wet.", "D-OPPOSITE")]),
    it("because_sentence", 1, 2, 6,
      "Ivy laughed first, at nothing much at all. Then her brother caught it, then Dad, then even Grandma behind her newspaper. Soon the whole room was laughing and nobody could say why.",
      "Choose the sentence that says it best.",
      [K("The family laughed because laughing spreads."),
       P("Ivy laughed because the family was laughing.", "D-SEQUENCE-SWAP"),
       P("The family laughed because the newspaper was funny.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Grandma stopped laughing because of Dad.", "D-OPPOSITE")]),
    it("because_sentence", 1, 2, 7,
      "The candle flame stood tall and still until Dad opened the hallway door. Then it bent sideways, flickered wildly, and almost went out before the door clicked shut again.",
      "Choose the sentence that says it best.",
      [K("The flame flickered because the door let in a draught."),
       P("The door opened because the flame flickered.", "D-CAUSE-REVERSE"),
       P("The flame flickered because the wax was old.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The flame grew taller because of the wind.", "D-OPPOSITE")]),
    it("because_sentence", 1, 2, 8,
      "Warm milk, a dim lamp, one last story. Halfway through the second page, Suki's eyes closed all by themselves, and Papa tiptoed out with the book still open in his hand.",
      "Choose the sentence that says it best.",
      [K("Suki fell asleep because everything made her cosy and calm."),
       P("Papa read the story because Suki fell asleep.", "D-CAUSE-REVERSE"),
       P("Suki fell asleep because the story was scary.", "D-OPPOSITE"),
       P("Suki stayed awake because of the milk.", "D-OPPOSITE")]),

    // ============ LEVEL 2 · chain (8) ============
    it("chain", 2, 1, 1,
      "A wasp smelled the open jam jar on the windowsill. It flew in through the kitchen window. Startled, Uncle Josh jumped back from the counter, knocked the flour bag with his elbow, and a white cloud settled slowly over the clean dishes.",
      "What happened RIGHT BEFORE the flour spilled?",
      [K("Uncle Josh jumped back from the counter"),
       P("the wasp smelled the jam", "D-SEQUENCE-SWAP"),
       P("flour settled on the dishes", "D-SEQUENCE-SWAP"),
       P("someone washed the dishes", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "middle-link question: jam → wasp → jump → elbow → flour" }),
    it("chain", 2, 1, 2,
      "The night frost cracked the old clay pot on the balcony. Soil trickled out of the crack all week. With half its soil gone, the rosemary plant tipped over in the next strong wind, and the falling pot startled the pigeons off the rail.",
      "Why did the rosemary tip over?",
      [K("its cracked pot had lost half its soil"),
       P("the pigeons knocked it", "D-PLAUSIBLE-UNSUPPORTED"),
       P("it startled the pigeons", "D-CAUSE-REVERSE"),
       P("the frost landed on its leaves", "D-TOPIC-ADJACENT")]),
    it("chain", 2, 1, 3,
      "Dee left the bath tap running while she answered the phone. The call was long. Water crept over the edge of the bath, found the gap by the pipe, and by the time Dee hung up, a brown ring was spreading on the kitchen ceiling below.",
      "What happened RIGHT BEFORE the mark appeared on the ceiling?",
      [K("water found the gap by the pipe"),
       P("Dee answered the phone", "D-SEQUENCE-SWAP"),
       P("Dee hung up the phone", "D-SEQUENCE-SWAP"),
       P("the kitchen ceiling was painted", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("chain", 2, 1, 4,
      "The football pitch flooded on Friday, so Saturday's match moved to the school yard. The yard's hard ground made the ball bounce twice as high, and twice-as-high bounces sailed over the fence, which is how Mr Njoku's tomatoes met seven footballs in one afternoon.",
      "Why did so many balls land in the tomatoes?",
      [K("the hard yard made the ball bounce higher"),
       P("the pitch flooded on Friday", "D-SEQUENCE-SWAP"),
       P("Mr Njoku threw them back", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the tomatoes attracted the balls", "D-CAUSE-REVERSE")],
      { note: "flood is the FIRST link, not the operative cause of the over-fence bounces" }),
    it("chain", 2, 2, 5,
      "Someone propped the freezer door open with a yoghurt pot during the party. Overnight the ice cream softened to milkshake. In the morning, the melting tub dripped through the shelf onto the peas, gluing the bags together in one frosty block.",
      "What happened RIGHT BEFORE the pea bags froze together?",
      [K("the softened ice cream dripped onto them"),
       P("the door was propped open", "D-SEQUENCE-SWAP"),
       P("the party guests arrived", "D-SEQUENCE-SWAP"),
       P("someone bought more peas", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("chain", 2, 2, 6,
      "The lift was crowded, and somebody's rucksack pressed every button at once. The lift began stopping at every single floor. All the stopping made Priya late to the dentist upstairs, and her name was called just as she burst out of the lift doors, breathing hard.",
      "Why was Priya nearly late?",
      [K("the lift stopped at every floor"),
       P("her name was called early", "D-PLAUSIBLE-UNSUPPORTED"),
       P("she pressed every button", "D-PLAUSIBLE-UNSUPPORTED"),
       P("she burst out of the doors", "D-CAUSE-REVERSE")]),
    it("chain", 2, 2, 7,
      "A strong gust snapped the kite's thin tail. Without its tail, the kite began spinning instead of gliding. The spinning wound the string around the flagpole three times, and that is where the kite stayed, rattling like a trapped bird, until the caretaker fetched his ladder.",
      "Why did the string wrap around the flagpole?",
      [K("the tailless kite went into a spin"),
       P("the caretaker wound it there", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the kite rattled like a bird", "D-CAUSE-REVERSE"),
       P("the string was too short", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("chain", 2, 2, 8,
      "The bathroom mirror steamed up during Amir's hot shower. He wiped it with a towel, which left fine fluff all over the glass. When the mirror dried, the fluff showed worse than the steam had, so he washed the mirror properly, which is how one hot shower led to cleaning the whole bathroom.",
      "What happened RIGHT BEFORE Amir washed the mirror properly?",
      [K("dried fluff showed all over the glass"),
       P("the shower steamed the mirror", "D-SEQUENCE-SWAP"),
       P("he cleaned the whole bathroom", "D-SEQUENCE-SWAP"),
       P("the towel fell in the bath", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ============ LEVEL 2 · multiple_causes (8) ============
    it("multiple_causes", 2, 1, 1,
      "The school fair made more money than ever this year. The weather was warm and dry, so crowds stayed all afternoon. The new baking stall sold out twice. And because the fair fell on payday weekend, purses were a little fuller than usual.",
      "Which of these was NOT a reason the fair did well?",
      [K("the fair sold out of tickets early"),
       P("the warm, dry weather", "D-DETAIL-AS-MAIN"),
       P("the popular baking stall", "D-DETAIL-AS-MAIN"),
       P("payday weekend", "D-DETAIL-AS-MAIN")],
      { note: "NOT-a-cause format: three real causes, one invented" }),
    it("multiple_causes", 2, 1, 2,
      "Rui slept through his alarm for three reasons. He had stayed up late finishing his comic. His phone had died in the night, so the alarm never rang. And the thick new curtains kept his room as dark as a cave long past sunrise.",
      "Which of these was NOT a reason Rui overslept?",
      [K("his little sister woke him early"),
       P("staying up late with his comic", "D-DETAIL-AS-MAIN"),
       P("his phone dying overnight", "D-DETAIL-AS-MAIN"),
       P("the thick dark curtains", "D-DETAIL-AS-MAIN")]),
    it("multiple_causes", 2, 1, 3,
      "The cactus on the windowsill turned soft and brown. Grandpa had watered it every single day, though a cactus wants water rarely. The pot had no hole, so the water sat around its roots. And the cold glass at night chilled it again and again.",
      "Which of these was NOT a cause of the cactus dying?",
      [K("too little water"),
       P("daily watering", "D-DETAIL-AS-MAIN"),
       P("a pot with no drain hole", "D-DETAIL-AS-MAIN"),
       P("cold nights by the glass", "D-DETAIL-AS-MAIN")],
      { note: "the invented option is the intuitive-but-backwards cause" }),
    it("multiple_causes", 2, 1, 4,
      "Half the class had colds by Friday. All week the rain had kept everyone crowded indoors at break. The window monitor was away, so no one aired the stuffy room. And two children had come in sniffing on Monday instead of resting at home.",
      "Which of these was NOT a reason the cold spread?",
      [K("the class played outside too long"),
       P("crowding indoors all week", "D-DETAIL-AS-MAIN"),
       P("the unaired, stuffy room", "D-DETAIL-AS-MAIN"),
       P("children coming in already sniffing", "D-DETAIL-AS-MAIN")]),
    it("multiple_causes", 2, 2, 5,
      "The old rope swing finally snapped on Sunday. Years of rain and sun had chewed at the fibres. The knot rubbed the same branch groove every swing. And that afternoon, for the first time, two riders had squeezed on together.",
      "Which of these was NOT a cause of the snap?",
      [K("someone cut the rope with scissors"),
       P("years of weather wearing the fibres", "D-DETAIL-AS-MAIN"),
       P("the knot rubbing the branch", "D-DETAIL-AS-MAIN"),
       P("two riders at once", "D-DETAIL-AS-MAIN")]),
    it("multiple_causes", 2, 2, 6,
      "The bakery queue stretched round the corner on Saturday. A food show had filmed there on Tuesday, and clips were everywhere. The rival bakery across town was shut for repairs. And Saturday was the first day of the famous plum tarts.",
      "Which of these was NOT a reason for the long queue?",
      [K("the bakery had cut all its prices"),
       P("the food show clips", "D-DETAIL-AS-MAIN"),
       P("the rival bakery being shut", "D-DETAIL-AS-MAIN"),
       P("the first plum tarts of the year", "D-DETAIL-AS-MAIN")]),
    it("multiple_causes", 2, 2, 7,
      "Nobody heard the phone ring at lunch. The blender was roaring through a smoothie. The radio was on for the cricket. And the phone itself was buried somewhere under the sofa cushions, ringing into the springs.",
      "Which of these was NOT a reason the ring went unheard?",
      [K("the phone was switched off"),
       P("the roaring blender", "D-DETAIL-AS-MAIN"),
       P("the radio playing cricket", "D-DETAIL-AS-MAIN"),
       P("the phone buried in the sofa", "D-DETAIL-AS-MAIN")]),
    it("multiple_causes", 2, 2, 8,
      "The little boat was hard to row home. The tide had turned against them. The wind blew straight off the shore into their faces. And the afternoon's happy swimming had left both rowers with arms like wet spaghetti.",
      "Which of these was NOT a reason the rowing was hard?",
      [K("a leak let water into the boat"),
       P("the tide against them", "D-DETAIL-AS-MAIN"),
       P("the wind in their faces", "D-DETAIL-AS-MAIN"),
       P("tired arms from swimming", "D-DETAIL-AS-MAIN")]),

    // ============ LEVEL 2 · reversal_trap (8) ============
    it("reversal_trap", 2, 1, 1,
      "Wherever the school cat sat, children gathered. New visitors sometimes thought the children attracted the cat. The dinner ladies knew better: the cat chose the sunniest spot first, and the children simply followed him to it.",
      "What REALLY made children and cat end up together?",
      [K("the cat picked a spot and children followed"),
       P("the children picked a spot and the cat followed", "D-CAUSE-REVERSE"),
       P("the dinner ladies called them together", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the sun followed the children", "D-CAUSE-REVERSE")]),
    it("reversal_trap", 2, 1, 2,
      "On sports day, Jo wore her lucky red socks and won three races. 'The socks make me fast,' she told everyone. Her coach smiled and pointed at the training chart on the wall: every square of the last two months was ticked.",
      "What does the passage suggest REALLY made Jo fast?",
      [K("two months of ticked-off training"),
       P("the lucky red socks", "D-CAUSE-REVERSE"),
       P("winning three races", "D-CAUSE-REVERSE"),
       P("the coach's smile", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("reversal_trap", 2, 1, 3,
      "Every time the floorboard by the kitchen creaked, Biscuit the dog appeared, and moments later food hit his bowl. A visitor might think the creak fed the dog. In truth, Dad stepping on that board meant Dad was fetching the dog food tin from that exact cupboard.",
      "What REALLY brought the food?",
      [K("Dad going to the food cupboard"),
       P("the creaking floorboard itself", "D-CAUSE-REVERSE"),
       P("Biscuit appearing in the kitchen", "D-CAUSE-REVERSE"),
       P("the visitor watching", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("reversal_trap", 2, 1, 4,
      "The louder the crowd sang, the harder the band played. And the harder the band played, the louder the crowd sang. By the last song, no one could say who was driving whom — the whole hall had become one big engine of noise.",
      "What does the passage say about the noise?",
      [K("crowd and band drove each other louder"),
       P("only the band made the crowd loud", "D-CAUSE-REVERSE"),
       P("only the crowd made the band loud", "D-CAUSE-REVERSE"),
       P("the hall's engine made the noise", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "two-way causation — the honest answer is the loop itself" }),
    it("reversal_trap", 2, 2, 5,
      "Umbrellas do not bring the rain, Gran says, though on our street it can look that way: the moment umbrellas bloom along the pavement, down it comes. Of course, everyone opens them because the first drops have already begun to fall.",
      "Why do umbrellas and rain arrive together?",
      [K("first drops make people open umbrellas"),
       P("open umbrellas pull down the rain", "D-CAUSE-REVERSE"),
       P("Gran signals the street", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the pavement attracts clouds", "D-CAUSE-REVERSE")]),
    it("reversal_trap", 2, 2, 6,
      "Whenever the ice-cream van's tune started, Tam's tummy rumbled. Tam decided the tune made him hungry. Mum laughed: the van always came at four o'clock — exactly the hour a boy who skipped his lunchtime peas gets hungry anyway.",
      "What REALLY explains Tam's four o'clock hunger?",
      [K("hours had passed since his small lunch"),
       P("the van's tune made him hungry", "D-CAUSE-REVERSE"),
       P("his rumbling tummy called the van", "D-CAUSE-REVERSE"),
       P("Mum's laughing reminded him", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("reversal_trap", 2, 2, 7,
      "The rooster crowed, and the sun came up. It happened every single morning, in that order. The farmer liked to joke that his rooster raised the sun. The vet put it differently: the first grey light wakes the rooster, and the crowing follows.",
      "Which explanation does the passage support?",
      [K("dawn light wakes the rooster, so he crows"),
       P("the rooster's crow raises the sun", "D-CAUSE-REVERSE"),
       P("the farmer wakes the rooster", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the vet taught the rooster to crow", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("reversal_trap", 2, 2, 8,
      "Firefighters arrive at big fires, and small fires have no firefighters at all. Looking only at that, you might decide firefighters make fires bigger. Ana's project poster explained it the right way round: the bigger the fire already is, the more firefighters get sent to it.",
      "What is the right way round, according to the poster?",
      [K("big fires bring many firefighters"),
       P("many firefighters make fires big", "D-CAUSE-REVERSE"),
       P("small fires send firefighters away", "D-CAUSE-REVERSE"),
       P("posters cause fewer fires", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ============ RETENTION RESERVE (8 L1 + 8 L2) ============
    it("find_effect", 1, 1, 9,
      "Joss shook the fizzy drink can all the way home, just to hear it slosh. When Dad opened it at the table, a hissing fountain leapt out and rained on the tablecloth.",
      "What happened because the can was shaken?",
      [K("the drink sprayed out when opened"),
       P("the drink went flat", "D-OPPOSITE"),
       P("Dad opened it at the table", "D-CAUSE-REVERSE"),
       P("the can went cold", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("find_effect", 1, 2, 10,
      "The torch had sat in the freezing shed all winter. When Ben clicked it on for the camp-out, the beam glowed dull orange for a minute and then gave up completely.",
      "What did the long cold do to the torch?",
      [K("it drained the batteries"),
       P("it cracked the glass", "D-PLAUSIBLE-UNSUPPORTED"),
       P("it made the beam brighter", "D-OPPOSITE"),
       P("it started the camp-out", "D-CAUSE-REVERSE")], { retention: true }),
    it("find_cause", 1, 1, 9,
      "Auntie Bel sneezed six times before she even said hello. Her eyes were pink and watery. On her lap, completely comfortable, sat the neighbour's fluffy white cat.",
      "Why was Auntie Bel sneezing?",
      [K("the cat's fur set off her allergy"),
       P("she had caught a cold saying hello", "D-PLAUSIBLE-UNSUPPORTED"),
       P("her watery eyes made her sneeze", "D-CAUSE-REVERSE"),
       P("the neighbour was dusty", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("find_cause", 1, 2, 10,
      "The strawberries were forgotten at the back of the fridge for two weeks. When Val found the box, a soft grey fur had crept over every berry.",
      "Why did the strawberries grow fur?",
      [K("mould grew on them over the weeks"),
       P("the fridge froze them", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Val found the box", "D-CAUSE-REVERSE"),
       P("a mouse slept on them", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("because_sentence", 1, 1, 9,
      "The plug chain had slipped off its hook into the water. Nobody noticed while the bath emptied itself, glug by glug, until only a cold puddle was left around Otto's toes.",
      "Choose the sentence that says it best.",
      [K("The bath emptied because the plug had come loose."),
       P("The plug came loose because the bath emptied.", "D-CAUSE-REVERSE"),
       P("The bath emptied because the water was cold.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The bath stayed full because of the chain.", "D-OPPOSITE")], { retention: true }),
    it("because_sentence", 1, 2, 10,
      "Nia's birthday balloon slipped out of her hand indoors. It sailed straight up and bumped softly against the ceiling, where it stayed all week, just out of reach of the broom.",
      "Choose the sentence that says it best.",
      [K("The balloon rose because the gas inside was lighter than air."),
       P("The ceiling pulled the balloon up.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The balloon rose because Nia held it tight.", "D-OPPOSITE"),
       P("The broom kept the balloon up.", "D-CAUSE-REVERSE")], { retention: true }),
    it("find_effect", 1, 1, 11,
      "A seagull spotted Pia's chip bag the moment she sat on the sea wall. It swooped once, low and bold, and a heartbeat later the biggest chip was travelling down the beach at wing-speed.",
      "What happened because the seagull swooped?",
      [K("it stole a chip"),
       P("Pia sat on the wall", "D-CAUSE-REVERSE"),
       P("the bag blew away", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the tide came in", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("find_cause", 1, 1, 11,
      "The trolley sang a squeaky song all round the supermarket — eee-aww, eee-aww. Dad crouched by the front wheel and found a flattened piece of chewing gum stuck right around it.",
      "Why did the trolley squeak?",
      [K("gum was stuck around a wheel"),
       P("the shopping was too heavy", "D-PLAUSIBLE-UNSUPPORTED"),
       P("its song annoyed Dad", "D-CAUSE-REVERSE"),
       P("the floor was wet", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("chain", 2, 1, 9,
      "Marta's hiccups started when she gulped her fizzy lemonade too fast. The hiccups made her giggle. The giggling shook more bubbles loose, which brought more hiccups, and soon she had to put the glass down until both the giggles and the hiccups wore themselves out.",
      "What started the whole chain?",
      [K("gulping the fizzy drink too fast"),
       P("the giggling", "D-SEQUENCE-SWAP"),
       P("putting the glass down", "D-SEQUENCE-SWAP"),
       P("a scary story", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("chain", 2, 2, 10,
      "The paint tin was left open overnight. By morning a skin had formed across the top. When Dad stirred the skin in, little rubbery flecks spread through the paint, and every stroke he brushed onto the door left tiny lumps, so the whole door had to be sanded and painted again.",
      "Why did the door need painting twice?",
      [K("flecks from the paint skin lumped the first coat"),
       P("the tin was left open overnight", "D-SEQUENCE-SWAP"),
       P("Dad sanded the door", "D-SEQUENCE-SWAP"),
       P("the brush was too wide", "D-PLAUSIBLE-UNSUPPORTED")],
      { retention: true, note: "the open tin is the first link; the operative cause of repainting is the lumpy coat" }),
    it("multiple_causes", 2, 1, 9,
      "The washing took all day to dry. The morning was misty and damp. The line hung in the shadiest corner of the yard. And Mum had wrung nothing out, pegging everything up still dripping.",
      "Which of these was NOT a reason the washing dried slowly?",
      [K("a hot wind blew all day"),
       P("the damp, misty morning", "D-DETAIL-AS-MAIN"),
       P("the shady corner", "D-DETAIL-AS-MAIN"),
       P("clothes pegged up dripping", "D-DETAIL-AS-MAIN")], { retention: true }),
    it("multiple_causes", 2, 2, 10,
      "The school hamster escaped in the night. His cage door had a weak latch that never quite clicked. The caretaker had moved the cage next to the shelf, making a perfect bridge. And carrot night meant the door had been opened one extra time.",
      "Which of these was NOT a cause of the escape?",
      [K("a child took him home"),
       P("the weak latch", "D-DETAIL-AS-MAIN"),
       P("the shelf right beside the cage", "D-DETAIL-AS-MAIN"),
       P("the extra carrot-night opening", "D-DETAIL-AS-MAIN")], { retention: true }),
    it("reversal_trap", 2, 1, 9,
      "Ice-cream sales and sunburn both jump in July. One silly newspaper joked that ice cream causes sunburn. Class 4 worked out the truth for their science wall: hot sunny weather causes BOTH — more cones eaten, more skin burned.",
      "What REALLY links ice cream and sunburn?",
      [K("hot sun causes both at once"),
       P("ice cream causes sunburn", "D-CAUSE-REVERSE"),
       P("sunburn makes people buy cones", "D-CAUSE-REVERSE"),
       P("the newspaper causes July", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("reversal_trap", 2, 2, 10,
      "Grandad noticed that the streetlights always came on just as he yawned his first evening yawn. 'My yawns switch them on,' he liked to say. Actually both had the same cause: the sky growing dark — dark enough for lights, late enough for yawns.",
      "What REALLY explains the lights and the yawns?",
      [K("evening darkness triggers both"),
       P("Grandad's yawns switch on the lights", "D-CAUSE-REVERSE"),
       P("the streetlights make him yawn", "D-CAUSE-REVERSE"),
       P("the switch is in his chair", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("chain", 2, 1, 11,
      "The magnet in Theo's pocket sat right next to his compass on the hike. The needle swung to point at the magnet instead of north. Trusting the needle, the group turned left at the fork, and the left path took them in a long loop back to their own starting stile.",
      "Why did the group walk in a loop?",
      [K("the magnet had pulled the compass off north"),
       P("the compass broke in the rain", "D-PLAUSIBLE-UNSUPPORTED"),
       P("they turned left at the fork", "D-SEQUENCE-SWAP"),
       P("the stile moved", "D-OPPOSITE")], { retention: true }),
    it("multiple_causes", 2, 1, 11,
      "The candles on the cake would not stay lit. The back door stood open to the garden. The ceiling fan spun on full. And two excited cousins were bouncing on the bench, puffing with laughter right at candle height.",
      "Which of these was NOT a reason the candles kept going out?",
      [K("the wax was too soft"),
       P("the open back door", "D-DETAIL-AS-MAIN"),
       P("the ceiling fan", "D-DETAIL-AS-MAIN"),
       P("the puffing cousins", "D-DETAIL-AS-MAIN")], { retention: true })
  ]
};
