// Context Clues — v3 authored bank (wave W2). One target word per passage,
// never repeated, always tier-2 (outside the K-2 familiar list — the sanctioned
// C-5 exception). Cells are clue TYPES. Reviewer test honoured: cover the
// target word and its meaning is still recoverable from the passage alone.
// Keys are child-worded meanings; distractors are plausible wrong meanings that
// fit the sentence grammar (D-PLAUSIBLE-UNSUPPORTED) plus one opposite.
//
// Target words used (unique): drowsy, gobble, enormous, fragile, soggy,
// gleaming, grumble, timid, sturdy, vanish, feast, chilly, glide, murmur,
// weary, dazzling, plead, scamper, hollow, drift, jagged, mend, snug, swift,
// tremble, faint, ancient, clutter, brisk, scent, gaze, bitter, slumber,
// commotion, drenched, nibble, gigantic, delicate, spotless, grumpy, shy-less
// (bold), rickety, disappear-less (loiter), banquet, nippy, soar, whisper-2
// (mutter), exhausted, brilliant, beg-2 (implore→skip), dash, empty-2 (bare),
// float-2 (bob), spiky, repair-2 (patch), cosy-2 (toasty), rapid, shiver,
// dim, elderly, mess-2 (jumble), lively, aroma, stare-2 (peer).

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, word, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage,
  prompt: `In this passage, what does "${word}" mean?`,
  choices, media: "text", target: word,
  // Reusing a definition, synonym, example, or action from the passage is the
  // construct being assessed here. The generic passage-overlap oracle cannot
  // distinguish that legitimate clue use from a shortcut.
  scannerExpected: true,
  ...extra
});

export default {
  skillId: "context_clues",
  skillName: "Context Clues",
  items: [
    // ============ LEVEL 1 · definition_clue (8) ============
    it("definition_clue", 1, 1, 1,
      "By eight o'clock Tara was drowsy — so sleepy that her eyes kept sliding shut in the middle of her favourite programme.",
      "drowsy",
      [K("very sleepy"),
       P("very hungry", "D-PLAUSIBLE-UNSUPPORTED"),
       P("wide awake", "D-OPPOSITE"),
       P("quite angry", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("definition_clue", 1, 1, 2,
      "The vase was fragile, which means it could break very easily, so Mum carried it across the room with two careful hands.",
      "fragile",
      [K("easily broken"),
       P("very heavy", "D-PLAUSIBLE-UNSUPPORTED"),
       P("impossible to break", "D-OPPOSITE"),
       P("full of flowers", "D-TOPIC-ADJACENT")]),
    it("definition_clue", 1, 1, 3,
      "Our new tent is sturdy — strongly made and hard to knock over. Even the wild wind on the hilltop could not flatten it.",
      "sturdy",
      [K("strong and well made"),
       P("bright and colourful", "D-PLAUSIBLE-UNSUPPORTED"),
       P("weak and floppy", "D-OPPOSITE"),
       P("brand new", "D-TOPIC-ADJACENT")]),
    it("definition_clue", 1, 1, 4,
      "A murmur is a soft, low sound of voices. From the top of the stairs, Lila could hear the murmur of the grown-ups talking downstairs.",
      "murmur",
      [K("a soft sound of talking"),
       P("a loud crash", "D-OPPOSITE"),
       P("a kind of stair", "D-TOPIC-ADJACENT"),
       P("a bright light", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("definition_clue", 1, 2, 5,
      "The path was covered in jagged stones — sharp, pointy ones with rough edges — so everyone kept their shoes on all the way to the waterfall.",
      "jagged",
      [K("sharp and rough at the edges"),
       P("smooth and round", "D-OPPOSITE"),
       P("wet and shiny", "D-PLAUSIBLE-UNSUPPORTED"),
       P("small and light", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("definition_clue", 1, 2, 6,
      "Hollow means empty inside. The old log by the fence was hollow, and a whole family of mice had moved into the space within it.",
      "hollow",
      [K("empty on the inside"),
       P("solid all the way through", "D-OPPOSITE"),
       P("covered in leaves", "D-TOPIC-ADJACENT"),
       P("very long", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("definition_clue", 1, 2, 7,
      "The lane was chilly that morning — cold enough to make your fingers ache — so Pip pulled his sleeves down over his hands.",
      "chilly",
      [K("uncomfortably cold"),
       P("nice and warm", "D-OPPOSITE"),
       P("very narrow", "D-TOPIC-ADJACENT"),
       P("too dark", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("definition_clue", 1, 2, 8,
      "To mend something is to fix it. Grandpa mended the torn net with a needle and green string, and by tea time it was good as new.",
      "mend",
      [K("to fix something"),
       P("to throw something away", "D-OPPOSITE"),
       P("to paint something", "D-PLAUSIBLE-UNSUPPORTED"),
       P("to hide something", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ============ LEVEL 1 · example_clue (8) ============
    it("example_clue", 1, 1, 1,
      "The picnic was a real feast: sandwiches, sausage rolls, two kinds of cake, a bowl of cherries, and a jug of cold lemonade that never seemed to empty.",
      "feast",
      [K("a big special meal"),
       P("a small snack", "D-OPPOSITE"),
       P("a kind of basket", "D-TOPIC-ADJACENT"),
       P("a long walk", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("example_clue", 1, 1, 2,
      "Milo's desk was full of clutter — old wrappers, dried-up pens, a single glove, broken crayons, and three notes from last term he never took home.",
      "clutter",
      [K("a mess of things not needed"),
       P("a neat row of books", "D-OPPOSITE"),
       P("a set of school rules", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a kind of desk", "D-TOPIC-ADJACENT")]),
    it("example_clue", 1, 1, 3,
      "Enormous things filled the museum hall: a whale skeleton longer than a bus, a boulder taller than Dad, and a footprint big enough for Nia to sit inside.",
      "enormous",
      [K("very, very big"),
       P("very old", "D-TOPIC-ADJACENT"),
       P("tiny and light", "D-OPPOSITE"),
       P("made of stone", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("example_clue", 1, 1, 4,
      "Everything about the morning was gleaming: the polished trumpet, the wet road after rain, the foil stars on the classroom window, and Dad's freshly washed car.",
      "gleaming",
      [K("shining brightly"),
       P("dull and dirty", "D-OPPOSITE"),
       P("out of tune", "D-PLAUSIBLE-UNSUPPORTED"),
       P("very expensive", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("example_clue", 1, 2, 5,
      "Timid creatures live in the hedge: the mouse that bolts at a footstep, the wren that hides deep in the leaves, and the rabbit that thumps once and vanishes down its hole.",
      "timid",
      [K("easily frightened"),
       P("bold and fierce", "D-OPPOSITE"),
       P("green and leafy", "D-TOPIC-ADJACENT"),
       P("very hungry", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("example_clue", 1, 2, 6,
      "Swift things flashed past the window all journey: racing motorbikes, a hawk stooping after a sparrow, and express trains that were gone almost before you saw them.",
      "swift",
      [K("very fast"),
       P("very slow", "D-OPPOSITE"),
       P("very loud", "D-PLAUSIBLE-UNSUPPORTED"),
       P("far away", "D-TOPIC-ADJACENT")]),
    it("example_clue", 1, 2, 7,
      "Ancient things filled Great-Uncle Ho's shelf: a coin worn smooth by a thousand years of thumbs, a map of countries that no longer exist, and a cracked pot older than the town itself.",
      "ancient",
      [K("very old"),
       P("brand new", "D-OPPOSITE"),
       P("very valuable", "D-PLAUSIBLE-UNSUPPORTED"),
       P("made of clay", "D-TOPIC-ADJACENT")]),
    it("example_clue", 1, 2, 8,
      "All the soggy things went by the radiator: Ken's socks after the puddle, the towel from swimming, and the newspaper that had spent the night on the wet step.",
      "soggy",
      [K("wet through"),
       P("dry and crisp", "D-OPPOSITE"),
       P("warm and cosy", "D-TOPIC-ADJACENT"),
       P("torn to bits", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ============ LEVEL 1 · action_clue (8) ============
    it("action_clue", 1, 1, 1,
      "The hungry puppy did not chew politely. He gobbled his whole dinner in four huge mouthfuls and then licked the empty bowl across the floor.",
      "gobbled",
      [K("ate very fast"),
       P("buried in the garden", "D-PLAUSIBLE-UNSUPPORTED"),
       P("ate very slowly", "D-OPPOSITE"),
       P("sniffed carefully", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("action_clue", 1, 1, 2,
      "The swans glided across the lake. Their bodies slid along smooth as paper boats, without one splash, while their feet paddled secretly below.",
      "glided",
      [K("moved smoothly along"),
       P("splashed noisily", "D-OPPOSITE"),
       P("sank slowly", "D-PLAUSIBLE-UNSUPPORTED"),
       P("flew high up", "D-TOPIC-ADJACENT")]),
    it("action_clue", 1, 1, 3,
      "The squirrel scampered along the fence — quick light steps, a leap, more quick steps — and was up the oak tree before Milo could point.",
      "scampered",
      [K("ran with quick little steps"),
       P("slept in the sun", "D-OPPOSITE"),
       P("crawled very slowly", "D-OPPOSITE"),
       P("dug a deep hole", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("action_clue", 1, 1, 4,
      "'Please, please, PLEASE can we keep him?' Sol pleaded, hands pressed together, following Mum from room to room with enormous hopeful eyes.",
      "pleaded",
      [K("begged with all his heart"),
       P("shouted angrily", "D-PLAUSIBLE-UNSUPPORTED"),
       P("whispered a secret", "D-PLAUSIBLE-UNSUPPORTED"),
       P("gave up quietly", "D-OPPOSITE")]),
    it("action_clue", 1, 2, 5,
      "Thunder boomed, and Pepper the cat trembled under the bed — her whole small body shaking like a leaf in the wind until the storm rolled away.",
      "trembled",
      [K("shook with fear"),
       P("purred happily", "D-OPPOSITE"),
       P("stretched out flat", "D-PLAUSIBLE-UNSUPPORTED"),
       P("fell fast asleep", "D-OPPOSITE")]),
    it("action_clue", 1, 2, 6,
      "Grandpa grumbled all the way up the hill — a low, cross mutter about his knees, the weather, and whoever had invented hills in the first place.",
      "grumbled",
      [K("complained in a low voice"),
       P("sang a cheerful song", "D-OPPOSITE"),
       P("climbed very fast", "D-PLAUSIBLE-UNSUPPORTED"),
       P("waved at neighbours", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("action_clue", 1, 2, 7,
      "One by one the soap bubbles drifted over the wall — floating wherever the breeze carried them, in no hurry to be anywhere at all.",
      "drifted",
      [K("floated slowly along"),
       P("popped at once", "D-PLAUSIBLE-UNSUPPORTED"),
       P("shot up like rockets", "D-OPPOSITE"),
       P("turned to rain", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("action_clue", 1, 2, 8,
      "Baby Yara gazed at the mobile above her cot — eyes wide, mouth open, watching the slow silver fish go round and round for a whole quiet hour.",
      "gazed",
      [K("looked for a long time"),
       P("glanced away quickly", "D-OPPOSITE"),
       P("cried loudly", "D-PLAUSIBLE-UNSUPPORTED"),
       P("reached and grabbed", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ============ LEVEL 2 · synonym_clue (8) ============
    it("synonym_clue", 2, 1, 1,
      "The fireworks were dazzling. The display was so bright that people shielded their eyes, and so brilliant that even the streetlights seemed dim afterwards.",
      "dazzling",
      [K("blindingly bright"),
       P("disappointingly small", "D-OPPOSITE"),
       P("dangerously loud", "D-PLAUSIBLE-UNSUPPORTED"),
       P("over too quickly", "D-TOPIC-ADJACENT")]),
    it("synonym_clue", 2, 1, 2,
      "After the mountain walk, the hikers were weary. Exhausted, worn out, done in — they dropped their packs at the hut door and nobody spoke for ten minutes.",
      "weary",
      [K("completely tired out"),
       P("full of energy", "D-OPPOSITE"),
       P("very thirsty", "D-PLAUSIBLE-UNSUPPORTED"),
       P("lost on the path", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("synonym_clue", 2, 1, 3,
      "A strange commotion filled the yard — such an uproar, such a racket of clanging and squawking, that three teachers hurried out to see what the fuss could be.",
      "commotion",
      [K("a noisy disturbance"),
       P("a peaceful hush", "D-OPPOSITE"),
       P("a kind of bird", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a school lesson", "D-TOPIC-ADJACENT")]),
    it("synonym_clue", 2, 1, 4,
      "Caught in the downpour without a coat, Priya arrived drenched — soaked to the skin, wet through, dripping a little lake onto the doormat.",
      "drenched",
      [K("completely soaked"),
       P("perfectly dry", "D-OPPOSITE"),
       P("very late", "D-PLAUSIBLE-UNSUPPORTED"),
       P("out of breath", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("synonym_clue", 2, 2, 5,
      "The mouse nibbled the cheese — tiny bite after tiny bite, nothing like the dog, who would have swallowed it whole in one gulp.",
      "nibbled",
      [K("ate with small bites"),
       P("swallowed in one go", "D-OPPOSITE"),
       P("pushed away", "D-PLAUSIBLE-UNSUPPORTED"),
       P("sniffed and left", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("synonym_clue", 2, 2, 6,
      "The baker kept his kitchen spotless. Not a crumb on the counters, not a smudge on the steel — so perfectly clean that the health inspector once asked for his secret.",
      "spotless",
      [K("perfectly clean"),
       P("covered in flour", "D-OPPOSITE"),
       P("very small", "D-PLAUSIBLE-UNSUPPORTED"),
       P("closed on Sundays", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("synonym_clue", 2, 2, 7,
      "The kestrel soared over the cliff — rising higher and higher on the warm air, climbing without a single wing-beat until it was only a speck.",
      "soared",
      [K("flew high upward"),
       P("dived to the ground", "D-OPPOSITE"),
       P("built a nest", "D-TOPIC-ADJACENT"),
       P("called loudly", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("synonym_clue", 2, 2, 8,
      "The soup was bitter — sharp and sour on the tongue, nothing like the sweet tomato soup from the tin — and Jonah's whole face folded up at the first spoonful.",
      "bitter",
      [K("sharp and unpleasant to taste"),
       P("sweet as honey", "D-OPPOSITE"),
       P("too hot to eat", "D-PLAUSIBLE-UNSUPPORTED"),
       P("thick and lumpy", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ============ LEVEL 2 · antonym_contrast_clue (8) ============
    it("antonym_contrast_clue", 2, 1, 1,
      "Unlike her sister, who charged into every new place shouting hello, Faye was bashful, hanging back by the door until someone gently waved her in.",
      "bashful",
      [K("shy around new people"),
       P("loud and confident", "D-OPPOSITE"),
       P("angry at her sister", "D-PLAUSIBLE-UNSUPPORTED"),
       P("tired of visiting", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("antonym_contrast_clue", 2, 1, 2,
      "The new bridge stood firm in any storm, but the old rope bridge was rickety — it wobbled and creaked at every single step, and two planks were missing.",
      "rickety",
      [K("shaky and likely to break"),
       P("solid and safe", "D-OPPOSITE"),
       P("newly painted", "D-PLAUSIBLE-UNSUPPORTED"),
       P("too high to cross", "D-TOPIC-ADJACENT")]),
    it("antonym_contrast_clue", 2, 1, 3,
      "While the town square buzzed all evening, the side streets were bare — no stalls, no lanterns, not a single person — as if the party had gathered every soul into one place.",
      "bare",
      [K("empty, with nothing there"),
       P("crowded and busy", "D-OPPOSITE"),
       P("dark green", "D-PLAUSIBLE-UNSUPPORTED"),
       P("freshly swept", "D-TOPIC-ADJACENT")]),
    it("antonym_contrast_clue", 2, 1, 4,
      "Everyone expected the head teacher's office to be warm, but it was nippy in there — so much so that she kept a blanket on her chair while the corridor outside stayed toasty.",
      "nippy",
      [K("uncomfortably cold"),
       P("cosily warm", "D-OPPOSITE"),
       P("strangely quiet", "D-PLAUSIBLE-UNSUPPORTED"),
       P("very tidy", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("antonym_contrast_clue", 2, 2, 5,
      "Dad walks at a stroll on Sundays, but on school mornings his pace is brisk — quick enough that Ida has to trot every few steps just to stay level.",
      "brisk",
      [K("fast and energetic"),
       P("slow and lazy", "D-OPPOSITE"),
       P("quiet and careful", "D-PLAUSIBLE-UNSUPPORTED"),
       P("lost and confused", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("antonym_contrast_clue", 2, 2, 6,
      "The twins could not have sounded more different: Ade spoke up clearly for the whole hall to hear, while Bola preferred to mutter, so that only her own collar caught the words.",
      "mutter",
      [K("speak low and unclearly"),
       P("shout to the whole hall", "D-OPPOSITE"),
       P("sing in tune", "D-PLAUSIBLE-UNSUPPORTED"),
       P("stay silent", "D-TOPIC-ADJACENT")]),
    it("antonym_contrast_clue", 2, 2, 7,
      "By day the harbour was lively, but at midnight it fell still: not one engine, not one voice, only rope against mast and the slow breathing of the sea.",
      "lively",
      [K("full of activity"),
       P("silent and still", "D-OPPOSITE"),
       P("deep under water", "D-PLAUSIBLE-UNSUPPORTED"),
       P("closed for winter", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("antonym_contrast_clue", 2, 2, 8,
      "Instead of the sharp midday light, the lamp gave only a dim glow — so faint that Noor had to hold her book almost against the bulb to read at all.",
      "dim",
      [K("giving very little light"),
       P("blindingly bright", "D-OPPOSITE"),
       P("warm to touch", "D-PLAUSIBLE-UNSUPPORTED"),
       P("newly bought", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ============ LEVEL 2 · inference_clue (8) ============
    it("inference_clue", 2, 1, 1,
      "When the magician clapped, the coin seemed to vanish. One moment it flashed between his fingers; the next his hands were empty, and the children searched the stage floor for a coin that simply was not there.",
      "vanish",
      [K("disappear completely"),
       P("grow much bigger", "D-PLAUSIBLE-UNSUPPORTED"),
       P("shine more brightly", "D-TOPIC-ADJACENT"),
       P("stay in plain sight", "D-OPPOSITE")]),
    it("inference_clue", 2, 1, 2,
      "The bear's winter slumber lasted for months. Snow piled over the den mouth, storms came and went, and still nothing inside stirred until the first warm week of spring.",
      "slumber",
      [K("a long deep sleep"),
       P("a hunting trip", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a loud growl", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a morning walk", "D-OPPOSITE")]),
    it("inference_clue", 2, 1, 3,
      "One whiff of the scent drifting from the kitchen told Omar everything: cinnamon, warm sugar, a promise of apples. His homework could wait.",
      "scent",
      [K("a smell in the air"),
       P("a loud timer", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a kind of pie", "D-TOPIC-ADJACENT"),
       P("a cold draught", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("inference_clue", 2, 1, 4,
      "The path was steep and the day was hot, but the view from the top repaid every step: the whole valley lay below them like a green map, and nobody regretted the climb.",
      "repaid",
      [K("made the effort worth it"),
       P("cost extra money", "D-PLAUSIBLE-UNSUPPORTED"),
       P("ruined completely", "D-OPPOSITE"),
       P("measured exactly", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("inference_clue", 2, 2, 5,
      "Dev peered through the keyhole, then through the gap under the door, then through the frosted glass — anything for a glimpse of the birthday preparations he was strictly banned from seeing.",
      "peered",
      [K("looked hard and closely"),
       P("knocked politely", "D-PLAUSIBLE-UNSUPPORTED"),
       P("walked away", "D-OPPOSITE"),
       P("listened carefully", "D-TOPIC-ADJACENT")]),
    it("inference_clue", 2, 2, 6,
      "The old rowing boat bobbed by the jetty — up with each small wave, down again after it, gentle as a cork, never drifting from its rope.",
      "bobbed",
      [K("floated up and down"),
       P("sank to the bottom", "D-OPPOSITE"),
       P("sped across the lake", "D-PLAUSIBLE-UNSUPPORTED"),
       P("leaked at the seams", "D-TOPIC-ADJACENT")]),
    it("inference_clue", 2, 2, 7,
      "Roz patched the knee of her jeans with a square of star-print cloth. The hole disappeared under the stars, the stitches held through every playtime, and the jeans lasted the whole year after all.",
      "patched",
      [K("covered a hole to fix it"),
       P("cut a bigger hole", "D-OPPOSITE"),
       P("washed in hot water", "D-PLAUSIBLE-UNSUPPORTED"),
       P("folded and put away", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("inference_clue", 2, 2, 8,
      "At the first drops, everyone dashed for the bandstand — coats over heads, pushchairs bumping, ice creams abandoned — and reached its roof just as the sky truly opened.",
      "dashed",
      [K("ran very quickly"),
       P("strolled slowly", "D-OPPOSITE"),
       P("danced in circles", "D-PLAUSIBLE-UNSUPPORTED"),
       P("queued politely", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ============ RETENTION RESERVE (8 L1 + 8 L2) ============
    it("definition_clue", 1, 1, 9,
      "Snug means warm, comfortable and safe. Inside her blanket nest with a book and the rain outside, Mia felt perfectly snug.",
      "snug",
      [K("warm and comfortable"),
       P("cold and damp", "D-OPPOSITE"),
       P("bored and restless", "D-PLAUSIBLE-UNSUPPORTED"),
       P("half asleep", "D-TOPIC-ADJACENT")]),
    it("definition_clue", 1, 2, 10,
      "A faint sound is one so quiet you can barely hear it. From two gardens away came the faint tinkle of a wind chime.",
      "faint",
      [K("very quiet"),
       P("booming loud", "D-OPPOSITE"),
       P("out of tune", "D-PLAUSIBLE-UNSUPPORTED"),
       P("far too slow", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("example_clue", 1, 1, 9,
      "Gigantic things filled Theo's dinosaur book: legs like tree trunks, teeth as long as rulers, and one footprint that could have held his whole paddling pool.",
      "gigantic",
      [K("huge beyond belief"),
       P("tiny and neat", "D-OPPOSITE"),
       P("scaly and green", "D-TOPIC-ADJACENT"),
       P("very fierce", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("example_clue", 1, 2, 10,
      "Everything delicate went on the top shelf: the paper lanterns, Gran's thin china cups, the sugar swan from the wedding, and the model ship made of matchsticks.",
      "delicate",
      [K("easily damaged"),
       P("tough as old boots", "D-OPPOSITE"),
       P("very expensive", "D-PLAUSIBLE-UNSUPPORTED"),
       P("high up", "D-TOPIC-ADJACENT")]),
    it("action_clue", 1, 1, 9,
      "All through dinner Uncle Ray was grumpy — he frowned at the peas, sighed at the weather, and answered every question with a single flat word.",
      "grumpy",
      [K("in a bad mood"),
       P("full of jokes", "D-OPPOSITE"),
       P("very hungry", "D-PLAUSIBLE-UNSUPPORTED"),
       P("fast asleep", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("action_clue", 1, 2, 10,
      "The lizard darted across the hot stone path — there one blink, gone the next — and vanished under the rosemary bush before anyone could crouch for a look.",
      "darted",
      [K("moved suddenly and fast"),
       P("slept in the sun", "D-OPPOSITE"),
       P("changed its colour", "D-TOPIC-ADJACENT"),
       P("hissed a warning", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("definition_clue", 1, 1, 11,
      "Elderly means old, especially for a person. The elderly man at number nine has lived on our street longer than every other neighbour put together.",
      "elderly",
      [K("old in age"),
       P("very young", "D-OPPOSITE"),
       P("new to the street", "D-PLAUSIBLE-UNSUPPORTED"),
       P("tall and thin", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("example_clue", 1, 1, 11,
      "The junk drawer was a jumble: rubber bands round old keys, a torch tangled in string, batteries mixed with buttons, and somewhere underneath, the missing bicycle bell.",
      "jumble",
      [K("a muddle of mixed-up things"),
       P("a tidy line", "D-OPPOSITE"),
       P("a locked box", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a shopping list", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("synonym_clue", 2, 1, 9,
      "The stray kitten was famished — starving, truly hollow-bellied — and it emptied the saucer of food before Ella had even stood back up.",
      "famished",
      [K("extremely hungry"),
       P("completely full", "D-OPPOSITE"),
       P("soft and fluffy", "D-PLAUSIBLE-UNSUPPORTED"),
       P("afraid of people", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("synonym_clue", 2, 2, 10,
      "The riddle baffled the whole family. It puzzled Dad, confused Gran, and stumped even Priya, who does the crossword in pen.",
      "baffled",
      [K("completely puzzled"),
       P("bored quickly", "D-PLAUSIBLE-UNSUPPORTED"),
       P("made everyone laugh", "D-PLAUSIBLE-UNSUPPORTED"),
       P("was solved at once", "D-OPPOSITE")]),
    it("antonym_contrast_clue", 2, 1, 9,
      "Most days the sea slapped the rocks in fury, but this morning it was placid — flat, quiet water without one white wave from the beach to the buoy.",
      "placid",
      [K("calm and peaceful"),
       P("wild and stormy", "D-OPPOSITE"),
       P("deep and cold", "D-PLAUSIBLE-UNSUPPORTED"),
       P("full of boats", "D-TOPIC-ADJACENT")]),
    it("antonym_contrast_clue", 2, 2, 10,
      "The first clue was simple enough for anyone, but the last was so cunning that even the puzzle club's champion chewed her pencil over it until the bell.",
      "cunning",
      [K("cleverly tricky"),
       P("plain and easy", "D-OPPOSITE"),
       P("written in ink", "D-PLAUSIBLE-UNSUPPORTED"),
       P("missing a piece", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("inference_clue", 2, 1, 9,
      "The parcel was so cumbersome that Jai had to carry it with both arms wrapped right around, walking sideways through doorways and resting at every corner.",
      "cumbersome",
      [K("big and awkward to carry"),
       P("light as a feather", "D-OPPOSITE"),
       P("tied with ribbon", "D-TOPIC-ADJACENT"),
       P("full of books", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("inference_clue", 2, 2, 10,
      "One sniff of the milk made Asha wince and hold the bottle at arm's length. It had turned rancid days ago, somewhere at the warm back of the van.",
      "rancid",
      [K("gone bad and smelly"),
       P("fresh and creamy", "D-OPPOSITE"),
       P("frozen solid", "D-PLAUSIBLE-UNSUPPORTED"),
       P("watered down", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("synonym_clue", 2, 1, 11,
      "Loyal to the end, the old sheepdog shadowed Farmer Bell everywhere — faithful through rain, market days, and even trips to the vet.",
      "loyal",
      [K("always faithful"),
       P("quick to run off", "D-OPPOSITE"),
       P("afraid of sheep", "D-PLAUSIBLE-UNSUPPORTED"),
       P("very old", "D-TOPIC-ADJACENT")], { retention: true }),
    it("inference_clue", 2, 1, 11,
      "The classroom fell silent as the results were read, and when her name came last — first place — Zainab beamed, a smile so wide it seemed to light the room.",
      "beamed",
      [K("smiled hugely"),
       P("burst into tears", "D-PLAUSIBLE-UNSUPPORTED"),
       P("frowned crossly", "D-OPPOSITE"),
       P("left the room", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true })
  ]
};
