// Inference — v3 authored bank (wave W1). The six-emotion rotation is dead:
// every item is its own scene with behavioural clues, and every distractor is a
// competing plausible reading killed by a specific clue (named in the note).
// L2 evidence_pick items quote the passage in EVERY option, so surface-matching
// ties and only real inference separates them.
//
// Feelings vocabulary used across the bank (>12 distinct): proud, worried,
// nervous, relieved, disappointed, curious, patient, embarrassed, excited,
// jealous, grateful, brave, frustrated, calm, hopeful, surprised.
//
// Topic registry: recital wings, burnt toast, vet visit, race ribbon, spilled
// paint, thunder night, new school gate, rooftop seagull, missing recorder,
// icy path, garden gnome, borrowed umbrella, birthday parcel, deep end,
// wobbling ladder, sleeping baby, torch batteries, muddy football, quiet
// grandpa, splinter, first bus alone, lost balloon, spelling test, snowman
// morning, aquarium eel, broken crayon, dark cave tour, stray feather, oven
// timer, tall slide, honey jar, tangled puppet, library whisper, crooked
// picture, growling stomach, jam sandwich thief.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, prompt, choices, note = "", extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage, prompt, choices, media: "text", note, ...extra
});

export default {
  skillId: "inference",
  skillName: "Inference",
  items: [
    // ============== LEVEL 1 · feeling_from_evidence (8) ==============
    it("feeling_from_evidence", 1, 1, 1,
      "Sami stood in the wings holding his recorder. He wiped his hands on his shirt three times. Through the curtain he could see all the chairs were full. He peeped at the audience, then quickly stepped back and checked his music again.",
      "How does Sami most likely feel?",
      [K("nervous"),
       P("bored", "D-OPPOSITE"),
       P("angry", "D-PLAUSIBLE-UNSUPPORTED"),
       P("sleepy", "D-PLAUSIBLE-UNSUPPORTED")],
      "wiping hands + re-checking music kills every rival reading"),
    it("feeling_from_evidence", 1, 1, 2,
      "Lena's cat had been at the vet all day. When Mum's phone finally rang, Lena froze. Mum listened, then smiled and gave a thumbs up. Lena let out a long breath and flopped onto the sofa like a rag doll.",
      "How does Lena feel at the end?",
      [K("relieved"),
       P("worried", "D-SEQUENCE-SWAP"),
       P("jealous", "D-PLAUSIBLE-UNSUPPORTED"),
       P("cross", "D-OPPOSITE")],
      "worried is TRUE earlier — the long breath and flop mark the change; classic before/after trap"),
    it("feeling_from_evidence", 1, 1, 3,
      "Everyone else had finished the race. Dara was still running, last by a whole lap. She kept her eyes on the finish line and pumped her arms. When she crossed it, she punched the air as if she had come first.",
      "How does Dara feel about finishing?",
      [K("proud"),
       P("ashamed", "D-PLAUSIBLE-UNSUPPORTED"),
       P("confused", "D-OPPOSITE"),
       P("scared", "D-PLAUSIBLE-UNSUPPORTED")],
      "punching the air kills 'ashamed', the tempting reading of finishing last"),
    it("feeling_from_evidence", 1, 1, 4,
      "At the new school gate, Ivo held Dad's hand a little too hard. He watched the other children stream past, laughing in twos and threes. He did not know a single name. He practised saying 'hello' very quietly to himself.",
      "How does Ivo most likely feel?",
      [K("nervous"),
       P("furious", "D-OPPOSITE"),
       P("proud", "D-PLAUSIBLE-UNSUPPORTED"),
       P("tired", "D-PLAUSIBLE-UNSUPPORTED")],
      "the too-hard grip and whispered practice are the clues"),
    it("feeling_from_evidence", 1, 2, 5,
      "Bea's balloon slipped off her wrist at the fair. She watched the red dot get smaller and smaller in the sky. Her lip wobbled. Then she looked down at the string still in her hand and quickly wiped one eye with her sleeve.",
      "How does Bea feel?",
      [K("sad"),
       P("thrilled", "D-OPPOSITE"),
       P("hungry", "D-PLAUSIBLE-UNSUPPORTED"),
       P("brave", "D-PLAUSIBLE-UNSUPPORTED")],
      "wobbling lip + wiped eye; 'thrilled' tempts because fairs are fun"),
    it("feeling_from_evidence", 1, 2, 6,
      "Kofi had studied his spelling words all week. When Miss Reed handed back the tests, she gave his desk a little tap and a wink. Kofi looked at the top of his page, sat up very straight, and could not stop smiling for the whole lesson.",
      "How does Kofi most likely feel?",
      [K("proud"),
       P("disappointed", "D-OPPOSITE"),
       P("jealous", "D-PLAUSIBLE-UNSUPPORTED"),
       P("nervous", "D-SEQUENCE-SWAP")],
      "nervous fits BEFORE results; the wink and straight back mark after"),
    it("feeling_from_evidence", 1, 2, 7,
      "The tour guide switched off the lights inside the cave. The dark was thicker than any night. Noor squeezed her torch but did not turn it on. 'One minute of true dark,' the guide had promised. Noor counted slowly and kept both feet very still.",
      "How does Noor feel in the dark?",
      [K("brave"),
       P("terrified and running", "D-OPPOSITE"),
       P("bored", "D-PLAUSIBLE-UNSUPPORTED"),
       P("silly", "D-PLAUSIBLE-UNSUPPORTED")],
      "she is scared-ish but holds still and counts — the point is managed fear"),
    it("feeling_from_evidence", 1, 2, 8,
      "Ren watched his sister open her birthday parcel. Inside was the robot he had wanted for months. He clapped along with everyone else, but his clap was slow. He kept looking at the robot, then at his own empty hands.",
      "How does Ren most likely feel?",
      [K("jealous"),
       P("delighted", "D-OPPOSITE"),
       P("scared", "D-PLAUSIBLE-UNSUPPORTED"),
       P("calm", "D-PLAUSIBLE-UNSUPPORTED")],
      "slow clap + empty hands; delighted is the surface reading of a party"),

    // ============== LEVEL 1 · where_am_i (8) ==============
    it("where_am_i", 1, 1, 1,
      "Everything smelled of warm bread. Rows of buns sat behind curved glass. A bell above the door jingled, and a lady in a floury apron called out, 'Next, please!'",
      "Where does this take place?",
      [K("a bakery"),
       P("a library", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a swimming pool", "D-OPPOSITE"),
       P("a garden", "D-PLAUSIBLE-UNSUPPORTED")],
      "smell + glass counter + floury apron"),
    it("where_am_i", 1, 1, 2,
      "Mara pulled her armbands tight. The air smelled of chlorine, and shouts echoed off the high ceiling. Somewhere a whistle blew, and the big clock on the wall had only one long red hand.",
      "Where is Mara?",
      [K("a swimming pool"),
       P("a football pitch", "D-TOPIC-ADJACENT"),
       P("a cinema", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a farm", "D-OPPOSITE")],
      "whistle tempts football; chlorine and armbands decide"),
    it("where_am_i", 1, 1, 3,
      "Hush hung over the long tables. Pages turned with tiny whispers. A trolley of books rolled softly past, and a lady stamped a date inside a cover. 'Two weeks,' she mouthed, almost silently.",
      "Where does this take place?",
      [K("a library"),
       P("a bookshop", "D-TOPIC-ADJACENT"),
       P("a playground", "D-OPPOSITE"),
       P("a kitchen", "D-PLAUSIBLE-UNSUPPORTED")],
      "bookshop is the near-miss; the date stamp and borrowing decide"),
    it("where_am_i", 1, 1, 4,
      "Straw crunched under Tia's boots. Something warm and huge breathed near her shoulder, smelling of grass. A bucket clanked, and a man in muddy overalls said, 'She likes you. Want to hold the brush?'",
      "Where is Tia?",
      [K("a stable"),
       P("a pet shop", "D-TOPIC-ADJACENT"),
       P("a classroom", "D-OPPOSITE"),
       P("a beach", "D-PLAUSIBLE-UNSUPPORTED")],
      "straw + huge warm animal + brush"),
    it("where_am_i", 1, 2, 5,
      "The floor hummed under their feet. Fields slid past the window, faster and faster. A voice from the ceiling said the next stop was in ten minutes, and a trolley of snacks squeaked up the aisle.",
      "Where does this take place?",
      [K("a train"),
       P("a bus", "D-TOPIC-ADJACENT"),
       P("a boat", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a lift", "D-OPPOSITE")],
      "bus is close; announced stops + aisle trolley + sliding fields decide"),
    it("where_am_i", 1, 2, 6,
      "Blue light rippled across everyone's faces. A long shadow glided by behind the glass, and a hundred silver shapes turned at once like one creature. 'No flash photos,' whispered the guide.",
      "Where are they?",
      [K("an aquarium"),
       P("a cinema", "D-TOPIC-ADJACENT"),
       P("a museum of paintings", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a cave", "D-PLAUSIBLE-UNSUPPORTED")],
      "cinema shares dark + glow; the glass and gliding shapes decide"),
    it("where_am_i", 1, 2, 7,
      "Trays clattered somewhere behind the counter. The smell of gravy filled the hall. Omar slid his tray along the rails, said 'yes please' to the peas, and looked for an empty seat beside his friends.",
      "Where is Omar?",
      [K("the school dinner hall"),
       P("his kitchen at home", "D-TOPIC-ADJACENT"),
       P("a sweet shop", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the school library", "D-OPPOSITE")],
      "tray rails + choosing peas + finding a seat"),
    it("where_am_i", 1, 2, 8,
      "Gulls screamed overhead. Wind tugged the flags on the sandcastles. Somewhere an ice-cream van sang its tinkling song, and Dad rubbed cream on Zoe's nose, saying the sun was strong today.",
      "Where does this take place?",
      [K("the beach"),
       P("a funfair", "D-TOPIC-ADJACENT"),
       P("a forest", "D-OPPOSITE"),
       P("a car park", "D-PLAUSIBLE-UNSUPPORTED")],
      "van music tempts funfair; gulls + sandcastles + sun cream decide"),

    // ============== LEVEL 1 · what_happens_next (8) ==============
    it("what_happens_next", 1, 1, 1,
      "Black clouds rolled over the park. The wind flipped the picnic blanket corner over the sandwiches. Far away, thunder grumbled. Mum started packing the food back into the basket, fast.",
      "What will most likely happen next?",
      [K("the family will hurry home before the rain"),
       P("the family will start a barbecue", "D-OPPOSITE"),
       P("the family will go swimming", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the family will fall asleep on the grass", "D-PLAUSIBLE-UNSUPPORTED")],
      "packing fast + thunder = leaving; barbecue reverses the evidence"),
    it("what_happens_next", 1, 1, 2,
      "Theo filled the tub with warm water. He fetched the dog shampoo and an old towel. Then he opened the back door and called, 'Biscuit! Here, boy!' From the garden came the sound of happy, muddy paws.",
      "What will most likely happen next?",
      [K("Theo will wash the dog"),
       P("Theo will take a bath himself", "D-TOPIC-ADJACENT"),
       P("Theo will feed the cat", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Theo will go to bed", "D-OPPOSITE")],
      "dog shampoo is the deciding detail against 'his own bath'"),
    it("what_happens_next", 1, 1, 3,
      "The smell of toast turned sharp and smoky. A thin grey wisp curled out of the toaster. Dad sniffed twice, dropped his newspaper, and ran for the kitchen.",
      "What will most likely happen next?",
      [K("Dad will pop out the burnt toast"),
       P("Dad will water the plants", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Dad will eat the toast happily", "D-OPPOSITE"),
       P("Dad will read another page", "D-SEQUENCE-SWAP")],
      "reading the paper is what he was doing BEFORE — the swap trap"),
    it("what_happens_next", 1, 1, 4,
      "Aya counted her pocket money twice. She put on her coat and took the empty honey jar from the shelf. 'Back soon,' she called, 'we need more for the pancakes!'",
      "What will most likely happen next?",
      [K("Aya will go and buy honey"),
       P("Aya will throw the jar away", "D-OPPOSITE"),
       P("Aya will make her bed", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Aya will eat the pancakes now", "D-SEQUENCE-SWAP")],
      "money + empty jar + 'we need more' point one way"),
    it("what_happens_next", 1, 2, 5,
      "The torch blinked, went dim, then died. Raj shook it, but the dark stayed. He remembered the drawer in the kitchen where the little round batteries lived, and he felt his way toward the stairs.",
      "What will most likely happen next?",
      [K("Raj will get new batteries"),
       P("Raj will throw the torch in the bin", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Raj will shine the torch again at once", "D-OPPOSITE"),
       P("Raj will go outside to play", "D-PLAUSIBLE-UNSUPPORTED")],
      "remembering the battery drawer is the plan"),
    it("what_happens_next", 1, 2, 6,
      "Nell's baby brother finally fell asleep in his cot. Mum tiptoed out backwards. Just then, Nell's music box began to plink loudly in her pocket. Mum spun round with wide eyes.",
      "What will most likely happen next?",
      [K("Nell will rush to switch off the music"),
       P("Nell will turn the music up", "D-OPPOSITE"),
       P("Nell will start singing along", "D-OPPOSITE"),
       P("Nell will open the window", "D-PLAUSIBLE-UNSUPPORTED")],
      "sleeping baby + wide eyes = silence needed"),
    it("what_happens_next", 1, 2, 7,
      "Frost had turned the path to glass overnight. Grandad tested it with one boot and slid an arm's length. 'Not today,' he said, looking at the gritting sand by the gate.",
      "What will most likely happen next?",
      [K("Grandad will spread sand on the icy path"),
       P("Grandad will run down the path", "D-OPPOSITE"),
       P("Grandad will plant flowers", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Grandad will wash the windows", "D-PLAUSIBLE-UNSUPPORTED")],
      "the glance at the gritting sand sets the plan"),
    it("what_happens_next", 1, 2, 8,
      "The jam sandwich was gone. Only crumbs led away across the kitchen floor, and the cat flap was still swinging gently. Outside, a magpie sat on the fence with something red and sticky on its beak.",
      "What most likely happened to the sandwich?",
      [K("a bird took it"),
       P("Mum tidied it away", "D-PLAUSIBLE-UNSUPPORTED"),
       P("it is still on the plate", "D-OPPOSITE"),
       P("the postman ate it", "D-PLAUSIBLE-UNSUPPORTED")],
      "crumb trail + swinging flap + sticky beak"),

    // ============== LEVEL 2 · why_did_they (8) ==============
    it("why_did_they", 2, 1, 1,
      "Ma put two umbrellas by the door instead of one. She checked the window again, then rolled up the picnic rug and slid it back on top of the cupboard. 'We'll do the indoor museum instead,' she said, 'and take the bus, not walk.'",
      "Why did Ma change the plans?",
      [K("she could tell rain was coming"),
       P("she was tired of picnics forever", "D-OPPOSITE"),
       P("the museum was free that day", "D-PLAUSIBLE-UNSUPPORTED"),
       P("she had lost the picnic rug", "D-OPPOSITE")],
      "two umbrellas + window checks; the rug is put AWAY, not lost"),
    it("why_did_they", 2, 1, 2,
      "At lunch, Marco slid his orange across to Lily without a word. Lily's lunchbox had fallen in a puddle that morning, and everyone had seen her empty tray. Marco kept his eyes on his own sandwich, as if nothing had happened.",
      "Why did Marco give Lily his orange?",
      [K("he wanted to help her without a fuss"),
       P("he hated oranges", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the teacher told him to share", "D-PLAUSIBLE-UNSUPPORTED"),
       P("he wanted everyone to praise him", "D-OPPOSITE")],
      "'without a word' and looking away kill the showing-off reading"),
    it("why_did_they", 2, 1, 3,
      "Pia usually raced her scooter down Hill Lane. Today she got off at the top and walked it down slowly, holding the brake lever the whole way. Halfway down, she stepped carefully around a patch where the council had painted a wet, shining square of new tar.",
      "Why did Pia walk instead of ride?",
      [K("the lane was not safe to ride today"),
       P("her scooter was stolen", "D-OPPOSITE"),
       P("she was bored of scooting", "D-PLAUSIBLE-UNSUPPORTED"),
       P("she wanted to be late for tea", "D-PLAUSIBLE-UNSUPPORTED")],
      "she still HAS the scooter; the wet tar is the mechanism"),
    it("why_did_they", 2, 1, 4,
      "Gran turned the television right down when the phone rang. She carried the phone to the quiet hallway and shut the kitchen door behind her. 'Yes, doctor, I can hear you clearly now,' she said.",
      "Why did Gran go to the hallway?",
      [K("she needed quiet to hear the call"),
       P("she wanted to watch television", "D-OPPOSITE"),
       P("the kitchen was too cold", "D-PLAUSIBLE-UNSUPPORTED"),
       P("she was hiding from Grandad", "D-PLAUSIBLE-UNSUPPORTED")],
      "'I can hear you clearly now' confirms the mechanism"),
    it("why_did_they", 2, 2, 5,
      "Coach Adams moved Jonah from striker to goalkeeper for the final. Some parents muttered. But in training all week, Jonah had tipped every single shot over the bar, even the hard low ones. When the final whistle blew, Jonah had kept the only clean sheet of the season.",
      "Why did the coach move Jonah?",
      [K("Jonah had shown he was brilliant in goal"),
       P("Jonah was too slow to run", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the coach wanted the team to lose", "D-OPPOSITE"),
       P("the parents asked for the change", "D-OPPOSITE")],
      "the training detail is the evidence; parents actually muttered AGAINST it"),
    it("why_did_they", 2, 2, 6,
      "Auntie Fern always kept her seed packets in old jam jars with the lids screwed tight. 'One flood in this shed was enough,' she would say, tapping a jar. On the top shelf, a faded brown tide mark still ran along the wooden wall.",
      "Why does Auntie Fern use sealed jars?",
      [K("a flood once ruined her seeds"),
       P("she likes collecting jam", "D-TOPIC-ADJACENT"),
       P("the jars look pretty on the shelf", "D-PLAUSIBLE-UNSUPPORTED"),
       P("seeds grow better inside glass", "D-PLAUSIBLE-UNSUPPORTED")],
      "the tide mark corroborates her one-line explanation"),
    it("why_did_they", 2, 2, 7,
      "On the first bus ride to school by herself, Asha sat directly behind the driver, even though the back seats were empty and her friends always said the back was best. She held her ticket in her hand the whole way instead of putting it in her bag.",
      "Why did Asha sit at the front with her ticket out?",
      [K("being new to riding alone, she wanted to feel safe and ready"),
       P("the back seats were broken", "D-PLAUSIBLE-UNSUPPORTED"),
       P("she wanted to annoy her friends", "D-OPPOSITE"),
       P("the driver was her uncle", "D-PLAUSIBLE-UNSUPPORTED")],
      "first-time-alone frames both choices; nothing supports the rivals"),
    it("why_did_they", 2, 2, 8,
      "Mr Okafor propped his ladder against the wall, then moved it twice before climbing. Each time he pushed the feet a little farther from the wall and pressed down on a rung with his boot. Only when the ladder did not wobble at all did he pick up his paintbrush.",
      "Why did Mr Okafor keep moving the ladder?",
      [K("he was making sure it would not slip"),
       P("he could not decide which wall to paint", "D-PLAUSIBLE-UNSUPPORTED"),
       P("he was trying to break the ladder", "D-OPPOSITE"),
       P("he had forgotten his paintbrush", "D-SEQUENCE-SWAP")],
      "the wobble test is the mechanism; the brush comes AFTER by design"),

    // ============== LEVEL 2 · what_went_unsaid (8) ==============
    it("what_went_unsaid", 2, 1, 1,
      "When Jess came in from the garden, a dripping umbrella already stood open in the bath. Two coats hung heavy on the radiator, and Mum was stuffing newspaper into a pair of dark, shining boots.",
      "What must have happened before Jess came in?",
      [K("someone had been out in heavy rain"),
       P("the family had been at the beach", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Mum had bought new boots", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the bath had overflowed", "D-TOPIC-ADJACENT")],
      "three water clues point outdoors; overflow explains only one of them"),
    it("what_went_unsaid", 2, 1, 2,
      "The classroom hamster wheel was still spinning slowly when the children arrived. The food bowl, full last night, held only two pellets, and the tissue-paper mountain in the corner now had a perfectly round doorway.",
      "What must have happened overnight?",
      [K("the hamster was busy while everyone was away"),
       P("a child fed the hamster at dawn", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the caretaker cleaned the cage", "D-OPPOSITE"),
       P("the hamster slept all night", "D-OPPOSITE")],
      "spinning wheel + eaten food + built doorway"),
    it("what_went_unsaid", 2, 1, 3,
      "Dad met them at the door wearing one oven glove and a guilty smile. The kitchen window was wide open in the cold, a tea towel was flapping over the smoke alarm, and a very dark cake sat in the bin.",
      "What went wrong while they were out?",
      [K("Dad burnt the cake he was baking"),
       P("Dad forgot to bake anything", "D-OPPOSITE"),
       P("burglars had opened the window", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the oven had never worked", "D-PLAUSIBLE-UNSUPPORTED")],
      "each clue is smoke management; the binned cake completes it"),
    it("what_went_unsaid", 2, 1, 4,
      "Marta's recorder case felt strangely light on the walk to school. When the music teacher asked everyone to play, Marta opened the case and found only a folded note from her little brother: 'Borrowed it for my pirate band. Sorry!'",
      "What had happened at home?",
      [K("her brother had taken the recorder without asking"),
       P("Marta had sold her recorder", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the teacher had collected the recorders", "D-OPPOSITE"),
       P("Marta forgot she owned a recorder", "D-OPPOSITE")],
      "the note states it; the light case was the early clue"),
    it("what_went_unsaid", 2, 2, 5,
      "The garden gnome had moved again. On Monday he faced the pond; by Friday he was under the rose bush, wearing a doll's scarf. Grandpa swore he never touched him. From the fence, the little girl next door watched with a very serious face, and one more doll's scarf in her hand.",
      "Who has most likely been moving the gnome?",
      [K("the girl next door"),
       P("Grandpa, though he swore he never touched him", "D-OPPOSITE"),
       P("the wind", "D-PLAUSIBLE-UNSUPPORTED"),
       P("nobody — it never moved", "D-OPPOSITE")],
      "the matching scarf is the fingerprint"),
    it("what_went_unsaid", 2, 2, 6,
      "By morning the bird feeder lay on the grass, split open and licked clean. The pole it hung from was bent in a smooth curve, like a drinking straw. In the flower bed below, deep five-toed prints led away toward the woods, each one wider than Dad's boot.",
      "What most likely visited in the night?",
      [K("a large, heavy animal from the woods"),
       P("a small garden bird", "D-OPPOSITE"),
       P("a naughty child from next door", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a strong gust of wind", "D-PLAUSIBLE-UNSUPPORTED")],
      "bent metal + wide prints rule out the small and the bodiless"),
    it("what_went_unsaid", 2, 2, 7,
      "The whole flat smelled of paint, though the walls were the same colour as ever. Newspaper was taped inside the bath tub, and tiny silver spots freckled Mum's glasses. On the balcony, Ela's old bicycle stood drying — suddenly, gloriously silver from wheel to wheel.",
      "What had Mum been doing?",
      [K("spray-painting Ela's bicycle as a surprise"),
       P("painting the bathroom walls a new colour", "D-TOPIC-ADJACENT"),
       P("cleaning her glasses", "D-DETAIL-AS-MAIN"),
       P("buying a brand-new bicycle", "D-PLAUSIBLE-UNSUPPORTED")],
      "same-colour walls kills the wall reading; silver spots + silver bike join up"),
    it("what_went_unsaid", 2, 2, 8,
      "When the lights came back on, the ice-cream tub on the counter was soft as soup, and the freezer drawers stood in puddles. The oven clock blinked 00:00, 00:00, 00:00, and every radio in the house had forgotten its stations.",
      "What must have happened while they were out?",
      [K("the electricity had been off for a long time"),
       P("someone left the freezer drawers hanging open", "D-TOPIC-ADJACENT"),
       P("the family bought soft ice cream", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a burglar reset the clocks", "D-PLAUSIBLE-UNSUPPORTED")],
      "blinking clocks + forgetful radios only fit a power cut, not an open freezer"),

    // ============== LEVEL 2 · evidence_pick (8) ==============
    it("evidence_pick", 2, 1, 1,
      "Tilly said she did not mind missing the trip. She said it twice, in a bright voice. But all through art she drew the same picture: a little bus on a long road, with a girl waving from the window seat.",
      "Which words from the story show how Tilly REALLY feels?",
      [K("she drew a girl waving from the bus window"),
       P("she said twice, in a bright voice, that she did not mind missing it", "D-OPPOSITE"),
       P("it was time for art", "D-DETAIL-AS-MAIN"),
       P("her voice was bright", "D-OPPOSITE")],
      "the drawing contradicts the words — evidence beats statements"),
    it("evidence_pick", 2, 1, 2,
      "'Any dog would do,' said Ba, shrugging at the shelter. Then a grey terrier pressed its nose to the bars. Ba knelt down for a long time. On the way home he asked, twice, whether terriers like long walks, and he kept the shelter's leaflet in his top pocket all week.",
      "Which words show that Ba wanted THAT dog?",
      [K("he kept the shelter's leaflet all week"),
       P("he shrugged at the shelter and said any dog would do", "D-OPPOSITE"),
       P("the terrier was grey", "D-DETAIL-AS-MAIN"),
       P("they went home", "D-DETAIL-AS-MAIN")],
      "shrug words vs pocket evidence"),
    it("evidence_pick", 2, 1, 3,
      "Nobody saw who tidied the book corner. But Miss Diaz noticed that the shelves were sorted by colour, exactly like Femi sorts his pencil tin, and that the beanbag was patted into a neat square, just the way Femi leaves his chair cushion after lunch.",
      "Which clue points to Femi?",
      [K("the shelves were sorted the way Femi sorts his pencils"),
       P("nobody saw who tidied the book corner shelves", "D-OPPOSITE"),
       P("the classroom has a book corner", "D-DETAIL-AS-MAIN"),
       P("it happened after lunch", "D-PLAUSIBLE-UNSUPPORTED")],
      "matching habits are the fingerprint"),
    it("evidence_pick", 2, 1, 4,
      "Harri claimed the win did not matter. Yet the medal hung over his bed, polished every Sunday. The race photograph moved from the drawer, to the shelf, to a frame on the wall. And whenever visitors came, somehow the talk always found its way to that rainy sports day.",
      "Which words show the win DID matter to Harri?",
      [K("the medal was polished every Sunday"),
       P("Harri claimed the win did not matter at all", "D-OPPOSITE"),
       P("sports day was rainy", "D-DETAIL-AS-MAIN"),
       P("visitors came to the house", "D-DETAIL-AS-MAIN")],
      "actions over words again — the polishing habit"),
    it("evidence_pick", 2, 2, 5,
      "The new boy said he had never played chess before. Then he set up every piece without looking at the box lid. He moved his knight in that funny L-shape straight away, and when Mr Salt's queen crept forward, the new boy smiled a small, knowing smile.",
      "Which words show the new boy HAD played chess?",
      [K("he set up every piece without looking"),
       P("he said he had never played", "D-OPPOSITE"),
       P("there was a box lid", "D-DETAIL-AS-MAIN"),
       P("Mr Salt had a queen", "D-DETAIL-AS-MAIN")],
      "setup knowledge is the giveaway"),
    it("evidence_pick", 2, 2, 6,
      "Mum insisted she was wide awake for the film. Halfway through, her mug tipped gently in her hand, and Leo caught it. By the big ending, her head had found the cushion, and the credits rolled to the sound of long, slow breathing.",
      "Which words show Mum was actually asleep?",
      [K("the credits rolled to long, slow breathing"),
       P("she insisted she was wide awake for the whole film", "D-OPPOSITE"),
       P("they watched a film", "D-DETAIL-AS-MAIN"),
       P("Leo sat beside her", "D-PLAUSIBLE-UNSUPPORTED")],
      "the breathing detail settles it"),
    it("evidence_pick", 2, 2, 7,
      "The caretaker grumbled that the school cat was 'nothing but a nuisance'. But the nuisance had a cushion in the boiler room, a bowl marked C-A-T in the caretaker's own careful letters, and on cold mornings, the first warm lap it looked for was his.",
      "Which words show the caretaker loves the cat?",
      [K("a bowl marked C-A-T in his own careful letters"),
       P("he grumbled that the cat was nothing but a nuisance", "D-OPPOSITE"),
       P("the school had a boiler room", "D-DETAIL-AS-MAIN"),
       P("mornings were cold", "D-DETAIL-AS-MAIN")],
      "the hand-lettered bowl is devotion in evidence form"),
    it("evidence_pick", 2, 2, 8,
      "Priti told everyone the thunder did not scare her one bit. Still, at the first rumble she turned her music up very loud. At the second, she remembered an urgent reason to visit the kitchen, where Gran was. At the third, she decided the safest place to read was under her blanket with a torch.",
      "Which words show Priti WAS scared of the thunder?",
      [K("she hid away to read under a blanket"),
       P("she told everyone the thunder did not scare her one bit", "D-OPPOSITE"),
       P("she owned some music", "D-DETAIL-AS-MAIN"),
       P("Gran was in the kitchen", "D-DETAIL-AS-MAIN")],
      "escalating avoidance behaviours are the evidence chain"),

    // ============== RETENTION RESERVE (8 L1-style + 8 L2-style) ==============
    it("feeling_from_evidence", 1, 1, 9,
      "The splinter was tiny but it was IN Milo's finger. He looked away while Dad held the tweezers. 'Done,' said Dad, before Milo had even squeezed his eyes shut properly. Milo stared at his finger, then laughed out loud.",
      "How does Milo feel at the end?",
      [K("surprised it was so easy"),
       P("still terrified", "D-SEQUENCE-SWAP"),
       P("angry with Dad", "D-OPPOSITE"),
       P("sleepy", "D-PLAUSIBLE-UNSUPPORTED")],
      ""),
    it("feeling_from_evidence", 1, 2, 10,
      "Wren had saved her pocket money for six weeks. At the till, the shopkeeper counted her coins slowly and slid the paint set across the counter. Wren carried the bag with both hands all the way home, checking inside at every corner.",
      "How does Wren most likely feel?",
      [K("proud and careful with her prize"),
       P("sorry she bought it", "D-OPPOSITE"),
       P("frightened of the shop", "D-PLAUSIBLE-UNSUPPORTED"),
       P("bored by painting", "D-OPPOSITE")],
      ""),
    it("where_am_i", 1, 1, 9,
      "Rows of red seats sloped down toward the glowing screen. Ana balanced the popcorn on her knees. The lights dimmed slowly, and a hush spread as the first music swelled.",
      "Where is Ana?",
      [K("a cinema"),
       P("a theatre with actors on stage", "D-TOPIC-ADJACENT"),
       P("her bedroom", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a stadium", "D-PLAUSIBLE-UNSUPPORTED")],
      ""),
    it("where_am_i", 1, 2, 10,
      "Everything here had a price sticker and a wobbling tower of tins. A voice announced that spilled grapes were being cleaned on aisle four. Mum ticked the last thing off her list and steered the rattling trolley toward the shortest queue.",
      "Where are they?",
      [K("a supermarket"),
       P("a street market", "D-TOPIC-ADJACENT"),
       P("a kitchen", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a garage", "D-OPPOSITE")],
      ""),
    it("what_happens_next", 1, 1, 9,
      "Kip's tummy growled in the quiet classroom, loud as a bear. The clock said one minute until the lunch bell. He slid his workbook into his tray and looked at the door.",
      "What will most likely happen next?",
      [K("Kip will go to lunch when the bell rings"),
       P("Kip will sit in the quiet classroom doing worksheets", "D-OPPOSITE"),
       P("Kip will go home for the day", "D-PLAUSIBLE-UNSUPPORTED"),
       P("Kip will fall asleep", "D-PLAUSIBLE-UNSUPPORTED")],
      "", { retention: true }),
    it("what_happens_next", 1, 2, 10,
      "Snow had fallen all night, thick and perfect. Two carrots, a scarf, and a bag of coal buttons waited by the back door. Josh pulled on his mittens and pushed the door open into the white garden.",
      "What will Josh most likely do?",
      [K("build a snowman"),
       P("cook carrot soup", "D-TOPIC-ADJACENT"),
       P("go back to bed", "D-OPPOSITE"),
       P("water the flowers", "D-PLAUSIBLE-UNSUPPORTED")],
      "", { retention: true }),
    it("feeling_from_evidence", 1, 1, 11,
      "It was Ola's turn on the tall slide at last. From the top, the ground looked very far away. She gripped the rail, sang her favourite song under her breath, and let go. At the bottom she shouted, 'AGAIN!'",
      "How did Ola feel about the slide by the end?",
      [K("excited"),
       P("too scared to try again", "D-SEQUENCE-SWAP"),
       P("cross with the queue", "D-PLAUSIBLE-UNSUPPORTED"),
       P("bored", "D-OPPOSITE")],
      "", { retention: true }),
    it("where_am_i", 1, 1, 11,
      "White coats hurried past on soft shoes. A machine somewhere beeped a steady, patient beep. Gran sat up in the high bed and grinned at the grapes they had brought her.",
      "Where does this take place?",
      [K("a hospital"),
       P("a hotel", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a school", "D-OPPOSITE"),
       P("a greenhouse", "D-PLAUSIBLE-UNSUPPORTED")],
      "", { retention: true }),
    it("why_did_they", 2, 1, 9,
      "Half an hour before the guests arrived, Ade hid his favourite dinosaur under his pillow. His baby cousins were coming, and last time, the smallest one had chewed the tail of his second-favourite dinosaur into a soggy stump.",
      "Why did Ade hide the dinosaur?",
      [K("to keep it safe from his little cousins"),
       P("he was tired of dinosaurs", "D-OPPOSITE"),
       P("his mum told him to tidy his whole room", "D-PLAUSIBLE-UNSUPPORTED"),
       P("he wanted to sleep with it", "D-PLAUSIBLE-UNSUPPORTED")],
      ""),
    it("why_did_they", 2, 2, 10,
      "The cafe owner started opening one hour earlier, at six. She put out a basket of day-old rolls marked 'help yourself' and left the outside light on in the dark mornings. The bin men, the postwoman, and the night-shift nurses began to wave through the window like old friends.",
      "Why did the owner most likely make these changes?",
      [K("to look after the town's early workers"),
       P("to sell her rolls for more money", "D-OPPOSITE"),
       P("because she could not sleep", "D-PLAUSIBLE-UNSUPPORTED"),
       P("because the council made her", "D-PLAUSIBLE-UNSUPPORTED")],
      ""),
    it("what_went_unsaid", 2, 1, 9,
      "The trail of tiny muddy paw prints began at the cat flap. It crossed the clean kitchen floor, climbed impossibly onto the counter, and ended in the middle of the fresh white birthday cake — where one candle now leaned at a guilty angle.",
      "What must have happened?",
      [K("the cat walked through mud and over the cake"),
       P("someone dropped the birthday cake on the floor", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the baker made the cake wrong", "D-OPPOSITE"),
       P("a candle fell by itself", "D-DETAIL-AS-MAIN")],
      ""),
    it("what_went_unsaid", 2, 2, 10,
      "Dad came home from the allotment whistling, which he never did. His muddy bag, usually flat, bulged in one huge round shape. He hid it behind his back through the whole kitchen, then said, far too casually, 'So... is the village show still on Saturday?'",
      "What is Dad most likely hiding?",
      [K("a giant vegetable he grew for the show"),
       P("his usual flat and empty muddy bag", "D-OPPOSITE"),
       P("a lost kitten", "D-PLAUSIBLE-UNSUPPORTED"),
       P("his gardening gloves", "D-PLAUSIBLE-UNSUPPORTED")],
      ""),
    it("evidence_pick", 2, 1, 9,
      "Sol said the baby lambs were 'fine, whatever'. But he was first up in the cold every morning to warm their bottles. He gave up Saturday football when the smallest lamb was poorly, and he kept a photo of it standing up for the first time.",
      "Which words show Sol truly cared about the lambs?",
      [K("he was first up every morning to warm their bottles"),
       P("he said the baby lambs were fine, whatever", "D-OPPOSITE"),
       P("there was football on Saturday", "D-DETAIL-AS-MAIN"),
       P("mornings were cold", "D-DETAIL-AS-MAIN")],
      "", { retention: true }),
    it("evidence_pick", 2, 2, 10,
      "The head teacher announced that the school definitely, absolutely did not have a mouse. Meanwhile, the caretaker was seen carrying a tiny humane trap and a jar of peanut butter toward the store room, and the cook had moved every open sack of flour onto the highest shelf.",
      "Which words show there probably WAS a mouse?",
      [K("a humane trap and peanut butter went to the store room"),
       P("the head said the school absolutely had no mouse", "D-OPPOSITE"),
       P("the school had a store room", "D-DETAIL-AS-MAIN"),
       P("the cook moved every open sack of flour up high", "D-DETAIL-AS-MAIN")],
      "", { retention: true }),
    it("why_did_they", 2, 1, 11,
      "Nina wrapped her library book in a plastic bag before putting it in her rucksack, even though the sky was blue. Her water bottle had leaked once before, all over her spelling homework, and the librarian's eyebrows were famous across three year groups.",
      "Why did Nina wrap the book?",
      [K("to protect it in case her bottle leaked again"),
       P("because rain was pouring on the walk to school", "D-PLAUSIBLE-UNSUPPORTED"),
       P("to hide the book from her friends", "D-PLAUSIBLE-UNSUPPORTED"),
       P("because the bag looked nice", "D-OPPOSITE")],
      "", { retention: true }),
    it("what_went_unsaid", 2, 2, 11,
      "Every plant on the windowsill leaned the same way, like dancers frozen mid-bow. The cactus alone stood up straight. Gran turned each pot half a circle, and by the next week, the leaners were bowing toward the window all over again.",
      "What makes the plants lean?",
      [K("they grow toward the light from the window"),
       P("Gran turning the pots knocks each plant sideways", "D-OPPOSITE"),
       P("the wind pushes them", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the pots are broken", "D-PLAUSIBLE-UNSUPPORTED")],
      "", { retention: true })
  ]
};
