// Precise literal details at L1; integrated details and stated-evidence checks at L2.
// Every level contains 32 mastery items (16 per phase) and 8 reserves.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, prompt, choices, note = "", extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage, prompt, choices, media: "text", note, ...extra
});

export default {
  skillId: "key_details",
  skillName: "Key Details",
  items: [
    { u: "what_happened", lvl: 1, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Owen needed a book for his weather project. He searched the science shelf without finding one. A helper showed him books about storms. Owen chose the one with lightning photographs. He took it to the reading table.",
      prompt: "What kind of book did Owen choose?",
      choices: [K("a book of lightning photos"), P("a book of lightning facts", "D-PLAUSIBLE-UNSUPPORTED"), P("a book of rainy day tales", "D-PLAUSIBLE-UNSUPPORTED"), P("a book of storm safety tips", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_002)" },
    { u: "what_happened", lvl: 1, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Leo painted a red fire truck at school. His wide brush made the ladder look messy. Ms. Chen gave him a thinner brush. Leo made neat silver lines on the ladder. He kept the wide brush for the wheels.",
      prompt: "What did Leo paint with the thinner brush?",
      choices: [K("thin marks on the ladder"), P("thick marks on the ladder", "D-PLAUSIBLE-UNSUPPORTED"), P("silver dots on the ladder", "D-PLAUSIBLE-UNSUPPORTED"), P("black wheels below the ladder", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_004)" },
    { u: "what_happened", lvl: 1, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Jonah walked on the beach with his aunt. They looked for empty shells to take home. A tiny crab sat inside one shell. Jonah left that shell where it was. He took three empty shells instead.",
      prompt: "Why did Jonah leave one shell on the sand?",
      choices: [K("a crab was using the shell"), P("his aunt wanted that shell", "D-PLAUSIBLE-UNSUPPORTED"), P("the shell had a sharp edge", "D-PLAUSIBLE-UNSUPPORTED"), P("the shell was full of sand", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_005)" },
    { u: "what_happened", lvl: 1, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Arlo carried warm rolls from the bakery counter. His paper bag tore near the door. Two rolls fell onto a clean tray. Baker Tom gave him a stronger bag. Arlo put every roll safely inside it.",
      prompt: "What happened to Arlo's first bag?",
      choices: [K("the bag split open"), P("the bag got wet", "D-PLAUSIBLE-UNSUPPORTED"), P("the bag slipped down", "D-PLAUSIBLE-UNSUPPORTED"), P("the bag blew away", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_006)" },
    { u: "what_happened", lvl: 1, ph: 2, v: 5, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Nina rode her bike along the park path. Its loose chain slipped as she pedalled. She walked the bike to the repair bench. Her dad tightened its chain with a tool. Then she rode along the path again.",
      prompt: "Why did Nina stop riding?",
      choices: [K("the chain was not tight"), P("the chain was too tight", "D-PLAUSIBLE-UNSUPPORTED"), P("the chain had come off", "D-PLAUSIBLE-UNSUPPORTED"), P("the chain had snapped apart", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_007)" },
    { u: "what_happened", lvl: 1, ph: 2, v: 6, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Eli saw a squirrel near the park bench. It held an acorn between its front paws. A pine cone lay beside the bench. The children stepped back to give it space. Soon the squirrel ran up a tree.",
      prompt: "What did the squirrel hold?",
      choices: [K("an acorn"), P("a pine cone", "D-PLAUSIBLE-UNSUPPORTED"), P("a twig", "D-PLAUSIBLE-UNSUPPORTED"), P("a leaf", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_009)" },
    { u: "what_happened", lvl: 1, ph: 2, v: 7, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Nora looked after the class calendar. She crossed off Monday after the class meeting. Their next trip would be on Friday. Nora drew a circle around that day. Her friends counted the days until the trip.",
      prompt: "Which day did Nora circle?",
      choices: [K("Friday"), P("Monday", "D-PLAUSIBLE-UNSUPPORTED"), P("Sunday", "D-PLAUSIBLE-UNSUPPORTED"), P("Tuesday", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_010)" },
    { u: "what_happened", lvl: 1, ph: 2, v: 8, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Lucas helped put the food shopping away. The eggs sat above some heavy cans. He lifted the eggs out with both hands. He wanted to keep them safe from breaking. Then he put the cans on the shelf.",
      prompt: "Why did Lucas lift out the eggs first?",
      choices: [K("to stop the eggs cracking"), P("to count the eggs first", "D-PLAUSIBLE-UNSUPPORTED"), P("to wash the eggs first", "D-PLAUSIBLE-UNSUPPORTED"), P("to cook the eggs quickly", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_011)" },
    { u: "where", lvl: 1, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Maya planted sunflower seeds in a small pot. She added a label with her name. Then she watered the dry soil. She put the pot on the sunny windowsill. A green shoot appeared there on Friday.",
      prompt: "Where did Maya place the pot?",
      choices: [K("on the sunny window ledge"), P("on the shaded window ledge", "D-PLAUSIBLE-UNSUPPORTED"), P("on the sunny garden step", "D-PLAUSIBLE-UNSUPPORTED"), P("on the shaded garden step", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_001)" },
    { u: "where", lvl: 1, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Dark clouds gathered above the school field. The class had planned to eat outside. Miss Green heard thunder beyond the trees. She moved the children into the school hall. Rain began while they ate their lunch.",
      prompt: "Where did Miss Green move the class?",
      choices: [K("inside the school hall"), P("outside the school hall", "D-PLAUSIBLE-UNSUPPORTED"), P("behind the school hall", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the school hall", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_008)" },
    { u: "where", lvl: 1, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Finn carried books to the little free library. Its shelf was almost full of small books. He put the large books at the bottom. The small books stood above them in rows. Now every book fitted on the shelf.",
      prompt: "Where did Finn put the large books?",
      choices: [K("below the small books"), P("above the small books", "D-PLAUSIBLE-UNSUPPORTED"), P("behind the small books", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the small books", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_013)" },
    { u: "where", lvl: 1, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Dylan checked the museum map on the bus. The dinosaur room was beside the stairs. The cafe was beside the gift shop. He showed the map to his partner. They found the dinosaur room after arriving.",
      prompt: "Where was the dinosaur room on the map?",
      choices: [K("beside the stairs"), P("beside the cafe", "D-PLAUSIBLE-UNSUPPORTED"), P("behind the stairs", "D-PLAUSIBLE-UNSUPPORTED"), P("behind the cafe", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_022)" },
    { u: "where", lvl: 1, ph: 2, v: 5, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Hana sorted games after the class played indoors. The puzzles went on the top shelf. She put card games in the red bin. One puzzle box still had its lid open. Hana checked its pieces and closed it.",
      prompt: "Where did Hana put the card games?",
      choices: [K("in the red bin"), P("on the top shelf", "D-PLAUSIBLE-UNSUPPORTED"), P("under the rug", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the door", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_026)" },
    { u: "where", lvl: 1, ph: 2, v: 6, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Toby brought a striped towel to swimming class. He left it on the bench before swimming. After his lesson, he dried his wet hair. Then he put it in his bag. The towel fitted into the bag's side pocket.",
      prompt: "Where did Toby pack the towel?",
      choices: [K("inside the pocket at the bag’s side"), P("on the bench beside his damp towel", "D-PLAUSIBLE-UNSUPPORTED"), P("inside the bag beneath all his clothes", "D-PLAUSIBLE-UNSUPPORTED"), P("on the towel rack beside his bench", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_061)" },
    { u: "where", lvl: 1, ph: 2, v: 7, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Ivy found a coin near the classroom door. She gave it to Ms. Lopez. The teacher used the box for lost things. She placed the coin inside that box. Omar came looking for his coin after school.",
      prompt: "Where did Ms. Lopez put the coin?",
      choices: [K("in the box for lost things"), P("on the box for lost things", "D-PLAUSIBLE-UNSUPPORTED"), P("by the box for lost things", "D-PLAUSIBLE-UNSUPPORTED"), P("under the box for lost things", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_062)" },
    { u: "where", lvl: 1, ph: 2, v: 8, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "A red glove lay beside the playground gate. Hassan picked it up before it blew away. He took it to the school office. The helper pinned it on the lost-items board. Its owner saw it there after lunch.",
      prompt: "Where was the glove first found?",
      choices: [K("by the playground gate"), P("on the office board", "D-PLAUSIBLE-UNSUPPORTED"), P("by the office door", "D-PLAUSIBLE-UNSUPPORTED"), P("on the classroom table", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_063)" },
    { u: "who", lvl: 1, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "The playground ball rolled under a bench. Ava picked it up during the break. She passed it to Coach Lee. Her friend Mina brought back a skipping rope. Coach Lee put both in the equipment basket.",
      prompt: "Who did Ava give the ball to?",
      choices: [K("Coach Lee"), P("Ava", "D-PLAUSIBLE-UNSUPPORTED"), P("Mina", "D-PLAUSIBLE-UNSUPPORTED"), P("Coach Kim", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_003)" },
    { u: "who", lvl: 1, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "Miles and Grandpa raked leaves from the path. The wind kept blowing them across the garden. Grandpa held a large bag open. Miles pushed the loose leaves into it. They tied it shut before more wind came.",
      prompt: "Who held the bag open?",
      choices: [K("Grandpa"), P("the teacher", "D-PLAUSIBLE-UNSUPPORTED"), P("the bus driver", "D-PLAUSIBLE-UNSUPPORTED"), P("Miles", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_016)" },
    { u: "who", lvl: 1, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "Grace could not find her red pencil. Maya had only a blue pencil nearby. Noah lent Grace his spare red pencil. She used it to finish her drawing. At the end, she gave it back.",
      prompt: "Who lent Grace a red pencil?",
      choices: [K("Noah"), P("her teacher", "D-PLAUSIBLE-UNSUPPORTED"), P("Maya", "D-PLAUSIBLE-UNSUPPORTED"), P("the librarian", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_020)" },
    { u: "who", lvl: 1, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "Rosa brought her beach ball to the picnic. Wind pushed it toward the pond. Her cousin caught it before it reached water. Rosa thanked him for saving the ball. She put it under their picnic blanket.",
      prompt: "Who caught the beach ball?",
      choices: [K("her cousin"), P("Rosa", "D-PLAUSIBLE-UNSUPPORTED"), P("her aunt", "D-PLAUSIBLE-UNSUPPORTED"), P("her sister", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_028)" },
    { u: "who", lvl: 1, ph: 2, v: 5, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "Dad printed a photo from the school concert. Zoe stood beside the choir teacher in it. Dad stood behind them in the back row. Zoe chose a yellow frame for the photo. She put it above her desk.",
      prompt: "Who was standing beside Zoe in the photo?",
      choices: [K("the teacher of the choir"), P("her dad behind the choir", "D-PLAUSIBLE-UNSUPPORTED"), P("her cousin in the choir", "D-PLAUSIBLE-UNSUPPORTED"), P("the teacher of her class", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_072)" },
    { u: "number_detail", lvl: 1, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "number_detail", media: "text",
      passage: "Mara put cups out for the class picnic. Twenty children needed drinks. At first, she put out eighteen cups. Her friend saw that two children needed cups. Mara added two more before lunch began.",
      prompt: "How many more cups did Mara add?",
      choices: [K("two"), P("eight", "D-PLAUSIBLE-UNSUPPORTED"), P("twenty", "D-PLAUSIBLE-UNSUPPORTED"), P("three", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_014)" },
    { u: "number_detail", lvl: 1, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "number_detail", media: "text",
      passage: "Lena listened to Mr. Hill at the piano. He played three high notes slowly. Lena copied them on a small keyboard. Then Mr. Hill played five low notes. Lena listened carefully to those notes too.",
      prompt: "How many high notes did Mr. Hill play?",
      choices: [K("three"), P("five", "D-PLAUSIBLE-UNSUPPORTED"), P("two", "D-PLAUSIBLE-UNSUPPORTED"), P("four", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_064)" },
    { u: "number_detail", lvl: 1, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "number_detail", media: "text",
      passage: "The reading corner felt cold beside the window. Max fetched two cushions from the shelf. He put one on the blue chair. He put the other on the rug. His group sat down for story time.",
      prompt: "How many cushions did Max carry?",
      choices: [K("two"), P("four", "D-PLAUSIBLE-UNSUPPORTED"), P("six", "D-PLAUSIBLE-UNSUPPORTED"), P("one", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_073)" },
    { u: "number_detail", lvl: 1, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "number_detail", media: "text",
      passage: "The classroom clock stopped during reading time. Ella saw both hands pointing at twelve. Mr. Reed changed its battery after lunch. The clock began ticking before home time. Ella watched its long hand move again.",
      prompt: "When did Mr. Reed change the battery?",
      choices: [K("after lunch"), P("before breakfast", "D-PLAUSIBLE-UNSUPPORTED"), P("during assembly", "D-PLAUSIBLE-UNSUPPORTED"), P("after home time", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_074)" },
    { u: "precise_detail", lvl: 2, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "Talia helped sort rolls before the bakery opened. One tray held plain rolls with soft tops. The other held rolls covered in seeds. Baker Tom chose the seeded rolls for the front counter. Talia put the plain rolls on the back shelf.",
      prompt: "Which rolls did Baker Tom choose for the front counter?",
      choices: [K("rolls with seeds on top"), P("rolls with soft plain tops", "D-PLAUSIBLE-UNSUPPORTED"), P("rolls with seeds mixed inside", "D-PLAUSIBLE-UNSUPPORTED"), P("rolls with a hard plain crust", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_032)" },
    { u: "precise_detail", lvl: 2, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "The garden club checked their plants after a hot weekend. Lettuce leaves were limp, but the tomatoes still stood tall. Mr. Hayes asked them to water the limp plants first. They watered the lettuce before the tomatoes. Then they wrote both jobs in their notebook.",
      prompt: "Which plants did the students water first?",
      choices: [K("the lettuce before the tomatoes"), P("the tomatoes before the lettuce", "D-PLAUSIBLE-UNSUPPORTED"), P("neither plant until the next morning", "D-PLAUSIBLE-UNSUPPORTED"), P("both plants at the same time", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_033)" },
    { u: "precise_detail", lvl: 2, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "Amira found a bookmark beside the mystery books. Daniel's name was written on it in blue ink. Amira's own bookmark had her name in green. She gave the lost bookmark to the librarian. The librarian put it in Daniel's book box.",
      prompt: "Whose name was on the bookmark?",
      choices: [K("Daniel's"), P("Amira's", "D-PLAUSIBLE-UNSUPPORTED"), P("the librarian's", "D-PLAUSIBLE-UNSUPPORTED"), P("Ms. Chen's", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_034)" },
    { u: "precise_detail", lvl: 2, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "Sofia played her piano song before the school concert. She began well and played the middle without stopping. She kept missing only the final note. Her teacher asked her to practice the ending slowly. Three careful tries helped her play that note correctly.",
      prompt: "Which part of the song was difficult for Sofia?",
      choices: [K("the very last piano note"), P("the very first piano note", "D-PLAUSIBLE-UNSUPPORTED"), P("the quiet middle piano note", "D-PLAUSIBLE-UNSUPPORTED"), P("the loud opening piano note", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_039)" },
    { u: "precise_detail", lvl: 2, ph: 2, v: 5, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "Nadia took photographs for the class newsletter. The chess club held its board in their photo. The garden team held fresh carrots in theirs. The teacher chose the picture with the carrots. Nadia placed that picture on the front page.",
      prompt: "Which picture did the teacher choose?",
      choices: [K("the garden team holding carrots"), P("the garden team planting carrots", "D-PLAUSIBLE-UNSUPPORTED"), P("the chess club holding a board", "D-PLAUSIBLE-UNSUPPORTED"), P("the chess club playing a game", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_058)" },
    { u: "precise_detail", lvl: 2, ph: 2, v: 6, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "Two cups in the science corner held the same soil. The cup with a red label had been watered. The cup with a blue label had stayed dry. Priya pressed a finger into each cup. The soil with the red label felt softer.",
      prompt: "Which soil felt softer?",
      choices: [K("the watered soil with the red label"), P("the dry soil with the blue label", "D-PLAUSIBLE-UNSUPPORTED"), P("the dry soil with the red label", "D-PLAUSIBLE-UNSUPPORTED"), P("the watered soil with the blue label", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_080)" },
    { u: "precise_detail", lvl: 2, ph: 2, v: 7, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "The class packed snacks for the field trip. Apples and cheese stayed in the fridge until morning. Crackers stayed in a sealed box on the counter. Ms. Reed checked both places before loading the cooler. She packed the apples and cheese last.",
      prompt: "Which snacks went in the fridge?",
      choices: [K("apples and cheese in the fridge"), P("apples and crackers in the fridge", "D-PLAUSIBLE-UNSUPPORTED"), P("cheese and crackers on the counter", "D-PLAUSIBLE-UNSUPPORTED"), P("apples and cheese on the counter", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_089)" },
    { u: "what_happened", lvl: 1, ph: 1, v: 9, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Priya made a poster about sea turtles. She wrote the title across the top. Then she drew a turtle on the beach. It was crawling toward the water. She added labels for the beach and ocean.",
      prompt: "What did Priya draw on the poster?",
      choices: [K("a turtle heading into the sea"), P("a turtle moving away from water", "D-PLAUSIBLE-UNSUPPORTED"), P("a turtle swimming far from shore", "D-PLAUSIBLE-UNSUPPORTED"), P("a turtle hiding from the sun", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_012)", retention: true },
    { u: "what_happened", lvl: 1, ph: 1, v: 10, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Sienna visited the fire station with her class. A firefighter showed them a jacket and helmet. She lifted the jacket with both hands. It weighed more than her full school bag. That made her open her eyes wide.",
      prompt: "What surprised Sienna about the jacket?",
      choices: [K("it was heavier than her bag"), P("it was smaller than her coat", "D-PLAUSIBLE-UNSUPPORTED"), P("it was wetter than her boots", "D-PLAUSIBLE-UNSUPPORTED"), P("it was brighter than her scarf", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_015)", retention: true },
    { u: "what_happened", lvl: 1, ph: 1, v: 11, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Jalen cleaned the lunch tables after eating. He sprayed the first table with water. Then he wiped it with a blue cloth. A sticky spot needed a second wipe. He moved on when the table was clean.",
      prompt: "What did Jalen use to wipe the table?",
      choices: [K("a blue cloth"), P("a blue sponge", "D-PLAUSIBLE-UNSUPPORTED"), P("a red cloth", "D-PLAUSIBLE-UNSUPPORTED"), P("a red sponge", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_017)", retention: true },
    { u: "where", lvl: 1, ph: 1, v: 12, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Nora chose a silver sticker after reading time. Her friend chose a star-shaped sticker. Nora put hers on her notebook cover. Her friend kept hers on her pencil box. Nora showed her notebook to Mom after school.",
      prompt: "Where did Nora put her sticker?",
      choices: [K("on her notebook cover"), P("on her pencil box", "D-PLAUSIBLE-UNSUPPORTED"), P("inside her notebook cover", "D-PLAUSIBLE-UNSUPPORTED"), P("inside her pencil box", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_069)", retention: true },
    { u: "where", lvl: 1, ph: 1, v: 13, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Amara left her flute case under her chair. Jacob saw it after their music lesson. He called to Amara near the door. Then he carried her case across the room. She thanked him and zipped it shut.",
      prompt: "Where was Amara's flute case?",
      choices: [K("under the chair"), P("on the chair", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the chair", "D-PLAUSIBLE-UNSUPPORTED"), P("behind the chair", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_076)", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 9, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "The teacher asked each group to use a different place. Marcus's group needed water from the slow part of the river. Only the patch near the reeds had slow water. The water near the bridge moved fast. Marcus took his jar to the right place and filled it.",
      prompt: "Where did Marcus fill his jar?",
      choices: [K("in the calm patch by the plants"), P("in the fast patch by the bridge", "D-PLAUSIBLE-UNSUPPORTED"), P("in the classroom tap by the sink", "D-PLAUSIBLE-UNSUPPORTED"), P("in the deep pool by the waterfall", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_031)", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 10, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "Noah and his uncle crossed a wooden footbridge. Its left side had a loose board by the rail. The right side had no loose boards. His uncle asked the park worker to close the unsafe side. The worker put a barrier across that side.",
      prompt: "Which side did the worker close?",
      choices: [K("the left side with the loose board"), P("the right side with the firm boards", "D-PLAUSIBLE-UNSUPPORTED"), P("both sides beside the bridge rail", "D-PLAUSIBLE-UNSUPPORTED"), P("neither side of the wooden bridge", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_035)", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 11, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "The firefighter showed the class a radio and a light. The radio let her hear messages from her team. The light helped her see inside dark rooms. She clipped the tool for hearing messages to her jacket. She kept the light in her hand.",
      prompt: "Which tool did she clip to her jacket?",
      choices: [K("the tool that receives team messages"), P("the tool that lights dark rooms", "D-PLAUSIBLE-UNSUPPORTED"), P("the clothes that block fierce heat", "D-PLAUSIBLE-UNSUPPORTED"), P("the tank that holds clean air", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_036)", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 12, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "The class counted butterflies in two parts of the meadow. Chloe's partner counted the ones on the purple flowers. Five butterflies sat there before flying away. Two others stayed on the yellow flowers. Chloe wrote her partner's count in her guide.",
      prompt: "How many butterflies did Chloe's partner count?",
      choices: [K("five butterflies"), P("two butterflies", "D-PLAUSIBLE-UNSUPPORTED"), P("seven butterflies", "D-PLAUSIBLE-UNSUPPORTED"), P("three butterflies", "D-OPPOSITE")],
      note: "Numeric detail extraction retention check.", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 13, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "Ethan and Grandma waited for the island train. The board showed two trains coming to the station. The city train would arrive at nine fifteen. The island train would arrive at ten thirty. Ethan read their train's time aloud to Grandma.",
      prompt: "What time did the screen say the train would arrive?",
      choices: [K("ten thirty"), P("nine fifteen", "D-PLAUSIBLE-UNSUPPORTED"), P("eleven forty", "D-PLAUSIBLE-UNSUPPORTED"), P("eight o'clock", "D-OPPOSITE")],
      note: "Time-detail extraction retention check.", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 14, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "The class sorted things after the spring fair. Clean paper could go in the recycling bag. Dirty plastic had to go in the trash. Mateo found clean paper cups and dirty plastic spoons. He checked the rule before choosing a bag for each.",
      prompt: "What did Mateo put in the recycling bag?",
      choices: [K("the clean paper cups"), P("the dirty plastic spoons", "D-PLAUSIBLE-UNSUPPORTED"), P("both the cups and spoons", "D-PLAUSIBLE-UNSUPPORTED"), P("neither cups nor spoons", "D-OPPOSITE")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_040)", retention: true },

    // ---- hand-written gap fills (L1 who x3, number_detail x4; precise x1) ----
    it("who", 1, 2, 6,
      "The class pet needed a school-break home. Four children offered to care for it. Miss Adu picked a name from a cup. The folded paper had Femi's name on it. Femi carried the pet's cage to the car.",
      "Who took the class pet home?",
      [K("Femi"), P("Miss Adu","D-PLAUSIBLE-UNSUPPORTED"), P("the taxi driver","D-PLAUSIBLE-UNSUPPORTED"), P("the custodian","D-PLAUSIBLE-UNSUPPORTED")]),
    it("who", 1, 2, 7,
      "Mr. Pole could not find the race whistle. He checked both pockets in his coat. Sana had a spare whistle on her bag. She lent it to him for the race. He blew it and the children started running.",
      "Who lent the whistle?",
      [K("Sana"), P("Mr Pole","D-PLAUSIBLE-UNSUPPORTED"), P("the winner","D-PLAUSIBLE-UNSUPPORTED"), P("a parent","D-PLAUSIBLE-UNSUPPORTED")]),
    it("who", 1, 2, 8,
      "Rain made a puddle by the school door. Someone mopped it before the bell each week. Early one morning, Priya saw who helped. Bill, the bus driver, was holding the mop. She waved to him through the window.",
      "Who mopped the puddle?",
      [K("Bill, who drives the bus"), P("Priya, who saw the mop", "D-PLAUSIBLE-UNSUPPORTED"), P("the helper who serves school meals", "D-PLAUSIBLE-UNSUPPORTED"), P("the teacher at the school window", "D-OPPOSITE")]),
    it("number_detail", 1, 2, 5,
      "Grandma wrote a short shopping list for Tayo. It said six eggs and two lemons. She also needed one small bag of sugar. Tayo repeated the list while he walked. He brought everything home from the shop.",
      "How many eggs were on the list?",
      [K("six"), P("two","D-SEQUENCE-SWAP"), P("one","D-SEQUENCE-SWAP"), P("ten","D-PLAUSIBLE-UNSUPPORTED")]),
    it("number_detail", 1, 2, 6,
      "The class counted animals during a nature walk. They saw five snails on a wall. Three white butterflies flew beside the hedge. One turtle crossed the path in front. Everyone waited until it reached the other side.",
      "How many butterflies did the class count?",
      [K("three"), P("five","D-SEQUENCE-SWAP"), P("one","D-SEQUENCE-SWAP"), P("seven","D-PLAUSIBLE-UNSUPPORTED")]),
    it("number_detail", 1, 2, 7,
      "The bake sale opened at ten o'clock. All the oat bars sold by ten thirty. The principal arrived at eleven o'clock. She bought the last brownie on the plate. Then the helpers packed the table away.",
      "When did the bake sale open?",
      [K("at ten o'clock"), P("at 10:30","D-SEQUENCE-SWAP"), P("at eleven","D-SEQUENCE-SWAP"), P("at lunchtime","D-PLAUSIBLE-UNSUPPORTED")]),
    it("number_detail", 1, 2, 8,
      "Nita used twenty red blocks for her tower. Ten blue blocks formed the middle. Four yellow blocks balanced at the top. The tower stood for one whole minute. Then the cat came to look at it.",
      "How many blue blocks were in the tower?",
      [K("ten"), P("twenty","D-SEQUENCE-SWAP"), P("four","D-SEQUENCE-SWAP"), P("forty","D-PLAUSIBLE-UNSUPPORTED")]),
    it("precise_detail", 2, 2, 8,
      "Two blue lunchboxes had the same rocket sticker. Cal's box had a dent in one corner. Robi's box had a smooth corner and smelled of orange. Cal looked at the corners before taking his lunchbox. He left the smooth box on the bench for Robi.",
      "How did Cal know which lunchbox was his?",
      [K("a dent in one corner"), P("a smooth corner and lid", "D-PLAUSIBLE-UNSUPPORTED"), P("the rocket sticker on top", "D-PLAUSIBLE-UNSUPPORTED"), P("the smell of an orange", "D-OPPOSITE")]),

    // ---- detail_across_sentences (L2, 8 new) ----
    it("detail_across_sentences", 2, 1, 1,
      "Ola filled the bird feeder with seeds at breakfast. At lunchtime, half the seeds had gone. After school, she found only dust in the feeder. She had not added more seeds during the day. A pigeon rested on the nearby fence.",
      "Which checks show the feeder changing from full to empty?",
      [K("at breakfast and after school"), P("at lunchtime and after school", "D-PLAUSIBLE-UNSUPPORTED"), P("at breakfast and the next morning", "D-PLAUSIBLE-UNSUPPORTED"), P("at lunchtime and the next morning", "D-OPPOSITE")],
      "answer assembled from first and third sentences"),
    it("detail_across_sentences", 2, 1, 2,
      "Three lost things stayed in a box on Friday. Jun took his striped scarf at morning break. Ivy took her water bottle after lunch. The only thing left was a dinosaur glove. The box stayed locked in school until Monday.",
      "Which treasure was still there on Saturday?",
      [K("the glove with a dinosaur"), P("the scarf with coloured stripes", "D-PLAUSIBLE-UNSUPPORTED"), P("the bottle used for water", "D-PLAUSIBLE-UNSUPPORTED"), P("the hat made from wool", "D-OPPOSITE")]),
    it("detail_across_sentences", 2, 1, 3,
      "Dad planted a tree when each child was born. Asha's tree has cherries, and Ben's has apples. Baby Mo has the youngest tree, a plum. This year, the apple tree gave the most fruit. Ben helped Dad carry all its full baskets.",
      "Whose tree gives the most fruit?",
      [K("Ben's tree"), P("Asha's tree", "D-PLAUSIBLE-UNSUPPORTED"), P("baby Mo's tree", "D-PLAUSIBLE-UNSUPPORTED"), P("Dad's pear tree", "D-OPPOSITE")]),
    it("detail_across_sentences", 2, 1, 4,
      "The school play needed a crown, sword and throne. Raj brought things made from a recycling box. Nell lent the clothes from her costume box. The sword was made of cardboard from the recycling box. Two gold chairs from the staff room became the throne.",
      "Where did the sword come from?",
      [K("Raj's recycling box"), P("Nell's costume box", "D-PLAUSIBLE-UNSUPPORTED"), P("the staff room chairs", "D-PLAUSIBLE-UNSUPPORTED"), P("the class art cupboard", "D-OPPOSITE")]),
    it("detail_across_sentences", 2, 2, 5,
      "The swimming lesson had three groups. Beginners stayed in water where they could stand. The middle group swam across with a kickboard. The top group swam full lengths without one. Keya moved from the middle group to the top group today. She handed her kickboard to a beginner.",
      "What is Keya allowed to do now?",
      [K("swim full lengths without a board"), P("swim across the pool with a board", "D-PLAUSIBLE-UNSUPPORTED"), P("stay where her feet touch the floor", "D-PLAUSIBLE-UNSUPPORTED"), P("dive from the high diving board", "D-OPPOSITE")],
      "needs the group rules AND her promotion"),
    it("detail_across_sentences", 2, 2, 6,
      "The twins sorted paper cups after the fair. They put half in the classroom cabinet. The remaining cups were shared between two art tables. Each table needed the same number of cups. The twins checked that both stacks matched before leaving.",
      "Where did the remaining cups go?",
      [K("equal stacks on the two art tables"), P("one large stack on an art table", "D-PLAUSIBLE-UNSUPPORTED"), P("equal stacks in two classroom cabinets", "D-PLAUSIBLE-UNSUPPORTED"), P("one small stack by the fair door", "D-OPPOSITE")],
      "integrates the storage sentence with the equal-table distribution sentence"),
    it("detail_across_sentences", 2, 2, 7,
      "The garden chart said to water on Mondays and Thursdays. Another rule said to skip watering after heavy rain. Rain poured all Thursday morning. Priya checked the chart and looked at the wet garden. She left the watering can under the sink.",
      "Why did Priya skip the watering?",
      [K("rain had already watered the garden"), P("Thursday was a day without watering", "D-PLAUSIBLE-UNSUPPORTED"), P("plant food had replaced the watering", "D-PLAUSIBLE-UNSUPPORTED"), P("Priya could not find the watering can", "D-OPPOSITE")],
      "rule sentence + weather sentence must combine"),
    it("detail_across_sentences", 2, 2, 8,
      "Three benches in the park remembered people from the town. The newest one was for Mr. Alam. He had fed sparrows here for forty years. The carpenter added a seed dish to this bench. The other benches had flowers beside them instead.",
      "Which bench has a seed dish, and why?",
      [K("Mr. Alam's, to remember feeding birds"), P("Mr. Alam's, to hold flowers in water", "D-PLAUSIBLE-UNSUPPORTED"), P("the oldest, to remember feeding birds", "D-PLAUSIBLE-UNSUPPORTED"), P("the oldest, to hold flowers in water", "D-OPPOSITE")]),

    // ---- which_is_not (L2, 8 new) ----
    it("which_is_not", 2, 1, 1,
      "The class cleaned its aquarium on Friday. They rinsed the gravel through a strainer. They wiped the glass inside and outside. The plastic castle was washed until it shone. The fish waited in a bucket during all this work.",
      "Which of these is NOT in the story?",
      [K("the fish were given new food"), P("the gravel was rinsed","D-DETAIL-AS-MAIN"), P("the glass was wiped","D-DETAIL-AS-MAIN"), P("the fish waited in a bucket","D-DETAIL-AS-MAIN")],
      "the key is plausible but absent — verbatim matchers pick a true fact and miss"),
    it("which_is_not", 2, 1, 2,
      "Helpers prepared the field for sports day. They painted white lanes on the grass. They counted beanbags into buckets beside the track. They tied the finish tape between two posts. Finally, someone tested the loudspeaker before the teams arrived.",
      "Which of these does the story NOT mention?",
      [K("medals were polished"), P("lanes were painted", "D-PLAUSIBLE-UNSUPPORTED"), P("beanbags were counted", "D-PLAUSIBLE-UNSUPPORTED"), P("the loudspeaker was tested", "D-OPPOSITE")]),
    it("which_is_not", 2, 1, 3,
      "Amir packed his bag the evening before the trip. He rolled up a raincoat to save space. He added sandwiches and a bottle of water. His notebook and pencil were ready for bird spotting. He put a flashlight at the top of the bag.",
      "Which item is NOT in Amir's bag?",
      [K("a camera"), P("a raincoat","D-DETAIL-AS-MAIN"), P("a notebook","D-DETAIL-AS-MAIN"), P("a flashlight","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 1, 4,
      "Grandpa kept his shed tidy. Screwdrivers hung on hooks in size order. Clear jars of screws stood on the window shelf. The lawn mower stayed under its cover. A radio near the door played music while he worked.",
      "Which of these is NOT described in the shed?",
      [K("a box of old paintbrushes"), P("screwdrivers on hooks","D-DETAIL-AS-MAIN"), P("jars of screws","D-DETAIL-AS-MAIN"), P("a radio by the door","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 2, 5,
      "The book fair filled the school hall for a day. Tables held picture books and joke books. An author signed books at a special table. Reading club tokens counted double at the fair. The librarian wore a dress with a book pattern.",
      "Which of these did NOT happen at the fair?",
      [K("the fair sold out of tickets early"), P("an author signed books","D-DETAIL-AS-MAIN"), P("reading tokens counted double","D-DETAIL-AS-MAIN"), P("the librarian wore her book dress","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 2, 6,
      "The power went off along the street. Neighbors put candles in glass jars on their steps. Mr. Okoye brought his guitar outside and played songs. The food truck could cook using its own gas. It kept serving warm meals while people listened.",
      "Which of these is NOT part of the story?",
      [K("a bonfire was lit in the road"), P("candles stood in glass jars", "D-PLAUSIBLE-UNSUPPORTED"), P("a guitar played songs", "D-PLAUSIBLE-UNSUPPORTED"), P("the food truck kept serving", "D-OPPOSITE")]),
    it("which_is_not", 2, 2, 7,
      "The museum put three rules beside the dinosaur room. Visitors had to walk on its smooth floor. They had to whisper so others could listen. They could take photos but could not use flash. A helper showed each group the rules before entering.",
      "Which rule is NOT on the door?",
      [K("no eating or drinking"), P("walk, don't run","D-DETAIL-AS-MAIN"), P("whisper","D-DETAIL-AS-MAIN"), P("no flash photos","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 2, 8,
      "Everyone had a job during the garden harvest. The tall cousins picked green beans. The younger cousins dug potatoes with small trowels. Grandma weighed the vegetables on her kitchen scale. The largest pumpkin went home in a wheelbarrow.",
      "Which of these is NOT in the story?",
      [K("carrots were pulled and washed"), P("beans were picked","D-DETAIL-AS-MAIN"), P("potatoes were dug up","D-DETAIL-AS-MAIN"), P("the pumpkin rode in the wheelbarrow","D-DETAIL-AS-MAIN")]),

    // ---- retention gap fills (4 new) ----
    it("who", 1, 1, 12,
      "The classroom plants looked dry after the break. On Monday, their soil was damp again. The principal asked who had watered them. Gita smiled and said she had done it. She put the empty watering can away.",
      "Who watered the plants?",
      [K("Gita"), P("the principal","D-PLAUSIBLE-UNSUPPORTED"), P("the rain","D-PLAUSIBLE-UNSUPPORTED"), P("nobody","D-OPPOSITE")], "", { retention: true }),
    it("number_detail", 1, 1, 12,
      "Grandma takes the ferry to the island. That part takes twenty minutes. The bus ride from the harbor takes ten. Her whole trip takes half an hour. She spends the afternoon visiting her family.",
      "How long does the ferry take?",
      [K("twenty minutes"), P("ten minutes","D-SEQUENCE-SWAP"), P("half an hour","D-SEQUENCE-SWAP"), P("an afternoon","D-SEQUENCE-SWAP")], "", { retention: true }),
    it("which_is_not", 2, 1, 9,
      "The family set up a table for their yard sale. They checked every board game for missing pieces. A shoebox held their old dinosaur figures. Outgrown rain boots stood in order from smallest to largest. A toy cash register was ready to count sales.",
      "Which of these was NOT on the table?",
      [K("a basket of picture books"), P("board games","D-DETAIL-AS-MAIN"), P("dinosaur figures","D-DETAIL-AS-MAIN"), P("outgrown rain boots","D-DETAIL-AS-MAIN")], "", { retention: true }),
    it("detail_across_sentences", 2, 1, 15,
      "The coach chose each runner's place from their best skill. Jaya was best at starting quickly. Omar was best at keeping a lead without being caught. The coach wanted that skill for the final runner. Ben and Priw took the two middle places.",
      "Why did Omar run last?",
      [K("he could keep a lead until the finish"), P("he could start faster than the other runners", "D-PLAUSIBLE-UNSUPPORTED"), P("he could keep the middle runners at one speed", "D-PLAUSIBLE-UNSUPPORTED"), P("he could tell each runner when to start", "D-OPPOSITE")], "", { retention: true }),
    // Fresh retry stock: four additional questions in each phase.
    {
      "u": "detail_across_sentences",
      "lvl": 2,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "detail_across_sentences",
      "passage": "The blue crate held books, and the red crate held games. Every book had a yellow return label. The games had plain white labels.",
      "prompt": "Which items had yellow labels?",
      "choices": [
        {
          "t": "the contents of the blue crate",
          "r": "KEY",
          "k": true
        },
        {
          "t": "the games inside the red crate",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "the contents of both coloured crates",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "the empty boxes beside the crates",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "precise_detail",
      "lvl": 2,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "precise_detail",
      "passage": "Each team could choose three tools for the building task. Noor chose scissors, a ruler, and tape. She left the glue and paint on the supply table.",
      "prompt": "Which tool did Noor leave behind?",
      "choices": [K("glue used to join pieces"), P("ruler used to measure pieces", "D-PLAUSIBLE-UNSUPPORTED"), P("tape used to fasten pieces", "D-PLAUSIBLE-UNSUPPORTED"), P("scissors used to cut pieces", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "which_is_not",
      "lvl": 2,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "which_is_not",
      "passage": "The notice said to bring a hat and a water bottle. Lunch would be provided at the park. Children also needed shoes suitable for walking.",
      "prompt": "Which instruction was NOT on the notice?",
      "choices": [
        {
          "t": "bring your own packed lunch",
          "r": "KEY",
          "k": true
        },
        {
          "t": "carry water for the outing",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "wear shoes for the walk",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "bring a hat for outdoors",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "detail_across_sentences",
      "lvl": 2,
      "ph": 1,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "detail_across_sentences",
      "passage": "Three pets arrived at the clinic. The rabbit came before the cat, and the dog arrived last. Only the first pet needed its claws trimmed.",
      "prompt": "Which pet needed a claw trim?",
      "choices": [K("the first arrival, a rabbit"), P("the next arrival, a cat", "D-PLAUSIBLE-UNSUPPORTED"), P("the last arrival, a dog", "D-PLAUSIBLE-UNSUPPORTED"), P("the cat and dog together", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "precise_detail",
      "lvl": 2,
      "ph": 2,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "precise_detail",
      "passage": "The morning ferry left at nine and took thirty minutes. Its afternoon return left at three and took forty minutes. Heavy wind slowed the return journey.",
      "prompt": "How long did the return journey take?",
      "choices": [
        {
          "t": "forty minutes on the water",
          "r": "KEY",
          "k": true
        },
        {
          "t": "thirty minutes on the water",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "three hours on the water",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "nine minutes on the water",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "detail_across_sentences",
      "lvl": 2,
      "ph": 2,
      "v": 22,
      "fmt": "COMPREHENSION",
      "cell": "detail_across_sentences",
      "passage": "Pia and Jules carried different boxes into the hall. Pia’s box was lighter, but Jules’s was wider. The wide box contained the folding display stand.",
      "prompt": "Who carried the display stand?",
      "choices": [
        {
          "t": "Jules, carrying the wider box",
          "r": "KEY",
          "k": true
        },
        {
          "t": "Pia, carrying the lighter box",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "both children sharing one box",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "neither child entering the hall",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "which_is_not",
      "lvl": 2,
      "ph": 2,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "which_is_not",
      "passage": "For the performance, the choir wore green scarves over white shirts. Each singer held a small lamp. They stood in two rows on the stage.",
      "prompt": "Which detail is NOT in the description?",
      "choices": [
        {
          "t": "the singers wore matching green hats",
          "r": "KEY",
          "k": true
        },
        {
          "t": "the scarves were worn over white shirts",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "the singers held lamps during the performance",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "the choir stood in two separate rows",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "detail_across_sentences",
      "lvl": 2,
      "ph": 2,
      "v": 23,
      "fmt": "COMPREHENSION",
      "cell": "detail_across_sentences",
      "passage": "The class made one shelter with sticks and another with card. They tested both using the same small fan. Only the stick shelter stayed standing during the test.",
      "prompt": "Which shelter did the fan blow down?",
      "choices": [
        {
          "t": "the shelter made from card",
          "r": "KEY",
          "k": true
        },
        {
          "t": "the shelter made from sticks",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "both shelters during the same test",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "neither of the two shelters",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "who",
      "lvl": 1,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "who",
      "passage": "A cleaner found a lunchbox in the empty hall. Its label had Hana’s name. The cleaner gave it to Hana after class.",
      "prompt": "Whose lunchbox was found?",
      "choices": [
        {
          "t": "the one belonging to Hana",
          "r": "KEY",
          "k": true
        },
        {
          "t": "the one belonging to the cleaner",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "the teacher’s own packed lunch",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "the visitor’s bag of food",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "retention": true,
      "note": "Fresh authored retry item: distinct situation and evidence."
    }
]
};
