// Key Details — v3 bank (wave W2). SALVAGE + top-up: the legacy
// highQualityComprehensionReplacements bank was the audit's one genuinely
// authored comprehension set (93/93 distinct skeletons, verified), so its best
// items ship verbatim here with cell tags and provenance; the cells the legacy
// bank never had (which_is_not, detail_across_sentences) and the small gaps
// (who / number_detail L1) are hand-written new.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, prompt, choices, note = "", extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage, prompt, choices, media: "text", note, ...extra
});

// Literal-detail questions still require comprehension: keys paraphrase the
// stated detail so a child cannot win by choosing the option that copies the
// most passage words. Number/time keys also switch notation.
const PARAPHRASED_LITERAL_KEYS = new Map(Object.entries({
  "a book with photographs of lightning": "the storm photo book",
  "neat silver ladder lines": "tidy marks on the ladder",
  "a tiny crab was inside it": "the shell was somebody's home",
  "it tore": "it split open",
  "the bike chain was loose": "the chain was not tight",
  "an acorn": "a nut from an oak tree",
  "so they would not crack": "to keep them safe from breaking",
  "on the sunny classroom window ledge": "in bright light",
  "into the hall": "inside the school building",
  "on the bottom": "beneath all the other books",
  "beside the stairs": "next to the staircase",
  "in the side pocket of his bag": "in an outside pocket",
  "in the lost-and-found box": "in the box for lost items",
  "beside the playground gate": "near the entrance to the play area",
  "Coach Lee": "the sports teacher",
  "Rosa's cousin": "her relative",
  "the choir teacher": "her singing teacher",
  "three": "3",
  "the last note": "the very end of the music",
  "the garden team holding fresh carrots": "the carrot-holding group",
  "a turtle crawling toward the water": "a sea animal heading to shore",
  "a two-way radio": "the device used to hear messages",
  "from breakfast until the end of school": "through most of the school day",
  "a blue cloth": "blue fabric",
  "on the front of her notebook": "on her notebook cover",
  "under the chair": "beneath a seat",
  "five": "5",
  "ten thirty": "10:30"
}));

export default {
  skillId: "key_details",
  skillName: "Key Details",
  items: [
    { u: "what_happened", lvl: 1, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Owen wanted a book about storms for his weather project. He looked on the science shelf but could not find one. The librarian showed him a basket of weather books near the window. Owen chose a book with photographs of lightning.",
      prompt: "What kind of book did Owen choose?",
      choices: [K("a book with photographs of lightning"), P("a book of animal jokes", "D-PLAUSIBLE-UNSUPPORTED"), P("a cookbook about soup", "D-PLAUSIBLE-UNSUPPORTED"), P("a story about a lost puppy", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_002)" },
    { u: "what_happened", lvl: 1, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Leo painted a red fire truck during art class. His wide brush made the ladder look messy. Ms. Chen gave him a thinner brush from the art box. Leo used the new brush to paint neat silver ladder lines.",
      prompt: "What did Leo paint with the thinner brush?",
      choices: [K("neat silver ladder lines"), P("green tree leaves", "D-PLAUSIBLE-UNSUPPORTED"), P("large black wheels", "D-PLAUSIBLE-UNSUPPORTED"), P("a yellow sun", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_004)" },
    { u: "what_happened", lvl: 1, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Jonah walked on the beach with his aunt. They collected empty shells for a science tray. One shell had a tiny crab tucked inside it. Jonah left that shell on the sand and chose three empty shells instead.",
      prompt: "Why did Jonah leave one shell on the sand?",
      choices: [K("a tiny crab was inside it"), P("it was too heavy to carry", "D-PLAUSIBLE-UNSUPPORTED"), P("it belonged to a shop", "D-PLAUSIBLE-UNSUPPORTED"), P("it was painted blue", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_005)" },
    { u: "what_happened", lvl: 1, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Arlo carried warm rolls from the bakery counter. The paper bag tore before he reached the door. Two rolls slipped onto a clean tray near the counter. Baker Tom gave Arlo a stronger bag.",
      prompt: "What happened to Arlo's first bag?",
      choices: [K("it tore"), P("it turned blue", "D-PLAUSIBLE-UNSUPPORTED"), P("it was empty", "D-PLAUSIBLE-UNSUPPORTED"), P("it fell into water", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_006)" },
    { u: "what_happened", lvl: 1, ph: 2, v: 5, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Nina rode her bike along the park path. A loose chain made the pedals stop turning. She walked the bike to a repair bench near the gate. Her dad fixed the chain with a small tool.",
      prompt: "Why did Nina stop riding?",
      choices: [K("the bike chain was loose"), P("the path was closed", "D-PLAUSIBLE-UNSUPPORTED"), P("the bell was too loud", "D-PLAUSIBLE-UNSUPPORTED"), P("the tire was purple", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_007)" },
    { u: "what_happened", lvl: 1, ph: 2, v: 6, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Eli saw a small squirrel near the park bench. It held an acorn and stayed very still. Park Ranger Kim asked the children to step back quietly. After a minute, the squirrel ran up the tree.",
      prompt: "What did the squirrel hold?",
      choices: [K("an acorn"), P("a sandwich", "D-PLAUSIBLE-UNSUPPORTED"), P("a blue ribbon", "D-PLAUSIBLE-UNSUPPORTED"), P("a pencil", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_009)" },
    { u: "what_happened", lvl: 1, ph: 2, v: 7, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Nora was in charge of the class calendar. She crossed off Monday after morning meeting. Then she circled Friday because the class trip was on Friday. Several students asked how many days were left.",
      prompt: "Which day did Nora circle?",
      choices: [K("Friday"), P("Monday", "D-PLAUSIBLE-UNSUPPORTED"), P("Sunday", "D-PLAUSIBLE-UNSUPPORTED"), P("Tuesday", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_010)" },
    { u: "what_happened", lvl: 1, ph: 2, v: 8, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Lucas helped unpack groceries after school. The eggs were in a carton at the top of the bag. Lucas lifted them out first so they would not crack. Then he put the heavier cans on the shelf.",
      prompt: "Why did Lucas lift out the eggs first?",
      choices: [K("so they would not crack"), P("so the cans would freeze", "D-PLAUSIBLE-UNSUPPORTED"), P("so the shelf would move", "D-PLAUSIBLE-UNSUPPORTED"), P("so the bag would turn blue", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_011)" },
    { u: "where", lvl: 1, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Maya planted sunflower seeds in a small pot. She wrote her name on a paper label and pushed it into the soil. After watering the pot, she placed it on the sunny classroom window ledge. On Friday, a tiny green shoot appeared.",
      prompt: "Where did Maya place the pot?",
      choices: [K("on the sunny classroom window ledge"), P("under her desk", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the lunch trays", "D-PLAUSIBLE-UNSUPPORTED"), P("inside her backpack", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_001)" },
    { u: "where", lvl: 1, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Ruby watched dark clouds gather over the field. Her class had planned to eat lunch outside. Miss Green heard thunder in the distance. She moved everyone into the hall before the rain began.",
      prompt: "Where did Miss Green move the class?",
      choices: [K("into the hall"), P("onto the field", "D-PLAUSIBLE-UNSUPPORTED"), P("behind the shed", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the road", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_008)" },
    { u: "where", lvl: 1, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Finn helped his neighbor carry books to a little free library. The shelf was almost full. Finn placed the small books upright and stacked the large books on the bottom. Then there was room for the whole pile.",
      prompt: "Where did Finn put the large books?",
      choices: [K("on the bottom"), P("beside the sink", "D-PLAUSIBLE-UNSUPPORTED"), P("in his lunch box", "D-PLAUSIBLE-UNSUPPORTED"), P("under the rug", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_013)" },
    { u: "where", lvl: 1, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Dylan studied a map before the museum trip. He found the dinosaur room beside the stairs. He showed the map to his partner on the bus. When they arrived, they walked straight to the dinosaur room.",
      prompt: "Where was the dinosaur room on the map?",
      choices: [K("beside the stairs"), P("under the cafe", "D-PLAUSIBLE-UNSUPPORTED"), P("inside the shop", "D-PLAUSIBLE-UNSUPPORTED"), P("behind the bus stop", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_022)" },
    { u: "where", lvl: 1, ph: 2, v: 5, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Hana sorted classroom games after indoor recess. She put puzzles on the top shelf and card games in the red bin. One puzzle box was open, so she checked that every piece was inside. Then she closed the lid.",
      prompt: "Where did Hana put the card games?",
      choices: [K("in the red bin"), P("on the top shelf", "D-PLAUSIBLE-UNSUPPORTED"), P("under the rug", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the door", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_026)" },
    { u: "where", lvl: 1, ph: 2, v: 6, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Toby brought a striped towel to swimming class. He folded it on the bench before getting into the pool. After the lesson, he dried his hair with the towel. Then he packed it in the side pocket of his bag.",
      prompt: "Where did Toby pack the towel?",
      choices: [K("in the side pocket of his bag"), P("under the pool ladder", "D-PLAUSIBLE-UNSUPPORTED"), P("inside a lunch tray", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the teacher's desk", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_061)" },
    { u: "where", lvl: 1, ph: 2, v: 7, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "Ivy found a coin near the classroom door. She did not put it in her pocket. She gave it to Ms. Lopez, who placed it in the lost-and-found box. At the end of the day, Omar came back to look for it.",
      prompt: "Where did Ms. Lopez put the coin?",
      choices: [K("in the lost-and-found box"), P("inside Ivy's pocket", "D-PLAUSIBLE-UNSUPPORTED"), P("under the rug", "D-PLAUSIBLE-UNSUPPORTED"), P("on the lunch table", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_062)" },
    { u: "where", lvl: 1, ph: 2, v: 8, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "A red glove was lying beside the playground gate. Hassan picked it up before the wind blew it away. He took it to the office after recess. The secretary pinned it to the lost items board.",
      prompt: "Where was the glove first found?",
      choices: [K("beside the playground gate"), P("inside the office drawer", "D-PLAUSIBLE-UNSUPPORTED"), P("under a classroom chair", "D-PLAUSIBLE-UNSUPPORTED"), P("on the bus seat", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_063)" },
    { u: "who", lvl: 1, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "The playground ball rolled under the bench during recess. Ava saw it before anyone stepped on it. She picked it up and gave it to Coach Lee. Coach Lee put the ball back in the equipment basket.",
      prompt: "Who did Ava give the ball to?",
      choices: [K("Coach Lee"), P("her brother", "D-PLAUSIBLE-UNSUPPORTED"), P("the librarian", "D-PLAUSIBLE-UNSUPPORTED"), P("a bus driver", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_003)" },
    { u: "who", lvl: 1, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "Miles helped his grandpa rake leaves. The wind blew leaves back across the path. Grandpa held the bag open while Miles pushed the leaves inside. They tied the bag before the wind could scatter them again.",
      prompt: "Who held the bag open?",
      choices: [K("Grandpa"), P("the teacher", "D-PLAUSIBLE-UNSUPPORTED"), P("the bus driver", "D-PLAUSIBLE-UNSUPPORTED"), P("Miles", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_016)" },
    { u: "who", lvl: 1, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "Grace opened her pencil box during writing time. Her red pencil was missing, while Maya wrote nearby with a blue one. Grace borrowed a red pencil from Noah. At the end of class, she returned it to him.",
      prompt: "Who lent Grace a red pencil?",
      choices: [K("Noah"), P("her teacher", "D-PLAUSIBLE-UNSUPPORTED"), P("Maya", "D-PLAUSIBLE-UNSUPPORTED"), P("the librarian", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_020)" },
    { u: "who", lvl: 1, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "At the family picnic, Rosa brought a beach ball. A gust of wind pushed it toward the pond. Her cousin caught it before it reached the water. Rosa thanked him and put the ball under the picnic blanket.",
      prompt: "Who caught the beach ball?",
      choices: [K("Rosa's cousin"), P("her teacher", "D-PLAUSIBLE-UNSUPPORTED"), P("a park ranger", "D-PLAUSIBLE-UNSUPPORTED"), P("her neighbor", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_028)" },
    { u: "who", lvl: 1, ph: 2, v: 5, fmt: "COMPREHENSION", cell: "who", media: "text",
      passage: "Dad printed a photo from the school concert. It showed Zoe standing beside the choir teacher. Zoe placed the photo in a yellow frame. She put the frame on the shelf above her desk.",
      prompt: "Who was standing beside Zoe in the photo?",
      choices: [K("the choir teacher"), P("the bus driver", "D-PLAUSIBLE-UNSUPPORTED"), P("her cousin", "D-PLAUSIBLE-UNSUPPORTED"), P("the librarian", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_072)" },
    { u: "number_detail", lvl: 1, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "number_detail", media: "text",
      passage: "Mara helped set out cups for the school picnic. She counted twenty students but placed only eighteen cups. Her friend noticed the mistake before lunch began. Mara added two more cups to the table.",
      prompt: "How many more cups did Mara add?",
      choices: [K("two"), P("eight", "D-PLAUSIBLE-UNSUPPORTED"), P("twenty", "D-PLAUSIBLE-UNSUPPORTED"), P("three", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_014)" },
    { u: "number_detail", lvl: 1, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "number_detail", media: "text",
      passage: "Lena listened carefully during music class. Mr. Hill played three high notes on the piano. Then Lena copied the notes on a small keyboard. Mr. Hill smiled because she played them in the correct order.",
      prompt: "How many high notes did Mr. Hill play?",
      choices: [K("three"), P("one", "D-PLAUSIBLE-UNSUPPORTED"), P("five", "D-PLAUSIBLE-UNSUPPORTED"), P("eight", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_064)" },
    { u: "number_detail", lvl: 1, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "number_detail", media: "text",
      passage: "The reading corner felt cold after the window was opened. Max carried two cushions from the shelf. He put one cushion on the blue chair and one on the rug. His group sat there during story time.",
      prompt: "How many cushions did Max carry?",
      choices: [K("two"), P("four", "D-PLAUSIBLE-UNSUPPORTED"), P("six", "D-PLAUSIBLE-UNSUPPORTED"), P("one", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_073)" },
    { u: "number_detail", lvl: 1, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "number_detail", media: "text",
      passage: "The classroom clock stopped during reading. Ella noticed that both hands stayed on twelve. Mr. Reed changed the battery after lunch. The clock began ticking again before home time.",
      prompt: "When did Mr. Reed change the battery?",
      choices: [K("after lunch"), P("before breakfast", "D-PLAUSIBLE-UNSUPPORTED"), P("during assembly", "D-PLAUSIBLE-UNSUPPORTED"), P("after home time", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_074)" },
    { u: "precise_detail", lvl: 2, ph: 1, v: 1, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "Before the bakery opened, Talia helped stack trays of rolls. One tray held plain rolls, and another held rolls with seeds on top. Baker Tom asked her to put the seeded rolls near the front counter. Customers usually bought those first.",
      prompt: "Which rolls did Talia put near the front counter?",
      choices: [K("the rolls with seeds on top"), P("the plain rolls", "D-PLAUSIBLE-UNSUPPORTED"), P("the burnt rolls", "D-PLAUSIBLE-UNSUPPORTED"), P("the rolls in a paper bag", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_032)" },
    { u: "precise_detail", lvl: 2, ph: 1, v: 2, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "The school garden club checked the vegetable beds after a hot weekend. The lettuce leaves looked limp, but the tomato plants were still strong. Mr. Hayes asked the students to water the lettuce first. Then they wrote the change in the garden notebook.",
      prompt: "Which plants did the students water first?",
      choices: [K("the lettuce"), P("the tomato plants", "D-PLAUSIBLE-UNSUPPORTED"), P("the apple tree", "D-PLAUSIBLE-UNSUPPORTED"), P("the flower pots", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_033)" },
    { u: "precise_detail", lvl: 2, ph: 1, v: 3, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "During reading time, Amira found a bookmark on the floor near the mystery shelf. The bookmark had Daniel's name written in blue ink. Amira gave it to the librarian instead of keeping it. The librarian placed it in Daniel's book box.",
      prompt: "Whose name was on the bookmark?",
      choices: [K("Daniel's"), P("Amira's", "D-PLAUSIBLE-UNSUPPORTED"), P("the librarian's", "D-PLAUSIBLE-UNSUPPORTED"), P("Ms. Chen's", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_034)" },
    { u: "precise_detail", lvl: 2, ph: 1, v: 4, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "Sofia practiced piano before the school concert. She kept missing the last note of the song. Her teacher asked her to play the final line slowly three times. After that, Sofia played the ending without stopping.",
      prompt: "Which part of the song was difficult for Sofia?",
      choices: [K("the last note"), P("the first word", "D-PLAUSIBLE-UNSUPPORTED"), P("the middle drumbeat", "D-PLAUSIBLE-UNSUPPORTED"), P("the title", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_039)" },
    { u: "precise_detail", lvl: 2, ph: 2, v: 5, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "Nadia took photographs for the class newsletter. She photographed the chess club, the art display, and the garden team. Her clearest picture showed the garden team holding fresh carrots. The teacher chose that picture for the front page.",
      prompt: "Which picture did the teacher choose?",
      choices: [K("the garden team holding fresh carrots"), P("the chess board under a chair", "D-PLAUSIBLE-UNSUPPORTED"), P("the empty hallway", "D-PLAUSIBLE-UNSUPPORTED"), P("the lunch menu", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_058)" },
    { u: "precise_detail", lvl: 2, ph: 2, v: 6, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "In the science corner, two cups held the same kind of soil. One cup was dry, and the other had been watered. Priya pressed a finger gently into each cup. The watered soil felt softer than the dry soil.",
      prompt: "Which soil felt softer?",
      choices: [K("the watered soil"), P("the dry soil", "D-PLAUSIBLE-UNSUPPORTED"), P("the soil in the bag", "D-PLAUSIBLE-UNSUPPORTED"), P("the soil on the shelf", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_080)" },
    { u: "precise_detail", lvl: 2, ph: 2, v: 7, fmt: "COMPREHENSION", cell: "precise_detail", media: "text",
      passage: "The class made a snack chart for the field trip. Apples and cheese went in the fridge until morning. Crackers stayed in a sealed box on the counter. Ms. Reed checked both places before loading the cooler.",
      prompt: "Which snacks went in the fridge?",
      choices: [K("apples and cheese"), P("crackers", "D-PLAUSIBLE-UNSUPPORTED"), P("sandwich wrappers", "D-PLAUSIBLE-UNSUPPORTED"), P("paper napkins", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_089)" },
    { u: "what_happened", lvl: 1, ph: 1, v: 9, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Priya made a poster about sea turtles. She wrote the title at the top in large letters. Then she drew a turtle crawling toward the water. Her teacher asked her to label the beach and the ocean.",
      prompt: "What did Priya draw on the poster?",
      choices: [K("a turtle crawling toward the water"), P("a chair with a cracked leg", "D-PLAUSIBLE-UNSUPPORTED"), P("a bike beside a gate", "D-PLAUSIBLE-UNSUPPORTED"), P("a bowl of soup", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_012)", retention: true },
    { u: "what_happened", lvl: 1, ph: 1, v: 10, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Sienna visited the fire station with her class. A firefighter showed them a heavy jacket and helmet. Sienna tried to lift the jacket with both hands. She was surprised because it weighed more than her school bag.",
      prompt: "What surprised Sienna about the jacket?",
      choices: [K("it was very heavy"), P("it was made of paper", "D-PLAUSIBLE-UNSUPPORTED"), P("it had no sleeves", "D-PLAUSIBLE-UNSUPPORTED"), P("it was kept in a lunch box", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_015)", retention: true },
    { u: "what_happened", lvl: 1, ph: 1, v: 11, fmt: "COMPREHENSION", cell: "what_happened", media: "text",
      passage: "Jalen helped clean the lunch tables. He sprayed the first table and wiped it with a blue cloth. A sticky spot was still there, so he wiped it again. When the spot was gone, he moved to the next table.",
      prompt: "What did Jalen use to wipe the table?",
      choices: [K("a blue cloth"), P("a red sponge", "D-PLAUSIBLE-UNSUPPORTED"), P("a paper plate", "D-PLAUSIBLE-UNSUPPORTED"), P("a green brush", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_017)", retention: true },
    { u: "where", lvl: 1, ph: 1, v: 12, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "After reading time, Nora chose a silver sticker from the reward box. She placed it on the front of her notebook. Her friend chose a star-shaped sticker. Nora showed her notebook to her mother after school.",
      prompt: "Where did Nora put her sticker?",
      choices: [K("on the front of her notebook"), P("inside the reward box", "D-PLAUSIBLE-UNSUPPORTED"), P("under her chair", "D-PLAUSIBLE-UNSUPPORTED"), P("on the classroom door", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p1_069)", retention: true },
    { u: "where", lvl: 1, ph: 1, v: 13, fmt: "COMPREHENSION", cell: "where", media: "text",
      passage: "During music practice, Amara forgot her flute case under the chair. Jacob saw it after the lesson ended. He carried it to Amara before she reached the hallway. Amara thanked him and zipped the case closed.",
      prompt: "Where was Amara's flute case?",
      choices: [K("under the chair"), P("inside the piano", "D-PLAUSIBLE-UNSUPPORTED"), P("on the playground", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the bus", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l1_p2_076)", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 9, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "Marcus joined his class for a river study. The teacher gave each group a clear jar and a label. Marcus filled his jar where the water moved slowly near the reeds. Back at school, his group compared the river water with tap water.",
      prompt: "Where did Marcus fill his jar?",
      choices: [K("in the calmest patch of the stream"), P("inside the school sink", "D-PLAUSIBLE-UNSUPPORTED"), P("under a playground slide", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the lunchroom door", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_031)", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 10, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "Noah crossed the old stone bridge with his uncle. Halfway across, they saw a loose board beside the railing. His uncle called the park office from his phone. A worker arrived and closed that side of the bridge.",
      prompt: "What did Noah and his uncle notice on the bridge?",
      choices: [K("one plank that was not secure"), P("a sleeping dog beside the path", "D-PLAUSIBLE-UNSUPPORTED"), P("a red backpack against the railing", "D-PLAUSIBLE-UNSUPPORTED"), P("a painted warning sign by the entrance", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p1_035)", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 11, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "The firefighters showed the class how they prepare for a call. First, they checked the oxygen tanks on the truck. Then one firefighter clipped a radio to her jacket. She explained that the radio helped the team hear directions.",
      prompt: "What did the firefighter clip to her jacket?",
      choices: [K("a two-way radio"), P("a laminated pass for the lunchroom", "D-PLAUSIBLE-UNSUPPORTED"), P("a silver badge used for classroom play", "D-PLAUSIBLE-UNSUPPORTED"), P("a folded visitor map from the zoo", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_036)", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 12, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "On the meadow walk, Chloe carried a small field guide. She saw yellow butterflies landing on purple flowers. Her partner counted five butterflies before they flew away. Chloe wrote the number beside a quick drawing in her guide.",
      prompt: "How many butterflies did Chloe's partner count?",
      choices: [K("five"), P("two", "D-PLAUSIBLE-UNSUPPORTED"), P("nine", "D-PLAUSIBLE-UNSUPPORTED"), P("twelve", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "Numeric detail extraction retention check.", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 13, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "Ethan waited at the station with his grandmother. Their train was late because workers were checking the track. A message on the screen said the train would arrive at ten thirty. Ethan read the time aloud so his grandmother could hear it.",
      prompt: "What time did the screen say the train would arrive?",
      choices: [K("ten thirty"), P("nine fifteen", "D-PLAUSIBLE-UNSUPPORTED"), P("eleven forty", "D-PLAUSIBLE-UNSUPPORTED"), P("eight o'clock", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "Time-detail extraction retention check.", retention: true },
    { u: "detail_across_sentences", lvl: 2, ph: 1, v: 14, fmt: "COMPREHENSION", cell: "detail_across_sentences", media: "text",
      passage: "The class cleaned the playground after the spring fair. Mateo found paper cups near the fence and plastic spoons under a table. He put the cups in the recycling bag. The spoons went into the trash bag because they were dirty.",
      prompt: "What did Mateo put in the recycling bag?",
      choices: [K("paper cups"), P("plastic spoons", "D-PLAUSIBLE-UNSUPPORTED"), P("muddy shoes", "D-PLAUSIBLE-UNSUPPORTED"), P("wooden blocks", "D-PLAUSIBLE-UNSUPPORTED")],
      note: "salvaged verbatim from highQualityComprehensionReplacements (hq_key_details_l2_p2_040)", retention: true },

    // ---- hand-written gap fills (L1 who x3, number_detail x4; precise x1) ----
    it("who", 1, 2, 6,
      "The class guinea pig needed a home during the school break. Four children offered. Miss Adu picked names from a cup, and the folded paper said 'Femi'. Femi carried the travel cage carefully to the car.",
      "Who took the guinea pig home?",
      [K("Femi"), P("Miss Adu","D-PLAUSIBLE-UNSUPPORTED"), P("the taxi driver","D-PLAUSIBLE-UNSUPPORTED"), P("the custodian","D-PLAUSIBLE-UNSUPPORTED")]),
    it("who", 1, 2, 7,
      "The whistle for the sack race was lost. Mr Pole checked his pockets twice. In the end, Sana lent him the spare whistle tied to her backpack, and the race began only one minute late.",
      "Who lent the whistle?",
      [K("Sana"), P("Mr Pole","D-PLAUSIBLE-UNSUPPORTED"), P("the winner","D-PLAUSIBLE-UNSUPPORTED"), P("a parent","D-PLAUSIBLE-UNSUPPORTED")]),
    it("who", 1, 2, 8,
      "On rainy Wednesdays, someone always mopped the puddle by the school door before the bell. Nobody knew who. One early morning, Priya spotted the mystery helper through the window: it was Bill, the bus driver, holding the mop.",
      "Who mopped the puddle?",
      [K("Bill the bus driver"), P("Priya","D-PLAUSIBLE-UNSUPPORTED"), P("the principal","D-PLAUSIBLE-UNSUPPORTED"), P("the custodian","D-PLAUSIBLE-UNSUPPORTED")]),
    it("number_detail", 1, 2, 5,
      "Grandma's shopping list was short: six eggs, two lemons, and one small bag of sugar. Tayo repeated it all the way to the store like a song. He came home with everything on the list and one free sticker.",
      "How many eggs were on the list?",
      [K("six"), P("two","D-SEQUENCE-SWAP"), P("one","D-SEQUENCE-SWAP"), P("ten","D-PLAUSIBLE-UNSUPPORTED")]),
    it("number_detail", 1, 2, 6,
      "The nature walk had a counting game. The class counted five snails on the wall, three white butterflies by the hedge, and one turtle crossing the path. The turtle reached the other side before they left.",
      "How many butterflies did the class count?",
      [K("three"), P("five","D-SEQUENCE-SWAP"), P("one","D-SEQUENCE-SWAP"), P("seven","D-PLAUSIBLE-UNSUPPORTED")]),
    it("number_detail", 1, 2, 7,
      "The bake sale opened at ten o'clock sharp. By 10:30 every oat bar was gone. The last brownie sold at eleven, when the principal bought it.",
      "When did the bake sale open?",
      [K("at ten o'clock"), P("at 10:30","D-SEQUENCE-SWAP"), P("at eleven","D-SEQUENCE-SWAP"), P("at lunchtime","D-PLAUSIBLE-UNSUPPORTED")]),
    it("number_detail", 1, 2, 8,
      "Nita's tower used every block in the box: twenty red ones for the bottom, ten blue ones for the middle, and four yellow ones balanced on top. It stood for one glorious minute before the cat inspected it.",
      "How many blue blocks were in the tower?",
      [K("ten"), P("twenty","D-SEQUENCE-SWAP"), P("four","D-SEQUENCE-SWAP"), P("forty","D-PLAUSIBLE-UNSUPPORTED")]),
    it("precise_detail", 2, 2, 8,
      "Two lunchboxes sat on the bench, nearly twins. Both were blue, both had a rocket sticker. But Cal's had a dent in one corner from the great playground drop, and Robi's still smelled faintly of yesterday's orange. Cal checked for the dent, took his box, and left the orange-smelling twin for Robi.",
      "How did Cal know which lunchbox was his?",
      [K("it had a dent in one corner"), P("it smelled of orange","D-OPPOSITE"), P("it had a rocket sticker","D-DETAIL-AS-MAIN"), P("it had his name on it","D-PLAUSIBLE-UNSUPPORTED")]),

    // ---- detail_across_sentences (L2, 8 new) ----
    it("detail_across_sentences", 2, 1, 1,
      "Ola filled the bird feeder with seeds at breakfast. At lunchtime the feeder was already half empty. By the end of the school day only dust was left, and one round pigeon sat on the fence.",
      "How long did the seeds last?",
      [K("from breakfast until the end of school"), P("exactly one hour","D-PLAUSIBLE-UNSUPPORTED"), P("a whole week","D-PLAUSIBLE-UNSUPPORTED"), P("until the next morning","D-SEQUENCE-SWAP")],
      "answer assembled from first and third sentences"),
    it("detail_across_sentences", 2, 1, 2,
      "The lost-and-found box held three items on Friday. Jun claimed the striped scarf at morning recess. The water bottle went home with Ivy after lunch. The dinosaur glove stayed unclaimed, so it remained in the box all weekend.",
      "Which treasure was still there on Saturday?",
      [K("the dinosaur glove"), P("the striped scarf","D-SEQUENCE-SWAP"), P("the water bottle","D-SEQUENCE-SWAP"), P("a wool hat","D-PLAUSIBLE-UNSUPPORTED")]),
    it("detail_across_sentences", 2, 1, 3,
      "Dad planted a tree when each child was born. Asha's cherry tree is the tallest now. Ben's apple tree gives the most fruit. The plum tree, the youngest, belongs to baby Mo — it is still shorter than the garden fence.",
      "Whose tree gives the most fruit?",
      [K("Ben's"), P("Asha's","D-SEQUENCE-SWAP"), P("baby Mo's","D-SEQUENCE-SWAP"), P("Dad's","D-PLAUSIBLE-UNSUPPORTED")]),
    it("detail_across_sentences", 2, 1, 4,
      "The school play needed props from three places. The crown came from Nell's costume box. The cardboard sword came from Raj's recycling pile. The throne was two chairs from the teachers' lounge, taped together and painted gold by the whole class.",
      "Where did the sword come from?",
      [K("Raj's recycling pile"), P("Nell's costume box","D-SEQUENCE-SWAP"), P("the teachers' lounge","D-SEQUENCE-SWAP"), P("the art store","D-PLAUSIBLE-UNSUPPORTED")]),
    it("detail_across_sentences", 2, 2, 5,
      "Monday's swimming lesson had three groups. Beginners stayed where they could stand. The middle group swam widths with a kickboard. The advanced group swam whole lengths without kickboards. Keya had been in the middle group since spring. On Monday she moved to the advanced group and handed her kickboard to a beginner.",
      "What is Keya allowed to do now?",
      [K("swim whole lengths without a kickboard"), P("swim widths with a kickboard","D-SEQUENCE-SWAP"), P("stay where she can stand","D-SEQUENCE-SWAP"), P("dive from the high board","D-PLAUSIBLE-UNSUPPORTED")],
      "needs the group rules AND her promotion"),
    it("detail_across_sentences", 2, 2, 6,
      "The twins sorted supplies after the school fair. Half the paper cups went into the classroom cabinet. They divided the remaining cups evenly between two art tables. At cleanup time, each art table had the same small stack ready for painting.",
      "Where did the remaining cups go?",
      [K("into equal stacks on two art tables"), P("all into one art table drawer","D-PLAUSIBLE-UNSUPPORTED"), P("back to the school fair","D-SEQUENCE-SWAP"), P("straight into the trash","D-OPPOSITE")],
      "integrates the storage sentence with the equal-table distribution sentence"),
    it("detail_across_sentences", 2, 2, 7,
      "The planter box schedule was strict: water on Mondays and Thursdays, add plant food on the first Monday of the month, and never water on a day when it had rained. This Thursday the sky poured all morning. Priya looked at the streaming glass, put the watering can back under the sink, and marked the chart anyway.",
      "Why did Priya skip the watering?",
      [K("rain days mean no watering, and it had rained"), P("Thursday was not a watering day","D-SEQUENCE-SWAP"), P("the can was lost","D-PLAUSIBLE-UNSUPPORTED"), P("it was a feeding day instead","D-SEQUENCE-SWAP")],
      "rule sentence + weather sentence must combine"),
    it("detail_across_sentences", 2, 2, 8,
      "Every bench in the park remembers somebody. The oak bench by the pond remembers Captain Reya. The curly iron bench remembers the twins' great-grandmother. And the newest bench, still smelling of paint, remembers Mr. Alam, who fed the sparrows here for forty years — which is why the carpenter cut a little seed dish into its arm.",
      "Which bench has a seed dish, and why?",
      [K("Mr. Alam's bench, to remember the birds he fed"), P("the oak bench, because of Captain Reya","D-SEQUENCE-SWAP"), P("the iron bench, because of the twins","D-SEQUENCE-SWAP"), P("no bench has one","D-OPPOSITE")]),

    // ---- which_is_not (L2, 8 new) ----
    it("which_is_not", 2, 1, 1,
      "The class aquarium got its spring cleaning on Friday. The gravel was rinsed in a strainer. The glass was wiped inside and out. The plastic castle came back shinier than ever, and the fish watched the whole operation from a bucket.",
      "Which of these is NOT in the story?",
      [K("the fish were given new food"), P("the gravel was rinsed","D-DETAIL-AS-MAIN"), P("the glass was wiped","D-DETAIL-AS-MAIN"), P("the fish waited in a bucket","D-DETAIL-AS-MAIN")],
      "the key is plausible but absent — verbatim matchers pick a true fact and miss"),
    it("which_is_not", 2, 1, 2,
      "Field day morning was all preparation. Lanes were painted white on the grass. Beanbags were counted into buckets. The finish tape was tied between two posts, and somebody tested the megaphone by saying 'pancakes' across the whole field.",
      "Which of these does the story NOT mention?",
      [K("medals were polished"), P("lanes were painted","D-DETAIL-AS-MAIN"), P("beanbags were counted","D-DETAIL-AS-MAIN"), P("the megaphone was tested","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 1, 3,
      "The night before the trip, Amir packed like an explorer. Raincoat, rolled tight. Sandwiches, wrapped and slightly squashed by the water bottle. Notebook and pencil, for bird spotting. His flashlight went in last, right at the top, in case of tunnels.",
      "Which item is NOT in Amir's bag?",
      [K("a camera"), P("a raincoat","D-DETAIL-AS-MAIN"), P("a notebook","D-DETAIL-AS-MAIN"), P("a flashlight","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 1, 4,
      "Grandpa's shed had a place for everything. Screwdrivers hung on hooks in size order. Clear jars of screws lined the window shelf. The lawn mower stayed under a cover, and the radio kept its place by the door, always tuned to music.",
      "Which of these is NOT described in the shed?",
      [K("a box of old paintbrushes"), P("screwdrivers on hooks","D-DETAIL-AS-MAIN"), P("jars of screws","D-DETAIL-AS-MAIN"), P("a radio by the door","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 2, 5,
      "The book fair filled the hall for one whole day. Tables sagged under picture books and joke books. A signing corner had an author with a fountain pen. Tokens from the summer reading club counted double, and the librarian wore a bright book-print dress.",
      "Which of these did NOT happen at the fair?",
      [K("a poetry competition was judged"), P("an author signed books","D-DETAIL-AS-MAIN"), P("reading tokens counted double","D-DETAIL-AS-MAIN"), P("the librarian wore her book dress","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 2, 6,
      "When the lights went out on the street, the neighbors made their own evening. Candles appeared in glass jars on doorsteps. Mr. Okoye carried his guitar outside and played requests. The food truck, which used its own gas, kept serving meals.",
      "Which of these is NOT part of the story?",
      [K("a bonfire was lit in the road"), P("candles stood in glass jars","D-DETAIL-AS-MAIN"), P("a guitar played requests","D-DETAIL-AS-MAIN"), P("the food truck kept serving","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 2, 7,
      "The museum's new dinosaur room opened with three rules on the door. Walk, don't run, because the floor was very smooth. Whisper, because sound bounced off the bones. Photos were welcome — but only without the flash, which could harm the painted copy of a cave wall.",
      "Which rule is NOT on the door?",
      [K("no eating or drinking"), P("walk, don't run","D-DETAIL-AS-MAIN"), P("whisper","D-DETAIL-AS-MAIN"), P("no flash photos","D-DETAIL-AS-MAIN")]),
    it("which_is_not", 2, 2, 8,
      "Harvest week at the community garden brought jobs for everyone. The tall cousins picked the green beans. The small cousins dug potatoes with trowels, cheering at every find. Grandma weighed everything on her kitchen scale, and the biggest pumpkin rode home in the wheelbarrow.",
      "Which of these is NOT in the story?",
      [K("carrots were pulled and washed"), P("beans were picked","D-DETAIL-AS-MAIN"), P("potatoes were dug up","D-DETAIL-AS-MAIN"), P("the pumpkin rode in the wheelbarrow","D-DETAIL-AS-MAIN")]),

    // ---- retention gap fills (4 new) ----
    it("who", 1, 1, 12,
      "The classroom plants drooped over the break. On the first day back, the principal read a note beside the damp soil. Gita smiled and admitted that she had watered them.",
      "Who watered the plants?",
      [K("Gita"), P("the principal","D-PLAUSIBLE-UNSUPPORTED"), P("the rain","D-PLAUSIBLE-UNSUPPORTED"), P("nobody","D-OPPOSITE")], "", { retention: true }),
    it("number_detail", 1, 1, 12,
      "The ferry to the island takes twenty minutes. The bus from the harbor takes ten more. Door to door, Grandma's trip is half an hour, followed by an afternoon visit.",
      "How long does the ferry take?",
      [K("twenty minutes"), P("ten minutes","D-SEQUENCE-SWAP"), P("half an hour","D-SEQUENCE-SWAP"), P("an afternoon","D-SEQUENCE-SWAP")], "", { retention: true }),
    it("which_is_not", 2, 1, 9,
      "The yard sale table was carefully arranged. Board games with all their pieces were checked twice. A shoebox held dinosaur figures. The outgrown rain boots stood in a row, smallest to biggest, and the toy cash register was ready for sales.",
      "Which of these was NOT on the table?",
      [K("a basket of picture books"), P("board games","D-DETAIL-AS-MAIN"), P("dinosaur figures","D-DETAIL-AS-MAIN"), P("outgrown rain boots","D-DETAIL-AS-MAIN")], "", { retention: true }),
    it("detail_across_sentences", 2, 1, 15,
      "The relay team ran in a fixed order. Jaya started, because her starts were lightning. Ben ran second and Priw third, keeping the pace steady. The last leg belonged to Omar. He was not the fastest starter, but once he was in front, nobody ever caught him.",
      "Why did Omar run last?",
      [K("no one could catch him from in front"), P("his starts were lightning","D-SEQUENCE-SWAP"), P("he kept the pace steady","D-SEQUENCE-SWAP"), P("he was the captain","D-PLAUSIBLE-UNSUPPORTED")], "", { retention: true }),
  ].map(item => ({
    ...item,
    choices: item.choices.map(choice => (
      choice.k && PARAPHRASED_LITERAL_KEYS.has(choice.t)
        ? { ...choice, t: PARAPHRASED_LITERAL_KEYS.get(choice.t) }
        : choice
    ))
  }))
};
