// Main Idea — v3 authored bank (wave W1). Every passage written one at a time,
// single-use, its own topic. Distractor law (BLUEPRINTS_COMPREHENSION §26):
// one true detail posing as the main idea, one topic-word overreach, one
// contradicted/unrelated. The key never copies the passage's most-repeated
// content word unless a distractor does too — the detail distractor always
// quotes MORE of the passage than the key, so surface-matching picks wrong.
//
// Topic registry (unique across this skill): beans, recycling, crossing guard,
// bees, library book, squeaky bike, storm at recess, dumplings, tadpoles,
// beach bag, class fish, kite, autumn leaves, wobbly tooth, bakery, lighthouse,
// snow shoveling, fence painting, ants, zipper, market, shadows, tidy-up race,
// stray kitten, lemonade, puddles, seeds on wind, night bus, museum bones,
// campfire, spider web, post office, otters, laundry line, moon phases, choir,
// bridge repair, garden worms, ferry, thunder counting, sandwich swap, magnets,
// tide pool crabs, hair cut, treehouse rules, compost, fog morning, drum
// practice, paper planes, new glasses, bird nest, escalator, pancake flip,
// firefly jar, garden plot, rain gauge, lost mitten, street mural, seed bank,
// bike bell, quiet corner, tooth chart, robot vacuum, swimming badge.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, prompt, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage, prompt, choices, media: "text", ...extra
});
const Q1 = "What is this story mostly about?";
const QI = "What is this passage mostly about?";

export default {
  skillId: "main_idea",
  skillName: "Main Idea",
  items: [
    // ================= LEVEL 1 · mostly_about_fiction (8) =================
    it("mostly_about_fiction", 1, 1, 1,
      "Rana planted three bean seeds in a paper cup. She watered them every morning before school. For days, nothing happened. Then one green stem pushed up through the soil. Rana cheered so loudly that her dog barked.",
      Q1,
      [K("waiting for a seed to grow"),
       P("a dog that barked", "D-DETAIL-AS-MAIN"),
       P("everything about paper cups", "D-TOPIC-ADJACENT"),
       P("a girl who hates plants", "D-OPPOSITE")]),
    it("mostly_about_fiction", 1, 1, 2,
      "Tom could not find his library book anywhere. He looked under his bed and behind the sofa. He even checked the fridge. At last he found it inside his pillowcase, right where he had read it last night.",
      Q1,
      [K("searching everywhere for a lost book"),
       P("looking inside the fridge", "D-DETAIL-AS-MAIN"),
       P("how libraries lend books", "D-TOPIC-ADJACENT"),
       P("a boy who loves tidying", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("mostly_about_fiction", 1, 1, 3,
      "Amara's bike squeaked all the way to the park. Squeak, squeak, squeak. Her uncle showed her how to drip oil on the chain. On the ride home, the bike rolled along quietly, and Amara grinned the whole way.",
      Q1,
      [K("fixing a noisy bike"),
       P("a ride to the park", "D-DETAIL-AS-MAIN"),
       P("all the parts of a bicycle", "D-TOPIC-ADJACENT"),
       P("a broken bike nobody fixed", "D-OPPOSITE")]),
    it("mostly_about_fiction", 1, 1, 4,
      "Milo's tooth had wobbled for a week. He wiggled it at breakfast and at bath time. Then, while he was laughing at dinner, it popped out into his hand. Milo put it under his pillow that night.",
      Q1,
      [K("a wobbly tooth finally coming out"),
       P("laughing at dinner", "D-DETAIL-AS-MAIN"),
       P("how to brush your teeth", "D-TOPIC-ADJACENT"),
       P("a boy scared of the dentist", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("mostly_about_fiction", 1, 2, 5,
      "A thin gray kitten kept visiting Priya's steps. Each day Priya set out a little dish of water. Each day the kitten crept closer. On Friday it finally curled up on her lap, purring like a tiny engine.",
      Q1,
      [K("slowly making friends with a kitten"),
       P("a dish of water on the steps", "D-DETAIL-AS-MAIN"),
       P("how to look after every pet", "D-TOPIC-ADJACENT"),
       P("a kitten that ran away forever", "D-OPPOSITE")]),
    it("mostly_about_fiction", 1, 2, 6,
      "Dev dropped his mitten somewhere in the snow. He walked back along his own footprints to look. Near the gate he saw a flash of red on the fence post. Someone had found his mitten and left it where he would see it.",
      Q1,
      [K("finding a lost mitten"),
       P("footprints in the snow", "D-DETAIL-AS-MAIN"),
       P("all kinds of winter clothes", "D-TOPIC-ADJACENT"),
       P("a boy who lost his hat", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("mostly_about_fiction", 1, 2, 7,
      "The choir had one last practice before the show. First the singing was too quiet. Then it was too fast. Miss Obi clapped a steady beat, and slowly all the voices came together like one big voice.",
      Q1,
      [K("a choir learning to sing together"),
       P("Miss Obi clapping a beat", "D-DETAIL-AS-MAIN"),
       P("every kind of music", "D-TOPIC-ADJACENT"),
       P("a show that was canceled", "D-OPPOSITE")]),
    it("mostly_about_fiction", 1, 2, 8,
      "Jin practiced flipping pancakes with a cold, empty pan. Flip, catch. Flip, catch. On Sunday he tried it with a real pancake while his dad watched. The pancake spun in the air and landed back in the pan.",
      Q1,
      [K("practicing until a pancake flip works"),
       P("a dad watching on Sunday", "D-DETAIL-AS-MAIN"),
       P("what people eat for breakfast", "D-TOPIC-ADJACENT"),
       P("a pancake that fell on the floor", "D-OPPOSITE")]),

    // ================= LEVEL 1 · mostly_about_info (8) =================
    it("mostly_about_info", 1, 1, 1,
      "Bees visit many flowers on one trip. They drink a sweet juice called nectar. Back at the hive, they pass the nectar to other bees. Slowly the nectar thickens into honey. One jar of honey takes thousands of flower visits.",
      QI,
      [K("how bees turn nectar into honey"),
       P("a sweet juice called nectar", "D-DETAIL-AS-MAIN"),
       P("every insect in the garden", "D-TOPIC-ADJACENT"),
       P("why bees never leave the hive", "D-OPPOSITE")]),
    it("mostly_about_info", 1, 1, 2,
      "A tadpole does not look like a frog. It has a tail and no legs. First the back legs grow. Then the front legs appear, and the tail gets shorter. At last the little frog can hop out of the pond.",
      QI,
      [K("how a tadpole becomes a frog"),
       P("back legs growing first", "D-DETAIL-AS-MAIN"),
       P("animals that live in ponds", "D-TOPIC-ADJACENT"),
       P("how frogs build nests", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("mostly_about_info", 1, 1, 3,
      "Old paper does not have to be trash. Trucks take it to a special factory. There it is mashed with water into a gray pulp. The pulp is rolled flat and dried. It comes out as fresh, clean paper, ready to use again.",
      QI,
      [K("how old paper is made new again"),
       P("a gray pulp of paper and water", "D-DETAIL-AS-MAIN"),
       P("everything factories can make", "D-TOPIC-ADJACENT"),
       P("why paper must be thrown away", "D-OPPOSITE")]),
    it("mostly_about_info", 1, 1, 4,
      "A lighthouse stands where the rocks are dangerous. At night its big lamp turns round and round. Ships far out at sea watch for the flashing light. The light tells them where the rocks are, so they can steer safely past.",
      QI,
      [K("how a lighthouse keeps ships safe"),
       P("a big lamp that turns", "D-DETAIL-AS-MAIN"),
       P("different kinds of tall buildings", "D-TOPIC-ADJACENT"),
       P("ships that sail only in the day", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("mostly_about_info", 1, 2, 5,
      "An ant is small, but it is a strong helper. Ants work in long lines. One ant finds a crumb and leaves a smell trail. The others follow the trail. Together they carry food back to the nest, piece by piece.",
      QI,
      [K("how ants work together to gather food"),
       P("one ant finds a crumb and leaves a trail", "D-DETAIL-AS-MAIN"),
       P("all the tiny animals in the world", "D-TOPIC-ADJACENT"),
       P("ants that live all alone", "D-OPPOSITE")]),
    it("mostly_about_info", 1, 2, 6,
      "Shadows are not the same all day. In the morning, the sun is low and shadows are long. At midday, the sun is high and shadows shrink small. In the evening they stretch long again, pointing the other way.",
      QI,
      [K("how shadows change through the day"),
       P("small shadows at midday", "D-DETAIL-AS-MAIN"),
       P("why the sky is blue", "D-TOPIC-ADJACENT"),
       P("shadows that never move", "D-OPPOSITE")]),
    it("mostly_about_info", 1, 2, 7,
      "A spider web starts with one thin thread. The spider lets the wind carry it across a gap. Then she walks the thread and adds more lines, round and round. The finished web is sticky, ready to catch her dinner.",
      QI,
      [K("how a spider builds its web"),
       P("wind carrying one thread", "D-DETAIL-AS-MAIN"),
       P("every animal that makes a home", "D-TOPIC-ADJACENT"),
       P("a spider that hates webs", "D-OPPOSITE")]),
    it("mostly_about_info", 1, 2, 8,
      "The moon seems to change shape, but it does not really. The moon circles the Earth. Sunlight lights up one side of it. Some nights we see all of the bright side, some nights only a sliver. That is why the moon looks different.",
      QI,
      [K("why the moon looks different each night"),
       P("seeing only a sliver of the bright side", "D-DETAIL-AS-MAIN"),
       P("all the stars in space", "D-TOPIC-ADJACENT"),
       P("how astronauts fly to the moon", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ================= LEVEL 1 · mostly_about_everyday (8) =================
    it("mostly_about_everyday", 1, 1, 1,
      "Every morning Mr Pole stands at the school crossing. He holds up his round sign, and the cars stop. He waves the children across, grinning his good-morning grin. Rain or shine, he is there before the first bell rings.",
      QI,
      [K("a crossing guard helping children every day"),
       P("a round sign held up to stop the cars", "D-DETAIL-AS-MAIN"),
       P("all the jobs grown-ups do", "D-TOPIC-ADJACENT"),
       P("children who cross alone", "D-OPPOSITE")]),
    it("mostly_about_everyday", 1, 1, 2,
      "A second-grade class had a cleanup race before going home. One team stacked the chairs. Another team collected the pencils. The last team wiped the tables. In five minutes the whole room was neat, and everyone won a sticker.",
      QI,
      [K("a class tidying their room together"),
       P("one team stacking chairs", "D-DETAIL-AS-MAIN"),
       P("every rule at school", "D-TOPIC-ADJACENT"),
       P("a room that stayed messy", "D-OPPOSITE")]),
    it("mostly_about_everyday", 1, 1, 3,
      "Saturday is market day. Grandma gives Ade the shopping list. He finds the oranges, and Grandma picks the fish. The vendor always adds one free plum for Ade. They walk home with heavy bags and happy plans for dinner.",
      QI,
      [K("a Saturday trip to buy food with Grandma"),
       P("one free plum from the vendor", "D-DETAIL-AS-MAIN"),
       P("how all shops sell food", "D-TOPIC-ADJACENT"),
       P("a boy who stayed at home", "D-OPPOSITE")]),
    it("mostly_about_everyday", 1, 1, 4,
      "The laundromat on our street hums all morning. Round windows spin with socks and shirts. Mrs. Kaur folds warm towels into tall piles. People chat while they wait, and the whole shop smells like clean cotton.",
      QI,
      [K("a busy morning at the laundromat"),
       P("towels folded into tall piles", "D-DETAIL-AS-MAIN"),
       P("every shop on the street", "D-TOPIC-ADJACENT"),
       P("clothes nobody ever washes", "D-OPPOSITE")]),
    it("mostly_about_everyday", 1, 2, 5,
      "After the rain, the playground was full of puddles. Small boots splashed in the big one by the slide. Two friends raced leaf boats along the gutter stream. By lunch, the sun had drunk the puddles all up.",
      QI,
      [K("playing outside after the rain"),
       P("leaf boats in the gutter", "D-DETAIL-AS-MAIN"),
       P("why weather changes", "D-TOPIC-ADJACENT"),
       P("children stuck indoors all day", "D-OPPOSITE")]),
    it("mostly_about_everyday", 1, 2, 6,
      "Dad flips the calendar to a new month. Everyone adds their days. Swimming badge test for Lena. Dentist for Dad. Grandma's visit gets a big red circle. The little squares fill up with the family's plans.",
      QI,
      [K("a family filling in their calendar"),
       P("a big red circle for Grandma", "D-DETAIL-AS-MAIN"),
       P("how to count all the months", "D-TOPIC-ADJACENT"),
       P("a family with nothing to do", "D-OPPOSITE")]),
    it("mostly_about_everyday", 1, 2, 7,
      "The mail carrier's cart squeaks up our road at nine. Letters slide through mail slots, flap, flap, flap. Number 12 gets a package and signs for it happily. Our dog waits by the mail slot every single morning.",
      QI,
      [K("the post arriving on our road"),
       P("a package for number 12", "D-DETAIL-AS-MAIN"),
       P("how dogs guard houses", "D-TOPIC-ADJACENT"),
       P("a road that gets no letters", "D-OPPOSITE")]),
    it("mostly_about_everyday", 1, 2, 8,
      "The bakery opens before the sun is up. Trays of rolls slide into the big oven. The smell of warm bread drifts down the street. By eight o'clock a little line waits at the door, sniffing happily.",
      QI,
      [K("a bakery starting its morning"),
       P("a line at eight o'clock", "D-DETAIL-AS-MAIN"),
       P("every food people like", "D-TOPIC-ADJACENT"),
       P("a shop that never opens", "D-OPPOSITE")]),

    // ================= LEVEL 2 · best_title (8) =================
    it("best_title", 2, 1, 1,
      "Nobody wanted the muddy corner of the school garden. Weeds grew tall, and snack wrappers blew against the fence. Then a second-grade class claimed it. They pulled the weeds, dug in compost, and planted sunflower seeds in careful rows. All summer the corner blazed yellow, and even the custodian stopped to take photographs.",
      "Which title fits this passage best?",
      [K("The Corner Nobody Wanted"),
       P("Snack Wrappers by the Fence", "D-DETAIL-AS-MAIN"),
       P("A Guide to Every Garden Flower", "D-TOPIC-ADJACENT"),
       P("The Year the Garden Failed", "D-OPPOSITE")]),
    it("best_title", 2, 1, 2,
      "When the old footbridge closed for repairs, everyone grumbled. The walk to school took ten minutes longer, right around the stream. But on the long way, children found blackberries, a heron, and a hollow tree that echoed. By the time the bridge reopened, some families kept taking the long way on purpose.",
      "Which title fits this passage best?",
      [K("The Long Way Round"),
       P("Fixing the Old Footbridge", "D-DETAIL-AS-MAIN"),
       P("All About Herons", "D-TOPIC-ADJACENT"),
       P("The Shortest Path to School", "D-OPPOSITE")]),
    it("best_title", 2, 1, 3,
      "Asha's drum kit lived in the garage, because drums are loud. Every evening she practiced the same tricky rhythm, and every evening it fell apart in the middle. Her mom suggested slowing right down. Boring, thought Asha, but she tried it. Two slow weeks later, her sticks flew through the rhythm at full speed without a single slip.",
      "Which title fits this passage best?",
      [K("Slow First, Fast Later"),
       P("A Drum Kit in the Garage", "D-DETAIL-AS-MAIN"),
       P("Famous Drummers of the World", "D-TOPIC-ADJACENT"),
       P("The Girl Who Gave Up Music", "D-OPPOSITE")]),
    it("best_title", 2, 1, 4,
      "The city aquarium had a problem: the otters kept escaping their pool at night and sliding down the corridors. Cameras showed them stacking rocks by the glass wall like little stairs. The keepers did not punish the clever climbers. Instead they built a bigger pool with waterfalls, tunnels, and plenty of rocks to move around.",
      "Which title fits this passage best?",
      [K("The Otters Who Outsmarted the Aquarium"),
       P("Cameras by the Glass Wall", "D-DETAIL-AS-MAIN"),
       P("How to Visit a City Aquarium", "D-TOPIC-ADJACENT"),
       P("The Otters Who Never Moved", "D-OPPOSITE")]),
    it("best_title", 2, 2, 5,
      "Grandpa folds a square of paper in silence. Corner to corner, crease by crease. Suddenly it has wings. He taught this plane to Dad thirty years ago, and today he is teaching it to me. Mine flies crooked, then straight, then right across the kitchen. Grandpa says the fold matters more than the throw.",
      "Which title fits this passage best?",
      [K("A Paper Plane Passed Down"),
       P("A Flight Across the Kitchen", "D-DETAIL-AS-MAIN"),
       P("The History of Real Airplanes", "D-TOPIC-ADJACENT"),
       P("The Plane That Would Not Fly", "D-OPPOSITE")]),
    it("best_title", 2, 2, 6,
      "At first the new rain gauge seemed dull. A plastic tube, a ruler, an empty chart. But day by day the chart filled in. A dry week made a flat line. A stormy Tuesday shot the line up like a mountain. By the end of the term, a third-grade class could read their whole spring in one zigzag picture.",
      "Which title fits this passage best?",
      [K("Our Spring, Drawn in Rain"),
       P("A Plastic Tube and a Ruler", "D-DETAIL-AS-MAIN"),
       P("Why Storms Happen", "D-TOPIC-ADJACENT"),
       P("The Chart Nobody Filled In", "D-OPPOSITE")]),
    it("best_title", 2, 2, 7,
      "The escalator at the station broke on Monday, and a sign said SORRY. Some people sighed and took the stairs. A busker moved to the bottom step and played cheerful songs for the climbers. Strangers started counting the steps out loud together, laughing when they lost count. It was, everyone agreed, a strangely happy week.",
      "Which title fits this passage best?",
      [K("The Week the Escalator Broke"),
       P("The Sign That Said Sorry All Week", "D-DETAIL-AS-MAIN"),
       P("How Train Stations Are Built", "D-TOPIC-ADJACENT"),
       P("The Week the Busker Stayed Home", "D-OPPOSITE")]),
    it("best_title", 2, 2, 8,
      "Every seed in the seed bank sleeps in a silver packet. Wheat from one valley, beans from another, a pumpkin seed saved from a hundred years ago. If a flood or a fire ever destroys a crop, farmers can borrow its seeds and start again. The freezer hums quietly, keeping tomorrow's fields safe on its cold shelves.",
      "Which title fits this passage best?",
      [K("A Bank That Saves Tomorrow's Fields"),
       P("A Pumpkin Seed from Long Ago", "D-DETAIL-AS-MAIN"),
       P("How to Cook with Beans", "D-TOPIC-ADJACENT"),
       P("The Bank That Lost Its Seeds", "D-OPPOSITE")]),

    // ================= LEVEL 2 · main_idea_vs_detail (8) =================
    it("main_idea_vs_detail", 2, 1, 1,
      "The class made soup for the winter fair. Priya chopped carrots into little moons. Sam stirred so the bottom would not stick. Miss Lee added one secret spoonful of ginger. When the pot finally bubbled, the whole corridor smelled wonderful, and the soup sold out in twenty minutes.",
      "Which option best states the main idea?",
      [K("the class made soup that everyone loved"),
       P("carrots were cut into little moons", "D-DETAIL-AS-MAIN"),
       P("Miss Lee added some ginger", "D-DETAIL-AS-MAIN"),
       P("Sam stirred the pot", "D-DETAIL-AS-MAIN")],
      { note: "three true details vs the point — the defining discrimination of this cell" }),
    it("main_idea_vs_detail", 2, 1, 2,
      "Hedgehogs need help in autumn. They look for a safe pile of leaves to sleep in all winter. People can leave a wild corner in the garden and check bonfires before lighting them. A small gap in the fence lets hedgehogs walk from garden to garden to find food.",
      "Which option best states the main idea?",
      [K("people can make gardens safer for hedgehogs"),
       P("hedgehogs sleep in piles of leaves", "D-DETAIL-AS-MAIN"),
       P("a gap in a fence helps hedgehogs walk through", "D-DETAIL-AS-MAIN"),
       P("bonfires should be checked", "D-DETAIL-AS-MAIN")]),
    it("main_idea_vs_detail", 2, 1, 3,
      "Maya kept a moon diary for a month. On clear nights she drew the moon's shape in silver pencil. On cloudy nights she wrote 'hidden' in the box. Slowly her pages showed the moon growing round, then shrinking thin. Her diary turned a whole month of sky into one small story.",
      "Which option best states the main idea?",
      [K("Maya's diary recorded how the moon changed"),
       P("she drew with a silver pencil", "D-DETAIL-AS-MAIN"),
       P("some nights she wrote 'hidden'", "D-DETAIL-AS-MAIN"),
       P("she kept the diary for a month", "D-DETAIL-AS-MAIN")]),
    it("main_idea_vs_detail", 2, 1, 4,
      "The old phone box on Elm Street does not hold a phone any more. The town filled it with books instead. Anyone may take one home, as long as they leave another. The shelves change every week: cookbooks, comics, mysteries. The little red box is now the smallest library in town.",
      "Which option best states the main idea?",
      [K("the phone box became a tiny library"),
       P("the box is red", "D-DETAIL-AS-MAIN"),
       P("the shelves change every week", "D-DETAIL-AS-MAIN"),
       P("people leave a book when they take one", "D-DETAIL-AS-MAIN")]),
    it("main_idea_vs_detail", 2, 2, 5,
      "Dad's garden plot gives us vegetables nearly all year. In spring we pull sweet little radishes. Summer brings beans that climb higher than me. In autumn we dig up potatoes like buried treasure. Even in winter there is kale, standing green in the frost.",
      "Which option best states the main idea?",
      [K("the garden plot grows food in every season"),
       P("beans climb very high", "D-DETAIL-AS-MAIN"),
       P("potatoes are dug in autumn", "D-DETAIL-AS-MAIN"),
       P("kale stands in the frost", "D-DETAIL-AS-MAIN")]),
    it("main_idea_vs_detail", 2, 2, 6,
      "The fire station opened its doors on Saturday. Children tried on helmets that wobbled on their heads. A firefighter showed how the long ladder unfolds to reach high windows. Everyone got to spray the practice hose at a target. By home time, half the visitors wanted the job one day.",
      "Which option best states the main idea?",
      [K("a day of visitors trying out the station"),
       P("the helmets wobbled", "D-DETAIL-AS-MAIN"),
       P("the long ladder unfolds to reach high windows", "D-DETAIL-AS-MAIN"),
       P("children sprayed a practice hose", "D-DETAIL-AS-MAIN")]),
    it("main_idea_vs_detail", 2, 2, 7,
      "A wind farm stands on the hill above our town. Each turbine is taller than the church tower. When the blades spin, they turn wind into electricity for hundreds of homes. On still days the blades rest, and on wild days they whirl like giant white pinwheels.",
      "Which option best states the main idea?",
      [K("the wind farm makes electricity from wind"),
       P("turbines are taller than the church", "D-DETAIL-AS-MAIN"),
       P("blades rest on still days", "D-DETAIL-AS-MAIN"),
       P("the blades look like pinwheels", "D-DETAIL-AS-MAIN")]),
    it("main_idea_vs_detail", 2, 2, 8,
      "Our street planned a surprise for Mr. Chen's hundredth birthday. Neighbors strung flags from lamp post to lamp post. The cafe baked a cake with exactly one hundred candles, which took three tries to light. Children painted a banner as long as a bus. When Mr. Chen stepped outside, the whole street sang at once.",
      "Which option best states the main idea?",
      [K("the street celebrated Mr. Chen's birthday together"),
       P("the cake had one hundred candles", "D-DETAIL-AS-MAIN"),
       P("the banner was as long as a bus", "D-DETAIL-AS-MAIN"),
       P("flags were strung from lamp post to lamp post", "D-DETAIL-AS-MAIN")]),

    // ================= LEVEL 2 · summary_choice (8) =================
    it("summary_choice", 2, 1, 1,
      "Leo wanted to swim the whole length of the pool. At first he could only manage halfway before standing up, coughing. His coach gave him one tip each week: slower arms, bubbles out, long legs. Six Saturdays later, Leo touched the far wall for the first time and burst up grinning.",
      "Which sentence sums up the whole passage best?",
      [K("Weekly tips and practice carried Leo to a full length at last."),
       P("At first Leo stood up coughing halfway down the pool.", "D-DETAIL-AS-MAIN"),
       P("Swimming pools hold lessons every Saturday.", "D-TOPIC-ADJACENT"),
       P("Leo decided swimming was not for him.", "D-OPPOSITE")]),
    it("summary_choice", 2, 1, 2,
      "The museum's dinosaur skeleton arrived in ninety-two boxes. For a month, visitors watched scientists fit bone to bone behind a glass wall. A neck as long as a slide rose slowly toward the ceiling. When the last tail bone clicked into place, the hall finally looked the way it did in the posters.",
      "Which sentence sums up the whole passage best?",
      [K("Scientists rebuilt a huge dinosaur skeleton while visitors watched."),
       P("The skeleton arrived in ninety-two boxes.", "D-DETAIL-AS-MAIN"),
       P("Museums keep many kinds of old things.", "D-TOPIC-ADJACENT"),
       P("The dinosaur could never be put together.", "D-OPPOSITE")]),
    it("summary_choice", 2, 1, 3,
      "When the power went out, the apartment went quiet and dark. Mom found candles, and we ate supper by their small light. With no screens, Grandma taught us a clapping game from when she was small. The lights blinked on at bedtime, but we asked to keep one candle burning anyway.",
      "Which sentence sums up the whole passage best?",
      [K("A power outage turned into a cozy evening of old games."),
       P("Mom found some candles.", "D-DETAIL-AS-MAIN"),
       P("Electricity comes into homes through wires.", "D-TOPIC-ADJACENT"),
       P("The family sat bored until the lights returned.", "D-OPPOSITE")]),
    it("summary_choice", 2, 1, 4,
      "The tide pool looked empty at first. Then Nadia crouched still and waited. A crab sidled out from under a stone. A blob on the rock turned out to be an anemone, waving tiny arms. The longer she stayed still, the more the pool came alive around her.",
      "Which sentence sums up the whole passage best?",
      [K("By waiting quietly, Nadia discovered the tide pool was full of life."),
       P("A crab came out from under a stone.", "D-DETAIL-AS-MAIN"),
       P("The seaside has sand, rocks and waves.", "D-TOPIC-ADJACENT"),
       P("Nadia found nothing in the empty pool.", "D-OPPOSITE")]),
    it("summary_choice", 2, 2, 5,
      "Robots vacuum some homes now, but they need help to do it well. Cables must be lifted off the floor, or the robot eats them. Chairs become fences that trap it in corners. One sock can end the whole clean. Tidy first, the instructions say, and the robot will do the rest.",
      "Which sentence sums up the whole passage best?",
      [K("A robot cleans well only in a home tidied for it first."),
       P("A sock can stop a robot vacuum.", "D-DETAIL-AS-MAIN"),
       P("Machines do many jobs in houses.", "D-TOPIC-ADJACENT"),
       P("Robot vacuums work best in messy rooms.", "D-OPPOSITE")]),
    it("summary_choice", 2, 2, 6,
      "The ferry crosses the bay eight times a day. Islanders set their clocks by its horn. It carries schoolchildren in the morning, shopping crates at noon, and tired workers at dusk. In storms it stays tied to the dock, and the whole island seems to hold its breath until it sails again.",
      "Which sentence sums up the whole passage best?",
      [K("The island's daily life moves to the rhythm of its ferry."),
       P("The ferry carries crates at noon.", "D-DETAIL-AS-MAIN"),
       P("Boats come in many shapes and sizes.", "D-TOPIC-ADJACENT"),
       P("The islanders ignore the ferry completely.", "D-OPPOSITE")]),
    it("summary_choice", 2, 2, 7,
      "Amir's baby sister cried every time he practiced trumpet. He tried playing in the yard, but the neighbors leaned out of windows. He tried the bathroom, where the echo was wonderful but the space was not. In the end, the closet full of winter coats muffled the sound, and everyone was happy.",
      "Which sentence sums up the whole passage best?",
      [K("Amir searched the apartment until he found a good place to practice."),
       P("The bathroom had a wonderful echo.", "D-DETAIL-AS-MAIN"),
       P("Trumpets are brass instruments.", "D-TOPIC-ADJACENT"),
       P("Amir gave his trumpet away.", "D-OPPOSITE")]),
    it("summary_choice", 2, 2, 8,
      "The street mural began as one painted door. The artist added a whale above it the next week, then waves along three more houses. Neighbors started leaving paint cans by their walls as an invitation. By summer, the gray street had become a sea scene that visitors crossed town to photograph.",
      "Which sentence sums up the whole passage best?",
      [K("One painted door slowly grew into a whole street of art."),
       P("A whale was painted above a door.", "D-DETAIL-AS-MAIN"),
       P("Artists use many colors of paint.", "D-TOPIC-ADJACENT"),
       P("The street stayed gray and plain.", "D-OPPOSITE")]),

    // ================= RETENTION RESERVE (form R: 8 L1-style + 8 L2-style) ==
    it("mostly_about_fiction", 1, 1, 9,
      "Bo built a tower of blocks taller than the table. His baby brother reached out one finger. Crash! Blocks rolled everywhere. Bo took a big breath. Then he handed his brother two blocks and they started a new tower together.",
      Q1,
      [K("starting again after a tower falls"),
       P("blocks rolling everywhere", "D-DETAIL-AS-MAIN"),
       P("how to build real houses", "D-TOPIC-ADJACENT"),
       P("a brother sent out of the room", "D-OPPOSITE")], { retention: true }),
    it("mostly_about_fiction", 1, 1, 10,
      "Nia's kite would not fly. It flopped on the grass like a tired fish. Grandpa tied on a longer tail made from his old scarf. The next gust lifted the kite high over the hill, and Nia ran laughing beneath it.",
      Q1,
      [K("getting a kite to fly at last"),
       P("a tail made from a scarf", "D-DETAIL-AS-MAIN"),
       P("all the things wind can do", "D-TOPIC-ADJACENT"),
       P("a kite lost in a tree", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("mostly_about_info", 1, 1, 9,
      "A magnet does not pull everything. It grabs paper clips, keys, and the fridge door. It ignores plastic bricks, wooden spoons, and glass marbles. Magnets only pull some metals. That is why one side of your toy sticks and the other side slides off.",
      QI,
      [K("what magnets do and do not pull"),
       P("a magnet grabbing paper clips", "D-DETAIL-AS-MAIN"),
       P("every toy in the toy box", "D-TOPIC-ADJACENT"),
       P("magnets that pull everything", "D-OPPOSITE")], { retention: true }),
    it("mostly_about_info", 1, 2, 10,
      "Compost turns old scraps into new soil. Peelings, leaves, and eggshells go into the bin. Tiny creatures chew them up for months. Slowly the scraps turn dark and crumbly. Gardeners spread this new soil to feed their plants.",
      QI,
      [K("how scraps become soil for plants"),
       P("eggshells going into the bin", "D-DETAIL-AS-MAIN"),
       P("all the creatures in a garden", "D-TOPIC-ADJACENT"),
       P("why scraps must go to the tip", "D-OPPOSITE")], { retention: true }),
    it("mostly_about_everyday", 1, 1, 9,
      "The dentist's waiting room has a fish tank and a box of old comics. Ben watches the striped fish glide while Mom reads. A buzzer sounds, a nurse smiles around the door, and it is Ben's turn to hop into the big moving chair.",
      QI,
      [K("waiting for a turn at the dentist"),
       P("a tank with striped fish", "D-DETAIL-AS-MAIN"),
       P("how teeth grow", "D-TOPIC-ADJACENT"),
       P("a boy who ran out of the door", "D-OPPOSITE")], { retention: true }),
    it("mostly_about_everyday", 1, 2, 10,
      "On Sunday the whole apartment smells of coconut rice. Auntie stirs the big silver pot. Cousins squeeze around the small table, elbow to elbow. There is always one more chair, one more plate, one more story before the food is gone.",
      QI,
      [K("a family crowding together for Sunday dinner"),
       P("a big silver pot", "D-DETAIL-AS-MAIN"),
       P("recipes from around the world", "D-TOPIC-ADJACENT"),
       P("a quiet dinner eaten alone", "D-OPPOSITE")], { retention: true }),
    it("mostly_about_fiction", 1, 2, 11,
      "The classroom hamster escaped on Friday. All weekend he was loose in the school. On Monday the children followed a trail of seed shells past the library. They found him asleep in the lost-and-found box, curled inside a wool hat.",
      Q1,
      [K("tracking down an escaped hamster"),
       P("seed shells by the library", "D-DETAIL-AS-MAIN"),
       P("how to care for small pets", "D-TOPIC-ADJACENT"),
       P("a hamster that never left its cage", "D-OPPOSITE")], { retention: true }),
    it("mostly_about_info", 1, 2, 11,
      "Tide pools change twice a day. When the tide is out, the pools sit still in the sun, and you can peer in. When the tide rolls back, the sea covers everything, bringing fresh water and food. The creatures in the pool live by this in-and-out clock.",
      QI,
      [K("how the tide changes life in a tide pool"),
       P("pools sitting still in the sun", "D-DETAIL-AS-MAIN"),
       P("every animal in the sea", "D-TOPIC-ADJACENT"),
       P("pools the sea never touches", "D-OPPOSITE")], { retention: true }),
    it("best_title", 2, 1, 9,
      "The night bus is a different world. Streetlights slide across sleepy faces. A nurse heads to her shift; a baker heads home, dusted in flour. The driver knows the regulars by name and waits an extra breath at every stop, because nobody should run at midnight.",
      "Which title fits this passage best?",
      [K("Riders of the Night Bus"),
       P("A Baker Dusted in Flour", "D-DETAIL-AS-MAIN"),
       P("How Buses Are Driven", "D-TOPIC-ADJACENT"),
       P("The Bus That Stopped Running", "D-OPPOSITE")], { retention: true }),
    it("best_title", 2, 2, 10,
      "The campfire needed three tries. The first pile of sticks was too wet. The second caught, then faded into smoke. For the third try, Sana peeled dry bark shavings and stacked the sticks like a little tent. Her uncle lit them safely, and the flame climbed, crackled, and settled in for the evening.",
      "Which title fits this passage best?",
      [K("Sana Keeps Trying"),
       P("A Match Behind a Hand", "D-DETAIL-AS-MAIN"),
       P("Forests and Their Trees", "D-TOPIC-ADJACENT"),
       P("The Fire That Never Lit", "D-OPPOSITE")], { retention: true }),
    it("main_idea_vs_detail", 2, 1, 9,
      "Swifts are astonishing birds. They eat while flying and even sleep on the wing. Their nests are tucked under roofs, and when the chicks leave, they may not land again for two whole years. In late summer the sky over town fills with their screaming, swooping games.",
      "Which option best states the main idea?",
      [K("swifts live almost their whole lives in the air"),
       P("their nests are under roofs", "D-DETAIL-AS-MAIN"),
       P("they scream over town in late summer", "D-DETAIL-AS-MAIN"),
       P("chicks may not land for two years", "D-DETAIL-AS-MAIN")], { retention: true }),
    it("main_idea_vs_detail", 2, 2, 10,
      "The repair cafe opens in the hall on the first Saturday of the month. People bring broken toasters, wobbly chairs, and jackets with stuck zips. Volunteers with toolboxes sit at long tables and mend things for free, explaining as they go. Most visitors leave with their things working and a new trick learned.",
      "Which option best states the main idea?",
      [K("volunteers fix people's broken things for free"),
       P("it happens in the hall", "D-DETAIL-AS-MAIN"),
       P("some jackets have stuck zips", "D-DETAIL-AS-MAIN"),
       P("volunteers sit at long tables with toolboxes", "D-DETAIL-AS-MAIN")], { retention: true }),
    it("summary_choice", 2, 1, 9,
      "The twins entered the sandcastle contest with a plan. Ria dug the moat while Rafi packed the towers. Halfway through, a wave stole their gate. They rebuilt it farther up the beach, faster this time. Their castle did not win first prize, but the judges gave it a ribbon for Best Teamwork.",
      "Which sentence sums up the whole passage best?",
      [K("The twins worked as a team and won a special ribbon."),
       P("A wave stole the castle gate.", "D-DETAIL-AS-MAIN"),
       P("Beaches are made of sand and shells.", "D-TOPIC-ADJACENT"),
       P("The twins gave up after the wave.", "D-OPPOSITE")], { retention: true }),
    it("summary_choice", 2, 2, 10,
      "Every window on Wren Street has a different bird sticker, because of one shop. The bookstore owner noticed birds bumping the big clear glass. She stuck a paper owl in the window, and the bumping stopped. She printed spare stickers, left them in a basket by the register, and week by week the whole street joined in.",
      "Which sentence sums up the whole passage best?",
      [K("A window idea helped birds across the neighborhood."),
       P("A paper owl was stuck in the bookshop window.", "D-DETAIL-AS-MAIN"),
       P("Bookshops sell many kinds of books.", "D-TOPIC-ADJACENT"),
       P("The street took every sticker down.", "D-OPPOSITE")], { retention: true }),
    it("best_title", 2, 1, 11,
      "Dad's old radio only played crackles until Amal turned the dial a hair at a time. A voice swam up out of the fuzz, then music, clear as water. Now the radio lives on the windowsill, and every breakfast starts with Amal's steady hand finding the station again.",
      "Which title fits this passage best?",
      [K("The Radio That Came Back to Life"),
       P("Crackles at Breakfast", "D-DETAIL-AS-MAIN"),
       P("How Sound Travels", "D-TOPIC-ADJACENT"),
       P("The Radio They Threw Away", "D-OPPOSITE")], { retention: true }),
    it("summary_choice", 2, 2, 11,
      "The school's old apple tree gives more fruit than anyone can eat. This year the cook dried rings of apple for snack time. A first-grade class pressed juice with a squeaky hand press. The rest went in crates by the gate with a sign saying HELP YOURSELF, and by Friday every crate was empty.",
      "Which sentence sums up the whole passage best?",
      [K("The school found ways to share a huge apple harvest."),
       P("A first-grade class pressed juice with a hand press.", "D-DETAIL-AS-MAIN"),
       P("Apple trees blossom in the spring.", "D-TOPIC-ADJACENT"),
       P("The apples were left to rot.", "D-OPPOSITE")], { retention: true })
  ]
};
