// Prepositions of Place — v3 authored bank (wave W10, paired with adjectives).
// The 303-item, 55-key sprawl prunes to 16 curated spatial words.
// L1 PREPOSITION_SCENE_CHOICE: ONE drawn scene, options differ ONLY by the
//   preposition (function-swap by construction). Scene-less relations use the
//   INVERSE of an existing scene (bird_above_tree answers "where is the
//   tree?" for below) — every relation gets real art with zero new assets.
// Every L1 item is a simple image-led location question. Children identify the
// depicted relationship; they never have to decode a text-only cloze first.
// L2 PREPOSITION_SENTENCE_FIT: cloze over four prepositions.
// L2 PREPOSITION_PRECISION: two options are spatially possible, one is exact —
//   every note defends why the key is uniquely right (the C-1 pressure item).
// The malformed "Choose the precise word means…" prompts are dead.
// Spec: docs/skills-assessment-rebuild/BLUEPRINTS_LANGUAGE.md §18.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });

// Scene choice: img is the scene file stem, options are relation phrases.
const psc = (u, lvl, ph, v, scene, prompt, phrases, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "PREPOSITION_SCENE_CHOICE",
  prompt,
  spoken: prompt,
  choices: phrases.map((p, i) => (i === 0 ? K(p) : P(p, rationales[i - 1] || "D-FUNCTION-SWAP"))),
  media: "image-required",
  img: scene,
  imgAlt: scene.replace(/_/g, " "),
  target: scene,
  note
});

const ptc = (u, lvl, ph, v, scene, prompt, words, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "PREPOSITION_TEXT_CHOICE",
  prompt,
  spoken: prompt,
  choices: words.map((w, i) => (i === 0 ? K(w) : P(w, rationales[i - 1]))),
  media: "image-required",
  img: scene,
  imgAlt: prompt.replace("___", words[0]),
  target: scene,
  note
});

const psf = (u, lvl, ph, v, sentence, words, rationales, note = "", imageKey = "") => ({
  u, lvl, ph, v, fmt: "PREPOSITION_SENTENCE_FIT",
  prompt: sentence,
  spoken: `Which where-word finishes the sentence? ${sentence.replace("___", "hmm")}`,
  sentence,
  choices: words.map((w, i) => (i === 0 ? K(w) : P(w, rationales[i - 1]))),
  media: "image-required",
  img: imageKey || `${u}-scene-${v}`,
  imgAlt: sentence.replace("___", words[0]),
  target: imageKey || `${u}-scene-${v}`,
  note
});

const pp = (u, lvl, ph, v, sentence, words, rationales, note = "", imageKey = "") => ({
  u, lvl, ph, v, fmt: "PREPOSITION_PRECISION",
  prompt: sentence,
  spoken: `Which where-word fits exactly? ${sentence.replace("___", "hmm")}`,
  sentence,
  choices: words.map((w, i) => (i === 0 ? K(w) : P(w, rationales[i - 1]))),
  media: "image-required",
  img: imageKey || `${u}-scene-${v}`,
  imgAlt: sentence.replace("___", words[0]),
  target: imageKey || `${u}-scene-${v}`,
  note
});

const FS = "D-FUNCTION-SWAP";
const PU = "D-PLAUSIBLE-UNSUPPORTED";

export default {
  skillId: "prepositions_of_place",
  skillName: "Prepositions of Place",
  items: [
    // ================= L1 phase 1: in on under behind next_to =================
    psc("in", 1, 1, 1, "cat_in_box", "Where is the cat?",
      ["in the box", "on the box", "under the box", "behind the box"], [FS, FS, FS]),
    psc("in", 1, 1, 2, "goat_inside_barn", "Where is the goat?",
      ["in the barn", "on the barn", "behind the barn", "under the barn"], [FS, FS, FS]),
    ptc("in", 1, 1, 3, "cat_in_box", "The cat is ___ the box.",
      ["in", "on", "under", "behind"], [FS, FS, FS]),
    ptc("in", 1, 1, 4, "goat_inside_barn", "The goat is ___ the barn.",
      ["in", "on", "behind", "under"], [FS, FS, FS]),
    psc("on", 1, 1, 1, "ball_on_chair", "Where is the ball?",
      ["on the chair", "in the chair", "under the chair", "behind the chair"], [FS, FS, FS]),
    psc("on", 1, 1, 2, "snow_on_roof", "Where is the snow?",
      ["on the roof", "in the roof", "under the roof", "behind the roof"], [FS, FS, FS]),
    ptc("on", 1, 1, 3, "ball_on_chair", "The ball is ___ the chair.",
      ["on", "in", "under", "behind"], [FS, FS, FS]),
    ptc("on", 1, 1, 4, "snow_on_roof", "The snow is ___ the roof.",
      ["on", "in", "under", "next to"], [FS, FS, FS]),
    psc("under", 1, 1, 1, "dog_under_table", "Where is the dog?",
      ["under the table", "on the table", "in the table", "next to the table"], [FS, FS, FS]),
    psc("under", 1, 1, 2, "slippers_under_bed", "Where are the slippers?",
      ["under the bed", "on the bed", "behind the bed", "next to the bed"], [FS, FS, FS]),
    ptc("under", 1, 1, 3, "dog_under_table", "The dog is ___ the table.",
      ["under", "on", "in", "next to"], [FS, FS, FS]),
    ptc("under", 1, 1, 4, "slippers_under_bed", "The slippers are ___ the bed.",
      ["under", "on", "behind", "next to"], [FS, FS, FS]),
    psc("behind", 1, 1, 1, "bear_behind_tree", "Where is the bear?",
      ["behind the tree", "in front of the tree", "above the tree", "in the tree"], [FS, FS, FS]),
    psc("behind", 1, 1, 2, "child_behind_curtain", "Where is the child?",
      ["behind the curtain", "in front of the curtain", "above the curtain", "next to the curtain"], [FS, FS, FS]),
    ptc("behind", 1, 1, 3, "bear_behind_tree", "The bear is ___ the tree.",
      ["behind", "in front of", "above", "inside"], [FS, FS, FS]),
    ptc("behind", 1, 1, 4, "child_behind_curtain", "The child is ___ the curtain.",
      ["behind", "in front of", "above", "next to"], [FS, FS, FS]),
    psc("next_to", 1, 1, 1, "rabbit_beside_basket", "Where is the rabbit?",
      ["next to the basket", "in the basket", "under the basket", "behind the basket"], [FS, FS, FS]),
    psc("next_to", 1, 1, 2, "cup_next_to_plate", "Where is the cup?",
      ["next to the plate", "under the plate", "behind the plate", "on the plate"], [FS, FS, FS]),
    ptc("next_to", 1, 1, 3, "rabbit_beside_basket", "The rabbit is ___ the basket.",
      ["next to", "under", "behind", "in"], [FS, FS, FS]),
    ptc("next_to", 1, 1, 4, "cup_next_to_plate", "The cup is ___ the plate.",
      ["next to", "under", "behind", "on"], [FS, FS, FS]),

    // ================= L1 phase 2: between in_front_of above below =================
    psc("between", 1, 2, 1, "cup_between_books", "Where is the cup?",
      ["between the books", "on the books", "under the books", "behind the books"], [FS, FS, FS]),
    psc("between", 1, 2, 2, "teddy_between_pillows", "Where is the teddy?",
      ["between the pillows", "on the pillows", "under the pillows", "behind the pillows"], [FS, FS, FS]),
    ptc("between", 1, 2, 3, "cup_between_books", "The cup is ___ the books.",
      ["between", "behind", "in front of", "above"], [FS, FS, FS]),
    ptc("between", 1, 2, 4, "teddy_between_pillows", "The teddy is ___ the pillows.",
      ["between", "on", "under", "behind"], [FS, FS, FS]),
    psc("in_front_of", 1, 2, 1, "bear_behind_tree", "Where is the tree?",
      ["in front of the bear", "behind the bear", "on the bear", "under the bear"], [FS, FS, FS],
      "the same scene answers both relations — the tree stands in front of the bear"),
    psc("in_front_of", 1, 2, 2, "bike_in_front_of_garage", "Where is the bike?",
      ["in front of the garage", "behind the garage", "above the garage", "inside the garage"], [FS, FS, FS]),
    ptc("in_front_of", 1, 2, 3, "bear_behind_tree", "The tree is ___ the bear.",
      ["in front of", "behind", "under", "next to"], [FS, FS, FS]),
    ptc("in_front_of", 1, 2, 4, "bike_in_front_of_garage", "The bike is ___ the garage.",
      ["in front of", "behind", "above", "inside"], [FS, FS, FS]),
    psc("above", 1, 2, 1, "bird_above_tree", "Where is the bird?",
      ["above the tree", "under the tree", "in the tree", "next to the tree"], [FS, FS, FS]),
    psc("above", 1, 2, 2, "clock_above_door", "Where is the clock?",
      ["above the door", "under the door", "behind the door", "in the door"], [FS, FS, FS]),
    ptc("above", 1, 2, 3, "bird_above_tree", "The bird is ___ the tree.",
      ["above", "below", "between", "behind"], [FS, FS, FS]),
    ptc("above", 1, 2, 4, "clock_above_door", "The clock is ___ the door.",
      ["above", "under", "behind", "next to"], [FS, FS, FS]),
    psc("below", 1, 2, 1, "bird_above_tree", "Where is the tree?",
      ["below the bird", "above the bird", "behind the bird", "next to the bird"], [FS, FS, FS],
      "the inverse question of the same scene"),
    psc("below", 1, 2, 2, "fish_below_bridge", "Where is the fish?",
      ["below the bridge", "above the bridge", "behind the bridge", "on the bridge"], [FS, FS, FS]),
    ptc("below", 1, 2, 3, "bird_above_tree", "The tree is ___ the bird.",
      ["below", "above", "behind", "next to"], [FS, FS, FS]),
    ptc("below", 1, 2, 4, "fish_below_bridge", "The fish is ___ the bridge.",
      ["below", "above", "behind", "on"], [FS, FS, FS]),

    // ================= L2 phase 1: over through near opposite =================
    psf("over", 2, 1, 1, "The plane flew ___ the town.",
      ["over", "under", "between", "behind"], [FS, FS, FS], "", "plane_over_town"),
    psf("over", 2, 1, 2, "The horse leapt ___ the gate.",
      ["over", "through", "under", "past"], [FS, FS, FS], "", "horse_over_gate"),
    pp("over", 2, 1, 3, "High in the sky, the plane passed ___ the town.",
      ["over", "behind", "through", "near"], [PU, PU, PU],
      "The elevated picture and high-in-the-sky clue pin over.",
      "plane_over_town"),
    pp("over", 2, 1, 4, "The horse jumped ___ the locked gate.",
      ["over", "through", "under", "past"], [PU, PU, PU],
      "through and under are possible for an open gate; the locked gate and picture leave over.",
      "horse_over_gate"),
    psf("through", 2, 1, 1, "The train roared ___ the tunnel.",
      ["through", "above", "beside", "behind"], [FS, FS, FS], "", "train_through_tunnel"),
    psf("through", 2, 1, 2, "Rain dripped ___ the crack in the tent.",
      ["through", "under", "behind", "over"], [FS, FS, FS], "", "rain_through_tent_crack"),
    pp("through", 2, 1, 3, "The train entered one end and left the other: ___ the tunnel.",
      ["through", "above", "beside", "behind"], [PU, PU, PU],
      "Entering one end and leaving the other defines through.",
      "train_through_tunnel"),
    pp("through", 2, 1, 4, "The tent leaked because rain came ___ a small crack.",
      ["through", "around", "over", "under"], [PU, PU, PU],
      "The visible crack is an opening that the rain passes through.",
      "rain_through_tent_crack"),
    psf("near", 2, 1, 1, "Our house is ___ the school on the same short street.",
      ["near", "inside", "above", "behind"], [FS, FS, FS],
      "The picture shows the house and school close together on one short street.",
      "house_near_school"),
    psf("near", 2, 1, 2, "Keep the bucket ___ the door for spills.",
      ["near", "above", "through", "between"], [FS, FS, FS], "", "bucket_near_door"),
    pp("near", 2, 1, 3, "Home is a short walk away. Our house is ___ the school.",
      ["near", "inside", "above", "behind"], [PU, PU, PU],
      "The picture and short-walk clue establish near without allowing inside, above, or behind.",
      "house_near_school"),
    pp("near", 2, 1, 4, "Keep the bucket ___ the door so it is quick to reach.",
      ["near", "opposite", "above", "between"], [PU, PU, PU],
      "Quick to reach and the small pictured gap pin near.",
      "bucket_near_door"),
    psf("opposite", 2, 1, 1, "The bakery is ___ the bank, just across the road.",
      ["opposite", "inside", "under", "through"], [FS, FS, FS],
      "just across the road defines opposite",
      "bakery_opposite_bank"),
    psf("opposite", 2, 1, 2, "The two goals stand ___ each other.",
      ["opposite", "beside", "near", "over"], [FS, FS, FS], "", "opposite_goals_pitch"),
    pp("opposite", 2, 1, 3, "The bakery faces the bank across the road: ___ the bank.",
      ["opposite", "beside", "behind", "near"], [PU, PU, PU],
      "Facing across the road pins opposite; near alone does not express the facing relation.",
      "bakery_opposite_bank"),
    pp("opposite", 2, 1, 4, "The goals at the two ends stand ___ each other.",
      ["opposite", "beside", "near", "over"], [PU, PU, PU],
      "goals face each other end to end — beside would be the same end",
      "opposite_goals_pitch"),

    // ================= L2 phase 2: among around inside_outside =================
    psf("among", 2, 2, 1, "A red tulip grew ___ the yellow tulips.",
      ["among", "between", "inside", "above"], [FS, FS, FS],
      "many yellow ones — among, not the two-thing between",
      "red_tulip_among_yellow_tulips"),
    psf("among", 2, 2, 2, "The deer stood ___ the trees.",
      ["among", "between", "over", "onto"], [FS, FS, FS], "", "deer_among_trees"),
    pp("among", 2, 2, 3, "One red flower grows ___ many yellow flowers.",
      ["among", "between", "under", "behind"], [PU, PU, PU],
      "Many surrounding flowers require among; between describes a smaller two-sided relation.",
      "red_tulip_among_yellow_tulips"),
    pp("among", 2, 2, 4, "A deer stood ___ the trees, hard to spot.",
      ["among", "between", "behind", "near"], [PU, PU, PU],
      "The deer is surrounded by several trees; behind would describe one tree.",
      "deer_among_trees"),
    psf("around", 2, 2, 1, "The fence runs ___ the whole garden.",
      ["around", "across", "through", "over"], [FS, FS, FS],
      "the whole garden pins the ring shape of around",
      "fence_around_garden"),
    psf("around", 2, 2, 2, "The path bends ___ the puddle.",
      ["around", "through", "over", "into"], [FS, FS, FS], "", "path_around_puddle"),
    pp("around", 2, 2, 3, "We walked ___ the puddle to keep our shoes dry.",
      ["around", "through", "over", "into"], [PU, PU, PU],
      "through gets you wet and over means a jump — walking dry pins around",
      "path_around_puddle"),
    pp("around", 2, 2, 4, "The fence makes a complete ring ___ the garden.",
      ["around", "across", "through", "over"], [PU, PU, PU],
      "A complete ring encloses the garden on all sides, which pins around.",
      "fence_around_garden"),
    psf("inside_outside", 2, 2, 1, "It poured with rain, so we played ___ the house.",
      ["inside", "outside", "above", "under"], [FS, FS, FS],
      "rain pins inside",
      "children_inside_house_in_rain"),
    psf("inside_outside", 2, 2, 2, "Leave the muddy boots ___ the door.",
      ["outside", "inside", "near", "behind"], [FS, FS, FS], "", "muddy_boots_outside_door"),
    pp("inside_outside", 2, 2, 3, "Leave your muddy boots ___ the door, then come in.",
      ["outside", "inside", "beside", "behind"], [PU, PU, PU],
      "Muddy boots stay outdoors before the child comes in, so outside is exact.",
      "muddy_boots_outside_door"),
    pp("inside_outside", 2, 2, 4, "Rain is falling outdoors, but the children are dry ___ the house.",
      ["inside", "outside", "under", "on"], [PU, PU, PU],
      "Dry while rain falls outdoors and the enclosing walls pin inside.",
      "children_inside_house_in_rain"),

    // ================= Retention reserve (form R) =================
    psc("on", 1, 1, 5, "ball_on_chair", "Where is the chair?",
      ["under the ball", "on the ball", "in the ball", "behind the ball"], [FS, FS, FS],
      "the inverse question of the same scene"),
    psc("between", 1, 2, 5, "cup_between_books", "Where are the books?",
      ["next to the cup", "in the cup", "under the cup", "above the cup"], [FS, FS, FS],
      "one book on each side — next to the cup"),
    ptc("in", 1, 1, 5, "goat_inside_barn", "Choose the word: the goat waits ___ the barn.",
      ["in", "on", "next to", "behind"], [FS, FS, FS]),
    ptc("under", 1, 1, 5, "dog_under_table", "Choose the word: the dog rests ___ the table.",
      ["under", "on", "above", "behind"], [FS, FS, FS]),
    ptc("above", 1, 2, 5, "clock_above_door", "Choose the word: the clock hangs ___ the door.",
      ["above", "under", "behind", "next to"], [FS, FS, FS]),
    ptc("next_to", 1, 1, 5, "rabbit_beside_basket", "Choose the words: the rabbit sits ___ the basket.",
      ["next to", "under", "above", "inside"], [FS, FS, FS]),
    psf("over", 2, 1, 5, "The horse is jumping ___ the gate.",
      ["over", "under", "inside", "between"], [FS, FS, FS],
      "The horse is visibly airborne above the gate.",
      "horse_over_gate"),
    psf("through", 2, 1, 5, "The train is passing ___ the tunnel.",
      ["through", "over", "behind", "onto"], [FS, FS, FS],
      "The train enters the tunnel opening.",
      "train_through_tunnel"),
    pp("near", 2, 1, 5, "A short path joins home and school. They are ___ each other.",
      ["near", "inside", "opposite", "above"], [PU, PU, PU],
      "The short path and small pictured gap pin near.",
      "house_near_school"),
    pp("among", 2, 2, 5, "The single red tulip stands ___ the yellow tulips.",
      ["among", "between", "under", "onto"], [PU, PU, PU],
      "Several yellow tulips surround the red one, which pins among.",
      "red_tulip_among_yellow_tulips"),
    psf("around", 2, 2, 5, "The fence curves ___ the garden.",
      ["around", "through", "onto", "above"], [FS, FS, FS],
      "The fence encloses the garden.",
      "fence_around_garden"),
    psf("inside_outside", 2, 2, 5, "The children stay dry ___ the house.",
      ["inside", "outside", "under", "between"], [FS, FS, FS],
      "The house walls enclose the children while rain falls outdoors.",
      "children_inside_house_in_rain")
  ].map(item => {
    if (item.v >= 5) item.retention = true;
    return item;
  })
};
