// Prepositions of Place — v3 authored bank (wave W10, paired with adjectives).
// Sixteen spatial concepts, each tied to visible scoring evidence.
// L1 PREPOSITION_SCENE_CHOICE: ONE drawn scene, options differ ONLY by the
//   preposition (function-swap by construction). Scene-less relations use the
//   INVERSE of an existing scene (bird_above_tree answers "where is the
//   tree?" for below). Fresh retries use independently authored scenes.
// Every L1 item is a simple image-led location question. Children identify the
// depicted relationship; they never have to decode a text-only cloze first.
// L2 PREPOSITION_SENTENCE_FIT: cloze over four prepositions. The exact
// pictured relationship supplies essential scoring evidence.
// L2 PREPOSITION_PRECISION: two options are spatially possible, one is exact —
//   every note defends why the key is uniquely right (the C-1 pressure item).
// The malformed "Choose the precise word means…" prompts are dead.
// Spec: docs/skills-assessment-rebuild/BLUEPRINTS_LANGUAGE.md §18.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });

const SCENE_LABELS = {
  "cat_in_box": "A cat and a box.",
  "goat_inside_barn": "A goat and a barn.",
  "ball_on_chair": "A ball and a chair.",
  "snow_on_roof": "Snow and a house roof.",
  "dog_under_table": "A dog and a table.",
  "slippers_under_bed": "A pair of slippers and a bed.",
  "bear_behind_tree": "A bear and a tree.",
  "child_behind_curtain": "A child and a curtain.",
  "rabbit_beside_basket": "A rabbit and a basket.",
  "cup_next_to_plate": "A cup and a plate.",
  "cup_between_books": "A cup and two books.",
  "teddy_between_pillows": "A teddy bear and two pillows.",
  "bike_in_front_of_garage": "A bicycle and a garage.",
  "bird_above_tree": "A bird and a tree.",
  "clock_above_door": "A clock and a door.",
  "fish_below_bridge": "A fish and a bridge.",
  "plane_over_town": "A plane and a town.",
  "horse_over_gate": "A horse and a gate.",
  "train_through_tunnel": "A train and a tunnel.",
  "rain_through_tent_crack": "Rain and a tent with a crack.",
  "house_near_school": "A house, a school and a path.",
  "bucket_near_door": "A bucket and a door.",
  "bakery_opposite_bank": "A bakery, a bank and a road.",
  "opposite_goals_pitch": "Two goals on a playing field.",
  "red_tulip_among_yellow_tulips": "A red tulip and several yellow tulips.",
  "deer_among_trees": "A deer and several trees.",
  "fence_around_garden": "A fence and a garden.",
  "path_around_puddle": "A path and a puddle.",
  "children_inside_house_in_rain": "Children, a house and rain.",
  "muddy_boots_outside_door": "Muddy boots and a door.",
  "fish-in-bowl": "An orange fish and a bowl.",
  "pencils-in-cup": "Three pencils and a blue cup.",
  "hat-on-head": "A red hat and a child.",
  "book-on-shelf": "A green book and a shelf.",
  "ball-under-bench": "A red ball and a wooden bench.",
  "shoe-under-stool": "A blue shoe and a stool.",
  "cat-behind-sofa": "A cat and a blue sofa.",
  "sun-behind-cloud": "A yellow sun and a cloud.",
  "lamp-next-to-bed": "A floor lamp and a bed.",
  "dog-next-to-bench": "A dog and a bench.",
  "ball-between-boxes": "A red ball and two blue boxes.",
  "child-between-trees": "A child and two trees.",
  "dog-in-front-of-house": "A dog and a house.",
  "flower-in-front-of-fence": "A red flower and a blue fence.",
  "balloon-above-child": "A balloon and a child.",
  "light-above-table": "A hanging light and a table.",
  "fish-below-boat": "A fish and a boat.",
  "ball-below-shelf": "A ball and a shelf.",
  "kite-over-pond": "A kite and a pond.",
  "bridge-over-stream": "A bridge and a stream.",
  "ball-through-hoop": "A basketball and a hoop.",
  "water-through-pipe": "Water, a pipe and a basin.",
  "backpack-near-bench": "A backpack and a bench.",
  "dog-near-doghouse": "A dog and a doghouse.",
  "chairs-opposite-table": "Two chairs and a round table.",
  "children-opposite-net": "Two children and a tennis net.",
  "red-ball-among-blue-balls": "A red ball and several blue balls.",
  "butterfly-among-flowers": "A butterfly and several flowers.",
  "ribbon-around-gift": "A ribbon and a gift.",
  "road-around-lake": "A road and a lake.",
  "kitten-inside-tent": "A kitten and an open tent.",
  "ball-outside-basket": "A ball and an empty basket.",
  "pencil-among-crayons": "A yellow pencil and several crayons.",
  "path-around-tree": "A path and a tree.",
  "duck-outside-pond": "A duck and a pond.",
  "apple-inside-lunchbox": "An apple and an open lunchbox."
};

const SCENE_PATHS = {
  "cat_in_box": "/images/assessment/release-media/cat-in-box-b44d5222.webp",
  "goat_inside_barn": "/images/assessment/release-media/goat-inside-barn-23d973f1.webp",
  "ball_on_chair": "/images/assessment/release-media/ball-on-chair-f5c50c79.webp",
  "snow_on_roof": "/images/assessment/release-media/snow-on-roof-f8167902.webp",
  "dog_under_table": "/images/assessment/release-media/dog-under-table-cf3e17f2.webp",
  "slippers_under_bed": "/images/assessment/release-media/slippers-under-bed-f363802c.webp",
  "bear_behind_tree": "/images/assessment/release-media/bear-behind-tree-b145e7e0.webp",
  "child_behind_curtain": "/images/assessment/release-media/child-behind-curtain-bcc7e04e.webp",
  "rabbit_beside_basket": "/images/assessment/release-media/rabbit-beside-basket-59d1b7cb.webp",
  "cup_next_to_plate": "/images/assessment/release-media/cup-next-to-plate-4f498f19.webp",
  "cup_between_books": "/images/assessment/release-media/cup-between-books-017aa912.webp",
  "teddy_between_pillows": "/images/assessment/release-media/teddy-between-pillows-ea981f49.webp",
  "bike_in_front_of_garage": "/images/assessment/release-media/bike-in-front-of-garage-603483c8.webp",
  "bird_above_tree": "/images/assessment/release-media/bird-above-tree-b27b365f.webp",
  "clock_above_door": "/images/assessment/release-media/clock-above-door-038c8846.webp",
  "fish_below_bridge": "/images/assessment/release-media/fish-below-bridge-1d71baa3.webp",
  "plane_over_town": "/images/assessment/release-media/plane-over-town-ccea5cd1.webp",
  "horse_over_gate": "/images/assessment/release-media/horse-over-gate-7ddfc247.webp",
  "train_through_tunnel": "/images/assessment/release-media/train-through-tunnel-adfa0aae.webp",
  "rain_through_tent_crack": "/images/assessment/release-media/rain-through-tent-crack-605d07ce.webp",
  "house_near_school": "/images/assessment/release-media/house-near-school-131b7950.webp",
  "bucket_near_door": "/images/assessment/release-media/bucket-near-door-aaa987d5.webp",
  "bakery_opposite_bank": "/images/assessment/release-media/bakery-opposite-bank-e3652e80.webp",
  "opposite_goals_pitch": "/images/assessment/release-media/opposite-goals-pitch-e13732f7.webp",
  "red_tulip_among_yellow_tulips": "/images/assessment/release-media/red-tulip-among-yellow-tulips-e122def3.webp",
  "deer_among_trees": "/images/assessment/release-media/deer-among-trees-d0bca87e.webp",
  "fence_around_garden": "/images/assessment/release-media/fence-around-garden-fd900b5e.webp",
  "path_around_puddle": "/images/assessment/release-media/path-around-puddle-cdc71276.webp",
  "children_inside_house_in_rain": "/images/assessment/release-media/children-inside-house-in-rain-ced30727.webp",
  "muddy_boots_outside_door": "/images/assessment/release-media/muddy-boots-outside-door-70820ee5.webp",
  "fish-in-bowl": "/images/assessment/grammar-scenes/fish-in-bowl.webp",
  "pencils-in-cup": "/images/assessment/grammar-scenes/pencils-in-cup.webp",
  "hat-on-head": "/images/assessment/grammar-scenes/hat-on-head.webp",
  "book-on-shelf": "/images/assessment/grammar-scenes/book-on-shelf.webp",
  "ball-under-bench": "/images/assessment/grammar-scenes/ball-under-bench.webp",
  "shoe-under-stool": "/images/assessment/grammar-scenes/shoe-under-stool.webp",
  "cat-behind-sofa": "/images/assessment/grammar-scenes/cat-behind-sofa.webp",
  "sun-behind-cloud": "/images/assessment/grammar-scenes/sun-behind-cloud.webp",
  "lamp-next-to-bed": "/images/assessment/grammar-scenes/lamp-next-to-bed.webp",
  "dog-next-to-bench": "/images/assessment/grammar-scenes/dog-next-to-bench.webp",
  "ball-between-boxes": "/images/assessment/grammar-scenes/ball-between-boxes.webp",
  "child-between-trees": "/images/assessment/grammar-scenes/child-between-trees.webp",
  "dog-in-front-of-house": "/images/assessment/grammar-scenes/dog-in-front-of-house.webp",
  "flower-in-front-of-fence": "/images/assessment/grammar-scenes/flower-in-front-of-fence.webp",
  "balloon-above-child": "/images/assessment/grammar-scenes/balloon-above-child.webp",
  "light-above-table": "/images/assessment/grammar-scenes/light-above-table.webp",
  "fish-below-boat": "/images/assessment/grammar-scenes/fish-below-boat.webp",
  "ball-below-shelf": "/images/assessment/grammar-scenes/ball-below-shelf.webp",
  "kite-over-pond": "/images/assessment/grammar-scenes/kite-over-pond.webp",
  "bridge-over-stream": "/images/assessment/grammar-scenes/bridge-over-stream.webp",
  "ball-through-hoop": "/images/assessment/grammar-scenes/ball-through-hoop.webp",
  "water-through-pipe": "/images/assessment/grammar-scenes/water-through-pipe.webp",
  "backpack-near-bench": "/images/assessment/grammar-scenes/backpack-near-bench.webp",
  "dog-near-doghouse": "/images/assessment/grammar-scenes/dog-near-doghouse.webp",
  "chairs-opposite-table": "/images/assessment/grammar-scenes/chairs-opposite-table.webp",
  "children-opposite-net": "/images/assessment/grammar-scenes/children-opposite-net.webp",
  "red-ball-among-blue-balls": "/images/assessment/grammar-scenes/red-ball-among-blue-balls.webp",
  "butterfly-among-flowers": "/images/assessment/grammar-scenes/butterfly-among-flowers.webp",
  "ribbon-around-gift": "/images/assessment/grammar-scenes/ribbon-around-gift.webp",
  "road-around-lake": "/images/assessment/grammar-scenes/road-around-lake.webp",
  "kitten-inside-tent": "/images/assessment/grammar-scenes/kitten-inside-tent.webp",
  "ball-outside-basket": "/images/assessment/grammar-scenes/ball-outside-basket.webp",
  "pencil-among-crayons": "/images/assessment/grammar-scenes/pencil-among-crayons.webp",
  "path-around-tree": "/images/assessment/grammar-scenes/path-around-tree.webp",
  "duck-outside-pond": "/images/assessment/grammar-scenes/duck-outside-pond.webp",
  "apple-inside-lunchbox": "/images/assessment/grammar-scenes/apple-inside-lunchbox.webp"
};

// Scene choice: img is the scene file stem, options are relation phrases.
const psc = (u, lvl, ph, v, scene, prompt, phrases, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "PREPOSITION_SCENE_CHOICE",
  prompt,
  spoken: prompt,
  choices: phrases.map((p, i) => (i === 0 ? K(p) : P(p, rationales[i - 1] || "D-FUNCTION-SWAP"))),
  media: "image-required",
  img: scene,
  imgAlt: SCENE_LABELS[scene],
  target: scene,
  suppressStimulusAudio: true,
  note
});

const ptc = (u, lvl, ph, v, scene, prompt, words, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "PREPOSITION_TEXT_CHOICE",
  prompt: `Which word tells where: ${prompt}`,
  spoken: `Which word tells where? ${prompt.replace("___", "hmm")}`,
  choices: words.map((w, i) => (i === 0 ? K(w) : P(w, rationales[i - 1]))),
  media: "image-required",
  img: scene,
  imgAlt: SCENE_LABELS[scene],
  target: scene,
  suppressStimulusAudio: true,
  note
});

const psf = (u, lvl, ph, v, sentence, words, rationales, note = "", scene) => ({
  u, lvl, ph, v, fmt: "PREPOSITION_SENTENCE_FIT",
  prompt: `Which word tells where: ${sentence}`,
  spoken: `Which word tells where? ${sentence.replace("___", "hmm")}`,
  sentence,
  choices: words.map((w, i) => (i === 0 ? K(w) : P(w, rationales[i - 1]))),
  media: "image-required",
  img: scene,
  imgAlt: SCENE_LABELS[scene],
  target: scene,
  suppressStimulusAudio: true,
  note
});

const pp = (u, lvl, ph, v, sentence, words, rationales, note = "", scene) => ({
  u, lvl, ph, v, fmt: "PREPOSITION_PRECISION",
  prompt: `Which word tells exactly where? ${sentence}`,
  spoken: `Which word tells exactly where? ${sentence.replace("___", "hmm")}`,
  sentence,
  choices: words.map((w, i) => (i === 0 ? K(w) : P(w, rationales[i - 1]))),
  media: "image-required",
  img: scene,
  imgAlt: SCENE_LABELS[scene],
  target: scene,
  suppressStimulusAudio: true,
  note
});

const FS = "D-FUNCTION-SWAP";
const PU = "D-PLAUSIBLE-UNSUPPORTED";

const freshPhaseItems = [
  pp("among", 2, 2, 6, "The pencil lies ___ the crayons.",
      ["among", "far from", "above", "outside"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "pencil-among-crayons"),
  pp("around", 2, 2, 6, "The path goes ___ the tree.",
      ["around", "through", "over", "under"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "path-around-tree"),
  pp("inside_outside", 2, 2, 6, "The duck is ___ the pond.",
      ["outside", "inside", "above", "under"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "duck-outside-pond"),
  pp("inside_outside", 2, 2, 7, "The apple is ___ the lunchbox.",
      ["inside", "outside", "under", "on"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "apple-inside-lunchbox")
];

export default {
  skillId: "prepositions_of_place",
  skillName: "Prepositions of Place",
  imageResolver: scene => SCENE_PATHS[scene] || null,
  items: [
    // ================= L1 phase 1: in on under behind next_to =================
    psc("in", 1, 1, 1, "cat_in_box", "Where is the cat?",
      ["in the box", "on the box", "under the box", "behind the box"], [FS, FS, FS]),
    psc("in", 1, 1, 2, "goat_inside_barn", "Where is the goat?",
      ["in the barn", "on the barn", "behind the barn", "under the barn"], [FS, FS, FS]),
    ptc("in", 1, 1, 3, "fish-in-bowl", "The fish is ___ the bowl.",
      ["in", "on", "under", "behind"], [FS, FS, FS]),
    ptc("in", 1, 1, 4, "pencils-in-cup", "The pencils are ___ the cup.",
      ["in", "on", "behind", "under"], [FS, FS, FS]),
    psc("on", 1, 1, 1, "ball_on_chair", "Where is the ball?",
      ["on the chair", "in the chair", "under the chair", "behind the chair"], [FS, FS, FS]),
    psc("on", 1, 1, 2, "snow_on_roof", "Where is the snow?",
      ["on the roof", "in the roof", "under the roof", "behind the roof"], [FS, FS, FS]),
    ptc("on", 1, 1, 3, "hat-on-head", "The hat is ___ the child\u2019s head.",
      ["on", "under", "behind", "next to"], [FS, FS, FS]),
    ptc("on", 1, 1, 4, "book-on-shelf", "The book is ___ the shelf.",
      ["on", "under", "behind", "next to"], [FS, FS, FS]),
    psc("under", 1, 1, 1, "dog_under_table", "Where is the dog?",
      ["under the table", "on the table", "in the table", "next to the table"], [FS, FS, FS]),
    psc("under", 1, 1, 2, "slippers_under_bed", "Where are the slippers?",
      ["under the bed", "on the bed", "behind the bed", "next to the bed"], [FS, FS, FS]),
    ptc("under", 1, 1, 3, "ball-under-bench", "The ball is ___ the bench.",
      ["under", "on", "behind", "next to"], [FS, FS, FS]),
    ptc("under", 1, 1, 4, "shoe-under-stool", "The shoe is ___ the stool.",
      ["under", "on", "behind", "next to"], [FS, FS, FS]),
    psc("behind", 1, 1, 1, "bear_behind_tree", "Where is the bear?",
      ["behind the tree", "in front of the tree", "above the tree", "in the tree"], [FS, FS, FS]),
    psc("behind", 1, 1, 2, "child_behind_curtain", "Where is the child?",
      ["behind the curtain", "in front of the curtain", "above the curtain", "next to the curtain"], [FS, FS, FS]),
    ptc("behind", 1, 1, 3, "cat-behind-sofa", "The cat is ___ the sofa.",
      ["behind", "in front of", "under", "inside"], [FS, FS, FS]),
    ptc("behind", 1, 1, 4, "sun-behind-cloud", "The sun is ___ the cloud.",
      ["behind", "in front of", "under", "inside"], [FS, FS, FS]),
    psc("next_to", 1, 1, 1, "rabbit_beside_basket", "Where is the rabbit?",
      ["next to the basket", "in the basket", "under the basket", "behind the basket"], [FS, FS, FS]),
    psc("next_to", 1, 1, 2, "cup_next_to_plate", "Where is the cup?",
      ["next to the plate", "under the plate", "behind the plate", "on the plate"], [FS, FS, FS]),
    ptc("next_to", 1, 1, 3, "lamp-next-to-bed", "The lamp is ___ the bed.",
      ["next to", "under", "on", "inside"], [FS, FS, FS]),
    ptc("next_to", 1, 1, 4, "dog-next-to-bench", "The dog is ___ the bench.",
      ["next to", "under", "on", "behind"], [FS, FS, FS]),

    // ================= L1 phase 2: between in_front_of above below =================
    psc("between", 1, 2, 1, "cup_between_books", "Where is the cup?",
      ["between the books", "on the books", "under the books", "behind the books"], [FS, FS, FS]),
    psc("between", 1, 2, 2, "teddy_between_pillows", "Where is the teddy?",
      ["between the pillows", "on the pillows", "under the pillows", "behind the pillows"], [FS, FS, FS]),
    ptc("between", 1, 2, 3, "ball-between-boxes", "The ball is ___ the boxes.",
      ["between", "on", "under", "behind"], [FS, FS, FS]),
    ptc("between", 1, 2, 4, "child-between-trees", "The child is ___ the trees.",
      ["between", "above", "under", "behind"], [FS, FS, FS]),
    psc("in_front_of", 1, 2, 1, "bear_behind_tree", "Where is the tree?",
      ["in front of the bear", "behind the bear", "on the bear", "under the bear"], [FS, FS, FS],
      "the same scene answers both relations — the tree stands in front of the bear"),
    psc("in_front_of", 1, 2, 2, "bike_in_front_of_garage", "Where is the bike?",
      ["in front of the garage", "behind the garage", "above the garage", "inside the garage"], [FS, FS, FS]),
    ptc("in_front_of", 1, 2, 3, "dog-in-front-of-house", "The dog is ___ the house.",
      ["in front of", "behind", "above", "inside"], [FS, FS, FS]),
    ptc("in_front_of", 1, 2, 4, "flower-in-front-of-fence", "The flower is ___ the fence.",
      ["in front of", "behind", "under", "inside"], [FS, FS, FS]),
    psc("above", 1, 2, 1, "bird_above_tree", "Where is the bird?",
      ["above the tree", "under the tree", "in the tree", "next to the tree"], [FS, FS, FS]),
    psc("above", 1, 2, 2, "clock_above_door", "Where is the clock?",
      ["above the door", "under the door", "behind the door", "in the door"], [FS, FS, FS]),
    ptc("above", 1, 2, 3, "balloon-above-child", "The balloon is ___ the child.",
      ["above", "below", "behind", "next to"], [FS, FS, FS]),
    ptc("above", 1, 2, 4, "light-above-table", "The light is ___ the table.",
      ["above", "under", "behind", "next to"], [FS, FS, FS]),
    psc("below", 1, 2, 1, "bird_above_tree", "Where is the tree?",
      ["below the bird", "above the bird", "behind the bird", "next to the bird"], [FS, FS, FS],
      "the inverse question of the same scene"),
    psc("below", 1, 2, 2, "fish_below_bridge", "Where is the fish?",
      ["below the bridge", "above the bridge", "behind the bridge", "on the bridge"], [FS, FS, FS]),
    ptc("below", 1, 2, 3, "fish-below-boat", "The fish is ___ the boat.",
      ["below", "above", "behind", "on"], [FS, FS, FS]),
    ptc("below", 1, 2, 4, "ball-below-shelf", "The ball is ___ the shelf.",
      ["below", "above", "behind", "on"], [FS, FS, FS]),

    // ================= L2 phase 1: over through near opposite =================
    psf("over", 2, 1, 1, "The plane flew ___ the town.",
      ["over", "under", "between", "behind"], [FS, FS, FS], "", "plane_over_town"),
    psf("over", 2, 1, 2, "The horse jumped ___ the gate.",
      ["over", "through", "under", "past"], [FS, FS, FS], "", "horse_over_gate"),
    pp("over", 2, 1, 3, "The kite flies ___ the pond.",
      ["over", "under", "through", "inside"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "kite-over-pond"),
    pp("over", 2, 1, 4, "The bridge goes ___ the stream.",
      ["over", "under", "beside", "through"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "bridge-over-stream"),
    psf("through", 2, 1, 1, "The train roared ___ the tunnel.",
      ["through", "above", "beside", "behind"], [FS, FS, FS], "", "train_through_tunnel"),
    psf("through", 2, 1, 2, "Rain dripped ___ the crack in the tent.",
      ["through", "under", "behind", "over"], [FS, FS, FS], "", "rain_through_tent_crack"),
    pp("through", 2, 1, 3, "The ball is passing ___ the hoop.",
      ["through", "above", "beside", "behind"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "ball-through-hoop"),
    pp("through", 2, 1, 4, "Water flows ___ the pipe.",
      ["through", "around", "over", "under"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "water-through-pipe"),
    psf("near", 2, 1, 1, "Our house is ___ the school, only a short walk away.",
      ["near", "far from", "inside", "through"], [FS, FS, FS],
      "Only near agrees with the short-walk clue.",
      "house_near_school"),
    psf("near", 2, 1, 2, "Keep the bucket ___ the door, only one step away.",
      ["near", "far from", "through", "over"], [FS, FS, FS], "", "bucket_near_door"),
    pp("near", 2, 1, 3, "The backpack is ___ the bench.",
      ["near", "far from", "under", "inside"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "backpack-near-bench"),
    pp("near", 2, 1, 4, "The dog is ___ the doghouse.",
      ["near", "far from", "inside", "over"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "dog-near-doghouse"),
    psf("opposite", 2, 1, 1, "The bakery is ___ the bank, just across the road.",
      ["opposite", "inside", "under", "through"], [FS, FS, FS],
      "just across the road defines opposite",
      "bakery_opposite_bank"),
    psf("opposite", 2, 1, 2, "The two goals stand ___ each other.",
      ["opposite", "beside", "near", "over"], [FS, FS, FS], "", "opposite_goals_pitch"),
    pp("opposite", 2, 1, 3, "The chairs stand ___ one another.",
      ["opposite", "beside", "under", "inside"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "chairs-opposite-table"),
    pp("opposite", 2, 1, 4, "The children stand ___ each other.",
      ["opposite", "beside", "behind", "over"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "children-opposite-net"),

    // ================= L2 phase 2: among around inside_outside =================
    psf("among", 2, 2, 1, "A red tulip grew ___ the yellow tulips.",
      ["among", "far from", "above", "outside"], [FS, FS, FS],
      "Several yellow tulips surround the red one.",
      "red_tulip_among_yellow_tulips"),
    psf("among", 2, 2, 2, "The deer stood ___ the trees.",
      ["among", "far from", "above", "outside"], [FS, FS, FS], "", "deer_among_trees"),
    pp("among", 2, 2, 3, "The red ball is ___ the blue balls.",
      ["among", "far from", "above", "outside"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "red-ball-among-blue-balls"),
    pp("among", 2, 2, 4, "The butterfly is ___ the flowers.",
      ["among", "far from", "above", "outside"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "butterfly-among-flowers"),
    psf("around", 2, 2, 1, "The fence runs ___ the whole garden.",
      ["around", "across", "through", "over"], [FS, FS, FS],
      "the whole garden pins the ring shape of around",
      "fence_around_garden"),
    psf("around", 2, 2, 2, "The path bends ___ the puddle.",
      ["around", "through", "over", "into"], [FS, FS, FS], "", "path_around_puddle"),
    pp("around", 2, 2, 3, "The ribbon wraps all the way ___ the gift.",
      ["around", "inside", "between", "under"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "ribbon-around-gift"),
    pp("around", 2, 2, 4, "The road goes ___ the lake.",
      ["around", "across", "through", "under"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "road-around-lake"),
    psf("inside_outside", 2, 2, 1, "It rained hard, so we played ___ the house.",
      ["inside", "outside", "above", "under"], [FS, FS, FS],
      "rain pins inside",
      "children_inside_house_in_rain"),
    psf("inside_outside", 2, 2, 2, "Leave the muddy boots ___ the door.",
      ["outside", "inside", "over", "through"], [FS, FS, FS], "", "muddy_boots_outside_door"),
    pp("inside_outside", 2, 2, 3, "The kitten is ___ the tent.",
      ["inside", "outside", "under", "on"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "kitten-inside-tent"),
    pp("inside_outside", 2, 2, 4, "The ball is ___ the basket.",
      ["outside", "inside", "under", "on"], [PU, PU, PU], "The pictured relationship supplies the location evidence.", "ball-outside-basket"),

    // ================= Retention reserve (form R) =================
    psc("on", 1, 1, 5, "ball_on_chair", "Which phrase tells where the ball is?",
      ["on the chair", "under the chair", "in the chair", "behind the chair"], [FS, FS, FS],
      "the retained item measures on directly rather than re-keying an inverse under relation"),
    psc("between", 1, 2, 5, "cup_between_books", "Which phrase tells where the cup is?",
      ["between the books", "on the books", "under the books", "above the books"], [FS, FS, FS],
      "the retained item measures between directly rather than re-keying the books' next-to relation"),
    ptc("in", 1, 1, 5, "goat_inside_barn", "The goat waits ___ the barn.",
      ["in", "on", "next to", "behind"], [FS, FS, FS]),
    ptc("under", 1, 1, 5, "dog_under_table", "The dog rests ___ the table.",
      ["under", "on", "above", "behind"], [FS, FS, FS]),
    ptc("above", 1, 2, 5, "clock_above_door", "The clock hangs ___ the door.",
      ["above", "under", "behind", "next to"], [FS, FS, FS]),
    ptc("next_to", 1, 1, 5, "rabbit_beside_basket", "The rabbit sits ___ the basket.",
      ["next to", "under", "above", "inside"], [FS, FS, FS]),
    psf("over", 2, 1, 5, "The horse is jumping ___ the gate.",
      ["over", "under", "inside", "between"], [FS, FS, FS],
      "The horse is visibly airborne above the gate.",
      "horse_over_gate"),
    psf("through", 2, 1, 5, "The train is passing ___ the tunnel.",
      ["through", "over", "behind", "onto"], [FS, FS, FS],
      "The train enters the tunnel opening.",
      "train_through_tunnel"),
    pp("near", 2, 1, 5, "A short path links home and school: home is ___ school.",
      ["near", "far from", "inside", "through"], [PU, PU, PU],
      "The short path pins near.",
      "house_near_school"),
    pp("among", 2, 2, 5, "The single red tulip stands ___ the yellow tulips.",
      ["among", "far from", "above", "outside"], [PU, PU, PU],
      "Several yellow tulips surround the red one, which pins among.",
      "red_tulip_among_yellow_tulips"),
    psf("around", 2, 2, 5, "The fence curves ___ the garden.",
      ["around", "through", "onto", "above"], [FS, FS, FS],
      "The fence encloses the garden.",
      "fence_around_garden"),
    psf("inside_outside", 2, 2, 5, "The children stay dry ___ the house.",
      ["inside", "outside", "under", "between"], [FS, FS, FS],
      "The house walls enclose the children while rain falls outdoors.",
      "children_inside_house_in_rain")
  ].map(item => {
    if (item.v >= 5) item.retention = true;
    return item;
  }).concat(freshPhaseItems)
};
