// Rhyming — v3 authored bank (wave W4, paired with cvc_short_vowels).
// L1 uses named picture choices with spoken-only fallback where no approved
// picture can carry the exact word. L2 uses spoken choices without labels.
// Both levels assess rhyme by sound. L2 adds longer rimes and odd-one-out sets.
// Every answer choice requires a recording so reading skill cannot substitute
// for, or prevent, demonstrating phonological awareness.
// Spec: docs/skills-assessment-rebuild/BLUEPRINTS_PHONOLOGICAL.md §3.

import { makeImageResolver } from "../lib.mjs";

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const sentenceCase = value => value ? `${value[0].toUpperCase()}${value.slice(1)}` : value;

const baseResolver = makeImageResolver(["rhyming", "digraphs", "blends", "long-vowels", "hfw", "cvc"]);

const resolver = word => ({
  tin: "/images/assessment/generated/phonics-quality/tin.webp",
  wig: "/images/assessment/generated/phonics-quality/wig.webp",
  dot: "/images/assessment/generated/phonics-quality/dot.webp",
  bun: "/images/assessment/generated/phonics-quality/bun.webp",
  peg: "/images/assessment/generated/phonics-quality/peg.webp"
}[word] || baseResolver(word));

// L1: picture cards with a spoken anchor.
const rmp = (u, lvl, ph, v, anchor, cards, keyWord, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "RHYME_MATCH_PICTURE",
  prompt: "Which word rhymes with the word you hear?",
  spoken: `${sentenceCase(anchor)}. Which word rhymes with it?`,
  cards,
  choices: cards.map(w => (w === keyWord ? K(w) : P(w, rationales[w]))),
  media: "image-required",
  evidenceModality: "audio+image",
  constructClaim: "spoken_rhyme_discrimination",
  hideWrittenLabels: true,
  target: anchor,
  note
});

// L2: spoken choices. The renderer provides numbered replay/select cards.
const rfr = (u, lvl, ph, v, anchor, words, keyWord, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "READ_FIND_RHYME",
  prompt: "Which word rhymes with the word you hear?",
  spoken: `${sentenceCase(anchor)}. Which word rhymes with it?`,
  choices: words.map(w => (w === keyWord ? K(w) : P(w, rationales[w]))),
  media: "audio-required",
  evidenceModality: "audio",
  constructClaim: "spoken_rhyme_discrimination",
  hideWrittenLabels: true,
  target: anchor,
  note
});

const odd = (u, lvl, ph, v, words, keyWord, note = "") => ({
  u, lvl, ph, v, fmt: "RHYME_ODD_ONE_OUT",
  prompt: "Which word does NOT rhyme with the others?",
  spoken: "Which word does not rhyme with the others?",
  choices: words.map(w => (w === keyWord ? K(w) : P(w, "D-RIME-NEAR"))),
  media: "audio-required",
  evidenceModality: "audio",
  constructClaim: "spoken_rhyme_discrimination",
  hideWrittenLabels: true,
  note: note || "three spoken words share a rime; one has a different rime"
});

export default {
  skillId: "rhyming",
  skillName: "Rhyming",
  imageResolver: resolver,
  items: [
    // ======== L1 phase 1: at an ap am ag ad ed en et eg ig in ip it og ========
    rmp("at", 1, 1, 1, "cat", ["hat", "cake", "pot", "jam"], "hat",
      { cake: "D-ONSET", pot: "D-VOWEL", jam: "D-RIME-NEAR" },
      "cake starts like cat but does not rhyme, without asking a child to distinguish two pictures they may both call hat"),
    rmp("at", 1, 1, 2, "sat", ["mat","sun","nut","bag"], "mat", {"sun":"D-ONSET","nut":"D-VOWEL","bag":"D-RIME-NEAR"}),
    rmp("at", 1, 1, 3, "bat", ["rat", "bag", "pot", "ham"], "rat",
      { bag: "D-ONSET", pot: "D-VOWEL", ham: "D-RIME-NEAR" }),
    rmp("an", 1, 1, 1, "man", ["pan", "map", "pin", "jam"], "pan",
      { map: "D-ONSET", pin: "D-VOWEL", jam: "D-RIME-NEAR" }),
    rmp("an", 1, 1, 2, "can", ["fan", "cap", "nut", "bag"], "fan",
      { cap: "D-ONSET", nut: "D-VOWEL", bag: "D-RIME-NEAR" }),
    rmp("an", 1, 1, 3, "tan", ["van", "tie", "hen", "rat"], "van",
      { tie: "D-ONSET", hen: "D-VOWEL", rat: "D-RIME-NEAR" }),
    rmp("ap", 1, 1, 1, "cap", ["map", "cat", "cup", "jam"], "map",
      { cat: "D-ONSET", cup: "D-VOWEL", jam: "D-RIME-NEAR" }),
    rmp("ap", 1, 1, 2, "map", ["cap", "mat", "mop", "bag"], "cap",
      { mat: "D-ONSET", mop: "D-VOWEL", bag: "D-RIME-NEAR" }),
    rmp("ap", 1, 1, 3, "lap", ["cap","leg","hen","ham"], "cap", {"leg":"D-ONSET","hen":"D-ONSET","ham":"D-RIME-NEAR"}),
    rmp("am", 1, 1, 1, "ham", ["jam", "hat", "drum", "bag"], "jam",
      { hat: "D-ONSET", drum: "D-VOWEL", bag: "D-RIME-NEAR" }),
    rmp("am", 1, 1, 2, "ram", ["ham", "rat", "mug", "cap"], "ham",
      { rat: "D-ONSET", mug: "D-VOWEL", cap: "D-RIME-NEAR" }),
    rmp("am", 1, 1, 3, "jam", ["ham","jug","mug","bat"], "ham", {"jug":"D-ONSET","mug":"D-VOWEL","bat":"D-RIME-NEAR"}),
    rmp("ag", 1, 1, 1, "bag", ["flag", "bat", "bug", "map"], "flag",
      { bat: "D-ONSET", bug: "D-VOWEL", map: "D-RIME-NEAR" }),
    rmp("ag", 1, 1, 2, "rag", ["bag", "rat", "leg", "jam"], "bag",
      { rat: "D-ONSET", leg: "D-VOWEL", jam: "D-RIME-NEAR" }),
    rmp("ag", 1, 1, 3, "tag", ["flag", "tie", "dog", "ham"], "flag",
      { tie: "D-ONSET", dog: "D-VOWEL", ham: "D-RIME-NEAR" }),
    rmp("ub", 1, 1, 1, "cub", ["tub", "cup", "bed", "mug"], "tub",
      { cup: "D-ONSET", bed: "D-VOWEL", mug: "D-RIME-NEAR" },
      "a concrete tub replaces the pad/notepad naming ambiguity"),
    rmp("ub", 1, 1, 2, "rub", ["tub","rat","dog","sun"], "tub", {"rat":"D-ONSET","dog":"D-VOWEL","sun":"D-RIME-NEAR"},
      "a familiar tub picture supports a fresh spoken anchor; picture reuse is not counted as a new visual stimulus"),
    rmp("ub", 1, 1, 3, "sub", ["tub", "sun", "pig", "nut"], "tub",
      { sun: "D-ONSET", pig: "D-VOWEL", nut: "D-RIME-NEAR" }),
    rmp("ed", 1, 1, 1, "red", ["bed","rat","bag","hen"], "bed", {"rat":"D-ONSET","bag":"D-VOWEL","hen":"D-RIME-NEAR"}),
    rmp("ed", 1, 1, 2, "fed", ["sled","fan","mud","pen"], "sled", {"fan":"D-ONSET","mud":"D-VOWEL","pen":"D-RIME-NEAR"}),
    rmp("ed", 1, 1, 3, "wed", ["bed","web","bag","pen"], "bed", {"web":"D-ONSET","bag":"D-VOWEL","pen":"D-RIME-NEAR"}),
    rmp("en", 1, 1, 1, "den", ["hen", "dog", "pin", "bed"], "hen",
      { dog: "D-ONSET", pin: "D-VOWEL", bed: "D-RIME-NEAR" }),
    rmp("en", 1, 1, 2, "men", ["pen", "meat", "sun", "bed"], "pen",
      { meat: "D-ONSET", sun: "D-VOWEL", bed: "D-RIME-NEAR" }),
    rmp("en", 1, 1, 3, "ten", ["hen","tent","nut","web"], "hen", {"tent":"D-ONSET","nut":"D-VOWEL","web":"D-RIME-NEAR"}),
    rmp("et", 1, 1, 1, "pet", ["net", "pen", "nut", "leg"], "net",
      { pen: "D-ONSET", nut: "D-VOWEL", leg: "D-RIME-NEAR" }),
    rmp("et", 1, 1, 2, "wet", ["net","web","nut","hen"], "net", {"web":"D-ONSET","nut":"D-VOWEL","hen":"D-RIME-NEAR"}),
    rmp("et", 1, 1, 3, "set", ["net","sun","cup","egg"], "net", {"sun":"D-ONSET","cup":"D-RIME-NEAR","egg":"D-RIME-NEAR"}),
    rmp("eg", 1, 1, 1, "peg", ["leg", "pen", "bag", "hen"], "leg",
      { pen: "D-ONSET", bag: "D-VOWEL", hen: "D-RIME-NEAR" }),
    rmp("eg", 1, 1, 2, "leg", ["egg","lamp","bug","pen"], "egg", {"lamp":"D-ONSET","bug":"D-VOWEL","pen":"D-RIME-NEAR"}),
    rmp("eg", 1, 1, 3, "leg", ["peg","lamp","log","net"], "peg", {"lamp":"D-ONSET","log":"D-VOWEL","net":"D-RIME-NEAR"}),
    rmp("ig", 1, 1, 1, "fig", ["pig", "fish", "dog", "pin"], "pig",
      { fish: "D-ONSET", dog: "D-VOWEL", pin: "D-RIME-NEAR" }),
    rmp("ig", 1, 1, 2, "twig", ["wig","tent","bug","web"], "wig", {"tent":"D-ONSET","bug":"D-VOWEL","web":"D-RIME-NEAR"}),
    rmp("ig", 1, 1, 3, "jig", ["pig","jam","log","lid"], "pig", {"jam":"D-ONSET","log":"D-VOWEL","lid":"D-RIME-NEAR"}),
    rmp("in", 1, 1, 1, "win", ["pin","web","nut","pig"], "pin", {"web":"D-ONSET","nut":"D-VOWEL","pig":"D-RIME-NEAR"}),
    rmp("in", 1, 1, 2, "pin", ["tin","pig","pen","lid"], "tin", {"pig":"D-ONSET","pen":"D-VOWEL","lid":"D-RIME-NEAR"}),
    rmp("in", 1, 1, 3, "chin", ["pin","chick","map","lid"], "pin", {"chick":"D-ONSET","map":"D-VOWEL","lid":"D-RIME-NEAR"}),
    rmp("ip", 1, 1, 1, "dip", ["ship", "dog", "cup", "pin"], "ship",
      { dog: "D-ONSET", cup: "D-VOWEL", pin: "D-RIME-NEAR" }),
    rmp("ip", 1, 1, 2, "rip", ["ship","ring","mop","pig"], "ship", {"ring":"D-ONSET","mop":"D-VOWEL","pig":"D-RIME-NEAR"}),
    rmp("ip", 1, 1, 3, "lip", ["ship","lion","pot","leg"], "ship", {"lion":"D-ONSET","pot":"D-VOWEL","leg":"D-RIME-NEAR"}),
    rmp("ock", 1, 1, 1, "dock", ["clock", "dog", "hat", "pot"], "clock",
      { dog: "D-ONSET", hat: "D-VOWEL", pot: "D-RIME-NEAR" },
      "the isolated clock removes the pit-versus-hole naming ambiguity"),
    rmp("ock", 1, 1, 2, "lock", ["sock","lamp","bed","pot"], "sock", {"lamp":"D-ONSET","bed":"D-VOWEL","pot":"D-RIME-NEAR"}),
    rmp("ock", 1, 1, 3, "sock", ["rock","sun","bed","pot"], "rock", {"sun":"D-ONSET","bed":"D-VOWEL","pot":"D-RIME-NEAR"}),
    rmp("og", 1, 1, 1, "fog", ["dog", "fox", "bag", "mop"], "dog",
      { fox: "D-ONSET", bag: "D-VOWEL", mop: "D-RIME-NEAR" }),
    rmp("og", 1, 1, 2, "jog", ["log","jam","leg","pot"], "log", {"jam":"D-ONSET","leg":"D-VOWEL","pot":"D-RIME-NEAR"}),
    rmp("og", 1, 1, 3, "hog", ["frog","hen","nut","pot"], "frog", {"hen":"D-ONSET","nut":"D-VOWEL","pot":"D-RIME-NEAR"}),

    // ======== L1 phase 2: op ot ug un up ut ========
    rmp("op", 1, 2, 1, "pop", ["mop", "pot", "map", "log"], "mop",
      { pot: "D-ONSET", map: "D-VOWEL", log: "D-RIME-NEAR" }),
    rmp("op", 1, 2, 2, "drop", ["mop","drum","cup","dog"], "mop", {"drum":"D-ONSET","cup":"D-VOWEL","dog":"D-RIME-NEAR"}),
    rmp("op", 1, 2, 3, "stop", ["mop", "star", "cap", "pot"], "mop",
      { star: "D-ONSET", cap: "D-VOWEL", pot: "D-RIME-NEAR" },
      "key avoids top — sTOP contains it whole, which would hand the scanner a 3-chunk"),
    rmp("ot", 1, 2, 1, "not", ["pot", "nut", "hat", "dog"], "pot",
      { nut: "D-ONSET", hat: "D-VOWEL", dog: "D-RIME-NEAR" }),
    rmp("ot", 1, 2, 2, "got", ["dot","goat","hat","log"], "dot", {"goat":"D-ONSET","hat":"D-VOWEL","log":"D-RIME-NEAR"}),
    rmp("ot", 1, 2, 3, "lot", ["pot","log","pig","net"], "pot", {"log":"D-ONSET","pig":"D-RIME-NEAR","net":"D-RIME-NEAR"}),
    rmp("ug", 1, 2, 1, "tug", ["bug","tub","bag","sun"], "bug", {"tub":"D-ONSET","bag":"D-VOWEL","sun":"D-RIME-NEAR"}),
    rmp("ug", 1, 2, 2, "dug", ["bug", "duck", "leg", "cup"], "bug",
      { duck: "D-ONSET", leg: "D-VOWEL", cup: "D-RIME-NEAR" }),
    rmp("ug", 1, 2, 3, "hug", ["mug", "hat", "dog", "sun"], "mug",
      { hat: "D-ONSET", dog: "D-VOWEL", sun: "D-RIME-NEAR" }),
    rmp("un", 1, 2, 1, "fun", ["sun","fan","pin","mug"], "sun", {"fan":"D-ONSET","pin":"D-VOWEL","mug":"D-RIME-NEAR"}),
    rmp("un", 1, 2, 2, "bun", ["sun","bug","hen","cup"], "sun", {"bug":"D-ONSET","hen":"D-VOWEL","cup":"D-RIME-NEAR"}),
    rmp("un", 1, 2, 3, "run", ["bun","rat","map","mug"], "bun", {"rat":"D-ONSET","map":"D-VOWEL","mug":"D-RIME-NEAR"}),
    rmp("up", 1, 2, 1, "pup", ["cup","pin","mop","bug"], "cup", {"pin":"D-ONSET","mop":"D-VOWEL","bug":"D-RIME-NEAR"}),
    {
      ...rmp("up", 1, 2, 2, "cup", ["pup","cap","mug","sun"], "pup", {"cap":"D-VOWEL","mug":"D-RIME-NEAR","sun":"D-RIME-NEAR"},
        "spoken choices preserve the simple CVC rhyme contrast without relying on an unreviewed puppy picture"),
      cards: undefined,
      media: "audio-required",
      evidenceModality: "audio"
    },
    rmp("up", 1, 2, 3, "up", ["cup","umbrella","cap","mud"], "cup", {"umbrella":"D-ONSET","cap":"D-VOWEL","mud":"D-RIME-NEAR"}),
    rmp("ut", 1, 2, 1, "shut", ["nut", "ship", "pot", "bug"], "nut",
      { ship: "D-ONSET", pot: "D-VOWEL", bug: "D-RIME-NEAR" }),
    rmp("ut", 1, 2, 2, "but", ["nut","bug","hat","sun"], "nut", {"bug":"D-ONSET","hat":"D-VOWEL","sun":"D-RIME-NEAR"}),
    rmp("ut", 1, 2, 3, "cut", ["nut", "cup", "net", "mug"], "nut",
      { cup: "D-ONSET", net: "D-VOWEL", mug: "D-RIME-NEAR" },
      "the directly nameable nut card removes the action-picture naming demand; labels remain hidden"),

    // ======== L2 phase 1: ing ang ong ink ock ack ick ill all ell ash ish ========
    rfr("ing", 2, 1, 1, "sing", ["ring", "sink", "sang", "rung"], "ring",
      { sink: "D-PATTERN-TRAP", sang: "D-VOWEL", rung: "D-VOWEL" },
      "sink is the near-family trap AND the scanner tie (sin/sing)"),
    rfr("ing", 2, 1, 2, "king", ["wing", "kind", "wink", "sang"], "wing",
      { kind: "D-PATTERN-TRAP", wink: "D-PATTERN-TRAP", sang: "D-VOWEL" }),
    odd("ing", 2, 1, 3, ["sing", "ring", "king", "jam"], "jam"),
    rfr("ang", 2, 1, 1, "bang", ["hang", "band", "hung", "ring"], "hang",
      { band: "D-PATTERN-TRAP", hung: "D-VOWEL", ring: "D-RIME-NEAR" }),
    rfr("ang", 2, 1, 2, "sang", ["fang", "sand", "song", "fan"], "fang",
      { sand: "D-PATTERN-TRAP", song: "D-VOWEL", fan: "D-DEVELOPMENTAL" },
      "fan drops the g — the cluster-reduction error; sand ties the san-chunk"),
    odd("ang", 2, 1, 3, ["bang", "sang", "hang", "cup"], "cup"),
    rfr("ong", 2, 1, 1, "song", ["long", "son", "sang", "lung"], "long",
      { son: "D-PATTERN-TRAP", sang: "D-VOWEL", lung: "D-RIME-NEAR" }),
    rfr("ong", 2, 1, 2, "long", ["gong","lost","lung","log"], "gong", {"lost":"D-ONSET","lung":"D-VOWEL","log":"D-DEVELOPMENTAL"}),
    odd("ong", 2, 1, 3, ["song", "long", "gong", "map"], "map"),
    rfr("ink", 2, 1, 1, "pink", ["sink", "pin", "sank", "ring"], "sink",
      { pin: "D-PATTERN-TRAP", sank: "D-VOWEL", ring: "D-RIME-NEAR" },
      "pin is the classic near-family answer — it ties the pin/pink chunk"),
    rfr("ink", 2, 1, 2, "wink", ["drink", "wind", "wing", "sank"], "drink",
      { wind: "D-PATTERN-TRAP", wing: "D-RIME-NEAR", sank: "D-VOWEL" }),
    odd("ink", 2, 1, 3, ["pink", "sink", "wink", "leg"], "leg"),
    rfr("ock", 2, 1, 1, "sock", ["rock","soft","sack","rug"], "rock", {"soft":"D-ONSET","sack":"D-VOWEL","rug":"D-RIME-NEAR"}),
    rfr("ock", 2, 1, 2, "lock", ["sock","lost","lick","log"], "sock", {"lost":"D-ONSET","lick":"D-VOWEL","log":"D-DEVELOPMENTAL"}),
    odd("ock", 2, 1, 3, ["sock", "rock", "lock", "pan"], "pan"),
    rfr("ack", 2, 1, 1, "back", ["sack","bag","sock","bat"], "sack", {"bag":"D-ONSET","sock":"D-VOWEL","bat":"D-RIME-NEAR"}),
    rfr("ack", 2, 1, 2, "pack", ["black","pan","pick","pat"], "black", {"pan":"D-ONSET","pick":"D-VOWEL","pat":"D-RIME-NEAR"}),
    odd("ack", 2, 1, 3, ["back", "sack", "pack", "mug"], "mug"),
    rfr("ick", 2, 1, 1, "stick", ["brick", "stiff", "stack", "bit"], "brick",
      { stiff: "D-PATTERN-TRAP", stack: "D-VOWEL", bit: "D-RIME-NEAR" }),
    rfr("ick", 2, 1, 2, "kick", ["lick","king","lock","kit"], "lick", {"king":"D-ONSET","lock":"D-VOWEL","kit":"D-DEVELOPMENTAL"}),
    odd("ick", 2, 1, 3, ["stick", "brick", "kick", "sun"], "sun"),
    rfr("ill", 2, 1, 1, "hill", ["pill","hip","pull","pin"], "pill", {"hip":"D-ONSET","pull":"D-VOWEL","pin":"D-RIME-NEAR"}),
    rfr("ill", 2, 1, 2, "mill", ["bill", "milk", "ball", "big"], "bill",
      { milk: "D-PATTERN-TRAP", ball: "D-VOWEL", big: "D-RIME-NEAR" },
      "milk ties the mil-chunk — the l-cluster neighbour"),
    odd("ill", 2, 1, 3, ["hill", "mill", "bill", "fox"], "fox"),
    rfr("all", 2, 1, 1, "ball", ["tall", "bald", "tell", "tap"], "tall",
      { bald: "D-PATTERN-TRAP", tell: "D-VOWEL", tap: "D-RIME-NEAR" }),
    rfr("all", 2, 1, 2, "wall", ["small", "walk", "well", "smell"], "small",
      { walk: "D-PATTERN-TRAP", well: "D-VOWEL", smell: "D-RIME-NEAR" },
      "walk ties the wal-chunk — same start, no rhyme"),
    odd("all", 2, 1, 3, ["ball", "tall", "fall", "pig"], "pig"),
    rfr("ell", 2, 1, 1, "bell", ["shell", "belt", "ball", "shop"], "shell",
      { belt: "D-PATTERN-TRAP", ball: "D-VOWEL", shop: "D-RIME-NEAR" }),
    rfr("ell", 2, 1, 2, "well", ["spell","wet","will","spot"], "spell", {"wet":"D-ONSET","will":"D-VOWEL","spot":"D-RIME-NEAR"}),
    odd("ell", 2, 1, 3, ["bell", "well", "shell", "cat"], "cat"),
    rfr("ash", 2, 1, 1, "cash", ["dash", "cast", "dish", "can"], "dash",
      { cast: "D-PATTERN-TRAP", dish: "D-VOWEL", can: "D-RIME-NEAR" }),
    rfr("ash", 2, 1, 2, "splash", ["crash", "splat", "crush", "cap"], "crash",
      { splat: "D-PATTERN-TRAP", crush: "D-VOWEL", cap: "D-RIME-NEAR" },
      "splat out-chunks the key (spla) — the scanner falls into the trap"),
    odd("ash", 2, 1, 3, ["dash", "cash", "splash", "bun"], "bun"),
    rfr("ish", 2, 1, 1, "wish", ["dish", "whisk", "dash", "dip"], "dish",
      { whisk: "D-PATTERN-TRAP", dash: "D-VOWEL", dip: "D-DEVELOPMENTAL" }),
    rfr("ish", 2, 1, 2, "fish", ["swish", "fist", "fresh", "swim"], "swish",
      { fist: "D-PATTERN-TRAP", fresh: "D-VOWEL", swim: "D-RIME-NEAR" }),
    odd("ish", 2, 1, 3, ["dish", "wish", "swish", "log"], "log"),

    // ======== L2 phase 2: uck ake ame ide ight oat eep ouse ird urn ar or ========
    rfr("uck", 2, 2, 1, "duck", ["truck","dust","deck","dug"], "truck", {"dust":"D-ONSET","deck":"D-VOWEL","dug":"D-DEVELOPMENTAL"}),
    rfr("uck", 2, 2, 2, "luck", ["stuck","lump","lick","cup"], "stuck", {"lump":"D-ONSET","lick":"D-VOWEL","cup":"D-RIME-NEAR"}),
    odd("uck", 2, 2, 3, ["duck", "truck", "stuck", "ham"], "ham"),
    rfr("ake", 2, 2, 1, "cake", ["lake","cap","like","can"], "lake", {"cap":"D-ONSET","like":"D-VOWEL","can":"D-RIME-NEAR"}),
    rfr("ake", 2, 2, 2, "snake", ["bake", "snack", "bike", "bag"], "bake",
      { snack: "D-PATTERN-TRAP", bike: "D-VOWEL", bag: "D-RIME-NEAR" },
      "snack ties the sna-chunk — short-vowel cousin of the anchor"),
    odd("ake", 2, 2, 3, ["cake", "lake", "bake", "fog"], "fog"),
    rfr("ame", 2, 2, 1, "game", ["name","gap","time","nap"], "name", {"gap":"D-ONSET","time":"D-VOWEL","nap":"D-RIME-NEAR"}),
    rfr("ame", 2, 2, 2, "same", ["flame","sand","flag","time"], "flame", {"sand":"D-ONSET","flag":"D-RIME-NEAR","time":"D-VOWEL"}),
    odd("ame", 2, 2, 3, ["game", "name", "same", "zip"], "zip"),
    rfr("ide", 2, 2, 1, "ride", ["hide","rib","made","hid"], "hide", {"rib":"D-ONSET","made":"D-VOWEL","hid":"D-DEVELOPMENTAL"}),
    rfr("ide", 2, 2, 2, "side", ["wide","sit","wade","win"], "wide", {"sit":"D-ONSET","wade":"D-VOWEL","win":"D-RIME-NEAR"}),
    odd("ide", 2, 2, 3, ["ride", "hide", "wide", "hen"], "hen"),
    rfr("ight", 2, 2, 1, "light", ["kite", "lit", "lift", "kit"], "kite",
      { lit: "D-DEVELOPMENTAL", lift: "D-PATTERN-TRAP", kit: "D-DEVELOPMENTAL" },
      "cross-spelling rhyme: kite shares no chunk with light, so the scanner reads nothing — the construct is sound, not letters"),
    rfr("ight", 2, 2, 2, "night", ["white", "wit", "net", "nut"], "white",
      { wit: "D-PATTERN-TRAP", net: "D-VOWEL", nut: "D-VOWEL" },
      "cross-spelling rhyme again; wit ties the with-overlap"),
    odd("ight", 2, 2, 3, ["light", "night", "right", "lamp"], "lamp"),
    rfr("oat", 2, 2, 1, "boat", ["goat", "board", "got", "bag"], "goat",
      { board: "D-PATTERN-TRAP", got: "D-DEVELOPMENTAL", bag: "D-RIME-NEAR" },
      "got is the short sibling; board ties the boa-chunk"),
    rfr("oat", 2, 2, 2, "coat", ["float", "coach", "cot", "fan"], "float",
      { coach: "D-PATTERN-TRAP", cot: "D-DEVELOPMENTAL", fan: "D-RIME-NEAR" }),
    odd("oat", 2, 2, 3, ["boat", "coat", "goat", "rug"], "rug"),
    rfr("eep", 2, 2, 1, "sheep", ["deep", "sheet", "ship", "den"], "deep",
      { sheet: "D-PATTERN-TRAP", ship: "D-DEVELOPMENTAL", den: "D-RIME-NEAR" },
      "sheet out-chunks the key (shee) — the scanner falls into the trap"),
    rfr("eep", 2, 2, 2, "jeep", ["sleep","jet","slip","jam"], "sleep", {"jet":"D-ONSET","slip":"D-DEVELOPMENTAL","jam":"D-RIME-NEAR"}),
    odd("eep", 2, 2, 3, ["sheep", "jeep", "deep", "mat"], "mat"),
    rfr("ouse", 2, 2, 1, "house", ["mouse","horse","moss","mouth"], "mouse", {"horse":"D-ONSET","moss":"D-RIME-NEAR","mouth":"D-RIME-NEAR"}),
    rfr("ouse", 2, 2, 2, "mouse", ["house","mice","moose","mop"], "house", {"mice":"D-ONSET","moose":"D-RIME-NEAR","mop":"D-RIME-NEAR"}),
    rfr("ouse", 2, 2, 3, "treehouse", ["mouse","treetop","mouth","moss"], "mouse", {"treetop":"D-ONSET","mouth":"D-RIME-NEAR","moss":"D-VOWEL"}, "the final syllable of treehouse rhymes with mouse; blouse is avoided because its final consonant varies by accent"),
    rfr("ird", 2, 2, 1, "bird", ["third","bib","bin","bad"], "third", {"bib":"D-ONSET","bin":"D-RIME-NEAR","bad":"D-VOWEL"}),
    rfr("ird", 2, 2, 2, "third", ["herd", "this", "thin", "hen"], "herd",
      { this: "D-PATTERN-TRAP", thin: "D-RIME-NEAR", hen: "D-VOWEL" },
      "cross-spelling rhyme (ird/erd); this ties the thi-chunk"),
    odd("ird", 2, 2, 3, ["bird", "third", "herd", "cap"], "cap"),
    rfr("urn", 2, 2, 1, "burn", ["turn","bud","torn","tub"], "turn", {"bud":"D-ONSET","torn":"D-VOWEL","tub":"D-RIME-NEAR"}),
    rfr("urn", 2, 2, 2, "turn", ["fern","tub","fun","fan"], "fern", {"tub":"D-ONSET","fun":"D-RIME-NEAR","fan":"D-VOWEL"}),
    odd("urn", 2, 2, 3, ["burn", "turn", "churn", "dog"], "dog"),
    rfr("ar", 2, 2, 1, "car", ["star", "cart", "care", "stop"], "star",
      { cart: "D-PATTERN-TRAP", care: "D-VOWEL", stop: "D-RIME-NEAR" },
      "care is one silent e from the anchor; cart out-chunks the key"),
    rfr("ar", 2, 2, 2, "jar", ["far", "jam", "fur", "jet"], "far",
      { jam: "D-PATTERN-TRAP", fur: "D-VOWEL", jet: "D-RIME-NEAR" }),
    odd("ar", 2, 2, 3, ["car", "star", "jar", "hut"], "hut"),
    rfr("or", 2, 2, 1, "corn", ["horn", "cord", "barn", "hen"], "horn",
      { cord: "D-PATTERN-TRAP", barn: "D-VOWEL", hen: "D-RIME-NEAR" },
      "barn is the ar/or vowel confusion; cord ties the cor-chunk"),
    rfr("or", 2, 2, 2, "fort", ["short", "fork", "shirt", "fog"], "short",
      { fork: "D-PATTERN-TRAP", shirt: "D-VOWEL", fog: "D-RIME-NEAR" }),
    odd("or", 2, 2, 3, ["corn", "horn", "torn", "bed"], "bed"),

    // Unheard anchors and rhyme groups; spoken-only choices need no new art.
    { ...rmp("ap", 1, 1, 20, "flap", ["map", "flag", "mop", "ham"], "map", { flag: "D-ONSET", mop: "D-VOWEL", ham: "D-RIME-NEAR" }),
      retention: true, cards: undefined, media: "audio-required", evidenceModality: "audio",
      note: "map alone shares /ap/; flag retains the initial blend, mop changes the vowel, ham changes the coda" },
    { ...rmp("ed", 1, 1, 20, "shed", ["bed", "ship", "mud", "hen"], "bed", { ship: "D-ONSET", mud: "D-VOWEL", hen: "D-RIME-NEAR" }),
      retention: true, cards: undefined, media: "audio-required", evidenceModality: "audio",
      note: "bed shares /ed/; ship has the same onset, mud keeps d but changes the vowel, hen changes the coda" },
    { ...rmp("un", 1, 2, 20, "spun", ["bun", "spoon", "pen", "cup"], "bun", { spoon: "D-ONSET", pen: "D-VOWEL", cup: "D-RIME-NEAR" }),
      retention: true, cards: undefined, media: "audio-required", evidenceModality: "audio",
      note: "bun alone shares /un/; spoon shares the initial blend, pen changes the vowel, cup changes the coda" },
    { ...rfr("ill", 2, 1, 20, "spill", ["pill", "spin", "spell", "pit"], "pill", { spin: "D-ONSET", spell: "D-VOWEL", pit: "D-RIME-NEAR" }), retention: true,
      note: "pill preserves the complete rime; spin keeps sp, spell contrasts e/i, and pit changes the final consonant" },
    { ...rfr("ide", 2, 2, 20, "wide", ["slide", "wind", "slid", "web"], "slide", { wind: "D-ONSET", slid: "D-VOWEL", web: "D-ONSET" }), retention: true,
      note: "slide alone shares /ide/; either familiar pronunciation of wind still contains a nonmatching final n+d cluster" },
    { ...odd("ash", 2, 1, 20, ["crash", "flash", "splash", "fish"], "fish", "three blend-onset words share /ash/; fish changes the medial vowel while retaining sh"), retention: true },

    // ======== Retention reserve (form R) ========
    rmp("at", 1, 1, 7, "rat", ["bat", "rose", "pot", "jam"], "bat",
      { rose: "D-ONSET", pot: "D-VOWEL", jam: "D-RIME-NEAR" }),
    rmp("og", 1, 1, 7, "log", ["dog", "lock", "bug", "mop"], "dog",
      { lock: "D-ONSET", bug: "D-VOWEL", mop: "D-RIME-NEAR" }),
    rmp("en", 1, 1, 7, "pen", ["hen","web","pin","net"], "hen", {"web":"D-RIME-NEAR","pin":"D-VOWEL","net":"D-RIME-NEAR"}),
    rmp("ug", 1, 2, 7, "jug", ["bug","web","bag","cup"], "bug", {"web":"D-VOWEL","bag":"D-VOWEL","cup":"D-RIME-NEAR"}),
    rmp("ip", 1, 1, 7, "tip", ["ship", "tie", "cap", "leg"], "ship",
      { tie: "D-ONSET", cap: "D-VOWEL", leg: "D-RIME-NEAR" }),
    rfr("ing", 2, 1, 7, "ring", ["sing", "rink", "rung", "rat"], "sing",
      { rink: "D-PATTERN-TRAP", rung: "D-VOWEL", rat: "D-RIME-NEAR" }),
    rfr("ake", 2, 2, 7, "bake", ["snake","bag","snack","bin"], "snake", {"bag":"D-ONSET","snack":"D-PATTERN-TRAP","bin":"D-RIME-NEAR"}),
    odd("ell", 2, 1, 7, ["shell", "spell", "yell", "tub"], "tub"),
    rfr("oat", 2, 2, 7, "goat", ["coat", "goal", "got", "cup"], "coat",
      { goal: "D-PATTERN-TRAP", got: "D-DEVELOPMENTAL", cup: "D-RIME-NEAR" }),
    odd("ink", 2, 1, 7, ["sink", "drink", "pink", "bat"], "bat")
  ].map(item => {
    if (item.v >= 7) item.retention = true;
    return item;
  })
};
