// Rhyming — v3 authored bank (wave W4, paired with cvc_short_vowels).
// The audit's worst construct fault (656 one-format items solvable by -at
// chunk-matching, 222 duplicate groups, audio suppressed). The v3 rebuild:
//   L1 (RHYME_MATCH_PICTURE, 21 CVC families): anchor is spoken/printed, the
//     four picture cards ALWAYS include the anchor's onset-mate (cap for cat)
//     or a wh- decoy — either ties the letter-chunk overlap, so a print scanner
//     can never separate the rhyming key from the trap. The onset-mate IS the
//     classic rhyme misconception (same start ≠ rhyme), so the anti-scanner
//     card and the pedagogical trap are the same card.
//   L2 (READ_FIND_RHYME + RHYME_ODD_ONE_OUT, 24 harder families): RFR items
//     carry a near-family mate (sink for sing) or wh-/wit- decoy that ties or
//     beats the key's rime chunk; ight uses cross-spelling rhymes (light→kite)
//     which are chunk-null by construction; ouse (no clean tie) runs entirely
//     on ODD_ONE_OUT, where the scanner picks a RHYMER (a distractor), never
//     the odd key. Zero scanner leaks is the target, not the 25% gate ceiling.
// L1 is audio-first phonological evidence. Written labels stay hidden and the
// gate requires approved production word audio for every answer card.
// Spec: docs/skills-assessment-rebuild/BLUEPRINTS_PHONOLOGICAL.md §3.

import { makeImageResolver } from "../lib.mjs";

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const sentenceCase = value => value ? `${value[0].toUpperCase()}${value.slice(1)}` : value;

const resolver = makeImageResolver(["rhyming", "digraphs", "blends", "long-vowels", "hfw", "cvc"]);

// L1: picture cards, spoken/printed anchor.
const rmp = (u, lvl, ph, v, anchor, cards, keyWord, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "RHYME_MATCH_PICTURE",
  prompt: "Which word rhymes with the word you hear?",
  spoken: `${sentenceCase(anchor)}. Which word rhymes with it?`,
  cards,
  choices: cards.map(w => (w === keyWord ? K(w) : P(w, rationales[w]))),
  media: "image-required",
  evidenceModality: "audio+image",
  constructClaim: "spoken_rhyme_discrimination",
  hideWrittenLabels: true,
  target: anchor,
  note
});

// L2: printed words.
const rfr = (u, lvl, ph, v, anchor, words, keyWord, rationales, note = "") => ({
  u, lvl, ph, v, fmt: "READ_FIND_RHYME",
  prompt: `Which word rhymes with ${anchor}?`,
  spoken: `${sentenceCase(anchor)}. Which word rhymes with ${anchor}?`,
  choices: words.map(w => (w === keyWord ? K(w) : P(w, rationales[w]))),
  media: "text",
  target: anchor,
  note
});

const odd = (u, lvl, ph, v, words, keyWord, note = "") => ({
  u, lvl, ph, v, fmt: "RHYME_ODD_ONE_OUT",
  prompt: "Which word does NOT rhyme with the others?",
  spoken: "Which word does not rhyme with the others?",
  choices: words.map(w => (w === keyWord ? K(w) : P(w, "D-RIME-NEAR"))),
  media: "text",
  note: note || "the scanner's max-overlap pick is always a rhymer (a distractor), never the odd key"
});

export default {
  skillId: "rhyming",
  skillName: "Rhyming",
  imageResolver: resolver,
  items: [
    // ======== L1 phase 1: at an ap am ag ad ed en et eg ig in ip it og ========
    rmp("at", 1, 1, 1, "cat", ["hat", "cake", "pot", "jam"], "hat",
      { cake: "D-ONSET", pot: "D-VOWEL", jam: "D-RIME-NEAR" },
      "cake starts like cat but does not rhyme, without asking a child to distinguish two pictures they may both call hat"),
    rmp("at", 1, 1, 2, "sat", ["mat", "whale", "nut", "bag"], "mat",
      { whale: "D-PATTERN-TRAP", nut: "D-VOWEL", bag: "D-RIME-NEAR" }),
    rmp("at", 1, 1, 3, "bat", ["rat", "bag", "pot", "ham"], "rat",
      { bag: "D-ONSET", pot: "D-VOWEL", ham: "D-RIME-NEAR" }),
    rmp("an", 1, 1, 1, "man", ["pan", "map", "pin", "jam"], "pan",
      { map: "D-ONSET", pin: "D-VOWEL", jam: "D-RIME-NEAR" }),
    rmp("an", 1, 1, 2, "can", ["fan", "cap", "nut", "bag"], "fan",
      { cap: "D-ONSET", nut: "D-VOWEL", bag: "D-RIME-NEAR" }),
    rmp("an", 1, 1, 3, "tan", ["van", "tie", "hen", "rat"], "van",
      { tie: "D-ONSET", hen: "D-VOWEL", rat: "D-RIME-NEAR" }),
    rmp("ap", 1, 1, 1, "cap", ["map", "cat", "cup", "jam"], "map",
      { cat: "D-ONSET", cup: "D-VOWEL", jam: "D-RIME-NEAR" }),
    rmp("ap", 1, 1, 2, "map", ["cap", "mat", "mop", "bag"], "cap",
      { mat: "D-ONSET", mop: "D-VOWEL", bag: "D-RIME-NEAR" }),
    rmp("ap", 1, 1, 3, "lap", ["cap", "whale", "hop", "ham"], "cap",
      { whale: "D-PATTERN-TRAP", hop: "D-VOWEL", ham: "D-RIME-NEAR" }),
    rmp("am", 1, 1, 1, "ham", ["jam", "hat", "drum", "bag"], "jam",
      { hat: "D-ONSET", drum: "D-VOWEL", bag: "D-RIME-NEAR" }),
    rmp("am", 1, 1, 2, "ram", ["ham", "rat", "mug", "cap"], "ham",
      { rat: "D-ONSET", mug: "D-VOWEL", cap: "D-RIME-NEAR" }),
    rmp("am", 1, 1, 3, "jam", ["ham", "whale", "mug", "bat"], "ham",
      { whale: "D-PATTERN-TRAP", mug: "D-VOWEL", bat: "D-RIME-NEAR" }),
    rmp("ag", 1, 1, 1, "bag", ["flag", "bat", "bug", "map"], "flag",
      { bat: "D-ONSET", bug: "D-VOWEL", map: "D-RIME-NEAR" }),
    rmp("ag", 1, 1, 2, "rag", ["bag", "rat", "leg", "jam"], "bag",
      { rat: "D-ONSET", leg: "D-VOWEL", jam: "D-RIME-NEAR" }),
    rmp("ag", 1, 1, 3, "tag", ["flag", "tie", "dog", "ham"], "flag",
      { tie: "D-ONSET", dog: "D-VOWEL", ham: "D-RIME-NEAR" }),
    rmp("ub", 1, 1, 1, "cub", ["tub", "cup", "bed", "mug"], "tub",
      { cup: "D-ONSET", bed: "D-VOWEL", mug: "D-RIME-NEAR" },
      "a concrete tub replaces the pad/notepad naming ambiguity"),
    rmp("ub", 1, 1, 2, "rub", ["tub", "rat", "dog", "sun"], "tub",
      { rat: "D-ONSET", dog: "D-VOWEL", sun: "D-RIME-NEAR" }),
    rmp("ub", 1, 1, 3, "sub", ["tub", "sun", "pig", "nut"], "tub",
      { sun: "D-ONSET", pig: "D-VOWEL", nut: "D-RIME-NEAR" }),
    rmp("ed", 1, 1, 1, "red", ["bed", "whale", "bag", "hen"], "bed",
      { whale: "D-PATTERN-TRAP", bag: "D-VOWEL", hen: "D-RIME-NEAR" }),
    rmp("ed", 1, 1, 2, "fed", ["bed", "wheel", "mud", "pen"], "bed",
      { wheel: "D-PATTERN-TRAP", mud: "D-VOWEL", pen: "D-RIME-NEAR" }),
    rmp("ed", 1, 1, 3, "wed", ["bed", "web", "bag", "ten"], "bed",
      { web: "D-ONSET", bag: "D-VOWEL", ten: "D-RIME-NEAR" }),
    rmp("en", 1, 1, 1, "den", ["hen", "dog", "pin", "bed"], "hen",
      { dog: "D-ONSET", pin: "D-VOWEL", bed: "D-RIME-NEAR" }),
    rmp("en", 1, 1, 2, "men", ["pen", "meat", "sun", "bed"], "pen",
      { meat: "D-ONSET", sun: "D-VOWEL", bed: "D-RIME-NEAR" }),
    rmp("en", 1, 1, 3, "hen", ["ten", "wheel", "nut", "web"], "ten",
      { wheel: "D-PATTERN-TRAP", nut: "D-VOWEL", web: "D-RIME-NEAR" }),
    rmp("et", 1, 1, 1, "pet", ["net", "pen", "nut", "leg"], "net",
      { pen: "D-ONSET", nut: "D-VOWEL", leg: "D-RIME-NEAR" }),
    rmp("et", 1, 1, 2, "wet", ["net", "web", "nut", "hen"], "net",
      { web: "D-ONSET", nut: "D-VOWEL", hen: "D-RIME-NEAR" }),
    rmp("et", 1, 1, 3, "set", ["net", "whale", "cut", "egg"], "net",
      { whale: "D-PATTERN-TRAP", cut: "D-VOWEL", egg: "D-RIME-NEAR" }),
    rmp("eg", 1, 1, 1, "peg", ["leg", "pen", "bag", "hen"], "leg",
      { pen: "D-ONSET", bag: "D-VOWEL", hen: "D-RIME-NEAR" }),
    rmp("eg", 1, 1, 2, "leg", ["egg", "lamp", "bug", "ten"], "egg",
      { lamp: "D-ONSET", bug: "D-VOWEL", ten: "D-RIME-NEAR" }),
    rmp("eg", 1, 1, 3, "peg", ["egg", "whale", "log", "net"], "egg",
      { whale: "D-PATTERN-TRAP", log: "D-VOWEL", net: "D-RIME-NEAR" }),
    rmp("ig", 1, 1, 1, "fig", ["pig", "fish", "dog", "pin"], "pig",
      { fish: "D-ONSET", dog: "D-VOWEL", pin: "D-RIME-NEAR" }),
    rmp("ig", 1, 1, 2, "twig", ["pig", "whale", "bug", "web"], "pig",
      { whale: "D-PATTERN-TRAP", bug: "D-VOWEL", web: "D-RIME-NEAR" }),
    rmp("ig", 1, 1, 3, "jig", ["pig", "whale", "log", "lid"], "pig",
      { whale: "D-PATTERN-TRAP", log: "D-VOWEL", lid: "D-RIME-NEAR" }),
    rmp("in", 1, 1, 1, "win", ["pin", "whale", "nut", "pig"], "pin",
      { whale: "D-PATTERN-TRAP", nut: "D-VOWEL", pig: "D-RIME-NEAR" }),
    rmp("in", 1, 1, 2, "tin", ["pin", "tie", "pen", "lid"], "pin",
      { tie: "D-ONSET", pen: "D-VOWEL", lid: "D-RIME-NEAR" }),
    rmp("in", 1, 1, 3, "chin", ["pin", "chick", "map", "hit"], "pin",
      { chick: "D-ONSET", map: "D-VOWEL", hit: "D-RIME-NEAR" },
      "chick out-chunks the key on the anchor overlap — the scanner falls into the onset trap"),
    rmp("ip", 1, 1, 1, "dip", ["ship", "dog", "cup", "pin"], "ship",
      { dog: "D-ONSET", cup: "D-VOWEL", pin: "D-RIME-NEAR" }),
    rmp("ip", 1, 1, 2, "rip", ["ship", "ring", "mop", "sit"], "ship",
      { ring: "D-ONSET", mop: "D-VOWEL", sit: "D-RIME-NEAR" }),
    rmp("ip", 1, 1, 3, "lip", ["ship", "lion", "pot", "leg"], "ship",
      { lion: "D-ONSET", pot: "D-VOWEL", leg: "D-RIME-NEAR" }),
    rmp("ock", 1, 1, 1, "dock", ["clock", "dog", "hat", "pot"], "clock",
      { dog: "D-ONSET", hat: "D-VOWEL", pot: "D-RIME-NEAR" },
      "the isolated clock removes the pit-versus-hole naming ambiguity"),
    rmp("ock", 1, 1, 2, "lock", ["clock", "lamp", "bed", "pot"], "clock",
      { lamp: "D-ONSET", bed: "D-VOWEL", pot: "D-RIME-NEAR" }),
    rmp("ock", 1, 1, 3, "sock", ["clock", "sun", "bed", "pot"], "clock",
      { sun: "D-ONSET", bed: "D-VOWEL", pot: "D-RIME-NEAR" }),
    rmp("og", 1, 1, 1, "fog", ["dog", "fox", "bag", "mop"], "dog",
      { fox: "D-ONSET", bag: "D-VOWEL", mop: "D-RIME-NEAR" }),
    rmp("og", 1, 1, 2, "jog", ["log", "whale", "leg", "pot"], "log",
      { whale: "D-PATTERN-TRAP", leg: "D-VOWEL", pot: "D-RIME-NEAR" }),
    rmp("og", 1, 1, 3, "hog", ["frog", "hop", "nut", "pot"], "frog",
      { hop: "D-ONSET", nut: "D-VOWEL", pot: "D-RIME-NEAR" }),

    // ======== L1 phase 2: op ot ug un up ut ========
    rmp("op", 1, 2, 1, "pop", ["mop", "pot", "map", "log"], "mop",
      { pot: "D-ONSET", map: "D-VOWEL", log: "D-RIME-NEAR" }),
    rmp("op", 1, 2, 2, "drop", ["mop", "drum", "cup", "dog"], "mop",
      { drum: "D-ONSET", cup: "D-VOWEL", dog: "D-RIME-NEAR" }),
    rmp("op", 1, 2, 3, "stop", ["mop", "star", "cap", "pot"], "mop",
      { star: "D-ONSET", cap: "D-VOWEL", pot: "D-RIME-NEAR" },
      "key avoids top — sTOP contains it whole, which would hand the scanner a 3-chunk"),
    rmp("ot", 1, 2, 1, "not", ["pot", "nut", "hat", "dog"], "pot",
      { nut: "D-ONSET", hat: "D-VOWEL", dog: "D-RIME-NEAR" }),
    rmp("ot", 1, 2, 2, "got", ["pot", "goat", "hat", "log"], "pot",
      { goat: "D-ONSET", hat: "D-VOWEL", log: "D-RIME-NEAR" },
      "goat starts like got but does not rhyme — long-o against short-o"),
    rmp("ot", 1, 2, 3, "lot", ["pot", "log", "sit", "net"], "pot",
      { log: "D-ONSET", sit: "D-VOWEL", net: "D-RIME-NEAR" }),
    rmp("ug", 1, 2, 1, "tug", ["bug", "whale", "bag", "sun"], "bug",
      { whale: "D-PATTERN-TRAP", bag: "D-VOWEL", sun: "D-RIME-NEAR" }),
    rmp("ug", 1, 2, 2, "dug", ["bug", "duck", "leg", "cup"], "bug",
      { duck: "D-ONSET", leg: "D-VOWEL", cup: "D-RIME-NEAR" }),
    rmp("ug", 1, 2, 3, "hug", ["mug", "hat", "dog", "sun"], "mug",
      { hat: "D-ONSET", dog: "D-VOWEL", sun: "D-RIME-NEAR" }),
    rmp("un", 1, 2, 1, "fun", ["sun", "whale", "pin", "mug"], "sun",
      { whale: "D-PATTERN-TRAP", pin: "D-VOWEL", mug: "D-RIME-NEAR" }),
    rmp("un", 1, 2, 2, "bun", ["sun", "bug", "hen", "cut"], "sun",
      { bug: "D-ONSET", hen: "D-VOWEL", cut: "D-RIME-NEAR" }),
    rmp("un", 1, 2, 3, "run", ["sun", "whale", "map", "mug"], "sun",
      { whale: "D-PATTERN-TRAP", map: "D-VOWEL", mug: "D-RIME-NEAR" },
      "the spoken action anchor avoids a subjective still while the sun card is directly nameable"),
    rmp("up", 1, 2, 1, "pup", ["cup", "whale", "mop", "bug"], "cup",
      { whale: "D-PATTERN-TRAP", mop: "D-VOWEL", bug: "D-RIME-NEAR" }),
    rmp("up", 1, 2, 2, "up", ["cup", "cap", "mug", "sun"], "cup",
      { cap: "D-VOWEL", mug: "D-RIME-NEAR", sun: "D-RIME-NEAR" },
      "the spoken anchor removes a subjective action picture while keeping one clear rhyme"),
    rmp("up", 1, 2, 3, "pup", ["cup", "whale", "cap", "mud"], "cup",
      { whale: "D-PATTERN-TRAP", cap: "D-VOWEL", mud: "D-RIME-NEAR" }),
    rmp("ut", 1, 2, 1, "shut", ["nut", "ship", "pot", "bug"], "nut",
      { ship: "D-ONSET", pot: "D-VOWEL", bug: "D-RIME-NEAR" }),
    rmp("ut", 1, 2, 2, "but", ["nut", "bug", "hat", "sun"], "nut",
      { bug: "D-ONSET", hat: "D-VOWEL", sun: "D-RIME-NEAR" }),
    rmp("ut", 1, 2, 3, "shut", ["nut", "ship", "net", "mug"], "nut",
      { ship: "D-ONSET", net: "D-VOWEL", mug: "D-RIME-NEAR" },
      "the directly nameable nut card removes the action-picture naming demand; labels remain hidden"),

    // ======== L2 phase 1: ing ang ong ink ock ack ick ill all ell ash ish ========
    rfr("ing", 2, 1, 1, "sing", ["ring", "sink", "sang", "rung"], "ring",
      { sink: "D-PATTERN-TRAP", sang: "D-VOWEL", rung: "D-VOWEL" },
      "sink is the near-family trap AND the scanner tie (sin/sing)"),
    rfr("ing", 2, 1, 2, "king", ["wing", "kind", "wink", "sang"], "wing",
      { kind: "D-PATTERN-TRAP", wink: "D-PATTERN-TRAP", sang: "D-VOWEL" }),
    odd("ing", 2, 1, 3, ["sing", "ring", "king", "jam"], "jam"),
    rfr("ang", 2, 1, 1, "bang", ["hang", "band", "hung", "ring"], "hang",
      { band: "D-PATTERN-TRAP", hung: "D-VOWEL", ring: "D-RIME-NEAR" }),
    rfr("ang", 2, 1, 2, "sang", ["fang", "sand", "song", "fan"], "fang",
      { sand: "D-PATTERN-TRAP", song: "D-VOWEL", fan: "D-DEVELOPMENTAL" },
      "fan drops the g — the cluster-reduction error; sand ties the san-chunk"),
    odd("ang", 2, 1, 3, ["bang", "sang", "hang", "cup"], "cup"),
    rfr("ong", 2, 1, 1, "song", ["long", "son", "sang", "lung"], "long",
      { son: "D-PATTERN-TRAP", sang: "D-VOWEL", lung: "D-RIME-NEAR" }),
    rfr("ong", 2, 1, 2, "long", ["gong", "whistle", "lung", "log"], "gong",
      { whistle: "D-PATTERN-TRAP", lung: "D-VOWEL", log: "D-DEVELOPMENTAL" }),
    odd("ong", 2, 1, 3, ["song", "long", "gong", "map"], "map"),
    rfr("ink", 2, 1, 1, "pink", ["sink", "pin", "sank", "ring"], "sink",
      { pin: "D-PATTERN-TRAP", sank: "D-VOWEL", ring: "D-RIME-NEAR" },
      "pin is the classic near-family answer — it ties the pin/pink chunk"),
    rfr("ink", 2, 1, 2, "wink", ["drink", "wind", "wing", "sank"], "drink",
      { wind: "D-PATTERN-TRAP", wing: "D-RIME-NEAR", sank: "D-VOWEL" }),
    odd("ink", 2, 1, 3, ["pink", "sink", "wink", "leg"], "leg"),
    rfr("ock", 2, 1, 1, "sock", ["rock", "whisk", "sack", "rug"], "rock",
      { whisk: "D-PATTERN-TRAP", sack: "D-VOWEL", rug: "D-RIME-NEAR" }),
    rfr("ock", 2, 1, 2, "lock", ["sock", "whistle", "lick", "log"], "sock",
      { whistle: "D-PATTERN-TRAP", lick: "D-VOWEL", log: "D-DEVELOPMENTAL" },
      "keys avoid lock/block containment pairs, which would hand a 4-chunk to scanners"),
    odd("ock", 2, 1, 3, ["sock", "rock", "lock", "pan"], "pan"),
    rfr("ack", 2, 1, 1, "back", ["sack", "witch", "sock", "bat"], "sack",
      { witch: "D-PATTERN-TRAP", sock: "D-VOWEL", bat: "D-RIME-NEAR" }),
    rfr("ack", 2, 1, 2, "pack", ["black", "whisk", "pick", "pat"], "black",
      { whisk: "D-PATTERN-TRAP", pick: "D-VOWEL", pat: "D-RIME-NEAR" }),
    odd("ack", 2, 1, 3, ["back", "sack", "pack", "mug"], "mug"),
    rfr("ick", 2, 1, 1, "stick", ["brick", "stiff", "stack", "bit"], "brick",
      { stiff: "D-PATTERN-TRAP", stack: "D-VOWEL", bit: "D-RIME-NEAR" }),
    rfr("ick", 2, 1, 2, "kick", ["lick", "witch", "lock", "kit"], "lick",
      { witch: "D-PATTERN-TRAP", lock: "D-VOWEL", kit: "D-DEVELOPMENTAL" }),
    odd("ick", 2, 1, 3, ["stick", "brick", "kick", "sun"], "sun"),
    rfr("ill", 2, 1, 1, "hill", ["pill", "whistle", "pull", "pin"], "pill",
      { whistle: "D-PATTERN-TRAP", pull: "D-VOWEL", pin: "D-RIME-NEAR" }),
    rfr("ill", 2, 1, 2, "mill", ["bill", "milk", "ball", "big"], "bill",
      { milk: "D-PATTERN-TRAP", ball: "D-VOWEL", big: "D-RIME-NEAR" },
      "milk ties the mil-chunk — the l-cluster neighbour"),
    odd("ill", 2, 1, 3, ["hill", "mill", "bill", "fox"], "fox"),
    rfr("all", 2, 1, 1, "ball", ["tall", "bald", "tell", "tap"], "tall",
      { bald: "D-PATTERN-TRAP", tell: "D-VOWEL", tap: "D-RIME-NEAR" }),
    rfr("all", 2, 1, 2, "wall", ["small", "walk", "well", "smell"], "small",
      { walk: "D-PATTERN-TRAP", well: "D-VOWEL", smell: "D-RIME-NEAR" },
      "walk ties the wal-chunk — same start, no rhyme"),
    odd("all", 2, 1, 3, ["ball", "tall", "fall", "pig"], "pig"),
    rfr("ell", 2, 1, 1, "bell", ["shell", "belt", "ball", "shop"], "shell",
      { belt: "D-PATTERN-TRAP", ball: "D-VOWEL", shop: "D-RIME-NEAR" }),
    rfr("ell", 2, 1, 2, "well", ["spell", "witch", "will", "spot"], "spell",
      { witch: "D-PATTERN-TRAP", will: "D-VOWEL", spot: "D-RIME-NEAR" }),
    odd("ell", 2, 1, 3, ["bell", "well", "shell", "cat"], "cat"),
    rfr("ash", 2, 1, 1, "cash", ["dash", "cast", "dish", "can"], "dash",
      { cast: "D-PATTERN-TRAP", dish: "D-VOWEL", can: "D-RIME-NEAR" }),
    rfr("ash", 2, 1, 2, "splash", ["crash", "splat", "crush", "cap"], "crash",
      { splat: "D-PATTERN-TRAP", crush: "D-VOWEL", cap: "D-RIME-NEAR" },
      "splat out-chunks the key (spla) — the scanner falls into the trap"),
    odd("ash", 2, 1, 3, ["dash", "cash", "splash", "bun"], "bun"),
    rfr("ish", 2, 1, 1, "wish", ["dish", "whisk", "dash", "dip"], "dish",
      { whisk: "D-PATTERN-TRAP", dash: "D-VOWEL", dip: "D-DEVELOPMENTAL" }),
    rfr("ish", 2, 1, 2, "fish", ["swish", "fist", "fresh", "swim"], "swish",
      { fist: "D-PATTERN-TRAP", fresh: "D-VOWEL", swim: "D-RIME-NEAR" }),
    odd("ish", 2, 1, 3, ["dish", "wish", "swish", "log"], "log"),

    // ======== L2 phase 2: uck ake ame ide ight oat eep ouse ird urn ar or ========
    rfr("uck", 2, 2, 1, "duck", ["truck", "witch", "deck", "dug"], "truck",
      { witch: "D-PATTERN-TRAP", deck: "D-VOWEL", dug: "D-DEVELOPMENTAL" }),
    rfr("uck", 2, 2, 2, "luck", ["stuck", "whistle", "lick", "cup"], "stuck",
      { whistle: "D-PATTERN-TRAP", lick: "D-VOWEL", cup: "D-RIME-NEAR" }),
    odd("uck", 2, 2, 3, ["duck", "truck", "stuck", "ham"], "ham"),
    rfr("ake", 2, 2, 1, "cake", ["lake", "whisk", "like", "can"], "lake",
      { whisk: "D-PATTERN-TRAP", like: "D-VOWEL", can: "D-RIME-NEAR" },
      "like is the silent-e sibling with the wrong vowel — one letter from the key"),
    rfr("ake", 2, 2, 2, "snake", ["bake", "snack", "bike", "bag"], "bake",
      { snack: "D-PATTERN-TRAP", bike: "D-VOWEL", bag: "D-RIME-NEAR" },
      "snack ties the sna-chunk — short-vowel cousin of the anchor"),
    odd("ake", 2, 2, 3, ["cake", "lake", "bake", "fog"], "fog"),
    rfr("ame", 2, 2, 1, "game", ["name", "witch", "time", "nap"], "name",
      { witch: "D-PATTERN-TRAP", time: "D-VOWEL", nap: "D-RIME-NEAR" }),
    rfr("ame", 2, 2, 2, "same", ["flame", "whistle", "flag", "time"], "flame",
      { whistle: "D-PATTERN-TRAP", flag: "D-RIME-NEAR", time: "D-VOWEL" }),
    odd("ame", 2, 2, 3, ["game", "name", "same", "zip"], "zip"),
    rfr("ide", 2, 2, 1, "ride", ["hide", "witch", "made", "hid"], "hide",
      { witch: "D-PATTERN-TRAP", made: "D-VOWEL", hid: "D-DEVELOPMENTAL" },
      "hid is the short sibling — drop the e, lose the rhyme"),
    rfr("ide", 2, 2, 2, "side", ["wide", "whisk", "wade", "win"], "wide",
      { whisk: "D-PATTERN-TRAP", wade: "D-VOWEL", win: "D-RIME-NEAR" }),
    odd("ide", 2, 2, 3, ["ride", "hide", "wide", "hen"], "hen"),
    rfr("ight", 2, 2, 1, "light", ["kite", "lit", "lift", "kit"], "kite",
      { lit: "D-DEVELOPMENTAL", lift: "D-PATTERN-TRAP", kit: "D-DEVELOPMENTAL" },
      "cross-spelling rhyme: kite shares no chunk with light, so the scanner reads nothing — the construct is sound, not letters"),
    rfr("ight", 2, 2, 2, "night", ["white", "wit", "net", "nut"], "white",
      { wit: "D-PATTERN-TRAP", net: "D-VOWEL", nut: "D-VOWEL" },
      "cross-spelling rhyme again; wit ties the with-overlap"),
    odd("ight", 2, 2, 3, ["light", "night", "right", "lamp"], "lamp"),
    rfr("oat", 2, 2, 1, "boat", ["goat", "board", "got", "bag"], "goat",
      { board: "D-PATTERN-TRAP", got: "D-DEVELOPMENTAL", bag: "D-RIME-NEAR" },
      "got is the short sibling; board ties the boa-chunk"),
    rfr("oat", 2, 2, 2, "coat", ["float", "coach", "cot", "fan"], "float",
      { coach: "D-PATTERN-TRAP", cot: "D-DEVELOPMENTAL", fan: "D-RIME-NEAR" }),
    odd("oat", 2, 2, 3, ["boat", "coat", "goat", "rug"], "rug"),
    rfr("eep", 2, 2, 1, "sheep", ["deep", "sheet", "ship", "den"], "deep",
      { sheet: "D-PATTERN-TRAP", ship: "D-DEVELOPMENTAL", den: "D-RIME-NEAR" },
      "sheet out-chunks the key (shee) — the scanner falls into the trap"),
    rfr("eep", 2, 2, 2, "jeep", ["sleep", "witch", "slip", "jam"], "sleep",
      { witch: "D-PATTERN-TRAP", slip: "D-DEVELOPMENTAL", jam: "D-RIME-NEAR" }),
    odd("eep", 2, 2, 3, ["sheep", "jeep", "deep", "mat"], "mat"),
    odd("ouse", 2, 2, 1, ["house", "mouse", "blouse", "bus"], "bus",
      "ouse has no scanner-safe RFR pairing (every rhyme shares the 4-letter rime), so the unit runs on odd-one-out, where max-overlap picks a rhymer"),
    odd("ouse", 2, 2, 2, ["mouse", "house", "blouse", "van"], "van"),
    odd("ouse", 2, 2, 3, ["house", "blouse", "mouse", "gum"], "gum"),
    rfr("ird", 2, 2, 1, "bird", ["third", "whisk", "bin", "bad"], "third",
      { whisk: "D-PATTERN-TRAP", bin: "D-RIME-NEAR", bad: "D-VOWEL" }),
    rfr("ird", 2, 2, 2, "third", ["herd", "this", "thin", "hen"], "herd",
      { this: "D-PATTERN-TRAP", thin: "D-RIME-NEAR", hen: "D-VOWEL" },
      "cross-spelling rhyme (ird/erd); this ties the thi-chunk"),
    odd("ird", 2, 2, 3, ["bird", "third", "herd", "cap"], "cap"),
    rfr("urn", 2, 2, 1, "burn", ["turn", "witch", "torn", "tub"], "turn",
      { witch: "D-PATTERN-TRAP", torn: "D-VOWEL", tub: "D-RIME-NEAR" }),
    rfr("urn", 2, 2, 2, "turn", ["fern", "whistle", "fun", "fan"], "fern",
      { whistle: "D-PATTERN-TRAP", fun: "D-RIME-NEAR", fan: "D-VOWEL" },
      "cross-spelling rhyme (urn/ern)"),
    odd("urn", 2, 2, 3, ["burn", "turn", "churn", "dog"], "dog"),
    rfr("ar", 2, 2, 1, "car", ["star", "cart", "care", "stop"], "star",
      { cart: "D-PATTERN-TRAP", care: "D-VOWEL", stop: "D-RIME-NEAR" },
      "care is one silent e from the anchor; cart out-chunks the key"),
    rfr("ar", 2, 2, 2, "jar", ["far", "jam", "fur", "jet"], "far",
      { jam: "D-PATTERN-TRAP", fur: "D-VOWEL", jet: "D-RIME-NEAR" }),
    odd("ar", 2, 2, 3, ["car", "star", "jar", "hut"], "hut"),
    rfr("or", 2, 2, 1, "corn", ["horn", "cord", "barn", "hen"], "horn",
      { cord: "D-PATTERN-TRAP", barn: "D-VOWEL", hen: "D-RIME-NEAR" },
      "barn is the ar/or vowel confusion; cord ties the cor-chunk"),
    rfr("or", 2, 2, 2, "fort", ["short", "fork", "shirt", "fog"], "short",
      { fork: "D-PATTERN-TRAP", shirt: "D-VOWEL", fog: "D-RIME-NEAR" }),
    odd("or", 2, 2, 3, ["corn", "horn", "fort", "bed"], "bed"),

    // ======== Retention reserve (form R) ========
    rmp("at", 1, 1, 7, "rat", ["bat", "rose", "pot", "jam"], "bat",
      { rose: "D-ONSET", pot: "D-VOWEL", jam: "D-RIME-NEAR" }),
    rmp("og", 1, 1, 7, "log", ["dog", "lock", "bug", "mop"], "dog",
      { lock: "D-ONSET", bug: "D-VOWEL", mop: "D-RIME-NEAR" }),
    rmp("en", 1, 1, 7, "pen", ["hen", "whale", "pin", "net"], "hen",
      { whale: "D-PATTERN-TRAP", pin: "D-VOWEL", net: "D-RIME-NEAR" }),
    rmp("ug", 1, 2, 7, "jug", ["bug", "whale", "bag", "cup"], "bug",
      { whale: "D-PATTERN-TRAP", bag: "D-VOWEL", cup: "D-RIME-NEAR" }),
    rmp("ip", 1, 1, 7, "tip", ["ship", "tie", "cap", "leg"], "ship",
      { tie: "D-ONSET", cap: "D-VOWEL", leg: "D-RIME-NEAR" }),
    rfr("ing", 2, 1, 7, "ring", ["sing", "rink", "rung", "rat"], "sing",
      { rink: "D-PATTERN-TRAP", rung: "D-VOWEL", rat: "D-RIME-NEAR" }),
    rfr("ake", 2, 2, 7, "bake", ["snake", "witch", "snack", "bin"], "snake",
      { witch: "D-PATTERN-TRAP", snack: "D-PATTERN-TRAP", bin: "D-RIME-NEAR" }),
    odd("ell", 2, 1, 7, ["shell", "spell", "yell", "tub"], "tub"),
    rfr("oat", 2, 2, 7, "goat", ["coat", "goal", "got", "cup"], "coat",
      { goal: "D-PATTERN-TRAP", got: "D-DEVELOPMENTAL", cup: "D-RIME-NEAR" }),
    odd("ink", 2, 1, 7, ["sink", "drink", "pink", "bat"], "bat")
  ].map(item => {
    if (item.v >= 7) item.retention = true;
    return item;
  })
};
