// Sentence Comprehension — v3 authored bank (wave W2). The bridge skill:
// meaning from ONE sentence. The legacy L1+stock-sentence→L2 cloning is dead —
// L2 cells are structurally different tasks (two-clause logic, pronoun
// reference, restatement), never longer copies of L1 items.
// The "passage" IS the sentence (8–14 words L1, 12–18 L2).

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, sentence, prompt, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage: sentence, prompt, choices, media: "text",
  ...(u === "pronoun_reference" ? { copyExempt: "pronoun-reference-label" } : {}),
  ...extra
});
const scene = (ph, v, imageKey, imageAlt, choices, extra = {}) => ({
  u: "picture_match",
  lvl: 1,
  ph,
  v,
  fmt: "COMPREHENSION",
  cell: "picture_match",
  prompt: "Which sentence tells about this picture?",
  spoken: "Look carefully at the picture. Which sentence tells about it?",
  choices,
  media: "image-required",
  img: imageKey,
  imgAlt: imageAlt,
  mediaRole: "scoring-evidence",
  evidenceModality: "image+sentence",
  constructClaim: "picture_to_sentence_meaning",
  suppressStimulusAudio: true,
  ...extra
});

export default {
  skillId: "sentence_comprehension",
  skillName: "Sentence Comprehension",
  items: [
    // ===== L1 · literal_who_what (8) =====
    it("literal_who_what", 1, 1, 1,
      "Granny Bola planted red tulips along the garden path.",
      "What change will Granny Bola see later?",
      [K("red flowers growing beside the path"), P("vegetables growing behind the shed", "D-PLAUSIBLE-UNSUPPORTED"), P("the path painted bright red", "D-VISUAL-NEIGHBOR"), P("the garden becoming empty", "D-OPPOSITE")]),
    it("literal_who_what", 1, 1, 2,
      "The dentist gave Milo a green sticker for brave sitting.",
      "Why did the dentist reward Milo?",
      [K("he sat calmly even though it felt scary"), P("he cleaned every tooth at home", "D-PLAUSIBLE-UNSUPPORTED"), P("he chose the color green", "D-VISUAL-NEIGHBOR"), P("he refused to sit in the chair", "D-OPPOSITE")]),
    it("literal_who_what", 1, 1, 3,
      "Our mail carrier whistles a tune along the whole street.",
      "What might neighbors hear when the mail carrier arrives?",
      [K("a person whistling music"), P("a bird tapping a window", "D-PLAUSIBLE-UNSUPPORTED"), P("a truck playing a tune", "D-TOPIC-ADJACENT"), P("complete silence on the street", "D-OPPOSITE")]),
    it("literal_who_what", 1, 1, 4,
      "Baby Ren stacked four wooden blocks all by himself.",
      "What did Ren make with the blocks?",
      [K("a small tower made from four pieces"), P("a shelf filled with four stories", "D-TOPIC-ADJACENT"), P("a table set for four people", "D-PLAUSIBLE-UNSUPPORTED"), P("a tower somebody else built", "D-OPPOSITE")]),
    it("literal_who_what", 1, 2, 5,
      "Uncle Dip burned the toast twice before breakfast.",
      "What went wrong before breakfast?",
      [K("the bread was cooked too long two times"), P("the soup spilled over two times", "D-PLAUSIBLE-UNSUPPORTED"), P("the kettle stopped working", "D-PLAUSIBLE-UNSUPPORTED"), P("breakfast was ready perfectly", "D-OPPOSITE")]),
    it("literal_who_what", 1, 2, 6,
      "The twins painted their bedroom door bright orange.",
      "Which statement must be true?",
      [K("two children changed the door's color"), P("one adult changed the wall's color", "D-VISUAL-NEIGHBOR"), P("two neighbors cleaned the room", "D-PLAUSIBLE-UNSUPPORTED"), P("the door stayed its old color", "D-OPPOSITE")]),
    it("literal_who_what", 1, 2, 7,
      "A magpie stole the shiny bottle top from our step.",
      "Why might the magpie have noticed the bottle top?",
      [K("it caught the light on the step"), P("it smelled like fresh bread", "D-PLAUSIBLE-UNSUPPORTED"), P("it was warm enough to wear", "D-PLAUSIBLE-UNSUPPORTED"), P("it was hidden in a dark box", "D-OPPOSITE")]),
    it("literal_who_what", 1, 2, 8,
      "Miss Faro fixed the wobbly table with folded cardboard.",
      "How did Miss Faro stop the wobble?",
      [K("she pushed layers of paper underneath"), P("she tied the legs with string", "D-PLAUSIBLE-UNSUPPORTED"), P("she struck the top with a hammer", "D-PLAUSIBLE-UNSUPPORTED"), P("she removed the table completely", "D-OPPOSITE")]),

    // ===== L1 · literal_where_when (8) =====
    it("literal_where_when", 1, 1, 1,
      "The choir practices in the hall every Tuesday.",
      "Which plan matches the sentence?",
      [K("sing together in the hall once each Tuesday"), P("sing outside every Saturday morning", "D-PLAUSIBLE-UNSUPPORTED"), P("meet in a classroom every afternoon", "D-PLAUSIBLE-UNSUPPORTED"), P("stop meeting for practice", "D-OPPOSITE")]),
    it("literal_where_when", 1, 1, 2,
      "Dad keeps his glasses in the fruit bowl, for some reason.",
      "Why is Dad's choice of place surprising?",
      [K("eyewear is stored with apples and bananas"), P("eyewear is stored beside his work", "D-PLAUSIBLE-UNSUPPORTED"), P("fruit is stored in the kitchen", "D-TOPIC-ADJACENT"), P("he wears the glasses on his face", "D-OPPOSITE")]),
    it("literal_where_when", 1, 1, 3,
      "The frog hid under the biggest lily pad.",
      "What was directly above the frog?",
      [K("the largest leaf on the pond"), P("a rock beside the water", "D-PLAUSIBLE-UNSUPPORTED"), P("the reeds at the edge", "D-PLAUSIBLE-UNSUPPORTED"), P("the open sky over the bank", "D-OPPOSITE")]),
    it("literal_where_when", 1, 1, 4,
      "Swimming lessons start right after lunch on Fridays.",
      "What should a student do on Friday?",
      [K("finish eating, then get ready to swim"), P("swim before eating breakfast", "D-SEQUENCE-SWAP"), P("wait until bedtime to swim", "D-PLAUSIBLE-UNSUPPORTED"), P("arrive for swimming on Saturday", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_where_when", 1, 2, 5,
      "Mom parks the bike behind the recycling bins.",
      "Where should someone look first for the bike?",
      [K("on the far side of the containers"), P("inside the garden building", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the entrance to the house", "D-PLAUSIBLE-UNSUPPORTED"), P("beneath a waterproof sheet", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_where_when", 1, 2, 6,
      "The market opens at 7:00, before school.",
      "When can people first shop at the market?",
      [K("at seven in the morning"), P("at nine in the morning", "D-PLAUSIBLE-UNSUPPORTED"), P("at noon", "D-PLAUSIBLE-UNSUPPORTED"), P("after school", "D-OPPOSITE")]),
    it("literal_where_when", 1, 2, 7,
      "Grandpa naps in the striped lawn chair by the roses.",
      "What is nearest Grandpa while he sleeps?",
      [K("flowers growing beside his striped seat"), P("cushions on the living-room sofa", "D-PLAUSIBLE-UNSUPPORTED"), P("ropes holding up a hammock", "D-PLAUSIBLE-UNSUPPORTED"), P("plates on the kitchen table", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_where_when", 1, 2, 8,
      "The lost kitten was found at the bottom of the linen closet.",
      "Where was the lost kitten found?",
      [K("on the closet floor"), P("the dark space beneath a vehicle", "D-PLAUSIBLE-UNSUPPORTED"), P("the high branches of a tree", "D-PLAUSIBLE-UNSUPPORTED"), P("the neighbor's garden", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ===== L1 · picture_match (8) — pick the sentence that fits the scene =====
    scene(1, 1, "scene-girl-jumps-puddle", "A girl in yellow rain boots jumping over a puddle.",
      [K("A girl in rain boots jumps over a puddle."),
       P("A girl sleeps in her warm bed.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("A boy in rain boots fills a puddle.", "D-VISUAL-NEIGHBOR"),
       P("A girl paints a picture of rain.", "D-TOPIC-ADJACENT")]),
    scene(1, 2, "scene-boys-ladder-bakery", "Two boys carrying a long ladder past a bakery.",
      [K("Two boys carry a ladder past the bakery."),
       P("Two boys buy buns at the bakery.", "D-TOPIC-ADJACENT"),
       P("One boy climbs a ladder at home.", "D-VISUAL-NEIGHBOR"),
       P("Two bakers carry a table.", "D-VISUAL-NEIGHBOR")]),
    scene(1, 3, "scene-cat-umbrella", "A cat asleep inside an open umbrella.",
      [K("A cat sleeps inside an open umbrella."),
       P("A cat hides from the rain indoors.", "D-TOPIC-ADJACENT"),
       P("A dog sleeps under an umbrella.", "D-VISUAL-NEIGHBOR"),
       P("A cat plays with a ball of wool.", "D-PLAUSIBLE-UNSUPPORTED")]),
    scene(1, 4, "scene-grandad-child-red-kite", "A grandpa and one child flying one red kite together.",
      [K("Grandpa and a child fly a red kite."),
       P("Grandpa buys a child a red ball.", "D-VISUAL-NEIGHBOR"),
       P("Two children fly two kites.", "D-VISUAL-NEIGHBOR"),
       P("Grandpa reads about kites.", "D-TOPIC-ADJACENT")]),
    scene(2, 5, "scene-red-sock-falling", "One red sock dropping from a full clothesline toward the grass.",
      [K("One red sock falls from the clothesline."),
       P("A red sock hangs safely on the line.", "D-OPPOSITE"),
      P("The empty clothesline swings in the wind.", "D-VISUAL-NEIGHBOR"),
       P("Someone irons a red shirt.", "D-TOPIC-ADJACENT")]),
    scene(2, 6, "scene-ducks-ice-cream-van", "Exactly three ducks waiting at an ice cream truck.",
      [K("Three ducks wait in line at the ice cream truck."),
       P("Three children feed ducks at the pond.", "D-VISUAL-NEIGHBOR"),
       P("An ice cream truck drives past a farm.", "D-TOPIC-ADJACENT"),
       P("One duck swims away from a boat.", "D-PLAUSIBLE-UNSUPPORTED")]),
    scene(2, 7, "scene-boy-giant-jelly", "A proud boy holding up a wobbly gelatin mold taller than his head.",
      [K("A boy holds up a giant wobbly gelatin mold."),
       P("A boy eats a small spoon of gelatin.", "D-VISUAL-NEIGHBOR"),
       P("A chef drops a tall cake.", "D-VISUAL-NEIGHBOR"),
       P("A boy washes a tall glass.", "D-PLAUSIBLE-UNSUPPORTED")]),
    scene(2, 8, "scene-snowman-sunglasses", "A snowman wearing sunglasses on a sunny winter day.",
      [K("A snowman wears sunglasses in the sunshine."),
       P("A snowman melts away in the rain.", "D-VISUAL-NEIGHBOR"),
       P("A child wears sunglasses at the beach.", "D-VISUAL-NEIGHBOR"),
       P("A snowman wears a warm scarf at night.", "D-VISUAL-NEIGHBOR")]),

    // ===== L1 · literal_action (8) =====
    it("literal_action", 1, 1, 1,
      "Pia tiptoed past the sleeping dog.",
      "How did Pia try not to wake the animal?",
      [K("she moved quietly on her toes"), P("she called loudly beside it", "D-OPPOSITE"), P("she gave it a bowl of food", "D-PLAUSIBLE-UNSUPPORTED"), P("she ran quickly through the park", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_action", 1, 1, 2,
      "The waiter balanced six plates on one arm.",
      "What made the waiter's action difficult?",
      [K("many dishes had to stay steady on one limb"), P("many dishes had already fallen to the floor", "D-OPPOSITE"), P("many dishes were waiting in a full sink", "D-PLAUSIBLE-UNSUPPORTED"), P("many orders were difficult to write down", "D-TOPIC-ADJACENT")]),
    it("literal_action", 1, 1, 3,
      "Grandma squeezed three large lemons for the lemonade.",
      "How did Grandma get juice for the drink?",
      [K("she crushed the fruit by hand"), P("she planted a tree for later", "D-TOPIC-ADJACENT"), P("she drank the finished mixture", "D-SEQUENCE-SWAP"), P("she bought several oranges", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_action", 1, 1, 4,
      "The goalkeeper tipped the ball above the crossbar.",
      "Where did the goalkeeper send the ball?",
      [K("over the bar"), P("into the goal", "D-OPPOSITE"), P("to the other end of the field", "D-PLAUSIBLE-UNSUPPORTED"), P("straight to the referee", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_action", 1, 2, 5,
      "Kofi taped the torn map back together.",
      "What did Kofi do?",
      [K("mended the map with tape"), P("tore the map in half", "D-OPPOSITE"), P("drew a new map", "D-PLAUSIBLE-UNSUPPORTED"), P("folded the map away", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_action", 1, 2, 6,
      "The parrot copied Grandpa's cough all afternoon.",
      "Which sound did the parrot repeat all afternoon?",
      [K("the bird repeated the man's cough"), P("the bird sang a sailor song", "D-PLAUSIBLE-UNSUPPORTED"), P("wings flapped through the window", "D-PLAUSIBLE-UNSUPPORTED"), P("the bird stayed silent while asleep", "D-OPPOSITE")]),
    it("literal_action", 1, 2, 7,
      "Ada rolled the biggest snowball in the whole street.",
      "How did Ada's snowball compare with the others?",
      [K("hers was larger than every other one nearby"), P("hers was the smallest one nearby", "D-OPPOSITE"), P("hers was the first one thrown", "D-PLAUSIBLE-UNSUPPORTED"), P("hers was made by a neighbor", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_action", 1, 2, 8,
      "The librarian stamped the book with tomorrow's date by mistake.",
      "What did the librarian do?",
      [K("stamped the wrong date"), P("lost the book", "D-PLAUSIBLE-UNSUPPORTED"), P("read the book aloud", "D-PLAUSIBLE-UNSUPPORTED"), P("mended the cover", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ===== L2 · two_clause (8) =====
    it("two_clause", 2, 1, 1,
      "Because the elevator was broken, the movers used the stairs.",
      "Why did the men use the stairs?",
      [K("the elevator was out of order"), P("the stairs were quicker", "D-PLAUSIBLE-UNSUPPORTED"), P("they liked climbing stairs", "D-PLAUSIBLE-UNSUPPORTED"), P("the elevator was full", "D-VISUAL-NEIGHBOR")]),
    it("two_clause", 2, 1, 2,
      "Rosa wore her brother's boots, so her footprints looked enormous.",
      "Why did the footprints look enormous?",
      [K("the boots were far too big for her"), P("Rosa's own feet were enormous", "D-PLAUSIBLE-UNSUPPORTED"), P("the mud made the footprints deep", "D-PLAUSIBLE-UNSUPPORTED"), P("a giant walked down the road", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("two_clause", 2, 1, 3,
      "The picnic moved indoors, but nobody minded because they still shared the cake.",
      "How did people feel about moving indoors?",
      [K("they did not mind, thanks to the cake"), P("they were very angry", "D-OPPOSITE"), P("they were worried about finding seats", "D-PLAUSIBLE-UNSUPPORTED"), P("they were surprised by the weather", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("two_clause", 2, 1, 4,
      "Although the sea looked calm, the flag on the beach was red.",
      "What did the red flag warn people about?",
      [K("the sea was not as safe as it looked"), P("the beach was closing for winter", "D-PLAUSIBLE-UNSUPPORTED"), P("a race was starting", "D-PLAUSIBLE-UNSUPPORTED"), P("the calm sea was safe", "D-OPPOSITE")]),
    it("two_clause", 2, 2, 5,
      "Jin saved his allowance all month so that he could buy Mom's birthday plant.",
      "Why did Jin save his allowance?",
      [K("to buy a plant for Mom's birthday"), P("to buy his own birthday plant", "D-POSITION"), P("to ride the bus every month", "D-OPPOSITE"), P("because he lost his money", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("two_clause", 2, 2, 6,
      "The paint was still wet, so the bench wore a little paper flag all day.",
      "Why did the bench have a flag?",
      [K("to warn that the paint was wet"), P("to celebrate a holiday", "D-PLAUSIBLE-UNSUPPORTED"), P("because a race finished there", "D-PLAUSIBLE-UNSUPPORTED"), P("because the bench was new", "D-VISUAL-NEIGHBOR")]),
    it("two_clause", 2, 2, 7,
      "Even though Tara practiced as goalkeeper every day, she chose to play forward in the final game.",
      "What position did Tara play in the final game?",
      [K("played forward"), P("played as goalkeeper", "D-VISUAL-NEIGHBOR"), P("watched from the bench", "D-PLAUSIBLE-UNSUPPORTED"), P("refereed the game", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("two_clause", 2, 2, 8,
      "The bread smelled wonderful, but it was for the fair, so nobody got a slice.",
      "Why did nobody eat the bread?",
      [K("it was being saved for the fair"), P("it smelled bad", "D-OPPOSITE"), P("it was burnt black", "D-PLAUSIBLE-UNSUPPORTED"), P("nobody was hungry", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ===== L2 · pronoun_reference (8) =====
    it("pronoun_reference", 2, 1, 1,
      "Maya handed the brush to Leo because he wanted to paint the fence blue.",
      "Who wanted to paint the fence blue?",
      [K("Leo"), P("Maya", "D-PLAUSIBLE-UNSUPPORTED"), P("the painter", "D-PLAUSIBLE-UNSUPPORTED"), P("the neighbor", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "the pronoun 'he' has one clear person reference" }),
    it("pronoun_reference", 2, 1, 2,
      "The seagull followed the fishing boat until it sailed out of the bay.",
      "What sailed out of the bay?",
      [K("the fishing boat"), P("the seagull", "D-VISUAL-NEIGHBOR"), P("a ferry", "D-PLAUSIBLE-UNSUPPORTED"), P("the harbor master", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "resolve 'it' — seagulls fly, boats sail" }),
    it("pronoun_reference", 2, 1, 3,
      "Sam lent Maya his lucky pencil, and it came back with teeth marks.",
      "Whose pencil got the teeth marks?",
      [K("Sam's"), P("Maya's", "D-VISUAL-NEIGHBOR"), P("the teacher's", "D-PLAUSIBLE-UNSUPPORTED"), P("nobody's", "D-OPPOSITE")]),
    it("pronoun_reference", 2, 1, 4,
      "When the twins visited Auntie Vee, she taught them a card game from her childhood.",
      "Who taught the card game?",
      [K("Auntie Vee"), P("the twins", "D-VISUAL-NEIGHBOR"), P("their mother", "D-PLAUSIBLE-UNSUPPORTED"), P("a grandparent", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("pronoun_reference", 2, 2, 5,
      "Nia put the seedling next to two cacti, but it soon grew too tall for the shelf.",
      "What grew too tall?",
      [K("the seedling"), P("the cacti", "D-VISUAL-NEIGHBOR"), P("the shelf", "D-PLAUSIBLE-UNSUPPORTED"), P("a sunflower", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "the singular pronoun 'it' has one clear singular noun reference" }),
    it("pronoun_reference", 2, 2, 6,
      "Carmen showed Grandpa the robot she had built out of cereal boxes.",
      "Who built the robot?",
      [K("Carmen"), P("Grandpa", "D-VISUAL-NEIGHBOR"), P("her dad", "D-PLAUSIBLE-UNSUPPORTED"), P("a toymaker", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "resolve 'she' — Grandpa cannot be 'she'" }),
    it("pronoun_reference", 2, 2, 7,
      "The keeper fed the penguins before the visitors arrived, so they were already full and sleepy.",
      "Who was full and sleepy?",
      [K("the penguins"), P("the visitors", "D-VISUAL-NEIGHBOR"), P("the keepers", "D-PLAUSIBLE-UNSUPPORTED"), P("the seals", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("pronoun_reference", 2, 2, 8,
      "Effie waved from the train until it moved beyond her cousin's platform.",
      "What moved beyond the platform?",
      [K("the train"), P("her cousin", "D-VISUAL-NEIGHBOR"), P("both of them", "D-PLAUSIBLE-UNSUPPORTED"), P("neither of them", "D-OPPOSITE")]),

    // ===== L2 · best_restatement (8) =====
    it("best_restatement", 2, 1, 1,
      "Not a single ticket for the puppet show was left by lunchtime.",
      "Which sentence means the SAME?",
      [K("The puppet show sold out before lunch."),
       P("The puppet show was canceled at lunch.", "D-OPPOSITE"),
       P("Tickets went on sale after lunch.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The puppets had their lunch.", "D-VISUAL-NEIGHBOR")]),
    it("best_restatement", 2, 1, 2,
      "Ravi knows the way to the pool with his eyes shut.",
      "Which sentence means the SAME?",
      [K("Ravi knows the route extremely well."),
       P("Ravi swims with his eyes shut.", "D-VISUAL-NEIGHBOR"),
       P("Ravi keeps getting lost.", "D-OPPOSITE"),
       P("Ravi walks to the pool asleep.", "D-VISUAL-NEIGHBOR")]),
    it("best_restatement", 2, 1, 3,
      "The whole class stood up before the final whistle ended the match.",
      "Which sentence means the SAME?",
      [K("Everyone rose before the match ended."),
       P("Everyone left before the match ended.", "D-VISUAL-NEIGHBOR"),
       P("The class sat quietly to the end.", "D-OPPOSITE"),
       P("The referee lost the whistle.", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("best_restatement", 2, 1, 4,
      "Dad says Grandma's soup has a smell strong enough to fill the street.",
      "Which sentence means the SAME?",
      [K("Dad says Grandma's soup smells very strong."),
       P("Grandma's soup is always cold.", "D-OPPOSITE"),
       P("Grandma cooks while the street sleeps.", "D-VISUAL-NEIGHBOR"),
       P("Dad says Grandma made soup for the street.", "D-VISUAL-NEIGHBOR")]),
    it("best_restatement", 2, 2, 5,
      "By the time the bus appeared, Omar's patience had completely run out.",
      "Which sentence means the SAME?",
      [K("Omar had stopped being patient before the bus came."),
       P("Omar ran after the bus.", "D-VISUAL-NEIGHBOR"),
       P("Omar waited calmly and quietly for the bus.", "D-OPPOSITE"),
       P("Omar had been waiting for a different bus.", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("best_restatement", 2, 2, 6,
      "The new puppy treated every shoe in the house as a chew toy.",
      "Which sentence means the SAME?",
      [K("The puppy chewed all the shoes."),
       P("The puppy fetched shoes politely.", "D-OPPOSITE"),
       P("The puppy had its own toys.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The house needed new carpets.", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("best_restatement", 2, 2, 7,
      "Keeping the secret until Friday was extremely difficult for Lila.",
      "Which sentence means the SAME?",
      [K("Lila found it hard not to tell the secret."),
       P("Lila told the secret on Monday.", "D-OPPOSITE"),
       P("Lila forgot the secret by Friday.", "D-VISUAL-NEIGHBOR"),
       P("Lila finished her work on Friday.", "D-VISUAL-NEIGHBOR")]),
    it("best_restatement", 2, 2, 8,
      "The hailstorm turned the trampoline into a giant popcorn machine.",
      "Which sentence means the SAME?",
      [K("Hailstones bounced all over the trampoline."),
       P("Popcorn spilled onto the trampoline.", "D-VISUAL-NEIGHBOR"),
       P("The trampoline blew away in the storm.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The children made popcorn indoors.", "D-TOPIC-ADJACENT")]),

    // ===== RETENTION (8 + 8) =====
    it("literal_who_what", 1, 1, 9,
      "Auntie Meg won the biggest pumpkin prize at the community fair.",
      "Why would Auntie Meg receive the award?",
      [K("her giant vegetable was judged best"), P("she served as the judge", "D-PLAUSIBLE-UNSUPPORTED"), P("her neighbor grew the winner", "D-PLAUSIBLE-UNSUPPORTED"), P("the fair gave no award", "D-OPPOSITE")], { retention: true }),
    it("literal_where_when", 1, 1, 10,
      "The school hamster sleeps all day and runs all night.",
      "When would the hamster's wheel most likely be moving?",
      [K("while the school is dark"), P("through every daytime lesson", "D-OPPOSITE"), P("only while pupils eat lunch", "D-PLAUSIBLE-UNSUPPORTED"), P("only on the first day of the week", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    scene(1, 9, "scene-small-dog-leads-tall-man", "A very small dog leading a very tall man down a street.",
      [K("A small dog leads a tall man down the street."),
       P("A tall man carries a small dog.", "D-VISUAL-NEIGHBOR"),
       P("Two dogs chase a ball.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("A man buys a dog lead.", "D-TOPIC-ADJACENT")], { retention: true }),
    it("literal_action", 1, 1, 10,
      "The baker hid a lucky coin inside one of the hundred buns.",
      "What did the baker do?",
      [K("hid a coin in one bun"), P("ate a hundred buns", "D-PLAUSIBLE-UNSUPPORTED"), P("dropped the tray", "D-PLAUSIBLE-UNSUPPORTED"), P("counted his money", "D-TOPIC-ADJACENT")], { retention: true }),
    it("literal_who_what", 1, 2, 10,
      "Little Ivo taught the parrot to say 'good morning' in a week.",
      "How did the bird learn the greeting?",
      [K("a young child trained it for seven days"), P("an older man trained it for seven days", "D-PLAUSIBLE-UNSUPPORTED"), P("an animal doctor trained it for seven days", "D-PLAUSIBLE-UNSUPPORTED"), P("it trained itself for seven days", "D-OPPOSITE")], { retention: true }),
    it("literal_where_when", 1, 2, 9,
      "Sports clothes are kept in the blue drawer under Robi's bed.",
      "Where are Robi's sports clothes kept?",
      [K("into the blue storage space below where he sleeps"), P("into the blue closet beside where he sleeps", "D-PLAUSIBLE-UNSUPPORTED"), P("into the blue locker he uses at school", "D-PLAUSIBLE-UNSUPPORTED"), P("into the blue basket beside the washing machine", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    scene(2, 10, "scene-family-asleep-film", "A whole family asleep on a sofa while film credits roll on the television.",
      [K("The family fell asleep before the film ended."),
       P("The family cheers at the film's ending.", "D-OPPOSITE"),
       P("The family waits in line for movie tickets.", "D-TOPIC-ADJACENT"),
       P("One child watches cartoons at breakfast.", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("literal_action", 1, 2, 9,
      "Mrs. Cho rescued the soccer ball from the school roof with a mop.",
      "What did Mrs. Cho do?",
      [K("got the ball down with a mop"), P("threw the ball onto the roof", "D-OPPOSITE"), P("cleaned the classroom floor", "D-TOPIC-ADJACENT"), P("bought a new soccer ball", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("two_clause", 2, 1, 9,
      "The candles were relit twice, because baby Bo blew them out from Mom's lap both times.",
      "Why were the candles relit?",
      [K("the baby kept blowing them out"), P("the wind blew them out", "D-PLAUSIBLE-UNSUPPORTED"), P("they burned down to stubs", "D-PLAUSIBLE-UNSUPPORTED"), P("the party started again", "D-VISUAL-NEIGHBOR")], { retention: true }),
    it("two_clause", 2, 2, 10,
      "Although the line curled twice around the square, Grandma said the dumplings were worth every minute.",
      "What did Grandma think about the wait?",
      [K("the dumplings made the long wait worthwhile"), P("the line was far too long to bother", "D-OPPOSITE"), P("the dumplings were served very quickly", "D-PLAUSIBLE-UNSUPPORTED"), P("the square was too crowded to visit", "D-VISUAL-NEIGHBOR")], { retention: true }),
    it("pronoun_reference", 2, 1, 9,
      "Priya read to her little brother until he finally fell asleep.",
      "Who fell asleep?",
      [K("her little brother"), P("Priya", "D-VISUAL-NEIGHBOR"), P("both of them", "D-PLAUSIBLE-UNSUPPORTED"), P("their mother", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("pronoun_reference", 2, 2, 10,
      "The coach thanked the parents after they had packed away every last cone and bib.",
      "Who packed away the cones?",
      [K("the parents"), P("the coach", "D-VISUAL-NEIGHBOR"), P("the players", "D-PLAUSIBLE-UNSUPPORTED"), P("the groundskeeper", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("best_restatement", 2, 1, 10,
      "The rising tide had completely covered the sandcastle by late afternoon.",
      "Which sentence means the SAME?",
      [K("The sea covered the sandcastle before evening."),
       P("The sandcastle survived until dark.", "D-OPPOSITE"),
       P("Someone ate dinner beside the sandcastle.", "D-VISUAL-NEIGHBOR"),
       P("The castle was built late that afternoon.", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("best_restatement", 2, 2, 9,
      "One sniff of the cheese sent the whole kitchen running for the windows.",
      "Which sentence means the SAME?",
      [K("The cheese smelled so bad everyone opened the windows."),
       P("Everyone raced to taste the cheese.", "D-OPPOSITE"),
       P("The kitchen windows were broken.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The cheese was served right beside the window.", "D-VISUAL-NEIGHBOR")], { retention: true }),
    it("literal_action", 2, 1, 11,
      "The window cleaner waved his squeegee at every child on the top deck of the bus.",
      "What did the window cleaner do?",
      [K("waved at the children on the bus"), P("cleaned the bus windows", "D-VISUAL-NEIGHBOR"), P("drove the bus to school", "D-PLAUSIBLE-UNSUPPORTED"), P("dropped his squeegee", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("pronoun_reference", 2, 1, 11,
      "Grandma passed Jonah the binoculars just as he spotted the heron landing.",
      "Who spotted the heron?",
      [K("Jonah"), P("Grandma", "D-VISUAL-NEIGHBOR"), P("a birdwatcher", "D-PLAUSIBLE-UNSUPPORTED"), P("nobody saw it", "D-OPPOSITE")], { retention: true })
  ]
};
