// Sentence Comprehension — v3 authored bank (wave W2). The bridge skill:
// meaning from ONE sentence. The legacy L1+stock-sentence→L2 cloning is dead —
// L2 cells are structurally different tasks (two-clause logic, pronoun
// reference, restatement), never longer copies of L1 items.
// The "passage" IS the sentence (8–14 words L1, 12–18 L2).

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, sentence, prompt, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage: sentence, prompt, choices, media: "text", ...extra
});

const LITERAL_CELLS = new Set(["literal_who_what", "literal_where_when", "literal_action", "picture_match"]);

export default {
  skillId: "sentence_comprehension",
  skillName: "Sentence Comprehension",
  items: [
    // ===== L1 · literal_who_what (8) =====
    it("literal_who_what", 1, 1, 1,
      "Granny Bola planted red tulips along the garden path.",
      "Who planted the tulips?",
      [K("Granny Bola"), P("the gardener", "D-PLAUSIBLE-UNSUPPORTED"), P("the twins", "D-PLAUSIBLE-UNSUPPORTED"), P("nobody did", "D-OPPOSITE")]),
    it("literal_who_what", 1, 1, 2,
      "The dentist gave Milo a green sticker for brave sitting.",
      "What did Milo get?",
      [K("a green sticker"), P("a new toothbrush", "D-PLAUSIBLE-UNSUPPORTED"), P("a balloon", "D-PLAUSIBLE-UNSUPPORTED"), P("nothing at all", "D-OPPOSITE")]),
    it("literal_who_what", 1, 1, 3,
      "Our postlady whistles show tunes on her whole round.",
      "Who whistles the tunes?",
      [K("the postlady"), P("the milkman", "D-PLAUSIBLE-UNSUPPORTED"), P("a blackbird", "D-PLAUSIBLE-UNSUPPORTED"), P("the radio", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_who_what", 1, 1, 4,
      "Baby Ren stacked four wooden blocks all by himself.",
      "What did Baby Ren stack?",
      [K("wooden blocks"), P("dinner plates", "D-PLAUSIBLE-UNSUPPORTED"), P("story books", "D-PLAUSIBLE-UNSUPPORTED"), P("shoe boxes", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_who_what", 1, 2, 5,
      "Uncle Dip burned the toast twice before breakfast.",
      "What did Uncle Dip burn?",
      [K("the toast"), P("the soup", "D-PLAUSIBLE-UNSUPPORTED"), P("his hand", "D-PLAUSIBLE-UNSUPPORTED"), P("the kettle", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_who_what", 1, 2, 6,
      "The twins painted their bedroom door bright orange.",
      "Who painted the door?",
      [K("the twins"), P("their dad", "D-PLAUSIBLE-UNSUPPORTED"), P("a decorator", "D-PLAUSIBLE-UNSUPPORTED"), P("the neighbours", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_who_what", 1, 2, 7,
      "A magpie stole the shiny bottle top from our step.",
      "What did the magpie steal?",
      [K("a shiny bottle top"), P("a slice of bread", "D-PLAUSIBLE-UNSUPPORTED"), P("a silver ring", "D-PLAUSIBLE-UNSUPPORTED"), P("a garden glove", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_who_what", 1, 2, 8,
      "Miss Faro fixed the wobbly table with folded card.",
      "What did Miss Faro use?",
      [K("folded card"), P("sticky tape", "D-PLAUSIBLE-UNSUPPORTED"), P("a hammer", "D-PLAUSIBLE-UNSUPPORTED"), P("string", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ===== L1 · literal_where_when (8) =====
    it("literal_where_when", 1, 1, 1,
      "The choir practises in the hall every Tuesday.",
      "When does the choir practise?",
      [K("every Tuesday"), P("every morning", "D-PLAUSIBLE-UNSUPPORTED"), P("on Saturdays", "D-PLAUSIBLE-UNSUPPORTED"), P("never", "D-OPPOSITE")]),
    it("literal_where_when", 1, 1, 2,
      "Dad keeps his glasses in the fruit bowl, for some reason.",
      "Where does Dad keep his glasses?",
      [K("in the fruit bowl"), P("on his desk", "D-PLAUSIBLE-UNSUPPORTED"), P("in the car", "D-PLAUSIBLE-UNSUPPORTED"), P("on his head", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_where_when", 1, 1, 3,
      "The frog hid under the biggest lily pad.",
      "Where did the frog hide?",
      [K("under the biggest lily pad"), P("behind a rock", "D-PLAUSIBLE-UNSUPPORTED"), P("in the reeds", "D-PLAUSIBLE-UNSUPPORTED"), P("on the bank", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_where_when", 1, 1, 4,
      "Swimming lessons start straight after lunch on Fridays.",
      "When do the lessons start?",
      [K("straight after lunch"), P("before breakfast", "D-PLAUSIBLE-UNSUPPORTED"), P("at bedtime", "D-PLAUSIBLE-UNSUPPORTED"), P("in the morning", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_where_when", 1, 2, 5,
      "Mum parks the bike behind the recycling bins.",
      "Where does the bike go?",
      [K("behind the recycling bins"), P("inside the shed", "D-PLAUSIBLE-UNSUPPORTED"), P("by the front door", "D-PLAUSIBLE-UNSUPPORTED"), P("under a cover", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_where_when", 1, 2, 6,
      "The market opens at seven, long before school.",
      "When does the market open?",
      [K("at seven"), P("at lunchtime", "D-PLAUSIBLE-UNSUPPORTED"), P("after school", "D-OPPOSITE"), P("at nine", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_where_when", 1, 2, 7,
      "Grandpa naps in the striped deckchair by the roses.",
      "Where does Grandpa nap?",
      [K("in the deckchair by the roses"), P("on the sofa", "D-PLAUSIBLE-UNSUPPORTED"), P("in the hammock", "D-PLAUSIBLE-UNSUPPORTED"), P("at the kitchen table", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_where_when", 1, 2, 8,
      "The lost kitten was found at the bottom of the airing cupboard.",
      "Where was the kitten found?",
      [K("in the airing cupboard"), P("under the car", "D-PLAUSIBLE-UNSUPPORTED"), P("up a tree", "D-PLAUSIBLE-UNSUPPORTED"), P("next door", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ===== L1 · picture_match (8) — pick the sentence that fits the scene =====
    it("picture_match", 1, 1, 1,
      "Scene: a girl in wellies jumping over a puddle.",
      "Which sentence tells about this scene?",
      [K("A girl in wellies jumps over a puddle."),
       P("A girl sleeps in her warm bed.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("A boy in wellies fills a puddle.", "D-VISUAL-NEIGHBOR"),
       P("A girl paints a picture of rain.", "D-TOPIC-ADJACENT")]),
    it("picture_match", 1, 1, 2,
      "Scene: two boys carrying a long ladder past a bakery.",
      "Which sentence tells about this scene?",
      [K("Two boys carry a ladder past the bakery."),
       P("Two boys buy buns at the bakery.", "D-TOPIC-ADJACENT"),
       P("One boy climbs a ladder at home.", "D-VISUAL-NEIGHBOR"),
       P("Two bakers carry a table.", "D-VISUAL-NEIGHBOR")]),
    it("picture_match", 1, 1, 3,
      "Scene: a cat asleep inside an open umbrella.",
      "Which sentence tells about this scene?",
      [K("A cat sleeps inside an open umbrella."),
       P("A cat hides from the rain indoors.", "D-TOPIC-ADJACENT"),
       P("A dog sleeps under an umbrella.", "D-VISUAL-NEIGHBOR"),
       P("A cat plays with a ball of wool.", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("picture_match", 1, 1, 4,
      "Scene: a grandad and a child flying one red kite together.",
      "Which sentence tells about this scene?",
      [K("Grandad and a child fly a red kite."),
       P("Grandad buys a child a red ball.", "D-VISUAL-NEIGHBOR"),
       P("Two children fly two kites.", "D-VISUAL-NEIGHBOR"),
       P("Grandad reads about kites.", "D-TOPIC-ADJACENT")]),
    it("picture_match", 1, 2, 5,
      "Scene: a full washing line with one red sock dropping to the grass.",
      "Which sentence tells about this scene?",
      [K("One red sock falls from the washing line."),
       P("A red sock hangs safely on the line.", "D-OPPOSITE"),
       P("The empty line swings in the wind.", "D-VISUAL-NEIGHBOR"),
       P("Someone irons a red shirt.", "D-TOPIC-ADJACENT")]),
    it("picture_match", 1, 2, 6,
      "Scene: three ducks queuing at an ice-cream van.",
      "Which sentence tells about this scene?",
      [K("Three ducks wait in line at the ice-cream van."),
       P("Three children feed ducks at the pond.", "D-VISUAL-NEIGHBOR"),
       P("An ice-cream van drives past a farm.", "D-TOPIC-ADJACENT"),
       P("One duck swims away from a boat.", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("picture_match", 1, 2, 7,
      "Scene: a boy proudly holding up a wobbly jelly taller than his head.",
      "Which sentence tells about this scene?",
      [K("A boy holds up a giant wobbly jelly."),
       P("A boy eats a small spoon of jelly.", "D-VISUAL-NEIGHBOR"),
       P("A chef drops a tall cake.", "D-VISUAL-NEIGHBOR"),
       P("A boy washes a tall glass.", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("picture_match", 1, 2, 8,
      "Scene: a snowman wearing sunglasses on a sunny winter day.",
      "Which sentence tells about this scene?",
      [K("A snowman wears sunglasses in the sunshine."),
       P("A snowman melts away in the rain.", "D-VISUAL-NEIGHBOR"),
       P("A child wears sunglasses at the beach.", "D-VISUAL-NEIGHBOR"),
       P("A snowman wears a woolly scarf at night.", "D-VISUAL-NEIGHBOR")]),

    // ===== L1 · literal_action (8) =====
    it("literal_action", 1, 1, 1,
      "Pia tiptoed past the sleeping dog.",
      "What did Pia do?",
      [K("tiptoed past the dog"), P("woke the dog up", "D-OPPOSITE"), P("fed the dog", "D-PLAUSIBLE-UNSUPPORTED"), P("ran to the park", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_action", 1, 1, 2,
      "The waiter balanced six plates on one arm.",
      "What did the waiter do?",
      [K("balanced six plates on one arm"), P("dropped six plates", "D-OPPOSITE"), P("washed the dishes", "D-PLAUSIBLE-UNSUPPORTED"), P("wrote down an order", "D-TOPIC-ADJACENT")]),
    it("literal_action", 1, 1, 3,
      "Nan squeezed three fat lemons for the lemonade.",
      "What did Nan do?",
      [K("squeezed lemons"), P("planted a lemon tree", "D-TOPIC-ADJACENT"), P("drank the lemonade", "D-SEQUENCE-SWAP"), P("bought some oranges", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_action", 1, 1, 4,
      "The goalkeeper tipped the ball over the bar.",
      "What did the goalkeeper do?",
      [K("tipped the ball over the bar"), P("let the ball in", "D-OPPOSITE"), P("scored a goal", "D-PLAUSIBLE-UNSUPPORTED"), P("blew the whistle", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_action", 1, 2, 5,
      "Kofi taped the torn map back together.",
      "What did Kofi do?",
      [K("mended the map with tape"), P("tore the map in half", "D-OPPOSITE"), P("drew a new map", "D-PLAUSIBLE-UNSUPPORTED"), P("folded the map away", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("literal_action", 1, 2, 6,
      "The parrot copied Grandpa's cough all afternoon.",
      "What did the parrot do?",
      [K("copied Grandpa's cough"), P("sang a sailor song", "D-PLAUSIBLE-UNSUPPORTED"), P("flew out the window", "D-PLAUSIBLE-UNSUPPORTED"), P("slept on its perch", "D-OPPOSITE")]),
    it("literal_action", 1, 2, 7,
      "Ada rolled the biggest snowball in the whole street.",
      "What did Ada do?",
      [K("rolled a huge snowball"), P("threw a small snowball", "D-VISUAL-NEIGHBOR"), P("shovelled the path", "D-TOPIC-ADJACENT"), P("stayed indoors", "D-OPPOSITE")]),
    it("literal_action", 1, 2, 8,
      "The librarian stamped the book with tomorrow's date by mistake.",
      "What did the librarian do?",
      [K("stamped the wrong date"), P("lost the book", "D-PLAUSIBLE-UNSUPPORTED"), P("read the book aloud", "D-PLAUSIBLE-UNSUPPORTED"), P("mended the cover", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ===== L2 · two_clause (8) =====
    it("two_clause", 2, 1, 1,
      "Because the lift was broken, the removal men used the stairs.",
      "Why did the men use the stairs?",
      [K("the lift was out of order"), P("the stairs were quicker", "D-PLAUSIBLE-UNSUPPORTED"), P("they liked climbing stairs", "D-PLAUSIBLE-UNSUPPORTED"), P("the lift was full", "D-VISUAL-NEIGHBOR")]),
    it("two_clause", 2, 1, 2,
      "Rosa wore her brother's boots, so her footprints looked enormous.",
      "Why did the footprints look enormous?",
      [K("the boots were far too big for her"), P("Rosa's own feet were enormous", "D-PLAUSIBLE-UNSUPPORTED"), P("the mud made the footprints deep", "D-PLAUSIBLE-UNSUPPORTED"), P("a giant walked down the road", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("two_clause", 2, 1, 3,
      "The picnic moved indoors, but nobody minded because of the cake.",
      "How did people feel about moving indoors?",
      [K("they did not mind, thanks to the cake"), P("they were very cross", "D-OPPOSITE"), P("they cancelled the picnic straight away", "D-OPPOSITE"), P("they forgot the cake", "D-OPPOSITE")]),
    it("two_clause", 2, 1, 4,
      "Although the sea looked calm, the flag on the beach was red.",
      "What did the red flag warn?",
      [K("the sea was not as safe as it looked"), P("the beach was closing for winter", "D-PLAUSIBLE-UNSUPPORTED"), P("a race was starting", "D-PLAUSIBLE-UNSUPPORTED"), P("the calm sea was safe", "D-OPPOSITE")]),
    it("two_clause", 2, 2, 5,
      "Jin saved his bus money all month so that he could buy Mum's birthday plant.",
      "Why did Jin save his bus money?",
      [K("to buy a plant for Mum's birthday"), P("to buy his own birthday plant", "D-POSITION"), P("to ride the bus every month", "D-OPPOSITE"), P("because he lost his money", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("two_clause", 2, 2, 6,
      "The paint was still wet, so the bench wore a little paper flag all day.",
      "Why did the bench have a flag?",
      [K("to warn that the paint was wet"), P("to celebrate a holiday", "D-PLAUSIBLE-UNSUPPORTED"), P("because a race finished there", "D-PLAUSIBLE-UNSUPPORTED"), P("because the bench was new", "D-VISUAL-NEIGHBOR")]),
    it("two_clause", 2, 2, 7,
      "Even though Tara practised in goal every day, she chose to play striker in the final.",
      "What did Tara do in the final?",
      [K("played striker"), P("played in goal", "D-VISUAL-NEIGHBOR"), P("watched from the bench", "D-PLAUSIBLE-UNSUPPORTED"), P("refereed the match", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("two_clause", 2, 2, 8,
      "The bread smelled wonderful, but it was for the fair, so nobody got a slice.",
      "Why did nobody eat the bread?",
      [K("it was being saved for the fair"), P("it smelled bad", "D-OPPOSITE"), P("it was burnt black", "D-PLAUSIBLE-UNSUPPORTED"), P("nobody was hungry", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ===== L2 · pronoun_reference (8) =====
    it("pronoun_reference", 2, 1, 1,
      "Maya handed the brush to Elena because she wanted the fence painted blue.",
      "Who wanted the fence painted blue?",
      [K("Maya"), P("Elena", "D-PLAUSIBLE-UNSUPPORTED"), P("the painter", "D-PLAUSIBLE-UNSUPPORTED"), P("the neighbour", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "resolve 'she' against the handing direction" }),
    it("pronoun_reference", 2, 1, 2,
      "The seagull followed the fishing boat until it sailed out of the bay.",
      "What sailed out of the bay?",
      [K("the fishing boat"), P("the seagull", "D-VISUAL-NEIGHBOR"), P("a ferry", "D-PLAUSIBLE-UNSUPPORTED"), P("the harbour master", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "resolve 'it' — seagulls fly, boats sail" }),
    it("pronoun_reference", 2, 1, 3,
      "Sam lent Ollie his lucky pencil, and it came back with teeth marks.",
      "Whose pencil got the teeth marks?",
      [K("Sam's"), P("Ollie's", "D-VISUAL-NEIGHBOR"), P("the teacher's", "D-PLAUSIBLE-UNSUPPORTED"), P("nobody's", "D-OPPOSITE")]),
    it("pronoun_reference", 2, 1, 4,
      "When the twins visited Auntie Vee, she taught them a card game from her childhood.",
      "Who taught the card game?",
      [K("Auntie Vee"), P("the twins", "D-VISUAL-NEIGHBOR"), P("their mother", "D-PLAUSIBLE-UNSUPPORTED"), P("a grandparent", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("pronoun_reference", 2, 2, 5,
      "Nia put the seedling next to the cactus, but it soon grew too tall for the shelf.",
      "What grew too tall?",
      [K("the seedling"), P("the cactus", "D-VISUAL-NEIGHBOR"), P("the shelf", "D-PLAUSIBLE-UNSUPPORTED"), P("a sunflower", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "cactuses stay small; the planted-and-growing one is the seedling" }),
    it("pronoun_reference", 2, 2, 6,
      "Carmen showed Grandpa the robot she had built out of cereal boxes.",
      "Who built the robot?",
      [K("Carmen"), P("Grandpa", "D-VISUAL-NEIGHBOR"), P("her dad", "D-PLAUSIBLE-UNSUPPORTED"), P("a toymaker", "D-PLAUSIBLE-UNSUPPORTED")],
      { note: "resolve 'she' — Grandpa cannot be 'she'" }),
    it("pronoun_reference", 2, 2, 7,
      "The keeper fed the penguins before the visitors arrived, so they were already full and sleepy.",
      "Who was full and sleepy?",
      [K("the penguins"), P("the visitors", "D-VISUAL-NEIGHBOR"), P("the keepers", "D-PLAUSIBLE-UNSUPPORTED"), P("the seals", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("pronoun_reference", 2, 2, 8,
      "Effie waved at her cousin from the train until she could not see the platform any more.",
      "Who was on the train?",
      [K("Effie"), P("her cousin", "D-VISUAL-NEIGHBOR"), P("both of them", "D-PLAUSIBLE-UNSUPPORTED"), P("neither of them", "D-OPPOSITE")]),

    // ===== L2 · best_restatement (8) =====
    it("best_restatement", 2, 1, 1,
      "Not a single ticket for the puppet show was left by lunchtime.",
      "Which sentence means the SAME?",
      [K("The puppet show sold out before lunch."),
       P("The puppet show was cancelled at lunch.", "D-OPPOSITE"),
       P("Many tickets were left after lunch.", "D-OPPOSITE"),
       P("The puppets had their lunch.", "D-VISUAL-NEIGHBOR")]),
    it("best_restatement", 2, 1, 2,
      "Ravi knows the way to the pool with his eyes shut.",
      "Which sentence means the SAME?",
      [K("Ravi knows the route extremely well."),
       P("Ravi swims with his eyes shut.", "D-VISUAL-NEIGHBOR"),
       P("Ravi keeps getting lost.", "D-OPPOSITE"),
       P("Ravi walks to the pool asleep.", "D-VISUAL-NEIGHBOR")]),
    it("best_restatement", 2, 1, 3,
      "The whole class was on its feet before the final whistle.",
      "Which sentence means the SAME?",
      [K("Everyone stood up before the match ended."),
       P("Everyone left before the match ended.", "D-VISUAL-NEIGHBOR"),
       P("The class sat quietly to the end.", "D-OPPOSITE"),
       P("The referee lost the whistle.", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("best_restatement", 2, 1, 4,
      "Gran's soup could wake up a sleepy street, Dad always says.",
      "Which sentence means the SAME?",
      [K("Dad says Gran's soup smells very strong."),
       P("Gran's soup is always cold.", "D-OPPOSITE"),
       P("Gran cooks while the street sleeps.", "D-VISUAL-NEIGHBOR"),
       P("Dad dislikes Gran's soup.", "D-OPPOSITE")]),
    it("best_restatement", 2, 2, 5,
      "By the time the bus appeared, Omar's patience had completely run out.",
      "Which sentence means the SAME?",
      [K("Omar had stopped being patient before the bus came."),
       P("Omar ran after the bus.", "D-VISUAL-NEIGHBOR"),
       P("Omar waited calmly and quietly for the bus.", "D-OPPOSITE"),
       P("The bus never appeared at all.", "D-OPPOSITE")]),
    it("best_restatement", 2, 2, 6,
      "The new puppy treated every shoe in the house as a chew toy.",
      "Which sentence means the SAME?",
      [K("The puppy chewed all the shoes."),
       P("The puppy fetched shoes politely.", "D-OPPOSITE"),
       P("The puppy had its own toys.", "D-OPPOSITE"),
       P("The house needed new carpets.", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("best_restatement", 2, 2, 7,
      "Keeping the secret until Friday nearly finished poor Lila off.",
      "Which sentence means the SAME?",
      [K("Lila found it hard not to tell the secret."),
       P("Lila told the secret on Monday.", "D-OPPOSITE"),
       P("Lila forgot the secret by Friday.", "D-VISUAL-NEIGHBOR"),
       P("Lila finished her work on Friday.", "D-VISUAL-NEIGHBOR")]),
    it("best_restatement", 2, 2, 8,
      "The hailstorm turned the trampoline into a giant popcorn machine.",
      "Which sentence means the SAME?",
      [K("Hailstones bounced all over the trampoline."),
       P("Popcorn spilled onto the trampoline.", "D-VISUAL-NEIGHBOR"),
       P("The trampoline blew away in the storm.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The children made popcorn indoors.", "D-TOPIC-ADJACENT")]),

    // ===== RETENTION (8 + 8) =====
    it("literal_who_what", 1, 1, 9,
      "Auntie Meg won the biggest marrow prize at the village show.",
      "Who won the prize?",
      [K("Auntie Meg"), P("the judge", "D-PLAUSIBLE-UNSUPPORTED"), P("next door's gardener", "D-PLAUSIBLE-UNSUPPORTED"), P("nobody this year", "D-OPPOSITE")], { retention: true }),
    it("literal_where_when", 1, 1, 10,
      "The school hamster sleeps all day and runs all night.",
      "When does the hamster run?",
      [K("at night"), P("all day", "D-OPPOSITE"), P("at lunchtime", "D-PLAUSIBLE-UNSUPPORTED"), P("on Mondays", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("picture_match", 1, 1, 9,
      "Scene: a very small dog walking a very tall man on a lead.",
      "Which sentence tells about this scene?",
      [K("A small dog leads a tall man down the street."),
       P("A tall man carries a small dog.", "D-VISUAL-NEIGHBOR"),
       P("Two dogs chase a ball.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("A man buys a dog lead.", "D-TOPIC-ADJACENT")], { retention: true }),
    it("literal_action", 1, 1, 10,
      "The baker hid a lucky coin inside one of the hundred buns.",
      "What did the baker do?",
      [K("hid a coin in one bun"), P("ate a hundred buns", "D-PLAUSIBLE-UNSUPPORTED"), P("dropped the tray", "D-PLAUSIBLE-UNSUPPORTED"), P("counted his money", "D-TOPIC-ADJACENT")], { retention: true }),
    it("literal_who_what", 1, 2, 10,
      "Little Ivo taught the parrot to say 'good morning' in a week.",
      "Who taught the parrot?",
      [K("Ivo"), P("Grandpa", "D-PLAUSIBLE-UNSUPPORTED"), P("the vet", "D-PLAUSIBLE-UNSUPPORTED"), P("the parrot learned alone", "D-OPPOSITE")], { retention: true }),
    it("literal_where_when", 1, 2, 9,
      "Sports kit lives in the blue drawer under Robi's bed.",
      "Where is the sports kit?",
      [K("in the drawer under the bed"), P("in the wardrobe", "D-PLAUSIBLE-UNSUPPORTED"), P("at school", "D-PLAUSIBLE-UNSUPPORTED"), P("in the wash", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("picture_match", 1, 2, 10,
      "Scene: a whole family asleep on the sofa while the film credits roll.",
      "Which sentence tells about this scene?",
      [K("The family fell asleep before the film ended."),
       P("The family cheers at the film's ending.", "D-OPPOSITE"),
       P("The family queues for cinema tickets.", "D-TOPIC-ADJACENT"),
       P("One child watches cartoons at breakfast.", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("literal_action", 1, 2, 9,
      "Mrs Cho rescued the football from the school roof with a mop.",
      "What did Mrs Cho do?",
      [K("got the ball down with a mop"), P("threw the ball onto the roof", "D-OPPOSITE"), P("cleaned the classroom floor", "D-TOPIC-ADJACENT"), P("bought a new football", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("two_clause", 2, 1, 9,
      "The candles were relit twice, because baby Bo blew them out from Mum's lap both times.",
      "Why were the candles relit?",
      [K("the baby kept blowing them out"), P("the wind blew them out", "D-PLAUSIBLE-UNSUPPORTED"), P("they burned down to stubs", "D-PLAUSIBLE-UNSUPPORTED"), P("the party started again", "D-VISUAL-NEIGHBOR")], { retention: true }),
    it("two_clause", 2, 2, 10,
      "Although the queue curled twice around the square, Nan said the dumplings were worth every minute.",
      "What did Nan think about the wait?",
      [K("the dumplings made the long wait worthwhile"), P("the queue was far too long to bother", "D-OPPOSITE"), P("the dumplings were disappointing", "D-OPPOSITE"), P("the square was too crowded to visit", "D-VISUAL-NEIGHBOR")], { retention: true }),
    it("pronoun_reference", 2, 1, 9,
      "Priya read to her little brother until he finally fell asleep.",
      "Who fell asleep?",
      [K("her little brother"), P("Priya", "D-VISUAL-NEIGHBOR"), P("both of them", "D-PLAUSIBLE-UNSUPPORTED"), P("their mother", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("pronoun_reference", 2, 2, 10,
      "The coach thanked the parents after they had packed away every last cone and bib.",
      "Who packed away the cones?",
      [K("the parents"), P("the coach", "D-VISUAL-NEIGHBOR"), P("the players", "D-PLAUSIBLE-UNSUPPORTED"), P("the groundskeeper", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("best_restatement", 2, 1, 10,
      "The tide had swallowed the whole sandcastle by tea time.",
      "Which sentence means the SAME?",
      [K("The sea covered the sandcastle before tea."),
       P("The sandcastle survived until dark.", "D-OPPOSITE"),
       P("Someone ate tea on the sandcastle.", "D-VISUAL-NEIGHBOR"),
       P("The castle was rebuilt at tea time.", "D-OPPOSITE")], { retention: true }),
    it("best_restatement", 2, 2, 9,
      "One sniff of the cheese sent the whole kitchen running for the windows.",
      "Which sentence means the SAME?",
      [K("The cheese smelled so bad everyone opened the windows."),
       P("Everyone raced to taste the cheese.", "D-OPPOSITE"),
       P("The kitchen windows were broken.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("The cheese was served right beside the window.", "D-VISUAL-NEIGHBOR")], { retention: true }),
    it("literal_action", 2, 1, 11,
      "The window cleaner waved his squeegee at every child on the top deck of the bus.",
      "What did the window cleaner do?",
      [K("waved at the children on the bus"), P("cleaned the bus windows", "D-VISUAL-NEIGHBOR"), P("drove the bus to school", "D-PLAUSIBLE-UNSUPPORTED"), P("dropped his squeegee", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("pronoun_reference", 2, 1, 11,
      "Gran passed Jonah the binoculars just as he spotted the heron landing.",
      "Who spotted the heron?",
      [K("Jonah"), P("Gran", "D-VISUAL-NEIGHBOR"), P("a birdwatcher", "D-PLAUSIBLE-UNSUPPORTED"), P("nobody saw it", "D-OPPOSITE")], { retention: true })
  ].map(item => (LITERAL_CELLS.has(item.u)
    // Single-sentence literal cells: the answer being findable in the sentence
    // IS the construct (match the question to the stated who/what/where/action),
    // so the surface-match oracle is expected to align here. The integration
    // cells (two_clause, pronoun_reference, best_restatement) stay leak-gated.
    ? { ...item, scannerExpected: true }
    : item))
};
