// Literal meanings, image matches, clause relations, reference and restatement.
// Every level contains 32 mastery items (16 per phase) and 8 reserves.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, sentence, prompt, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage: sentence, prompt, choices, media: "text",
  ...(u === "pronoun_reference" ? { copyExempt: "pronoun-reference-label" } : {}),
  ...extra
});
const scene = (ph, v, imageKey, imageAlt, choices, extra = {}) => ({
  u: "picture_match",
  lvl: 1,
  ph,
  v,
  fmt: "COMPREHENSION",
  cell: "picture_match",
  prompt: "Which sentence tells about this picture?",
  spoken: "Look carefully at the picture. Which sentence tells about it?",
  choices,
  media: "image-required",
  img: imageKey,
  imgAlt: imageAlt,
  mediaRole: "scoring-evidence",
  evidenceModality: "image+sentence",
  constructClaim: "picture_to_sentence_meaning",
  suppressStimulusAudio: true,
  ...extra
});

export default {
  skillId: "sentence_comprehension",
  skillName: "Sentence Comprehension",
  items: [
    // ===== L1 · literal_who_what (8) =====
    it("literal_who_what", 1, 1, 1,
      "Granny Bola planted red flowers beside the garden path.",
      "What did Granny Bola plant?",
      [K("red flowers along the garden path"), P("red flowers far from the garden path", "D-PLAUSIBLE-UNSUPPORTED"), P("green beans along the garden path", "D-PLAUSIBLE-UNSUPPORTED"), P("green beans far from the garden path", "D-OPPOSITE")]),
    it("literal_who_what", 1, 1, 2,
      "The dentist gave Milo a sticker for sitting calmly.",
      "What did Milo get from the dentist?",
      [K("a sticker as a reward"), P("a toy as a reward", "D-PLAUSIBLE-UNSUPPORTED"), P("a brush for his teeth", "D-PLAUSIBLE-UNSUPPORTED"), P("a sticker for his sister", "D-OPPOSITE")]),
    it("literal_who_what", 1, 1, 3,
      "Our mail carrier whistles music along the whole street.",
      "Who whistles along the street?",
      [K("the person who brings letters"), P("the person who sells bread", "D-PLAUSIBLE-UNSUPPORTED"), P("the person who drives buses", "D-PLAUSIBLE-UNSUPPORTED"), P("the person who sweeps paths", "D-OPPOSITE")]),
    it("literal_who_what", 1, 1, 4,
      "Baby Ren stacked four wooden blocks by himself.",
      "Who stacked the four blocks?",
      [K("Ren did it alone"), P("Ren and his dad", "D-PLAUSIBLE-UNSUPPORTED"), P("Ren and his sister", "D-PLAUSIBLE-UNSUPPORTED"), P("Ren and his friend", "D-OPPOSITE")]),
    it("literal_who_what", 1, 2, 5,
      "Uncle Dip burned two slices of toast before breakfast.",
      "What went wrong before breakfast?",
      [K("his toast got too dark"), P("his toast fell onto the floor", "D-PLAUSIBLE-UNSUPPORTED"), P("his tea spilled on the table", "D-PLAUSIBLE-UNSUPPORTED"), P("his cups broke on the floor", "D-OPPOSITE")]),
    it("literal_who_what", 1, 2, 6,
      "The twins painted their bedroom door bright orange.",
      "What did the twins paint?",
      [K("the entrance to their bedroom"), P("the inside wall of their bedroom", "D-PLAUSIBLE-UNSUPPORTED"), P("the entrance to their kitchen", "D-PLAUSIBLE-UNSUPPORTED"), P("the inside wall of their kitchen", "D-OPPOSITE")]),
    it("literal_who_what", 1, 2, 7,
      "A magpie took the shiny bottle top from outside.",
      "What did the bird take?",
      [K("the top from a bottle"), P("the side of a box", "D-PLAUSIBLE-UNSUPPORTED"), P("the lid from a jar", "D-PLAUSIBLE-UNSUPPORTED"), P("the handle of a cup", "D-OPPOSITE")]),
    it("literal_who_what", 1, 2, 8,
      "Miss Faro fixed a wobbly table with folded card.",
      "What did Miss Faro fix?",
      [K("a table that was not steady"), P("a chair that was not steady", "D-PLAUSIBLE-UNSUPPORTED"), P("a table with a wet top", "D-PLAUSIBLE-UNSUPPORTED"), P("a chair with a torn seat", "D-OPPOSITE")]),

    // ===== L1 · literal_where_when (8) =====
    it("literal_where_when", 1, 1, 1,
      "The choir practices in the hall every Tuesday.",
      "When does the choir practice?",
      [K("on Tuesday each week"), P("on Friday each week", "D-PLAUSIBLE-UNSUPPORTED"), P("on Monday each week", "D-PLAUSIBLE-UNSUPPORTED"), P("on Sunday each week", "D-OPPOSITE")]),
    it("literal_where_when", 1, 1, 2,
      "Dad stores his glasses in an empty fruit bowl.",
      "Where does Dad keep his glasses?",
      [K("inside a bowl for fruit"), P("beside a bowl for fruit", "D-PLAUSIBLE-UNSUPPORTED"), P("inside a box for toys", "D-PLAUSIBLE-UNSUPPORTED"), P("beside a box for toys", "D-OPPOSITE")]),
    it("literal_where_when", 1, 1, 3,
      "The frog hid under the largest pond leaf.",
      "Where did the frog hide?",
      [K("below the biggest leaf"), P("above the biggest leaf", "D-PLAUSIBLE-UNSUPPORTED"), P("below the smallest leaf", "D-PLAUSIBLE-UNSUPPORTED"), P("above the smallest leaf", "D-OPPOSITE")]),
    it("literal_where_when", 1, 1, 4,
      "Swimming lessons start after lunch every Friday.",
      "When do swimming lessons start?",
      [K("when Friday’s lunch is over"), P("before Friday’s lunch has started", "D-PLAUSIBLE-UNSUPPORTED"), P("when Monday’s lunch is over", "D-PLAUSIBLE-UNSUPPORTED"), P("before Monday’s lunch has started", "D-OPPOSITE")]),
    it("literal_where_when", 1, 2, 5,
      "Mom parks her bike behind the recycling bins.",
      "Where does Mom park her bike?",
      [K("at the back of the bins"), P("at the front of the bins", "D-PLAUSIBLE-UNSUPPORTED"), P("on the left of the bins", "D-PLAUSIBLE-UNSUPPORTED"), P("on the right of the bins", "D-OPPOSITE")]),
    it("literal_where_when", 1, 2, 6,
      "The market opens at seven in the morning.",
      "When does the market first open?",
      [K("at seven before lunch"), P("at seven after lunch", "D-PLAUSIBLE-UNSUPPORTED"), P("at nine before lunch", "D-PLAUSIBLE-UNSUPPORTED"), P("at nine after lunch", "D-OPPOSITE")]),
    it("literal_where_when", 1, 2, 7,
      "Grandpa naps in the striped chair beside the roses.",
      "Where does Grandpa nap?",
      [K("on the chair near the flowers"), P("on the chair near the window", "D-PLAUSIBLE-UNSUPPORTED"), P("on the bench near the flowers", "D-PLAUSIBLE-UNSUPPORTED"), P("on the bench near the window", "D-OPPOSITE")]),
    it("literal_where_when", 1, 2, 8,
      "The kitten was found inside the tall cupboard.",
      "Where was the kitten found?",
      [K("in the cupboard"), P("on the cupboard", "D-PLAUSIBLE-UNSUPPORTED"), P("by the cupboard", "D-PLAUSIBLE-UNSUPPORTED"), P("under the cupboard", "D-OPPOSITE")]),

    // ===== L1 · picture_match (8) — pick the sentence that fits the scene =====
    scene(1, 1, "scene-girl-jumps-puddle", "A girl in yellow rain boots jumping over a puddle.",
      [K("A girl in rain boots jumps over a puddle."),
       P("A girl sleeps in her warm bed.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("A boy in rain boots fills a puddle.", "D-VISUAL-NEIGHBOR"),
       P("A girl paints a picture of rain.", "D-TOPIC-ADJACENT")]),
    scene(1, 2, "scene-boys-ladder-bakery", "Two boys carrying a long ladder past a bakery.",
      [K("Two boys carry a ladder past the bakery."),
       P("Two boys buy buns at the bakery.", "D-TOPIC-ADJACENT"),
       P("One boy climbs a ladder at home.", "D-VISUAL-NEIGHBOR"),
       P("Two bakers carry a table.", "D-VISUAL-NEIGHBOR")]),
    scene(1, 3, "scene-cat-umbrella", "A cat asleep inside an open umbrella.",
      [K("A cat sleeps inside an open umbrella."),
       P("A cat hides from the rain indoors.", "D-TOPIC-ADJACENT"),
       P("A dog sleeps under an umbrella.", "D-VISUAL-NEIGHBOR"),
       P("A cat plays with a ball of wool.", "D-PLAUSIBLE-UNSUPPORTED")]),
    scene(1, 4, "scene-grandad-child-red-kite", "A grandpa and one child flying one red kite together.",
      [K("Grandpa and a child fly a red kite."),
       P("Grandpa buys a child a red ball.", "D-VISUAL-NEIGHBOR"),
       P("Two children fly two kites.", "D-VISUAL-NEIGHBOR"),
       P("Grandpa reads about kites.", "D-TOPIC-ADJACENT")]),
    scene(2, 5, "scene-red-sock-falling", "One red sock dropping from a full clothesline toward the grass.",
      [K("One red sock falls from the clothesline."),
       P("A red sock hangs safely on the line.", "D-OPPOSITE"),
      P("The empty clothesline swings in the wind.", "D-VISUAL-NEIGHBOR"),
       P("Someone irons a red shirt.", "D-TOPIC-ADJACENT")]),
    scene(2, 6, "scene-ducks-ice-cream-van", "Exactly three ducks waiting at an ice cream truck.",
      [K("Three ducks wait in line at the ice cream truck."),
       P("Three children feed ducks at the pond.", "D-VISUAL-NEIGHBOR"),
       P("An ice cream truck drives past a farm.", "D-TOPIC-ADJACENT"),
       P("One duck swims away from a boat.", "D-PLAUSIBLE-UNSUPPORTED")]),
    scene(2, 7, "scene-boy-giant-jelly", "A boy holding a tray with a huge red jelly above his head.",
      [K("A boy holds up a huge red jelly."), P("A boy eats from a small red bowl.", "D-PLAUSIBLE-UNSUPPORTED"), P("A boy drops a tray of red apples.", "D-PLAUSIBLE-UNSUPPORTED"), P("A boy washes a tall empty glass.", "D-OPPOSITE")]),
    scene(2, 8, "scene-snowman-sunglasses", "A snowman wearing sunglasses on a sunny winter day.",
      [K("A snowman wears sunglasses in the sunshine."),
       P("A snowman melts away in the rain.", "D-VISUAL-NEIGHBOR"),
       P("A child wears sunglasses at the beach.", "D-VISUAL-NEIGHBOR"),
       P("A snowman wears a warm scarf at night.", "D-VISUAL-NEIGHBOR")]),

    // ===== L1 · literal_action (8) =====
    it("literal_action", 1, 1, 1,
      "Pia tiptoed past the sleeping dog.",
      "How did Pia move past the dog?",
      [K("she stepped quietly on her toes"), P("she ran quickly on the grass", "D-PLAUSIBLE-UNSUPPORTED"), P("she jumped over its soft bed", "D-PLAUSIBLE-UNSUPPORTED"), P("she crawled under its low bench", "D-OPPOSITE")]),
    it("literal_action", 1, 1, 2,
      "The waiter carried six plates on one arm.",
      "How did the waiter carry the plates?",
      [K("balanced on his arm"), P("stacked on a tray", "D-PLAUSIBLE-UNSUPPORTED"), P("packed in a box", "D-PLAUSIBLE-UNSUPPORTED"), P("spread on a cart", "D-OPPOSITE")]),
    it("literal_action", 1, 1, 3,
      "Grandma squeezed three lemons to make a drink.",
      "How did Grandma make juice from the lemons?",
      [K("she pressed the fruit"), P("she peeled the fruit", "D-PLAUSIBLE-UNSUPPORTED"), P("she boiled the fruit", "D-PLAUSIBLE-UNSUPPORTED"), P("she chopped the fruit", "D-OPPOSITE")]),
    it("literal_action", 1, 1, 4,
      "The goalkeeper tipped the ball above the goal.",
      "Where did the goalkeeper send the ball?",
      [K("over the goal"), P("into the goal", "D-PLAUSIBLE-UNSUPPORTED"), P("beside the goal", "D-PLAUSIBLE-UNSUPPORTED"), P("under the goal", "D-OPPOSITE")]),
    it("literal_action", 1, 2, 5,
      "Kofi taped the torn map back together.",
      "What did Kofi do to the map?",
      [K("joined its torn parts with tape"), P("cut its folded parts with scissors", "D-PLAUSIBLE-UNSUPPORTED"), P("drew its missing roads with pencil", "D-PLAUSIBLE-UNSUPPORTED"), P("hung its top edge with string", "D-OPPOSITE")]),
    it("literal_action", 1, 2, 6,
      "The parrot copied Grandpa's cough all afternoon.",
      "What sound did the parrot make?",
      [K("the same cough as Grandpa"), P("the same song as Grandpa", "D-PLAUSIBLE-UNSUPPORTED"), P("a cough different from Grandpa's", "D-PLAUSIBLE-UNSUPPORTED"), P("a song different from Grandpa's", "D-OPPOSITE")]),
    it("literal_action", 1, 2, 7,
      "Ada rolled the biggest snowball in the street.",
      "How large was Ada's snowball?",
      [K("larger than the others nearby"), P("smaller than the others nearby", "D-PLAUSIBLE-UNSUPPORTED"), P("the same size as the others", "D-PLAUSIBLE-UNSUPPORTED"), P("half the size of the others", "D-OPPOSITE")]),
    it("literal_action", 1, 2, 8,
      "The librarian stamped tomorrow's date on today's book.",
      "Which date did the librarian stamp?",
      [K("the next day's date"), P("the same day's date", "D-PLAUSIBLE-UNSUPPORTED"), P("the last day's date", "D-PLAUSIBLE-UNSUPPORTED"), P("the next month's date", "D-OPPOSITE")]),

    // ===== L2 · two_clause (8) =====
    it("two_clause", 2, 1, 1,
      "Because the lift was broken, the movers used the stairs.",
      "Why did the movers use the stairs?",
      [K("the lift could not work"), P("the stairs would save time", "D-PLAUSIBLE-UNSUPPORTED"), P("the lift had no space", "D-PLAUSIBLE-UNSUPPORTED"), P("the stairs were less steep", "D-OPPOSITE")], { note: "Connect the broken lift to the alternative route." }),
    it("two_clause", 2, 1, 2,
      "Rosa wore big borrowed boots, so her footprints looked huge.",
      "Why did Rosa leave huge footprints?",
      [K("her boots were larger than her feet"), P("her feet were larger than her boots", "D-PLAUSIBLE-UNSUPPORTED"), P("the ground was softer than usual", "D-PLAUSIBLE-UNSUPPORTED"), P("the mud was deeper than usual", "D-OPPOSITE")], { note: "Distinguish the size of the borrowed boots from Rosa's own feet." }),
    it("two_clause", 2, 1, 3,
      "The picnic moved inside, but everyone still enjoyed sharing the cake.",
      "How did people feel after moving inside?",
      [K("pleased to share the cake"), P("cross about sharing the cake", "D-PLAUSIBLE-UNSUPPORTED"), P("worried about finding a cake", "D-PLAUSIBLE-UNSUPPORTED"), P("surprised to find a cake", "D-OPPOSITE")], { note: "Follow the contrast instead of assuming the move spoiled the picnic." }),
    it("two_clause", 2, 1, 4,
      "The sea looked calm, but a sign warned against swimming.",
      "What does the sentence tell us about swimming?",
      [K("the calm water might be unsafe"), P("the calm water must be safe", "D-PLAUSIBLE-UNSUPPORTED"), P("the calm water would be warm", "D-PLAUSIBLE-UNSUPPORTED"), P("the calm water would be shallow", "D-OPPOSITE")], { note: "Resolve appearance versus explicit warning without requiring flag knowledge." }),
    it("two_clause", 2, 2, 5,
      "Jin saved his money to buy Mom a birthday plant.",
      "Why did Jin save his money?",
      [K("for a plant to give Mom"), P("for a plant to keep himself", "D-PLAUSIBLE-UNSUPPORTED"), P("for a present from his mom", "D-PLAUSIBLE-UNSUPPORTED"), P("for a present from his friend", "D-OPPOSITE")], { note: "Link the purpose clause to the recipient." }),
    it("two_clause", 2, 2, 6,
      "The bench had wet paint, so a sign warned people away.",
      "Why was the sign there?",
      [K("to keep people off wet paint"), P("to help people find a seat", "D-PLAUSIBLE-UNSUPPORTED"), P("to show people a new path", "D-PLAUSIBLE-UNSUPPORTED"), P("to ask people to paint benches", "D-OPPOSITE")], { note: "Connect the warning to the still-wet surface." }),
    it("two_clause", 2, 2, 7,
      "Tara practiced in goal, but played forward in the final match.",
      "Where did Tara play in the final match?",
      [K("up front with the attackers"), P("in goal with the gloves", "D-PLAUSIBLE-UNSUPPORTED"), P("at the side as a helper", "D-PLAUSIBLE-UNSUPPORTED"), P("on the bench as a spare", "D-OPPOSITE")], { note: "Use the contrast to separate practice from the match." }),
    it("two_clause", 2, 2, 8,
      "The bread smelled good, but nobody ate it before the fair.",
      "What happened to the bread before the fair?",
      [K("it was left for later"), P("it was eaten straight away", "D-PLAUSIBLE-UNSUPPORTED"), P("it was thrown in the bin", "D-PLAUSIBLE-UNSUPPORTED"), P("it was cut for a picnic", "D-OPPOSITE")], { note: "Use the second clause instead of inferring eating from the smell." }),

    // ===== L2 · pronoun_reference (8) =====
    it("pronoun_reference", 2, 1, 1,
      "Maya passed her brother the brush because he wanted to paint.",
      "Who wanted to paint?",
      [K("Maya's brother"), P("Maya herself", "D-PLAUSIBLE-UNSUPPORTED"), P("Maya's sister", "D-PLAUSIBLE-UNSUPPORTED"), P("Maya's mother", "D-OPPOSITE")],
      { note: "Resolve he using the stated brother relationship." }),
    it("pronoun_reference", 2, 1, 2,
      "The gull followed the fishing boat until it sailed away.",
      "What sailed away?",
      [K("the fishing boat"), P("the following gull", "D-PLAUSIBLE-UNSUPPORTED"), P("a passing ferry", "D-PLAUSIBLE-UNSUPPORTED"), P("a small sailboat", "D-OPPOSITE")],
      { note: "Use the verb sailed to select the correct singular referent." }),
    it("pronoun_reference", 2, 1, 3,
      "Sam lent Maya his pencil, and she chewed its end.",
      "Whose pencil did Maya chew?",
      [K("Sam's pencil"), P("Maya's pencil", "D-PLAUSIBLE-UNSUPPORTED"), P("the teacher's pencil", "D-PLAUSIBLE-UNSUPPORTED"), P("her brother's pencil", "D-OPPOSITE")], { note: "Resolve possession across the two clauses." }),
    it("pronoun_reference", 2, 1, 4,
      "The twins visited Auntie Vee, and she taught them a game.",
      "Who taught the game?",
      [K("Auntie Vee"), P("the twins", "D-PLAUSIBLE-UNSUPPORTED"), P("their mother", "D-PLAUSIBLE-UNSUPPORTED"), P("their grandpa", "D-OPPOSITE")], { note: "Resolve she versus plural them." }),
    it("pronoun_reference", 2, 2, 5,
      "Nia put a seedling beside two cacti, but it grew taller.",
      "What grew taller?",
      [K("the seedling"), P("the two cacti", "D-PLAUSIBLE-UNSUPPORTED"), P("the plant shelf", "D-PLAUSIBLE-UNSUPPORTED"), P("the flower pot", "D-OPPOSITE")],
      { note: "Use singular it rather than the nearer plural cacti." }),
    it("pronoun_reference", 2, 2, 6,
      "Carmen showed Grandpa the robot that she built from boxes.",
      "Who built the robot?",
      [K("Carmen"), P("Grandpa", "D-PLAUSIBLE-UNSUPPORTED"), P("her dad", "D-PLAUSIBLE-UNSUPPORTED"), P("her brother", "D-OPPOSITE")],
      { note: "Resolve she through a relative clause." }),
    it("pronoun_reference", 2, 2, 7,
      "The keeper fed the penguins, so they were full before visitors arrived.",
      "Who was full?",
      [K("the penguins"), P("the visitors", "D-PLAUSIBLE-UNSUPPORTED"), P("the keepers", "D-PLAUSIBLE-UNSUPPORTED"), P("the seals", "D-OPPOSITE")], { note: "Resolve plural they across cause and later arrival." }),
    it("pronoun_reference", 2, 2, 8,
      "Effie waved to her cousin until the train passed him.",
      "Who did the train pass?",
      [K("Effie's cousin"), P("Effie herself", "D-PLAUSIBLE-UNSUPPORTED"), P("the train driver", "D-PLAUSIBLE-UNSUPPORTED"), P("the ticket seller", "D-OPPOSITE")], { note: "Resolve him as the person on the platform." }),

    // ===== L2 · best_restatement (8) =====
    it("best_restatement", 2, 1, 1,
      "By lunchtime, every ticket for the puppet show had sold.",
      "Which sentence means the SAME?",
      [K("No tickets were left by lunch."), P("Some tickets were left after lunch.", "D-PLAUSIBLE-UNSUPPORTED"), P("New tickets went on sale at lunch.", "D-PLAUSIBLE-UNSUPPORTED"), P("The puppet show was canceled at lunch.", "D-OPPOSITE")]),
    it("best_restatement", 2, 1, 2,
      "Ravi knows the route to the pool very well.",
      "Which sentence means the SAME?",
      [K("Ravi can find his way there easily."), P("Ravi needs help to find his way.", "D-PLAUSIBLE-UNSUPPORTED"), P("Ravi has never gone to the pool.", "D-PLAUSIBLE-UNSUPPORTED"), P("Ravi always takes a new route there.", "D-OPPOSITE")]),
    it("best_restatement", 2, 1, 3,
      "The class stood up before the final whistle ended the match.",
      "Which sentence means the SAME?",
      [K("Everyone rose before the match finished."), P("Everyone rose after the match finished.", "D-PLAUSIBLE-UNSUPPORTED"), P("Everyone left before the match finished.", "D-PLAUSIBLE-UNSUPPORTED"), P("Everyone sat until the match finished.", "D-OPPOSITE")]),
    it("best_restatement", 2, 1, 4,
      "Dad said the soup had a very strong smell.",
      "Which sentence means the SAME?",
      [K("Dad could smell the soup clearly."), P("Dad could hardly smell the soup.", "D-PLAUSIBLE-UNSUPPORTED"), P("Dad wanted soup with more salt.", "D-PLAUSIBLE-UNSUPPORTED"), P("Dad said the soup was too cold.", "D-OPPOSITE")]),
    it("best_restatement", 2, 2, 5,
      "Omar had stopped waiting calmly before the late bus came.",
      "Which sentence means the SAME?",
      [K("Omar grew impatient while waiting for the bus."), P("Omar stayed calm while waiting for the bus.", "D-PLAUSIBLE-UNSUPPORTED"), P("Omar missed the bus because he arrived late.", "D-PLAUSIBLE-UNSUPPORTED"), P("Omar left calmly before the bus arrived.", "D-OPPOSITE")]),
    it("best_restatement", 2, 2, 6,
      "The new puppy chewed every shoe in the house.",
      "Which sentence means the SAME?",
      [K("No shoe escaped the puppy's chewing."), P("Some shoes escaped the puppy's chewing.", "D-PLAUSIBLE-UNSUPPORTED"), P("The puppy only chewed its own toys.", "D-PLAUSIBLE-UNSUPPORTED"), P("The puppy carried shoes without chewing them.", "D-OPPOSITE")]),
    it("best_restatement", 2, 2, 7,
      "Lila found it hard to keep the secret until Friday.",
      "Which sentence means the SAME?",
      [K("Not telling the secret was difficult."), P("Remembering the secret was very easy.", "D-PLAUSIBLE-UNSUPPORTED"), P("Telling the secret made Lila happy.", "D-PLAUSIBLE-UNSUPPORTED"), P("Hearing the secret made Lila worried.", "D-OPPOSITE")]),
    it("best_restatement", 2, 2, 8,
      "Hailstones bounced all over the trampoline during the storm.",
      "Which sentence means the SAME?",
      [K("Falling ice jumped across the trampoline."), P("Falling leaves covered the whole trampoline.", "D-PLAUSIBLE-UNSUPPORTED"), P("Heavy rain washed under the trampoline.", "D-PLAUSIBLE-UNSUPPORTED"), P("Strong wind lifted the whole trampoline.", "D-OPPOSITE")]),

    // ===== RETENTION (8 + 8) =====
    it("literal_who_what", 1, 1, 9,
      "Auntie Meg won a prize for her huge pumpkin.",
      "What won Auntie Meg a prize?",
      [K("her very large pumpkin"), P("her very large carrot", "D-PLAUSIBLE-UNSUPPORTED"), P("her very small pumpkin", "D-PLAUSIBLE-UNSUPPORTED"), P("her very small carrot", "D-OPPOSITE")], { retention: true }),
    it("literal_where_when", 1, 1, 10,
      "The school hamster sleeps all day and runs overnight.",
      "When does the school hamster run?",
      [K("during the night"), P("during the day", "D-PLAUSIBLE-UNSUPPORTED"), P("only before lunch", "D-PLAUSIBLE-UNSUPPORTED"), P("only after lunch", "D-OPPOSITE")], { retention: true }),
    scene(1, 9, "scene-small-dog-leads-tall-man", "A very small dog leading a very tall man down a street.",
      [K("A small dog leads a tall man down the street."),
       P("A tall man carries a small dog.", "D-VISUAL-NEIGHBOR"),
       P("Two dogs chase a ball.", "D-PLAUSIBLE-UNSUPPORTED"),
       P("A man buys a dog lead.", "D-TOPIC-ADJACENT")], { retention: true }),
    it("literal_action", 1, 1, 10,
      "The baker hid a coin inside one bread roll.",
      "Where did the baker put the coin?",
      [K("in one bread roll"), P("by one bread roll", "D-PLAUSIBLE-UNSUPPORTED"), P("under the bread tray", "D-PLAUSIBLE-UNSUPPORTED"), P("behind the bread tray", "D-OPPOSITE")], { retention: true }),
    it("literal_who_what", 1, 2, 10,
      "Little Ivo taught the parrot to say good morning.",
      "Who taught the bird its greeting?",
      [K("the child called Ivo"), P("the child’s mother", "D-PLAUSIBLE-UNSUPPORTED"), P("the child’s neighbour", "D-PLAUSIBLE-UNSUPPORTED"), P("the child’s grandfather", "D-OPPOSITE")], { retention: true }),
    it("literal_where_when", 1, 2, 9,
      "Robi’s sports clothes fill a drawer below his bed.",
      "Where does Robi keep his sports clothes?",
      [K("in the drawer under his bed"), P("in the basket under his bed", "D-PLAUSIBLE-UNSUPPORTED"), P("in the drawer beside his bed", "D-PLAUSIBLE-UNSUPPORTED"), P("in the basket beside his bed", "D-OPPOSITE")], { retention: true }),
    scene(2, 10, "scene-family-asleep-film", "A family asleep together on a sofa beside a television.",
      [K("The family sleeps together on the sofa."), P("The family eats together at the table.", "D-PLAUSIBLE-UNSUPPORTED"), P("The family watches television from the sofa.", "D-PLAUSIBLE-UNSUPPORTED"), P("The family reads together on the floor.", "D-OPPOSITE")], { retention: true }),
    it("literal_action", 1, 2, 9,
      "Mrs. Cho got the ball down with a mop.",
      "What did Mrs. Cho use to reach the ball?",
      [K("a mop with a long handle"), P("a pole with a small hook", "D-PLAUSIBLE-UNSUPPORTED"), P("a broom with a long handle", "D-PLAUSIBLE-UNSUPPORTED"), P("a net with a small hoop", "D-OPPOSITE")], { retention: true }),
    it("two_clause", 2, 1, 9,
      "Baby Bo blew the candles out, so Mom lit them again.",
      "Why did Mom light the candles again?",
      [K("Bo had blown them out"), P("Bo had put them away", "D-PLAUSIBLE-UNSUPPORTED"), P("the wind had blown them out", "D-PLAUSIBLE-UNSUPPORTED"), P("the rain had made them wet", "D-OPPOSITE")], { retention: true , note: "Connect an action to a repeated action."}),
    it("two_clause", 2, 2, 10,
      "The wait was long, but Grandma thought the dumplings were worth it.",
      "What did Grandma think about waiting?",
      [K("the food made the wait worthwhile"), P("the food made the wait pointless", "D-PLAUSIBLE-UNSUPPORTED"), P("the line was too short to join", "D-PLAUSIBLE-UNSUPPORTED"), P("the line was too noisy to join", "D-OPPOSITE")], { retention: true , note: "Interpret a contrast in opinion after a long wait."}),
    it("pronoun_reference", 2, 1, 9,
      "Priya read to her brother until he fell asleep.",
      "Who fell asleep?",
      [K("her brother"), P("Priya", "D-PLAUSIBLE-UNSUPPORTED"), P("her mother", "D-PLAUSIBLE-UNSUPPORTED"), P("her sister", "D-OPPOSITE")], { retention: true , note: "Resolve he at the end of the subordinate clause."}),
    it("pronoun_reference", 2, 2, 10,
      "The coach thanked the parents because they had packed the cones.",
      "Who packed the cones?",
      [K("the parents"), P("the coach", "D-PLAUSIBLE-UNSUPPORTED"), P("the players", "D-PLAUSIBLE-UNSUPPORTED"), P("the helpers", "D-OPPOSITE")], { retention: true , note: "Resolve they from the people thanked, not the subject."}),
    it("best_restatement", 2, 1, 10,
      "The tide had covered the sandcastle by late afternoon.",
      "Which sentence means the SAME?",
      [K("The sea was over it before evening."), P("The sea stayed below it until evening.", "D-PLAUSIBLE-UNSUPPORTED"), P("The sea washed it away after dark.", "D-PLAUSIBLE-UNSUPPORTED"), P("The sea never reached it that day.", "D-OPPOSITE")], { retention: true }),
    it("best_restatement", 2, 2, 9,
      "The cheese smelled so bad that everyone opened the windows.",
      "Which sentence means the SAME?",
      [K("People let fresh air in because of the cheese."), P("People let fresh air in to cool the cheese.", "D-PLAUSIBLE-UNSUPPORTED"), P("People shut the windows to hide the cheese smell.", "D-PLAUSIBLE-UNSUPPORTED"), P("People shut the windows because the cheese was cold.", "D-OPPOSITE")], { retention: true }),
    it("two_clause", 2, 1, 11,
      "The cleaner kept working, but waved to the passing children.",
      "What did the cleaner do while working?",
      [K("greeted the children with a wave"), P("joined the children on their walk", "D-PLAUSIBLE-UNSUPPORTED"), P("asked the children for a cloth", "D-PLAUSIBLE-UNSUPPORTED"), P("told the children to step back", "D-OPPOSITE")], { retention: true , note: "Both actions happen together despite the contrast."}),
    it("pronoun_reference", 2, 1, 11,
      "Grandma passed Jonah the glasses after he spotted a bird.",
      "Who spotted the bird?",
      [K("Jonah"), P("Grandma", "D-PLAUSIBLE-UNSUPPORTED"), P("a birdwatcher", "D-PLAUSIBLE-UNSUPPORTED"), P("a gardener", "D-OPPOSITE")], { retention: true , note: "Resolve he and distinguish receiving from noticing."}),
    // Fresh retry stock: four additional questions in each phase.
    {
      "u": "two_clause",
      "lvl": 2,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "two_clause",
      "passage": "The lift was full, so Mei waited for the next one. She reached the top floor after her friends.",
      "prompt": "Why did Mei wait?",
      "choices": [
        {
          "t": "there was no room inside the lift",
          "r": "KEY",
          "k": true
        },
        {
          "t": "her friends were waiting on the ground floor",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "the lift could not reach the top floor",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "she wanted to use the stairs instead",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "two_clause",
      "lvl": 2,
      "ph": 1,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "two_clause",
      "passage": "Leo carried the empty tray, but Hana carried the drinks. Both took their things to the picnic table.",
      "prompt": "What did Hana carry?",
      "choices": [K("the drinks taken to the table"), P("the empty tray taken to the table", "D-PLAUSIBLE-UNSUPPORTED"), P("the picnic table carried to the garden", "D-PLAUSIBLE-UNSUPPORTED"), P("both the drinks and the empty tray", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "pronoun_reference",
      "lvl": 2,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "pronoun_reference",
      "passage": "Nina showed her drawings to Alex. He chose the picture with a boat on it.",
      "prompt": "Who does \"He\" mean?",
      "choices": [K("Alex, the person viewing Nina’s pictures"), P("Nina, the person showing Alex her pictures", "D-PLAUSIBLE-UNSUPPORTED"), P("the person sailing in the drawn boat", "D-PLAUSIBLE-UNSUPPORTED"), P("the teacher looking over Nina’s shoulder", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "best_restatement",
      "lvl": 2,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "best_restatement",
      "passage": "The gate stays shut unless an adult opens it. Children wait outside until that happens.",
      "prompt": "Which sentence has the same meaning?",
      "choices": [
        {
          "t": "Children can enter after an adult opens the gate.",
          "r": "KEY",
          "k": true
        },
        {
          "t": "Children can open the gate whenever they reach it.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "The gate closes only after the children have left.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "An adult must wait outside while children go in.",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "two_clause",
      "lvl": 2,
      "ph": 2,
      "v": 22,
      "fmt": "COMPREHENSION",
      "cell": "two_clause",
      "passage": "Before the visitors arrived, Arlo moved his models onto a shelf. He left room on the table for their bags.",
      "prompt": "When did Arlo move his models?",
      "choices": [
        {
          "t": "while he was preparing for the visitors",
          "r": "KEY",
          "k": true
        },
        {
          "t": "after the visitors put down their bags",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "while the visitors were leaving the house",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "after he had shown them every model",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "pronoun_reference",
      "lvl": 2,
      "ph": 2,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "pronoun_reference",
      "passage": "Amina gave the old coats to her neighbours. They thanked her and carried them to the shelter.",
      "prompt": "Who does \"They\" refer to?",
      "choices": [
        {
          "t": "the neighbours receiving the coats",
          "r": "KEY",
          "k": true
        },
        {
          "t": "Amina carrying her old clothes",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "the people already at the shelter",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "the coats lying in the bag",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "best_restatement",
      "lvl": 2,
      "ph": 2,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "best_restatement",
      "passage": "Only the children with permission slips could join the walk. Everyone else stayed at school with Ms Moss.",
      "prompt": "Which sentence has the same meaning?",
      "choices": [
        {
          "t": "A permission slip was needed to go on the walk.",
          "r": "KEY",
          "k": true
        },
        {
          "t": "Every child went walking before returning to the school.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "Children staying at school had all brought permission slips.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "Ms Moss took the whole class out for a walk.",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "best_restatement",
      "lvl": 2,
      "ph": 2,
      "v": 22,
      "fmt": "COMPREHENSION",
      "cell": "best_restatement",
      "passage": "Tara finished folding the cards before she decorated their covers. She put each finished card in an envelope.",
      "prompt": "Which sentence keeps the same order?",
      "choices": [
        {
          "t": "Tara folded, decorated, then packed each card.",
          "r": "KEY",
          "k": true
        },
        {
          "t": "Tara decorated, packed, then folded each card.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "Tara packed, folded, then decorated each card.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "Tara folded, packed, then decorated each card.",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    }
]
};
