// Sequencing — v3 authored bank (wave W2). Every passage has a NECESSARY order
// (causal or conventional), never an arbitrary list; ordinal wording is
// explicit per the instructional standards (first/second/last, before/after —
// no bare "next" on unfinished sequences). L1 = 3 orderable events; L2 = 4.
// D-SEQUENCE-SWAP distractors are real events at the wrong position.
//
// Topic registry: getting dressed for snow, planting seeds, washing the dog,
// pancake making, letter to grandma, bike puncture, library visit, paper-mache
// mask, tooth brushing chart, seed to salad, tent pitching, hot chocolate,
// school photo day, bird feeder prep, birthday card, fire drill, apple crumble,
// wormery build, kite build, car wash, museum trip, jam making, haircut,
// present wrapping, treasure hunt, recycling sort, class trip lunch, shadow
// tracing, boot cleaning, egg hatching diary, bridge of books, dentist visit.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, prompt, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage, prompt, choices, media: "text", ...extra
});

// The old sequence panels were sliced from larger mosaics; direct review found
// repeated adjacent-panel contamination. Sequence is therefore assessed from
// the short story and explicit action phrases, not from cropped or inferential
// pictures. Keep the unused image-key argument so the item list remains easy
// to compare with its historical source while no visual path can become active.
const sequenceItem = (u, ph, v, passage, events, _imageKeys, retention = false) => {
  const joined = order => order.join(" → ");
  return {
    u,
    lvl: 1,
    ph,
    v,
    fmt: "COMPREHENSION",
    cell: u,
    passage,
    prompt: "Which order matches the story?",
    spoken: `${passage} Which order matches the story?`,
    choices: [
      K(joined(events)),
      P(joined([events[1], events[0], events[2]]), "D-SEQUENCE-START"),
      P(joined([events[0], events[2], events[1]]), "D-SEQUENCE-END"),
      P(joined([...events].reverse()), "D-SEQUENCE-REVERSE")
    ],
    media: "text",
    evidenceModality: "audio+text",
    constructClaim: "story_event_order",
    displayPassageDuringResponse: true,
    retention
  };
};

const textSequenceItem = (u, ph, v, passage, events, retention = false) => {
  const joined = order => order.join(" → ");
  const prompt = "Which order matches the actions?";
  return {
    u,
    lvl: 1,
    ph,
    v,
    fmt: "COMPREHENSION",
    cell: u,
    passage,
    prompt,
    spoken: `${passage} ${prompt}`,
    choices: [
      K(joined(events)),
      P(joined([events[1], events[0], events[2]]), "D-SEQUENCE-START"),
      P(joined([events[0], events[2], events[1]]), "D-SEQUENCE-END"),
      P(joined([...events].reverse()), "D-SEQUENCE-REVERSE")
    ],
    media: "text",
    evidenceModality: "audio+text",
    constructClaim: "story_event_order",
    displayPassageDuringResponse: true,
    retention
  };
};

const levelOnePictureSequences = [
  sequenceItem("first_event", 1, 1, "The cat jumped on the box, curled into a ball, and fell asleep.",
    ["jumped on the box", "curled into a ball", "fell asleep"],
    ["cat-jumps-on-box", "cat-curls-on-box", "cat-sleeps-on-box"]),
  sequenceItem("first_event", 1, 2, "Mia put a seed in soil, watered it, and saw a green shoot.",
    ["put in the seed", "watered the soil", "saw a green shoot"],
    ["child-plants-seed", "child-waters-seed", "seed-grows-shoot"]),
  sequenceItem("first_event", 1, 3, "Ben wet his hands, rubbed in soap, and rinsed the bubbles away.",
    ["wet his hands", "rubbed in soap", "rinsed his hands"],
    ["child-wets-hands", "child-soaps-hands", "child-rinses-hands"]),
  textSequenceItem("first_event", 1, 4,
    "Zara pulled on one sock. Then she put on its shoe. Last, she tied the laces.",
    ["pulled on a sock", "put on the shoe", "tied the laces"]),
  sequenceItem("first_event", 2, 5, "Dad put bread in the toaster, waited for it to pop, and spread butter.",
    ["put bread in", "toast popped up", "spread the butter"],
    ["bread-enters-toaster", "toast-pops-up", "butter-spread-on-toast"]),
  sequenceItem("first_event", 2, 6, "Noah threw the ball, the dog chased it, and the dog brought it back.",
    ["threw the ball", "dog chased it", "dog brought it back"],
    ["child-throws-ball", "dog-chases-ball", "dog-returns-ball"]),
  textSequenceItem("first_event", 2, 7,
    "Lina drew a circle. Then she added sun rays. Last, she colored the sun yellow.",
    ["drew a circle", "added the rays", "colored the sun"]),
  sequenceItem("first_event", 2, 8, "Omar set down blocks, stacked a tower, and smiled at the top.",
    ["set down blocks", "stacked the tower", "smiled at the tower"],
    ["child-sets-blocks", "child-stacks-tower", "child-smiles-at-tower"]),

  sequenceItem("middle_event", 1, 1, "Ava laid down bread, added cheese, and closed the sandwich.",
    ["laid down bread", "added the cheese", "closed the sandwich"],
    ["bread-on-plate", "cheese-on-bread", "closed-sandwich"]),
  textSequenceItem("middle_event", 1, 2,
    "Rain began. Eli put on his boots. Then he opened an umbrella. Last, he walked outside.",
    ["put on boots", "opened an umbrella", "walked outside"]),
  sequenceItem("middle_event", 1, 3, "The girl opened her book, read one page, and put in a bookmark.",
    ["opened the book", "read the page", "put in a bookmark"],
    ["child-opens-book", "child-reads-page", "child-adds-bookmark"]),
  sequenceItem("middle_event", 1, 4, "Kai filled a cup, drank the water, and put the cup in the sink.",
    ["filled the cup", "drank the water", "put cup in sink"],
    ["child-fills-cup", "child-drinks-water", "child-puts-cup-in-sink"]),
  sequenceItem("middle_event", 2, 5, "Mom cracked an egg, whisked it, and cooked it in the pan.",
    ["cracked the egg", "whisked the egg", "cooked the egg"],
    ["adult-cracks-egg", "adult-whisks-egg", "egg-cooks-in-pan"]),
  sequenceItem("middle_event", 2, 6, "The boy kicked the ball, it hit the goal, and his team cheered.",
    ["kicked the ball", "ball went in goal", "team cheered"],
    ["child-kicks-football", "football-enters-goal", "children-cheer-goal"]),
  textSequenceItem("middle_event", 2, 7,
    "Nia washed the muddy dog. Then she dried its fur. Last, she brushed the fur smooth.",
    ["washed the dog", "dried its fur", "brushed the fur smooth"]),
  sequenceItem("middle_event", 2, 8, "The baker mixed dough, shaped a loaf, and put it in the oven.",
    ["mixed the dough", "shaped the loaf", "put loaf in oven"],
    ["baker-mixes-dough", "baker-shapes-loaf", "baker-puts-loaf-in-oven"]),

  textSequenceItem("last_event", 1, 1,
    "Sam put toothpaste on his brush. Then he brushed his teeth. Last, he rinsed his mouth.",
    ["added toothpaste", "brushed his teeth", "rinsed his mouth"]),
  sequenceItem("last_event", 1, 2, "The child found paper, folded a plane, and flew it across the room.",
    ["found the paper", "folded a plane", "flew the plane"],
    ["child-finds-paper", "child-folds-paper-plane", "child-flies-paper-plane"]),
  sequenceItem("last_event", 1, 3, "Ivy picked an apple, washed it, and took a bite.",
    ["picked the apple", "washed the apple", "bit the apple"],
    ["child-picks-apple", "child-washes-apple", "child-bites-apple"]),
  sequenceItem("last_event", 1, 4, "The boy built a snowball, added a head, and gave the snowman a hat.",
    ["made a snowball", "added the head", "added the hat"],
    ["child-rolls-snowball", "child-builds-snowman-head", "child-adds-snowman-hat"]),
  sequenceItem("last_event", 2, 5, "Ana wrapped the gift, tied a bow, and gave it to her friend.",
    ["wrapped the gift", "tied the bow", "gave the gift"],
    ["child-wraps-gift", "child-ties-gift-bow", "child-gives-gift"]),
  sequenceItem("last_event", 2, 6, "The class dug a hole, planted the tree, and watered its roots.",
    ["dug the hole", "planted the tree", "watered the roots"],
    ["children-dig-hole", "children-plant-tree", "children-water-tree"]),
  sequenceItem("last_event", 2, 7, "Leo put trash in a bag, tied it shut, and placed it in the trash can.",
    ["filled the bag", "tied the bag", "put bag in trash can"],
    ["child-fills-rubbish-bag", "child-ties-rubbish-bag", "child-puts-bag-in-bin"]),
  sequenceItem("last_event", 2, 8, "The bus stopped, the doors opened, and the children stepped off.",
    ["bus stopped", "doors opened", "children stepped off"],
    ["school-bus-stops", "school-bus-doors-open", "children-leave-school-bus"]),

  sequenceItem("first_event", 1, 9, "Rae picked up a pencil, drew a star, and colored it red.",
    ["picked up pencil", "drew the star", "colored it red"],
    ["child-picks-up-pencil", "child-draws-star", "child-colours-red-star"], true),
  sequenceItem("middle_event", 1, 9, "Max opened the gate, led the pony through, and shut the gate.",
    ["opened the gate", "led pony through", "shut the gate"],
    ["child-opens-gate", "child-leads-pony", "child-shuts-gate"], true),
  sequenceItem("last_event", 1, 9, "The frog sat, jumped into the pond, and swam away.",
    ["frog sat", "frog jumped", "frog swam away"],
    ["frog-sits-by-pond", "frog-jumps-into-pond", "frog-swims-away"], true),
  sequenceItem("first_event", 2, 10, "Jo poured cereal, added milk, and ate breakfast.",
    ["poured cereal", "added milk", "ate breakfast"],
    ["child-pours-cereal", "child-adds-milk", "child-eats-cereal"], true),
  textSequenceItem("middle_event", 2, 10,
    "The child zipped a coat. Then the child put on a hat. Last, the child went into the snow.",
    ["zipped the coat", "put on the hat", "went into the snow"], true),
  sequenceItem("last_event", 2, 10, "Mia washed a plate, dried it, and put it on the shelf.",
    ["washed the plate", "dried the plate", "put plate on shelf"],
    ["child-washes-plate", "child-dries-plate", "child-puts-plate-on-shelf"], true)
];

export default {
  skillId: "sequencing",
  skillName: "Sequencing",
  items: [...levelOnePictureSequences, ...[
    // ========== LEVEL 1 · first_event (8) ==========
    it("first_event", 1, 1, 1,
      "Before the snowy walk, Tunde got ready. He pulled on his thick socks. Then he zipped his coat right up to his chin. Last of all he pushed his hands into his mittens.",
      "What did Tunde do FIRST?",
      [K("pulled on his thick socks"),
       P("zipped up his coat", "D-SEQUENCE-SWAP"),
       P("put on his mittens", "D-SEQUENCE-SWAP"),
       P("built a snowman", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("first_event", 1, 1, 2,
      "Kaya made a get-well card for Grandma. First she folded the paper in half. After that she drew a bumblebee on the front. At the end she wrote her name inside with three hearts.",
      "What did Kaya do FIRST?",
      [K("folded the paper in half"),
       P("drew a bumblebee", "D-SEQUENCE-SWAP"),
       P("wrote her name inside", "D-SEQUENCE-SWAP"),
       P("posted the card", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("first_event", 1, 1, 3,
      "The fire drill had rules. First, everyone stopped what they were doing the moment the bell rang. Second, they lined up without talking. Last, they walked out to the yard and stood with their class.",
      "What happened FIRST in the fire drill?",
      [K("everyone stopped when the bell rang"),
       P("they lined up quietly", "D-SEQUENCE-SWAP"),
       P("they walked to the yard", "D-SEQUENCE-SWAP"),
       P("they rang the bell themselves", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("first_event", 1, 1, 4,
      "Dad and Effy washed the car on Sunday. First they hosed off the loose mud. Then they rubbed the car all over with soapy sponges. At the end they dried it with an old towel until it shone.",
      "What did they do FIRST?",
      [K("hosed off the mud"),
       P("rubbed it with sponges", "D-SEQUENCE-SWAP"),
       P("dried it with a towel", "D-SEQUENCE-SWAP"),
       P("drove to the sea", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("first_event", 1, 2, 5,
      "To plant seeds, a first-grade class followed the steps. First they dampened a paper towel and laid it in the tray. Then they sprinkled the tiny seeds on top. Last they put the tray on the sunny windowsill.",
      "Which step came FIRST?",
      [K("dampening the paper towel"),
       P("sprinkling the seeds", "D-SEQUENCE-SWAP"),
       P("putting the tray in the sun", "D-SEQUENCE-SWAP"),
       P("eating the cress sandwiches", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("first_event", 1, 2, 6,
      "Jaz repaired her flat bike tire with Uncle Dev. First they turned the bike upside down. After that they removed the flat inner tube. At the end they fitted the new tube and pumped up the tire.",
      "What did they do FIRST?",
      [K("turned the bike upside down"),
       P("pulled out the flat tube", "D-SEQUENCE-SWAP"),
       P("pumped up the new tube", "D-SEQUENCE-SWAP"),
       P("rode to the park", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("first_event", 1, 2, 7,
      "Photo day had an order. First Miss Bell brushed everyone into neat rows on the benches. Then the photographer counted to three. Last, forty children said CHEESE at exactly the same time.",
      "What happened FIRST on photo day?",
      [K("Miss Bell arranged the rows"),
       P("the photographer counted", "D-SEQUENCE-SWAP"),
       P("everyone said CHEESE", "D-SEQUENCE-SWAP"),
       P("the photos were posted home", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("first_event", 1, 2, 8,
      "Grandma made hot chocolate in three steps. First she warmed the milk slowly in the pan. Then she stirred in two spoons of chocolate until it melted. Last came a little swirl of cream on top.",
      "What did Grandma do FIRST?",
      [K("warmed the milk in the pan"),
       P("stirred in the chocolate", "D-SEQUENCE-SWAP"),
       P("added the cream on top", "D-SEQUENCE-SWAP"),
       P("drank it by the fire", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ========== LEVEL 1 · middle_event (8) ==========
    it("middle_event", 1, 1, 1,
      "Bath time for Biscuit the dog went like this. First Ade filled the tub with warm water. Second he scrubbed the mud out of Biscuit's fur. Last he rubbed him dry until he was a fluffy cloud.",
      "What happened SECOND?",
      [K("Ade scrubbed the mud out"),
       P("Ade filled the tub", "D-SEQUENCE-SWAP"),
       P("Ade rubbed Biscuit dry", "D-SEQUENCE-SWAP"),
       P("Biscuit dug a hole", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("middle_event", 1, 1, 2,
      "The class made pancakes. First they whisked the eggs, flour and milk into a smooth batter. Second they poured a little circle into the hot pan. Last they lifted the golden pancake onto a plate.",
      "What happened SECOND?",
      [K("they poured batter into the pan"),
       P("they whisked the batter", "D-SEQUENCE-SWAP"),
       P("they lifted the pancake out", "D-SEQUENCE-SWAP"),
       P("they washed the plates", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("middle_event", 1, 1, 3,
      "Ivo wrote to his grandma in three steps. First he wrote the letter about his new tooth. Second he sealed it in the envelope and added a stamp. Last he dropped it into the mailbox.",
      "What happened SECOND?",
      [K("he sealed and stamped the envelope"),
       P("he wrote about his tooth", "D-SEQUENCE-SWAP"),
       P("he posted it in the box", "D-SEQUENCE-SWAP"),
       P("gran wrote back", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("middle_event", 1, 1, 4,
      "At the library, Suki did three things. First she slid last week's books into the return slot. Second she hunted the shelves for a dinosaur story. Last she took her pile to the desk to be stamped.",
      "What did Suki do SECOND?",
      [K("hunted for a dinosaur story"),
       P("returned last week's books", "D-SEQUENCE-SWAP"),
       P("had her pile stamped", "D-SEQUENCE-SWAP"),
       P("read under the table", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("middle_event", 1, 2, 5,
      "The tent went up in three steps. First Dad spread the tarp flat on the grass. Second the twins connected the long poles and slid them through the tent sleeves. Last everyone raised the tent and staked the corners.",
      "What happened SECOND?",
      [K("the poles were clicked and threaded"),
       P("the tarp was spread out", "D-SEQUENCE-SWAP"),
       P("the corners were staked", "D-SEQUENCE-SWAP"),
       P("it rained on the tent", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("middle_event", 1, 2, 6,
      "Bo's paper-mache mask took three days. On the first day he blew up a balloon and pasted it with newspaper strips. On the second day, once it was dry, he popped the balloon and cut out eye holes. On the last day he painted the mask gold like a lion.",
      "What did Bo do on the SECOND day?",
      [K("popped the balloon and cut eye holes"),
       P("pasted newspaper on the balloon", "D-SEQUENCE-SWAP"),
       P("painted the mask gold", "D-SEQUENCE-SWAP"),
       P("wore the mask to school", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("middle_event", 1, 2, 7,
      "The recycling job had an order. First Ren emptied every container into one big pile. Second he sorted the pile — paper here, cans there, glass in the crate. Last he wheeled everything out to the curb for the morning truck.",
      "What did Ren do SECOND?",
      [K("sorted the pile into groups"),
       P("emptied the containers into a pile", "D-SEQUENCE-SWAP"),
       P("wheeled it all to the curb", "D-SEQUENCE-SWAP"),
       P("drove the morning truck", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("middle_event", 1, 2, 8,
      "Grandpa made a pinecone bird feeder in three steps. First he chose a large pinecone. Second he spread seed butter over it with a spoon. Last he rolled it in birdseed and tied on a string.",
      "What did Grandpa do SECOND?",
      [K("spread seed butter on the pinecone"),
       P("chose a large pinecone", "D-SEQUENCE-SWAP"),
       P("rolled it in seed and added string", "D-SEQUENCE-SWAP"),
       P("hung up an empty spoon", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ========== LEVEL 1 · last_event (8) ==========
    it("last_event", 1, 1, 1,
      "Milly's bedtime routine never changed. First came the bath with the boats. Then came teeth, top row and bottom row. Last of all came the story — always one chapter, sometimes one and a half.",
      "What came LAST?",
      [K("the story"),
       P("the bath with the boats", "D-SEQUENCE-SWAP"),
       P("brushing teeth", "D-SEQUENCE-SWAP"),
       P("breakfast", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("last_event", 1, 1, 2,
      "The treasure hunt had three clues. The first clue was under the doormat. The second clue hid inside a rain boot by the door. The last clue led to the cookie tin, where the chocolate coins were waiting.",
      "Where did the hunt END?",
      [K("at the cookie tin"),
       P("under the doormat", "D-SEQUENCE-SWAP"),
       P("inside the rain boot", "D-SEQUENCE-SWAP"),
       P("at the candy store", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("last_event", 1, 1, 3,
      "Making apple crumble went in order. First Mom peeled and chopped the apples. Then Leo mixed the butter, flour, and sugar into crumbs and spread them on top. Last the dish went into the hot oven until the kitchen smelled wonderful.",
      "What happened LAST?",
      [K("the dish went into the oven"),
       P("the apples were chopped", "D-SEQUENCE-SWAP"),
       P("the crumbs were spread on top", "D-SEQUENCE-SWAP"),
       P("the apples were picked", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("last_event", 1, 1, 4,
      "At the dentist, Pia's visit had three parts. First she sat in the big chair and it hummed up high. Then the dentist counted her teeth with a tiny mirror. At the very end Pia chose a sticker from the golden box.",
      "What happened at the END of the visit?",
      [K("Pia chose a sticker"),
       P("the chair hummed up high", "D-SEQUENCE-SWAP"),
       P("her teeth were counted", "D-SEQUENCE-SWAP"),
       P("Pia lost a tooth", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("last_event", 1, 2, 5,
      "Wrapping Dad's present was a mission. First Ana cut the paper to size. Then she folded and taped the ends as neatly as she could. Last she stuck the bow on top and hid the present under her bed until morning.",
      "What did Ana do LAST?",
      [K("added the bow and hid the present"),
       P("cut the paper to size", "D-SEQUENCE-SWAP"),
       P("taped the folded ends", "D-SEQUENCE-SWAP"),
       P("opened the present herself", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("last_event", 1, 2, 6,
      "The school trip lunch had rules. First everyone found a dry spot on the grass. Then sandwiches came out, and trading was allowed. At the very end, every piece of trash went into the bags, and the field was left exactly as they found it.",
      "What happened LAST at lunch?",
      [K("all the trash was packed away"),
       P("everyone found a dry spot", "D-SEQUENCE-SWAP"),
       P("sandwiches were swapped", "D-SEQUENCE-SWAP"),
       P("the bus drove home", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("last_event", 1, 2, 7,
      "Kip built a kite from a kit. First he slotted the two sticks into a cross. Then he stretched the red sail over the frame and clipped it. Last he tied on the string and the long rattling tail.",
      "What did Kip do LAST?",
      [K("tied on the string and tail"),
       P("slotted the sticks into a cross", "D-SEQUENCE-SWAP"),
       P("stretched the sail on the frame", "D-SEQUENCE-SWAP"),
       P("flew the kite at the beach", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("last_event", 1, 2, 8,
      "Muddy boot cleanup worked in order. First the boots were tapped together outside to knock the big lumps off. Then an old brush scrubbed the tricky spots around the laces. Last the clean boots stood in a row on a drying rack.",
      "What happened LAST?",
      [K("the boots stood on a drying rack"),
       P("the boots were banged together", "D-SEQUENCE-SWAP"),
       P("the laces were scrubbed", "D-SEQUENCE-SWAP"),
       P("new boots were bought", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ========== LEVEL 2 · before_after_relation (8) ==========
    it("before_after_relation", 2, 1, 1,
      "Jam morning followed Grandma's strict order: berries picked before the sun got hot, then washed, then boiled with sugar until steam covered the kitchen windows. Only when a test drop wrinkled on a cold plate did the jars get filled, and the labels went on last, once the glass had cooled.",
      "What happened right BEFORE the jars were filled?",
      [K("the jam passed the cold-plate test"),
       P("the berries were picked", "D-SEQUENCE-SWAP"),
       P("the labels went on", "D-SEQUENCE-SWAP"),
       P("the jars were bought", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("before_after_relation", 2, 1, 2,
      "The egg diary told the whole story. Day one: six eggs under the warm lamp. Day nineteen: the first tiny crack. Day twenty: cheeping from inside the shells. Day twenty-one: five wet chicks, then a sixth, late and loud. Day twenty-three: six fluffy escape artists.",
      "What happened right AFTER the first crack appeared?",
      [K("cheeping came from inside the shells"),
       P("the eggs went under the lamp", "D-SEQUENCE-SWAP"),
       P("the chicks turned fluffy", "D-SEQUENCE-SWAP"),
       P("a seventh egg arrived", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("before_after_relation", 2, 1, 3,
      "Hair-cut Saturday followed its ritual. The gown went on backwards like a superhero cape. The spray bottle made Otto shiver. The scissors talked their snip-snip talk around his ears. And only after the little mirror had shown him the back of his own head did the lollipop jar come down from the shelf.",
      "When did the lollipop jar come down?",
      [K("once Otto had seen the finished haircut"),
       P("before the gown went on", "D-SEQUENCE-SWAP"),
       P("while the spray bottle worked", "D-SEQUENCE-SWAP"),
       P("it stayed on the shelf", "D-OPPOSITE")]),
    it("before_after_relation", 2, 1, 4,
      "The museum trip ran like clockwork. Coats and bags went into the big lockers first. The dinosaur hall came before lunch, because Mr. Idris knew nobody could concentrate after seeing the gift shop. Lunch happened in the echoing basement room. The gift shop came last — five dollars, one bag, no trades.",
      "What did the class do right BEFORE lunch?",
      [K("visited the dinosaur hall"),
       P("put bags in the lockers", "D-SEQUENCE-SWAP"),
       P("visited the gift shop", "D-SEQUENCE-SWAP"),
       P("rode the bus home", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("before_after_relation", 2, 2, 5,
      "The salad took all spring. Seeds went into pots on the cold windowsill in March. In April, after the last frost had passed, the little plants moved out to the raised bed. May brought watering duty and one dramatic slug battle. In June, at last, scissors met lettuce, and lunch tasted of the whole spring.",
      "When did the plants move outside?",
      [K("once the winter frosts had ended"),
       P("before the seeds were potted", "D-SEQUENCE-SWAP"),
       P("after the lettuce was cut", "D-SEQUENCE-SWAP"),
       P("during the slug battle", "D-SEQUENCE-SWAP")]),
    it("before_after_relation", 2, 2, 6,
      "Match-day afternoons had a fixed shape. Boots were cleaned the night before — always the night before, never the morning, that was the rule. The team sheet went up at noon. Warm-up laps started at one. And the moment the whistle blew at two, every stomach butterfly vanished until full time.",
      "When were the boots cleaned?",
      [K("on the evening ahead of match day"),
       P("at noon with the team sheet", "D-SEQUENCE-SWAP"),
       P("after the whistle blew", "D-SEQUENCE-SWAP"),
       P("during the warm-up laps", "D-SEQUENCE-SWAP")]),
    it("before_after_relation", 2, 2, 7,
      "The shadow experiment lasted from breakfast to late afternoon. At nine, Asha traced her friend's shadow, long and thin, stretching to the fence. Just after twelve she drew it again, short and close to his feet. At three the shadow reached the other side, and by five it touched the hedge, longer than ever.",
      "What was the shadow like just AFTER twelve?",
      [K("short and close to his feet"),
       P("stretching long to the fence", "D-SEQUENCE-SWAP"),
       P("touching the hedge", "D-SEQUENCE-SWAP"),
       P("gone completely", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("before_after_relation", 2, 2, 8,
      "Moving the bookcase needed planning. Every book came off the shelves before anything else. The empty case moved across the room a little at a time. Then Dad vacuumed the dusty carpet where it had stood. Only after that did the books go back in Robi's new rainbow order.",
      "What happened right BEFORE the books went back?",
      [K("the old spot was vacuumed"),
       P("the books came off the shelves", "D-SEQUENCE-SWAP"),
       P("the case waddled across the room", "D-SEQUENCE-SWAP"),
       P("new shelves were built", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ========== LEVEL 2 · implied_order (8) ==========
    it("implied_order", 2, 1, 1,
      "Noor licked the last icing from her fingers. The kitchen still smelled of warm cake, and two baking pans soaked in the sink. On the table sat the finished cake with icing and a cherry, next to the open recipe book.",
      "Which of these must have happened FIRST, before everything else?",
      [K("the cake was baked in the pans"),
       P("the icing was licked off fingers", "D-SEQUENCE-SWAP"),
       P("the cherry went on top", "D-SEQUENCE-SWAP"),
       P("the tins went into the sink", "D-SEQUENCE-SWAP")],
      { note: "events told out of order; reader reconstructs bake → ice → cherry → wash → lick" }),
    it("implied_order", 2, 1, 2,
      "The sled stood dripping in the entryway. Three pairs of soaked gloves lay on a drying rack, and a carrot with a bite-shaped dent waited by the back door. Out in the garden, a lopsided snowman wore Dad's second-best scarf.",
      "Which of these happened LAST, after all the rest?",
      [K("the wet things were brought in to dry"),
       P("the lopsided snowman was built in the garden", "D-SEQUENCE-SWAP"),
       P("the sled ride on the hill happened", "D-SEQUENCE-SWAP"),
       P("snow began to fall", "D-SEQUENCE-SWAP")]),
    it("implied_order", 2, 1, 3,
      "A wheelbarrow of fresh weeds stood by the gate. The flower bed's soil was dark and freshly turned. Twelve small marigolds now filled the spaces where the weeds had grown, and a watering can stood beside the new row.",
      "What had to happen BEFORE the marigolds were planted?",
      [K("the weeds were pulled out"),
       P("the marigolds were watered", "D-SEQUENCE-SWAP"),
       P("the new row was admired", "D-SEQUENCE-SWAP"),
       P("the wheelbarrow was painted", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("implied_order", 2, 1, 4,
      "Rio hopped to the bench with one bare foot. Out in the shallow end, a lifeguard fished patiently with a long pole. On the tiles lay one wet sock, and somewhere between the changing room and the water, the story of how his flip-flop had ended up floating told itself.",
      "What must have happened BEFORE the lifeguard got the pole?",
      [K("the flip-flop went into the water"),
       P("Rio hopped to the bench", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the flip-flop was fished out", "D-SEQUENCE-SWAP"),
       P("the pool was closed", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("implied_order", 2, 2, 5,
      "Aunt Zainab's package was ready at last. Tape sealed every box flap, and a neat address label covered the first two mistakes. Inside, jars of jam sat in thick newspaper, with no room to move.",
      "What must have happened BEFORE the box was taped shut?",
      [K("the wrapped jars were placed inside"),
       P("the package was carried to the mail counter", "D-SEQUENCE-SWAP"),
       P("the tape was cut open again", "D-SEQUENCE-SWAP"),
       P("the jam was served at breakfast", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("implied_order", 2, 2, 6,
      "Curtain call. Flowers landed on the stage as the cast bowed in painted cardboard armor. In the wings, the prompt book sat closed on its stool at last, and backstage a whole semester's rehearsal notes filled the trash can — three drafts of the script, the audition list, and the first rough set sketches.",
      "Which of these came FIRST, long before tonight?",
      [K("the auditions were held"),
       P("the cast took their bows", "D-SEQUENCE-SWAP"),
       P("flowers landed on the stage", "D-SEQUENCE-SWAP"),
       P("the prompt book closed", "D-SEQUENCE-SWAP")]),
    it("implied_order", 2, 2, 7,
      "The wormery finally stood complete on the balcony: layers of sand and dark soil striped like a cake, damp leaves on top, and five worms already tunnelling their first wavy lines past the glass. A bag of leftover sand slumped by the door, and Juno's soil-crusted trowel soaked in a jam jar.",
      "Which of these must have happened BEFORE the worms went in?",
      [K("the sand and soil were layered"),
       P("the worms drew wavy tunnel lines past the glass", "D-SEQUENCE-SWAP"),
       P("the trowel went into the jar", "D-PLAUSIBLE-UNSUPPORTED"),
       P("the wormery was emptied out", "D-OPPOSITE")]),
    it("implied_order", 2, 2, 8,
      "Half-time. The score sat at two-one, and Coach passed the orange quarters down the line of muddy knees. Nobody mentioned the first goal any more — the lucky bounce off the post — and everybody mentioned the second, Ffion's header, over and over, louder each telling.",
      "Which goal happened FIRST?",
      [K("the lucky bounce off the post"),
       P("Ffion's header", "D-SEQUENCE-SWAP"),
       P("the half-time oranges", "D-SEQUENCE-SWAP"),
       P("the winning penalty", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ========== LEVEL 2 · process_order (8) ==========
    it("process_order", 2, 1, 1,
      "A letter's journey has stages. It is placed in the mail box on the corner. A postal worker empties the box into a big sack. At the sorting center, machines read the ZIP code and place it in the right tray. A truck carries the tray across the country, and a mail carrier brings the letter to the right door.",
      "What happens right AFTER the box is emptied?",
      [K("the letter is sorted by ZIP code"),
       P("the letter is posted in the box", "D-SEQUENCE-SWAP"),
       P("the mail carrier brings it to the door", "D-SEQUENCE-SWAP"),
       P("the letter is written", "D-SEQUENCE-SWAP")]),
    it("process_order", 2, 1, 2,
      "From cocoa pod to chocolate bar takes many steps. Farmers cut the pods and scoop out the beans. The beans dry in the sun for days. Roasting develops their flavor. Then grinding turns them into a thick brown paste. After sugar and milk are added, the paste sets into bars.",
      "What happens right BEFORE the beans are roasted?",
      [K("they dry in the sun"),
       P("they are ground to paste", "D-SEQUENCE-SWAP"),
       P("sugar and milk join in", "D-SEQUENCE-SWAP"),
       P("the bars reach the stores", "D-SEQUENCE-SWAP")]),
    it("process_order", 2, 1, 3,
      "Recycled glass goes around in a loop. Bottles from curbside bins travel to the plant. There they are sorted by color and smashed into small pieces. A furnace melts the pieces into glowing liquid. The liquid is blown or pressed into new bottles, which can return to curbside bins to start again.",
      "What happens right AFTER the glass is smashed into small pieces?",
      [K("the furnace melts the small pieces"),
       P("bottles are collected from curbside bins", "D-SEQUENCE-SWAP"),
       P("new bottles are blown", "D-SEQUENCE-SWAP"),
       P("the bottles are sorted by color", "D-SEQUENCE-SWAP")]),
    it("process_order", 2, 1, 4,
      "A tooth's visit from the tooth fairy follows steps, Ari explained seriously. The tooth wobbles for days. It comes out — usually in an apple or a laugh. It goes under the pillow at bedtime. In the morning, a coin has taken its place. The tooth itself, Ari suspected, joins a very large collection somewhere.",
      "In Ari's list, what happens right AFTER the tooth goes under the pillow?",
      [K("a coin appears by morning"),
       P("the tooth starts to wobble", "D-SEQUENCE-SWAP"),
       P("the tooth comes out", "D-SEQUENCE-SWAP"),
       P("the dentist is called", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("process_order", 2, 2, 5,
      "Making honey happens in stages. Bees drink nectar from flowers and carry it home. Other bees pass the nectar from bee to bee, thickening it. The nectar is packed into wax cells. Bees fan it until enough water has gone. Only then is each cell capped with wax.",
      "What do the bees do right BEFORE capping the cell?",
      [K("fan the nectar with their wings"),
       P("drink nectar from flowers", "D-SEQUENCE-SWAP"),
       P("pass it from bee to bee", "D-SEQUENCE-SWAP"),
       P("break the wax open", "D-OPPOSITE")]),
    it("process_order", 2, 2, 6,
      "The rescue boat launch follows a practiced order. Alerts sound across the town. Crew members stop what they are doing and run to the station. They put on boots, suits, and life jackets. The doors open, the boat moves down the ramp, and the crew receives directions on the water.",
      "What happens right AFTER the crew members reach the station?",
      [K("they put on their safety gear"),
       P("the alerts sound", "D-SEQUENCE-SWAP"),
       P("the boat goes down the ramp", "D-SEQUENCE-SWAP"),
       P("they ask where they are going", "D-SEQUENCE-SWAP")]),
    it("process_order", 2, 2, 7,
      "A library book's life is a circle. It is chosen and borrowed at the desk. It lives in a reader's house for a while — beside beds, in bags, once or twice in a garden. It comes back through the return slot. It is checked, sometimes mended with careful tape, and then reshelved in its exact place, ready to be chosen all over again.",
      "What happens right AFTER the book comes back through the slot?",
      [K("it is checked and mended if needed"),
       P("it is borrowed at the desk", "D-SEQUENCE-SWAP"),
       P("it lives beside someone's bed", "D-SEQUENCE-SWAP"),
       P("it is reshelved immediately unchecked", "D-SEQUENCE-SWAP")]),
    it("process_order", 2, 2, 8,
      "School soup follows the garden calendar. Seeds are planted in trays in early spring. Seedlings move to the garden after the last frost. All season the watering schedule keeps them alive. In autumn the vegetables are pulled, scrubbed, and chopped, and the whole school eats the soup.",
      "What happens right BEFORE the vegetables are pulled?",
      [K("a whole term of watering"),
       P("the seeds are sown in trays", "D-SEQUENCE-SWAP"),
       P("the soup is eaten", "D-SEQUENCE-SWAP"),
       P("the trays are washed", "D-PLAUSIBLE-UNSUPPORTED")]),

    // ========== RETENTION RESERVE (8 + 8) ==========
    it("first_event", 1, 1, 9,
      "Milo set the breakfast table his way. First he laid out three bowls in a row. Then he stood the cereal boxes up like castle towers. Last he put a spoon beside each bowl, handles all pointing the same way.",
      "What did Milo do FIRST?",
      [K("laid out the three bowls"),
       P("stood up the cereal boxes", "D-SEQUENCE-SWAP"),
       P("placed the spoons", "D-SEQUENCE-SWAP"),
       P("poured the milk", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("middle_event", 1, 1, 10,
      "Wash day for Teddy had three steps. First Teddy took a gentle bath in the sink. Second he was squeezed softly in a towel. Last he hung from the clothesline until the sun had dried him.",
      "What happened SECOND?",
      [K("Teddy was squeezed in a towel"),
       P("Teddy had his bath", "D-SEQUENCE-SWAP"),
       P("Teddy hung from the clothesline", "D-SEQUENCE-SWAP"),
       P("Teddy was lost at the park", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("last_event", 1, 1, 11,
      "The lost tooth chart worked in order. First Amy wiggled the tooth and marked a W on the chart. Then, when it came out, she drew a star on that day's square. Last of all she colored the whole row gold, because the chart was finally finished.",
      "What did Amy do LAST?",
      [K("colored the row gold"),
       P("marked a W on the chart", "D-SEQUENCE-SWAP"),
       P("drew a star on the square", "D-SEQUENCE-SWAP"),
       P("started a new chart", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("first_event", 1, 2, 10,
      "Puddle-jumping had rules of its own. First, boots on — no exceptions, not even for socks with frogs on. Then the garden inspection, walking the path to find the deepest, brownest puddle. Only then came the jumping, biggest splash wins, judged by the dog.",
      "What came FIRST in the rules?",
      [K("putting boots on"),
       P("inspecting the puddles", "D-SEQUENCE-SWAP"),
       P("the jumping contest", "D-SEQUENCE-SWAP"),
       P("drying the dog", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("middle_event", 1, 2, 11,
      "The class assembly took shape in three rehearsals. In the first, everyone just learned where to stand. In the second, the speaking parts joined in, script pages rustling. In the third and last, costumes came out, and suddenly the hall felt like a real show.",
      "What happened in the SECOND rehearsal?",
      [K("the speaking parts were practiced"),
       P("everyone learned where to stand", "D-SEQUENCE-SWAP"),
       P("the costumes came out", "D-SEQUENCE-SWAP"),
       P("the audience arrived", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("last_event", 1, 2, 12,
      "Feeding the ducks properly went like this. First the oats were shared into four little cups, one each. Then the slow walk to the pond, cups held like treasure. At the end, the oats were scattered wide across the water, so even the shy duck at the back got breakfast.",
      "What happened LAST?",
      [K("the oats were scattered on the water"),
       P("the oats were shared into cups", "D-SEQUENCE-SWAP"),
       P("the walk to the pond", "D-SEQUENCE-SWAP"),
       P("bread was thrown instead", "D-OPPOSITE")], { retention: true }),
    it("first_event", 1, 1, 12,
      "Painting the fence took all Saturday. First Dad and Nia brushed off the old flaky bits. Then they stirred the big tin until the paint was smooth. Last they painted plank by plank, racing the afternoon rain.",
      "What did they do FIRST?",
      [K("brushed off the flaky bits"),
       P("stirred the paint smooth", "D-SEQUENCE-SWAP"),
       P("painted plank by plank", "D-SEQUENCE-SWAP"),
       P("built a new fence", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("middle_event", 1, 1, 12,
      "Story time in the blanket fort had an order. First the cushions were piled into a nest. Second the flashlight was clipped to the tent pole, casting a circle of light. Last Uncle Remy read in his creaky pirate voice until somebody, usually Uncle Remy, fell asleep.",
      "What happened SECOND?",
      [K("the flashlight was clipped to the pole"),
       P("the cushions were piled up", "D-SEQUENCE-SWAP"),
       P("the pirate voice reading", "D-SEQUENCE-SWAP"),
       P("breakfast was cooked", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("before_after_relation", 2, 1, 9,
      "The bridge of books rose across the classroom floor all week. Monday: two towers, one at each side. Tuesday: the towers grew waist-high. Wednesday: the first careful row of atlases went across the gap. Thursday: the marble made its first crossing. Friday, the principal asked for every book to go back on the shelves.",
      "What happened right BEFORE the marble made its first crossing?",
      [K("the atlas plank bridged the gap"),
       P("the two towers were started", "D-SEQUENCE-SWAP"),
       P("the books went back on shelves", "D-SEQUENCE-SWAP"),
       P("a second marble was found", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("before_after_relation", 2, 2, 10,
      "Outdoor movie night ran on a strict timetable. The blankets were checked while it was still light, always first. Snacks came out at six. The movie began at seven. Star watching waited until full dark.",
      "When were the blankets checked?",
      [K("at the start, before sunset"),
       P("after the movie began", "D-SEQUENCE-SWAP"),
       P("during star watching", "D-SEQUENCE-SWAP"),
       P("at six with the snacks", "D-SEQUENCE-SWAP")], { retention: true }),
    it("implied_order", 2, 1, 10,
      "The sandcastle stood finished at last, moat and all, with a seagull feather flying from the top tower. Around it lay the story of the morning: a ring of shells not quite used up, two buckets with wet sand still crusting their rims, and one very sandy pair of knees.",
      "Which of these must have happened FIRST?",
      [K("the buckets were filled and turned over"),
       P("the feather flag was placed on the top tower", "D-SEQUENCE-SWAP"),
       P("the shells were arranged around the castle", "D-SEQUENCE-SWAP"),
       P("the tide later washed the castle away", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("implied_order", 2, 2, 11,
      "The community concert was over. On the piano stood a jar of garden flowers and a thank-you card signed by the whole street. The borrowed chairs were going back next door two at a time, and the drink dispenser in the kitchen held its final cups.",
      "Which of these happened FIRST, before the rest?",
      [K("the neighbors lent their chairs"),
       P("the thank-you card was signed", "D-SEQUENCE-SWAP"),
       P("the chairs went back two at a time", "D-SEQUENCE-SWAP"),
       P("the flowers wilted", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("process_order", 2, 1, 9,
      "Wool has a long journey to a sweater. The sheep is sheared in early summer. The fleece is washed until the water runs clear. Carding combs untangle every fiber the same way. The spinning wheel twists the fibers into one long thread, and the knitting needles shape it loop by loop.",
      "What happens right AFTER the fleece is washed?",
      [K("carding combs untangle the fibers"),
       P("the sheep is sheared in early summer", "D-SEQUENCE-SWAP"),
       P("the thread is knitted", "D-SEQUENCE-SWAP"),
       P("the sweater is worn", "D-SEQUENCE-SWAP")], { retention: true }),
    it("process_order", 2, 2, 10,
      "A rescued hedgehog moves through the wildlife center in stages. New arrivals are weighed and checked when they come in. Sick ones stay warm in a quiet room until they feed by themselves. Then comes the outdoor pen, to practice being wild again. Release night is last, back to the hedge where each one was found.",
      "What happens right BEFORE the hedgehog moves to the outdoor pen?",
      [K("feeding by themselves in the quiet room"),
       P("being weighed on arrival", "D-SEQUENCE-SWAP"),
       P("release at the hedge", "D-SEQUENCE-SWAP"),
       P("hibernating all winter", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("before_after_relation", 2, 1, 11,
      "The lost glove's week went like this. Monday it fell at the bus stop. Tuesday someone balanced it on the wall, in case its owner came back. Wednesday it wore a dusting of frost. Thursday Priya recognized it from the bus window. And on Friday, glove and girl went home together at last.",
      "What happened right AFTER the glove was put on the wall?",
      [K("it got a dusting of frost"),
       P("it fell at the bus stop", "D-SEQUENCE-SWAP"),
       P("Priya took it home", "D-SEQUENCE-SWAP"),
       P("it was posted to the school", "D-PLAUSIBLE-UNSUPPORTED")], { retention: true }),
    it("process_order", 2, 1, 11,
      "The pedestrian signal follows a strict order. The button is pressed, and the small light says WAIT. Traffic gets a yellow warning, then red. Only then does the white walking symbol appear. When it starts to blink, people finish crossing, and then the cars get their turn again.",
      "What happens right AFTER the traffic light turns red?",
      [K("the white walking symbol appears"),
       P("the button is pressed", "D-SEQUENCE-SWAP"),
       P("the yellow warning shows", "D-SEQUENCE-SWAP"),
       P("the WAIT light switches on", "D-SEQUENCE-SWAP")], { retention: true })
  ].filter(item => item.lvl === 2)]
};
