// Theme & Higher Comprehension — v3 authored bank (wave W2). Every passage is
// a COMPLETE arc (setup → tension → resolution). Themes are concrete child
// morals, phrased fresh each time; L2 theme_among_rivals carries two morally
// plausible readings and the evidence must pick one; theme_vs_plot uses plot
// summaries as distractors; apply_theme transfers the lesson to a new case.
//
// Topic registry: shared telescope, seed race, wrong bus stop, borrowed comic,
// burnt cookies retry, quiet goalkeeper, young bird left with parent, snapped crayon
// halves, grandpa's slow watch, wobbly tooth brag, lighthouse keeper's list,
// smallest lantern, muddy boots helper, puzzle corner piece, jam recipe fail,
// paper crane hundred, shy singer duet, stuck tractor teamwork, lost-and-found
// coin, greedy goldfish, mended umbrella, first snow patience, litter robot,
// two ladders, apology letter, echo hello, library whisperer, splinter thank
// you, shared jump rope, night-light courage, plum tree waiting, homework
// swap honesty.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, prompt, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage, prompt, choices, media: "text", ...extra
});
const QT = "What lesson does this story teach?";

export default {
  skillId: "theme_higher_comprehension",
  skillName: "Theme and Higher Comprehension",
  items: [
    // ========== LEVEL 1 · lesson_mistake_fixed (8) ==========
    it("lesson_mistake_fixed", 1, 1, 1,
      "Jory borrowed Ann's comic and left it out in the rain. The pages wrinkled and stuck together. He wanted to hide it under his bed. Instead he showed Ann, said sorry, and spent his saved money on a new copy. Ann was sad about the comic — but glad he had told the truth.",
      QT,
      [K("owning up to a mistake is better than hiding it"),
       P("a comic was left out in the rain", "D-DETAIL-AS-MAIN"),
       P("never lend anything to anyone", "D-OPPOSITE"),
       P("comics can cost saved money", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 1, 2,
      "Bel's first batch of cookies came out black as coal. She nearly threw her apron in the trash. Instead she read the recipe again and found her mistake — the oven had been far too hot. The second batch came out golden, and the kitchen smelled wonderful.",
      QT,
      [K("a mistake can teach you how to do better"),
       P("the first cookies burned black", "D-DETAIL-AS-MAIN"),
       P("baking always goes wrong", "D-OPPOSITE"),
       P("ovens can be hot", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 1, 3,
      "Kit snapped the blue crayon and quickly slid it back in the tin, broken ends together. All morning it bothered him like a stone in a shoe. At last he told Miss May. She smiled, taped the crayon, and said broken things mend easier than secrets.",
      QT,
      [K("telling the truth about a mistake makes it easier to fix"),
       P("a blue crayon got snapped", "D-DETAIL-AS-MAIN"),
       P("crayons should never be shared", "D-OPPOSITE"),
       P("tape can fix many things", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 1, 4,
      "Ravi moved to another bus seat to avoid sitting next to a new boy. At the school gate, Ravi's bag strap broke and his books spilled. The new boy gathered every book and helped carry the bag inside. The next day Ravi chose the seat beside him.",
      QT,
      [K("do not judge someone before you know them"),
       P("Ravi's bag strap broke", "D-DETAIL-AS-MAIN"),
       P("always sit away from someone new", "D-OPPOSITE"),
       P("school gates are meeting places", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 2, 5,
      "Lena bragged that her wobbly tooth would come out first, before Sam's. She wiggled it all day just to win. It came out at last — but it hurt, and there was no prize, only Sam saying 'well done' kindly. Lena wished she had let it happen in its own time.",
      QT,
      [K("racing to be first can spoil the fun"),
       P("Lena's tooth was wobbly", "D-DETAIL-AS-MAIN"),
       P("teeth should never come out", "D-OPPOSITE"),
       P("Sam said well done", "D-DETAIL-AS-MAIN")]),
    it("lesson_mistake_fixed", 1, 2, 6,
      "Min fed the class goldfish twice, then once more, because it always looked hungry. The tank turned cloudy and the fish went slow and sad. A pet store worker explained: too much food can hurt a fish. Min learned to feed only the measured amount, and the water cleared.",
      QT,
      [K("too much of a good thing can do harm"),
       P("the tank water turned cloudy", "D-DETAIL-AS-MAIN"),
       P("goldfish should not be fed", "D-OPPOSITE"),
       P("pet stores sell fish food", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 2, 7,
      "In the quiet library, Posy whispered a joke, then a story, then a song. The librarian did not scold. She just pointed at the reading corner, where a small boy had lost his place three times. Posy saw his angry face — and understood without one word being said.",
      QT,
      [K("your noise can spoil things for others"),
       P("Posy whispered a song", "D-DETAIL-AS-MAIN"),
       P("libraries should ban jokes", "D-OPPOSITE"),
       P("librarians point at corners", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 2, 8,
      "Dara promised to water her neighbor's plum tree during school break, then forgot for a whole hot week. The leaves curled. She followed the watering directions every day after that, and by the end of summer the tree stood green again — and Dara never made a promise carelessly again.",
      QT,
      [K("a promise matters even when it is hard to keep"),
       P("the plum leaves curled up", "D-DETAIL-AS-MAIN"),
       P("never help your neighbors", "D-OPPOSITE"),
       P("summer weeks can be hot", "D-TOPIC-ADJACENT")]),

    // ========== LEVEL 1 · lesson_kindness_returned (8) ==========
    it("lesson_kindness_returned", 1, 1, 1,
      "Every wet morning, Iris carried her little brother's boots so he could climb the bus steps. One icy day, Iris slipped and her books flew everywhere. Before she could blink, her brother and three of his small friends were gathering pages from every puddle.",
      QT,
      [K("kindness you give comes back to you"),
       P("books flew into the puddles", "D-DETAIL-AS-MAIN"),
       P("icy days are for staying home", "D-TOPIC-ADJACENT"),
       P("little brothers are a nuisance", "D-OPPOSITE")]),
    it("lesson_kindness_returned", 1, 1, 2,
      "The new girl ate lunch alone, so Bo moved his tray next to hers and shared his grapes. Weeks later, when Bo broke his arm and could not cut his food, a tray slid quietly next to his — and the new girl cut his dinner into pieces without being asked.",
      QT,
      [K("small kindnesses grow into friendship"),
       P("Bo shared his grapes", "D-DETAIL-AS-MAIN"),
       P("eat lunch alone if you can", "D-OPPOSITE"),
       P("broken arms make eating hard", "D-DETAIL-AS-MAIN")]),
    it("lesson_kindness_returned", 1, 1, 3,
      "Grandpa Tan fixed umbrellas for the whole street and never took a penny. 'Rain falls on everyone,' he said. When his roof leaked in the big storm, half the street appeared at his door with ladders, buckets, and a hot dinner in a basket.",
      QT,
      [K("a helper is never left to struggle alone"),
       P("Grandpa Tan fixed umbrellas", "D-DETAIL-AS-MAIN"),
       P("keep your pennies for yourself", "D-OPPOSITE"),
       P("storms can break roofs", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 1, 4,
      "At the fair, Nia's last coin rolled under the lost-and-found table. The boy behind the table crawled in the dust to fetch it, and Nia used it to buy two candy apples — one for herself, and one for a dusty, grinning boy.",
      QT,
      [K("sharing doubles a good moment"),
       P("a coin rolled under a table", "D-DETAIL-AS-MAIN"),
       P("keep both candy apples", "D-OPPOSITE"),
       P("fairs sell candy apples", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 5,
      "Wren was the quietest singer in choir, so quiet her words were mostly shapes. Ana stood beside her every week and sang a little softer, so Wren could hear her own voice. At the concert, two voices rose together — and one of them had never sounded so brave.",
      QT,
      [K("gentle support helps courage grow"),
       P("Wren sang very quietly", "D-DETAIL-AS-MAIN"),
       P("loud singers matter most", "D-OPPOSITE"),
       P("choirs give concerts", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 6,
      "Old Mr Price's tractor sank in the mud, and he sat a long time, too proud to wave for help. The Okafor children saw anyway. They fetched planks, their mother, and a rope — and afterwards Mr Price's orchard gate, locked for years, stood open with a sign: APPLES, HELP YOURSELVES.",
      QT,
      [K("helping without being asked opens hearts"),
       P("a tractor sank in the mud", "D-DETAIL-AS-MAIN"),
       P("pride is always right", "D-OPPOSITE"),
       P("orchards grow apples", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 7,
      "Jude saw broken glass on the slide. He stood beside it to warn the younger children and called an adult, missing the soccer game while the slide was made safe. Nobody noticed — he thought. On Friday, a note appeared in his cubby: 'Thank you from the little ones. You didn't know we saw.'",
      QT,
      [K("quiet good deeds are still seen"),
       P("there was glass on the slide", "D-DETAIL-AS-MAIN"),
       P("soccer matters more than safety", "D-OPPOSITE"),
       P("notes can go in cubbies", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 8,
      "One jump rope, eleven children. Quarrels every recess — until Fern started counting everyone in: two turns each, jumpers become turners, turners become jumpers. The rope never rested, the line sang the counting song, and recess stopped ending in tears.",
      QT,
      [K("fair sharing lets everyone enjoy more"),
       P("eleven children wanted one rope", "D-DETAIL-AS-MAIN"),
       P("the strongest should keep the rope", "D-OPPOSITE"),
       P("jumping rope has counting songs", "D-TOPIC-ADJACENT")]),

    // ========== LEVEL 1 · lesson_effort_pays (8) ==========
    it("lesson_effort_pays", 1, 1, 1,
      "Pip's sunflower seed sat in the soil doing nothing while Marco's shot up like a green rocket. Pip watered anyway, every day, even when it felt silly. In week five, a late little stem appeared — and by August, Pip's flower was the tallest in the whole garden.",
      QT,
      [K("keep trying when progress is slow"),
       P("Marco's flower grew first", "D-DETAIL-AS-MAIN"),
       P("slow seeds never grow", "D-OPPOSITE"),
       P("sunflowers grow in gardens", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 1, 2,
      "The monkey bars defeated Ola all autumn. Each break she got one bar farther before dropping. Winter gloves, spring blisters, a hundred small tries. On the last day of term she swung across the whole row — and the playground burst into cheering she never expected.",
      QT,
      [K("many small tries add up to a big win"),
       P("Ola wore winter gloves", "D-DETAIL-AS-MAIN"),
       P("give up after one autumn", "D-OPPOSITE"),
       P("playgrounds have monkey bars", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 1, 3,
      "Tam wanted to fold one hundred paper cranes like the ones in the library book. By crane twenty his folds were crooked; by fifty, his thumbs ached. He folded on the bus, at breakfast, and after school. Crane one hundred sat perfectly on his windowsill before his birthday.",
      QT,
      [K("big goals are finished one small step at a time"),
       P("his thumbs ached at fifty", "D-DETAIL-AS-MAIN"),
       P("one hundred is too many", "D-OPPOSITE"),
       P("libraries have craft books", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 1, 4,
      "Nobody wanted to be goalkeeper, so quiet Emil took the gloves. He practiced alone against the garage wall all season — thud, catch, thud, catch. In the last game, with the score tied, Emil dove sideways and caught the final shot, and his name was the loudest word on the field.",
      QT,
      [K("practice done quietly still shines in the end"),
       P("Emil practiced against a garage wall", "D-DETAIL-AS-MAIN"),
       P("goalkeepers never matter", "D-OPPOSITE"),
       P("games can end with a tied score", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 2, 5,
      "The first snow would not stick, and Ceri checked the window a hundred times. Grandma said watching would not hurry the sky, so Ceri stopped watching and got ready instead: gloves dried, sled waxed, carrot saved. When the deep snow finally came, she was first — and readiest — on the hill.",
      QT,
      [K("use waiting time to get ready"),
       P("the first snow would not stick", "D-DETAIL-AS-MAIN"),
       P("watching the sky brings snow", "D-OPPOSITE"),
       P("sleds go on hills", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 2, 6,
      "The jigsaw puzzle's last corner piece was missing, and everyone gave up — except Ash, who liked finishing things. He searched the sofa, the stairs, the dog's bed, and finally the folded edge of a rug. The picture on the table was complete because one person would not stop looking.",
      QT,
      [K("finishing takes one person who will not quit"),
       P("the piece was under the folded edge of a rug", "D-DETAIL-AS-MAIN"),
       P("lost pieces stay lost", "D-OPPOSITE"),
       P("dogs sleep in beds", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 2, 7,
      "Grandpa's old watch had stopped, so repairing it became Suvi's winter project. She studied the gears, sorted the tiny screws, and tried three careful adjustments. When the watch finally ticked the right time, Grandpa wore it proudly every day.",
      QT,
      [K("careful effort can bring an old thing back to use"),
       P("the watch had stopped", "D-DETAIL-AS-MAIN"),
       P("old watches cannot be fixed", "D-OPPOSITE"),
       P("winter is for projects", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 2, 8,
      "A fifth-grade class built a robot to pick up paper scraps, but it kept jamming. They tested it, found one problem at a time, widened the wheels, and moved the brush. After many fixes, the robot rolled down the hallway and collected every scrap without stopping.",
      QT,
      [K("testing and fixing one problem at a time can make an idea work"),
       P("the class widened the robot's wheels", "D-DETAIL-AS-MAIN"),
       P("stop trying when a project jams", "D-OPPOSITE"),
       P("schools have hallways", "D-TOPIC-ADJACENT")]),

    // ========== LEVEL 2 · theme_among_rivals (8) ==========
    it("theme_among_rivals", 2, 1, 1,
      "Two watering cans sat by the garden: Jo's shiny new one and the old dented one her mom had used as a girl. Jo always chose the shiny can — until she noticed its wide spout soaked the path but missed the roots. The old can's long spout placed water exactly where each plant needed it. After that, Jo cared for both cans but reached for the dented one each morning.",
      "Which lesson is best supported by the story?",
      [K("judge a tool by how well it works, not by how shiny it looks"),
       P("family memories can make old things worth caring for", "D-PLAUSIBLE-UNSUPPORTED"),
       P("new things always work badly", "D-OPPOSITE"),
       P("the old can had a long spout", "D-DETAIL-AS-MAIN")],
      { note: "rival family-memory lesson is worthy but Jo changes her choice only after comparing how the cans work" }),
    it("theme_among_rivals", 2, 1, 2,
      "Yusuf told everyone that his loud trumpet solo would be the concert's best part. His sister Amal said little and practiced the harp behind a closed door. Yusuf played well and bowed twice. Then Amal's gentle tune held the whole hall silent before the applause began. On the way home, Yusuf asked how she had made quiet music hold such a big room.",
      "Which lesson is best supported by the story?",
      [K("something quiet can still have a powerful effect"),
       P("regular practice helps a performer improve", "D-PLAUSIBLE-UNSUPPORTED"),
       P("loud music can never be beautiful", "D-OPPOSITE"),
       P("the hall stayed silent before applauding", "D-DETAIL-AS-MAIN")]),
    it("theme_among_rivals", 2, 1, 3,
      "Milo and Dad disagreed about the night-light. Dad thought darkness would help Milo sleep, but Milo was frightened by shapes in the room. They agreed to keep a flashlight beside the bed. Milo used it the first night, held it the second, and by Friday left it untouched — because knowing he could switch it on made the dark feel manageable.",
      "Which lesson is best supported by the story?",
      [K("knowing help is near can build courage"),
       P("a fair compromise can settle a family disagreement", "D-PLAUSIBLE-UNSUPPORTED"),
       P("feeling afraid means you cannot be brave", "D-OPPOSITE"),
       P("a flashlight sat beside the bed", "D-DETAIL-AS-MAIN")]),
    it("theme_among_rivals", 2, 1, 4,
      "Priya found the answer list for Friday's spelling test lying by the copier — every word, a day early. She looked at it a long moment, then slid it under the school office door. Her score on Friday was seven out of ten, her usual score. But when Mr. Field told the class someone had returned the list unread, Priya felt prouder than any unfair perfect score could have made her feel.",
      "Which lesson is best supported by the story?",
      [K("being honest feels better than winning unfairly"),
       P("hard work can improve a test score", "D-PLAUSIBLE-UNSUPPORTED"),
       P("a high score matters more than honesty", "D-OPPOSITE"),
       P("an answer list lay by the copier", "D-DETAIL-AS-MAIN")]),
    it("theme_among_rivals", 2, 2, 5,
      "Etta found a young feathered bird hopping under the hedge after a storm. She wanted to carry it indoors, but her grandmother called a wildlife rescue line first. They were told to keep pets away and watch from a distance. Soon the parent bird returned with food, and the young bird followed it deeper into the hedge.",
      "Which lesson is best supported by the story?",
      [K("the best help can support without taking over"),
       P("quick action is always the best way to protect an animal", "D-PLAUSIBLE-UNSUPPORTED"),
       P("wild animals should become household pets", "D-OPPOSITE"),
       P("the parent bird returned with food", "D-DETAIL-AS-MAIN")],
      { note: "the rescue line directs a small, informed action; taking the bird indoors is explicitly rejected" }),
    it("theme_among_rivals", 2, 2, 6,
      "The junior bake-off allowed one entry each. Zeke's jam roll collapsed just before judging, and he stood over the broken cake, out of time and hope. Nell knew her lemon cake might win, but helping Zeke would mean missing judging. She withdrew her entry and helped him turn the broken roll into dessert cups for the visitors. They won no prize, but every cup was eaten, and they left laughing together.",
      "Which lesson is best supported by the story?",
      [K("friendship can matter more than prizes"),
       P("creative reuse can turn a mistake into something useful", "D-PLAUSIBLE-UNSUPPORTED"),
       P("winning matters more than helping a friend", "D-OPPOSITE"),
       P("a jam roll collapsed before judging", "D-DETAIL-AS-MAIN")]),
    it("theme_among_rivals", 2, 2, 7,
      "Every evening, Kofi's echo game in the stairwell — HELLO... hello... hello — annoyed the third floor. Mrs. Adjei came down, and everyone expected her to scold him. Instead she taught him the trick her own father taught her: the softer you call, the closer the echo leans in to listen. After that, Kofi played quiet echo games, and the third floor heard nothing at all.",
      "Which lesson is best supported by the story?",
      [K("calm guidance can solve a problem better than scolding"),
       P("quiet games are a good choice in shared indoor spaces", "D-PLAUSIBLE-UNSUPPORTED"),
       P("anger is the only way to change behavior", "D-OPPOSITE"),
       P("Kofi played an echo game", "D-DETAIL-AS-MAIN")]),
    it("theme_among_rivals", 2, 2, 8,
      "The class voted to spend the prize money on a party. Robin alone voted for new goal nets, and lost, nineteen to one. At the party, Robin neither sulked in the corner nor pretended the nets had been a silly idea. He handed out cake, laughed at the games — and in spring, when the nets budget came up again, nineteen hands remembered his good grace and went up with his.",
      "Which lesson is best supported by the story?",
      [K("respecting a fair decision can earn other people's respect"),
       P("speaking up for an unpopular idea can lead to change", "D-PLAUSIBLE-UNSUPPORTED"),
       P("losing a vote means your idea has no value", "D-OPPOSITE"),
       P("the vote was nineteen to one", "D-DETAIL-AS-MAIN")]),

    // ========== LEVEL 2 · theme_vs_plot (8) ==========
    it("theme_vs_plot", 2, 1, 1,
      "Sana's telescope was the envy of the street, and she guarded it jealously — until the comet week, when she discovered that a wonder seen alone went quiet quickly. She chalked VIEWINGS, FREE on the sidewalk. Neighbors lined up past bedtime, gasping in turn, and Sana found that the comet felt more amazing every time someone new cried out at it.",
      "Which option states the theme rather than a plot event?",
      [K("wonders grow when they are shared"),
       P("Sana chalked a sign and neighbors lined up", "D-DETAIL-AS-MAIN"),
       P("a comet passed during one week", "D-DETAIL-AS-MAIN"),
       P("a girl owned a telescope", "D-DETAIL-AS-MAIN")],
      { note: "theme vs three plot restatements — the defining discrimination" }),
    it("theme_vs_plot", 2, 1, 2,
      "The wrong bus stop turned out to be the right one. Dropped a street early by a rain-blind driver, Marisol sheltered in a doorway that happened to belong to the town's tiny museum — free on Thursdays. She spent the hour among ship models and whale bones she had never known existed, and afterwards she sometimes got off early on purpose, just to see what else the town was hiding.",
      "Which option states the theme rather than a plot event?",
      [K("wrong turns can lead to good discoveries"),
       P("a driver stopped a street early", "D-DETAIL-AS-MAIN"),
       P("the museum was free on Thursdays", "D-DETAIL-AS-MAIN"),
       P("Marisol saw whale bones", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 1, 3,
      "Every apology Tom had ever given was a mumbled 'sorry' with his eyes on his shoes. But after breaking Grandma's teapot — the one from her wedding — mumbled words felt too small. He wrote a letter instead: what he did, why it was careless, and how he would help replace it. Grandma kept the repaired teapot on the shelf. The letter she kept in her purse for years.",
      "Which option states the theme rather than a plot event?",
      [K("a sincere apology explains the wrong and tries to repair it"),
       P("Tom broke his grandma's teapot", "D-DETAIL-AS-MAIN"),
       P("the teapot was repaired", "D-DETAIL-AS-MAIN"),
       P("Grandma kept a letter in her purse", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 1, 4,
      "The lighthouse keeper kept a list of every ship that passed safely in the night. Nobody asked him to; the ships never knew. When he retired after forty years, the harbor master read the list's last page aloud — four thousand names — and everyone on the dock stood silent, understanding at last how his steady work had helped keep the route safe.",
      "Which option states the theme rather than a plot event?",
      [K("unseen service can still be valuable"),
       P("a keeper wrote down ships' names", "D-DETAIL-AS-MAIN"),
       P("the harbor master read a list aloud", "D-DETAIL-AS-MAIN"),
       P("the keeper retired after forty years", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 5,
      "At the lantern festival, the prize always went to the biggest lantern — until the year of the great wind. One by one the giant paper palaces guttered and tore, while Amaya's stubby little lantern, built low and snug around its flame, bobbed on through the dark like a heartbeat. It crossed the finish line alone, the only light left on the river.",
      "Which option states the theme rather than a plot event?",
      [K("what is built to last beats what is built to impress"),
       P("a great wind blew at the festival", "D-DETAIL-AS-MAIN"),
       P("big lanterns tore one by one", "D-DETAIL-AS-MAIN"),
       P("one lantern crossed the line", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 6,
      "Priw the goldfish ate everything first — flakes meant for three fish vanished into one round mouth. He grew grand and golden while Tup and Lin thinned behind the pump. Then came the week the family forgot the flakes. Priw, who had never learned to hunt the tank's green threads, drifted hungry — and it was quick little Tup and Lin who nosed him toward the water-weed and showed him how.",
      "Which option states the theme rather than a plot event?",
      [K("grabbing the most can leave you knowing the least"),
       P("one goldfish ate the others' flakes", "D-DETAIL-AS-MAIN"),
       P("the family forgot to feed the fish", "D-DETAIL-AS-MAIN"),
       P("two fish ate water-weed", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 7,
      "Mud season soaked shoes all over the school, and the boot room filled with complaints. Ede said nothing. Each recess, she simply placed the wettest boots on the drying rack and turned them as they dried. Nobody knew for weeks. When the principal finally saw her and asked why, Ede said dry boots made people kinder all afternoon, and she liked the school kinder.",
      "Which option states the theme rather than a plot event?",
      [K("small quiet care can change a whole place"),
       P("mud season soaked the shoes", "D-DETAIL-AS-MAIN"),
       P("boots were placed on a drying rack", "D-DETAIL-AS-MAIN"),
       P("the principal saw Ede one day", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 8,
      "The twins divided the attic with a chalk line the day they stopped sharing: her books that side, his models this side. The line worked perfectly. It kept out borrowing, and mess, and quarrels — and stories read aloud, and glue passed at the right moment, and company on rainy days. By October the attic was the tidiest, quietest, loneliest room in the house, and the chalk was the first thing they washed away together.",
      "Which option states the theme rather than a plot event?",
      [K("blocking trouble can also block friendship"),
       P("twins drew a chalk line in the attic", "D-DETAIL-AS-MAIN"),
       P("the attic became very tidy", "D-DETAIL-AS-MAIN"),
       P("the chalk was washed away", "D-DETAIL-AS-MAIN")]),

    // ========== LEVEL 2 · apply_theme (8) ==========
    it("apply_theme", 2, 1, 1,
      "Remember Pip, who watered a seed that showed nothing for five weeks and grew the garden's tallest sunflower? Keep Pip's lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Ines keeps practicing her times tables that will not stick, until one day they do"),
       P("Ines plants a sunflower seed in a pot on her own windowsill at home", "D-TOPIC-ADJACENT"),
       P("Ines gives up learning the violin after one single squeaky week of lessons", "D-OPPOSITE"),
       P("Ines buys a violin after seeing a concert", "D-TOPIC-ADJACENT")],
      { note: "transfer: same lesson, different domain — the sunflower option is the surface trap" }),
    it("apply_theme", 2, 1, 2,
      "Remember Jory, who ruined Ann's comic in the rain and chose telling the truth over hiding it. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Cam scratches Dad's bike and leaves a note owning up before Dad sees"),
       P("Cam reads comics carefully indoors", "D-TOPIC-ADJACENT"),
       P("Cam hides the mug he broke behind the cereal boxes where nobody looks", "D-OPPOSITE"),
       P("Cam saves his allowance for weeks to buy a brand-new comic", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 1, 3,
      "Remember Etta and the young bird: she kept pets away and watched from a distance so its parent could return. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Ray stays with a lost toddler and calls a security guard"),
       P("Ray builds every bird in the garden a wooden house", "D-TOPIC-ADJACENT"),
       P("Ray carries a fallen chick home to raise it himself in a shoebox by his bed", "D-OPPOSITE"),
       P("Ray watches an egg hatch on television", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 1, 4,
      "Remember the lighthouse keeper's list — forty years of steady, unseen work that kept the sea-road open. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("the custodian who salts the school steps before anyone arrives every icy morning"),
       P("a singer who performs on television so that millions can applaud her name", "D-OPPOSITE"),
       P("a sailor who names his boat after a lighthouse", "D-TOPIC-ADJACENT"),
       P("a keeper who paints his lighthouse red", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 2, 5,
      "Remember Nell at the bake-off, who withdrew her own cake to help Zeke after his cake collapsed. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("On field day, Vic stops mid-race to help a fallen runner, finishing last together"),
       P("Vic bakes a lemon cake for the fair", "D-TOPIC-ADJACENT"),
       P("On field day, Vic guards his bag of candy so that nobody else gets a single piece", "D-OPPOSITE"),
       P("Vic enters two contests in one day", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 2, 6,
      "Remember Amaya's little lantern, built low and snug around its flame, still burning when the grand paper palaces had torn. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Jo finishes a clear three-paragraph report"),
       P("Jo starts building the biggest, grandest sandcastle the beach has ever seen", "D-OPPOSITE"),
       P("Jo carries a lantern on the camping trip", "D-TOPIC-ADJACENT"),
       P("Jo enters the festival every single year", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 2, 7,
      "Remember Priya and the answer list she slid under the school office door unread, and how seven honest points felt better than ten unfair ones. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Dev's ball lands over the line; he calls it out himself, though no one saw"),
       P("Dev studies spelling every Thursday night", "D-TOPIC-ADJACENT"),
       P("Dev peeks at his sister's cards when she leaves the room, and wins the game", "D-OPPOSITE"),
       P("Dev posts a letter for his teacher", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 2, 8,
      "Remember the twins' chalk line — how a wall that kept out mess and quarrels kept out company too, until washing it away was the happiest chore in the house. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Mia opens the blocked den and welcomes her brother back"),
       P("Mia chalks a hopscotch grid on the path", "D-TOPIC-ADJACENT"),
       P("After a quarrel, Mia labels every pencil she owns so nobody can ever borrow one", "D-OPPOSITE"),
       P("Mia tidies the attic every Sunday", "D-TOPIC-ADJACENT")]),

    // ========== RETENTION RESERVE (8 + 8) ==========
    it("lesson_mistake_fixed", 1, 1, 9,
      "Zia copied Ola's homework to save time, and got the same three answers wrong. Worse, she could not explain them at the board. That night she did the page herself, slowly. Next test her answers were her own — and she could explain every one.",
      QT,
      [K("copying steals your own chance to learn"),
       P("Zia got three answers wrong", "D-DETAIL-AS-MAIN"),
       P("homework is a waste of time", "D-OPPOSITE"),
       P("teachers use whiteboards", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 1, 10,
      "On the coldest morning, Ffion cleared frost from her neighbor's windshield along with her mom's, just because she was out there anyway with the scraper. All winter after that, on trash day, Ffion's family cans came back up the driveway before they were even awake — wheeled by a neighbor who was out there anyway.",
      QT,
      [K("kindness between neighbors can come back around"),
       P("a windshield had frost on it", "D-DETAIL-AS-MAIN"),
       P("trash cans should stay by the road", "D-TOPIC-ADJACENT"),
       P("winter mornings are cold", "D-DETAIL-AS-MAIN")]),
    it("lesson_effort_pays", 1, 2, 9,
      "Rosa could not swim a stroke in June. She would not go in past her waist. All summer she practiced floating, then kicking, then one arm, then the other. On the last beach day, she swam out to the yellow buoy and back — not fast, not far, but every meter of it hers.",
      QT,
      [K("step-by-step effort builds real skill"),
       P("Rosa touched the yellow buoy", "D-DETAIL-AS-MAIN"),
       P("stay out of the sea in June", "D-OPPOSITE"),
       P("beaches have buoys", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 2, 10,
      "Ben teased Ollie about his taped glasses, and the laugh he expected never came — only a horrible quiet. Sorry felt impossible to say, so Ben did it the slow way: a saved seat, a defending word at soccer, and at last the words themselves. 'Took you long enough,' said Ollie — and moved over to make room.",
      QT,
      [K("a wrong can be mended, even slowly"),
       P("Ollie's glasses were taped", "D-DETAIL-AS-MAIN"),
       P("teasing makes people laugh", "D-OPPOSITE"),
       P("soccer happens at lunch", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 11,
      "The crowded lunch line always squeezed out little Yani, last and smallest. Big Aron noticed and simply stood behind him each day like a friendly wall. Years later — Aron on crutches after an accident, the hallway crowded — it was a much taller Yani who walked behind him, all the way, like a friendly wall.",
      QT,
      [K("protection given is remembered and returned"),
       P("the lunch line was crowded", "D-DETAIL-AS-MAIN"),
       P("small children should line up elsewhere", "D-OPPOSITE"),
       P("hallways get crowded", "D-TOPIC-ADJACENT")], { retention: true }),
    it("lesson_effort_pays", 1, 1, 11,
      "The recorder squeaked for everyone, but for Dot it SCREECHED. Her family bought earplugs; the dog left the room. Dot practiced in the garage, ten minutes a day, no more, no matter what. By the spring concert, the screech was gone, and her daily practice had produced clear, steady notes.",
      QT,
      [K("a little practice every day can build a skill"),
       P("the dog left the room", "D-DETAIL-AS-MAIN"),
       P("recorders are hopeless instruments", "D-OPPOSITE"),
       P("garages are for practicing", "D-TOPIC-ADJACENT")], { retention: true }),
    it("lesson_mistake_fixed", 1, 1, 11,
      "Nobody saw Wolf knock the class globe off its stand — but Wolf saw the dent, and Wolf knew. The secret felt like a marble in his shoe. When he finally told Mr Otieno, the telling took ten seconds, the gluing five minutes, and the marble was gone by lunch.",
      QT,
      [K("confessing is quicker and lighter than hiding"),
       P("the globe got a dent", "D-DETAIL-AS-MAIN"),
       P("globes should be bolted down", "D-TOPIC-ADJACENT"),
       P("secrets keep you company", "D-OPPOSITE")], { retention: true }),
    it("lesson_kindness_returned", 1, 1, 12,
      "Half Moon Lane flooded, and the corner store stood in brown water. Mrs. Vo had given credit, candy, and kind words for twenty years. By noon, without one phone call, the street filled with neighbors in rain boots, carrying and mopping — and by evening the store's OPEN sign was the driest thing on the street.",
      QT,
      [K("long kindness may be repaid quickly"),
       P("brown water entered the store", "D-DETAIL-AS-MAIN"),
       P("stores should not give credit", "D-OPPOSITE"),
       P("floods can cover streets", "D-TOPIC-ADJACENT")], { retention: true }),
    it("theme_among_rivals", 2, 1, 9,
      "The chess club's best player, Ines, could beat anyone — and said so often. The club shrank to three. A new teacher, Ms. Drew, asked Ines to spend one term coaching. At first Ines missed playing every game, but she set up practice boards, explained her moves, and helped beginners finish whole matches. By summer the club filled two classrooms. When one coached beginner finally beat her fairly, Ines was surprised to find she had never enjoyed chess more.",
      "Which lesson is best supported by the story?",
      [K("teaching others can make success larger than winning alone"),
       P("competition can help beginners improve", "D-PLAUSIBLE-UNSUPPORTED"),
       P("skilled players should keep their ideas secret", "D-OPPOSITE"),
       P("the club filled two classrooms", "D-DETAIL-AS-MAIN")]),
    it("theme_among_rivals", 2, 2, 10,
      "Papa's workshop looked messy beside the neighbor's neat rows of tools. Papa kept open baskets labeled BIKE, PAINT, and GARDEN, so each basket mixed tools of different shapes and sizes. When a bicycle chain broke, he lifted the BIKE basket and had the wrench, oil, and rag together in seconds. The neighbor stopped teasing and made a task basket of her own.",
      "Which lesson is best supported by the story?",
      [K("a useful system can work well even when it does not look neat"),
       P("taking care of tools shows respect for shared things", "D-PLAUSIBLE-UNSUPPORTED"),
       P("organized systems make work harder", "D-OPPOSITE"),
       P("the bike basket held oil and a rag", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 1, 9,
      "The school play needed a horse, and the horse costume needed two children who could move as one. Rehearsals were a disaster — front legs turning left, back legs right, the teachers crying with laughter. So Fen and Alba practiced everything together for a month: walking home, lining up, even yawning. On the night, the horse trotted, reared, and bowed — and two very different girls came out of one costume as best friends.",
      "Which option states the theme rather than a plot event?",
      [K("cooperation can build friendship"),
       P("a play needed a horse costume", "D-DETAIL-AS-MAIN"),
       P("rehearsals went badly at first", "D-DETAIL-AS-MAIN"),
       P("the horse bowed on the night", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 10,
      "Great-Aunt Bess left Callum her 'treasure', and the whole family imagined jewelry. The box held a trowel, seed packets, and a notebook: fifty years of what she had planted, for whom, and why — a tree for every new baby on the street, roses for every wedding. Callum was disappointed for exactly one spring. Then the first tree he planted blossomed outside the hospital's family courtyard, and he understood what kind of rich his aunt had been.",
      "Which option states the theme rather than a plot event?",
      [K("a life spent giving is its own treasure"),
       P("a box held a trowel and seeds", "D-DETAIL-AS-MAIN"),
       P("the family expected jewelry", "D-DETAIL-AS-MAIN"),
       P("a tree blossomed in spring", "D-DETAIL-AS-MAIN")]),
    it("apply_theme", 2, 1, 9,
      "Remember Wolf and the dented globe — how confessing took ten seconds and carrying the secret had felt like a marble in his shoe. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Tess tells the librarian today about the juice she spilled on page nine"),
       P("Tess polishes the class globe until it shines", "D-TOPIC-ADJACENT"),
       P("Tess quietly slides the juice-stained book to the very bottom of the returns pile", "D-OPPOSITE"),
       P("Tess reads with juice far away from books", "D-TOPIC-ADJACENT")], { retention: true }),
    it("apply_theme", 2, 2, 10,
      "Remember Ede placing wet boots on the school's drying rack — small quiet care that made a whole school kinder. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Ojas quietly sharpens the class pencils"),
       P("Ojas wins the school kindness certificate on stage", "D-TOPIC-ADJACENT"),
       P("Ojas dries only his own boots and leaves everyone else's dripping", "D-OPPOSITE"),
       P("Ojas buys new boots for himself", "D-TOPIC-ADJACENT")], { retention: true }),
    it("theme_among_rivals", 2, 1, 11,
      "The school's quiet-hour challenge raised money for the library, and Vin, who loved to talk, was expected to find it hardest. He completed the challenge, but the surprise was what he noticed: Priw's chair squeaking because he needed a cushion, Lom quietly sharing a clever story idea, and a lonely boy by the window. Afterward Vin found Priw a cushion, asked Lom about the idea, and invited the lonely boy to join him.",
      "Which lesson is best supported by the story?",
      [K("listening helps you notice what other people need"),
       P("finishing a difficult challenge can earn respect", "D-PLAUSIBLE-UNSUPPORTED"),
       P("talking is always wrong", "D-OPPOSITE"),
       P("the challenge raised money for the library", "D-DETAIL-AS-MAIN")], { retention: true }),
    it("apply_theme", 2, 2, 11,
      "Remember the little lantern that finished alone because it was built for the wind, not for the judges. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Bea makes a small volcano that works every time"),
       P("Bea spends every evening decorating her project with gold ribbon and glitter", "D-OPPOSITE"),
       P("Bea enters the lantern festival next year", "D-TOPIC-ADJACENT"),
       P("Bea judges the fair with the teachers", "D-TOPIC-ADJACENT")], { retention: true })
  ]
};
