// Theme & Higher Comprehension — v3 authored bank (wave W2). Every passage is
// a COMPLETE arc (setup → tension → resolution). Themes are concrete child
// morals, phrased fresh each time; L2 theme_among_rivals carries two morally
// plausible readings and the evidence must pick one; theme_vs_plot uses plot
// summaries as distractors; apply_theme transfers the lesson to a new case.
//
// Topic registry: shared telescope, seed race, wrong bus stop, borrowed comic,
// burnt biscuits retry, quiet goalkeeper, nest left alone, snapped crayon
// halves, grandpa's slow watch, wobbly tooth brag, lighthouse keeper's list,
// smallest lantern, muddy boots helper, puzzle corner piece, jam recipe fail,
// paper crane hundred, shy singer duet, stuck tractor teamwork, lost-and-found
// coin, greedy goldfish, mended umbrella, first snow patience, litter robot,
// two ladders, apology letter, echo hello, library whisperer, splinter thank
// you, shared skipping rope, night-light courage, plum tree waiting, homework
// swap honesty.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, prompt, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage, prompt, choices, media: "text", ...extra
});
const QT = "What lesson does this story teach?";

export default {
  skillId: "theme_higher_comprehension",
  skillName: "Theme and Higher Comprehension",
  items: [
    // ========== LEVEL 1 · lesson_mistake_fixed (8) ==========
    it("lesson_mistake_fixed", 1, 1, 1,
      "Jory borrowed Ann's comic and left it out in the rain. The pages wrinkled like crisps. He wanted to hide it under his bed. Instead he showed Ann, said sorry, and spent his pocket money on a new copy. Ann was sad about the comic — but glad he had told the truth.",
      QT,
      [K("owning up to a mistake is better than hiding it"),
       P("a comic was left out in the rain", "D-DETAIL-AS-MAIN"),
       P("never lend anything to anyone", "D-OPPOSITE"),
       P("comics cost pocket money", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 1, 2,
      "Bel's first batch of biscuits came out black as coal. She nearly threw her apron in the bin. Instead she read the recipe again and found her mistake — the oven had been far too hot. The second batch came out golden, and the kitchen smelled like a hug.",
      QT,
      [K("a mistake can teach you how to do better"),
       P("the first biscuits burned black", "D-DETAIL-AS-MAIN"),
       P("baking always goes wrong", "D-OPPOSITE"),
       P("ovens can be hot", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 1, 3,
      "Kit snapped the blue crayon and quickly slid it back in the tin, broken ends together. All morning it bothered him like a stone in a shoe. At last he told Miss May. She smiled, taped the crayon, and said broken things mend easier than secrets.",
      QT,
      [K("a secret mistake feels heavier than a told one"),
       P("a blue crayon got snapped", "D-DETAIL-AS-MAIN"),
       P("crayons should never be shared", "D-OPPOSITE"),
       P("tape can fix many things", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 1, 4,
      "Ravi got off the bus one stop early to avoid sitting next to a new boy. The walk was long, his bag was heavy, and he still met the new boy at the school gate — who grinned and carried the bag the last stretch. The next day they sat together.",
      QT,
      [K("do not judge someone before you know them"),
       P("Ravi's bag was heavy", "D-DETAIL-AS-MAIN"),
       P("always get off the bus early", "D-OPPOSITE"),
       P("school gates are meeting places", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 2, 5,
      "Lena bragged that her wobbly tooth would come out first, before Sam's. She wiggled it all day just to win. It came out at last — but it hurt, and there was no prize, only Sam saying 'well done' kindly. Lena wished she had let it happen in its own time.",
      QT,
      [K("racing to be first can spoil the fun"),
       P("Lena's tooth was wobbly", "D-DETAIL-AS-MAIN"),
       P("teeth should never come out", "D-OPPOSITE"),
       P("Sam said well done", "D-DETAIL-AS-MAIN")]),
    it("lesson_mistake_fixed", 1, 2, 6,
      "Min fed the class goldfish twice, then once more, because it always looked hungry. The tank turned cloudy and the fish went slow and sad. The pet-shop lady explained: too much food is its own kind of unkindness. Min learned to feed a pinch, no more, and the water cleared.",
      QT,
      [K("too much of a good thing can do harm"),
       P("the tank water turned cloudy", "D-DETAIL-AS-MAIN"),
       P("goldfish should not be fed", "D-OPPOSITE"),
       P("pet shops know about fish", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 2, 7,
      "In the quiet library, Posy whispered a joke, then a story, then a song. The librarian did not scold. She just pointed at the reading corner, where a small boy had lost his place three times. Posy saw his cross little face — and understood without one word being said.",
      QT,
      [K("your noise can spoil things for others"),
       P("Posy whispered a song", "D-DETAIL-AS-MAIN"),
       P("libraries should ban jokes", "D-OPPOSITE"),
       P("librarians point at corners", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 2, 8,
      "Dara promised to water next-door's plum tree during the holiday, then forgot for a whole hot week. The leaves curled. She watered it every evening after that, twice on the hottest days, and by the end of summer the tree stood green again — and Dara never made a promise carelessly again.",
      QT,
      [K("a promise matters even when it is hard to keep"),
       P("the plum leaves curled up", "D-DETAIL-AS-MAIN"),
       P("never help your neighbours", "D-OPPOSITE"),
       P("summer weeks can be hot", "D-TOPIC-ADJACENT")]),

    // ========== LEVEL 1 · lesson_kindness_returned (8) ==========
    it("lesson_kindness_returned", 1, 1, 1,
      "Every wet morning, Iris carried her little brother's boots so he could climb the bus steps. One icy day, Iris slipped and her books flew everywhere. Before she could blink, her brother and three of his small friends were gathering pages from every puddle.",
      QT,
      [K("kindness you give comes back to you"),
       P("books flew into the puddles", "D-DETAIL-AS-MAIN"),
       P("icy days are for staying home", "D-TOPIC-ADJACENT"),
       P("little brothers are a nuisance", "D-OPPOSITE")]),
    it("lesson_kindness_returned", 1, 1, 2,
      "The new girl ate lunch alone, so Bo moved his tray next to hers and shared his grapes. Weeks later, when Bo broke his arm and could not cut his food, a tray slid quietly next to his — and the new girl cut his dinner into pieces without being asked.",
      QT,
      [K("small kindnesses grow into friendship"),
       P("Bo shared his grapes", "D-DETAIL-AS-MAIN"),
       P("eat lunch alone if you can", "D-OPPOSITE"),
       P("broken arms make eating hard", "D-DETAIL-AS-MAIN")]),
    it("lesson_kindness_returned", 1, 1, 3,
      "Grandpa Tan fixed umbrellas for the whole street and never took a penny. 'Rain falls on everyone,' he said. When his roof leaked in the big storm, half the street appeared at his door with ladders, buckets, and a hot dinner in a basket.",
      QT,
      [K("a helper is never left to struggle alone"),
       P("Grandpa Tan fixed umbrellas", "D-DETAIL-AS-MAIN"),
       P("keep your pennies for yourself", "D-OPPOSITE"),
       P("storms can break roofs", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 1, 4,
      "At the fair, Nia's last coin rolled under the lost-and-found table. The boy behind the table crawled in the dust to fetch it, and Nia used it to buy two toffee apples — one for herself, and one for a dusty, grinning boy.",
      QT,
      [K("sharing doubles a good moment"),
       P("a coin rolled under a table", "D-DETAIL-AS-MAIN"),
       P("keep both toffee apples", "D-OPPOSITE"),
       P("fairs sell toffee apples", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 5,
      "Wren was the quietest singer in choir, so quiet her words were mostly shapes. Ana stood beside her every week and sang a little softer, so Wren could hear her own voice. At the concert, two voices rose together — and one of them had never sounded so brave.",
      QT,
      [K("gentle support helps courage grow"),
       P("Wren sang very quietly", "D-DETAIL-AS-MAIN"),
       P("loud singers matter most", "D-OPPOSITE"),
       P("choirs give concerts", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 6,
      "Old Mr Price's tractor sank in the mud, and he sat a long time, too proud to wave for help. The Okafor children saw anyway. They fetched planks, their mother, and a rope — and afterwards Mr Price's orchard gate, locked for years, stood open with a sign: APPLES, HELP YOURSELVES.",
      QT,
      [K("helping without being asked opens hearts"),
       P("a tractor sank in the mud", "D-DETAIL-AS-MAIN"),
       P("pride is always right", "D-OPPOSITE"),
       P("orchards grow apples", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 7,
      "Jude found a splinter of glass on the slide and spent his whole break carefully clearing every piece, missing the football game. Nobody noticed — he thought. On Friday, a note appeared in his tray: 'Thank you from the little ones. You didn't know we saw.'",
      QT,
      [K("quiet good deeds are still seen"),
       P("there was glass on the slide", "D-DETAIL-AS-MAIN"),
       P("football matters more than safety", "D-OPPOSITE"),
       P("notes go in trays", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 8,
      "One skipping rope, eleven children. Quarrels every break — until Fern started counting everyone in: two turns each, jumpers become turners, turners become jumpers. The rope never rested, the queue sang the counting song, and break time stopped ending in tears.",
      QT,
      [K("fair sharing lets everyone enjoy more"),
       P("eleven children wanted one rope", "D-DETAIL-AS-MAIN"),
       P("the strongest should keep the rope", "D-OPPOSITE"),
       P("skipping has counting songs", "D-TOPIC-ADJACENT")]),

    // ========== LEVEL 1 · lesson_effort_pays (8) ==========
    it("lesson_effort_pays", 1, 1, 1,
      "Pip's sunflower seed sat in the soil doing nothing while Marco's shot up like a green rocket. Pip watered anyway, every day, even when it felt silly. In week five, a late little stem appeared — and by August, Pip's flower was the tallest in the whole garden.",
      QT,
      [K("keep trying when progress is slow"),
       P("Marco's flower grew first", "D-DETAIL-AS-MAIN"),
       P("slow seeds never grow", "D-OPPOSITE"),
       P("sunflowers grow in gardens", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 1, 2,
      "The monkey bars defeated Ola all autumn. Each break she got one bar farther before dropping. Winter gloves, spring blisters, a hundred small tries. On the last day of term she swung across the whole row — and the playground burst into cheering she never expected.",
      QT,
      [K("many small tries add up to a big win"),
       P("Ola wore winter gloves", "D-DETAIL-AS-MAIN"),
       P("give up after one autumn", "D-OPPOSITE"),
       P("playgrounds have monkey bars", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 1, 3,
      "Tam wanted to fold one hundred paper cranes like the ones in the library book. By crane twenty his folds were crooked; by fifty, his thumbs ached. He folded on the bus, at breakfast, in the bath queue. Crane one hundred sat perfectly on his windowsill before his birthday.",
      QT,
      [K("big goals are finished one small step at a time"),
       P("his thumbs ached at fifty", "D-DETAIL-AS-MAIN"),
       P("one hundred is too many", "D-OPPOSITE"),
       P("libraries have craft books", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 1, 4,
      "Nobody wanted goalkeeper, so quiet Emil took the gloves. He practised alone against the garage wall all season — thud, catch, thud, catch. In the last match, with the score level, Emil flew sideways and tipped the ball over the bar, and his name was the loudest word on the pitch.",
      QT,
      [K("practice done quietly still shines in the end"),
       P("Emil practised against a garage", "D-DETAIL-AS-MAIN"),
       P("goalkeepers never matter", "D-OPPOSITE"),
       P("matches can end level", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 2, 5,
      "The first snow would not stick, and Ceri checked the window a hundred times. Gran said watching would not hurry the sky, so Ceri stopped watching and got ready instead: gloves dried, sledge waxed, carrot saved. When the deep snow finally came, she was first — and readiest — on the hill.",
      QT,
      [K("use waiting time to get ready"),
       P("the first snow would not stick", "D-DETAIL-AS-MAIN"),
       P("watching the sky brings snow", "D-OPPOSITE"),
       P("sledges go on hills", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 2, 6,
      "The jigsaw's last corner piece was missing, and everyone gave up — except Ash, who liked finishing things. He searched the sofa, the stairs, the dog's basket, and finally the turn-up of Grandad's trouser leg. The picture on the table was complete because one person would not stop looking.",
      QT,
      [K("finishing takes one person who will not quit"),
       P("the piece was in a trouser turn-up", "D-DETAIL-AS-MAIN"),
       P("lost pieces stay lost", "D-OPPOSITE"),
       P("dogs sleep in baskets", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 2, 7,
      "Grandpa's watch ran five minutes slow, and he liked it that way — but the mending of it became Suvi's winter project. Springs, screws, a magnifying glass, three failed tries, one bent tool. When the watch finally ticked true, Grandpa wore it proudly... set five minutes slow again, for old times' sake.",
      QT,
      [K("hard work is worth it even for small things"),
       P("the watch ran five minutes slow", "D-DETAIL-AS-MAIN"),
       P("old watches cannot be fixed", "D-OPPOSITE"),
       P("winter is for projects", "D-TOPIC-ADJACENT")]),
    it("lesson_effort_pays", 1, 2, 8,
      "The school's litter-picking robot kept jamming, and Class 5 kept unjamming it — new wheels from a skateboard, a brush from the lost kit box, tape, more tape. The head teacher said buy a new one. Class 5 said their patched robot, wobbling proudly down the corridor, was already the best one in the world.",
      QT,
      [K("caring for something makes it precious"),
       P("the robot got skateboard wheels", "D-DETAIL-AS-MAIN"),
       P("broken things belong in bins", "D-OPPOSITE"),
       P("schools have corridors", "D-TOPIC-ADJACENT")]),

    // ========== LEVEL 2 · theme_among_rivals (8) ==========
    it("theme_among_rivals", 2, 1, 1,
      "Two ladders leaned on the orchard wall: Jo's new silver one and the old wooden one Jo's mum had climbed as a girl. Jo always chose the silver ladder — until the day it slid on wet grass and the wooden one, with its worn, deep-gripped rungs, carried her safely up to the highest apples. That autumn Jo oiled the old ladder's joints herself, and the silver one waited under a sheet.",
      "Two lessons seem possible. Which one does the story support MOST?",
      [K("old things earn trust that shiny things have not"),
       P("never buy anything new when something old still works", "D-OPPOSITE"),
       P("picking apples is dangerous", "D-TOPIC-ADJACENT"),
       P("a ladder slid on the wet grass", "D-DETAIL-AS-MAIN")],
      { note: "rival reading 'new things are bad' is too strong; evidence supports earned trust" }),
    it("theme_among_rivals", 2, 1, 2,
      "Yusuf practised the trumpet loudly and often, and told everyone about the concert. His sister Amal practised the harp quietly behind a closed door, and told no one. At the concert Yusuf played brilliantly and bowed twice. Amal played one simple tune so beautifully that the hall forgot to clap for a moment. On the way home, Yusuf asked, for the first time, if she would teach him the quiet way of practising.",
      "Two lessons seem possible. Which one does the story support MOST?",
      [K("quiet skill can speak louder than showing off"),
       P("trumpets are better than harps", "D-TOPIC-ADJACENT"),
       P("never tell anyone about a concert", "D-OPPOSITE"),
       P("the hall forgot to clap once", "D-DETAIL-AS-MAIN")]),
    it("theme_among_rivals", 2, 1, 3,
      "The night-light argument ran all week: Dad said seven-year-olds do not need one, and Milo said the dark had shapes in it. The compromise was a torch on the pillow, 'for emergencies'. Milo used it the first night, held it the second, and by Friday it lay under the bed, forgotten — because knowing he COULD switch it on had quietly shrunk every shape in the dark.",
      "Which lesson fits best?",
      [K("knowing help is near can build courage"),
       P("darkness is truly dangerous", "D-OPPOSITE"),
       P("torches belong on pillows", "D-DETAIL-AS-MAIN"),
       P("fathers are always right", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("theme_among_rivals", 2, 1, 4,
      "Priya found the spelling list for Friday's test lying by the photocopier — every word, a day early. She looked at it a long moment, then posted it back under the staffroom door. Her score on Friday was seven out of ten, her ordinary score. But when Mr Field told the class someone had returned the list unread, Priya sat a little taller than any ten out of ten had ever made her sit.",
      "Two lessons seem possible. Which one does the story support MOST?",
      [K("being honest feels better than winning unfairly"),
       P("always aim for ten out of ten", "D-PLAUSIBLE-UNSUPPORTED"),
       P("spelling tests do not matter", "D-OPPOSITE"),
       P("a list lay by the photocopier", "D-DETAIL-AS-MAIN")]),
    it("theme_among_rivals", 2, 2, 5,
      "When the storm knocked the nest from the hedge, Etta wanted to carry the eggs indoors at once, to save them with blankets and a lamp. Her grandmother stopped her: 'The mother is watching from the fence. Help small, not big.' They wedged the nest back, moved away, and watched the mother return. All three chicks hatched in the hedge, wild and loud, needing nobody's lamp.",
      "Which lesson fits best?",
      [K("the gentlest useful action can be best"),
       P("never touch anything outdoors", "D-OPPOSITE"),
       P("storms knock down nests", "D-DETAIL-AS-MAIN"),
       P("lamps can keep eggs warm", "D-TOPIC-ADJACENT")],
      { note: "rival 'always rescue dramatically' vs supported 'restrain and trust nature'" }),
    it("theme_among_rivals", 2, 2, 6,
      "The junior bake-off allowed one entry each. Zeke's jam roll collapsed an hour before judging, and he stood in the wreckage of sponge, out of time and out of hope. Nell looked at her own perfect lemon cake, then cut it in half, plated the halves separately, and told the judges the second entry was Zeke's idea as much as hers. They did not win. Neither of them ever called it a loss.",
      "Two lessons seem possible. Which one does the story support MOST?",
      [K("friendship can matter more than prizes"),
       P("never enter a bake-off", "D-OPPOSITE"),
       P("lemon cakes beat jam rolls", "D-TOPIC-ADJACENT"),
       P("a jam roll collapsed before judging", "D-DETAIL-AS-MAIN")]),
    it("theme_among_rivals", 2, 2, 7,
      "Every evening, Kofi's echo game in the stairwell — HELLO... hello... hello — annoyed the third floor. Mrs Adjei came down, and everyone waited for the telling-off. Instead she taught him the trick her own father taught her: the softer you call, the closer the echo leans in to listen. After that, the stairwell heard whisper-games, and the third floor heard nothing at all.",
      "Which lesson fits best?",
      [K("gentle words teach better than anger"),
       P("echoes live in stairwells", "D-DETAIL-AS-MAIN"),
       P("games should be banned indoors", "D-OPPOSITE"),
       P("third floors are grumpy", "D-PLAUSIBLE-UNSUPPORTED")]),
    it("theme_among_rivals", 2, 2, 8,
      "The class voted to spend the prize money on a party. Robin alone voted for new goal nets, and lost, nineteen to one. At the party, Robin neither sulked in the corner nor pretended the nets had been a silly idea. He handed out cake, laughed at the games — and in spring, when the nets budget came round again, nineteen hands remembered his good grace and went up with his.",
      "Two lessons seem possible. Which one does the story support MOST?",
      [K("lose well now; gain friends later"),
       P("parties are better than nets", "D-TOPIC-ADJACENT"),
       P("never vote against the class", "D-OPPOSITE"),
       P("the vote was nineteen to one", "D-DETAIL-AS-MAIN")]),

    // ========== LEVEL 2 · theme_vs_plot (8) ==========
    it("theme_vs_plot", 2, 1, 1,
      "Sana's telescope was the envy of the street, and she guarded it jealously — until the comet week, when she discovered that a wonder seen alone goes quiet quickly. She chalked VIEWINGS, FREE on the pavement. Neighbours queued past bedtime, gasping in turn, and Sana found that the comet grew more amazing every time someone new cried out at it.",
      "Which of these is the THEME — not just what happened?",
      [K("wonders grow when they are shared"),
       P("Sana chalked a sign and neighbours queued", "D-DETAIL-AS-MAIN"),
       P("a comet passed during one week", "D-DETAIL-AS-MAIN"),
       P("a girl owned a telescope", "D-DETAIL-AS-MAIN")],
      { note: "theme vs three plot restatements — the defining discrimination" }),
    it("theme_vs_plot", 2, 1, 2,
      "The wrong bus stop turned out to be the right one. Dropped a street early by a rain-blind driver, Marisol sheltered in a doorway that happened to belong to the town's tiny museum — free on Thursdays. She spent the hour among ship models and whale bones she had never known existed, and afterwards she sometimes got off early on purpose, just to see what else the town was hiding.",
      "Which of these is the THEME — not just what happened?",
      [K("wrong turns can lead to good discoveries"),
       P("a driver stopped a street early", "D-DETAIL-AS-MAIN"),
       P("the museum was free on Thursdays", "D-DETAIL-AS-MAIN"),
       P("Marisol saw whale bones", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 1, 3,
      "Every apology Tom had ever given was a mumbled 'sorry' with his eyes on his shoes. But breaking Gran's teapot — the one from her wedding — mumbled words felt too small. He wrote a letter instead: what he did, why it was careless, what he would save up to mend. Gran kept the taped-together teapot on the shelf. The letter she kept in her purse, for years.",
      "Which of these is the THEME — not just what happened?",
      [K("a true apology names the wrong and mends it"),
       P("Tom broke his gran's teapot", "D-DETAIL-AS-MAIN"),
       P("the teapot was taped back together", "D-DETAIL-AS-MAIN"),
       P("Gran kept a letter in her purse", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 1, 4,
      "The lighthouse keeper kept a list of every ship that passed safely in the night. Nobody asked him to; the ships never knew. When he retired after forty years, the harbourmaster read the list's last page aloud — four thousand names — and the whole quay stood silent, understanding at last what steady, unseen work had been holding their sea-road open.",
      "Which of these is the THEME — not just what happened?",
      [K("steady unseen work holds the world together"),
       P("a keeper wrote down ships' names", "D-DETAIL-AS-MAIN"),
       P("the harbourmaster read a list aloud", "D-DETAIL-AS-MAIN"),
       P("the keeper retired after forty years", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 5,
      "At the lantern festival, the prize always went to the biggest lantern — until the year of the great wind. One by one the giant paper palaces guttered and tore, while Amaya's stubby little lantern, built low and snug around its flame, bobbed on through the dark like a heartbeat. It crossed the finish line alone, the only light left on the river.",
      "Which of these is the THEME — not just what happened?",
      [K("what is built to last beats what is built to impress"),
       P("a great wind blew at the festival", "D-DETAIL-AS-MAIN"),
       P("big lanterns tore one by one", "D-DETAIL-AS-MAIN"),
       P("one lantern crossed the line", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 6,
      "Priw the goldfish ate everything first — flakes meant for three fish vanished into one round mouth. He grew grand and golden while Tup and Lin thinned behind the pump. Then came the week the family forgot the flakes. Priw, who had never learned to hunt the tank's green threads, drifted hungry — and it was quick little Tup and Lin who nosed him toward the water-weed and showed him how.",
      "Which of these is the THEME — not just what happened?",
      [K("grabbing the most can leave you knowing the least"),
       P("one goldfish ate the others' flakes", "D-DETAIL-AS-MAIN"),
       P("the family forgot to feed the fish", "D-DETAIL-AS-MAIN"),
       P("two fish ate water-weed", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 7,
      "Mud season ruined every shoe in the village school, and the cloakroom filled with squelching and complaints. Little Ede said nothing. Each break, she simply lined the worst boots by the radiator and turned them as they dried. Nobody knew for weeks. When the head finally caught her at it and asked why, Ede shrugged: warm boots made people kinder all afternoon, and she liked the school kinder.",
      "Which of these is the THEME — not just what happened?",
      [K("small quiet care can change a whole place"),
       P("mud season ruined the shoes", "D-DETAIL-AS-MAIN"),
       P("boots were dried by a radiator", "D-DETAIL-AS-MAIN"),
       P("the head caught Ede one day", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 8,
      "The twins divided the attic with a chalk line the day they stopped sharing: her books that side, his models this side. The line worked perfectly. It kept out borrowing, and mess, and quarrels — and stories read aloud, and glue passed at the right moment, and company on rainy days. By October the attic was the tidiest, quietest, loneliest room in the house, and the chalk was the first thing they washed away together.",
      "Which of these is the THEME — not just what happened?",
      [K("blocking trouble can also block friendship"),
       P("twins drew a chalk line in the attic", "D-DETAIL-AS-MAIN"),
       P("the attic became very tidy", "D-DETAIL-AS-MAIN"),
       P("the chalk was washed away", "D-DETAIL-AS-MAIN")]),

    // ========== LEVEL 2 · apply_theme (8) ==========
    it("apply_theme", 2, 1, 1,
      "Remember Pip, who watered a seed that showed nothing for five weeks and grew the garden's tallest sunflower? Keep Pip's lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Ines keeps practising her times tables that will not stick, until one day they do"),
       P("Ines plants a sunflower seed in a pot on her own windowsill at home", "D-TOPIC-ADJACENT"),
       P("Ines gives up learning the violin after one single squeaky week of lessons", "D-OPPOSITE"),
       P("Ines waters her plant once and forgets it", "D-OPPOSITE")],
      { note: "transfer: same lesson, different domain — the sunflower option is the surface trap" }),
    it("apply_theme", 2, 1, 2,
      "Remember Jory, who ruined Ann's comic in the rain and chose telling the truth over hiding it. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Cam scratches Dad's bike and leaves a note owning up before Dad sees"),
       P("Cam reads comics carefully indoors", "D-TOPIC-ADJACENT"),
       P("Cam hides the mug he broke behind the cereal boxes where nobody looks", "D-OPPOSITE"),
       P("Cam saves his pocket money for weeks to buy a brand-new comic", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 1, 3,
      "Remember Etta and the fallen nest: her grandmother taught her to 'help small, not big', wedging the nest back and letting the mother bird do the rest. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Ray stays with a lost toddler and calls a guard"),
       P("Ray builds every bird in the garden a wooden house", "D-TOPIC-ADJACENT"),
       P("Ray carries a fallen chick home to raise it himself in a shoebox by his bed", "D-OPPOSITE"),
       P("Ray watches an egg hatch on television", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 1, 4,
      "Remember the lighthouse keeper's list — forty years of steady, unseen work that kept the sea-road open. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("the caretaker who salts the school steps before anyone arrives, every icy morning, unthanked"),
       P("a singer who performs on television so that millions can applaud her name", "D-OPPOSITE"),
       P("a sailor who names his boat after a lighthouse", "D-TOPIC-ADJACENT"),
       P("a keeper who paints his lighthouse red", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 2, 5,
      "Remember Nell at the bake-off, who cut her perfect cake in half so her friend still had an entry, and never called it a loss. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("On sports day, Vic stops mid-race to pull up a fallen runner, finishing last together"),
       P("Vic bakes a lemon cake for the fair", "D-TOPIC-ADJACENT"),
       P("On sports day, Vic guards his bag of sweets so that nobody else gets a single one", "D-OPPOSITE"),
       P("Vic enters two contests in one day", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 2, 6,
      "Remember Amaya's little lantern, built low and snug around its flame, still burning when the grand paper palaces had torn. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Jo writes three strong sentences instead of an unfinished epic"),
       P("Jo starts building the biggest, grandest sandcastle the beach has ever seen", "D-OPPOSITE"),
       P("Jo carries a lantern on the camping trip", "D-TOPIC-ADJACENT"),
       P("Jo enters the festival every single year", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 2, 7,
      "Remember Priya and the spelling list she posted back under the staffroom door unread, and how seven honest marks felt taller than ten unfair ones. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Dev's ball lands over the line; he calls it out himself, though no one saw"),
       P("Dev studies spelling every Thursday night", "D-TOPIC-ADJACENT"),
       P("Dev peeks at his sister's cards when she leaves the room, and wins the game", "D-OPPOSITE"),
       P("Dev posts a letter for his teacher", "D-TOPIC-ADJACENT")]),
    it("apply_theme", 2, 2, 8,
      "Remember the twins' chalk line — how a wall that kept out mess and quarrels kept out company too, until washing it away was the happiest chore in the house. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Mia opens the blocked den and welcomes her brother back"),
       P("Mia chalks a hopscotch grid on the path", "D-TOPIC-ADJACENT"),
       P("After a quarrel, Mia labels every pencil she owns so nobody can ever borrow one", "D-OPPOSITE"),
       P("Mia tidies the attic every Sunday", "D-TOPIC-ADJACENT")]),

    // ========== RETENTION RESERVE (8 + 8) ==========
    it("lesson_mistake_fixed", 1, 1, 9,
      "Zia copied Ola's homework to save time, and got the same three answers wrong. Worse, she could not explain them at the board. That night she did the page herself, slowly. Next test her answers were her own — and she could explain every one.",
      QT,
      [K("copying steals your own chance to learn"),
       P("Zia got three answers wrong", "D-DETAIL-AS-MAIN"),
       P("homework is a waste of time", "D-OPPOSITE"),
       P("teachers use whiteboards", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 1, 10,
      "On the coldest morning, Ffion cleared frost from her neighbour's windscreen along with her mum's, just because she was out there anyway with the scraper. All winter after that, on bin day, Ffion's family bins came back up the drive before they were even awake — wheeled by a neighbour who was out there anyway.",
      QT,
      [K("neighbourly kindness circles back around"),
       P("a windscreen had frost on it", "D-DETAIL-AS-MAIN"),
       P("bins should stay by the road", "D-TOPIC-ADJACENT"),
       P("winter mornings are cold", "D-DETAIL-AS-MAIN")]),
    it("lesson_effort_pays", 1, 2, 9,
      "Rosa could not swim a stroke in June. She would not go in past her waist. All summer she practised floating, then kicking, then one arm, then the other. On the last beach day, she swam out to the yellow buoy and back — not fast, not far, but every metre of it hers.",
      QT,
      [K("step-by-step effort builds real skill"),
       P("Rosa touched the yellow buoy", "D-DETAIL-AS-MAIN"),
       P("stay out of the sea in June", "D-OPPOSITE"),
       P("beaches have buoys", "D-TOPIC-ADJACENT")]),
    it("lesson_mistake_fixed", 1, 2, 10,
      "Ben teased Ollie about his taped glasses, and the laugh he expected never came — only a horrible quiet. Sorry felt impossible to say, so Ben did it the slow way: a saved seat, a defending word at football, and at last the words themselves. 'Took you long enough,' said Ollie — and shoved up to make room.",
      QT,
      [K("a wrong can be mended, even slowly"),
       P("Ollie's glasses were taped", "D-DETAIL-AS-MAIN"),
       P("teasing makes people laugh", "D-OPPOSITE"),
       P("football happens at lunch", "D-TOPIC-ADJACENT")]),
    it("lesson_kindness_returned", 1, 2, 11,
      "The lunch queue crush always squeezed out little Yani, last and smallest. Big Aron noticed, and simply stood behind him each day like a friendly wall. Years later — Aron on crutches after his accident, the corridor crowded — it was a much taller Yani who walked behind him, all the way, like a friendly wall.",
      QT,
      [K("protection given is remembered and returned"),
       P("the lunch queue had a crush", "D-DETAIL-AS-MAIN"),
       P("small children should queue elsewhere", "D-OPPOSITE"),
       P("corridors get crowded", "D-TOPIC-ADJACENT")], { retention: true }),
    it("lesson_effort_pays", 1, 1, 11,
      "The recorder squeaked for everyone, but for Dot it SCREECHED. Her family bought earplugs; the dog left the room. Dot practised in the shed, ten minutes a day, no more, no matter what. By the spring concert, the screech had worn away like a rough edge, and the shed concerts had quietly become rather good.",
      QT,
      [K("a little practice every day wears problems smooth"),
       P("the dog left the room", "D-DETAIL-AS-MAIN"),
       P("recorders are hopeless instruments", "D-OPPOSITE"),
       P("sheds are for practising", "D-TOPIC-ADJACENT")], { retention: true }),
    it("lesson_mistake_fixed", 1, 1, 11,
      "Nobody saw Wolf knock the class globe off its stand — but Wolf saw the dent, and Wolf knew. The secret felt like a marble in his shoe. When he finally told Mr Otieno, the telling took ten seconds, the gluing five minutes, and the marble was gone by lunch.",
      QT,
      [K("confessing is quicker and lighter than hiding"),
       P("the globe got a dent", "D-DETAIL-AS-MAIN"),
       P("globes should be bolted down", "D-TOPIC-ADJACENT"),
       P("secrets keep you company", "D-OPPOSITE")], { retention: true }),
    it("lesson_kindness_returned", 1, 1, 12,
      "Half Moon Lane flooded, and the corner shop stood in brown water. Mrs Vo had given credit, sweets, and kind words for twenty years. By noon, without one phone call, the lane filled with neighbours in wellies, carrying and mopping — and by evening the shop's OPEN sign was the driest thing on the street.",
      QT,
      [K("long kindness may be repaid quickly"),
       P("a foot of water entered the shop", "D-DETAIL-AS-MAIN"),
       P("shops should not give credit", "D-OPPOSITE"),
       P("floods happen on lanes", "D-TOPIC-ADJACENT")], { retention: true }),
    it("theme_among_rivals", 2, 1, 9,
      "The chess club's best player, Ines, could beat anyone — and said so, often. The club shrank to three. New teacher Ms Drew asked Ines to spend one term coaching instead of winning. It itched at first, losing on purpose to show a trick. But by summer the club filled two classrooms, and when a small coached beginner finally beat her fair and square, Ines was surprised to find she had never enjoyed chess more.",
      "Two lessons seem possible. Which one does the story support MOST?",
      [K("lifting others can beat winning alone"),
       P("chess clubs need two classrooms", "D-DETAIL-AS-MAIN"),
       P("never let anyone win", "D-OPPOSITE"),
       P("beginners ruin clubs", "D-OPPOSITE")]),
    it("theme_among_rivals", 2, 2, 10,
      "Papa's garden was chaos — beans in with roses, pumpkins wandering the path — and next door's garden was ruler-straight rows. Next door teased; Papa just picked. When blight took the whole street's tomatoes, it hopped easily down next door's tidy tomato rows but got lost in Papa's jumble, where marigolds and garlic broke its path. That autumn, next door's rows had two new residents: marigolds, and a little wandering pumpkin.",
      "Which lesson fits best?",
      [K("there is hidden wisdom in ways that look untidy"),
       P("blight took the street's tomatoes", "D-DETAIL-AS-MAIN"),
       P("neat rows are always wrong", "D-OPPOSITE"),
       P("pumpkins wander paths", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 1, 9,
      "The school play needed a horse, and the horse costume needed two children who could move as one. Rehearsals were disaster — front legs turning left, back legs right, the audience of teachers crying with laughter. So Fen and Alba practised everything together for a month: walking home, queueing, even yawning. On the night, the horse trotted, reared, and bowed — and two very different girls came out of one costume as best friends.",
      "Which of these is the THEME — not just what happened?",
      [K("working as one can join people for good"),
       P("a play needed a horse costume", "D-DETAIL-AS-MAIN"),
       P("rehearsals went badly at first", "D-DETAIL-AS-MAIN"),
       P("the horse bowed on the night", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 10,
      "Great-Aunt Bess left Callum her 'treasure', and the whole family imagined jewellery. The box held a trowel, seed packets, and a notebook: fifty years of what she had planted, for whom, and why — a tree for every new baby on the street, roses for every wedding. Callum was disappointed for exactly one spring. Then the first of HIS trees blossomed outside the maternity window, and he understood what kind of rich his aunt had been.",
      "Which of these is the THEME — not just what happened?",
      [K("a life spent giving is its own treasure"),
       P("a box held a trowel and seeds", "D-DETAIL-AS-MAIN"),
       P("the family expected jewellery", "D-DETAIL-AS-MAIN"),
       P("a tree blossomed in spring", "D-DETAIL-AS-MAIN")]),
    it("apply_theme", 2, 1, 9,
      "Remember Wolf and the dented globe — how confessing took ten seconds and carrying the secret had felt like a marble in his shoe. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Tess tells the librarian TODAY about the juice she spilled on page nine"),
       P("Tess polishes the class globe till it shines", "D-TOPIC-ADJACENT"),
       P("Tess quietly slides the juice-stained book to the very bottom of the returns pile", "D-OPPOSITE"),
       P("Tess reads with juice far away from books", "D-TOPIC-ADJACENT")], { retention: true }),
    it("apply_theme", 2, 2, 10,
      "Remember Ede drying the village school's boots by the radiator — small quiet care that made a whole school kinder. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Ojas sharpens the class pencil pot every morning before anyone notices"),
       P("Ojas wins the school kindness certificate on stage", "D-TOPIC-ADJACENT"),
       P("Ojas dries his own boots by the radiator and leaves everyone else's dripping", "D-OPPOSITE"),
       P("Ojas buys new boots for himself", "D-TOPIC-ADJACENT")], { retention: true }),
    it("theme_among_rivals", 2, 1, 11,
      "The sponsored silence raised money for the library, and chatterbox Vin was everyone's favourite joke entry. He lasted the whole day — but the surprise was what he heard in his own silence: Priw's chair squeaking for a cushion, quiet Lom's brilliant mutterings over the maths, the lonely hum of the boy by the window. Vin never became a quiet boy. But he became a boy who sometimes chose to listen, and three people's days got better when he did.",
      "Which lesson fits best?",
      [K("listening shows you what talking drowns out"),
       P("a sponsored silence raised money", "D-DETAIL-AS-MAIN"),
       P("talking is always wrong", "D-OPPOSITE"),
       P("libraries need cushions", "D-TOPIC-ADJACENT")], { retention: true }),
    it("apply_theme", 2, 2, 11,
      "Remember the little lantern that finished alone because it was built for the wind, not for the judges. Keep that lesson in mind.",
      "Which new situation shows the SAME lesson?",
      [K("Bea makes a small volcano that works every time"),
       P("Bea spends every evening decorating her project with gold ribbon and glitter", "D-OPPOSITE"),
       P("Bea enters the lantern festival next year", "D-TOPIC-ADJACENT"),
       P("Bea judges the fair with the teachers", "D-TOPIC-ADJACENT")], { retention: true })
  ]
};
