// Complete story arcs; plausible rival messages, theme versus plot and independent transfer.
// Every level contains 32 mastery items (16 per phase) and 8 reserves.

const K = t => ({ t, r: "KEY", k: true });
const P = (t, r) => ({ t, r });
const it = (u, lvl, ph, v, passage, prompt, choices, extra = {}) => ({
  u, lvl, ph, v, fmt: "COMPREHENSION", cell: u, passage, prompt, choices, media: "text", ...extra
});
const QT = "What lesson does this story teach?";

export default {
  skillId: "theme_higher_comprehension",
  skillName: "Theme and Higher Comprehension",
  items: [
    // ========== LEVEL 1 · lesson_mistake_fixed (8) ==========
    it("lesson_mistake_fixed", 1, 1, 1,
      "Jory left Ann's comic in the rain. The pages stuck together. He wanted to hide it, but told Ann instead. He bought a new copy with his savings. Ann thanked him for being honest.",
      QT,
      [K("Own up and try to put mistakes right."), P("Saving patiently can help you reach a goal.", "D-PLAUSIBLE-UNSUPPORTED"), P("A careful plan can protect valuable belongings.", "D-PLAUSIBLE-UNSUPPORTED"), P("Save up before buying something you want.", "D-OPPOSITE")]),
    it("lesson_mistake_fixed", 1, 1, 2,
      "Bel's first cookies burned. She nearly gave up. Then she checked the recipe and found her mistake. The oven had been too hot. Her next batch cooked well at the right heat.",
      QT,
      [K("Learning from mistakes helps you improve."), P("Sharing successful work can make other people happy.", "D-PLAUSIBLE-UNSUPPORTED"), P("Listening to others can help settle an argument.", "D-PLAUSIBLE-UNSUPPORTED"), P("Following friends is better than deciding alone.", "D-OPPOSITE")]),
    it("lesson_mistake_fixed", 1, 1, 3,
      "Kit broke the class crayon and hid it. Later, he told Miss May what had happened. She showed him how to tape it together. He wished he had told her sooner.",
      QT,
      [K("Telling the truth can help solve a problem."), P("Taking turns gives everyone a fair chance.", "D-PLAUSIBLE-UNSUPPORTED"), P("A patient friend can help you gain confidence.", "D-PLAUSIBLE-UNSUPPORTED"), P("New supplies are always better than old ones.", "D-OPPOSITE")]),
    it("lesson_mistake_fixed", 1, 1, 4,
      "Ravi would not sit beside the new boy. Then Ravi's bag broke and his books fell out. The new boy helped gather and carry them. Next day, Ravi chose to sit with him.",
      QT,
      [K("Get to know people before judging them."), P("Preparing carefully helps protect important belongings.", "D-PLAUSIBLE-UNSUPPORTED"), P("Sharing responsibility can make a large job easier.", "D-PLAUSIBLE-UNSUPPORTED"), P("Working alone is easier than accepting help.", "D-OPPOSITE")]),
    it("lesson_mistake_fixed", 1, 2, 5,
      "Lena raced Sam to finish their drawings first. She rushed and tore her paper. Sam worked slowly and made a neat picture. Lena started again, taking care this time.",
      QT,
      [K("Careful work matters more than finishing first."), P("A patient friend can help you feel welcome.", "D-PLAUSIBLE-UNSUPPORTED"), P("Sharing supplies lets more people join an activity.", "D-PLAUSIBLE-UNSUPPORTED"), P("A short task needs no planning at all.", "D-OPPOSITE")]),
    it("lesson_mistake_fixed", 1, 2, 6,
      "Min gave the fish extra food every day. Uneaten food made the water cloudy. An adult helped Min measure the right amount. With less waste, the tank stayed clean.",
      QT,
      [K("Too much of something useful can cause harm."), P("Taking turns makes a shared task more fair.", "D-PLAUSIBLE-UNSUPPORTED"), P("Trying new things can reveal a hidden talent.", "D-PLAUSIBLE-UNSUPPORTED"), P("Doing more always gives a better result.", "D-OPPOSITE")]),
    it("lesson_mistake_fixed", 1, 2, 7,
      "Posy sang softly in the quiet library. A boy kept losing his place while reading. Posy noticed him cover his ears. She stopped singing, and he began reading again.",
      QT,
      [K("Think about how your actions affect others."), P("Regular practice can improve a difficult skill.", "D-PLAUSIBLE-UNSUPPORTED"), P("Sharing favourite stories can build a friendship.", "D-PLAUSIBLE-UNSUPPORTED"), P("Finish your own task before noticing anyone else.", "D-OPPOSITE")]),
    it("lesson_mistake_fixed", 1, 2, 8,
      "Dara promised to water her neighbour's tree. She forgot, and its leaves began to curl. She made a daily reminder and followed it. Soon the tree had healthy new leaves.",
      QT,
      [K("Keeping a promise takes care and action."), P("Sharing ideas can make a plan better.", "D-PLAUSIBLE-UNSUPPORTED"), P("Patient practice can help you learn new skills.", "D-PLAUSIBLE-UNSUPPORTED"), P("Accept every task, even without time for it.", "D-OPPOSITE")]),

    // ========== LEVEL 1 · lesson_kindness_returned (8) ==========
    it("lesson_kindness_returned", 1, 1, 1,
      "Iris often helped her brother climb the bus steps. One morning, Iris slipped and dropped her books. Her brother hurried over with his friends. Together they picked up every book for her.",
      QT,
      [K("People who receive help may offer help too."), P("Preparing carefully helps prevent a difficult problem.", "D-PLAUSIBLE-UNSUPPORTED"), P("Learning from mistakes helps your work improve.", "D-PLAUSIBLE-UNSUPPORTED"), P("Practicing a skill makes difficult work easier.", "D-OPPOSITE")]),
    it("lesson_kindness_returned", 1, 1, 2,
      "The new girl always ate alone. Bo sat beside her and shared his grapes. Later, Bo broke his arm. She helped cut his lunch and stayed to chat.",
      QT,
      [K("Small acts of care can start a friendship."), P("Practicing daily can make a hard task easier.", "D-PLAUSIBLE-UNSUPPORTED"), P("Keeping a promise can build trust over time.", "D-PLAUSIBLE-UNSUPPORTED"), P("Saying sorry is the way to repair trust.", "D-OPPOSITE")]),
    it("lesson_kindness_returned", 1, 1, 3,
      "Grandpa Tan fixed his neighbours' umbrellas for free. A storm later damaged his roof. Those neighbours arrived with tools and warm food. They helped him until the roof was safe.",
      QT,
      [K("A caring neighbour can receive kindness in return."), P("Careful planning can reduce the damage from storms.", "D-PLAUSIBLE-UNSUPPORTED"), P("Learning a useful skill can take many tries.", "D-PLAUSIBLE-UNSUPPORTED"), P("Saving money always matters more than sharing time.", "D-OPPOSITE")]),
    it("lesson_kindness_returned", 1, 1, 4,
      "Nia dropped her last coin under a table. A boy crawled underneath and found it. Nia bought two small apples with the coin. She gave one to the boy to thank him.",
      QT,
      [K("Sharing can show thanks for a kind act."), P("Careful practice helps you improve a new skill.", "D-PLAUSIBLE-UNSUPPORTED"), P("Waiting patiently can help you notice new things.", "D-PLAUSIBLE-UNSUPPORTED"), P("Keeping a secret can protect a good friendship.", "D-OPPOSITE")]),
    it("lesson_kindness_returned", 1, 2, 5,
      "Wren was afraid to sing for the choir. Ana practiced quietly beside her every week. Wren began singing more clearly. At the concert, they stood together and both sang.",
      QT,
      [K("Patient support can help someone gain confidence."), P("A fair contest gives everyone a chance.", "D-PLAUSIBLE-UNSUPPORTED"), P("Listening carefully can help solve an argument.", "D-PLAUSIBLE-UNSUPPORTED"), P("Good friends always enjoy the same activities.", "D-OPPOSITE")]),
    it("lesson_kindness_returned", 1, 2, 6,
      "Mr Price could not move his wheelbarrow from mud. The children fetched an adult to help him. Together, they pushed it onto firm ground. He thanked them with apples from his orchard.",
      QT,
      [K("Offering help can bring people closer together."), P("Planning ahead can save time on difficult jobs.", "D-PLAUSIBLE-UNSUPPORTED"), P("Taking turns gives everyone a fair chance.", "D-PLAUSIBLE-UNSUPPORTED"), P("The best worker finishes every job without help.", "D-OPPOSITE")]),
    it("lesson_kindness_returned", 1, 2, 7,
      "Jude spotted broken glass on the slide. He warned younger children and called an adult. He missed his game while keeping them away. Later, the children gave him a thank-you note.",
      QT,
      [K("A helpful act can matter to other people."), P("Joining a group can help you make friends.", "D-PLAUSIBLE-UNSUPPORTED"), P("A new skill often takes many days of practice.", "D-PLAUSIBLE-UNSUPPORTED"), P("A prize matters more than the work behind it.", "D-OPPOSITE")]),
    it("lesson_kindness_returned", 1, 2, 8,
      "Eleven children argued over one jump rope. Fern suggested two jumps each, then changing places. Everyone agreed and took a turn. This time, nobody was left out of the game.",
      QT,
      [K("Sharing fairly helps people have fun together."), P("Repairing old equipment can save useful materials.", "D-PLAUSIBLE-UNSUPPORTED"), P("Keeping a promise can rebuild someone’s trust.", "D-PLAUSIBLE-UNSUPPORTED"), P("Having many children makes every game more fun.", "D-OPPOSITE")]),

    // ========== LEVEL 1 · lesson_effort_pays (8) ==========
    it("lesson_effort_pays", 1, 1, 1,
      "Pip's seed stayed hidden while other seeds sprouted. Pip checked the soil and watered when needed. At last, a small shoot appeared. With steady care, it grew into a tall sunflower.",
      QT,
      [K("Keep caring for a goal when progress is slow."), P("Sharing something special can make others happy.", "D-PLAUSIBLE-UNSUPPORTED"), P("Trying a different plan can solve a problem.", "D-PLAUSIBLE-UNSUPPORTED"), P("Quick results matter more than careful daily work.", "D-OPPOSITE")]),
    it("lesson_effort_pays", 1, 1, 2,
      "Ola could reach only one monkey bar. She tried again at each break. After weeks, she reached halfway. By summer, she could cross the whole row.",
      QT,
      [K("Small improvements can build toward a big goal."), P("A team can finish work faster than one person.", "D-PLAUSIBLE-UNSUPPORTED"), P("Choosing safe equipment helps prevent an accident.", "D-PLAUSIBLE-UNSUPPORTED"), P("A promise is worth keeping even when forgotten.", "D-OPPOSITE")]),
    it("lesson_effort_pays", 1, 1, 3,
      "Tam wanted to fold one hundred paper birds. He made a few after school each day. His pile slowly grew. At last, he counted one hundred finished birds.",
      QT,
      [K("Large tasks can be finished in small steps."), P("Helping someone may bring help back to you.", "D-PLAUSIBLE-UNSUPPORTED"), P("Asking for advice can prevent an early mistake.", "D-PLAUSIBLE-UNSUPPORTED"), P("Changing goals daily keeps a project on track.", "D-OPPOSITE")]),
    it("lesson_effort_pays", 1, 1, 4,
      "Emil wanted to become a better goalkeeper. He practiced catching every evening. Some balls slipped past, but he tried again. In the final game, he saved a difficult shot.",
      QT,
      [K("Regular practice can prepare you for a challenge."), P("Accepting a fair decision shows respect for others.", "D-PLAUSIBLE-UNSUPPORTED"), P("Good teamwork depends on sharing ideas with others.", "D-PLAUSIBLE-UNSUPPORTED"), P("Winning once means there is nothing left to learn.", "D-OPPOSITE")]),
    it("lesson_effort_pays", 1, 2, 5,
      "Ceri kept watching for snow. Grandma suggested getting ready while she waited. Ceri dried her gloves and checked her sled. When snow came, she was ready to play.",
      QT,
      [K("Waiting time can be used to get ready."), P("A kind act can brighten someone else’s day.", "D-PLAUSIBLE-UNSUPPORTED"), P("Asking for advice can help settle a disagreement.", "D-PLAUSIBLE-UNSUPPORTED"), P("Sharing a mistake makes a friendship stronger.", "D-OPPOSITE")]),
    it("lesson_effort_pays", 1, 2, 6,
      "One puzzle piece was missing. Ash looked under the sofa and behind the chair. He still did not find it. He checked the rug and found the piece there.",
      QT,
      [K("Keep looking when the first try does not work."), P("A group can finish work faster by sharing it.", "D-PLAUSIBLE-UNSUPPORTED"), P("A careful promise can help someone trust you.", "D-PLAUSIBLE-UNSUPPORTED"), P("The quickest search always gives the best result.", "D-OPPOSITE")]),
    it("lesson_effort_pays", 1, 2, 7,
      "Grandpa helped Suvi repair his old toy train. She checked its wheels and cleaned each part. Her first repair did not work. After another careful check, the train ran again.",
      QT,
      [K("Patient work can make an old thing useful."), P("Sharing your skills can help a neighbour succeed.", "D-PLAUSIBLE-UNSUPPORTED"), P("Finding a fair compromise can protect a friendship.", "D-PLAUSIBLE-UNSUPPORTED"), P("A good plan means you never need to change.", "D-OPPOSITE")]),
    it("lesson_effort_pays", 1, 2, 8,
      "A class built a robot to collect paper scraps. Its wheels kept getting stuck. The children tested and changed one part each time. After several changes, it rolled along collecting paper.",
      QT,
      [K("Testing and improving can make an idea work."), P("Good leaders make sure every voice is heard.", "D-PLAUSIBLE-UNSUPPORTED"), P("Accepting a fair result shows respect for others.", "D-PLAUSIBLE-UNSUPPORTED"), P("A new idea always works on its first try.", "D-OPPOSITE")]),

    // ========== LEVEL 2 · theme_among_rivals (8) ==========
    it("theme_among_rivals", 2, 1, 1,
      "Jo always chose the shiny new watering can. Its wide spout sent water onto the path instead of roots. The dented can's long spout watered each plant neatly. Jo began choosing that can for her daily watering.",
      "Which lesson is best supported by the story?",
      [K("Choose a tool for its usefulness, not just its appearance."), P("Family memories can give old objects a special meaning.", "D-PLAUSIBLE-UNSUPPORTED"), P("Sharing gardening tasks can help a family work together.", "D-PLAUSIBLE-UNSUPPORTED"), P("Replace familiar tools whenever something new becomes available.", "D-OPPOSITE")],
      { note: "rival family-memory lesson is worthy but Jo changes her choice only after comparing how the cans work" }),
    it("theme_among_rivals", 2, 1, 2,
      "Yusuf said his loud trumpet would be the concert's best part. Amal practiced a quiet harp tune each day. Yusuf played well, but Amal's gentle music held everyone still. He asked her how soft music could have such power.",
      "Which lesson is best supported by the story?",
      [K("Quiet work can make a strong impression."), P("Performing together can help people build lasting friendships.", "D-PLAUSIBLE-UNSUPPORTED"), P("A fair competition gives different skills an equal chance.", "D-PLAUSIBLE-UNSUPPORTED"), P("The loudest performer deserves the most attention.", "D-OPPOSITE")]),
    it("theme_among_rivals", 2, 1, 3,
      "Milo feared the dark, so Dad left a torch beside him. At first, Milo used it every night. Later, knowing it was there was enough. He slept without switching it on.",
      "Which lesson is best supported by the story?",
      [K("Knowing support is nearby can help courage grow."), P("A steady routine can help people remember important tasks.", "D-PLAUSIBLE-UNSUPPORTED"), P("Listening to different opinions can make group decisions fairer.", "D-PLAUSIBLE-UNSUPPORTED"), P("Everyone gains confidence at exactly the same speed.", "D-OPPOSITE")]),
    it("theme_among_rivals", 2, 1, 4,
      "Priya found tomorrow's answer sheet beside the copier. She could see its heading but did not read the answers. She returned it and earned her usual seven points. She felt proud that her score was truly her own.",
      "Which lesson is best supported by the story?",
      [K("An honest result can matter more than an unfair victory."), P("Regular study can help you improve a difficult skill.", "D-PLAUSIBLE-UNSUPPORTED"), P("Helping a classmate learn can strengthen a friendship.", "D-PLAUSIBLE-UNSUPPORTED"), P("A kind gift can bring an unexpected friendship.", "D-OPPOSITE")]),
    it("theme_among_rivals", 2, 2, 5,
      "Etta found a young bird with feathers beneath a hedge. She wanted to take it indoors. A rescue worker advised keeping pets away and watching quietly. Etta followed that advice, and the bird's parent returned with food.",
      "Which lesson is best supported by the story?",
      [K("Good help should fit what someone actually needs."), P("Patience helps people develop new skills over time.", "D-PLAUSIBLE-UNSUPPORTED"), P("Preparing carefully can prevent a problem from happening.", "D-PLAUSIBLE-UNSUPPORTED"), P("Every difficult problem should be solved without outside advice.", "D-OPPOSITE")],
      { note: "the rescue line directs a small, informed action; taking the bird indoors is explicitly rejected" }),
    it("theme_among_rivals", 2, 2, 6,
      "Nell was ready to enter her cake in the contest. Her friend Zeke dropped his cake and began to cry. Nell missed her turn while helping him make dessert cups. They won nothing, but laughed while sharing the cups with visitors.",
      "Which lesson is best supported by the story?",
      [K("Helping a friend can matter more than winning a prize."), P("Sharing ideas can help a team create a better design.", "D-PLAUSIBLE-UNSUPPORTED"), P("Learning from a mistake can improve your next attempt.", "D-PLAUSIBLE-UNSUPPORTED"), P("A mistake should make you abandon the whole activity.", "D-OPPOSITE")]),
    it("theme_among_rivals", 2, 2, 7,
      "Kofi's noisy stairwell game disturbed the neighbours. Mrs Adjei calmly explained that a baby nearby was sleeping. She helped him find an outdoor space for the game. Kofi moved there willingly and invited other children to join.",
      "Which lesson is best supported by the story?",
      [K("Calm explanation can help people change their actions."), P("Offering equal turns can make a shared game fairer.", "D-PLAUSIBLE-UNSUPPORTED"), P("Preparing before an activity can help you avoid mistakes.", "D-PLAUSIBLE-UNSUPPORTED"), P("The best solution is always to stop playing altogether.", "D-OPPOSITE")]),
    it("theme_among_rivals", 2, 2, 8,
      "Robin voted for goal nets, but the class chose a party. He still helped serve food and joined the games. Later, he explained again why the old nets needed replacing. Classmates listened because he had respected their earlier choice.",
      "Which lesson is best supported by the story?",
      [K("Respecting other decisions can help people respect your ideas."), P("Trying an unfamiliar activity can reveal a new interest.", "D-PLAUSIBLE-UNSUPPORTED"), P("Careful preparation can make a celebration run smoothly.", "D-PLAUSIBLE-UNSUPPORTED"), P("Speaking the loudest is the best way to change minds.", "D-OPPOSITE")]),

    // ========== LEVEL 2 · theme_vs_plot (8) ==========
    it("theme_vs_plot", 2, 1, 1,
      "Sana kept her telescope to herself. During comet week, she invited neighbours to look through it. Each person noticed something different and shared their excitement. Sana enjoyed the comet more while watching with them.",
      "Which message does the whole story support?",
      [K("Sharing an experience can make it more enjoyable."), P("Caring for valuable equipment helps it last longer.", "D-PLAUSIBLE-UNSUPPORTED"), P("Practicing a difficult skill can lead to improvement.", "D-TOPIC-ADJACENT"), P("Sana invited neighbours to look through her telescope during comet week.", "D-DETAIL-AS-MAIN")],
      { note: "theme vs three plot restatements — the defining discrimination" }),
    it("theme_vs_plot", 2, 1, 2,
      "Marisol got off the bus one stop too early. While waiting for rain to stop, she entered a small museum. Its ship models interested her so much that she stayed. She returned the next week to learn more.",
      "Which message does the whole story support?",
      [K("An unexpected change can lead to a good discovery."), P("Planning a journey carefully can save time and effort.", "D-PLAUSIBLE-UNSUPPORTED"), P("Sharing a discovery can help other people learn.", "D-TOPIC-ADJACENT"), P("Marisol entered a small museum after leaving her bus too early.", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 1, 3,
      "Tom broke Grandma's special teapot while playing carelessly. He explained what happened instead of muttering a quick apology. He offered his savings and helped repair the handle. Grandma thanked him for taking responsibility.",
      "Which message does the whole story support?",
      [K("A sincere apology includes trying to put things right."), P("Family objects can remind people of happy times.", "D-PLAUSIBLE-UNSUPPORTED"), P("Patient work can give old belongings a new use.", "D-TOPIC-ADJACENT"), P("Tom helped repair the handle of Grandma’s broken teapot.", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 1, 4,
      "The lighthouse keeper checked the lamp each night for forty years. Most sailors never met him. When he retired, they thanked him for guiding their ships safely. He learned how much his quiet work had mattered.",
      "Which message does the whole story support?",
      [K("Helpful service matters even without an audience."), P("Teaching others can keep useful knowledge alive across generations.", "D-PLAUSIBLE-UNSUPPORTED"), P("Familiar routines can make new tasks less frightening.", "D-TOPIC-ADJACENT"), P("The lighthouse keeper checked his lamp every night for forty years.", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 5,
      "Amaya built a small lantern with a strong frame. Other children made much larger lanterns from thin paper. At the parade, strong wind tore the thin lanterns. Amaya's plain little lantern stayed together throughout the walk.",
      "Which message does the whole story support?",
      [K("A strong design can matter more than an impressive size."), P("Taking part together can make a celebration enjoyable.", "D-PLAUSIBLE-UNSUPPORTED"), P("A patient teacher can help beginners become confident.", "D-TOPIC-ADJACENT"), P("Amaya’s small lantern stayed together while larger lanterns tore.", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 6,
      "Priw took all the simple jobs during the class project. Tup and Lin learned the harder jobs by practicing together. When Priw needed to join two boards, he could not start. He asked them to teach him and then practiced too.",
      "Which message does the whole story support?",
      [K("Avoiding challenges can mean missing chances to learn."), P("Sharing responsibilities can make a large task easier.", "D-PLAUSIBLE-UNSUPPORTED"), P("Accepting others’ ideas can help a group choose fairly.", "D-TOPIC-ADJACENT"), P("Tup and Lin showed Priw how to join two boards.", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 7,
      "Wet boots filled the school boot room each morning. Ede quietly placed them on the drying rack and turned them. Children were happier when their boots were dry after lunch. When asked, Ede said helping made her day better too.",
      "Which message does the whole story support?",
      [K("Small helpful actions can improve a shared place."), P("A steady routine can help someone learn a skill.", "D-PLAUSIBLE-UNSUPPORTED"), P("Taking care of belongings can help them last longer.", "D-TOPIC-ADJACENT"), P("Ede put the wet boots on the drying rack each morning.", "D-DETAIL-AS-MAIN")]),
    it("theme_vs_plot", 2, 2, 8,
      "The twins divided their attic room with a chalk line. They stopped sharing books and models, so arguments ended. But they also missed reading and making things together. They erased the line and agreed on rules for sharing.",
      "Which message does the whole story support?",
      [K("Solving a problem should leave room for friendship."), P("Having your own space can help you concentrate.", "D-PLAUSIBLE-UNSUPPORTED"), P("A fair schedule can help people finish a shared task.", "D-TOPIC-ADJACENT"), P("The twins erased the chalk line across their shared attic.", "D-DETAIL-AS-MAIN")]),

    // ========== LEVEL 2 · apply_theme (8) ==========
    it("apply_theme", 2, 1, 1,
      "Luca could not balance on one foot during his dance. He practiced a little after school each day. At first, he wobbled and stepped down. Weeks later, he could hold the pose throughout the music.",
      "Which new situation shows the SAME lesson?",
      [K("Ines repeats hard sums regularly until she can solve them."), P("Ines lends dance shoes to a friend after school one day.", "D-PLAUSIBLE-UNSUPPORTED"), P("Ines admits losing a school book and offers to replace it.", "D-PLAUSIBLE-UNSUPPORTED"), P("Ines invites a new child to sit with her each lunchtime.", "D-OPPOSITE")],
      { note: "transfer: same lesson, different domain — the sunflower option is the surface trap" }),
    it("apply_theme", 2, 1, 2,
      "Jo accidentally cracked a borrowed plant pot. He considered hiding it behind the shed. Instead, he told its owner and helped buy a replacement. The owner thanked him for explaining what had happened.",
      "Which new situation shows the SAME lesson?",
      [K("Cam admits scratching a bike and offers to help repair it."), P("Cam keeps practicing cycling until he can ride without wobbling.", "D-PLAUSIBLE-UNSUPPORTED"), P("Cam shares his bicycle with a visitor who has no bike.", "D-PLAUSIBLE-UNSUPPORTED"), P("Cam chooses a strong helmet instead of the most colourful one.", "D-OPPOSITE")]),
    it("apply_theme", 2, 1, 3,
      "A younger child struggled with a puzzle. Ray wanted to finish it for her. Instead, he showed her how to find the corner pieces. She did the rest herself and proudly showed the finished picture.",
      "Which new situation shows the SAME lesson?",
      [K("Lee gives a useful hint, then lets his brother solve it."), P("Lee solves the whole sum while his brother watches quietly.", "D-PLAUSIBLE-UNSUPPORTED"), P("Lee shares his prize with his brother after a contest.", "D-PLAUSIBLE-UNSUPPORTED"), P("Lee tells his brother the truth about a broken toy.", "D-OPPOSITE")]),
    it("apply_theme", 2, 1, 4,
      "Every morning, Evi checked the shared path for fallen branches. She moved small ones and reported large ones to an adult. Most walkers never saw her doing it. Her steady work helped them use the path safely.",
      "Which new situation shows the SAME lesson?",
      [K("A caretaker quietly clears icy steps before children reach school."), P("A singer practices a song to win a public talent contest.", "D-PLAUSIBLE-UNSUPPORTED"), P("A child returns money after noticing a shopkeeper made a mistake.", "D-PLAUSIBLE-UNSUPPORTED"), P("A gardener chooses strong tools because they will last longer.", "D-OPPOSITE")]),
    it("apply_theme", 2, 2, 5,
      "Rafi was close to winning the treasure hunt. His partner fell and hurt her ankle. He stopped, called an adult, and stayed beside her. Another team won, but Rafi was glad his friend was safe.",
      "Which new situation shows the SAME lesson?",
      [K("Vic misses his race to help a teammate who has fallen."), P("Vic practices running daily so he can beat his old time.", "D-PLAUSIBLE-UNSUPPORTED"), P("Vic admits that his foot crossed the line before the start.", "D-PLAUSIBLE-UNSUPPORTED"), P("Vic chooses sturdy shoes that will last through wet weather.", "D-OPPOSITE")]),
    it("apply_theme", 2, 2, 6,
      "Mara needed a bag for her walking trip. One had shiny beads but thin straps. The plain one had strong straps and a waterproof cover. Mara chose it, and her clothes stayed dry throughout the rain.",
      "Which new situation shows the SAME lesson?",
      [K("Jo chooses sturdy shoes that last through many wet walks."), P("Jo chooses shoes in the colour her closest friend likes.", "D-PLAUSIBLE-UNSUPPORTED"), P("Jo chooses shiny shoes to match a special party dress.", "D-PLAUSIBLE-UNSUPPORTED"), P("Jo chooses shoes because the shop advertises them most often.", "D-OPPOSITE")], { note: "Transfer useful design over appearance to a new object; no prior item is needed." }),
    it("apply_theme", 2, 2, 7,
      "Suri noticed that the scorer had given her an extra point. Nobody else had seen the mistake. She told the scorer, even though the change cost her victory. She was glad the result was fair.",
      "Which new situation shows the SAME lesson?",
      [K("Dev admits a rule break that could have helped him win."), P("Dev trains after school to improve his throwing and catching.", "D-PLAUSIBLE-UNSUPPORTED"), P("Dev shares a spare bat with someone from the other team.", "D-PLAUSIBLE-UNSUPPORTED"), P("Dev helps a younger player learn to hold the bat.", "D-OPPOSITE")]),
    it("apply_theme", 2, 2, 8,
      "Mia stopped her brother entering her den after an argument. Her things stayed tidy, but she missed playing with him. She invited him back and explained which things needed care. They found a way to enjoy the den together again.",
      "Which new situation shows the SAME lesson?",
      [K("Ali welcomes her sister to a workbench with agreed sharing rules."), P("Ali tidies the workbench alone before starting her next picture.", "D-PLAUSIBLE-UNSUPPORTED"), P("Ali buys stronger scissors because they can cut through thick card.", "D-PLAUSIBLE-UNSUPPORTED"), P("Ali thanks a friend for helping finish a difficult craft model.", "D-OPPOSITE")]),

    // ========== RETENTION RESERVE (8 + 8) ==========
    it("lesson_mistake_fixed", 1, 1, 9,
      "Zia copied answers so she could finish quickly. In class, she could not explain them. That night, she worked through the questions herself. Next day, she could explain how each answer worked.",
      QT,
      [K("Doing your own work helps you learn."), P("A kind friend can encourage you to try.", "D-PLAUSIBLE-UNSUPPORTED"), P("Working together helps share a heavy task.", "D-PLAUSIBLE-UNSUPPORTED"), P("Taking turns is the best way to share equipment.", "D-OPPOSITE")], { retention: true }),
    it("lesson_kindness_returned", 1, 1, 10,
      "Ffion helped clear frost from her neighbour's car. Later, her family forgot to bring their bins in. The neighbour wheeled them back up the drive. Ffion smiled when she saw him helping.",
      QT,
      [K("Neighbours can return each other’s kindness."), P("Careful planning can prevent a repeated problem.", "D-PLAUSIBLE-UNSUPPORTED"), P("Daily practice can make a difficult skill easier.", "D-PLAUSIBLE-UNSUPPORTED"), P("Making a mistake helps you learn a skill.", "D-OPPOSITE")], { retention: true }),
    it("lesson_effort_pays", 1, 2, 9,
      "Rosa practiced swimming with her teacher all summer. First she learned to float, then to kick. Next, she practiced moving her arms. By summer's end, she could swim across the pool.",
      QT,
      [K("Learning small steps can build a new skill."), P("Sharing a goal can bring friends closer together.", "D-PLAUSIBLE-UNSUPPORTED"), P("Helping someone can bring help back to you.", "D-PLAUSIBLE-UNSUPPORTED"), P("The first attempt shows all you can ever do.", "D-OPPOSITE")], { retention: true }),
    it("lesson_mistake_fixed", 1, 2, 10,
      "Ben teased Ollie about his taped glasses. Ollie looked hurt and walked away. Ben said sorry and stopped the teasing. He treated Ollie kindly until they became friends again.",
      QT,
      [K("Kind actions can help put a wrong right."), P("Humour can help people enjoy spending time together.", "D-PLAUSIBLE-UNSUPPORTED"), P("Listening to advice can help a project improve.", "D-PLAUSIBLE-UNSUPPORTED"), P("Working quickly leaves more time for other activities.", "D-OPPOSITE")], { retention: true }),
    it("lesson_kindness_returned", 1, 2, 11,
      "Aron helped little Yani through a crowded lunch line. Later, Aron needed crutches after hurting his leg. Yani walked beside him in the crowded hall. He helped make space so Aron could pass safely.",
      QT,
      [K("Help given can be remembered and returned."), P("Patient practice can help you overcome a difficulty.", "D-PLAUSIBLE-UNSUPPORTED"), P("Sharing a goal can make a group stronger.", "D-PLAUSIBLE-UNSUPPORTED"), P("Keeping a secret is the best way to help.", "D-OPPOSITE")], { retention: true }),
    it("lesson_effort_pays", 1, 1, 11,
      "Dot's recorder made squeaky notes at first. She practiced for ten minutes every day. Her teacher helped her fix each mistake. At the concert, she played a clear, steady tune.",
      QT,
      [K("A little practice each day can build skill."), P("Choosing useful equipment helps you complete a task.", "D-PLAUSIBLE-UNSUPPORTED"), P("Listening to others helps a group make decisions.", "D-PLAUSIBLE-UNSUPPORTED"), P("A kind act can start a new friendship.", "D-OPPOSITE")], { retention: true }),
    it("lesson_mistake_fixed", 1, 1, 11,
      "Wolf knocked the class globe off its stand. He hid the loose part all morning. Finally, he told his teacher. Together they fixed it, and Wolf stopped worrying.",
      QT,
      [K("Asking honestly for help can ease a worry."), P("Sharing a special object can bring people together.", "D-PLAUSIBLE-UNSUPPORTED"), P("Checking your work carefully can prevent mistakes.", "D-PLAUSIBLE-UNSUPPORTED"), P("A difficult task should be finished without any help.", "D-OPPOSITE")], { retention: true }),
    it("lesson_kindness_returned", 1, 1, 12,
      "Mrs Vo had helped her neighbours for years. One day, flood water entered her shop. The neighbours came to carry stock and mop floors. By evening, their work had made the shop dry.",
      QT,
      [K("A caring community can support one another."), P("Planning carefully can protect things from damage.", "D-PLAUSIBLE-UNSUPPORTED"), P("A steady routine helps you learn a skill.", "D-PLAUSIBLE-UNSUPPORTED"), P("The newest building is always the safest building.", "D-OPPOSITE")], { retention: true }),
    it("theme_among_rivals", 2, 1, 9,
      "Ines won every chess game and often boasted about it. Soon, few children wanted to play. She began coaching beginners and praising their progress. The club grew, and she enjoyed seeing her pupils improve.",
      "Which lesson is best supported by the story?",
      [K("Helping others improve can be more rewarding than winning alone."), P("Patient practice can help people develop a difficult skill.", "D-PLAUSIBLE-UNSUPPORTED"), P("Fair rules give new competitors a chance to take part.", "D-PLAUSIBLE-UNSUPPORTED"), P("Making a task easier means nobody will learn from it.", "D-OPPOSITE")], { retention: true }),
    it("theme_among_rivals", 2, 2, 10,
      "Papa grouped his tools by job instead of size. Each basket looked untidy but held everything for one task. When a bike chain broke, he found all he needed quickly. His neat neighbour copied the system after seeing it work.",
      "Which lesson is best supported by the story?",
      [K("A useful system need not look like other systems."), P("Taking care of tools can help them last longer.", "D-PLAUSIBLE-UNSUPPORTED"), P("Sharing equipment gives more people a chance to learn.", "D-PLAUSIBLE-UNSUPPORTED"), P("Following old habits is better than considering a new idea.", "D-OPPOSITE")], { retention: true }),
    it("theme_vs_plot", 2, 1, 9,
      "Fen and Alba shared a horse costume in the school play. At first, they turned in different directions and kept falling. They practiced listening and moving together for weeks. By the performance, they worked smoothly and had become close friends.",
      "Which message does the whole story support?",
      [K("Working together can help a friendship grow."), P("Fair choices give every performer an equal chance.", "D-PLAUSIBLE-UNSUPPORTED"), P("Good advice can help someone face a fear.", "D-TOPIC-ADJACENT"), P("Fen and Alba practiced moving together inside the horse costume.", "D-DETAIL-AS-MAIN")], { retention: true }),
    it("theme_vs_plot", 2, 2, 10,
      "Bess left Callum a box of seeds and a gardening notebook. He had hoped for jewels and felt disappointed. The book described trees she had planted to celebrate other people. He planted a tree for a new baby and understood her joy.",
      "Which message does the whole story support?",
      [K("The chance to give can be a valuable gift."), P("Learning from older relatives can preserve useful knowledge.", "D-PLAUSIBLE-UNSUPPORTED"), P("Patient gardening can reward people after a long wait.", "D-TOPIC-ADJACENT"), P("Callum found seeds and a notebook inside Bess’s box.", "D-DETAIL-AS-MAIN")], { retention: true }),
    it("apply_theme", 2, 1, 9,
      "Tara lost a library game's smallest piece. She hid the box, worrying someone would find out. Finally, she told the librarian, who helped replace the piece. Tara could enjoy using the library again without keeping a secret.",
      "Which new situation shows the SAME lesson?",
      [K("Tess tells the librarian about juice spilled on a borrowed book."), P("Tess practices reading a hard book until the words feel easy.", "D-PLAUSIBLE-UNSUPPORTED"), P("Tess lends a favourite book to a new child in class.", "D-PLAUSIBLE-UNSUPPORTED"), P("Tess sorts all the class books quietly before the others arrive.", "D-OPPOSITE")], { retention: true }),
    it("apply_theme", 2, 2, 10,
      "Ojas noticed the shared pencils were always blunt at lesson time. Each morning, he sharpened a few before sitting down. Other children could start their work without a long wait. They did not know who had helped, but Ojas was pleased.",
      "Which new situation shows the SAME lesson?",
      [K("Lea sets out supplies so everyone can begin their painting easily."), P("Lea practices mixing colours until she can make a perfect green.", "D-PLAUSIBLE-UNSUPPORTED"), P("Lea chooses strong brushes instead of ones with shiny handles.", "D-PLAUSIBLE-UNSUPPORTED"), P("Lea admits spilling paint and helps wash it from the floor.", "D-OPPOSITE")], { retention: true }),
    it("theme_among_rivals", 2, 1, 11,
      "Vin usually talked throughout group work. One day, he listened while the others shared their ideas. He heard a useful suggestion from quiet Lom. He also noticed a child needed help, and offered it.",
      "Which lesson is best supported by the story?",
      [K("Listening can reveal ideas and needs you might otherwise miss."), P("A difficult challenge can reveal a skill you overlooked.", "D-PLAUSIBLE-UNSUPPORTED"), P("Sharing responsibility can make a large project easier.", "D-PLAUSIBLE-UNSUPPORTED"), P("Helping someone means finishing all of their work for them.", "D-OPPOSITE")], { retention: true }),
    it("apply_theme", 2, 2, 11,
      "Bea needed a bridge for a model train. She chose thick card and tested how much it could hold. Another bridge looked grand but bent beneath the train. Bea's plain bridge carried it safely across every time.",
      "Which new situation shows the SAME lesson?",
      [K("Jem builds a plain shelter that stays strong in heavy rain."), P("Jem decorates a shelter with the brightest ribbons in the class.", "D-PLAUSIBLE-UNSUPPORTED"), P("Jem shares his building tools with a child who forgot them.", "D-PLAUSIBLE-UNSUPPORTED"), P("Jem admits breaking a borrowed tool and offers to replace it.", "D-OPPOSITE")], { retention: true }),
    // Fresh retry stock: four additional questions in each phase.
    {
      "u": "lesson_mistake_fixed",
      "lvl": 1,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "lesson_mistake_fixed",
      "passage": "Alf guessed how much salt the soup needed. It tasted far too salty. Next time, he measured with the recipe’s small spoon. Everyone enjoyed that batch.",
      "prompt": "What lesson does this story teach?",
      "choices": [K("Careful checking can prevent repeating a mistake."), P("Sharing a meal can help new friends meet.", "D-PLAUSIBLE-UNSUPPORTED"), P("Patient practice helps you remember a difficult skill.", "D-PLAUSIBLE-UNSUPPORTED"), P("A difficult skill should be practiced without help.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "lesson_kindness_returned",
      "lvl": 1,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "lesson_kindness_returned",
      "passage": "Luz helped her neighbour carry heavy shopping bags. The next week, Luz hurt her wrist. Her neighbour brought her schoolbooks home each afternoon. They both smiled at having someone to help.",
      "prompt": "What lesson does this story teach?",
      "choices": [K("People can support each other at different times."), P("Careful preparation can make a hard journey easier.", "D-PLAUSIBLE-UNSUPPORTED"), P("Keeping a promise can build trust over time.", "D-PLAUSIBLE-UNSUPPORTED"), P("Practice matters more than choosing the right tools.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "lesson_effort_pays",
      "lvl": 1,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "lesson_effort_pays",
      "passage": "Han wanted to read a whole chapter alone. At first, he managed only one page. He practiced a little each evening. Soon, he finished the chapter without stopping.",
      "prompt": "What lesson does this story teach?",
      "choices": [K("Steady practice can help you reach a goal."), P("Sharing a story can help people feel connected.", "D-PLAUSIBLE-UNSUPPORTED"), P("Listening to friends can reveal an unexpected idea.", "D-PLAUSIBLE-UNSUPPORTED"), P("Asking questions means you have not tried enough.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "lesson_mistake_fixed",
      "lvl": 1,
      "ph": 1,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "lesson_mistake_fixed",
      "passage": "Sali took the wrong bag home from school. She found a name tag different from hers. She called the owner and arranged a swap. Next day, she checked her bag before leaving.",
      "prompt": "What lesson does this story teach?",
      "choices": [K("Put mistakes right and learn how to avoid them."), P("Keep trying until you master a difficult task.", "D-PLAUSIBLE-UNSUPPORTED"), P("A kind gift can help a new friendship grow.", "D-PLAUSIBLE-UNSUPPORTED"), P("Getting home quickly matters more than checking belongings.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "lesson_kindness_returned",
      "lvl": 1,
      "ph": 2,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "lesson_kindness_returned",
      "passage": "Finn helped a new player learn the team’s game. Later, Finn forgot his trainers for practice. The player lent him a spare pair. Finn thanked him, and they practiced together.",
      "prompt": "What lesson does this story teach?",
      "choices": [K("Kind support can grow between teammates."), P("Fair rules give every player a chance.", "D-PLAUSIBLE-UNSUPPORTED"), P("Careful work can repair a damaged object.", "D-PLAUSIBLE-UNSUPPORTED"), P("Following a routine means nothing can go wrong.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "lesson_effort_pays",
      "lvl": 1,
      "ph": 2,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "lesson_effort_pays",
      "passage": "Ava’s first woven mat had loose, uneven strips. She looked closely at a finished example. She adjusted her weave and tried several small mats. Her next one lay flat and held together.",
      "prompt": "What lesson does this story teach?",
      "choices": [K("Learning from each try helps work improve."), P("Sharing materials can help everyone join in.", "D-PLAUSIBLE-UNSUPPORTED"), P("Listening to others helps a group decide fairly.", "D-PLAUSIBLE-UNSUPPORTED"), P("A good friend always chooses the same activity.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "lesson_effort_pays",
      "lvl": 1,
      "ph": 2,
      "v": 22,
      "fmt": "COMPREHENSION",
      "cell": "lesson_effort_pays",
      "passage": "Mo wanted to remember a long message for assembly. He learned one short part each day. Then he practiced joining the parts together. At assembly, he remembered the whole message.",
      "prompt": "What lesson does this story teach?",
      "choices": [K("Small steps can make a large task manageable."), P("A fair group gives everyone time to speak.", "D-PLAUSIBLE-UNSUPPORTED"), P("Helping a friend can matter more than winning.", "D-PLAUSIBLE-UNSUPPORTED"), P("A short wait can make a good surprise better.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "lesson_mistake_fixed",
      "lvl": 1,
      "ph": 2,
      "v": 22,
      "fmt": "COMPREHENSION",
      "cell": "lesson_mistake_fixed",
      "passage": "Kit interrupted whenever someone shared an idea. Soon, his group stopped trying to speak. He began waiting and asking what others thought. Their next plan used ideas from every member.",
      "prompt": "What lesson does this story teach?",
      "choices": [K("Listening gives everyone a chance to contribute."), P("Preparing carefully can make speaking feel easier.", "D-PLAUSIBLE-UNSUPPORTED"), P("Practicing regularly can improve a new skill.", "D-PLAUSIBLE-UNSUPPORTED"), P("Finishing quietly means never sharing your good ideas.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "theme_among_rivals",
      "lvl": 2,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "theme_among_rivals",
      "passage": "Rae thought the youngest team member could not help with the map. The others became lost among paths that looked alike. The child noticed marks they had missed and found the right turn. Rae asked for her ideas throughout the rest of the walk.",
      "prompt": "Which lesson is best supported by the story?",
      "choices": [K("Useful ideas can come from people you underestimate."), P("A careful plan can reduce mistakes during a journey.", "D-PLAUSIBLE-UNSUPPORTED"), P("Working toward a shared goal can help strangers become friends.", "D-PLAUSIBLE-UNSUPPORTED"), P("Growing older automatically makes someone better at every task.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "theme_vs_plot",
      "lvl": 2,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "theme_vs_plot",
      "passage": "Mika wanted to build a bench alone and refused advice. Her first frame wobbled when anyone sat on it. She asked a neighbour to show her stronger joints. Together they made a bench she was proud to share.",
      "prompt": "Which message does the whole story support?",
      "choices": [K("Accepting help can make your own work stronger."), P("Repairing old things can reduce the waste people create.", "D-PLAUSIBLE-UNSUPPORTED"), P("Careful planning can help people use their time wisely.", "D-TOPIC-ADJACENT"), P("Mika’s neighbour helped her make stronger joints for a bench.", "D-DETAIL-AS-MAIN")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "apply_theme",
      "lvl": 2,
      "ph": 1,
      "v": 20,
      "fmt": "COMPREHENSION",
      "cell": "apply_theme",
      "passage": "Hana saved the best ideas for herself during a group challenge. Her own model looked good, but the shared structure collapsed. In the next round, she explained her method to everyone. All their models fitted together, and the whole group succeeded.",
      "prompt": "Which new situation shows the same lesson?",
      "choices": [
        {
          "t": "A player shares a useful tactic so the whole team improves.",
          "r": "KEY",
          "k": true
        },
        {
          "t": "A player trains alone to beat her own fastest running time.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "A player admits stepping over a line during an important game.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "A player chooses stronger shoes instead of more colourful ones.",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "theme_among_rivals",
      "lvl": 2,
      "ph": 1,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "theme_among_rivals",
      "passage": "A weather forecast warned of heavy rain during the picnic. The class wanted to keep their original outdoor plan. Then they moved the games into the hall and enjoyed them there. They were glad they had changed plans before the storm arrived.",
      "prompt": "Which lesson is best supported by the story?",
      "choices": [K("Changing a plan sensibly can still lead to success."), P("Listening to every opinion can make a group decision fair.", "D-PLAUSIBLE-UNSUPPORTED"), P("Taking turns gives everyone a chance to enjoy an activity.", "D-PLAUSIBLE-UNSUPPORTED"), P("Letting one person decide is the fairest way to work.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "theme_vs_plot",
      "lvl": 2,
      "ph": 2,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "theme_vs_plot",
      "passage": "Ben could finish the mural faster by painting over his partner’s work. Instead, he waited until she returned and asked about her design. They found a way to join both patterns. The finished wall showed ideas from both artists.",
      "prompt": "Which message does the whole story support?",
      "choices": [K("Respecting another person’s work can improve a shared result."), P("Planning carefully can help a group finish on time.", "D-PLAUSIBLE-UNSUPPORTED"), P("Regular practice can help people express their ideas clearly.", "D-TOPIC-ADJACENT"), P("Ben waited for his partner and asked about her mural design.", "D-DETAIL-AS-MAIN")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "apply_theme",
      "lvl": 2,
      "ph": 2,
      "v": 21,
      "fmt": "COMPREHENSION",
      "cell": "apply_theme",
      "passage": "The class built a model town for the science fair. Their fountain looked impressive but leaked water across the roads. They repaired the seal before adding any more decorations. At the fair, the plain repaired fountain worked all afternoon.",
      "prompt": "Which new situation shows the same lesson?",
      "choices": [
        {
          "t": "Eli chooses a plain torch that keeps working in rain.",
          "r": "KEY",
          "k": true
        },
        {
          "t": "Eli offers a spare torch to a friend without one.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "Eli practices using a map until he can find the route.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "Eli admits losing a torch and offers to replace it.",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "theme_among_rivals",
      "lvl": 2,
      "ph": 2,
      "v": 22,
      "fmt": "COMPREHENSION",
      "cell": "theme_among_rivals",
      "passage": "The winning choir heard that another group’s bus had broken down. They could have started without those singers. Instead, they agreed to wait and shorten their own rehearsal. The late group arrived in time, and everyone performed.",
      "prompt": "Which lesson is best supported by the story?",
      "choices": [K("Fairness can involve giving up a small advantage."), P("Practicing a performance together can make a group stronger.", "D-PLAUSIBLE-UNSUPPORTED"), P("Preparing a backup plan can help when transport goes wrong.", "D-PLAUSIBLE-UNSUPPORTED"), P("Winning matters most when other people have fewer chances.", "D-OPPOSITE")],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    },
    {
      "u": "apply_theme",
      "lvl": 2,
      "ph": 2,
      "v": 22,
      "fmt": "COMPREHENSION",
      "cell": "apply_theme",
      "passage": "Asha planted flowers beside the shared path every year. She rarely saw who enjoyed them while she was at work. One day, neighbours left notes thanking her for the cheerful view. She realised her quiet care had brightened many daily walks.",
      "prompt": "Which new situation shows the same lesson?",
      "choices": [
        {
          "t": "A pupil quietly prepares shared art tools that everyone uses later.",
          "r": "KEY",
          "k": true
        },
        {
          "t": "A pupil practices drawing so her contest entry can win a prize.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "A pupil admits forgetting a task and asks for another chance.",
          "r": "D-PLAUSIBLE-UNSUPPORTED"
        },
        {
          "t": "A pupil selects stronger paper for a model that must last.",
          "r": "D-OPPOSITE"
        }
      ],
      "media": "text",
      "note": "Fresh authored retry item: distinct situation and evidence."
    }
]
};
