// Captions from direct illustration review; stable source page numbers survive manuscript reordering.
export const GUIDED_READING_ILLUSTRATION_DESCRIPTIONS = Object.freeze({
  "level-c-nonfiction-08-butterflies::9": "A female monarch rests on a milkweed leaf with her abdomen touching a small egg attached directly to the leaf.",
  "bob-and-nan-07-birthday::7": "Bob swings his new bat on the garden lawn while Nan moves to get the ball.",
  "ja-b-08::10": "James holds Bella’s lead while Anna props up the bent flowers beside Chips.",
  "ja-b-10::14": "Anna presses a patch onto the green tent while Chips sniffs beside her. Dad holds Chips’s lead; James watches and Mom stands at the back door.",
  "ab-c-03::8": "Rain falls outside the cottage window. Aiden slumps beside a board game while Betty draws a route showing the beach, harbor and lighthouse.",
  "ab-c-10::13": "At home, Aiden draws barrels in his own spiral notebook beside a separate open reference book showing a castle storeroom.",
  "meadow-pals-04-bouncy-wont-stop::3": "Bouncy, wearing her red neck ribbon, hops into Grumpy’s full pail and tips water across the path.",
  "meadow-pals-04-bouncy-wont-stop::5": "Bouncy, wearing her red neck ribbon, tips Clucky’s basket as four eggs roll onto the path.",
  "meadow-pals-04-bouncy-wont-stop::6": "Bouncy returns the last egg to Clucky’s basket beside Grumpy and his refilled pail of water. Her red neck ribbon and two spring legs are visible.",
  "meadow-pals-13-splashy-finds-a-puddle::8": "Splashy wipes Grumpy’s wet hat while Grumpy holds a towel around himself beside the puddle.",
  "dino-pals-03-dozy-wont-wake-up::5": "Bossy points to an empty place and leaf bowl beside the picnic food. Chompy, Sunny and Bouncy wait with her; Dozy is absent.",
  "dino-pals-04-grumpy-needs-help::5": "Grumpy pulls the vine tied around the heavy rock, but his club tail remains trapped beneath its edge. Bouncy watches beside the rock.",
  "dino-pals-04-grumpy-needs-help::6": "Grumpy studies the rock with the pulling vine loose on the ground. His club tail is still caught beneath the rock’s lower edge.",
  "dino-pals-09-honkys-inside-voice::8": "Inside the cave, Honky lowers a leaf bowl of rescued fruit for Bossy, Chompy, Grumpy and Dozy. Rain falls beyond the entrance.",
  "dino-pals-10-cheekys-prank-goes-wrong::2": "Cheeky ties a leaf hat to a vine hanging from a low branch above the path. Wiggly approaches beneath it.",
  "dino-pals-12-fancys-bad-day::9": "Fancy pours water from a leaf bowl onto the folded leaf fan on a flat rock beside the warm cave pool. Wiggly stands beside her.",
  "dino-pals-18-dozys-wonderful-dream::10": "In the golden dream landscape, Dozy and Sunny curl up on a thin cloud spread over a broad, solid rocky peak.",
  "moonwood-tales-c-04::1": "Glimmer stands in a bare practice patch with two piles of dry leaves moved away. Fern’s closed seed pouch rests nearby outside the practice space.",
  "moonwood-tales-c-04::11": "A gray fox sneezes as Glimmer blows a gentle breath across its nose, dropping Fern’s closed seed pouch.",
  "moonwood-tales-c-05::6": "Tiny Wren slides toward the spine of an open spell book as its page curls beneath her feet.",
  "moonwood-tales-c-08::8": "Burrow presses one digging claw into the small notch beside the door while Luna watches.",
  "moonwood-tales-c-09::13": "Wren tips the leaf wash into the stream while Spark carries a bowl to rinse the blue flowers. Silver fish are visible in the water.",
  "moonwood-tales-c-15::9": "Luna points to an old carving of a rabbit beside an acorn at its doorway while Burrow leans closer.",
  "moonwood-tales-c-15::10": "The next carving shows rain over the rabbit’s tunnel and a green shoot growing where the acorn was covered with earth.",
  "moonwood-tales-c-15::11": "Burrow and Luna study a carving of a great oak growing around the rabbit’s small round doorway.",
  "moonwood-tales-c-17::7": "Bare-root plants walk into Hollow Oak, with the smallest passing Burrow’s tunnel as he moves aside.",
  "moonwood-tales-c-17::10": "Wren sprinkles stream water on the bare-root plants as they walk back toward the empty holes in the garden.",
  "moonwood-tales-c-17::11": "Fern presses soil around the smallest plant as its roots settle into its garden patch.",
  "moonwood-tales-c-34::10": "A solid braided root-fiber hook fixed to the low wooden rail supports the glowing lantern while Spark counts beside it.",
  "moonwood-tales-c-35::9": "Stone and Pip use separate striking tools to tap the hanging root chimes in order, starting with the lowest chime.",
  "moonwood-tales-c-35::10": "Luna opens Hollow Oak’s doors while the suspended chimes ring and separate sound ripples spread into the moonlit forest.",
  "willow-street-the-squeaky-wheel::2": "Samir, in his cobalt hoodie and charcoal trousers, kneels beside the stopped cart to look for stones. Zoe holds the handle steady; Samir keeps his hands away from the axle.",
  "gr-a-26::3": "A child feeds an orange fish in a planted rectangular aquarium with a visible filter.",
  "first-facts-a-05-flowers-and-trees::8": "A child waters a row of flowers in a sunny garden, with leafy trees growing beyond the stone wall.",
  "meadow-pals-08-tiny-is-very-small::3": "Grumpy stretches a foreleg toward the key inside a hollow log. Tiny watches beside the log on the farm lawn.",
  "gr-a-26::1": "A golden dog leaps beside a ball, a food bowl and a round dog bed in the garden.",
  "gr-a-26::4": "A colorful pet bird flies inside a spacious aviary with perches and hanging toys.",
  "gr-a-26::5": "A white rabbit hops beside a rack of hay in a grassy enclosure.",
  "gr-a-27::1": "The glowing Sun and a much smaller Earth appear against dark space.",
  "gr-a-27::2": "Sunlight fills a landscape of trees, grass and a winding path toward a village.",
  "gr-a-27::3": "Sunlight falls across a grassy bank and the clear water of a stream.",
  "gr-a-27::4": "Sunlight reaches a young plant’s green leaves, with its roots visible beneath the soil.",
  "gr-a-27::5": "A child looks down while watering seedlings in a sunny garden bed.",
  "gr-a-27::6": "A child pets a rabbit beside sunlit plants, flowers and a stream, with a bird and butterfly nearby.",
  "gr-a-28::6": "A red apple hangs above a garden with green grass, colorful flowers, a white cloud and the yellow-looking Sun.",
  "gr-a-29::6": "The child washes soapy hands under running water at the sink.",
  "gr-b-31::1": "A tree covered in new buds and blossoms stands beside a stream under cloudy spring skies.",
  "gr-b-31::2": "A tree full of green leaves stands beside the stream in summer sunshine.",
  "gr-b-31::6": "Four views of the same tree show the seasons, above a spring bud and blossom, green leaf, fall leaf and snowball.",
  "gr-b-32::2": "A single peeled yellow banana rests on a wooden tabletop.",
  "gr-b-32::6": "A branch shows an open blossom, a fading blossom and a developing round fruit.",
  "gr-b-33::6": "An adult wearing safety glasses uses a screwdriver on a clamped board while a child watches from a distance.",
  "gr-b-34::1": "A simple diagram shows the Sun lighting one half of Earth, with a small land marker on the bright side.",
  "gr-b-34::3": "A curved arrow shows Earth turning while sunlight still reaches the same side of the globe.",
  "gr-b-34::4": "The land marker has turned into Earth’s dark half, away from the Sun.",
  "gr-b-34::6": "The rotation arrow and returning land marker show Earth continuing from darkness into daylight.",
  "gr-b-35::4": "A teacher and four children sit around an open book and colored blocks at a classroom table.",
  "gr-b-35::5": "Two police officers guide a car around a fallen branch, with traffic cones marking the obstruction.",
  "gr-c-37::3": "A child watches a shallow tray of water on a tabletop beside a sunny window.",
  "gr-c-37::6": "A pitcher of liquid water and a bowl of ice sit in a kitchen, with a kettle farther back.",
  "gr-c-38::4": "The child tastes a slice of apple at the kitchen table.",
  "gr-c-38::5": "The child feels a pine cone beside a smooth stone and folded cloth in a patch of sunlight.",
  "gr-d-42::4": "Earth viewed from space shows a broad blue ocean covering most of the visible globe.",
  "gr-d-45::5": "An astronaut looks out through a spacecraft window above Earth, with solar panels extending from the craft.",
  "gr-d-45::6": "Earth and its nearby Moon appear below more distant planets and a spiral galaxy against a dark starry sky.",
  "gr-e-47::2": "Water pours from a watering can onto a plant, with its roots visible beneath the soil.",
  "gr-e-47::6": "Side-by-side diagrams compare a small seedling with a larger fruiting plant and show a tadpole developing into a frog.",
  "gr-e-48::1": "Paper clips cluster around both ends of a red-and-blue bar magnet.",
  "gr-e-48::2": "A horseshoe magnet attracts paper clips and metal washers while wooden sticks and colored buttons remain separate.",
  "gr-e-50::3": "The child smells a pink flower beside a basket of bread and a bowl of oranges.",
  "first-facts-level-a-15-baby-animals::1": "A fluffy yellow chick sits in a straw nest resting on the farmyard ground, with a red barn and fence behind it.",
  "meadow-pals-04-bouncy-wont-stop::7": "Bouncy hops along the clear path beside Grumpy and Clucky. Grumpy’s pail is full of blue water, and four eggs rest safely in Clucky’s basket.",
  "willow-street-the-squeaky-wheel::5": "The gardener kneels beside the green cart and touches the oil can's spout to the metal axle hub at the center of the near front wheel. Samir and Zoe watch.",
  "willow-street-make-fruit-and-yoghurt-cups::6": "Zoe spoons yogurt onto the fruit in the fourth clear cup. Each of the four cups has a white yogurt base, banana and berries in the middle, and a second white yogurt layer on top."
});
