/** Copy for the teacher-led benchmark administration workspace. */
export const BENCHMARK_RUNNER_COPY = Object.freeze({
  workspace: "Teacher assessment workspace",
  legacyTitle: "Earlier assessment form",
  legacyHelp: "This saved assessment keeps its original questions so earlier answers stay attached to the right items. Start a new assessment to use the expanded current forms.",
  contentIssueTitle: "This item needs a content correction",
  savedResponse: "Review the earlier saved response",
  markUnscorable: "Record as not scorable",
  markedUnscorable: "Recorded as not scorable. This item will not count as a wrong answer.",
  contentReview: "Needs item review",
  studentCopy: "Student display",
  openStudent: "Open student display",
  closeStudent: "Close student display",
  studentOpen: "Student display is open. Move it to the student’s screen. Keep this recording page visible while timing.",
  studentBlocked: "The student display did not open. Allow popups and try again, or use a printed reading copy.",
  displayHelp: "How to use this display",
  captureHelp: "About recording modes",
  studentHelp: "A separate, clean window shows only the reading task. Answers, judgments and student details stay on this page.",
  captureLabel: "Record answers",
  quick: "Quick marks",
  detail: "Add detail",
  quickHelp: "Choose an outcome to save and move on. You can change any previous answer.",
  detailHelp: "Stay on each item to record the exact response and useful observations, then choose Next item.",
  next: "Next item",
  recordOutcome: "Record the response and choose an outcome above.",
  oralTitle: "Listen and say",
  oralInstruction: "Listen to your teacher. Say your answer.",
  spellingTitle: "Listen and write",
  spellingInstruction: "Listen to your teacher. Write the word.",
  readingInstruction: "Read the word aloud.",
  fluencyInstruction: "Read aloud when your teacher says to begin.",
  returnToTeacher: "Return to teacher",
  prepare: "Before you begin",
  practice: "Try the task together",
  practiceHelp: "Optional, unscored demonstration. Use it before the first scored item. Do not rehearse the assessment items.",
  practiceAnswer: "Model response",
  teacherOnly: "Teacher only",
  guidance: "What to listen for",
  accept: "Accept",
  doNotAccept: "Do not accept",
  compare: "Compare the spelling",
  target: "Conventional spelling",
  transcription: "Student’s spelling",
  comparisonHelp: "Highlighted letters show a difference in the transcription. Judge sound representation yourself; this comparison does not score plausibility.",
  observed: "What you noticed (optional)",
  observedHelp: "Record a useful observation in the student’s own words when possible. Keep teaching feedback until after the assessment.",
  search: "Find an item or response",
  searchPlaceholder: "Search a word, task or response",
  filter: "Show items",
  all: "All items",
  recorded: "Recorded",
  unfinished: "Still to record",
  unscorable: "Couldn’t score",
  noMatches: "No matching items. Clear the search or choose All items.",
  reviewResults: "Response review",
  passageTeacher: "Teacher recording copy",
  passageHelp: "Give the student a clean display or printed copy. Start timing on the first spoken word; keep this recording page visible for the whole minute.",
  print: "Print reading copy",
  timingSteps: "Reading sequence",
  timingStepLabels: ["Prepare the copy", "Time the read", "Mark the last word", "Review the reading"],
  meaning: "Talk about the passage",
  meaningHelp: "Optional discussion after timing. Record what the student understood; this does not change the fluency score or placement.",
  meaningResponse: "Student’s explanation (optional)",
  meaningFinishHelp: "If comfortable, the student may finish the passage after timing. Keep this untimed reading separate from the recorded minute. Skip discussion if the passage remains unread.",
  meaningReadComplete: "The student has now read the complete passage",
  prosodyGuide: "Reading expression guide",
  unscored: "Unscored",
  outcomes: Object.freeze({ automatic_accurate: "Read straight away", accurate_after_sounding: "Read after sounding out", self_corrected: "Self-corrected", exact: "Correct spelling", plausible: "Sounds right", not_yet: "Not yet", incorrect: "Not correct", correct: "Correct", no_response: "No response", not_scorable: "Couldn’t score" }),
  needsDetail: "Needs detail",
  notDone: "Not done"
});
