export const MANUAL_DIAGNOSTIC_COPY = {
  letterTitle: "Letter names and sounds", patternTitle: "Phonics patterns", unnamed: "Selected student",
  letterDescription: "Record names and sounds separately. Keep the same letter order and accept consistent dialect differences.",
  patternDescription: "Assess a spelling part first, then read one word. This diagnostic describes instruction needs; it does not set a reading level.",
  teacherView: "Teacher workspace", pupilView: "Show student view", pupilClose: "Back to teacher", pupilDialog: "Student stimulus",
  letterName: "Letter name", letterSound: "Letter sound", patternSound: "Pattern pronunciation", patternWord: "Word reading",
  namePrompt: "What is the name of this letter?", soundPrompt: "What sound can this letter make?", wordPrompt: "Read this word.",
  nameGuide: "Accept the conventional letter name, including zee or zed. Naming a word that begins with the letter does not demonstrate the letter name.",
  soundGuide: "Accept a usual sound for this letter. Record the sound actually heard. A letter name alone is not sound knowledge. Use Not scorable for an access or speech barrier you cannot interpret reliably.",
  soundVariants: "Vowels may have more than one valid sound; c, g, s, x and y also vary by word. For q, record whether the student gives /k/ or the familiar qu /k/ /w/ sequence. Accept consistent dialect differences without labelling them errors.",
  wordGuide: "Hear the whole word without pictures, spoken models or a sentence clue. Accurate sounding out counts as correct; note the response process separately. Record a self-correction only when the student repairs independently.",
  instruction: "Say to the student", scoringGuide: "Scoring guidance · teacher only", stage: (i,n)=>"Item "+i+" of "+n,
  taskStep: (i,n)=>"Task "+i+" of "+n, saved: (n,total)=>n+" of "+total+" items recorded", mark: "Record the response",
  outcomes: [{value:"correct",label:"Correct"},{value:"incorrect",label:"Not yet"},{value:"no_response",label:"No response"},{value:"not_scorable",label:"Not scorable"},{value:"not_administered",label:"Not assessed"}],
  actual: "What the student said", optionalActual: "Optional for a correct response; required for Not yet.", actualPlaceholder: "Write the response you actually heard",
  selfCorrected: "Self-corrected without help", errorTypes: "What did you notice?", notes: "Observation or access note", notePlaceholder: "For example, sound added; interruption; glasses unavailable",
  errorLabels: {letter_confusion:"Letter confusion", name_for_sound:"Named instead of sounded",sound_for_name:"Sounded instead of named",vowel:"Vowel",consonant:"Consonant",omission:"Sound omitted",addition:"Sound added",substitution:"Sound substituted",blending:"Blending",word_guess:"Guessed a word"},
  nextTask: label=>"Continue to "+label.toLowerCase(), nextItem: "Save and next", finish: "Finish and save", saveExit: "Save & exit", saving: "Saving…", previous: "Previous item",
  saveError: "This result could not be saved. Your choices remain here. Try again.", review: "Review recorded items", reviewHint: "Choose an item to inspect or correct. Later responses stay in the record.",
  reviewResults: "Review results", complete: "Assessment recorded", completionNote: "These are observations from this sitting. Missing and unscorable responses stay separate; no automatic placement or mastery judgement is made.",
  recorded: "Recorded", pending: "Not recorded", missing: "Not assessed", unscorable: "Not scorable", noResponse: "No response", correct: "Correct", scored: "Scored responses",
  score: (correct,total)=>correct+" of "+total, profile: "Response profile", uppercase: "Uppercase", lowercase: "Lowercase", nextTeaching: "Plan the next teaching step",
  needsPractice: "Model the targets below in a short teaching group, practise with different examples, then assess again without support.",
  noErrors: "No errors were recorded among the scored responses. Complete any missing observations before drawing a broader conclusion.",
  reviewEvidence: "Recorded evidence", savedEvidenceHint: "This completed record is read-only. Start a new assessment for a later observation.", observedCorrect: "Teacher marked correct; response not transcribed.", notTranscribed: "No response transcript recorded.",
  restart: "Start a new assessment", return: "Return to assessments", target: "Target", outcome: "Outcome", response: "Response", supportNote: "Do not show scoring controls or model answers to the student during the assessment.",
  firstRequired: "Record the first response before showing the word.",
  draftNote: "Save & exit keeps an unfinished assessment available to resume. Review lets you correct a record without removing later responses."
};
