import {
  SHEET_NAMES,
  addCoverSheet,
  addDataSheet,
  addHowToReadSheet,
  addKpiBand,
  addProvenanceSheet,
  addSectionHeading,
  addSheet,
  addTable,
  applyPrintSetup,
  createReportWorkbook,
  downloadWorkbook,
  orderSheets,
  writeCell
} from "./excel/reportWorkbookKit.js";
import { WORKBOOK_COLORS, WORKBOOK_FONTS } from "./excel/reportWorkbookTheme.js";
import {
  MLL_DOMAINS,
  MLL_LEVELS,
  MLL_STANDING_DISCLAIMER,
  mllLevelLabel
} from "../policy/mllLanguagePolicy.js";
import { canDoBankStats } from "../data/mll/widaCanDoBank.js";

/**
 * The multilingual-learner workbook.
 *
 * This is the artefact an EL teacher takes to an ILP meeting, a parent
 * conference, or a compliance audit. It is a report, not a data dump: cover,
 * summary, what to do next, then detail, then the interpretive guide, then the
 * machine-readable rows.
 *
 * Two design rules are enforced here rather than left to the caller:
 *   - the standing WIDA disclaimer prints on the cover AND on every sheet that
 *     shows anything score-like;
 *   - official scores and classroom evidence never share a table, a colour or an
 *     axis, so no reader can mistake one for the other.
 */

const MLL_SHEETS = Object.freeze({
  PROFICIENCY: "Language proficiency",
  CAN_DO: "What they can do",
  TRANSFER: "First-language transfer",
  REFERENCE: "Sound reference",
  SERVICES: "Services and goals",
  FAMILY: "For families",
  CLASS: "Caseload",
  DESCRIPTORS: "Descriptor bank"
});

const SHEET_ORDER = [
  SHEET_NAMES.COVER,
  SHEET_NAMES.SUMMARY,
  MLL_SHEETS.CLASS,
  MLL_SHEETS.PROFICIENCY,
  MLL_SHEETS.CAN_DO,
  MLL_SHEETS.TRANSFER,
  MLL_SHEETS.REFERENCE,
  MLL_SHEETS.SERVICES,
  MLL_SHEETS.FAMILY,
  MLL_SHEETS.DESCRIPTORS,
  SHEET_NAMES.HOW_TO_READ,
  SHEET_NAMES.DATA,
  SHEET_NAMES.PROVENANCE
];

function disclaimerNotes() {
  return MLL_STANDING_DISCLAIMER.paragraphs;
}

function addDisclaimerFooter(sheet, row) {
  let current = row + 1;
  disclaimerNotes().forEach(paragraph => {
    sheet.mergeCells(`B${current}:H${current}`);
    writeCell(sheet, `B${current}`, paragraph, {
      font: WORKBOOK_FONTS.banner,
      alignment: { vertical: "top", wrapText: true }
    });
    sheet.getRow(current).height = Math.max(14, Math.ceil(paragraph.length / 130) * 12);
    current += 1;
  });
  return current;
}

/* ------------------------------------------------------------------ *
 * Student workbook
 * ------------------------------------------------------------------ */

export async function createMllStudentWorkbook(report) {
  const taken = new Set();
  const profile = report.profile || {};
  const workbook = await createReportWorkbook({
    title: `Multilingual learner report — ${profile.studentName || "Student"}`,
    subject: "WIDA-aligned classroom language evidence",
    generatedAt: report.generatedAt
  });

  /* -------- Cover -------- */
  addCoverSheet(workbook, {
    eyebrow: "Literacy Guide · Multilingual learner report",
    title: profile.studentName || "Student",
    subtitle: [profile.className, profile.grade ? `Grade ${profile.grade}` : "", report.identity?.gradeClusterLabel]
      .filter(Boolean)
      .join(" · "),
    headline: report.headline,
    facts: [
      ["Home language", report.identity?.homeLanguage],
      ["Reads in home language", report.identity?.homeLanguageLiteracyLabel],
      ["Country of origin", report.identity?.countryOfOrigin],
      ["Years in US schools", report.identity?.yearsInUsSchools ?? "Not recorded"],
      ["First identified", report.identity?.dateFirstIdentified],
      ["Program", report.services?.programModel],
      ["Latest official score", report.proficiency?.available
        ? `${report.proficiency.source} · ${report.proficiency.date}`
        : "None on file"],
      ["Report generated", String(report.generatedAt || "").slice(0, 10)],
      report.generatedBy ? ["Generated by", report.generatedBy] : null
    ],
    notices: disclaimerNotes(),
    taken
  });

  /* -------- Summary -------- */
  const summary = addSheet(workbook, SHEET_NAMES.SUMMARY, { tabColor: WORKBOOK_COLORS.teal, taken });
  summary.columns = [{ width: 2 }, ...Array.from({ length: 12 }, () => ({ width: 12 })), { width: 2 }];

  let row = 2;
  row = addSectionHeading(
    summary,
    row,
    "Current English language proficiency",
    report.proficiency?.headlineRationale || "",
    { span: 12 }
  );

  const headlineCards = [
    {
      label: report.proficiency?.headlineCompositeLabel || "Oral Language",
      value: report.proficiency?.headlineLevelLabel || null,
      note: report.proficiency?.available
        ? `${report.proficiency.source} · ${report.proficiency.date}`
        : "No official score on file",
      tone: "brand"
    },
    {
      label: "Toward exit",
      value: report.distanceToExit?.reachable === false
        ? "Not available at this grade"
        : report.distanceToExit?.meetsAll
          ? "Meets criteria"
          : report.distanceToExit?.gap != null
            ? `${report.distanceToExit.gap} to go`
            : null,
      note: report.distanceToExit?.note || "",
      tone: "neutral"
    },
    {
      label: "Sound patterns explained",
      value: report.transfer?.summary
        ? `${report.transfer.summary.explainedCount} of ${report.transfer.summary.total}`
        : null,
      note: report.transfer?.available
        ? `by ${report.transfer.summary?.language} transfer`
        : "No home language recorded",
      tone: "secure"
    },
    {
      label: "Needs a closer look",
      value: report.transfer?.summary?.residueCount ?? null,
      note: "Patterns not explained by first-language transfer",
      tone: report.transfer?.summary?.residueCount ? "developing" : "neutral"
    }
  ];
  row = addKpiBand(summary, row, headlineCards, { columnsPerCard: 3 });

  row = addSectionHeading(summary, row, "By domain", "Every score shows where it came from. Official scores and classroom evidence are never mixed.", { span: 12 });
  const domainRows = (report.proficiency?.domains || []).map(domain => {
    const canDo = (report.canDoByDomain || []).find(entry => entry.domain === domain.id);
    return {
      domain: domain.label,
      mode: MLL_DOMAINS.find(entry => entry.id === domain.id)?.mode === "expressive" ? "Expressive" : "Interpretive",
      level: domain.level != null ? mllLevelLabel(Math.floor(domain.level)) : "Not checked",
      scaleScore: domain.scaleScore,
      source: domain.source || "—",
      date: domain.date || "",
      ceiling: domain.kindergartenCeiling != null ? `Max ${domain.kindergartenCeiling} at K` : "",
      workingRange: canDo?.range?.label || ""
    };
  });
  const domainTable = addTable(
    summary,
    row,
    [
      { key: "domain", header: "Domain", width: 14 },
      { key: "mode", header: "Mode", width: 13 },
      { key: "level", header: "Official level", width: 20 },
      { key: "scaleScore", header: "Scale score", type: "number", width: 12 },
      { key: "source", header: "Source", width: 22 },
      { key: "date", header: "Assessed", type: "date", width: 12 },
      { key: "ceiling", header: "Grade ceiling", width: 16 },
      { key: "workingRange", header: "Working range (classroom)", width: 34, wrap: true }
    ],
    domainRows,
    { emptyMessage: "No official English language proficiency scores on file.", freezeHeader: false }
  );
  row = domainTable.nextRow;

  if (report.proficiency?.kindergartenNote) {
    summary.mergeCells(`B${row}:M${row}`);
    writeCell(summary, `B${row}`, report.proficiency.kindergartenNote, {
      font: WORKBOOK_FONTS.sectionHelp,
      alignment: { vertical: "top", wrapText: true }
    });
    summary.getRow(row).height = 32;
    row += 2;
  }

  if (report.dataGaps?.length) {
    row = addSectionHeading(summary, row, "Missing information", "Filling these in improves the report. Nothing here is guessed.", { span: 12 });
    const gapTable = addTable(
      summary,
      row,
      [
        { key: "field", header: "Field", width: 26 },
        { key: "impact", header: "What it changes", width: 74, wrap: true }
      ],
      report.dataGaps,
      { freezeHeader: false, autoFilter: false }
    );
    row = gapTable.nextRow;
  }

  addDisclaimerFooter(summary, row);
  applyPrintSetup(summary, { landscape: true, titleForFooter: "Summary" });

  /* -------- Trajectory -------- */
  const proficiency = addSheet(workbook, MLL_SHEETS.PROFICIENCY, { tabColor: WORKBOOK_COLORS.blue, taken });
  proficiency.columns = [{ width: 2 }, ...Array.from({ length: 11 }, () => ({ width: 15 })), { width: 2 }];
  row = 2;
  row = addSectionHeading(
    proficiency,
    row,
    "Language proficiency over time",
    report.trajectory?.note || "Three years where available, with the source of every score.",
    { span: 11 }
  );

  const trajectoryRows = [];
  (report.trajectory?.points || []).forEach(point => {
    if (point.kind === "break") {
      trajectoryRows.push({
        date: "———",
        source: point.label,
        listening: "", speaking: "", reading: "", writing: "",
        oral: "", literacy: "", overall: "",
        note: point.caution,
        isBreak: true
      });
      return;
    }
    const domainLevel = id => point.domains.find(entry => entry.id === id)?.level ?? "";
    const compositeLevel = id => point.composites.find(entry => entry.id === id)?.level ?? "";
    trajectoryRows.push({
      date: point.date,
      source: point.sourceLabel,
      grade: point.gradeAtTest,
      listening: domainLevel("listening"),
      speaking: domainLevel("speaking"),
      reading: domainLevel("reading"),
      writing: domainLevel("writing"),
      oral: compositeLevel("oral_language"),
      literacy: compositeLevel("literacy"),
      overall: compositeLevel("overall"),
      note: point.official ? "Official score" : "Not an official score"
    });
  });

  const trajectoryTable = addTable(
    proficiency,
    row,
    [
      { key: "date", header: "Date", width: 13 },
      { key: "source", header: "Source", width: 30, wrap: true },
      { key: "grade", header: "Grade", width: 8 },
      { key: "listening", header: "Listening", type: "number", numFmt: "0.0", width: 11 },
      { key: "speaking", header: "Speaking", type: "number", numFmt: "0.0", width: 11 },
      { key: "reading", header: "Reading", type: "number", numFmt: "0.0", width: 11 },
      { key: "writing", header: "Writing", type: "number", numFmt: "0.0", width: 11 },
      { key: "oral", header: "Oral Language", type: "number", numFmt: "0.0", width: 14 },
      { key: "literacy", header: "Literacy", type: "number", numFmt: "0.0", width: 11 },
      { key: "overall", header: "Overall", type: "number", numFmt: "0.0", width: 11 },
      { key: "note", header: "Note", width: 44, wrap: true }
    ],
    trajectoryRows,
    { emptyMessage: "No language proficiency history on file yet.", autoFilter: false }
  );
  row = trajectoryTable.nextRow;

  // Highlight the rebaseline row so it cannot be skimmed past.
  trajectoryRows.forEach((entry, index) => {
    if (!entry.isBreak) return;
    const excelRow = trajectoryTable.firstDataRow + index;
    for (let column = 2; column <= 12; column += 1) {
      const cell = proficiency.getRow(excelRow).getCell(column);
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: WORKBOOK_COLORS.developingFill } };
      cell.font = { ...WORKBOOK_FONTS.body, bold: true, color: { argb: WORKBOOK_COLORS.developingText } };
    }
  });

  row = addSectionHeading(proficiency, row, "How the composites are built", "", { span: 11 });
  const compositeTable = addTable(
    proficiency,
    row,
    [
      { key: "label", header: "Composite", width: 20 },
      { key: "note", header: "Weighting", width: 60, wrap: true }
    ],
    report.proficiency?.compositeWeights || [],
    { freezeHeader: false, autoFilter: false }
  );
  row = compositeTable.nextRow;
  addDisclaimerFooter(proficiency, row);
  applyPrintSetup(proficiency, { landscape: true, titleForFooter: "Language proficiency over time" });

  /* -------- Can Do -------- */
  const canDoSheet = addSheet(workbook, MLL_SHEETS.CAN_DO, { tabColor: WORKBOOK_COLORS.teal, taken });
  canDoSheet.columns = [{ width: 2 }, { width: 16 }, { width: 22 }, { width: 74 }, { width: 20 }, { width: 2 }];
  row = 2;
  row = addSectionHeading(
    canDoSheet,
    row,
    "What this student can do now",
    "Statements from the WIDA Can Do Descriptors at the student's working level, taken at the lower end of the range so the report claims what is securely observable.",
    { span: 4 }
  );

  const canDoRows = (report.canDoByDomain || []).flatMap(entry =>
    entry.statements.length
      ? entry.statements.map(statement => ({
          domain: entry.domainLabel,
          level: statement.levelLabel,
          statement: statement.text,
          keyUse: statement.keyUse + (statement.inferredCrosswalk ? " (mapping inferred)" : "")
        }))
      : [{
          domain: entry.domainLabel,
          level: "",
          statement: entry.note || entry.range?.note || "No descriptors available for this domain yet.",
          keyUse: ""
        }]
  );
  const canDoTable = addTable(
    canDoSheet,
    row,
    [
      { key: "domain", header: "Domain", width: 16 },
      { key: "level", header: "Level", width: 22 },
      { key: "statement", header: "Can do", width: 74, wrap: true },
      { key: "keyUse", header: "Key language use", width: 20, wrap: true }
    ],
    canDoRows,
    { emptyMessage: "No working level recorded yet, so no Can Do statements are shown." }
  );
  row = canDoTable.nextRow;
  writeCell(canDoSheet, `B${row}`, "About these statements", { font: WORKBOOK_FONTS.kpiLabel });
  canDoSheet.mergeCells(`C${row}:E${row}`);
  writeCell(
    canDoSheet,
    `C${row}`,
    `From the ${canDoBankStats().edition}. That edition is keyed to the 2016 Key Uses (Recount, Explain, Argue, Discuss) while the current standards use the 2020 Key Language Uses (Narrate, Inform, Explain, Argue). Where a statement is mapped from Recount to Narrate or Inform, it is marked "mapping inferred" — WIDA has not published a crosswalk, so that mapping is Literacy Guide's.`,
    { font: WORKBOOK_FONTS.body, alignment: { vertical: "top", wrapText: true } }
  );
  canDoSheet.getRow(row).height = 58;
  row += 2;
  addDisclaimerFooter(canDoSheet, row);
  applyPrintSetup(canDoSheet, { landscape: true, titleForFooter: "What this student can do now" });

  /* -------- Transfer -------- */
  const transferSheet = addSheet(workbook, MLL_SHEETS.TRANSFER, { tabColor: WORKBOOK_COLORS.purple, taken });
  transferSheet.columns = [{ width: 2 }, { width: 14 }, { width: 12 }, { width: 12 }, { width: 12 }, { width: 68 }, { width: 2 }];
  row = 2;
  row = addSectionHeading(
    transferSheet,
    row,
    "First-language transfer",
    "An English-only phonics assessment cannot tell the difference between a sound a student cannot decode and a sound that does not exist in their first language. This section separates the two.",
    { span: 5 }
  );

  transferSheet.mergeCells(`B${row}:F${row + 2}`);
  writeCell(transferSheet, `B${row}`, report.transfer?.narrative || "", {
    font: WORKBOOK_FONTS.body,
    fill: WORKBOOK_COLORS.primarySoft,
    alignment: { vertical: "top", wrapText: true }
  });
  transferSheet.getRow(row).height = 26;
  transferSheet.getRow(row + 1).height = 26;
  transferSheet.getRow(row + 2).height = 26;
  row += 4;

  row = addSectionHeading(
    transferSheet,
    row,
    "Patterns that need a closer look",
    "The residue — what first-language transfer does not explain. This is the part worth attention.",
    { span: 5 }
  );
  transferSheet.mergeCells(`B${row}:F${row + 1}`);
  writeCell(transferSheet, `B${row}`, report.transfer?.residueNarrative || "", {
    font: { ...WORKBOOK_FONTS.body, bold: true },
    fill: WORKBOOK_COLORS.developingFill,
    alignment: { vertical: "top", wrapText: true }
  });
  transferSheet.getRow(row).height = 28;
  transferSheet.getRow(row + 1).height = 28;
  row += 3;

  const residueRows = (report.transfer?.residue || []).map(entry => ({
    sound: entry.targetPhoneme ? `/${entry.targetPhoneme}/` : entry.word || "",
    produced: entry.producedPhoneme ? `/${entry.producedPhoneme}/` : "",
    position: entry.position || "",
    missed: entry.occurrences,
    opportunities: entry.opportunities,
    note: entry.note || ""
  }));
  const residueTable = addTable(
    transferSheet,
    row,
    [
      { key: "sound", header: "Target sound", width: 14 },
      { key: "produced", header: "Produced", width: 12 },
      { key: "position", header: "Position", width: 12 },
      { key: "missed", header: "Missed", type: "number", width: 13 },
      { key: "opportunities", header: "Chances", type: "number", width: 13 },
      { key: "note", header: "Note", width: 68, wrap: true }
    ],
    residueRows,
    { emptyMessage: "Nothing here. Every recorded pattern is explained by first-language differences.", freezeHeader: false }
  );
  row = residueTable.nextRow;

  row = addSectionHeading(
    transferSheet,
    row,
    "Patterns explained by first-language transfer",
    "Forward cue transfer — a normal stage of learning a second sound system. Teach these as new sounds, not as decoding difficulties.",
    { span: 5 }
  );
  const explainedRows = (report.transfer?.explained || []).map(entry => ({
    sound: entry.targetPhoneme ? `/${entry.targetPhoneme}/` : entry.word || "",
    produced: entry.producedPhoneme ? `/${entry.producedPhoneme}/` : "",
    position: entry.position || "",
    missed: entry.occurrences,
    opportunities: entry.opportunities,
    note: entry.sentence || ""
  }));
  const explainedTable = addTable(
    transferSheet,
    row,
    [
      { key: "sound", header: "Target sound", width: 14 },
      { key: "produced", header: "Produced", width: 12 },
      { key: "position", header: "Position", width: 12 },
      { key: "missed", header: "Missed", type: "number", width: 13 },
      { key: "opportunities", header: "Chances", type: "number", width: 13 },
      { key: "note", header: "Why this is expected", width: 68, wrap: true }
    ],
    explainedRows,
    { emptyMessage: "No transfer-explained patterns recorded.", freezeHeader: false }
  );
  row = explainedTable.nextRow;

  [report.transfer?.caution, report.transfer?.disclaimer]
    .filter(Boolean)
    .forEach(text => {
      transferSheet.mergeCells(`B${row}:F${row}`);
      writeCell(transferSheet, `B${row}`, text, {
        font: { ...WORKBOOK_FONTS.banner, bold: true },
        alignment: { vertical: "top", wrapText: true }
      });
      transferSheet.getRow(row).height = Math.max(16, Math.ceil(text.length / 120) * 13);
      row += 1;
    });
  addDisclaimerFooter(transferSheet, row);
  applyPrintSetup(transferSheet, { landscape: true, titleForFooter: "First-language transfer" });

  /* -------- Sound reference -------- */
  if (report.transferReference?.length) {
    const reference = addSheet(workbook, MLL_SHEETS.REFERENCE, { tabColor: WORKBOOK_COLORS.purple, taken });
    reference.columns = [{ width: 2 }];
    row = addSectionHeading(
      reference,
      2,
      `English sounds and ${report.transfer?.homeLanguage || "the home language"}`,
      "Differences documented in the research. Every row here predicts an English \"error\" that is not a decoding difficulty.",
      { span: 6 }
    );
    addTable(
      reference,
      row,
      [
        { key: "category", header: "Type", width: 12 },
        { key: "target", header: "English", width: 26, wrap: true },
        { key: "expected", header: "Often becomes", width: 18 },
        { key: "position", header: "Where", width: 12 },
        { key: "example", header: "Example", width: 40, wrap: true },
        { key: "note", header: "Note", width: 60, wrap: true }
      ],
      report.transferReference,
      { emptyMessage: "No reference available." }
    );
    applyPrintSetup(reference, { landscape: true, repeatHeaderRow: row, titleForFooter: "Sound reference" });
  }

  /* -------- Services and goals -------- */
  const services = addSheet(workbook, MLL_SHEETS.SERVICES, { tabColor: WORKBOOK_COLORS.amber, taken });
  services.columns = [{ width: 2 }, { width: 26 }, { width: 74 }, { width: 2 }];
  row = 2;
  row = addSectionHeading(services, row, "Services and accommodations", "", { span: 2 });
  [
    ["Program model", report.services?.programModel],
    ["Minutes per week", report.services?.serviceMinutesPerWeek ?? "Not recorded"],
    ["Provider", report.services?.serviceProvider],
    ["Support types", (report.services?.supportTypes || []).join(", ") || "None recorded"],
    ["Accommodations", (report.services?.accommodations || []).join(", ") || "None recorded"],
    report.services?.declinedNote ? ["Family declined services", report.services.declinedNote] : null
  ]
    .filter(Boolean)
    .forEach(([label, value]) => {
      writeCell(services, `B${row}`, label, { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
      writeCell(services, `C${row}`, value, { font: WORKBOOK_FONTS.body, alignment: { vertical: "top", wrapText: true } });
      services.getRow(row).height = Math.max(16, Math.ceil(String(value).length / 88) * 14);
      row += 1;
    });

  row += 1;
  row = addSectionHeading(services, row, "Language goals", "Tied to WIDA Language Expectations rather than to a score.", { span: 2 });
  const goalTable = addTable(
    services,
    row,
    [
      { key: "domain", header: "Domain", width: 14 },
      { key: "text", header: "Goal", width: 60, wrap: true },
      { key: "expectationCode", header: "Language Expectation", width: 30 },
      { key: "targetDate", header: "Target", type: "date", width: 12 },
      { key: "status", header: "Status", width: 14 }
    ],
    report.goals || [],
    { emptyMessage: "No language goals recorded yet.", freezeHeader: false }
  );
  row = goalTable.nextRow;

  (report.suggestedExpectations || []).forEach(suggestion => {
    row = addSectionHeading(
      services,
      row,
      `Suggested focus: ${suggestion.label}`,
      suggestion.definition,
      { span: 2 }
    );
    writeCell(services, `B${row}`, suggestion.code, { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
    services.mergeCells(`C${row}:C${row}`);
    writeCell(services, `C${row}`, suggestion.expectations.join("  ·  "), {
      font: WORKBOOK_FONTS.body,
      alignment: { vertical: "top", wrapText: true }
    });
    services.getRow(row).height = 48;
    row += 2;
  });
  applyPrintSetup(services, { titleForFooter: "Services and goals" });

  /* -------- Family -------- */
  const family = addSheet(workbook, MLL_SHEETS.FAMILY, { tabColor: WORKBOOK_COLORS.teal, taken });
  family.columns = [{ width: 2 }, { width: 22 }, { width: 82 }, { width: 2 }];
  row = 2;
  row = addSectionHeading(
    family,
    row,
    "For families",
    "Plain language. No percentiles, no scaled scores, no reading levels, no comparisons to classmates.",
    { span: 2 }
  );
  writeCell(family, `B${row}`, "Your child's language", { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
  writeCell(family, `C${row}`, report.family?.affirmL1 || "", {
    font: { ...WORKBOOK_FONTS.body, bold: true },
    fill: WORKBOOK_COLORS.primarySoft,
    alignment: { vertical: "top", wrapText: true }
  });
  family.getRow(row).height = 34;
  row += 2;

  (report.family?.strengths || []).forEach(strength => {
    writeCell(family, `B${row}`, `Can do — ${strength.domain}`, { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
    writeCell(family, `C${row}`, strength.statement, { font: WORKBOOK_FONTS.body, alignment: { vertical: "top", wrapText: true } });
    row += 1;
  });

  row += 1;
  row = addSectionHeading(family, row, "What you can do at home", "", { span: 2 });
  (report.family?.homeActions || []).forEach((action, index) => {
    writeCell(family, `B${row}`, `${index + 1}.`, { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
    writeCell(family, `C${row}`, action, { font: WORKBOOK_FONTS.body, alignment: { vertical: "top", wrapText: true } });
    family.getRow(row).height = Math.max(18, Math.ceil(action.length / 95) * 15);
    row += 1;
  });

  row += 1;
  writeCell(family, `B${row}`, "Questions?", { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
  writeCell(family, `C${row}`, report.family?.whoToTalkTo || "", {
    font: WORKBOOK_FONTS.body,
    alignment: { vertical: "top", wrapText: true }
  });
  family.getRow(row).height = 32;
  applyPrintSetup(family, { titleForFooter: "For families" });

  /* -------- How to read -------- */
  addHowToReadSheet(workbook, {
    metricRows: [
      { label: "Proficiency level", definition: "One of six WIDA levels, 1 Entering to 6 Reaching. Shown number-first because the 2020 descriptors are numeric and will survive the 2027 revision." },
      { label: "Oral Language", definition: "Listening and Speaking, weighted equally. This report leads with it because Overall is 70% literacy-weighted and misrepresents young multilingual learners." },
      { label: "Overall", definition: "Listening 15%, Speaking 15%, Reading 35%, Writing 35%. Composites are built from scale scores and then converted — proficiency levels cannot be averaged." },
      { label: "Working range", definition: "A range, never a single number. A single number would be a WIDA proficiency level in all but name, and this product does not produce those." },
      { label: "First-language transfer", definition: "A predictable difference between two sound systems. Not an error in any clinical sense — a normal stage of learning a second language." },
      { label: "Residue", definition: "The error patterns first-language transfer does not explain. These are the ones worth a closer look." }
    ],
    extraNotes: [
      ...disclaimerNotes(),
      "This report is classroom evidence to bring to an ACCESS or ILP conversation. It is not a substitute for your state's designated English language proficiency assessment."
    ],
    taken
  });

  /* -------- Data -------- */
  const dataRows = (report.canDoByDomain || []).map(entry => ({
    student_id: profile.studentId,
    student_name: profile.studentName,
    class_name: profile.className,
    grade: profile.grade,
    grade_cluster: profile.gradeCluster,
    home_language: profile.homeLanguage,
    home_language_literacy: profile.homeLanguageLiteracy === null ? "" : profile.homeLanguageLiteracy ? "yes" : "no",
    domain_code: entry.domain,
    domain_name: entry.domainLabel,
    mode: entry.mode,
    official_level: entry.officialLevel ?? "",
    official_level_label: entry.officialLevelLabel,
    official_source: report.proficiency?.source || "",
    official_date: report.proficiency?.date || "",
    working_range_label: entry.range?.label || "",
    working_range_basis: entry.range?.basis || "",
    can_do_statements: entry.statements.length,
    transfer_explained: report.transfer?.summary?.explainedCount ?? "",
    transfer_residue: report.transfer?.summary?.residueCount ?? "",
    policy_version: report.policyVersion
  }));
  addDataSheet(
    workbook,
    Object.keys(dataRows[0] || {
      student_id: "", student_name: "", domain_code: "", domain_name: ""
    }).map(key => ({ key, header: key, width: Math.max(12, key.length + 3) })),
    dataRows,
    { taken }
  );

  /* -------- Provenance -------- */
  addProvenanceSheet(
    workbook,
    [
      { field: "Report type", value: "Multilingual learner student report" },
      { field: "Student", value: profile.studentName },
      { field: "Class", value: profile.className },
      { field: "Generated", value: report.generatedAt },
      { field: "Generated by", value: report.generatedBy || "Not recorded" },
      { field: "Language policy version", value: report.policyVersion },
      { field: "Descriptor bank", value: canDoBankStats().edition },
      { field: "Descriptors available", value: `${canDoBankStats().total} across Kindergarten, Grade 1 and Grades 2-3` },
      { field: "Crosswalk provenance", value: canDoBankStats().crosswalkProvenance },
      { field: "Official scores on file", value: report.proficiency?.available ? `${report.proficiency.source}, ${report.proficiency.date}` : "None" },
      { field: "Exit criteria", value: profile.exitCriteria?.configured ? `${profile.exitCriteria.compositeId} ≥ ${profile.exitCriteria.compositeMinimum}${profile.exitCriteria.domainFloor ? `, no domain below ${profile.exitCriteria.domainFloor}` : ""}` : "Not configured for this district" },
      { field: "First-language reference", value: report.transfer?.profile ? `${report.transfer.profile.label} (${report.transfer.profile.reviewStatus})` : "None" },
      { field: "Copy issues found", value: report.copyIssues?.length ? `${report.copyIssues.length} deficit-framing phrases flagged` : "None" }
    ],
    { taken, extraNotes: disclaimerNotes() }
  );

  orderSheets(workbook, SHEET_ORDER);
  return workbook;
}

export async function exportMllStudentReport(report, { fileName = "" } = {}) {
  const workbook = await createMllStudentWorkbook(report);
  const name =
    fileName ||
    `mll-report-${slug(report.profile?.studentName || "student")}-${String(report.generatedAt || "").slice(0, 10)}.xlsx`;
  return downloadWorkbook(workbook, name);
}

/* ------------------------------------------------------------------ *
 * Class workbook
 * ------------------------------------------------------------------ */

export async function createMllClassWorkbook(report) {
  const taken = new Set();
  const workbook = await createReportWorkbook({
    title: `Multilingual learner caseload — ${report.className || "Class"}`,
    subject: "WIDA-aligned classroom language evidence",
    generatedAt: report.generatedAt
  });

  addCoverSheet(workbook, {
    eyebrow: "Literacy Guide · Multilingual learner caseload",
    title: report.className || "Class",
    subtitle: `${report.summary.multilingualLearners} multilingual ${report.summary.multilingualLearners === 1 ? "learner" : "learners"}`,
    headline: `${report.summary.multilingualLearners} multilingual ${report.summary.multilingualLearners === 1 ? "learner" : "learners"}, ${report.summary.withOfficialScores} with an official proficiency score on file. ${report.headlineNote}`,
    facts: [
      ["Languages", report.summary.languages.map(entry => `${entry.language} (${entry.count})`).join(", ") || "None recorded"],
      ["In a monitoring window", report.summary.inMonitoring],
      ["Meeting exit criteria", report.summary.meetingExitCriteria],
      ["Missing fields across caseload", report.summary.totalDataGaps],
      ["Generated", String(report.generatedAt || "").slice(0, 10)]
    ],
    notices: [report.orderingNote, ...disclaimerNotes()],
    taken
  });

  const summary = addSheet(workbook, SHEET_NAMES.SUMMARY, { tabColor: WORKBOOK_COLORS.teal, taken });
  summary.columns = [{ width: 2 }, ...Array.from({ length: 12 }, () => ({ width: 12 })), { width: 2 }];
  let row = addSectionHeading(summary, 2, "Caseload at a glance", "", { span: 12 });
  row = addKpiBand(summary, row, [
    { label: "Multilingual learners", value: report.summary.multilingualLearners, note: "On this class list", tone: "brand" },
    { label: "With official scores", value: report.summary.withOfficialScores, note: "ACCESS, screener or MODEL on file", tone: "neutral" },
    { label: "In monitoring", value: report.summary.inMonitoring, note: "Exited, still monitored", tone: "neutral" },
    { label: "Missing fields", value: report.summary.totalDataGaps, note: "Across the caseload", tone: report.summary.totalDataGaps ? "developing" : "secure" }
  ], { columnsPerCard: 3 });

  row = addSectionHeading(summary, row, "Levels on file", "Students with no official score are counted separately, never as zero.", { span: 12 });
  const levelTable = addTable(
    summary,
    row,
    [
      { key: "label", header: "Level", width: 26 },
      { key: "count", header: "Students", type: "number", width: 14 }
    ],
    report.summary.levelDistribution,
    { freezeHeader: false, autoFilter: false }
  );
  row = levelTable.nextRow;

  row = addSectionHeading(summary, row, "Languages", "", { span: 12 });
  addTable(
    summary,
    row,
    [
      { key: "language", header: "Home language", width: 26 },
      { key: "count", header: "Students", type: "number", width: 14 }
    ],
    report.summary.languages,
    { freezeHeader: false, autoFilter: false }
  );
  applyPrintSetup(summary, { landscape: true, titleForFooter: "Caseload at a glance" });

  const caseload = addSheet(workbook, MLL_SHEETS.CLASS, { tabColor: WORKBOOK_COLORS.blue, taken });
  caseload.columns = [{ width: 2 }];
  row = addSectionHeading(
    caseload,
    2,
    "Caseload",
    report.orderingNote,
    { span: 12 }
  );
  addTable(
    caseload,
    row,
    [
      { key: "studentName", header: "Student", width: 22 },
      { key: "grade", header: "Grade", width: 8 },
      { key: "homeLanguage", header: "Home language", width: 16 },
      { key: "headlineLevelLabel", header: "Oral Language", width: 20 },
      { key: "listening", header: "Listening", type: "number", numFmt: "0.0", width: 11 },
      { key: "speaking", header: "Speaking", type: "number", numFmt: "0.0", width: 11 },
      { key: "reading", header: "Reading", type: "number", numFmt: "0.0", width: 11 },
      { key: "writing", header: "Writing", type: "number", numFmt: "0.0", width: 11 },
      { key: "lastAssessed", header: "Last assessed", type: "date", width: 13 },
      { key: "source", header: "Source", width: 22 },
      { key: "programModel", header: "Program", width: 20, wrap: true },
      { key: "serviceMinutesPerWeek", header: "Min/week", type: "number", width: 13 },
      { key: "transferResidue", header: "Needs a look", type: "number", width: 12 },
      { key: "dataGapCount", header: "Missing fields", type: "number", width: 13 }
    ],
    report.rows,
    { freezeFirstColumn: true, emptyMessage: "No multilingual learners flagged on this class list yet." }
  );
  applyPrintSetup(caseload, { landscape: true, repeatHeaderRow: row, titleForFooter: "Caseload" });

  addHowToReadSheet(workbook, {
    metricRows: [
      { label: "Oral Language", definition: "Listening and Speaking, weighted equally. Used as the headline for K-3 because Overall is 70% literacy-weighted." },
      { label: "Needs a look", definition: "Sound patterns not explained by first-language transfer. A high number is worth investigating; a zero is not a clean bill of health." },
      { label: "Missing fields", definition: "Profile fields that would improve this student's report. Home language is the highest-value one." }
    ],
    extraNotes: [report.orderingNote, ...disclaimerNotes()],
    taken
  });

  addDataSheet(
    workbook,
    [
      { key: "studentId", header: "student_id", width: 20 },
      { key: "studentName", header: "student_name", width: 22 },
      { key: "grade", header: "grade", width: 8 },
      { key: "gradeCluster", header: "grade_cluster", width: 14 },
      { key: "homeLanguage", header: "home_language", width: 16 },
      { key: "lifecycleStage", header: "lifecycle_stage", width: 18 },
      { key: "programModel", header: "program_model", width: 20 },
      { key: "serviceMinutesPerWeek", header: "service_minutes_per_week", type: "number", width: 20 },
      { key: "headlineLevel", header: "oral_language_level", type: "number", numFmt: "0.0", width: 18 },
      { key: "listening", header: "listening_level", type: "number", numFmt: "0.0", width: 15 },
      { key: "speaking", header: "speaking_level", type: "number", numFmt: "0.0", width: 15 },
      { key: "reading", header: "reading_level", type: "number", numFmt: "0.0", width: 15 },
      { key: "writing", header: "writing_level", type: "number", numFmt: "0.0", width: 15 },
      { key: "lastAssessed", header: "last_assessed", width: 14 },
      { key: "source", header: "score_source", width: 22 },
      { key: "distanceToExit", header: "levels_to_exit", type: "number", numFmt: "0.0", width: 14 },
      { key: "meetsExit", header: "meets_exit_criteria", width: 18 },
      { key: "inMonitoring", header: "in_monitoring_window", width: 20 },
      { key: "transferResidue", header: "unexplained_sound_patterns", type: "number", width: 24 },
      { key: "dataGapCount", header: "missing_profile_fields", type: "number", width: 20 }
    ],
    report.rows,
    { taken }
  );

  addProvenanceSheet(
    workbook,
    [
      { field: "Report type", value: "Multilingual learner caseload" },
      { field: "Class", value: report.className },
      { field: "Generated", value: report.generatedAt },
      { field: "Students included", value: report.summary.multilingualLearners },
      { field: "Language policy version", value: report.policyVersion },
      { field: "Ordering", value: report.orderingNote }
    ],
    { taken, extraNotes: disclaimerNotes() }
  );

  orderSheets(workbook, SHEET_ORDER);
  return workbook;
}

export async function exportMllClassReport(report, { fileName = "" } = {}) {
  const workbook = await createMllClassWorkbook(report);
  const name = fileName || `mll-caseload-${slug(report.className || "class")}-${String(report.generatedAt || "").slice(0, 10)}.xlsx`;
  return downloadWorkbook(workbook, name);
}

/* ------------------------------------------------------------------ *
 * Descriptor bank sheet — usable on its own
 * ------------------------------------------------------------------ */

export async function createCanDoBankWorkbook(descriptors) {
  const taken = new Set();
  const stats = canDoBankStats();
  const workbook = await createReportWorkbook({
    title: "WIDA Can Do Descriptors — K to Grade 3",
    subject: stats.edition
  });
  addCoverSheet(workbook, {
    eyebrow: "Literacy Guide",
    title: "WIDA Can Do Descriptors",
    subtitle: "Kindergarten, Grade 1, Grades 2-3",
    headline: `${stats.total} descriptors across three grade clusters, four domains and five proficiency levels. Level 6 has no descriptors — WIDA deliberately leaves it open-ended.`,
    facts: [
      ["Edition", stats.edition],
      ["Clusters", stats.clusters.join(", ")],
      ["Levels", stats.levels.join(", ")],
      ["Rows with an inferred 2020 mapping", stats.inferredCrosswalkRows]
    ],
    notices: [stats.crosswalkProvenance, ...disclaimerNotes()],
    taken
  });
  const sheet = addSheet(workbook, MLL_SHEETS.DESCRIPTORS, { tabColor: WORKBOOK_COLORS.teal, taken });
  sheet.columns = [{ width: 2 }];
  const row = addSectionHeading(sheet, 2, "Descriptor bank", stats.crosswalkProvenance, { span: 7 });
  addTable(
    sheet,
    row,
    [
      { key: "clusterLabel", header: "Grade cluster", width: 15 },
      { key: "levelLabel", header: "Level", width: 20 },
      { key: "domainLabel", header: "Domain", width: 14 },
      { key: "keyUse2016Label", header: "Key Use (2016)", width: 15 },
      { key: "keyUse2020Label", header: "Key Language Use (2020)", width: 26, wrap: true },
      { key: "text", header: "Can do", width: 70, wrap: true }
    ],
    descriptors,
    { freezeFirstColumn: true }
  );
  applyPrintSetup(sheet, { landscape: true, repeatHeaderRow: row, titleForFooter: "Descriptor bank" });
  orderSheets(workbook, [SHEET_NAMES.COVER, MLL_SHEETS.DESCRIPTORS]);
  return workbook;
}

function slug(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48) || "report";
}

export const MLL_WORKBOOK_SHEETS = MLL_SHEETS;
export const MLL_WORKBOOK_LEVELS = MLL_LEVELS;
