import {
  NUMBER_FORMATS,
  WORKBOOK_COLORS,
  WORKBOOK_FONTS,
  statusCellStyle,
  statusLegendRows
} from "./reportWorkbookTheme.js";
import {
  REPORTING_BIBLE_POLICY,
  REPORTING_BIBLE_VERSION,
  REPORT_STATUS_LABELS,
  REPORT_STATUS_NOTES,
  REPORT_STATUS_ORDER,
  STANDING_NOTICES,
  canonicalStatusId,
  evaluateMasteryGates,
  reportStatusLabel
} from "../../policy/reportingBible.js";

/**
 * The workbook kit.
 *
 * A workbook is a report that happens to be in Excel. It carries the same
 * summary block, the same vocabulary, the same colours and the same next-step
 * guidance as the screen — Reporting Bible, Part X.
 *
 * Before this kit, every export was a flat provenance dump: a 29-column sheet
 * whose headers included "Response schema", "Scoring rule version" and
 * "Administration interface", with no cover, no summary, no next step, and
 * export-only synonyms ("Growing", "Not started yet") that contradicted the
 * screen. That is an audit log, not a report. This kit builds the report.
 *
 * Nothing here knows about literacy. It knows about cover sheets, KPI bands,
 * tables, matrices and legends. The report builders supply the content.
 */

export const SHEET_NAMES = Object.freeze({
  COVER: "Cover",
  SUMMARY: "Summary",
  TEACH_NEXT: "Teach next",
  HOW_TO_READ: "How to read this",
  DATA: "Data",
  PROVENANCE: "About this report"
});

/** Excel forbids these in a sheet name, and caps the name at 31 characters. */
export function safeSheetName(name, taken = new Set()) {
  let base = String(name || "Sheet").replace(/[[\]:*?/\\]/g, " ").trim().slice(0, 31) || "Sheet";
  if (!taken.has(base)) {
    taken.add(base);
    return base;
  }
  for (let suffix = 2; suffix < 100; suffix += 1) {
    const candidate = `${base.slice(0, 31 - String(suffix).length - 1)} ${suffix}`;
    if (!taken.has(candidate)) {
      taken.add(candidate);
      return candidate;
    }
  }
  taken.add(base);
  return base;
}

async function loadExcelJs() {
  const module = await import("exceljs");
  const ExcelJS = module.default || module["module.exports"] || module;
  if (!ExcelJS?.Workbook) throw new Error("ExcelJS workbook export is unavailable.");
  return ExcelJS;
}

/* ------------------------------------------------------------------ *
 * Low-level cell helpers
 * ------------------------------------------------------------------ */

function fill(color) {
  return { type: "pattern", pattern: "solid", fgColor: { argb: color } };
}

function thin(color) {
  return { style: "thin", color: { argb: color } };
}

function boxBorder(color) {
  return { top: thin(color), left: thin(color), bottom: thin(color), right: thin(color) };
}

export function writeCell(sheet, address, value, style = {}) {
  const cell = sheet.getCell(address);
  cell.value = value === undefined || value === null ? "" : value;
  if (style.font) cell.font = style.font;
  if (style.fill) cell.fill = fill(style.fill);
  if (style.border) cell.border = style.border;
  if (style.alignment) cell.alignment = style.alignment;
  if (style.numFmt) cell.numFmt = style.numFmt;
  return cell;
}

/**
 * Values that must never render as 0.
 *
 * The bible's first law: missing evidence is reported as missing. Passing null
 * through `Number()` yields 0, and a 0 in an accuracy column reads as a child
 * who got everything wrong. Every numeric writer in this kit goes through here.
 */
export function numberOrBlank(value) {
  if (value === undefined || value === null || value === "") return "";
  const number = Number(value);
  return Number.isFinite(number) ? number : "";
}

export function percentOrBlank(value) {
  const number = numberOrBlank(value);
  return number === "" ? "" : number / 100;
}

export function dateOrBlank(value) {
  if (!value) return "";
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 10);
}

/* ------------------------------------------------------------------ *
 * Workbook creation and chrome
 * ------------------------------------------------------------------ */

export async function createReportWorkbook({
  title = "Literacy Guide report",
  subject = "",
  creator = "Literacy Guide",
  generatedAt = null
} = {}) {
  const ExcelJS = await loadExcelJs();
  const workbook = new ExcelJS.Workbook();
  workbook.creator = creator;
  workbook.lastModifiedBy = creator;
  workbook.title = title;
  workbook.subject = subject;
  workbook.company = "Literacy Guide";
  workbook.description = `Generated by Literacy Guide. Reporting policy ${REPORTING_BIBLE_VERSION}.`;
  if (generatedAt) {
    const stamp = generatedAt instanceof Date ? generatedAt : new Date(generatedAt);
    if (!Number.isNaN(stamp.getTime())) {
      workbook.created = stamp;
      workbook.modified = stamp;
    }
  }
  workbook.views = [{ x: 0, y: 0, width: 24000, height: 16000, firstSheet: 0, activeTab: 0, visibility: "visible" }];
  return workbook;
}

/**
 * Page setup plus the FERPA banner in the print header. Every sheet gets this;
 * a printed page that leaves the building must say what it is.
 */
export function applyPrintSetup(sheet, { landscape = false, repeatHeaderRow = 0, titleForFooter = "" } = {}) {
  sheet.pageSetup = {
    orientation: landscape ? "landscape" : "portrait",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    horizontalCentered: false,
    margins: { left: 0.4, right: 0.4, top: 0.6, bottom: 0.6, header: 0.3, footer: 0.3 },
    printTitlesRow: repeatHeaderRow ? `${repeatHeaderRow}:${repeatHeaderRow}` : undefined
  };
  sheet.headerFooter = {
    oddHeader: `&L&"Calibri,Italic"&8${REPORTING_BIBLE_POLICY.exportPrivacy.confidentialityBanner}`,
    oddFooter: `&L&"Calibri,Regular"&8${titleForFooter || sheet.name}&R&"Calibri,Regular"&8Page &P of &N`
  };
}

export function addSheet(workbook, name, { tabColor = WORKBOOK_COLORS.teal, taken } = {}) {
  const sheet = workbook.addWorksheet(safeSheetName(name, taken), {
    properties: { tabColor: { argb: tabColor }, defaultRowHeight: 18 },
    views: [{ showGridLines: false }]
  });
  return sheet;
}

/* ------------------------------------------------------------------ *
 * Cover sheet
 * ------------------------------------------------------------------ */

/**
 * The cover. Hambleton & Zenisky's most actionable finding is that every report
 * needs a highlight block at the top saying what it says — the field's weakest
 * domain is supporting material, at 1.28 out of 3.0.
 */
export function addCoverSheet(workbook, {
  eyebrow = "Literacy Guide",
  title = "Report",
  subtitle = "",
  headline = "",
  facts = [],
  notices = [],
  taken
} = {}) {
  const sheet = addSheet(workbook, SHEET_NAMES.COVER, { tabColor: WORKBOOK_COLORS.primary, taken });
  sheet.columns = [{ width: 3 }, { width: 26 }, { width: 62 }, { width: 3 }];

  sheet.mergeCells("B2:C2");
  writeCell(sheet, "B2", eyebrow.toUpperCase(), { font: WORKBOOK_FONTS.coverEyebrow });

  sheet.mergeCells("B3:C4");
  writeCell(sheet, "B3", title, {
    font: WORKBOOK_FONTS.coverTitle,
    alignment: { vertical: "middle", wrapText: true }
  });
  sheet.getRow(3).height = 30;
  sheet.getRow(4).height = 12;

  if (subtitle) {
    sheet.mergeCells("B5:C5");
    writeCell(sheet, "B5", subtitle, { font: WORKBOOK_FONTS.coverSubtitle, alignment: { wrapText: true } });
  }

  // A rule under the title block, in brand teal.
  ["B6", "C6"].forEach(address => {
    writeCell(sheet, address, "", { fill: WORKBOOK_COLORS.primary });
  });
  sheet.getRow(6).height = 3;

  let row = 8;
  if (headline) {
    sheet.mergeCells(`B${row}:C${row + 2}`);
    writeCell(sheet, `B${row}`, headline, {
      font: { ...WORKBOOK_FONTS.body, size: 12 },
      fill: WORKBOOK_COLORS.primarySoft,
      border: boxBorder(WORKBOOK_COLORS.border),
      alignment: { vertical: "top", wrapText: true }
    });
    sheet.getRow(row).height = 22;
    sheet.getRow(row + 1).height = 22;
    sheet.getRow(row + 2).height = 22;
    row += 4;
  }

  facts.filter(Boolean).forEach(([label, value]) => {
    writeCell(sheet, `B${row}`, label, { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
    // Left-align explicitly: Excel right-aligns numbers by default, which would
    // strand a bare count at the far edge of a wide column, disconnected from
    // the label it belongs to.
    writeCell(sheet, `C${row}`, value ?? "", {
      font: WORKBOOK_FONTS.body,
      alignment: { vertical: "top", horizontal: "left", wrapText: true }
    });
    row += 1;
  });

  row += 1;
  [...notices, REPORTING_BIBLE_POLICY.exportPrivacy.confidentialityBanner,
    REPORTING_BIBLE_POLICY.exportPrivacy.releaseNotice]
    .filter(Boolean)
    .forEach(notice => {
      sheet.mergeCells(`B${row}:C${row}`);
      writeCell(sheet, `B${row}`, notice, {
        font: WORKBOOK_FONTS.banner,
        alignment: { vertical: "top", wrapText: true }
      });
      sheet.getRow(row).height = Math.max(14, Math.ceil(String(notice).length / 95) * 12);
      row += 1;
    });

  sheet.views = [{ showGridLines: false }];
  applyPrintSetup(sheet, { titleForFooter: title });
  return sheet;
}

/* ------------------------------------------------------------------ *
 * KPI band and status split
 * ------------------------------------------------------------------ */

const KPI_TONES = Object.freeze({
  neutral: { fill: WORKBOOK_COLORS.surfaceSubtle, edge: WORKBOOK_COLORS.border, text: WORKBOOK_COLORS.inkStrong },
  brand: { fill: WORKBOOK_COLORS.primarySoft, edge: WORKBOOK_COLORS.primary, text: WORKBOOK_COLORS.primaryStrong },
  secure: { fill: WORKBOOK_COLORS.secureFill, edge: WORKBOOK_COLORS.secureEdge, text: WORKBOOK_COLORS.secureText },
  developing: { fill: WORKBOOK_COLORS.developingFill, edge: WORKBOOK_COLORS.developingEdge, text: WORKBOOK_COLORS.developingText },
  needs_support: { fill: WORKBOOK_COLORS.needsSupportFill, edge: WORKBOOK_COLORS.needsSupportEdge, text: WORKBOOK_COLORS.needsSupportText },
  mixed_evidence: { fill: WORKBOOK_COLORS.mixedFill, edge: WORKBOOK_COLORS.mixedEdge, text: WORKBOOK_COLORS.mixedText },
  not_enough_evidence: { fill: WORKBOOK_COLORS.neutralFill, edge: WORKBOOK_COLORS.neutralEdge, text: WORKBOOK_COLORS.neutralText },
  not_checked: { fill: WORKBOOK_COLORS.neutralFill, edge: WORKBOOK_COLORS.neutralEdge, text: WORKBOOK_COLORS.neutralText }
});

/**
 * A row of metric cards, each spanning two columns and three rows — the
 * screen's `.simple-report-summary` in cells.
 *
 * A card whose `value` is null renders "Not enough results", never 0.
 */
export function addKpiBand(sheet, startRow, cards = [], { columnsPerCard = 2, startColumn = 2 } = {}) {
  const usable = cards.filter(Boolean).slice(0, 6);
  usable.forEach((card, index) => {
    const first = startColumn + index * columnsPerCard;
    const last = first + columnsPerCard - 1;
    const tone = KPI_TONES[card.tone] || KPI_TONES.neutral;
    const colLetter = n => sheet.getColumn(n).letter;

    sheet.mergeCells(`${colLetter(first)}${startRow}:${colLetter(last)}${startRow}`);
    writeCell(sheet, `${colLetter(first)}${startRow}`, String(card.label || "").toUpperCase(), {
      font: { ...WORKBOOK_FONTS.kpiLabel, color: { argb: tone.text } },
      fill: tone.fill,
      border: { top: thin(tone.edge), left: thin(tone.edge), right: thin(tone.edge) },
      alignment: { vertical: "middle", horizontal: "left", indent: 1 }
    });

    sheet.mergeCells(`${colLetter(first)}${startRow + 1}:${colLetter(last)}${startRow + 1}`);
    const hasValue = card.value !== null && card.value !== undefined && card.value !== "";
    const valueCell = writeCell(
      sheet,
      `${colLetter(first)}${startRow + 1}`,
      hasValue ? card.value : "Not enough results",
      {
        font: hasValue
          ? { ...WORKBOOK_FONTS.kpiValue, color: { argb: tone.text } }
          : { ...WORKBOOK_FONTS.bodyMuted, italic: true },
        fill: tone.fill,
        border: { left: thin(tone.edge), right: thin(tone.edge) },
        alignment: { vertical: "middle", horizontal: "left", indent: 1 }
      }
    );
    if (hasValue && card.numFmt) valueCell.numFmt = card.numFmt;

    sheet.mergeCells(`${colLetter(first)}${startRow + 2}:${colLetter(last)}${startRow + 2}`);
    writeCell(sheet, `${colLetter(first)}${startRow + 2}`, card.note || "", {
      font: WORKBOOK_FONTS.kpiNote,
      fill: tone.fill,
      border: { bottom: thin(tone.edge), left: thin(tone.edge), right: thin(tone.edge) },
      alignment: { vertical: "top", horizontal: "left", indent: 1, wrapText: true }
    });
  });

  sheet.getRow(startRow).height = 16;
  sheet.getRow(startRow + 1).height = 30;
  sheet.getRow(startRow + 2).height = 26;
  return startRow + 4;
}

/**
 * The five/six-way status split, in the bible's order, with the reconcile line
 * beneath. `counts` is keyed by any status alias; it is canonicalised here.
 */
export function addStatusSplit(sheet, startRow, counts = {}, { reconcileLine = "", startColumn = 2 } = {}) {
  const normalised = {};
  Object.entries(counts).forEach(([key, value]) => {
    const id = canonicalStatusId(key);
    normalised[id] = (normalised[id] || 0) + (Number(value) || 0);
  });
  const cards = REPORT_STATUS_ORDER.filter(
    id => normalised[id] !== undefined || id !== "mixed_evidence"
  ).map(id => ({
    label: REPORT_STATUS_LABELS[id],
    value: normalised[id] || 0,
    note: REPORT_STATUS_NOTES[id],
    tone: id,
    numFmt: NUMBER_FORMATS.integer
  }));

  let row = addKpiBand(sheet, startRow, cards, { columnsPerCard: 2, startColumn });
  if (reconcileLine) {
    const colLetter = n => sheet.getColumn(n).letter;
    sheet.mergeCells(`${colLetter(startColumn)}${row}:${colLetter(startColumn + 11)}${row}`);
    writeCell(sheet, `${colLetter(startColumn)}${row}`, reconcileLine, {
      font: WORKBOOK_FONTS.bodyMuted,
      alignment: { vertical: "middle", wrapText: true }
    });
    row += 2;
  }
  return row;
}

/* ------------------------------------------------------------------ *
 * Section headings
 * ------------------------------------------------------------------ */

export function addSectionHeading(sheet, row, title, help = "", { startColumn = 2, span = 12 } = {}) {
  const colLetter = n => sheet.getColumn(n).letter;
  sheet.mergeCells(`${colLetter(startColumn)}${row}:${colLetter(startColumn + span - 1)}${row}`);
  writeCell(sheet, `${colLetter(startColumn)}${row}`, title, {
    font: WORKBOOK_FONTS.sectionTitle,
    alignment: { vertical: "middle" }
  });
  sheet.getRow(row).height = 22;
  let next = row + 1;
  if (help) {
    sheet.mergeCells(`${colLetter(startColumn)}${next}:${colLetter(startColumn + span - 1)}${next}`);
    writeCell(sheet, `${colLetter(startColumn)}${next}`, help, {
      font: WORKBOOK_FONTS.sectionHelp,
      alignment: { vertical: "top", wrapText: true }
    });
    sheet.getRow(next).height = Math.max(15, Math.ceil(String(help).length / 110) * 14);
    next += 1;
  }
  return next + 1;
}

/* ------------------------------------------------------------------ *
 * Tables
 * ------------------------------------------------------------------ */

/**
 * Numeric columns are right-aligned with a one-character indent. Without the
 * indent a narrow count column pushes its digits flush against the next
 * column's text, and "3" beside "Multisensory ch/sh/th sort" reads as one value.
 */
function numericColumn(column) {
  return column?.type === "number" || column?.type === "percent";
}

/**
 * Column spec:
 *   { key, header, width?, type?, wrap?, note? }
 *   type: "text" | "number" | "percent" | "date" | "status" | "fraction"
 *
 * `type: "status"` colours the cell from the canonical status id and prefixes
 * the mark glyph, so the sheet still reads in greyscale.
 *
 * Widths are computed from actual content when not given, capped at 60 —
 * ExcelJS will not autofit, and 29 columns of default width is why the old
 * exports were unreadable without ten minutes of dragging.
 */
export function addTable(sheet, startRow, columns = [], rows = [], {
  startColumn = 2,
  zebra = true,
  autoFilter = true,
  freezeHeader = true,
  freezeFirstColumn = false,
  emptyMessage = "No results yet.",
  totalRow = null
} = {}) {
  const colLetter = n => sheet.getColumn(n).letter;
  const headerRow = startRow;

  columns.forEach((column, index) => {
    const position = startColumn + index;
    const cell = writeCell(sheet, `${colLetter(position)}${headerRow}`, column.header, {
      font: WORKBOOK_FONTS.tableHeader,
      fill: WORKBOOK_COLORS.primaryStrong,
      alignment: numericColumn(column)
        ? { vertical: "middle", horizontal: "right", indent: 1, wrapText: true }
        : { vertical: "middle", horizontal: "left", indent: 1, wrapText: true },
      border: { bottom: thin(WORKBOOK_COLORS.primary) }
    });
    if (column.note) cell.note = column.note;

    const contentWidth = rows.reduce((widest, row) => {
      const value = row?.[column.key];
      const text = value === null || value === undefined ? "" : String(value);
      return Math.max(widest, Math.min(text.length, column.wrap ? 44 : 60));
    }, String(column.header).length);
    sheet.getColumn(position).width =
      column.width || Math.max(numericColumn(column) ? 14 : 10, Math.min(60, contentWidth + 3));
  });
  sheet.getRow(headerRow).height = 26;

  if (!rows.length) {
    sheet.mergeCells(
      `${colLetter(startColumn)}${headerRow + 1}:${colLetter(startColumn + Math.max(0, columns.length - 1))}${headerRow + 1}`
    );
    writeCell(sheet, `${colLetter(startColumn)}${headerRow + 1}`, emptyMessage, {
      font: { ...WORKBOOK_FONTS.bodyMuted, italic: true },
      alignment: { vertical: "middle", wrapText: true }
    });
    return { headerRow, firstDataRow: headerRow + 1, lastRow: headerRow + 1, nextRow: headerRow + 3 };
  }

  rows.forEach((row, rowIndex) => {
    const excelRow = headerRow + 1 + rowIndex;
    const striped = zebra && rowIndex % 2 === 1;
    columns.forEach((column, index) => {
      const position = startColumn + index;
      const raw = row?.[column.key];
      const style = {
        font: WORKBOOK_FONTS.body,
        alignment: numericColumn(column)
          ? { vertical: "top", horizontal: "right", indent: 1 }
          : { vertical: "top", horizontal: "left", indent: 1, wrapText: Boolean(column.wrap) },
        border: { bottom: thin(WORKBOOK_COLORS.border) }
      };
      if (striped) style.fill = WORKBOOK_COLORS.surfaceSubtle;

      let value = raw;
      if (column.type === "number") {
        value = numberOrBlank(raw);
        style.numFmt = column.numFmt || NUMBER_FORMATS.integer;
      } else if (column.type === "percent") {
        value = percentOrBlank(raw);
        style.numFmt = column.numFmt || NUMBER_FORMATS.percent;
      } else if (column.type === "date") {
        value = dateOrBlank(raw);
      } else if (column.type === "status") {
        const id = canonicalStatusId(raw);
        const treatment = statusCellStyle(id);
        value = `${treatment.mark}  ${reportStatusLabel(id)}`;
        style.fill = treatment.fill;
        style.font = { ...WORKBOOK_FONTS.body, bold: true, color: { argb: treatment.font } };
        style.border = { ...style.border, ...boxBorder(treatment.edge) };
      } else if (value === null || value === undefined) {
        value = "";
      }
      writeCell(sheet, `${colLetter(position)}${excelRow}`, value, style);
    });
    if (columns.some(column => column.wrap)) {
      const longest = columns
        .filter(column => column.wrap)
        .reduce((max, column) => Math.max(max, String(row?.[column.key] ?? "").length), 0);
      const width = columns.find(column => column.wrap)?.width || 44;
      sheet.getRow(excelRow).height = Math.max(18, Math.min(90, Math.ceil(longest / width) * 13 + 5));
    }
  });

  const lastRow = headerRow + rows.length;
  let nextRow = lastRow + 1;

  if (totalRow) {
    columns.forEach((column, index) => {
      const position = startColumn + index;
      const raw = totalRow[column.key];
      const style = {
        font: { ...WORKBOOK_FONTS.body, bold: true },
        fill: WORKBOOK_COLORS.primarySoft,
        alignment: numericColumn(column)
          ? { vertical: "middle", horizontal: "right", indent: 1 }
          : { vertical: "middle", horizontal: "left", indent: 1 },
        border: { top: thin(WORKBOOK_COLORS.primary), bottom: thin(WORKBOOK_COLORS.primary) }
      };
      let value = raw ?? "";
      if (column.type === "number") {
        value = numberOrBlank(raw);
        style.numFmt = column.numFmt || NUMBER_FORMATS.integer;
      } else if (column.type === "percent") {
        value = percentOrBlank(raw);
        style.numFmt = column.numFmt || NUMBER_FORMATS.percent;
      }
      writeCell(sheet, `${colLetter(position)}${nextRow}`, value, style);
    });
    nextRow += 1;
  }

  if (autoFilter) {
    sheet.autoFilter = {
      from: { row: headerRow, column: startColumn },
      to: { row: lastRow, column: startColumn + columns.length - 1 }
    };
  }
  if (freezeHeader) {
    sheet.views = [{
      state: "frozen",
      ySplit: headerRow,
      xSplit: freezeFirstColumn ? startColumn : 0,
      showGridLines: false
    }];
  }

  return { headerRow, firstDataRow: headerRow + 1, lastRow, nextRow: nextRow + 1 };
}

/* ------------------------------------------------------------------ *
 * Matrix / heatmap
 * ------------------------------------------------------------------ */

/**
 * A students × skills grid. Cells carry the status mark and are coloured from
 * the canonical status id — never from a percentage, because the band comes
 * from status, not accuracy, and a 100%-accuracy cell can legitimately be
 * neutral (see `simpleStudentReports.js` and the bible, Part X.3).
 *
 * The row header column is frozen so a teacher can scroll a wide matrix and
 * still see who each row is.
 */
export function addStatusMatrix(sheet, startRow, {
  rowHeader = "Student",
  columnHeaders = [],
  rows = [],
  startColumn = 2,
  emptyMessage = "No results yet.",
  // Long headers print on the diagonal, which is the only way a thirty-column
  // class matrix fits a page. With a handful of columns it just looks broken —
  // and worse, a 12-character header sits flat immediately beside a
  // 13-character one standing on its end. Callers with few columns raise this.
  rotateHeadersOver = 12,
  columnWidth = 13
} = {}) {
  const colLetter = n => sheet.getColumn(n).letter;
  const rotates = header => String(header).length > rotateHeadersOver;

  writeCell(sheet, `${colLetter(startColumn)}${startRow}`, rowHeader, {
    font: WORKBOOK_FONTS.tableHeader,
    fill: WORKBOOK_COLORS.primaryStrong,
    alignment: { vertical: "middle", wrapText: true }
  });
  sheet.getColumn(startColumn).width = Math.max(
    18,
    Math.min(34, rows.reduce((widest, row) => Math.max(widest, String(row.label || "").length), rowHeader.length) + 2)
  );

  // ALL OR NONE. Deciding per header meant "Short a CVC" lay flat beside
  // "Letter sounds a-m" standing on its end in the same row, which reads as a
  // rendering fault rather than a space-saving choice. One long name is enough
  // to tip the whole header row onto the diagonal.
  const anyRotates = columnHeaders.some(rotates);

  columnHeaders.forEach((header, index) => {
    const position = startColumn + 1 + index;
    writeCell(sheet, `${colLetter(position)}${startRow}`, header, {
      font: WORKBOOK_FONTS.tableHeader,
      fill: WORKBOOK_COLORS.primaryStrong,
      alignment: { vertical: "bottom", horizontal: "center", wrapText: true, textRotation: anyRotates ? 60 : 0 }
    });
    sheet.getColumn(position).width = Math.max(
      columnWidth,
      anyRotates ? columnWidth : String(header).length + 2
    );
  });
  sheet.getRow(startRow).height = anyRotates ? 74 : 28;

  if (!rows.length) {
    writeCell(sheet, `${colLetter(startColumn)}${startRow + 1}`, emptyMessage, {
      font: { ...WORKBOOK_FONTS.bodyMuted, italic: true }
    });
    return startRow + 3;
  }

  rows.forEach((row, rowIndex) => {
    const excelRow = startRow + 1 + rowIndex;
    writeCell(sheet, `${colLetter(startColumn)}${excelRow}`, row.label ?? "", {
      font: { ...WORKBOOK_FONTS.body, bold: true },
      fill: rowIndex % 2 ? WORKBOOK_COLORS.surfaceSubtle : undefined,
      alignment: { vertical: "middle" },
      border: { bottom: thin(WORKBOOK_COLORS.border) }
    });
    (row.cells || []).forEach((cellValue, index) => {
      const position = startColumn + 1 + index;
      const id = canonicalStatusId(cellValue?.status ?? cellValue);
      const treatment = statusCellStyle(id);
      const cell = writeCell(sheet, `${colLetter(position)}${excelRow}`, treatment.mark, {
        font: { ...WORKBOOK_FONTS.body, bold: true, size: 12, color: { argb: treatment.font } },
        fill: treatment.fill,
        alignment: { vertical: "middle", horizontal: "center" },
        border: boxBorder(treatment.edge)
      });
      const detail = cellValue?.note || cellValue?.detail;
      cell.note = detail
        ? `${reportStatusLabel(id)} — ${detail}`
        : reportStatusLabel(id);
    });
    sheet.getRow(excelRow).height = 20;
  });

  sheet.views = [{ state: "frozen", ySplit: startRow, xSplit: startColumn, showGridLines: false }];
  return startRow + rows.length + 3;
}

/**
 * A numeric heatmap with a real Excel three-colour scale, for anything that IS
 * legitimately continuous (coverage percentages, counts). Never used for status.
 */
export function addNumericHeatmap(sheet, { firstRow, lastRow, firstColumn, lastColumn, reverse = false }) {
  const colLetter = n => sheet.getColumn(n).letter;
  const ref = `${colLetter(firstColumn)}${firstRow}:${colLetter(lastColumn)}${lastRow}`;
  const low = reverse ? WORKBOOK_COLORS.secureFill : WORKBOOK_COLORS.needsSupportFill;
  const high = reverse ? WORKBOOK_COLORS.needsSupportFill : WORKBOOK_COLORS.secureFill;
  sheet.addConditionalFormatting({
    ref,
    rules: [{
      type: "colorScale",
      priority: 1,
      cfvo: [{ type: "min" }, { type: "percentile", value: 50 }, { type: "max" }],
      color: [{ argb: low }, { argb: WORKBOOK_COLORS.developingFill }, { argb: high }]
    }]
  });
  return ref;
}

/* ------------------------------------------------------------------ *
 * "How to read this" — the interpretive guide, in the file
 * ------------------------------------------------------------------ */

/**
 * Hambleton & Zenisky: supporting material is the field's weakest domain, and
 * the fix is a standalone interpretive guide under four pages — not an
 * 80-page manual, not a help-centre article. This sheet is that guide, shipped
 * inside the artefact it explains so it cannot be separated from it.
 */
export function addHowToReadSheet(workbook, {
  metricRows = [],
  extraNotes = [],
  taken
} = {}) {
  const sheet = addSheet(workbook, SHEET_NAMES.HOW_TO_READ, { tabColor: WORKBOOK_COLORS.slate, taken });
  sheet.columns = [{ width: 3 }, { width: 26 }, { width: 74 }, { width: 3 }];

  let row = 2;
  row = addSectionHeading(sheet, row, "How to read this workbook", "", { span: 2 });

  const principles = [
    ["Missing is not zero", STANDING_NOTICES.missingIsNotZero],
    ["Accuracy is not mastery", STANDING_NOTICES.accuracyIsNotMastery],
    ["This is not a diagnosis", STANDING_NOTICES.screeningIsNotDiagnosis],
    ["Asking for an evaluation", STANDING_NOTICES.rtiEvaluationRight]
  ];
  principles.forEach(([label, text]) => {
    writeCell(sheet, `B${row}`, label, { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
    writeCell(sheet, `C${row}`, text, {
      font: WORKBOOK_FONTS.body,
      alignment: { vertical: "top", wrapText: true }
    });
    sheet.getRow(row).height = Math.max(16, Math.ceil(text.length / 88) * 14);
    row += 1;
  });

  row += 1;
  row = addSectionHeading(sheet, row, "What each status means", "", { span: 2 });
  statusLegendRows().forEach(entry => {
    const treatment = statusCellStyle(entry.statusId);
    writeCell(sheet, `B${row}`, `${entry.mark}  ${entry.label}`, {
      font: { ...WORKBOOK_FONTS.body, bold: true, color: { argb: treatment.font } },
      fill: treatment.fill,
      border: boxBorder(treatment.edge),
      alignment: { vertical: "middle" }
    });
    writeCell(sheet, `C${row}`, REPORT_STATUS_NOTES[entry.statusId], {
      font: WORKBOOK_FONTS.body,
      alignment: { vertical: "middle", wrapText: true }
    });
    row += 1;
  });

  row += 1;
  row = addSectionHeading(sheet, row, "What Secure means here", "", { span: 2 });
  const gates = evaluateMasteryGates({});
  writeCell(sheet, `B${row}`, "The rule", { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
  writeCell(sheet, `C${row}`, gates.summary, {
    font: WORKBOOK_FONTS.body,
    alignment: { vertical: "top", wrapText: true }
  });
  row += 1;
  gates.gates.forEach((gate, index) => {
    writeCell(sheet, `B${row}`, `Gate ${index + 1}`, { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
    writeCell(sheet, `C${row}`, gate.label, { font: WORKBOOK_FONTS.body, alignment: { vertical: "top", wrapText: true } });
    row += 1;
  });
  writeCell(sheet, `B${row}`, "Why 90%", { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
  writeCell(
    sheet,
    `C${row}`,
    "Children who reach 90% at the time of learning still hold about 88% of it three to four weeks later. At 80% they hold about 69%. The extra ten points is the difference between learning that lasts and learning that fades.",
    { font: WORKBOOK_FONTS.body, alignment: { vertical: "top", wrapText: true } }
  );
  sheet.getRow(row).height = 42;
  row += 2;

  row = addSectionHeading(sheet, row, "Why some skills show no judgement", "", { span: 2 });
  writeCell(sheet, `B${row}`, "The rule", { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top" } });
  writeCell(
    sheet,
    `C${row}`,
    `A skill needs at least ${REPORTING_BIBLE_POLICY.evidenceSufficiency.judgementMinimumScoredItems} scored items before this report will call it Secure, Developing or Needs support, and ${REPORTING_BIBLE_POLICY.evidenceSufficiency.confidentMinimumScoredItems} before the judgement is treated as confident. Below that the honest answer is "Not enough results" — a handful of items cannot tell you what a child knows, however tempting the percentage looks.`,
    { font: WORKBOOK_FONTS.body, alignment: { vertical: "top", wrapText: true } }
  );
  sheet.getRow(row).height = 56;
  row += 2;

  if (metricRows.length) {
    row = addSectionHeading(sheet, row, "Measures used in this workbook", "", { span: 2 });
    metricRows.forEach(metric => {
      writeCell(sheet, `B${row}`, metric.label || metric.field || "", {
        font: WORKBOOK_FONTS.kpiLabel,
        alignment: { vertical: "top", wrapText: true }
      });
      writeCell(sheet, `C${row}`, metric.definition || metric.value || "", {
        font: WORKBOOK_FONTS.body,
        alignment: { vertical: "top", wrapText: true }
      });
      sheet.getRow(row).height = Math.max(16, Math.ceil(String(metric.definition || metric.value || "").length / 88) * 14);
      row += 1;
    });
    row += 1;
  }

  extraNotes.filter(Boolean).forEach(note => {
    sheet.mergeCells(`B${row}:C${row}`);
    writeCell(sheet, `B${row}`, note, {
      font: WORKBOOK_FONTS.banner,
      alignment: { vertical: "top", wrapText: true }
    });
    sheet.getRow(row).height = Math.max(14, Math.ceil(String(note).length / 100) * 12);
    row += 1;
  });

  applyPrintSetup(sheet, { titleForFooter: "How to read this workbook" });
  return sheet;
}

/* ------------------------------------------------------------------ *
 * Provenance
 * ------------------------------------------------------------------ */

export function addProvenanceSheet(workbook, rows = [], { taken, extraNotes = [] } = {}) {
  const sheet = addSheet(workbook, SHEET_NAMES.PROVENANCE, { tabColor: WORKBOOK_COLORS.slate, taken });
  sheet.columns = [{ width: 3 }, { width: 34 }, { width: 66 }, { width: 3 }];
  let row = 2;
  row = addSectionHeading(
    sheet,
    row,
    "About this report",
    "Where the results came from, when they were read, and which versions produced them.",
    { span: 2 }
  );
  (rows || []).forEach(entry => {
    const label = entry?.field ?? entry?.label ?? "";
    const value = entry?.value ?? "";
    writeCell(sheet, `B${row}`, label, { font: WORKBOOK_FONTS.kpiLabel, alignment: { vertical: "top", wrapText: true } });
    writeCell(sheet, `C${row}`, value, { font: WORKBOOK_FONTS.body, alignment: { vertical: "top", wrapText: true } });
    sheet.getRow(row).height = Math.max(16, Math.ceil(String(value).length / 80) * 14);
    row += 1;
  });
  row += 1;
  [`Reporting policy: ${REPORTING_BIBLE_VERSION}`, ...extraNotes].filter(Boolean).forEach(note => {
    sheet.mergeCells(`B${row}:C${row}`);
    writeCell(sheet, `B${row}`, note, { font: WORKBOOK_FONTS.banner, alignment: { vertical: "top", wrapText: true } });
    row += 1;
  });
  applyPrintSetup(sheet, { titleForFooter: "About this report" });
  return sheet;
}

/* ------------------------------------------------------------------ *
 * Long-format data sheet
 * ------------------------------------------------------------------ */

/**
 * The machine-readable sheet. Long format, one row per student per skill per
 * window, code and label both, denominator always present, and an explicit
 * evidence-sufficiency column — the bible's Part X.4. Teachers pivot this; they
 * do not parse the pretty sheets.
 */
export function addDataSheet(workbook, columns = [], rows = [], { taken, sheetName = SHEET_NAMES.DATA } = {}) {
  const sheet = addSheet(workbook, sheetName, { tabColor: WORKBOOK_COLORS.slate, taken });
  sheet.columns = [{ width: 2 }];
  addTable(sheet, 1, columns, rows, {
    startColumn: 2,
    zebra: false,
    autoFilter: true,
    freezeHeader: true,
    emptyMessage: "No rows. Nothing has been assessed in this scope yet."
  });
  applyPrintSetup(sheet, { landscape: true, repeatHeaderRow: 1, titleForFooter: sheetName });
  return sheet;
}

/* ------------------------------------------------------------------ *
 * Output
 * ------------------------------------------------------------------ */

export async function workbookToBuffer(workbook) {
  return workbook.xlsx.writeBuffer();
}

export async function downloadWorkbook(workbook, fileName) {
  const buffer = await workbookToBuffer(workbook);
  if (typeof document === "undefined" || typeof URL?.createObjectURL !== "function") {
    return buffer;
  }
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
  return buffer;
}

/**
 * Put the sheets in reading order regardless of the order they were built in.
 * ExcelJS orders by insertion; report builders often create detail sheets while
 * they still have the data in hand.
 */
export function orderSheets(workbook, preferredOrder = []) {
  const order = new Map(preferredOrder.map((name, index) => [name, index]));
  workbook.worksheets
    .slice()
    .sort((a, b) => {
      const aOrder = order.has(a.name) ? order.get(a.name) : 500;
      const bOrder = order.has(b.name) ? order.get(b.name) : 500;
      return aOrder - bOrder;
    })
    .forEach((sheet, index) => {
      sheet.orderNo = index + 1;
    });
}
