// Current contracts for the nine illustrated practice games in the Arcade.
// These remain supported practice; movement and eventual success are not placement evidence.
const records = {
  "cvc-word-builder": ["build", "Ordered grapheme construction with a printed and pictured word model", "Build a useful object", "Tap the next sound tile; Undo reverses the last choice.", "Easy uses reviewed CVC objects; medium and hard introduce reviewed clusters and letter teams.", "Current Meadow/Dino/Moonwood hero in a foreground workbench", "building"],
  "blend-and-build": ["family", "Supported onset/rime blending within authored sound families", "Fill a collection of pictured words", "Tap an onset to join the retained rime.", "Easy CVC families, medium digraph/cluster onsets, hard longer clusters/rimes; actual family lengths bound each outing.", "Current world hero beside a collection of built objects", "building"],
  "letter-garden": ["garden", "One changed written grapheme in a pictured and printed word contrast", "Grow a flower by changing one letter", "Tap one seed for the marked letter while all other letters remain.", "26 distinct directed contrasts per tier; later tiers use longer words, clusters and vowel teams.", "Woolly in the owned meadow garden", "building"],
  "sight-word-memory": ["memory", "Supported printed word pairing and spatial recall", "Light Luna’s four lanterns", "Turn two opaque cards and match their printed words.", "Retain the reviewed four-pair curriculum boards and saved board progression; no mastery claim from memory alone.", "Canonical Luna and a woodland lantern table", "recognition"],
  "word-rescue": ["rescue", "Printed word recognition against a recorded or printed target", "Build bridges for Splashy", "Select the matching word plank; Speedy carries it automatically.", "Retain reviewed difficulty banks and six six-plank bridges, without a carrying accuracy gate.", "Canonical Speedy and Splashy on an illustrated riverbank", "recognition"],
  "pop-the-word": ["target", "Supported high-frequency word recognition", "Help Chompy’s balloon festival", "Tap the target word on one of six stationary balloons.", "16/20/24-word seeded fresh outings by tier; optional gentle motion never changes literacy demand.", "Canonical Chompy in an illustrated balloon festival", "recognition"],
  "word-hopscotch": ["sentence", "Supported sentence word order using a complete printed model", "Hop across a sentence", "Choose the next word from a unique bounded bank.", "Shorter to longer reviewed sentence models across tiers; reached words remain in order and only the next hop is an answer.", "Current world hero follows reached stepping stones", "sentences"],
  "reading-race": ["quiz", "Supported capital, punctuation, grammar and meaningful sentence repair", "Repair the forest sign", "Tap a repair piece once; the substituted sentence and its context determine acceptance.", "Reviewed tier-specific repairs; accepted alternatives retained and semantically ambiguous items have explicit story facts.", "Canonical Luna beside a readable forest sign", "sentences"],
  "sound-sort-factory": ["sort", "Supported first written grapheme sorting; not isolated-phoneme evidence", "Sort parcels into the matching chutes", "Tap the chute matching the parcel’s first letters.", "16/24/32 seeded parcels from 4/6/8 contrasts; both bins represented and later tiers retain digraph contrasts.", "Canonical Chompy beside the owned conveyor factory scene", "sentences"]
};
const unitFiles = {
  building: "tests/unit/phonicsBuildingOverhaul.test.js",
  recognition: "tests/unit/recognitionPractice.test.js",
  sentences: "tests/unit/sentenceWorkshopOverhaul.test.js"
};
const browserFiles = {
  building: "tests/release/phonics-building-overhaul.spec.js",
  recognition: "tests/release/phonics-recognition-overhaul.spec.js",
  sentences: "tests/release/phonics-sentence-worlds.spec.js"
};
export const PHONICS_PRACTICE_BRIEFS = Object.fromEntries(Object.entries(records).map(([id, [mode, construct, goal, action, ladder, character, group]]) => [id, {
  schemaVersion: 1, gameId: id, version: "practice-2",
  audience: "Early learners practising the chosen difficulty with recorded cues and explicit printed/pictured support.",
  experiencePromise: goal,
  learning: { targetConstruct: construct, childGoal: goal, integratedAction: action, nonTargetDemands: "No compulsory timing, carrying, steering, dragging or confirmation gate.", evidenceEvent: "Keep first responses, errors and supported retries in the existing practice record; all remain practiceOnly with independent false.", movementCreatesEvidence: false },
  loop: { onboard: "The shared player shows the current seeded outing and visible controls.", perceive: "Read or replay the complete target while every available answer stays legible.", act: action, feedback: "Correct answers change the world immediately, then advance after the owned result dwell.", retry: "Retain the target and completed work; explain the actual chosen contrast and allow another response.", complete: "The existing player saves one result receipt and offers Next, Replay and Back to Arcade." },
  prompt: { visible: construct, spoken: "Existing owned LEDA word/sentence cues only, with the player sound preference.", replay: "Hear remains retryable after autoplay rejection; missing recordings expose printed support without synthetic speech." },
  controls: { keyboard: ["Tab to named choices; Enter or Space answers.", "Shared Pause and Exit remain available."], touch: ["Tap the complete 56px or larger answer; no motor follow-up is required."], minimumTargetCssPixels: 56, pointerReleaseEvents: ["pointerup", "pointercancel", "lostpointercapture"] },
  difficulty: { curriculumBeforePressure: true, ladder },
  gameFeel: { movement: "World changes follow a settled literacy choice and never create evidence.", forgiveness: ["Untimed answers", "Specific retry preserves completed work", "Pause freezes result clocks"], camera: "One bounded illustrated playfield keeps the target and current choices visible.", successFeedback: "A built object, grown flower, lit lantern, placed plank, popped balloon or reached word/sign records the actual response.", errorFeedback: "Feedback names the selected word, spelling, punctuation or contrast; it cannot silently reject a valid alternative." },
  world: { artDirection: "Retained owned scenery, canonical transparent cast and opaque foreground literacy props.", route: goal, character, assetFallback: "Missing decoration preserves the readable target, native choices and specific feedback." },
  state: { pauseResume: "Shared engine pause freezes result dwell and input; gesture replay remains usable.", checkpoint: "Retain the exact seeded deck, partial first question, response support and accepted result phase; legacy saved decks retain their original lengths.", completion: "Commit one existing practice receipt; accepted-result reload cannot score or complete twice." },
  accessibility: { reducedMotion: "Decorative movement is reduced or frozen; choices stay usable.", soundOff: "Printed/pictured target and specific feedback remain available, without an independent listening claim.", nonColourCue: "Words, ticks, shapes, marked slots and actual world changes supplement colour.", semanticFallback: "Native named controls expose the complete interaction outside decorative scenery." },
  performance: { lowPowerFallback: "Compact owned WebP scenes and native DOM controls avoid a new heavy renderer.", inputSafety: "Direct buttons need no held movement; pause, cancel and unmount stop owned clocks and audio.", assetFailure: "Failed decoration never removes targets or choices; failed audio can be retried with printed support." },
  privacy: { dataWritten: ["Existing score, stars, completed count and supported practice evidence", "Existing scoped seeded checkpoint and local stage envelope"], network: ["Same-origin owned artwork/audio and existing progress sync only"], newIdentifier: false, newExternalService: false },
  validation: { unit: [unitFiles[group], "tests/unit/phonicsCheckpointContinuity.test.js"], browser: [browserFiles[group], "tests/release/recognition-practice.spec.js"], physicalDevice: { status: "unknown", note: "Chromium/WebKit device-sized play and screenshots are not physical iPad or classroom observation." } },
  mode
}]));
