import { assessmentReleaseStandard } from "../src/content/releaseStandard.js";
import { auditStrictProductionReadiness } from "./auditAllSkillsStrictProductionReadiness.js";

export function buildAssessmentReleaseStatus() {
  const report = auditStrictProductionReadiness();
  return report.perSkill.map(skill => {
    return {
      skillId: skill.skillId,
      skillName: skill.skillName,
      standardVersion: skill.releaseStandardDecision.standardVersion,
      releaseReady: skill.releaseStandardDecision.releaseReady,
      dimensions: skill.releaseStandardDecision.dimensions,
      reasons: skill.releaseStandardDecision.reasons,
      authoredQuestions: skill.rawQuestionCount,
      approvedQuestions: skill.strictCandidateQuestionCount,
      runtimeSelectableQuestions: skill.releaseStandardDecision.releaseReady
        ? skill.strictUsableQuestionCount
        : 0,
      releaseEligibleQuestions: skill.strictUsableQuestionCount,
      unapprovedAudioQuestions: skill.unapprovedAudioQuestionCount,
      publicationMode: "audited-id-set",
      publishedQuestionIds: skill.strictUsableQuestionIds,
      publishedQuestions: skill.publishedQuestions,
      levels: skill.releaseStandardDecision.levels,
      accessibilityIssueCount: skill.accessibilityIssueCount,
      missingRequiredImages: skill.missingImageCount,
      missingRequiredAudio: skill.missingAudioCount,
      wiringDefects: skill.mediaWiringFixCount
    };
  });
}

export async function buildRuntimeAlignedAssessmentReleaseStatus() {
  const statuses = buildAssessmentReleaseStatus();
  const { loadAssessmentSkillBankCandidates } = await import(
    "../src/data/loadAssessmentSkillBank.js"
  );
  return Promise.all(statuses.map(async status => {
    const candidates = await loadAssessmentSkillBankCandidates(status.skillId);
    const candidateIds = new Set(
      candidates.map(question => String(question.id || question.questionId || ""))
    );
    const missingPublished = status.publishedQuestions.filter(
      question => !candidateIds.has(String(question.questionId || ""))
    );
    const runtimeAligned = missingPublished.length === 0;
    const releaseReady = status.releaseReady && runtimeAligned;
    return {
      ...status,
      releaseReady,
      dimensions: {
        ...status.dimensions,
        runtimeSelectability: status.releaseReady
          ? runtimeAligned ? "pass" : "fail"
          : "blocked"
      },
      reasons: [
        ...status.reasons,
        ...(status.releaseReady && !runtimeAligned
          ? [
              `Live student bank is missing ${missingPublished.length} of `
              + `${status.publishedQuestions.length} canonically approved questions.`
            ]
          : [])
      ],
      runtimeSelectableQuestions: releaseReady ? status.releaseEligibleQuestions : 0
    };
  }));
}

export function renderAssessmentReleaseStatus(statuses = buildAssessmentReleaseStatus()) {
  const payload = JSON.stringify(statuses.map(status => {
    const output = { ...status };
    delete output.publishedQuestionIds;
    delete output.publishedQuestions;
    return output;
  }), null, 2);
  return `// Generated by tools/generateAssessmentReleaseStatus.mjs from src/content/releaseStandard.js.
// Do not edit by hand. A skill is published only when every canonical dimension passes.

export const assessmentReleaseStatus = Object.freeze(${payload});

export const assessmentReleaseStatusBySkillId = Object.freeze(Object.fromEntries(
  assessmentReleaseStatus.map(status => [status.skillId, status])
));

export const assessmentReleaseStatusVersion = ${JSON.stringify(assessmentReleaseStandard.version)};
`;
}

export function renderAssessmentReleaseExposure(statuses = buildAssessmentReleaseStatus()) {
  const exposureBySkillId = Object.fromEntries(statuses.map(status => [
    status.skillId,
    status.releaseReady ? status.publishedQuestions : []
  ]));
  return `// Generated by tools/generateAssessmentReleaseStatus.mjs from the canonical
// strict per-skill audit. Do not edit by hand.

export const assessmentReleaseExposureBySkillId = Object.freeze(${JSON.stringify(exposureBySkillId, null, 2)});
export const assessmentReleaseExposureVersion = ${JSON.stringify(assessmentReleaseStandard.version)};
`;
}
