import { assessmentReleaseStandard } from "../src/content/releaseStandard.js";
import { auditStrictProductionReadiness } from "./auditAllSkillsStrictProductionReadiness.js";

export function buildAssessmentReleaseStatus() {
  const report = auditStrictProductionReadiness();
  return report.perSkill.map(skill => ({
    skillId: skill.skillId,
    skillName: skill.skillName,
    standardVersion: skill.releaseStandardDecision.standardVersion,
    releaseReady: skill.releaseStandardDecision.releaseReady,
    dimensions: skill.releaseStandardDecision.dimensions,
    reasons: skill.releaseStandardDecision.reasons,
    runtimeSelectableQuestions: skill.strictUsableQuestionCount,
    levels: skill.releaseStandardDecision.levels,
    accessibilityIssueCount: skill.accessibilityIssueCount,
    missingRequiredImages: skill.missingImageCount,
    missingRequiredAudio: skill.missingAudioCount,
    wiringDefects: skill.mediaWiringFixCount
  }));
}

export function renderAssessmentReleaseStatus(statuses = buildAssessmentReleaseStatus()) {
  const payload = JSON.stringify(statuses, null, 2);
  return `// Generated by tools/generateAssessmentReleaseStatus.mjs from src/content/releaseStandard.js.
// Do not edit by hand. A skill is published only when every canonical dimension passes.

export const assessmentReleaseStatus = Object.freeze(${payload});

export const assessmentReleaseStatusBySkillId = Object.freeze(Object.fromEntries(
  assessmentReleaseStatus.map(status => [status.skillId, status])
));

export const assessmentReleaseStatusVersion = ${JSON.stringify(assessmentReleaseStandard.version)};
`;
}
