import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { guidedReadingBooks, formatGuidedReadingType } from "../src/data/guidedReadingBooks.js";
import { getGuidedReadingBookAudioPath, getGuidedReadingPageAudioPath } from "../src/utils/guidedReading/readAloudPolicy.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicRoot = path.join(repoRoot, "public");
const inventoryPath = path.join(repoRoot, "docs", "guided-reading", "whole_book_audio_coverage_inventory.md");
const kimiRequestPath = path.join(repoRoot, "docs", "assets", "kimi_missing_whole_book_audio_request.md");

function publicFileExists(publicPath = "") {
  return Boolean(publicPath) && fs.existsSync(path.join(publicRoot, publicPath.replace(/^\//, "")));
}

function hasPageTiming(page = {}) {
  return [
    page.audioStartSeconds,
    page.audioStart,
    page.startSeconds,
    page.startTime,
    page.syncStart,
    page.audioEndSeconds,
    page.audioEnd,
    page.endSeconds,
    page.endTime,
    page.syncEnd,
    page.audioDurationSeconds,
    page.audioDuration,
    page.duration
  ].some(value => Number.isFinite(Number(value)));
}

function hasBookTiming(book = {}) {
  return Boolean(
    book.pageTimings ||
    book.pageTiming ||
    book.audioTimings ||
    book.audioSync ||
    book.sync ||
    (book.pages || []).some(hasPageTiming)
  );
}

function normalizeSeriesKey(book = {}) {
  if (book.seriesId) return book.seriesId;
  if (String(book.id || "").startsWith("first-facts-level-a")) return "first-facts-level-a";
  if (String(book.id || "").startsWith("first-facts-a")) return "first-facts";
  if (String(book.id || "").startsWith("first-facts-c")) return "first-facts-level-c";
  return String(book.id || "").split("-").slice(0, 2).join("-");
}

function suggestedWholeBookAudioPath(book = {}) {
  const declared = getGuidedReadingBookAudioPath(book);
  if (declared) return declared;

  const firstPageAudio = getGuidedReadingPageAudioPath((book.pages || [])[0] || {});
  if (firstPageAudio.includes("/audio/page-")) {
    return firstPageAudio.replace(/\/audio\/page-\d+\.mp3$/, "/audio/full-book.mp3");
  }
  if (firstPageAudio.includes("/audio/narration/")) {
    return `/guided-reading/audio/narration/${book.id}-full-book.mp3`;
  }

  const firstPageImage = (book.pages || [])[0]?.image || "";
  if (firstPageImage.includes("/page-")) {
    return `${firstPageImage.replace(/\/page-[^/]+$/, "")}/audio/full-book.mp3`;
  }
  return `/guided-reading/audio/whole-books/${book.id}.mp3`;
}

function markdownTable(headers, rows) {
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map(row => `| ${row.map(cell => String(cell ?? "").replace(/\n/g, "<br>").replace(/\|/g, "\\|")).join(" | ")} |`)
  ].join("\n");
}

function bookRows() {
  return guidedReadingBooks.map(book => {
    const pages = book.pages || [];
    const wholeBookAudioPath = getGuidedReadingBookAudioPath(book);
    const wholeBookAudioExists = publicFileExists(wholeBookAudioPath);
    const pageImageCount = pages.filter(page => publicFileExists(page.image)).length;
    const pageAudioCount = pages.filter(page => publicFileExists(getGuidedReadingPageAudioPath(page))).length;

    return {
      id: book.id,
      title: book.title,
      type: formatGuidedReadingType(book.type),
      level: book.level,
      series: normalizeSeriesKey(book),
      pageCount: pages.length,
      wholeBookAudioPath,
      wholeBookAudioExists,
      suggestedWholeBookAudioPath: suggestedWholeBookAudioPath(book),
      pageImageCount,
      pageAudioCount,
      hasAllPageImages: pageImageCount === pages.length,
      hasAllPageAudio: pageAudioCount === pages.length,
      hasPageTiming: hasBookTiming(book),
      pages
    };
  });
}

function status(value) {
  return value ? "yes" : "no";
}

function writeInventory(rows) {
  const wholeBookAudioRows = rows.filter(row => row.wholeBookAudioExists);
  const missingWholeBookAudioRows = rows.filter(row => !row.wholeBookAudioExists);
  const pageTimingRows = rows.filter(row => row.hasPageTiming);
  const bySeries = Object.values(Object.groupBy(rows, row => row.series))
    .map(items => {
      const item = items[0];
      return [
        item.series,
        items.length,
        items.filter(row => row.wholeBookAudioExists).length,
        items.filter(row => !row.wholeBookAudioExists).length,
        items.filter(row => row.hasAllPageImages).length,
        items.filter(row => row.hasAllPageAudio).length,
        items.filter(row => row.hasPageTiming).length
      ];
    })
    .sort((a, b) => String(a[0]).localeCompare(String(b[0])));

  const lines = [
    "# Guided Reading Whole-Book Audio Coverage Inventory",
    "",
    "Generated by `node tools/auditGuidedReadingWholeBookAudio.js` from the active `guidedReadingBooks` registry and files under `public/`.",
    "",
    "## Summary",
    "",
    `- Active guided-reading books audited: ${rows.length}`,
    `- Books with existing whole-book audio: ${wholeBookAudioRows.length}`,
    `- Books missing whole-book audio: ${missingWholeBookAudioRows.length}`,
    `- Books with all page images present: ${rows.filter(row => row.hasAllPageImages).length}`,
    `- Books with all page-level audio present: ${rows.filter(row => row.hasAllPageAudio).length}`,
    `- Books with explicit page-level timing/sync data: ${pageTimingRows.length}`,
    "",
    "Note: page-level narration audio and page-level timing/sync data are different. Many books have one MP3 per page, but no book currently declares timestamps that map a single whole-book MP3 to page boundaries.",
    "",
    "## Coverage by Series",
    "",
    markdownTable(
      ["Series", "Books", "Whole-book audio", "Missing whole-book audio", "All page images", "All page audio", "Explicit timing"],
      bySeries
    ),
    "",
    "## Book Inventory",
    "",
    markdownTable(
      [
        "ID",
        "Title",
        "Type",
        "Level",
        "Pages",
        "Whole-book audio",
        "Page images",
        "Page audio",
        "Explicit timing",
        "Whole-book audio path / suggested path"
      ],
      rows.map(row => [
        row.id,
        row.title,
        row.type,
        row.level,
        row.pageCount,
        status(row.wholeBookAudioExists),
        `${row.pageImageCount}/${row.pageCount}`,
        `${row.pageAudioCount}/${row.pageCount}`,
        status(row.hasPageTiming),
        row.wholeBookAudioPath || row.suggestedWholeBookAudioPath
      ])
    )
  ];

  fs.mkdirSync(path.dirname(inventoryPath), { recursive: true });
  fs.writeFileSync(inventoryPath, `${lines.join("\n")}\n`);
}

function writeKimiRequest(rows) {
  const missingRows = rows.filter(row => !row.wholeBookAudioExists);
  const lines = [
    "# Kimi Request: Missing Guided Reading Whole-Book Audio",
    "",
    "Create only the missing whole-book audio files listed below. Do not create page images, word audio, page-level narration, browser-TTS output, placeholder audio, or audio for books that already have a whole-book MP3.",
    "",
    "Delivery requirements:",
    "- One clean MP3 per book at the exact requested path.",
    "- Natural child-friendly narration in a consistent warm voice.",
    "- Read the page text in page order with a short natural pause between pages.",
    "- Do not read page numbers, filenames, markdown, section labels, or production notes.",
    "- Preserve punctuation, dialogue, names, and British spellings where present.",
    "",
    `Books requested: ${missingRows.length}`,
    ""
  ];

  missingRows.forEach((row, index) => {
    lines.push(
      `## ${index + 1}. ${row.title}`,
      "",
      `- Book ID: ${row.id}`,
      `- Type/level: ${row.type}, Level ${row.level}`,
      `- Pages: ${row.pageCount}`,
      `- Required output path: \`${row.suggestedWholeBookAudioPath}\``,
      "",
      "Page text to narrate:",
      ""
    );
    row.pages.forEach(page => {
      lines.push(`Page ${page.pageNumber || row.pages.indexOf(page) + 1}:`);
      lines.push(String(page.pageAudioText || page.text || "").trim());
      lines.push("");
    });
  });

  fs.mkdirSync(path.dirname(kimiRequestPath), { recursive: true });
  fs.writeFileSync(kimiRequestPath, `${lines.join("\n")}\n`);
}

const rows = bookRows();
writeInventory(rows);
writeKimiRequest(rows);

console.log(`Audited ${rows.length} active guided-reading books.`);
console.log(`Whole-book audio present: ${rows.filter(row => row.wholeBookAudioExists).length}`);
console.log(`Whole-book audio missing: ${rows.filter(row => !row.wholeBookAudioExists).length}`);
console.log(`All page images present: ${rows.filter(row => row.hasAllPageImages).length}`);
console.log(`Explicit page timing present: ${rows.filter(row => row.hasPageTiming).length}`);
console.log(`Wrote ${path.relative(repoRoot, inventoryPath)}`);
console.log(`Wrote ${path.relative(repoRoot, kimiRequestPath)}`);
