import crypto from "crypto";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { masteryCoreQuestions } from "../src/data/masteryCoreQuestions.js";
import { masteryExtraQuestions } from "../src/data/masteryExtraQuestions.js";
import { templateQuestions } from "../src/data/templateQuestions.js";
import { templateExpansion } from "../src/data/templateExpansion.js";
import { templateExpansion2 } from "../src/data/templateExpansion2.js";
import { templateExpansion3 } from "../src/data/templateExpansion3.js";
import { templateExpansion4 } from "../src/data/templateExpansion4.js";
import { templateExpansion5 } from "../src/data/templateExpansion5.js";
import { templateExpansion6 } from "../src/data/templateExpansion6.js";
import { templateExpansion7 } from "../src/data/templateExpansion7.js";
import { generatedQuestions } from "../src/data/generatedQuestions.js";
import { fixSentenceQuestions } from "../src/data/fixSentenceQuestions.js";
import { templateComprehensionAdvanced } from "../src/data/templateComprehensionAdvanced.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const outputPath = path.join(rootDir, "src/data/audioManifest.js");

const questionBanks = [
  ["masteryCoreQuestions", masteryCoreQuestions],
  ["masteryExtraQuestions", masteryExtraQuestions],
  ["templateQuestions", templateQuestions],
  ["templateExpansion", templateExpansion],
  ["templateExpansion2", templateExpansion2],
  ["templateExpansion3", templateExpansion3],
  ["templateExpansion4", templateExpansion4],
  ["templateExpansion5", templateExpansion5],
  ["templateExpansion6", templateExpansion6],
  ["templateExpansion7", templateExpansion7],
  ["generatedQuestions", generatedQuestions],
  ["fixSentenceQuestions", fixSentenceQuestions],
  ["templateComprehensionAdvanced", templateComprehensionAdvanced]
];

function normalizeAudioText(text) {
  return String(text || "")
    .normalize("NFKC")
    .replace(/[“”]/g, "\"")
    .replace(/[‘’]/g, "'")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function hashAudioText(normalizedText) {
  return crypto
    .createHash("sha1")
    .update(normalizedText)
    .digest("hex")
    .slice(0, 16);
}

function shouldIncludePassage(question) {
  return (
    question.audioPassage === true ||
    question.includePassageAudio === true ||
    question.passageAudio === true ||
    question.usePassageAudio === true
  );
}

function addEntry(entries, stats, text, kind) {
  const normalizedText = normalizeAudioText(text);

  if (!normalizedText) return;

  const key = hashAudioText(normalizedText);

  if (!entries.has(key)) {
    entries.set(key, {
      text: String(text).trim(),
      normalizedText,
      path: `/audio/${key}.mp3`,
      kinds: new Set(),
      useCount: 0
    });
  }

  const entry = entries.get(key);
  entry.kinds.add(kind);
  entry.useCount += 1;
  stats[kind] += 1;
}

const entries = new Map();
const stats = {
  prompt: 0,
  choice: 0,
  spokenPrompt: 0,
  passage: 0
};

let questionCount = 0;

for (const [, bank] of questionBanks) {
  for (const question of bank) {
    questionCount += 1;

    addEntry(entries, stats, question.prompt || question.question, "prompt");
    addEntry(entries, stats, question.spokenPrompt, "spokenPrompt");

    if (Array.isArray(question.choices)) {
      for (const choice of question.choices) {
        addEntry(entries, stats, choice, "choice");
      }
    }

    if (question.passage && shouldIncludePassage(question)) {
      addEntry(entries, stats, question.passage, "passage");
    }
  }
}

const audioManifest = Object.fromEntries(
  [...entries.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, entry]) => [
      key,
      {
        text: entry.text,
        normalizedText: entry.normalizedText,
        path: entry.path,
        kinds: [...entry.kinds].sort(),
        useCount: entry.useCount
      }
    ])
);

const audioTextIndex = Object.fromEntries(
  Object.entries(audioManifest).map(([key, entry]) => [entry.normalizedText, key])
);

const output = `// Generated by tools/buildAudioManifest.js. Do not edit by hand.

export const audioManifest = ${JSON.stringify(audioManifest, null, 2)};

export const audioTextIndex = ${JSON.stringify(audioTextIndex, null, 2)};

export const audioManifestStats = ${JSON.stringify({
  entries: entries.size,
  questionsScanned: questionCount,
  collectedUses: stats
}, null, 2)};
`;

fs.writeFileSync(outputPath, output);

console.log(`Wrote ${path.relative(rootDir, outputPath)}`);
console.log(`Questions scanned: ${questionCount}`);
console.log(`Unique audio entries: ${entries.size}`);
console.log(`Collected uses: ${JSON.stringify(stats)}`);
