#!/usr/bin/env node
import { createHash } from "node:crypto";
import { readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { CONNECTED_TEXT_RECORDS } from "../src/features/soundSeekers/content/connectedTextRecords.js";
import { MEANING_SUPPORT_RECORDS } from "../src/features/soundSeekers/content/meaningSupportRecords.js";
import { PRONUNCIATION_RECORDS } from "../src/features/soundSeekers/content/pronunciationRecords.js";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(repositoryRoot,
  "src/features/soundSeekers/content/connectedTextUsage.generated.js");
const args = process.argv.slice(2);
if (args.some(argument => argument !== "--write") || args.filter(argument => argument === "--write").length > 1) {
  throw new Error("Usage: buildSoundSeekersConnectedTextUsage.mjs [--write]");
}
const write = args.includes("--write");

const tokenize = text => String(text || "")
  .normalize("NFKC")
  .replace(/[\u2018\u2019]/gu, "'")
  .toLocaleLowerCase("en-US")
  .match(/[a-z]+(?:'[a-z]+)?/gu) || [];

const uses = new Map();
function add(wordId, use) {
  const normalized = String(wordId || "").replace(/^hw:/u, "");
  if (!PRONUNCIATION_RECORDS[normalized]) return;
  const list = uses.get(normalized) || [];
  list.push(Object.freeze(use));
  uses.set(normalized, list);
}

for (const scene of CONNECTED_TEXT_RECORDS) {
  scene.tokenIds.forEach((wordId, ordinal) => add(wordId, {
    sceneId: scene.id, stopId: scene.stopId, surface: "running_text", ordinal
  }));
  tokenize(scene.prompt.text).forEach((wordId, ordinal) => add(wordId, {
    sceneId: scene.id, stopId: scene.stopId, surface: "prompt", ordinal
  }));
  scene.choice.options.forEach((option, optionOrdinal) => {
    if (option.presentation === "text") {
      tokenize(option.childLabel).forEach((wordId, tokenOrdinal) => add(wordId, {
        sceneId: scene.id,
        stopId: scene.stopId,
        surface: "text_option",
        ordinal: (optionOrdinal * 100) + tokenOrdinal
      }));
    }
    tokenize(option.accessibleLabel).forEach((wordId, tokenOrdinal) => add(wordId, {
      sceneId: scene.id,
      stopId: scene.stopId,
      surface: "accessible_label",
      ordinal: (optionOrdinal * 100) + tokenOrdinal
    }));
  });
}

for (const support of MEANING_SUPPORT_RECORDS) {
  const text = `${support.childDefinition} ${support.ellSupport.oralBridge} ${support.actionPrompt}`;
  tokenize(text).forEach((wordId, ordinal) => add(wordId, {
    sceneId: `meaning:${support.wordId}`,
    stopId: "meaning-support",
    surface: "meaning_support",
    ordinal
  }));
}

const usage = [...uses].sort(([left], [right]) => left.localeCompare(right))
  .map(([wordId, entries]) => ({ wordId, uses: entries }));
const advancedIds = [...new Set(CONNECTED_TEXT_RECORDS
  .flatMap(scene => [...scene.advancedTokenIds, ...scene.advancedChildLabelTokenIds]))].sort();
const advancedHash = createHash("sha256").update(JSON.stringify(advancedIds)).digest("hex");
const banner = "// AUTO-GENERATED by tools/buildSoundSeekersConnectedTextUsage.mjs - do not edit.\n";
const rendered = `${banner}
const deepFreeze = value => {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const child of Object.values(value)) deepFreeze(child);
  return Object.freeze(value);
};

export const CONNECTED_TEXT_USAGE = deepFreeze(${JSON.stringify(usage, null, 2)});
export const ADVANCED_SCENE_TOKEN_IDS = Object.freeze(${JSON.stringify(advancedIds)});
export const ADVANCED_SCENE_TOKEN_COUNT = ADVANCED_SCENE_TOKEN_IDS.length;
export const ADVANCED_SCENE_TOKEN_CONTENT_HASH = ${JSON.stringify(advancedHash)};
`;

if (!write) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== rendered) throw new Error("connectedTextUsage.generated.js is stale; run with --write");
  console.log(`connected-text usage current: ${usage.length} pronunciation IDs`);
} else {
  const temporaryPath = `${outputPath}.tmp-${process.pid}`;
  try {
    await writeFile(temporaryPath, rendered, { flag: "wx" });
    await rename(temporaryPath, outputPath);
  } finally {
    await unlink(temporaryPath).catch(() => {});
  }
  console.log(`connected-text usage written: ${usage.length} pronunciation IDs`);
}
