import path from "node:path";

import { getLevelOneContentQualityIssues } from "../src/data/levelOneContentQuality.js";
import {
  getQuestionImagePaths,
  loadCoreQuestionPool,
  normalizeWord,
  publicPathExists,
  repoRoot,
  selectableRuntimeQuestionsForSkill,
  writeFile
} from "./phonicsRuntimeUtils.js";

const checkedSkills = [
  ["vowel_teams", "Vowel Teams"],
  ["r_controlled", "R-Controlled Vowels"],
  ["nouns", "Nouns"],
  ["verbs", "Verbs"],
  ["adjectives", "Adjectives"],
  ["prepositions", "Prepositions of Place"],
  ["plurals", "Plurals"],
  ["antonyms_synonyms", "Antonyms and Synonyms"]
];

function level(question = {}) {
  return Number(question.level || question.assessmentLevel || question.depthLevel || 1) >= 2 ? 2 : 1;
}

function imageStatus(question = {}) {
  const paths = getQuestionImagePaths(question);
  const missing = paths.filter(item => !publicPathExists(item));
  return {
    count: paths.length,
    missing,
    complete: paths.length > 0 && missing.length === 0
  };
}

const blockedRows = [];
for (const question of loadCoreQuestionPool()) {
  const issues = getLevelOneContentQualityIssues(question);
  if (!issues.length) continue;
  blockedRows.push({
    skillId: question.skillId || question.assessmentSkillId || "",
    id: question.id || "",
    target: normalizeWord(question.targetWord || question.correctAnswer || question.answer || question.itemKey || ""),
    issues
  });
}

const summary = checkedSkills.map(([skillId, label]) => {
  const l1 = selectableRuntimeQuestionsForSkill(skillId).filter(question => level(question) === 1);
  const missingImages = l1.filter(question => !imageStatus(question).complete);
  const hardTargets = l1.filter(question => getLevelOneContentQualityIssues(question).length > 0);
  return {
    skillId,
    label,
    count: l1.length,
    missingImages,
    hardTargets,
    samples: l1.slice(0, 8).map(question => normalizeWord(question.targetWord || question.correctAnswer || question.answer || question.itemKey || question.id))
  };
});

const failures = [];
summary.forEach(row => {
  if (row.count < 15) failures.push(`${row.label} Level 1 has ${row.count} selectable visual items; expected at least 15.`);
  if (row.missingImages.length) failures.push(`${row.label} Level 1 has ${row.missingImages.length} selectable items without complete images.`);
  if (row.hardTargets.length) failures.push(`${row.label} Level 1 has ${row.hardTargets.length} selectable items blocked by the quality rule.`);
});

const report = [
  "# Assessment Level 1 Content and Media Audit",
  "",
  "Generated by `npm run check:assessment-level1-content-media`.",
  "",
  "## Level 1 Rule",
  "",
  "- Prefer image-backed prompts and/or image-backed answer options.",
  "- Avoid text-only grammar/vocabulary classification unless the skill is explicitly reading text.",
  "- Use concrete, familiar, imageable words.",
  "- Missing media deactivates runtime use or queues the item for replacement.",
  "",
  "## Runtime Summary",
  "",
  "| Skill | Selectable Level 1 Items | Missing Images | Sample Targets |",
  "| --- | ---: | ---: | --- |",
  ...summary.map(row =>
    `| ${row.label} | ${row.count} | ${row.missingImages.length} | ${row.samples.join(", ")} |`
  ),
  "",
  "## Blocked Level 1 Rows",
  "",
  blockedRows.length
    ? [
      "| Skill | Question ID | Target | Issues |",
      "| --- | --- | --- | --- |",
      ...blockedRows.slice(0, 250).map(row => `| ${row.skillId} | ${row.id} | ${row.target} | ${row.issues.join("; ")} |`)
    ].join("\n")
    : "None.",
  "",
  "## Failures",
  "",
  failures.length ? failures.map(item => `- ${item}`).join("\n") : "- none",
  ""
];

writeFile(path.join(repoRoot, "docs/validation/assessment_level1_content_media_audit.md"), report.join("\n"));
console.log("Wrote docs/validation/assessment_level1_content_media_audit.md");

if (failures.length) {
  failures.forEach(failure => console.error(`- ${failure}`));
  process.exit(1);
}

console.log("Assessment Level 1 content/media check passed.");
