import path from "node:path";

import { ALL_HFW_WORD_SET, normalizeHfwSkillId } from "../src/data/highFrequencyWordBands.js";
import {
  getQuestionSkillLabel,
  normalizeWord,
  repoRoot,
  selectableRuntimeQuestionsForSkill,
  writeFile
} from "./phonicsRuntimeUtils.js";

const hfwSkills = ["hfw_1_25", "hfw_26_50", "hfw_51_75", "hfw_76_100"];

function getPrompt(question = {}) {
  return [question.prompt, question.question, question.spokenPrompt].filter(Boolean).join(" ");
}

function getOptions(question = {}) {
  return [
    ...(Array.isArray(question.answerOptions) ? question.answerOptions : []),
    ...(Array.isArray(question.options) ? question.options : []),
    ...(Array.isArray(question.choices) ? question.choices : [])
  ].map(option => {
    if (option && typeof option === "object") return option.value || option.word || option.label || option.text || "";
    return option;
  }).map(normalizeWord).filter(Boolean);
}

function getAnswer(question = {}) {
  return normalizeWord(question.correctAnswer || question.answer || question.targetWord || question.itemKey || "");
}

function promptTargetsSpecificWord(question = {}) {
  const prompt = normalizeWord(getPrompt(question));
  const answer = getAnswer(question);
  if (!answer) return false;
  return prompt.includes(`find the word ${answer}`) ||
    prompt.includes(`which word says ${answer}`) ||
    prompt.includes(`choose ${answer}`) ||
    prompt.includes(`listen to the word choose ${answer}`);
}

function isGenericHfwPrompt(question = {}) {
  const prompt = normalizeWord(getPrompt(question));
  return /\b(high frequency|sight word)\b/.test(prompt) && !promptTargetsSpecificWord(question);
}

const rows = [];
const failures = [];

for (const skillId of hfwSkills) {
  for (const question of selectableRuntimeQuestionsForSkill(skillId)) {
    const options = getOptions(question);
    const hfwOptions = options.filter(word => ALL_HFW_WORD_SET.has(word));
    const genericPrompt = isGenericHfwPrompt(question);
    const explanation = String(question.explanation || question.teachingTip || question.feedback || "").toLowerCase();
    const genericExplanation = explanation.includes("this is a high-frequency word") && hfwOptions.length > 1;
    const sameBandGenericDistractors = genericPrompt && hfwOptions.length > 1;

    if (sameBandGenericDistractors || genericExplanation) {
      const issue = `${question.id}: generic HFW wording with valid HFW options (${hfwOptions.join(", ")})`;
      failures.push(issue);
      rows.push({
        skillId,
        id: question.id,
        prompt: getPrompt(question),
        answer: getAnswer(question),
        hfwOptions,
        action: "blocked by validator; prompt must target a specific word or use non-HFW distractors"
      });
    }
  }
}

const report = [
  "# HFW Distractor Ambiguity Audit",
  "",
  "Generated by `npm run check:hfw-distractor-ambiguity`.",
  "",
  "## Summary",
  "",
  `- HFW skills checked: ${hfwSkills.join(", ")}`,
  `- Ambiguous active runtime questions: ${failures.length}`,
  "",
  "## Rule",
  "",
  "If a prompt asks generically for a high-frequency word, distractors must not also be valid HFWs. Word-recognition questions should instead target a specific word, such as `Find the word: the`.",
  "",
  "## Flagged Items",
  "",
  rows.length
    ? [
      "| Skill | Question ID | Answer | Valid HFW options | Action |",
      "| --- | --- | --- | --- | --- |",
      ...rows.map(row => `| ${row.skillId} | ${row.id} | ${row.answer} | ${row.hfwOptions.join(", ")} | ${row.action} |`)
    ].join("\n")
    : "None.",
  "",
  "## Runtime Bands",
  "",
  ...hfwSkills.map(skillId => {
    const count = selectableRuntimeQuestionsForSkill(skillId).length;
    return `- ${getQuestionSkillLabel({ skillId }) || normalizeHfwSkillId(skillId)}: ${count} selectable questions`;
  }),
  ""
];

writeFile(path.join(repoRoot, "docs/validation/hfw_distractor_ambiguity_audit.md"), report.join("\n"));
console.log("Wrote docs/validation/hfw_distractor_ambiguity_audit.md");

if (failures.length) {
  failures.forEach(failure => console.error(`- ${failure}`));
  process.exit(1);
}

console.log("HFW distractor ambiguity check passed.");
