import path from "node:path";

import { managedAssessmentSkillDepthConfig } from "../src/data/skillLevelDepthConfig.js";
import {
  normalizeWord,
  repoRoot,
  selectableRuntimeQuestionsForSkill,
  writeFile
} from "./phonicsRuntimeUtils.js";

const INITIAL_SOUND_SKILLS = new Set(["initial_sounds"]);

function wordOnset(word = "") {
  return normalizeWord(word).replace(/[^a-z]/g, "").slice(0, 1);
}

function getSkillId(question = {}) {
  return String(question.skillId || question.assessmentSkillId || question.stage || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function getAnswer(question = {}) {
  const answer = Array.isArray(question.correctAnswers)
    ? question.correctAnswers[0]
    : question.correctAnswer || question.answer;
  return normalizeWord(answer);
}

function getOptions(question = {}) {
  const raw = [
    ...(Array.isArray(question.choices) ? question.choices : []),
    ...(Array.isArray(question.options) ? question.options : []),
    ...(Array.isArray(question.answerOptions) ? question.answerOptions : []),
    ...(Array.isArray(question.imageCards) ? question.imageCards : [])
  ];
  const words = raw
    .map(option => {
      if (option && typeof option === "object") {
        return option.value || option.word || option.label || option.text || "";
      }
      return option;
    })
    .map(normalizeWord)
    .filter(word => /^[a-z]+$/.test(word));
  return [...new Set(words)];
}

function hasWordChoiceSurface(question = {}) {
  const prompt = String(question.prompt || question.question || "").toLowerCase();
  const template = String(question.templateType || question.formatType || question.questionType || "").toLowerCase();
  const answerOptions = Array.isArray(question.answerOptions) ? question.answerOptions : [];
  const imageCards = Array.isArray(question.imageCards) ? question.imageCards : [];
  return (
    template.includes("word") ||
    template.includes("picture") ||
    prompt.includes("which word") ||
    prompt.includes("pick the word") ||
    prompt.includes("matches the picture") ||
    answerOptions.some(option => option && typeof option === "object" && (option.image || option.imageUrl || option.imagePath)) ||
    imageCards.length > 0
  );
}

function hasOnsetGiveaway(question = {}) {
  const skillId = getSkillId(question);
  if (INITIAL_SOUND_SKILLS.has(skillId)) return false;
  if (!hasWordChoiceSurface(question)) return false;

  const answer = getAnswer(question);
  const options = getOptions(question);
  if (!answer || options.length !== 4 || !options.includes(answer)) return false;
  if (answer.length < 3) return false;

  const distractors = options.filter(word => word !== answer);
  if (distractors.length !== 3) return false;

  const answerOnset = wordOnset(answer);
  const distractorOnsets = distractors.map(wordOnset).filter(Boolean);
  return Boolean(
    answerOnset &&
    distractorOnsets.length === 3 &&
    new Set(distractorOnsets).size === 1 &&
    distractorOnsets[0] !== answerOnset
  );
}

const skillIds = [...new Set(managedAssessmentSkillDepthConfig.map(config => config.skillId))];
const rows = [];

for (const skillId of skillIds) {
  for (const question of selectableRuntimeQuestionsForSkill(skillId)) {
    if (!hasOnsetGiveaway(question)) continue;
    const answer = getAnswer(question);
    const options = getOptions(question);
    rows.push({
      skillId,
      id: question.id,
      prompt: question.prompt || question.question || "",
      answer,
      options,
      distractorOnsets: options.filter(word => word !== answer).map(wordOnset)
    });
  }
}

const markdown = [
  "# Distractor Onset Giveaway Audit",
  "",
  "Generated by `npm run check:distractor-onset-giveaway`.",
  "",
  `- Runtime selectable questions checked: ${skillIds.length} skills`,
  `- Odd-one-out onset giveaways: ${rows.length}`,
  "",
  rows.length
    ? [
      "| Skill | Question ID | Answer | Options | Distractor onsets |",
      "| --- | --- | --- | --- | --- |",
      ...rows.map(row => `| ${row.skillId} | ${row.id} | ${row.answer} | ${row.options.join(", ")} | ${row.distractorOnsets.join(", ")} |`)
    ].join("\n")
    : "None.",
  ""
].join("\n");

writeFile(path.join(repoRoot, "docs/validation/distractor_onset_giveaway_audit.md"), markdown);
writeFile(path.join(repoRoot, "docs/validation/distractor_onset_giveaway_audit.json"), `${JSON.stringify({
  generatedBy: "npm run check:distractor-onset-giveaway",
  checkedSkills: skillIds,
  failures: rows
}, null, 2)}\n`);

console.log("Wrote docs/validation/distractor_onset_giveaway_audit.md");
console.log("Wrote docs/validation/distractor_onset_giveaway_audit.json");

if (rows.length) {
  console.error(`Found ${rows.length} onset giveaway question(s).`);
  process.exit(1);
}
