import path from "node:path";

import {
  getQuestionAudioPaths,
  getQuestionImagePaths,
  normalizeWord,
  publicPathExists,
  repoRoot,
  selectableRuntimeQuestionsForSkill,
  writeFile
} from "./phonicsRuntimeUtils.js";

const rows = [];
const failures = [];
const longVowelItems = selectableRuntimeQuestionsForSkill("long_vowels_silent_e");

for (const question of longVowelItems) {
  const targetWord = normalizeWord(question.targetWord || question.word || question.audioText || question.correctAnswer || question.answer || "");
  const audioPaths = getQuestionAudioPaths(question);
  const imagePaths = getQuestionImagePaths(question);
  const missingAudio = audioPaths.filter(item => String(item).startsWith("/") && !publicPathExists(item));
  const hasImage = imagePaths.some(publicPathExists);
  const audioLed = audioPaths.length > 0 && !hasImage;
  const action = audioLed || missingAudio.length
    ? "blocked: audio-led or missing prompt audio is not acceptable for active Long Vowels"
    : "active: image-backed replacement item";

  if (audioLed || missingAudio.length) {
    failures.push(`${question.id}: ${action}`);
  }

  rows.push({
    id: question.id,
    targetWord,
    audio: audioPaths.join(", ") || "none",
    image: imagePaths.join(", ") || "none",
    action
  });
}

const report = [
  "# Assessment Prompt Audio Quality Audit",
  "",
  "Generated by `npm run check:assessment-prompt-audio-quality`.",
  "",
  "## Long Vowels and Silent E",
  "",
  `- Active runtime-selectable items inspected: ${longVowelItems.length}`,
  `- Audio-led or missing-audio failures: ${failures.length}`,
  "",
  "| Question ID | Target Word | Audio Path | Image Path | Action |",
  "| --- | --- | --- | --- | --- |",
  ...rows.map(row =>
    `| ${row.id} | ${row.targetWord} | ${row.audio} | ${row.image} | ${row.action} |`
  ),
  "",
  "## Failures",
  "",
  failures.length ? failures.map(item => `- ${item}`).join("\n") : "- none",
  ""
];

writeFile(path.join(repoRoot, "docs/validation/assessment_prompt_audio_quality_audit.md"), report.join("\n"));
console.log("Wrote docs/validation/assessment_prompt_audio_quality_audit.md");

if (failures.length) {
  failures.forEach(failure => console.error(`- ${failure}`));
  process.exit(1);
}

console.log("Assessment prompt audio quality check passed.");
