import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { buildCurriculumReleaseBoard } from "../src/content/curriculumReleaseBoard.js";
import { repoRoot } from "./phonicsRuntimeUtils.js";

export const curriculumBoardDocumentPath = path.join(
  repoRoot,
  "docs",
  "release",
  "CURRICULUM_BOARD.md"
);
export const curriculumBoardModulePath = path.join(
  repoRoot,
  "src",
  "content",
  "assessments",
  "curriculumReleaseBoard.generated.js"
);

function safeCell(value = "") {
  return String(value || "—")
    .replaceAll("|", "\\|")
    .replace(/\s+/g, " ")
    .trim();
}

function questionIdentity(question = {}) {
  return [
    String(question.id || question.questionId || ""),
    Number(question.level || question.assessmentLevel || 1)
  ].join("::");
}

export async function buildLiveCurriculumBoard(statuses = null) {
  let resolvedStatuses = statuses;
  let generatedExposureBySkillId = {};
  if (!resolvedStatuses) {
    const statusModule = await import(
      "../src/content/assessments/assessmentReleaseStatus.generated.js"
    );
    const exposureModule = await import(
      "../src/content/assessments/assessmentReleaseExposure.generated.js"
    );
    resolvedStatuses = statusModule.assessmentReleaseStatus;
    generatedExposureBySkillId = exposureModule.assessmentReleaseExposureBySkillId;
  }
  const exposureEntries = resolvedStatuses.map(status => {
    const questions = status.releaseReady
      ? status.publishedQuestions || generatedExposureBySkillId[status.skillId] || []
      : [];
    const identities = questions.map(questionIdentity).filter(Boolean).sort();
    const level1 = questions.filter(
      question => Number(question.level || question.assessmentLevel || 1) === 1
    ).length;
    const level2 = questions.length - level1;
    return [status.skillId, {
      count: questions.length,
      level1,
      level2,
      fingerprint: crypto
        .createHash("sha256")
        .update(identities.join("\n"))
        .digest("hex")
    }];
  });

  return buildCurriculumReleaseBoard({
    statuses: resolvedStatuses,
    exposureBySkillId: Object.fromEntries(exposureEntries)
  });
}

export function renderCurriculumBoardModule(model) {
  return `// Generated by tools/generateAssessmentReleaseStatus.mjs from the canonical
// release rubric, strict audit, live student bank loader, and media exclusions.
// Do not edit by hand.

export const curriculumReleaseBoard = Object.freeze(${JSON.stringify(model, null, 2)});
`;
}

function waiverText(waiver) {
  if (!waiver.excludedQuestionCount) return "None";
  const reviews = waiver.reviewBy.join(", ") || "date missing";
  return `${waiver.excludedQuestionCount} excluded; review ${reviews}`;
}

function exposureText(row) {
  if (!row.studentExposure.count) return "0 — blocked from children";
  return `${row.studentExposure.count} today (L1 ${row.studentExposure.level1}; L2 ${row.studentExposure.level2})`;
}

export function renderCurriculumBoardDocument(model) {
  const rows = model.rows.map(row => [
    row.skillName,
    row.gateStatus,
    row.owner,
    row.authoredQuestions,
    row.approvedQuestions,
    exposureText(row),
    `sha256:${row.studentExposure.fingerprint.slice(0, 12)}`,
    row.reasons.join(" ") || "All canonical release dimensions pass.",
    waiverText(row.waiver)
  ].map(safeCell).join(" | "));

  return `# Loop D curriculum release board

This file is generated from the same model rendered by the live admin Content
Coverage console. Do not edit it by hand.

Canonical release standard: \`${model.standardVersion}\`

## Current truth

- Skills ready: **${model.readySkills}/${model.rows.length}**
- Skills blocked: **${model.blockedSkills}/${model.rows.length}**
- A READY row means the canonical question-count, balance, media,
  accessibility, and live runtime-selectability dimensions pass.
- “Student exposure today” is counted from the real student bank loader after
  the release decision, not inferred from authored inventory.
- The exposure fingerprint identifies the exact sorted question-and-level set.
- A media waiver is an explicit review-dated exclusion from runtime. It never
  permits a missing-media question to reach a child.

| Skill | Gate | Owner | Authored | Approved | Student exposure today | Exact exposure set | Gate reason | Release exclusions / waivers |
| --- | --- | --- | ---: | ---: | --- | --- | --- | --- |
${rows.map(row => `| ${row} |`).join("\n")}

## Loop D rule

For each blocked skill: fill canonical question/variation gaps, wire and review
required media, rerun the strict audit and runtime simulation, regenerate this
board, and do not mark READY until the real student loader exposes the reviewed
set. Completion requires 30/30 READY with zero variation and media-wiring
failures.
`;
}

export async function writeCurriculumBoard(model = null) {
  const resolvedModel = model || await buildLiveCurriculumBoard();
  fs.writeFileSync(curriculumBoardModulePath, renderCurriculumBoardModule(resolvedModel));
  fs.writeFileSync(curriculumBoardDocumentPath, renderCurriculumBoardDocument(resolvedModel));
  return resolvedModel;
}
