import path from "node:path";

import { mediaQaReviewItems } from "../src/data/generated/mediaQaReviewItems.generated.js";
import { mergeMediaQaReviewItems } from "../src/data/mediaQaReviewStatus.js";
import { writeFile } from "./phonicsRuntimeUtils.js";

const repoRoot = process.cwd();
const outMd = path.join(repoRoot, "docs/validation/media_qa_quarantine_report.md");
const outJson = path.join(repoRoot, "docs/validation/media_qa_quarantine_report.json");
const kimiMd = path.join(repoRoot, "docs/assets/kimi_media_qa_replacement_request.md");
const kimiCsv = path.join(repoRoot, "docs/assets/kimi_media_qa_replacement_request.csv");
const hfwSkillIds = new Set(["hfw_1_25", "hfw_26_50", "hfw_51_75", "hfw_76_100"]);

function csvEscape(value = "") {
  const text = String(value ?? "");
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function markdownEscape(value = "") {
  return String(value ?? "").replace(/\n/g, "<br>").replace(/\|/g, "\\|");
}

function markdownTable(headers, rows) {
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map(row => `| ${row.map(markdownEscape).join(" | ")} |`)
  ].join("\n");
}

function canRunWithoutImage(item = {}) {
  if (hfwSkillIds.has(item.skillId)) return true;
  if (item.area === "assessment" && ["sentence_comprehension", "key_details", "sequencing", "main_idea", "inference", "cause_effect", "context_clues", "theme"].includes(item.skillId)) return true;
  return !item.imagePath;
}

function replacementNeeded(item = {}) {
  return item.status === "quarantined" && !canRunWithoutImage(item);
}

function replacementPrompt(item = {}) {
  return [
    `Create one clean child-friendly LiteracyPath cartoon image matching this exact ${item.area === "guided_reading" ? "page text" : "question text"}: "${item.text}".`,
    "No photorealistic images, embedded text, watermarks, logos, rainbow/babyish images, AI slop, extra hands/fingers/limbs, distorted faces, malformed animals, or clutter.",
    "The image must match the exact question/text/page."
  ].join(" ");
}

const rows = mergeMediaQaReviewItems(mediaQaReviewItems);
const quarantinedRows = rows
  .filter(row => row.status === "quarantined")
  .map(row => ({
    ...row,
    reason: "teacher_marked_no",
    canRunWithoutImage: canRunWithoutImage(row),
    existingAlternativeImageExists: false,
    kimiReplacementNeeded: replacementNeeded(row)
  }));
const kimiRows = quarantinedRows.filter(row => row.kimiReplacementNeeded);

writeFile(outJson, `${JSON.stringify({
  summary: {
    totalReviewItems: rows.length,
    quarantined: quarantinedRows.length,
    kimiReplacementNeeded: kimiRows.length
  },
  rows: quarantinedRows
}, null, 2)}\n`);

writeFile(outMd, [
  "# Media QA Quarantine Report",
  "",
  "Generated by `npm run export:media-qa-quarantine`.",
  "",
  "## Summary",
  "",
  `- Total review items: ${rows.length}`,
  `- Quarantined items: ${quarantinedRows.length}`,
  `- Kimi replacements needed: ${kimiRows.length}`,
  "",
  "## Quarantined Items",
  "",
  quarantinedRows.length
    ? markdownTable(["Area", "Skill", "Question/Page", "Target", "Text", "Image Path", "Can Run Without Image", "Kimi Needed"], quarantinedRows.map(row => [
      row.area,
      row.displaySkillName || row.skillId,
      row.questionId || row.pageId,
      row.targetWord,
      row.text,
      row.imagePath,
      row.canRunWithoutImage ? "Y" : "N",
      row.kimiReplacementNeeded ? "Y" : "N"
    ]))
    : "None.",
  ""
].join("\n"));

writeFile(kimiCsv, [
  ["area", "skillId", "questionId", "pageId", "bookTitle", "targetWord", "text", "answerChoices", "correctAnswer", "imagePath", "reason", "replacementPrompt"].join(","),
  ...kimiRows.map(row => [
    row.area,
    row.skillId,
    row.questionId,
    row.pageId,
    row.bookTitle,
    row.targetWord,
    row.text,
    (row.answerChoices || []).join(" | "),
    row.correctAnswer,
    row.imagePath,
    row.reason,
    replacementPrompt(row)
  ].map(csvEscape).join(","))
].join("\n") + "\n");

writeFile(kimiMd, [
  "# Kimi Media QA Replacement Request",
  "",
  "Create only simple clean child-friendly LiteracyPath cartoon images. No photorealism, embedded text, watermarks, logos, rainbow/babyish images, AI slop, extra hands/fingers/limbs, distorted faces, malformed animals, or clutter.",
  "",
  `Rows requested: ${kimiRows.length}`,
  "",
  ...kimiRows.map(row => [
    `## ${row.questionId || row.pageId}`,
    "",
    `- Area: ${row.area}`,
    `- Skill/book: ${row.displaySkillName || row.skillId || row.bookTitle}`,
    `- Text: ${row.text}`,
    `- Current image path: ${row.imagePath}`,
    `- Reason: teacher_marked_no`,
    `- Prompt: ${replacementPrompt(row)}`,
    ""
  ].join("\n"))
].join("\n"));

console.log(JSON.stringify({
  totalReviewItems: rows.length,
  quarantined: quarantinedRows.length,
  kimiReplacementNeeded: kimiRows.length,
  report: path.relative(repoRoot, outMd),
  kimiMarkdown: path.relative(repoRoot, kimiMd),
  kimiCsv: path.relative(repoRoot, kimiCsv)
}, null, 2));
