#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { guidedReadingBooks } from "../src/data/guidedReadingBooks.js";
import { auditGuidedReadingQuestionBank } from "./guidedReadingQuestionAuditLib.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const quizDirectory = path.join(repoRoot, "public", "guided-reading", "quizzes");
const outputPath = path.join(repoRoot, "src", "data", "generated", "guidedReadingQuizzes.generated.js");
const audit = auditGuidedReadingQuestionBank({ books: guidedReadingBooks, quizDirectory });

if (audit.failures.length) {
  console.error("Guided Reading quiz index was not generated because validation failed:");
  audit.failures.slice(0, 80).forEach(item => console.error(`- ${item}`));
  process.exit(1);
}

const quizIndex = Object.fromEntries(guidedReadingBooks.map(book => {
  const quizPath = path.join(quizDirectory, `${book.id}.json`);
  const authored = JSON.parse(fs.readFileSync(quizPath, "utf8"));
  return [book.id, {
    bookId: authored.bookId,
    quizVersion: authored.quizVersion,
    contentHash: authored.contentHash,
    questions: authored.questions.map(question => ({
      id: question.id,
      prompt: question.prompt,
      choices: question.choices,
      answer: question.answer,
      kind: question.kind
    }))
  }];
}));

const output = [
  "// Generated by tools/generateGuidedReadingQuizIndex.js. Do not edit by hand.",
  `export const GUIDED_READING_QUIZZES = ${JSON.stringify(quizIndex)};`,
  ""
].join("\n");

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);
console.log(`Generated ${path.relative(repoRoot, outputPath)} with ${Object.keys(quizIndex).length} validated quizzes.`);
