import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { CHILD_COPY } from "../src/copy/childCopy.js";
import {
  STUDENT_HOME_ACTIVITY_TITLES,
  STUDENT_HOME_COPY,
  homeHeroInstruction,
  studentBookPanelAudioText
} from "../src/copy/studentNavigationCopy.js";
import {
  STUDENT_RAIL_HOME,
  STUDENT_RAIL_DESTINATIONS,
  STUDENT_TAB_BAR
} from "../src/policy/studentTabBar.js";
import { selectStudentHomeRecommendation } from "../src/policy/learningPolicy.js";
import { guidedReadingBooks } from "../src/data/guidedReadingBooks.js";
import { GAME_LIST } from "../src/data/learnGamesData.js";
import { QUEST_STOPS } from "../src/data/questSequence.js";
import { elSkillsBlockCycles } from "../src/data/elSkillsBlockCycles.js";
import {
  getLedaInstructionAudioPath,
  getLedaWordAudioPath,
  normalizeLedaAudioText
} from "../src/data/ledaProductionAudio.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const STUDENT_LOGIN_VOICE_LINES = Object.freeze({
  "class-code": CHILD_COPY.signIn.missingCode,
  "who-are-you": CHILD_COPY.signIn.whoAreYou,
  "tap-your-pictures": CHILD_COPY.signIn.pictures,
  "did-not-match": "That did not match.",
  "try-again": CHILD_COPY.actions.tryAgain,
  "ask-teacher": CHILD_COPY.signIn.askTeacher
});

// Enumerate the exact strings passed to speakStudentRailLabel. Full book and
// learning data are build-time inputs only; none enter the student shell.
// Include both shelf states and every title, stop and cycle so adding a long
// recorded phrase works without widening a hand-picked/length-filtered list.
export function getStudentNavigationAudioTexts() {
  const bookTitles = [...new Set(guidedReadingBooks.map(book => book.title))];
  const gameTitles = [...new Set(GAME_LIST.map(game => game.title))];
  return [...new Set([
    ...[STUDENT_RAIL_HOME, ...STUDENT_RAIL_DESTINATIONS, ...STUDENT_TAB_BAR].map(item => item.label),
    ...Object.values(STUDENT_HOME_ACTIVITY_TITLES),
    ...[undefined, { label: "Continue" }, { label: "Teacher picked" }].map(homeHeroInstruction),
    STUDENT_HOME_COPY.explore,
    STUDENT_HOME_COPY.unreadableProgress,
    STUDENT_HOME_COPY.phonicsStop,
    STUDENT_HOME_COPY.storiesStop,
    STUDENT_HOME_COPY.hollowStop,
    selectStudentHomeRecommendation().childReason,
    ...QUEST_STOPS.map(stop => STUDENT_HOME_COPY.soundStop(stop.index, stop.name)),
    ...elSkillsBlockCycles.filter(cycle => cycle.cycleNumber)
      .map(cycle => STUDENT_HOME_COPY.mapStop(cycle.cycleNumber)),
    ...[...bookTitles, STUDENT_HOME_COPY.fallbackBookTitle].map(STUDENT_HOME_COPY.bookStop),
    ...[...gameTitles, STUDENT_HOME_COPY.fallbackGameTitle].map(STUDENT_HOME_COPY.gameStop),
    ...bookTitles.flatMap(title => [
      studentBookPanelAudioText(false, title),
      studentBookPanelAudioText(true, title)
    ])
  ])];
}

function resolveShellAudio(text) {
  // The runtime trims each label before resolving instructions, then words.
  const label = String(text || "").trim();
  return getLedaInstructionAudioPath(label) || getLedaWordAudioPath(label);
}

function verifyAudioFile(key, audioPath) {
  const publicPath = path.join(repoRoot, "public", audioPath.replace(/^\//u, ""));
  if (!fs.existsSync(publicPath) || fs.statSync(publicPath).size === 0) {
    throw new Error(`Missing LEDA shell audio file for ${key}: ${audioPath}`);
  }
}

export function buildShellAudioSources() {
  const loginRows = Object.entries(STUDENT_LOGIN_VOICE_LINES).map(([key, text]) => {
    const audioPath = resolveShellAudio(text);
    if (!audioPath) throw new Error(`Missing approved LEDA shell audio for ${key}: ${text}`);
    verifyAudioFile(key, audioPath);
    return { key, audioPath };
  });
  const navigationRows = new Map();
  for (const text of getStudentNavigationAudioTexts()) {
    const audioPath = resolveShellAudio(text);
    // Missing recordings already stayed silent. Preserve that behavior: never
    // substitute another phrase, concatenate words or start browser speech.
    if (!audioPath) continue;
    verifyAudioFile(text, audioPath);
    navigationRows.set(normalizeLedaAudioText(text.trim()), audioPath);
  }
  const banner = "// Generated by tools/generateShellAudioPaths.mjs. Do not edit by hand.";
  return {
    "src/data/generated/shellAudioPaths.generated.js": [
      banner,
      "// This keeps the first-login shell independent of the multi-megabyte full audio index.",
      "export const STUDENT_LOGIN_VOICE_AUDIO = Object.freeze({",
      ...loginRows.map(row => `  ${JSON.stringify(row.key)}: ${JSON.stringify(row.audioPath)},`),
      "});",
      ""
    ].join("\n"),
    "src/data/generated/studentNavigationAudio.generated.js": [
      banner,
      "// Exact Home, Books and navigation phrases resolved from the canonical LEDA catalogue.",
      "// The lookup stays synchronous so the first play() retains the child's tap gesture.",
      "export const STUDENT_NAVIGATION_AUDIO = Object.freeze({",
      ...[...navigationRows].sort(([a], [b]) => a.localeCompare(b))
        .map(([text, audioPath]) => `  ${JSON.stringify(text)}: ${JSON.stringify(audioPath)},`),
      "});",
      ""
    ].join("\n")
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  for (const [relativePath, source] of Object.entries(buildShellAudioSources())) {
    const outputPath = path.join(repoRoot, relativePath);
    if (check) {
      if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== source) {
        throw new Error(`Stale shell audio projection: ${relativePath}. Run node tools/generateShellAudioPaths.mjs.`);
      }
    } else {
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });
      fs.writeFileSync(outputPath, source);
    }
    console.log(`shell audio paths: ${check ? "verified" : "generated"} ${relativePath} (${Buffer.byteLength(source)} bytes)`);
  }
}
