import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatedDir = path.join(repoRoot, "src", "data", "generated");
const shardDir = path.join(generatedDir, "runtimeShards");

const BANKS = [
  {
    file: "languageSkillQuestions.generated.js",
    exportName: "languageSkillQuestions",
    shardPrefix: "language",
    group(question, _sourceIndex, groupIndexes) {
      const skillId = question.skillId;
      const groupIndex = groupIndexes.get(skillId) || 0;
      groupIndexes.set(skillId, groupIndex + 1);
      return `${skillId}.part-${String.fromCharCode(97 + Math.floor(groupIndex / 80))}`;
    }
  },
  {
    file: "skillLevelGapQuestions.generated.js",
    exportName: "skillLevelGapQuestions",
    shardPrefix: "skill-gap",
    group(question) {
      return question.skillId;
    }
  },
  {
    file: "rhyming.generated.js",
    exportName: "rhymingGeneratedQuestions",
    shardPrefix: "rhyming",
    group(question, _sourceIndex, groupIndexes) {
      const level = Number(question.level || 1) || 1;
      const groupIndex = groupIndexes.get(`level-${level}`) || 0;
      groupIndexes.set(`level-${level}`, groupIndex + 1);
      return `level-${level}.part-${String.fromCharCode(97 + Math.floor(groupIndex / 60))}`;
    }
  },
  {
    file: "hfwAssessmentQuestions.generated.js",
    exportName: "hfwAssessmentQuestions",
    shardPrefix: "hfw",
    group(question, _sourceIndex, groupIndexes) {
      const skillId = question.skillId;
      const groupIndex = groupIndexes.get(skillId) || 0;
      groupIndexes.set(skillId, groupIndex + 1);
      return `${skillId}.part-${String.fromCharCode(97 + Math.floor(groupIndex / 75))}`;
    }
  },
  {
    file: "hfwLevel2Questions.generated.js",
    exportName: "hfwLevel2Questions",
    shardPrefix: "hfw-level-2",
    group(question) {
      return question.skillId;
    }
  }
];

function safeKey(value) {
  return String(value || "unassigned")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function shardSource(bank, shardKey, rows) {
  const provenance = `${bank.file}#${shardKey}`;
  const payload = rows.map(({ question, sourceIndex }) => ({
    ...question,
    __runtimeSourceIndex: sourceIndex
  }));
  return `// Generated by tools/generateRuntimeQuestionBankShards.mjs from ${provenance}. Do not edit by hand.\n`
    + `export const questions = ${JSON.stringify(payload, null, 2)};\n`;
}

function barrelSource(bank, shards) {
  const imports = shards
    .map((shard, index) => `import { questions as shard${index} } from "./runtimeShards/${shard.file}";`)
    .join("\n");
  const spreads = shards.map((_shard, index) => `  ...shard${index}`).join(",\n");
  return `// Generated by tools/generateRuntimeQuestionBankShards.mjs. Do not edit by hand.\n`
    + `// Runtime imports the per-skill shards directly; this complete barrel is for audits and authoring tools.\n`
    + `${imports}\n\n`
    + "function withoutRuntimeIndex(question) {\n"
    + "  const cleanQuestion = { ...question };\n"
    + "  delete cleanQuestion.__runtimeSourceIndex;\n"
    + "  return cleanQuestion;\n"
    + "}\n\n"
    + `export const ${bank.exportName} = [\n${spreads}\n].map(withoutRuntimeIndex);\n`;
}

fs.mkdirSync(shardDir, { recursive: true });
const expectedFiles = new Set();
const summaries = [];

for (const bank of BANKS) {
  const modulePath = path.join(generatedDir, bank.file);
  const moduleUrl = `${pathToFileURL(modulePath).href}?runtime-shards=${Date.now()}`;
  const module = await import(moduleUrl);
  const questions = module[bank.exportName];
  if (!Array.isArray(questions)) {
    throw new Error(`${bank.file} does not export array ${bank.exportName}.`);
  }

  const grouped = new Map();
  const groupIndexes = new Map();
  questions.forEach((question, sourceIndex) => {
    const key = safeKey(bank.group(question, sourceIndex, groupIndexes));
    const rows = grouped.get(key) || [];
    rows.push({ question, sourceIndex });
    grouped.set(key, rows);
  });

  const shards = [...grouped.entries()]
    .map(([key, rows]) => {
      const file = `${bank.shardPrefix}.${key}.generated.js`;
      expectedFiles.add(file);
      fs.writeFileSync(path.join(shardDir, file), shardSource(bank, key, rows));
      return { file, key, count: rows.length };
    });

  fs.writeFileSync(modulePath, barrelSource(bank, shards));
  summaries.push(`${bank.exportName}: ${questions.length} rows -> ${shards.length} shards`);
}

for (const file of fs.readdirSync(shardDir)) {
  if (file.endsWith(".generated.js") && !expectedFiles.has(file)) {
    fs.unlinkSync(path.join(shardDir, file));
  }
}

console.log(`runtime question banks: ${summaries.join("; ")}`);
