import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = path.join(repositoryRoot, "public/audio/production/en-US/supplemental");
const generatedModulePath = path.join(
  repositoryRoot,
  "src/data/generated/ledaRuntimeSupplement.generated.js"
);
const projectId = "project-3c66c1c8-cc9e-4d6d-bdf";
const voiceName = "en-US-Chirp3-HD-Leda";
const endpoint = "https://texttospeech.googleapis.com/v1/text:synthesize";

// These are active runtime words that were represented only by a legacy
// recording and therefore were not present in the first corpus extraction.
const texts = Object.freeze([
  "a blanket fort", "arrange", "athlete", "backpack", "balance", "bathe",
  "borrow", "bow", "cape", "chat", "cheer", "chop", "close", "color",
  "concrete", "connect", "copy", "crib", "decorate", "describe", "divide",
  "dome", "dull", "flip", "fold", "fond", "friendly", "gather", "gray",
  "grin", "guess", "hike", "honest", "invite", "join", "label", "library",
  "lightweight", "listen and find", "lonely", "march", "mole", "patient",
  "pete", "pine", "pretend", "quicksand", "read", "repeat", "rip", "screen",
  "separate", "shadow", "soccer", "sort", "spill", "sprinkle", "stale",
  "stove", "tame", "tickle", "use", "vegetable", "wind",
  // Active arcade/quest words caught by recorded-audio playthrough tests.
  "ax", "string", "tonight", "track", "twist",
  // Human-ear replacements requested during the assessment QA pass. Keeping
  // these in the highest-priority supplement map guarantees every surface
  // stops resolving the earlier production take.
  "hat", "sun",
  "what digraph makes the sh sound as in ship",
  "what digraph makes the ch sound as in chip",
  "what digraph makes the th sound as in think",
  "ask your teacher for the class code",
  "who are you",
  "tap your three secret pictures",
  "that did not match",
  "ask your teacher for help",
  "watch me first",
  "start at the top",
  "now you try",
  "amazing work",
  "build the word you hear",
  "listen then tap the matching word",
  "find the matching sight words"
]);

function slug(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function hash(value) {
  return createHash("sha256").update(value).digest("hex").slice(0, 10);
}

function run(command, args, label) {
  const result = spawnSync(command, args, { encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(`${label} failed: ${String(result.stderr || result.stdout).slice(-1600)}`);
  }
}

async function synthesize(accessToken, record) {
  try {
    if ((await stat(record.mp3Path)).size > 0) return false;
  } catch {
    // Generate it.
  }
  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json; charset=utf-8",
      "x-goog-user-project": projectId
    },
    body: JSON.stringify({
      input: { text: record.text },
      voice: { languageCode: "en-US", name: voiceName },
      audioConfig: { audioEncoding: "LINEAR16", sampleRateHertz: 24000 }
    })
  });
  if (!response.ok) {
    throw new Error(`${record.text} failed with ${response.status}: ${(await response.text()).slice(0, 1000)}`);
  }
  const result = await response.json();
  await writeFile(record.wavPath, Buffer.from(result.audioContent, "base64"));
  return true;
}

await mkdir(outputDirectory, { recursive: true });
const accessToken = execFileSync(
  "gcloud",
  ["auth", "application-default", "print-access-token"],
  { encoding: "utf8" }
).trim();

const records = texts.map(text => {
  const id = `${slug(text)}-${hash(`${voiceName}|${text}`)}`;
  return {
    text,
    wavPath: path.join(outputDirectory, `${id}.wav`),
    mp3Path: path.join(outputDirectory, `${id}.mp3`),
    publicPath: `/audio/production/en-US/supplemental/${id}.mp3`
  };
});

for (let offset = 0; offset < records.length; offset += 8) {
  await Promise.all(
    records.slice(offset, offset + 8).map(record =>
      synthesize(accessToken, record).then(generated => {
        record.generated = generated;
      })
    )
  );
}

for (const record of records) {
  if (!record.generated) continue;
  run(
    "ffmpeg",
    [
      "-y", "-hide_banner", "-loglevel", "error", "-i", record.wavPath,
      "-af", "loudnorm=I=-24:TP=-2:LRA=7,afade=t=in:st=0:d=0.015",
      "-codec:a", "libmp3lame", "-b:a", "128k", record.mp3Path
    ],
    `Normalize ${record.text}`
  );
  await unlink(record.wavPath);
}

const map = Object.fromEntries(records.map(record => [record.text, record.publicPath]));
const moduleText = `// AUTO-GENERATED by tools/generateLedaRuntimeSupplement.mjs - do not edit.\n` +
  `export const LEDA_RUNTIME_SUPPLEMENT_AUDIO = Object.freeze(${JSON.stringify(map, null, 2)});\n`;
await writeFile(generatedModulePath, moduleText);
console.log(`Generated ${records.length} Leda runtime supplement clips.`);
