// Generates a manifest of every audio file under public/ so runtime code can
// check existence instead of probing URLs (the SPA host returns index.html
// for missing files, which stalls audio fallback chains).
// Runs automatically before every build via the "prebuild" npm script.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = path.join(root, "public");
const outFile = path.join(root, "src", "data", "generated", "audioFilePaths.generated.js");
const choiceKeysOutFile = path.join(root, "src", "data", "generated", "audioChoiceKeys.generated.js");
const phonemeOutFile = path.join(root, "src", "data", "generated", "audioPhonemePaths.generated.js");
const guidedReadingOutFile = path.join(root, "src", "data", "generated", "audioGuidedReadingPaths.generated.js");
const questOutFile = path.join(root, "src", "data", "generated", "audioQuestPaths.generated.js");

const files = [];
function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (/\.(mp3|m4a|ogg|wav)$/i.test(entry.name)) {
      files.push("/" + path.relative(publicDir, full).split(path.sep).join("/"));
    }
  }
}
walk(publicDir);
files.sort();

const banner = "// AUTO-GENERATED by tools/generateAudioManifest.js - do not edit.\n";
// Store each directory once instead of repeating it for every file. Runtime
// callers keep the Set-like `.has(path)` contract, while the entry bundle no
// longer pays hundreds of kilobytes for duplicate path prefixes.
const filesByDirectory = {};
for (const file of files) {
  const slash = file.lastIndexOf("/");
  const directory = file.slice(0, slash);
  const name = file.slice(slash + 1);
  (filesByDirectory[directory] ||= []).push(name);
}
const compactDirectories = Object.fromEntries(
  Object.entries(filesByDirectory).map(([directory, names]) => [
    directory,
    names.join("\n")
  ])
);
function renderManifest(directoryMap, exportName) {
  return `${banner}
const AUDIO_FILE_NAMES_BY_DIRECTORY = new Map(
  Object.entries(${JSON.stringify(directoryMap)})
    .map(([directory, names]) => [directory, new Set(names.split("\\n"))])
);

export function hasAudioFilePath(value = "") {
  const path = String(value || "");
  const slash = path.lastIndexOf("/");
  if (slash <= 0 || slash === path.length - 1) return false;
  return AUDIO_FILE_NAMES_BY_DIRECTORY
    .get(path.slice(0, slash))
    ?.has(path.slice(slash + 1)) || false;
}

export const ${exportName} = Object.freeze({ has: hasAudioFilePath });
`;
}

const phonemeDirectories = new Set([
  "/audio/phonemes",
  "/audio/phonemes/reviewed",
  "/audio/quest/alt",
  "/audio/production/en-US/isolated_word",
  "/audio/production/en-US/letter_name",
  "/audio/production/en-US/pattern"
]);
const guidedReadingDirectories = new Set([
  "/audio/production/en-US/guided_page",
  "/audio/production/en-US/supplemental",
  "/audio/production/en-US/isolated_word",
  "/audio/production/en-US/letter_name"
]);
// Quest and arcade audio can resolve instructional, story, supplemental and
// word clips through the shared Leda resolver, so keep the complete lookup in
// this on-demand feature manifest. Guided Reading still gets its own smaller
// manifest and does not pay for this one until a quest/game is opened.
const questDirectories = new Set(Object.keys(compactDirectories));
const selectDirectories = directories => Object.fromEntries(
  Object.entries(compactDirectories).filter(([directory]) => directories.has(directory))
);

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, renderManifest(compactDirectories, "AUDIO_FILE_PATHS"));
fs.writeFileSync(phonemeOutFile, renderManifest(selectDirectories(phonemeDirectories), "AUDIO_PHONEME_PATHS"));
fs.writeFileSync(guidedReadingOutFile, renderManifest(selectDirectories(guidedReadingDirectories), "AUDIO_GUIDED_READING_PATHS"));
fs.writeFileSync(questOutFile, renderManifest(selectDirectories(questDirectories), "AUDIO_QUEST_PATHS"));
const choiceKeys = files
  .map(file => file.match(/^\/audio\/choices\/([0-9a-f]{16})\.mp3$/)?.[1] || "")
  .filter(Boolean);
fs.writeFileSync(
  choiceKeysOutFile,
  `${banner}export const AUDIO_CHOICE_KEYS = new Set(${JSON.stringify(choiceKeys)});\n`
);
console.log(`audio manifest: ${files.length} files -> ${path.relative(root, outFile)}`);
