import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicRoot = path.join(root, "public");
const outputPath = path.join(root, "src/data/generated/assessmentImageVariants.generated.js");

function filesUnder(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true })
    .flatMap(entry => entry.isDirectory()
      ? filesUnder(path.join(directory, entry.name))
      : [path.join(directory, entry.name)]);
}

function publicPath(filePath) {
  return `/${path.relative(publicRoot, filePath).split(path.sep).join("/")}`;
}

function sortedObject(value) {
  return Object.fromEntries(Object.entries(value)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, child]) => [key, Array.isArray(child)
      ? child.slice().sort()
      : sortedObject(child)]));
}

function buildHfwVariants() {
  const rootDirectory = path.join(publicRoot, "images/assessment/hfw/variants");
  const variants = {};
  for (const filePath of filesUnder(rootDirectory)) {
    if (path.extname(filePath).toLowerCase() !== ".webp") continue;
    const relative = path.relative(rootDirectory, filePath).split(path.sep);
    if (relative.length !== 2) continue;
    const [bandDirectory, fileName] = relative;
    if (!/^hfw-\d+-\d+$/.test(bandDirectory)) continue;
    const match = fileName.match(/^(.+)-(l[12]p[12])-\d+\.webp$/i);
    if (!match) continue;
    const band = bandDirectory.replaceAll("-", "_");
    const word = match[1];
    const phase = match[2].toLowerCase();
    variants[band] ||= {};
    variants[band][word] ||= {};
    variants[band][word][phase] ||= [];
    variants[band][word][phase].push(publicPath(filePath));
  }
  return sortedObject(variants);
}

function buildRhymingVariants() {
  const rootDirectory = path.join(publicRoot, "images/assessment/rhyming/variants");
  const variants = {};
  for (const filePath of filesUnder(rootDirectory)) {
    if (path.extname(filePath).toLowerCase() !== ".webp") continue;
    const relative = path.relative(rootDirectory, filePath).split(path.sep);
    if (relative.length !== 2) continue;
    const [family, fileName] = relative;
    const match = fileName.match(/^(.+)-\d+\.webp$/i);
    if (!match) continue;
    const word = match[1];
    variants[family] ||= {};
    variants[family][word] ||= [];
    variants[family][word].push(publicPath(filePath));
  }
  return sortedObject(variants);
}

const hfw = buildHfwVariants();
const rhyming = buildRhymingVariants();
const source = `// Generated by tools/generateAssessmentImageVariants.mjs. Do not hand-edit.\n\n` +
  `export const hfwAssessmentImageVariants = ${JSON.stringify(hfw, null, 2)};\n\n` +
  `export const rhymingAssessmentImageVariants = ${JSON.stringify(rhyming, null, 2)};\n\n` +
  `function normalizeToken(value = "") {\n` +
  `  return String(value || "").toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");\n` +
  `}\n\n` +
  `function pickVariant(paths = [], seed = 0, fallback = "") {\n` +
  `  if (!paths.length) return fallback;\n` +
  `  const index = Math.abs(Number(seed) || 0) % paths.length;\n` +
  `  return paths[index] || fallback;\n` +
  `}\n\n` +
  `export function getHfwAssessmentImageVariant(skillId, word, level, phase, seed = 0, fallback = "") {\n` +
  `  const band = String(skillId || "").replace(/-/g, "_");\n` +
  `  const wordKey = normalizeToken(word);\n` +
  `  const phaseKey = \`l\${Number(level) >= 2 ? 2 : 1}p\${Number(phase) === 2 ? 2 : 1}\`;\n` +
  `  return pickVariant(hfwAssessmentImageVariants[band]?.[wordKey]?.[phaseKey] || [], seed, fallback);\n` +
  `}\n\n` +
  `export function getRhymingAssessmentImageVariant(family, targetWord, seed = 0, fallback = "") {\n` +
  `  const familyKey = normalizeToken(family);\n` +
  `  const targetKey = normalizeToken(targetWord);\n` +
  `  return pickVariant(rhymingAssessmentImageVariants[familyKey]?.[targetKey] || [], seed, fallback);\n` +
  `}\n`;

fs.writeFileSync(outputPath, source);

const hfwCount = Object.values(hfw).flatMap(words => Object.values(words))
  .flatMap(phases => Object.values(phases)).flat().length;
const rhymingCount = Object.values(rhyming).flatMap(words => Object.values(words)).flat().length;
console.log(`Generated assessment image variants: ${hfwCount} HFW and ${rhymingCount} rhyming files.`);
