import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { LEDA_PRODUCTION_AUDIO_BY_ROLE } from "../src/data/generated/ledaProductionAudio.generated.js";
import { LEDA_RUNTIME_SUPPLEMENT_AUDIO } from "../src/data/generated/ledaRuntimeSupplement.generated.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(repoRoot, "src/data/generated/ledaWordAudio.generated.js");
const oneWordSupplement = Object.fromEntries(
  Object.entries(LEDA_RUNTIME_SUPPLEMENT_AUDIO).filter(([text]) => !/\s/u.test(text.trim()))
);
const lookup = Object.freeze({
  ...(LEDA_PRODUCTION_AUDIO_BY_ROLE.letter_name || {}),
  ...(LEDA_PRODUCTION_AUDIO_BY_ROLE.isolated_word || {}),
  ...oneWordSupplement
});

const source = [
  "// Generated by tools/generateLedaWordLookup.mjs. Do not edit by hand.",
  "// Single-word lookup only: full prompts, passages and stories stay route-deferred.",
  `export const LEDA_WORD_AUDIO = Object.freeze(${JSON.stringify(lookup)});`,
  ""
].join("\n");

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, source);
console.log(`LEDA word lookup: ${Object.keys(lookup).length} cues -> ${path.relative(repoRoot, outputPath)}`);
