import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const publicDir = path.join(rootDir, "public");
const outputPath = path.join(rootDir, "src", "data", "publicMediaInventory.js");

const IMAGE_EXTENSIONS = new Set([".webp", ".png", ".jpg", ".jpeg", ".gif", ".svg"]);
const AUDIO_EXTENSIONS = new Set([".mp3", ".wav", ".m4a", ".ogg"]);

function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(fullPath);
    return [fullPath];
  });
}

function titleCase(value = "") {
  return String(value)
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, letter => letter.toUpperCase())
    .trim();
}

function inferTargetWord(filePath = "") {
  const base = path.basename(filePath, path.extname(filePath));
  return titleCase(base.replace(/^\d+[-_]?/, ""));
}

function inferSkill(filePath = "", mediaType = "") {
  const parts = filePath.split("/").filter(Boolean);
  if (filePath.includes("/media/initial-sounds/")) return ["initial_sounds", "Initial Sounds"];
  if (filePath.includes("/guided-reading/")) return ["guided_reading", "Guided Reading"];
  if (filePath.includes("/books/public-domain/")) return ["public_domain_books", "Public-Domain Books"];
  if (filePath.includes("/images/cvc/") || filePath.includes("/audio/child-mode/words/")) return ["assessment_media", "Assessment Media"];
  if (filePath.includes("/images/child-mode/") || filePath.includes("/audio/child-mode/")) return ["child_mode", "Child Mode"];
  if (filePath.includes("/images/comprehension/")) return ["comprehension", "Comprehension"];
  if (filePath.includes("/images/prepositions/")) return ["prepositions", "Prepositions"];
  if (filePath.includes("/images/scenes/")) return ["sentence_picture", "Sentence Picture"];
  if (filePath.includes("/images/generated/")) return ["generated_media", "Generated Media"];
  return [mediaType === "audio" ? "audio_media" : "image_media", mediaType === "audio" ? "Audio Media" : "Image Media"];
}

const records = walk(publicDir)
  .map(file => {
    const extension = path.extname(file).toLowerCase();
    const mediaType = IMAGE_EXTENSIONS.has(extension)
      ? "image"
      : AUDIO_EXTENSIONS.has(extension)
        ? "audio"
        : "";
    if (!mediaType) return null;
    const filePath = `/${path.relative(publicDir, file).split(path.sep).join("/")}`;
    const [skillId, skillName] = inferSkill(filePath, mediaType);
    return {
      id: `${mediaType}:${filePath}`,
      mediaType,
      targetWord: inferTargetWord(filePath),
      skillId,
      skillName,
      level: "",
      filePath,
      linkedQuestionIds: [],
      status: "unreviewed",
      rejectionReason: "",
      reviewerNotes: "",
      reviewedAt: "",
      reviewedBy: "",
      heuristicFlags: [],
      replacementPath: "",
      source: "public_file_inventory",
      exists: true,
      fileSizeBytes: fs.statSync(file).size
    };
  })
  .filter(Boolean)
  .sort((a, b) =>
    a.mediaType.localeCompare(b.mediaType) ||
    a.skillName.localeCompare(b.skillName) ||
    a.filePath.localeCompare(b.filePath)
  );

fs.writeFileSync(
  outputPath,
  `// Generated by tools/generatePublicMediaInventory.js. Do not edit by hand.\nexport const publicMediaInventory = ${JSON.stringify(records, null, 2)};\n`
);

const imageCount = records.filter(record => record.mediaType === "image").length;
const audioCount = records.filter(record => record.mediaType === "audio").length;
console.log(`Generated public media inventory: ${imageCount} images, ${audioCount} audio files.`);
