// GENERATE the "sage-soft" layer — the de-comic-ing of the student sub-pages.
//
// Owner call (2026-07-17): under the sage skin, every student area except the
// Arcade and the Hollow should read like the sage home — soft palette, no
// heavy ink outlines, no hard offset drop-shadows. The comic look is not a
// list of special cases, it is two REPEATED PATTERNS across the comic layer:
//
//   1. thick borders   (>= 2px, usually var(--comic-ink))
//   2. hard shadows    (box-shadow: Npx Npx 0 <ink>, no blur — the pop-art
//                       offset slab)
//
// Hand-overriding hundreds of such rules would drift the moment the comic
// layer changes, so this tool PARSES the comic layer and EMITS one soft
// override per offending rule into src/styles/sage-soft.generated.css:
//
//   border-width  ->  1.5px hairline (semantic border COLOURS are kept —
//                     right/wrong feedback still reads; the palette was
//                     already remapped by sage-subpages.css)
//   box-shadow    ->  one soft ambient shadow
//
// Every emitted selector is scoped to the sage skin and EXEMPTS the Arcade
// and Hollow subtrees, which keep the full comic look by design.
//
//   npm run generate:sage-soft     (also runs in prebuild)

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// Heaviness lives in three layers: the comic reskin, the vibrant student
// layer beneath it, and the shared App.css component styles. All three are
// parsed; the .lp-skin-sage scope keeps every override student-side only.
const SOURCES = [
  path.join(ROOT, "src", "styles", "comic-theme.css"),
  path.join(ROOT, "src", "styles", "student-vibrant.css"),
  path.join(ROOT, "src", "App.css")
];
const OUT = path.join(ROOT, "src", "styles", "sage-soft.generated.css");

const SOFT_SHADOW = "0 1px 3px rgba(30, 40, 30, 0.10)";
const SOFT_BORDER_WIDTH = "1.5px";
const EXEMPT = ":not(:is(.hollow-page, .student-surface-arcade, .companion-picker) *)";

// A hard pop-art shadow: at least one layer shaped "Npx Npx 0[px] <color>"
// (offset slab, zero blur). Soft ambient shadows (with blur) are left alone.
const HARD_SHADOW = /(^|,)\s*(inset\s+)?-?\d+(\.\d+)?px\s+-?\d+(\.\d+)?px\s+0(px)?\s/;

// Border declarations at 2px and above count as "heavy". 1.5px and below is
// already the sage hairline.
function heavyBorderWidth(value) {
  const match = /^(-?\d+(?:\.\d+)?)px/.exec(String(value).trim());
  return match ? Number(match[1]) >= 2 : false;
}

function scopeSelector(selector) {
  const trimmed = selector.trim();
  // Never touch rules that are already skin-, hollow- or arcade-specific.
  if (/lp-skin-sage|lp-home-sage|hollow|arcade/i.test(trimmed)) return null;
  // Keyframe steps and pseudo-roots pass through untouched.
  if (trimmed.startsWith("@") || /^(from|to|\d+%)$/.test(trimmed)) return null;
  const scoped = trimmed.includes(".student-mode-app")
    ? trimmed.replace(/\.student-mode-app/, ".student-mode-app.lp-skin-sage")
    : `.lp-skin-sage ${trimmed}`;
  return `${scoped}${EXEMPT}`;
}

const overrides = [];
let borders = 0;
let shadows = 0;

for (const source of SOURCES) {
const parsed = postcss.parse(fs.readFileSync(source, "utf8"));

parsed.walkRules(rule => {
  if (rule.parent?.type === "atrule" && /keyframes/i.test(rule.parent.name || "")) return;
  const declarations = [];
  rule.walkDecls(decl => {
    const prop = decl.prop.toLowerCase();
    if (prop === "box-shadow" && HARD_SHADOW.test(decl.value)) {
      declarations.push(`box-shadow: ${decl.value.includes("inset") ? "none" : SOFT_SHADOW}`);
      shadows += 1;
    } else if ((prop === "border" || /^border-(top|right|bottom|left)$/.test(prop)) && heavyBorderWidth(decl.value)) {
      const side = prop === "border" ? "border" : prop;
      declarations.push(`${side}-width: ${SOFT_BORDER_WIDTH}`);
      borders += 1;
    } else if (/^border(-(top|right|bottom|left))?-width$/.test(prop) && heavyBorderWidth(decl.value)) {
      declarations.push(`${decl.prop}: ${SOFT_BORDER_WIDTH}`);
      borders += 1;
    } else if (prop === "text-shadow" && HARD_SHADOW.test(decl.value)) {
      declarations.push("text-shadow: none");
      shadows += 1;
    }
  });
  if (!declarations.length) return;
  const scoped = rule.selectors.map(scopeSelector).filter(Boolean);
  if (!scoped.length) return;
  overrides.push(`${scoped.join(",\n")} {\n  ${[...new Set(declarations)].join(";\n  ")};\n}`);
});
}

const banner = `/* GENERATED by tools/generateSageSoft.mjs — do not edit by hand.
   Soft overrides for every heavy comic border/shadow, scoped to the sage
   skin, Arcade + Hollow exempt. Regenerate: npm run generate:sage-soft.
   Sources: comic-theme, student-vibrant, App.css · ${borders} borders softened · ${shadows} shadows feathered. */
`;

fs.writeFileSync(OUT, banner + "\n" + overrides.join("\n\n") + "\n");
console.log(`sage-soft: ${overrides.length} rules (${borders} borders, ${shadows} shadows) -> ${path.relative(ROOT, OUT)}`);
