import fs from 'node:fs';
import { createHash } from 'node:crypto';

// This is the already-published v1 contract, not a new hosted-data migration.
// Practice editorial changes must not change labels beneath server-owned keys.
const migration = new URL('../supabase/migrations/20261006092000_literacy_mock_items.sql', import.meta.url);
const output = new URL('../src/data/generated/literacyMockV1Comprehension.generated.js', import.meta.url);
const sql = fs.readFileSync(migration, 'utf8');
const payload = sql.match(/from jsonb_array_elements\('([\s\S]*)'::jsonb\) item/);
if (!payload) throw new Error('Published mock manifest payload was not found.');
const skills = new Set(['key_details', 'sequencing', 'listen_key_details', 'listen_sequencing']);
const items = JSON.parse(payload[1].replace(/''/g, "'")).filter(item => skills.has(item.skillId));
if (items.length !== 304 || new Set(items.map(item => item.id)).size !== items.length) {
  throw new Error('Published comprehension coverage changed; review the version contract.');
}
const sourceHash = createHash('sha256').update(sql).digest('hex');
const contents = `// Generated by tools/generateLiteracyMockPublishedComprehension.mjs.\n`
  + `// Published literacy-mock-v1 migration SHA-256: ${sourceHash}\n`
  + `// Preserve the private server manifest's exact labels, keys, snapshots and media.\n`
  + `export const LITERACY_MOCK_V1_COMPREHENSION = ${JSON.stringify(items.map(item => item.itemSnapshot))};\n`;
if (process.argv.includes('--check')) {
  if (fs.readFileSync(output, 'utf8') !== contents) throw new Error('Published mock comprehension shard is stale.');
} else {
  fs.writeFileSync(output, contents);
}
console.log(`Published v1 comprehension: ${items.length} items; source ${sourceHash.slice(0, 12)}.`);
