#!/usr/bin/env node
import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { mathsAudioRequests } from "../src/maths/media/mathsAudioSourceManifest.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const voice = "en-US-Chirp3-HD-Leda";
const languageCode = "en-US";
const endpoint = "https://texttospeech.googleapis.com/v1/text:synthesize";
const projectId = process.env.GOOGLE_CLOUD_PROJECT || "project-3c66c1c8-cc9e-4d6d-bdf";
const dryRun = process.argv.includes("--dry-run");
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const hash = value => createHash("sha256").update(value).digest("hex").slice(0, 12);
const slug = value => String(value).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 58);
const unique = new Map();
for (const request of mathsAudioRequests) {
  const key = `${voice}|${request.role}|${request.exactText}`;
  if (!unique.has(key)) unique.set(key, request);
}
function outputFor(request) {
  const fingerprint = hash(`${voice}|${request.role}|${request.exactText}`);
  const fileName = `${slug(request.exactText)}-${fingerprint}.mp3`;
  const publicDir = `/audio/production/en-US/${request.role}`;
  return { absoluteDir: path.join(root, "public", publicDir), absolutePath: path.join(root, "public", publicDir, fileName), publicPath: `${publicDir}/${fileName}`, fingerprint };
}

async function synthesize(token, text, role) {
  for (let attempt = 1; attempt <= 6; attempt += 1) {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json; charset=utf-8", "x-goog-user-project": projectId },
      body: JSON.stringify({
        input: { text },
        voice: { languageCode, name: voice },
        audioConfig: { audioEncoding: "LINEAR16", sampleRateHertz: 24000, speakingRate: role === "maths_song_guide" ? 0.86 : 0.94, pitch: 0 }
      })
    });
    if (response.ok) return Buffer.from((await response.json()).audioContent, "base64");
    const detail = await response.text();
    if (![429, 500, 502, 503, 504].includes(response.status) || attempt === 6) throw new Error(`Leda synthesis failed (${response.status}): ${detail.slice(0, 500)}`);
    await wait(Math.min(30000, 1200 * (2 ** (attempt - 1))));
  }
  throw new Error("Unreachable Leda synthesis state");
}

function normalizeMp3(wavPath, mp3Path) {
  const result = spawnSync("ffmpeg", ["-y", "-hide_banner", "-loglevel", "error", "-i", wavPath, "-af", "highpass=f=60,loudnorm=I=-24:TP=-2:LRA=7,afade=t=in:st=0:d=0.015,afade=t=out:st=0:d=0.025", "-ar", "44100", "-ac", "1", "-codec:a", "libmp3lame", "-b:a", "128k", mp3Path], { encoding: "utf8" });
  if (result.status !== 0) throw new Error(result.stderr || "ffmpeg normalization failed");
}

const uniqueRequests = [...unique.values()];
const token = dryRun ? "" : execFileSync("gcloud", ["auth", "application-default", "print-access-token"], { encoding: "utf8" }).trim();
for (let index = 0; index < uniqueRequests.length; index += 1) {
  const request = uniqueRequests[index];
  const output = outputFor(request);
  await fs.mkdir(output.absoluteDir, { recursive: true });
  const exists = await fs.stat(output.absolutePath).catch(() => null);
  if (!exists && !dryRun) {
    const wavPath = output.absolutePath.replace(/\.mp3$/, ".wav");
    await fs.writeFile(wavPath, await synthesize(token, request.exactText, request.role));
    normalizeMp3(wavPath, output.absolutePath);
    await fs.unlink(wavPath);
    await wait(250);
  }
  console.log(`[${index + 1}/${uniqueRequests.length}] ${request.id} -> ${output.publicPath}`);
}

const manifest = mathsAudioRequests.map(request => {
  const output = outputFor(request);
  return { ...request, voice, publicPath: output.publicPath, fingerprint: output.fingerprint, status: dryRun ? "planned" : "generated-awaiting-listening-review" };
});
if (!dryRun) {
  const generated = ["// AUTO-GENERATED by tools/generateMathsLedaAudio.mjs. Do not edit.", `export const MATHS_LEDA_VOICE = ${JSON.stringify(voice)};`, `export const mathsLedaAudioManifest = Object.freeze(${JSON.stringify(manifest, null, 2)});`, "export const mathsLedaAudioById = new Map(mathsLedaAudioManifest.filter(row => row.status === 'approved').map(row => [row.id, row.publicPath]));", ""].join("\n");
  const generatedDir = path.join(root, "src/maths/media/generated");
  await fs.mkdir(generatedDir, { recursive: true });
  await fs.writeFile(path.join(generatedDir, "mathsLedaAudio.generated.js"), generated);
  await fs.writeFile(path.join(root, ".artifacts/maths-release/maths-audio-review.json"), JSON.stringify({ voice, createdAt: new Date().toISOString(), status: "generated-awaiting-listening-review", requests: manifest }, null, 2));
}
