// Generates a manifest of every audio file under public/ so runtime code can
// check existence instead of probing URLs (the SPA host returns index.html
// for missing files, which stalls audio fallback chains).
// Runs automatically before every build via the "prebuild" npm script.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = path.join(root, "public");
const outFile = path.join(root, "src", "data", "generated", "audioFilePaths.generated.js");
const choiceKeysOutFile = path.join(root, "src", "data", "generated", "audioChoiceKeys.generated.js");

const files = [];
function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (/\.(mp3|m4a|ogg|wav)$/i.test(entry.name)) {
      files.push("/" + path.relative(publicDir, full).split(path.sep).join("/"));
    }
  }
}
walk(publicDir);
files.sort();

const banner = "// AUTO-GENERATED by tools/generateAudioManifest.js - do not edit.\n";
// Store each directory once instead of repeating it for every file. Runtime
// callers keep the Set-like `.has(path)` contract, while the entry bundle no
// longer pays hundreds of kilobytes for duplicate path prefixes.
const filesByDirectory = {};
for (const file of files) {
  const slash = file.lastIndexOf("/");
  const directory = file.slice(0, slash);
  const name = file.slice(slash + 1);
  (filesByDirectory[directory] ||= []).push(name);
}
const compactDirectories = Object.fromEntries(
  Object.entries(filesByDirectory).map(([directory, names]) => [
    directory,
    names.join("\n")
  ])
);
const body = `${banner}
const AUDIO_FILE_NAMES_BY_DIRECTORY = new Map(
  Object.entries(${JSON.stringify(compactDirectories)})
    .map(([directory, names]) => [directory, new Set(names.split("\\n"))])
);

export function hasAudioFilePath(value = "") {
  const path = String(value || "");
  const slash = path.lastIndexOf("/");
  if (slash <= 0 || slash === path.length - 1) return false;
  return AUDIO_FILE_NAMES_BY_DIRECTORY
    .get(path.slice(0, slash))
    ?.has(path.slice(slash + 1)) || false;
}

export const AUDIO_FILE_PATHS = Object.freeze({ has: hasAudioFilePath });
`;
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, body);
const choiceKeys = files
  .map(file => file.match(/^\/audio\/choices\/([0-9a-f]{16})\.mp3$/)?.[1] || "")
  .filter(Boolean);
fs.writeFileSync(
  choiceKeysOutFile,
  `${banner}export const AUDIO_CHOICE_KEYS = new Set(${JSON.stringify(choiceKeys)});\n`
);
console.log(`audio manifest: ${files.length} files -> ${path.relative(root, outFile)}`);
