import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadLiteracyMockBank, LITERACY_MOCK_VERSION, LITERACY_MOCK_VERSIONS, LITERACY_MOCK_SKILLS } from '../src/data/literacyMockBank.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export async function createLiteracyMockManifest({ requireAllMedia = true, contentVersion = LITERACY_MOCK_VERSION } = {}) {
  const authored = await loadLiteracyMockBank({ includeUnavailable: true, contentVersion });
  const unavailable = authored.filter(item => !item.mediaReady);
  if (requireAllMedia && unavailable.length) throw new Error(`${unavailable.length} authored mock items are missing exact required audio.`);
  const bank = authored.filter(item => item.mediaReady);
  for (const item of bank) {
    for (const asset of [...item.requiredAudioPaths, ...item.requiredImagePaths]) {
      if (!asset.startsWith('/') || asset.includes('..') || !fs.existsSync(path.join(root, 'public', asset.split('#')[0]))) {
        throw new Error(`Missing or invalid mock media: ${item.id}: ${asset}`);
      }
    }
  }
  for (const skill of LITERACY_MOCK_SKILLS) for (const level of [1, 2]) {
    if (!bank.some(item => item.skillId === skill.id && item.level === level)) throw new Error(`Mock coverage missing: ${skill.id} level ${level}`);
  }
  return {
    contentVersion,
    itemCount: bank.length,
    unavailableItemIds: unavailable.map(item => item.id),
    items: bank.map(item => ({
      id: item.id, skillId: item.skillId, domainId: item.domainId, level: item.level,
      format: item.format, choices: item.choices, answer: item.answer, answerMode: item.answerMode,
      requiredAudioPaths: item.requiredAudioPaths, itemSnapshot: item.itemSnapshot,
    })),
  };
}

export function literacyMockManifestSql(manifest) {
  if (!LITERACY_MOCK_VERSIONS.includes(manifest.contentVersion)) throw new Error('Unsupported literacy mock content version.');
  if (manifest.unavailableItemIds.length) throw new Error('A hosted manifest cannot omit authored items with unavailable media.');
  if (manifest.itemCount !== manifest.items.length || new Set(manifest.items.map(item => item.id)).size !== manifest.itemCount) {
    throw new Error('A hosted manifest requires an exact count of unique item IDs.');
  }
  const payload = JSON.stringify(manifest.items).replace(/'/g, "''");
  return `-- Generated by tools/generateLiteracyMockManifest.mjs; do not edit item keys by hand.\n`
    + `-- Private canonical answers: no public or student table access.\nbegin;\n`
    + `create temporary table literacy_mock_incoming (item jsonb not null) on commit drop;\n`
    + `insert into literacy_mock_incoming select item from jsonb_array_elements('${payload}'::jsonb) item;\n`
    + `do $publication$ begin\n`
    + `  if exists (select 1 from public.literacy_mock_items old join literacy_mock_incoming incoming on old.id = incoming.item->>'id'\n`
    + `    where old.content_version = '${manifest.contentVersion}' and old.item is distinct from incoming.item) then\n`
    + `    raise exception 'Published mock content is immutable; publish a new version for changed items';\n`
    + `  end if;\nend $publication$;\n`
    + `insert into public.literacy_mock_items (id, content_version, item)\n`
    + `select item->>'id', '${manifest.contentVersion}', item\n`
    + `from literacy_mock_incoming\n`
    + `on conflict (content_version, id) do nothing;\n`
    + `do $publication$ begin\n`
    + `  if (select count(*) from public.literacy_mock_items where content_version = '${manifest.contentVersion}') <> ${manifest.itemCount} then\n`
    + `    raise exception 'Mock publication count differs from the complete authored manifest';\n`
    + `  end if;\n`
    + `  if exists (select 1 from public.literacy_mock_publications where content_version = '${manifest.contentVersion}' and item_count <> ${manifest.itemCount}) then\n`
    + `    raise exception 'Published mock catalogue count is immutable';\n`
    + `  end if;\nend $publication$;\n`
    + `insert into public.literacy_mock_publications (content_version, item_count) values ('${manifest.contentVersion}', ${manifest.itemCount})\n`
    + `on conflict (content_version) do nothing;\ncommit;\n`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const valueAfter = flag => args.includes(flag) ? args[args.indexOf(flag) + 1] : '';
  const allowUnavailable = args.includes('--allow-unavailable');
  try {
    const manifest = await createLiteracyMockManifest({ requireAllMedia: !allowUnavailable,
      contentVersion: valueAfter('--content-version') || LITERACY_MOCK_VERSION });
    const jsonFile = valueAfter('--json');
    const sqlFile = valueAfter('--sql');
    if (jsonFile) {
      fs.mkdirSync(path.dirname(path.resolve(jsonFile)), { recursive: true });
      fs.writeFileSync(jsonFile, `${JSON.stringify(manifest)}\n`);
    }
    if (sqlFile) {
      fs.mkdirSync(path.dirname(path.resolve(sqlFile)), { recursive: true });
      fs.writeFileSync(sqlFile, literacyMockManifestSql(manifest));
    }
    console.log(JSON.stringify({ contentVersion: manifest.contentVersion, itemCount: manifest.itemCount,
      unavailableCount: manifest.unavailableItemIds.length, jsonFile: jsonFile || null, sqlFile: sqlFile || null }));
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
