import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { getRuntimeGuidedReadingBooks } from "../src/utils/guidedReading/runtimeBooks.js";
import { GUIDED_READING_LEVEL_REVIEWS } from "../src/data/guidedReadingLevelReviews.js";
import { GUIDED_READING_LEXILE_MEASURES } from "../src/data/guidedReadingLexileMeasures.js";
import { APP_READING_LEVELS, validateLexileReceipt } from "../src/utils/guidedReading/bookTextAnalysis.js";
import { computeBookTextMetrics, fingerprintBookReadingText, serializeBookReadingText } from "../src/utils/guidedReading/textMetrics.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const target = path.join(root, "src/data/generated/guidedReadingTextAnalysis.generated.js");
const books = getRuntimeGuidedReadingBooks();
const ids = new Set(books.map(book => book.id));
for (const id of Object.keys(GUIDED_READING_LEVEL_REVIEWS)) {
  if (!ids.has(id)) throw new Error(`Remove retired reading-level review ${id}; it is outside the runtime catalogue.`);
}
for (const id of Object.keys(GUIDED_READING_LEXILE_MEASURES)) {
  if (!ids.has(id)) throw new Error(`Lexile receipt ${id} is outside the runtime catalogue.`);
}
const analysis = Object.fromEntries(books.map(book => {
  const review = GUIDED_READING_LEVEL_REVIEWS[book.id];
  const textFingerprint = fingerprintBookReadingText(book);
  if (!review || review.reviewedTextFingerprint !== textFingerprint) {
    throw new Error(`${book.id}: complete a full-text editorial review before generating a new level. Existing review is missing or stale.`);
  }
  if (!APP_READING_LEVELS.includes(review.appReadingLevel) || !review.rationale || !review.reviewedAt) {
    throw new Error(`${book.id}: reading-level review is incomplete.`);
  }
  const textHash = `sha256:${createHash("sha256").update(serializeBookReadingText(book)).digest("hex")}`;
  const receipt = GUIDED_READING_LEXILE_MEASURES[book.id];
  const metrics = computeBookTextMetrics(book);
  const described = metrics.independentlyDescribedPageCount;
  return [book.id, {
    title: book.title,
    appReadingLevel: review.appReadingLevel,
    rationale: review.rationale,
    reviewMethod: review.reviewMethod,
    reviewedAt: review.reviewedAt,
    textFingerprint,
    textHash,
    metrics,
    illustrationSupport: {
      basis: "existing-description-metadata",
      status: described === metrics.pageCount ? "separately-described" : described ? "partly-described" : "text-derived-descriptions-only",
      note: "Picture support is a contextual assumption from the manuscript and available descriptions; this review did not inspect rendered art."
    },
    lexile: receipt ? validateLexileReceipt(receipt, textHash) : {
      status: "pending", measure: null, label: "Lexile pending",
      reason: "No authorized MetaMetrics measurement receipt for this exact text."
    }
  }];
}));
const output = `// Generated by tools/generateGuidedReadingTextAnalysis.mjs. Do not edit.\nexport const GUIDED_READING_TEXT_ANALYSIS = Object.freeze(${JSON.stringify(analysis, null, 2)});\n`;
if (process.argv.includes("--check")) {
  if (fs.readFileSync(target, "utf8") !== output) throw new Error("Guided Reading text analysis is stale. Run node tools/generateGuidedReadingTextAnalysis.mjs.");
} else {
  fs.writeFileSync(target, output);
}
if (process.argv.includes("--report")) {
  const directory = path.join(root, ".artifacts/book-level-analysis");
  fs.mkdirSync(directory, { recursive: true });
  const csvCell = value => `"${String(value ?? "").replaceAll('"', '""')}"`;
  const columns = ["id", "title", "appReadingLevel", "wordCount", "pageCount", "uniqueWordCount", "averageWordsPerSentence", "maxWordsPerSentence", "averageWordsPerPage", "maxWordsPerPage", "lexileStatus", "lexileMeasure", "rationale", "textHash"];
  const rows = Object.entries(analysis).map(([id, row]) => [id, row.title, row.appReadingLevel, row.metrics.wordCount, row.metrics.pageCount, row.metrics.uniqueWordCount, row.metrics.averageWordsPerSentence, row.metrics.maxWordsPerSentence, row.metrics.averageWordsPerPage, row.metrics.maxWordsPerPage, row.lexile.status, row.lexile.measure, row.rationale, row.textHash]);
  fs.writeFileSync(path.join(directory, "guided-reading-level-analysis.csv"), [columns, ...rows].map(row => row.map(csvCell).join(",")).join("\n") + "\n");
}
const distribution = Object.values(analysis).reduce((counts, row) => ({ ...counts, [row.appReadingLevel]: (counts[row.appReadingLevel] || 0) + 1 }), {});
console.log(`${books.length} books have current full-text reviews. App levels: ${JSON.stringify(distribution)}. Lexile measured: ${Object.values(analysis).filter(row => row.lexile.status === "measured").length}.`);
