import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { LEDA_PRODUCTION_AUDIO_BY_ROLE } from "../src/data/generated/ledaProductionAudio.generated.js";
import { LEDA_RUNTIME_SUPPLEMENT_AUDIO } from "../src/data/generated/ledaRuntimeSupplement.generated.js";
import { ASSESSMENT_LEDA_GAP_AUDIO_BY_ROLE } from "../src/data/generated/assessmentLedaGaps.generated.js";
import { CHILD_WORD_AUDIO_OVERRIDES } from "../src/data/childWordAudioOverrides.js";
import { getLedaWordAudioPath } from "../src/data/ledaProductionAudio.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(repoRoot, "src/data/generated/ledaWordAudio.generated.js");
const wordSources = [
  LEDA_PRODUCTION_AUDIO_BY_ROLE.letter_name,
  LEDA_PRODUCTION_AUDIO_BY_ROLE.isolated_word,
  LEDA_RUNTIME_SUPPLEMENT_AUDIO,
  ASSESSMENT_LEDA_GAP_AUDIO_BY_ROLE.letter_name,
  ASSESSMENT_LEDA_GAP_AUDIO_BY_ROLE.isolated_word,
  ASSESSMENT_LEDA_GAP_AUDIO_BY_ROLE.supplemental,
  CHILD_WORD_AUDIO_OVERRIDES
];
const words = [...new Set(wordSources.flatMap(source => Object.keys(source || {})))]
  .filter(text => text.trim() && !/\s/u.test(text.trim()));
// Resolve through the production policy so repairs and reviewed child-word
// overrides retain exactly the same priority in the compact startup lookup.
const lookup = Object.freeze(Object.fromEntries(
  words.map(text => [text, getLedaWordAudioPath(text)]).filter(([, audioPath]) => audioPath)
));

const source = [
  "// Generated by tools/generateLedaWordLookup.mjs. Do not edit by hand.",
  "// Single-word lookup only: full prompts, passages and stories stay route-deferred.",
  `export const LEDA_WORD_AUDIO = Object.freeze(${JSON.stringify(lookup)});`,
  ""
].join("\n");

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, source);
console.log(`LEDA word lookup: ${Object.keys(lookup).length} cues -> ${path.relative(repoRoot, outputPath)}`);
