// Emits a tiny {id, title, level} index of all guided reading books so the
// daily mission (loaded on the student home screen) doesn't pull the full
// book data files into the main bundle. Runs via the npm "prebuild" script.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outFile = path.join(root, "src", "data", "generated", "guidedReadingBookIndex.generated.js");

const { guidedReadingBooks } = await import(path.join(root, "src/data/guidedReadingBooks.js"));

const index = guidedReadingBooks.map(book => ({
  id: book.id,
  title: book.title,
  level: book.level
}));

const banner = "// AUTO-GENERATED by tools/generateBookIndex.js - do not edit.\n";
fs.writeFileSync(outFile, `${banner}export const GUIDED_READING_BOOK_INDEX = ${JSON.stringify(index)};\n`);
console.log(`book index: ${index.length} books -> ${path.relative(root, outFile)}`);

// ── Story questions for the quest's Story Stop station ────────────────────
// Built from the worlds' own book titles ("Muddy Has a Bath" ->
// "Who has a bath?" answer Muddy), so questions always match real stories.
const { guidedReadingSeriesBooks } = await import(path.join(root, "src/data/guidedReadingSeriesBooks.js"));
const WORLD_SERIES = { meadow: "meadow-pals", dino: "dino-pals", moonwood: "moonwood-tales" };
const storyBank = {};
for (const [world, seriesId] of Object.entries(WORLD_SERIES)) {
  const titles = guidedReadingSeriesBooks.filter(b => b.seriesId === seriesId).map(b => b.title);
  const questions = [];
  const names = new Set();
  for (const title of titles) {
    let m = title.match(/^([A-Z][a-z]+)'s (.+)$/);          // "Chompy's Big Lunch"
    if (m) {
      names.add(m[1]);
      questions.push({ prompt: `Who has ${/^(a|an|the) /i.test(m[2]) ? "" : "a "}${m[2].toLowerCase()}?`, answer: m[1] });
      continue;
    }
    m = title.match(/^([A-Z][a-z]+) ((?:[A-Z][a-z']*|and|the|a|an|at|too|up|into)(?: .+)?)$/); // "Muddy Has a Bath"
    if (m && !["The", "What", "One", "Something"].includes(m[1]) && !m[2].startsWith("and ")) {
      names.add(m[1]);
      questions.push({ prompt: `Who ${m[2].toLowerCase().replace(/^won't/, "will not")}?`, answer: m[1] });
    }
  }
  storyBank[world] = { names: [...names], questions };
}
const storyOut = path.join(root, "src", "data", "generated", "questStoryQuestions.generated.js");
fs.writeFileSync(storyOut, `${banner}export const QUEST_STORY_QUESTIONS = ${JSON.stringify(storyBank)};\n`);
console.log(`story questions: ${Object.values(storyBank).map(b => b.questions.length).join("/")} (meadow/dino/moonwood) -> ${path.relative(root, storyOut)}`);
