import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { CHILD_COPY } from "../src/copy/childCopy.js";
import {
  getLedaInstructionAudioPath,
  getLedaWordAudioPath
} from "../src/data/ledaProductionAudio.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(repoRoot, "src/data/generated/shellAudioPaths.generated.js");
const voiceLines = Object.freeze({
  "class-code": CHILD_COPY.signIn.missingCode,
  "who-are-you": CHILD_COPY.signIn.whoAreYou,
  "tap-your-pictures": CHILD_COPY.signIn.pictures,
  "did-not-match": "That did not match.",
  "try-again": CHILD_COPY.actions.tryAgain,
  "ask-teacher": CHILD_COPY.signIn.askTeacher
});

const rows = Object.entries(voiceLines).map(([key, text]) => {
  const audioPath = getLedaInstructionAudioPath(text) || getLedaWordAudioPath(text);
  if (!audioPath) throw new Error(`Missing approved LEDA shell audio for ${key}: ${text}`);
  const publicPath = path.join(repoRoot, "public", audioPath.replace(/^\//u, ""));
  if (!fs.existsSync(publicPath) || fs.statSync(publicPath).size === 0) {
    throw new Error(`Missing LEDA shell audio file for ${key}: ${audioPath}`);
  }
  return { key, text, audioPath };
});

const source = [
  "// Generated by tools/generateShellAudioPaths.mjs. Do not edit by hand.",
  "// This keeps the first-login shell independent of the multi-megabyte full audio index.",
  "export const STUDENT_LOGIN_VOICE_AUDIO = Object.freeze({",
  ...rows.map(row => `  ${JSON.stringify(row.key)}: ${JSON.stringify(row.audioPath)},`),
  "});",
  ""
].join("\n");

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, source);
console.log(`shell audio paths: ${rows.length} verified LEDA cues -> ${path.relative(repoRoot, outputPath)}`);
