// Generates src/data/generated/hfwEligibilityKeys.generated.js — the slim
// id/key/word-set projection of hfwApprovedQuestionBank.generated.js that
// src/data/hfwRuntimeEligibility.js needs at runtime. The full approved bank
// (~1.2MB, every sentence/prompt/image field) stays a tools-only import; the
// runtime bundle only ships the sets plus a {targetWord, level} row per id.
//
// Run: node tools/generateHfwEligibilityKeys.js
// Runs automatically in `npm run prebuild`, and must be re-run after
// `npm run import:approved-hfw-bank` changes the approved bank.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  hfwApprovedQuestionBank,
  hfwApprovedQuestionIds,
  hfwApprovedQuestionContentKeys,
  hfwApprovedQuestionTextKeys,
  hfwApprovedWords,
  hfwApprovedWordsBySkill
} from "../src/data/generated/hfwApprovedQuestionBank.generated.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(repoRoot, "src/data/generated/hfwApprovedQuestionBank.generated.js");
const outputPath = path.join(repoRoot, "src/data/generated/hfwEligibilityKeys.generated.js");

function fail(message) {
  console.error(`generateHfwEligibilityKeys FAILED: ${message}`);
  process.exit(1);
}

if (!Array.isArray(hfwApprovedQuestionBank) || !hfwApprovedQuestionBank.length) {
  fail("approved HFW bank is empty");
}
const badRows = hfwApprovedQuestionBank.filter(row =>
  !row ||
  !String(row.questionId || "") ||
  !String(row.targetWord || "") ||
  !Number.isFinite(Number(row.level))
);
if (badRows.length) {
  fail(`${badRows.length} approved rows missing questionId/targetWord/level (first: ${JSON.stringify(badRows[0]).slice(0, 120)})`);
}
const slimRows = hfwApprovedQuestionBank.map(row => [
  row.questionId,
  { targetWord: row.targetWord, level: row.level }
]);
if (new Set(slimRows.map(([id]) => id)).size !== slimRows.length) {
  fail("approved bank has duplicate questionIds; slim row map would drop rows");
}
if (!hfwApprovedQuestionIds.size || !hfwApprovedQuestionContentKeys.size || !hfwApprovedQuestionTextKeys.size) {
  fail("approved id/content/text key sets are empty");
}
if (!hfwApprovedWords.length || !Object.keys(hfwApprovedWordsBySkill).length) {
  fail("approved word lists are empty");
}

const source = [
  "// Generated by tools/generateHfwEligibilityKeys.js from hfwApprovedQuestionBank.generated.js. Do not hand-edit.",
  "// Slim id/key/word sets for src/data/hfwRuntimeEligibility.js so the runtime",
  "// bundle does not ship the full approved HFW workbook bank.",
  "// Regenerate: node tools/generateHfwEligibilityKeys.js (also runs in prebuild).",
  `export const hfwApprovedQuestionIds = new Set(${JSON.stringify([...hfwApprovedQuestionIds])});`,
  `export const hfwApprovedQuestionContentKeys = new Set(${JSON.stringify([...hfwApprovedQuestionContentKeys])});`,
  `export const hfwApprovedQuestionTextKeys = new Set(${JSON.stringify([...hfwApprovedQuestionTextKeys])});`,
  `export const hfwApprovedWords = ${JSON.stringify(hfwApprovedWords)};`,
  "export const hfwApprovedWordSet = new Set(hfwApprovedWords);",
  `export const hfwApprovedWordsBySkill = ${JSON.stringify(hfwApprovedWordsBySkill)};`,
  "export const hfwApprovedWordSetsBySkill = Object.fromEntries(Object.entries(hfwApprovedWordsBySkill).map(([skillId, words]) => [skillId, new Set(words)]));",
  `export const hfwApprovedRowsByQuestionId = new Map(${JSON.stringify(slimRows)});`,
  ""
].join("\n");

fs.writeFileSync(outputPath, source, "utf8");

const sourceKb = Math.round(fs.statSync(sourcePath).size / 1024);
const outputKb = Math.round(fs.statSync(outputPath).size / 1024);
console.log(
  `Wrote ${path.relative(repoRoot, outputPath)} (${outputKb}KB) from ` +
  `${path.relative(repoRoot, sourcePath)} (${sourceKb}KB): ` +
  `${slimRows.length} rows, ${hfwApprovedQuestionIds.size} ids, ` +
  `${hfwApprovedQuestionContentKeys.size} content keys, ${hfwApprovedQuestionTextKeys.size} text keys, ` +
  `${hfwApprovedWords.length} approved words.`
);
