// Generates a manifest of every audio file under public/ so runtime code can
// check existence instead of probing URLs (the SPA host returns index.html
// for missing files, which stalls audio fallback chains).
// Runs automatically before every build via the "prebuild" npm script.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = path.join(root, "public");
const outFile = path.join(root, "src", "data", "generated", "audioFilePaths.generated.js");

const files = [];
function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (/\.(mp3|m4a|ogg|wav)$/i.test(entry.name)) {
      files.push("/" + path.relative(publicDir, full).split(path.sep).join("/"));
    }
  }
}
walk(publicDir);
files.sort();

const banner = "// AUTO-GENERATED by tools/generateAudioManifest.js - do not edit.\n";
const body = `${banner}export const AUDIO_FILE_PATHS = new Set(${JSON.stringify(files)});\n`;
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, body);
console.log(`audio manifest: ${files.length} files -> ${path.relative(root, outFile)}`);
