// Emits a tiny discovery index of all guided reading books so the
// daily mission (loaded on the student home screen) doesn't pull the full
// book data files into the main bundle. Runs via the npm "prebuild" script.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outFile = path.join(root, "src", "data", "generated", "guidedReadingBookIndex.generated.js");

const { guidedReadingBooks } = await import(path.join(root, "src/data/guidedReadingBooks.js"));
const { getGuidedReadingBookMetadata } = await import(path.join(root, "src/data/guidedReadingBookMetadata.js"));

const index = guidedReadingBooks.map(book => {
  const metadata = getGuidedReadingBookMetadata(book);
  return {
    id: book.id,
    title: book.title,
    level: book.level,
    readingBandProfile: book.readingBandProfile || metadata?.readingBandProfile,
    readingMode: book.readingMode || metadata?.readingMode,
    ...(book.collection ? { collection: book.collection } : {})
  };
});

const banner = "// AUTO-GENERATED by tools/generateBookIndex.js - do not edit.\n";
fs.writeFileSync(outFile, `${banner}export const GUIDED_READING_BOOK_INDEX = ${JSON.stringify(index)};\n`);
console.log(`book index: ${index.length} books -> ${path.relative(root, outFile)}`);

// ── Story questions for the quest's Story Stop station ────────────────────
// Built from the worlds' own book titles. Every question ships the book's COVER
// and printed TITLE, so the round is self-contained: the child reads the
// cover to answer - no prior reading of the book is assumed.
const { guidedReadingSeriesBooks } = await import(path.join(root, "src/data/guidedReadingSeriesBooks.js"));
const WORLD_SERIES = { meadow: "meadow-pals", dino: "dino-pals", moonwood: "moonwood-tales" };
const storyBank = {};
for (const [world, seriesId] of Object.entries(WORLD_SERIES)) {
  const books = guidedReadingSeriesBooks.filter(b => b.seriesId === seriesId);
  const questions = [];
  const names = new Set();
  for (const book of books) {
    const title = book.title;
    const cover = book.coverImage && fs.existsSync(path.join(root, "public", book.coverImage))
      ? book.coverImage
      : "";
    let m = title.match(/^([A-Z][a-z]+)'s (.+)$/);          // "Chompy's Big Lunch"
    if (m) {
      names.add(m[1]);
      questions.push({ prompt: "Whose story is this?", answer: m[1], title, cover });
      continue;
    }
    m = title.match(/^([A-Z][a-z]+) ((?:[A-Z][a-z']*|and|the|a|an|at|too|up|into)(?: .+)?)$/); // "Muddy Has a Bath"
    if (m && !["The", "What", "One", "Something"].includes(m[1]) && !m[2].startsWith("and ")) {
      names.add(m[1]);
      questions.push({ prompt: "Whose story is this?", answer: m[1], title, cover });
    }
  }
  storyBank[world] = { names: [...names], questions };
}
// Picture words verified against the actual files on disk - the asset
// manifest sometimes lists images that do not exist.
const { LETTER_EXAMPLES } = await import(path.join(root, "src/data/elSkillsBlockCycles.js"));
const { getChildWordAsset } = await import(path.join(root, "src/data/childAssets.js"));
const verified = [];
for (const word of new Set(Object.values(LETTER_EXAMPLES).flat().map(w => String(w).toLowerCase()))) {
  try {
    const asset = getChildWordAsset(word, { allowBlockedAssessmentImage: true });
    const image = asset?.image || asset?.fallbackImage;
    if (image && fs.existsSync(path.join(root, "public", image))) verified.push(word);
  } catch { /* skip */ }
}
const storyOut = path.join(root, "src", "data", "generated", "questStoryQuestions.generated.js");
fs.writeFileSync(storyOut, `${banner}export const QUEST_STORY_QUESTIONS = ${JSON.stringify(storyBank)};\nexport const VERIFIED_PICTURE_WORDS = ${JSON.stringify(verified.sort())};\n`);
console.log(`story questions: ${Object.values(storyBank).map(b => b.questions.length).join("/")} (meadow/dino/moonwood) -> ${path.relative(root, storyOut)}`);
