import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { vocabularyMediaLexicon } from "../src/data/vocabularyMediaLexicon.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(
  root,
  "src",
  "data",
  "generated",
  "vocabularyRuntime.generated.js"
);
const skillNames = [
  "initialSounds",
  "finalSounds",
  "rhyming",
  "cvcShortVowels",
  "blends",
  "digraphs",
  "longVowelsSilentE",
  "vowelTeams",
  "rControlledVowels",
  "vocabulary"
];

function skillMask(skills = {}) {
  return skillNames.reduce(
    (mask, skillName, index) => (
      skills[skillName]?.eligible ? mask | (1 << index) : mask
    ),
    0
  );
}

const rows = vocabularyMediaLexicon.map(entry => [
  entry.word,
  entry.normalizedWord === entry.word ? "" : entry.normalizedWord,
  entry.displayWord === entry.word ? "" : entry.displayWord,
  entry.imagePath || "",
  entry.audioPath || "",
  entry.status || "",
  entry.recommendedLevel ?? null,
  entry.difficultyBand || "",
  entry.isImageable !== false,
  entry.tags || [],
  skillMask(entry.skills),
  [
    entry.phonics?.initialSound || "",
    entry.phonics?.finalSound || "",
    entry.phonics?.medialVowel || "",
    entry.phonics?.rimeFamily || "",
    entry.phonics?.syllableCount || 0,
    entry.phonics?.onset || "",
    entry.phonics?.syllableType || "",
    entry.phonics?.vowelPattern || ""
  ],
  entry.notes || ""
]);

const source = `// AUTO-GENERATED by tools/generateVocabularyRuntime.mjs - do not edit.
const SKILL_NAMES = ${JSON.stringify(skillNames)};
const ROWS = ${JSON.stringify(rows)};

export const vocabularyRuntime = ROWS.map(row => {
  const word = row[0];
  const phonics = row[11];
  const skills = {};
  SKILL_NAMES.forEach((skillName, index) => {
    if (row[10] & (1 << index)) skills[skillName] = { eligible: true };
  });
  return {
    word,
    normalizedWord: row[1] || word,
    displayWord: row[2] || word,
    imagePath: row[3],
    audioPath: row[4],
    status: row[5],
    recommendedLevel: row[6],
    difficultyBand: row[7],
    isImageable: row[8],
    tags: row[9],
    skills,
    phonics: {
      initialSound: phonics[0],
      finalSound: phonics[1],
      medialVowel: phonics[2],
      rimeFamily: phonics[3],
      syllableCount: phonics[4],
      onset: phonics[5],
      syllableType: phonics[6],
      vowelPattern: phonics[7]
    },
    notes: row[12]
  };
});
`;

fs.writeFileSync(outputPath, source);
console.log(
  `vocabulary runtime: ${rows.length} compact rows -> ${path.relative(root, outputPath)}`
);
