import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { masterWordLexicon } from "../src/content/lexicon/masterWordLexicon.js";
import { getApprovedAudioPath } from "../src/data/audioPreferenceManifest.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(
  repoRoot,
  "src",
  "content",
  "lexicon",
  "lexiconMediaIndex.generated.js"
);

const rows = masterWordLexicon
  .filter(entry => entry.imageUrl || entry.audioUrl)
  .map(entry => {
    const approvedAudio = getApprovedAudioPath(
      entry.lowercaseWord,
      entry.audioUrl || ""
    );
    return [
      entry.lowercaseWord,
      entry.imageUrl || "",
      approvedAudio,
      entry.source || "existing-media"
    ];
  })
  .filter(([, imageUrl, audioUrl]) => imageUrl || audioUrl)
  .sort((left, right) => left[0].localeCompare(right[0]));

const source = `// Generated by tools/generateLexiconMediaIndex.mjs. Do not edit by hand.
// This is the browser projection of the build-time master lexicon. Keeping
// assessment question banks out of this module preserves their lazy boundary.
export const lexiconMediaRows = Object.freeze(${JSON.stringify(rows)});

const lexiconMediaByWord = new Map(
  lexiconMediaRows.map(([word, imageUrl, audioUrl, source]) => [
    word,
    Object.freeze({ word, imageUrl, audioUrl, source })
  ])
);

export function getLexiconMediaEntry(word) {
  return lexiconMediaByWord.get(String(word || "").toLowerCase()) || null;
}
`;

fs.writeFileSync(outputPath, source);
console.log(`lexicon media: ${rows.length} projected rows -> ${path.relative(repoRoot, outputPath)}`);
