import path from "node:path";

import { hfwAssessmentQuestions } from "../src/data/generated/hfwAssessmentQuestions.generated.js";
import { getAssessmentMediaByPath } from "../src/data/assessmentMediaRegistry.js";
import { writeFile } from "./phonicsRuntimeUtils.js";
import { renderHfwQuestionImageReviewSource } from "./hfwQuestionImageReviewSource.mjs";

const repoRoot = process.cwd();
const outputPath = path.join(repoRoot, "src/data/generated/hfwQuestionImageReview.generated.js");
const hfwSkillIds = new Set(["hfw_1_25", "hfw_26_50", "hfw_51_75", "hfw_76_100"]);

function imagePathFor(question = {}) {
  return String(
    question.imagePath ||
    question.imageUrl ||
    question.image ||
    question.primaryImage ||
    question.questionImage ||
    question.targetImagePath ||
    question.targetImageUrl ||
    question.targetImage ||
    ""
  ).trim();
}

function imagePolicyFor(question = {}) {
  return String(question.imagePolicy || question.hfwImagePolicy || "no_image").trim() || "no_image";
}

function imageSourceFor(imagePath = "", record = null) {
  if (!imagePath) return "";
  return record?.source || record?.sourceType || record?.variantSource || "question_image_path";
}

function replacementPromptFor(question = {}) {
  const sentence = question.fullSentence || question.sentenceText || question.sentenceWithBlank || question.sentence || "";
  return [
    `Create one clean child-friendly LiteracyPath cartoon scene matching this exact sentence: "${sentence}".`,
    "No embedded text, labels, signs, watermarks, logos, photorealism, rainbow/babyish style, AI slop, extra hands/fingers/limbs, or distorted faces."
  ].join(" ");
}

const rows = hfwAssessmentQuestions
  .filter(question => hfwSkillIds.has(question.skillId))
  .map(question => {
    const currentImagePath = imagePathFor(question);
    const record = currentImagePath ? getAssessmentMediaByPath(currentImagePath, "image") : null;
    const imagePolicy = imagePolicyFor(question);
    const qaStatus = currentImagePath
      ? "pending"
      : imagePolicy === "no_image" || imagePolicy === "none"
        ? "no_image_required"
        : "needs_kimi";
    return {
      questionId: question.approvedQuestionId || question.questionId || question.id,
      skillId: question.skillId,
      band: question.band || question.skillId,
      level: Number(question.level || question.difficultyLevel || 1),
      phase: Number(question.phase || question.assessmentPhase || 1),
      targetWord: question.targetWord || question.correctAnswer || question.answer || "",
      questionType: question.questionType || "",
      sentenceWithBlank: question.sentenceWithBlank || question.visibleSentenceWithBlank || question.sentence || "",
      fullSentence: question.fullSentence || question.sentenceText || "",
      correctAnswer: question.correctAnswer || question.answer || "",
      answerChoices: Array.isArray(question.choices)
        ? question.choices
        : (Array.isArray(question.answerOptions)
          ? question.answerOptions.map(option => typeof option === "string" ? option : option.value || option.label || option.text || option.word || "")
          : []),
      letterTiles: Array.isArray(question.letterTiles) ? question.letterTiles : [],
      currentImagePath,
      imageSource: imageSourceFor(currentImagePath, record),
      imageRole: record?.imageRole || "",
      imagePolicy,
      qaStatus,
      rejectionReason: "",
      reviewerNotes: "",
      replacementPrompt: replacementPromptFor(question)
    };
  });

writeFile(
  outputPath,
  renderHfwQuestionImageReviewSource(
    rows,
    "// Generated by tools/generateHfwQuestionImageReview.js. Do not hand-edit unless importing a reviewed workbook."
  )
);

const summary = rows.reduce((counts, row) => {
  counts.total += 1;
  if (row.currentImagePath) counts.withImages += 1;
  counts[row.qaStatus] = (counts[row.qaStatus] || 0) + 1;
  return counts;
}, { total: 0, withImages: 0 });

console.log(JSON.stringify({
  generated: path.relative(repoRoot, outputPath),
  ...summary
}, null, 2));
