import {
  canonicalVisibleText,
  guidedReadingPageKey,
  sha256,
  stableStringify
} from "./guidedReadingAudioPipelineLib.mjs";

export function isGuidedReadingNarrationCleared({
  clearance = {},
  bookId,
  pageNumber,
  displayedText,
  audioPath,
  audioSha256,
  voice
}) {
  const record = clearance[guidedReadingPageKey(bookId, pageNumber)];
  if (!record) return false;
  return record.displayedTextSha256 === sha256(canonicalVisibleText(displayedText))
    && record.audioPath === audioPath
    && record.audioSha256 === audioSha256
    && record.voice === voice;
}

export function buildGuidedReadingNarrationProvenanceModule({
  audit,
  voice,
  exactOverrides = {}
}) {
  const exactPlaceholder = "__GUIDED_READING_EXACT_PAGE_AUDIO__";
  const payload = {
    schemaVersion: 2,
    generatedBy: "tools/checkGuidedReadingNarrationProvenance.mjs --refresh",
    voice,
    liveBookCount: audit.activeBookCount,
    livePageCount: audit.livePageCount,
    productionManifestPageCount: audit.productionManifestPageCount,
    productionManifestSha256: audit.productionManifestSha256,
    corpusSha256: audit.corpusSha256,
    narrationRebuildClearanceSha256: audit.narrationRebuildClearanceSha256,
    auditedWordSequenceMismatchCount: audit.wordSequenceMismatchCount,
    auditedPageAudioTextMismatchCount: audit.pageAudioTextMismatchCount,
    auditedAudioHashMismatchCount: 0,
    resolvedNormalizedCollisionCount: audit.normalizedCollisionCount,
    exactPageAudioByText: exactPlaceholder
  };
  const serialized = stableStringify(payload, 2);
  const exactSerialized = stableStringify(exactOverrides, 2);
  return (
    "// AUTO-GENERATED by tools/checkGuidedReadingNarrationProvenance.mjs --refresh.\n" +
    "// Refresh is refused unless every live page resolves to non-empty exact-text Leda audio.\n" +
    `export const GUIDED_READING_NARRATION_PROVENANCE = Object.freeze(${serialized.replace(
      JSON.stringify(exactPlaceholder),
      `Object.freeze(${exactSerialized})`
    )});\n`
  );
}
