import fs from "node:fs";
import path from "node:path";
import ExcelJS from "exceljs";

import { normalizeHfwSentenceFrame } from "../src/data/hfwQualityRules.js";

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const workbookPath = path.join(repoRoot, "docs", "review", "hfw_question_review.xlsx");
const outputPath = path.join(repoRoot, "src", "data", "generated", "hfwQuestionReviewBlocklist.generated.js");

function normalizeDecision(value = "") {
  const text = String(value || "").trim().toUpperCase();
  if (["N", "NO", "REJECT", "REJECTED", "DELETE"].includes(text)) return "rejected";
  return "accepted";
}

function readCell(row, headerMap, key) {
  const index = headerMap.get(key);
  return index ? String(row.getCell(index).value ?? "").trim() : "";
}

function jsString(value = "") {
  return JSON.stringify(String(value ?? ""));
}

function writeBlocklist(rows) {
  const body = rows.map(row => `  {
    questionId: ${jsString(row.questionId)},
    skillId: ${jsString(row.skillId)},
    targetWord: ${jsString(row.targetWord)},
    sentenceWithBlank: ${jsString(row.sentenceWithBlank)},
    fullSentence: ${jsString(row.fullSentence)},
    contentKey: ${jsString(row.contentKey)},
    sentenceFrame: ${jsString(row.sentenceFrame)},
    reason: ${jsString(row.reason)},
    reviewNotes: ${jsString(row.reviewNotes)}
  }`).join(",\n");
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, `// Generated by tools/importHfwQuestionReviewWorkbook.js. Do not hand-edit.\n\nexport const hfwQuestionReviewBlocklist = [\n${body}\n];\nexport const hfwQuestionReviewBlockedIds = new Set(hfwQuestionReviewBlocklist.map(row => row.questionId));\nexport const hfwQuestionReviewBlockedContentKeys = new Set(hfwQuestionReviewBlocklist.flatMap(row => row.contentKey ? [row.contentKey] : []));\nexport const hfwQuestionReviewBlockedSentenceFrames = new Set(hfwQuestionReviewBlocklist.flatMap(row => row.sentenceFrame ? [row.sentenceFrame] : []));\n`);
}

if (!fs.existsSync(workbookPath)) {
  writeBlocklist([]);
  console.log("HFW review workbook not found; created empty blocklist and skipped import.");
  process.exit(0);
}

const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile(workbookPath);
const sheet = workbook.getWorksheet("All HFW") || workbook.worksheets.find(ws => ws.name.startsWith("HFW "));
if (!sheet) {
  writeBlocklist([]);
  console.log("HFW review workbook has no review sheet; created empty blocklist and skipped import.");
  process.exit(0);
}

const headerMap = new Map();
sheet.getRow(1).eachCell((cell, colNumber) => {
  headerMap.set(String(cell.value || "").trim(), colNumber);
});

const rejected = [];
let changedRows = 0;
sheet.eachRow((row, rowNumber) => {
  if (rowNumber === 1) return;
  const decision = normalizeDecision(readCell(row, headerMap, "acceptable"));
  const reviewNotes = readCell(row, headerMap, "review_notes");
  const reason = readCell(row, headerMap, "delete_reason");
  if (decision !== "accepted" || reviewNotes || reason) changedRows += 1;
  if (decision !== "rejected") return;
  const sentenceWithBlank = readCell(row, headerMap, "sentence_with_blank");
  const targetWord = readCell(row, headerMap, "target_word");
  rejected.push({
    questionId: readCell(row, headerMap, "question_id"),
    skillId: readCell(row, headerMap, "skill_id"),
    targetWord,
    sentenceWithBlank,
    fullSentence: readCell(row, headerMap, "full_sentence"),
    contentKey: readCell(row, headerMap, "content_key"),
    sentenceFrame: `${targetWord}::${normalizeHfwSentenceFrame(sentenceWithBlank)}`,
    reason: reason || "Rejected by teacher review.",
    reviewNotes
  });
});

writeBlocklist(rejected);
console.log(JSON.stringify({
  workbookPath: path.relative(repoRoot, workbookPath),
  changedRows,
  rejected: rejected.length,
  reviewPending: changedRows === 0
}, null, 2));
