import fs from "node:fs";
import path from "node:path";
import ExcelJS from "exceljs";

import { writeFile } from "./phonicsRuntimeUtils.js";

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const workbookPath = path.join(repoRoot, "docs", "image-qa", "review-data", "image_qa_review.xlsx");
const blocklistPath = path.join(repoRoot, "src", "data", "generated", "imageQaReviewBlocklist.generated.js");
const auditJsonPath = path.join(repoRoot, "docs", "validation", "image_qa_review_import_audit.json");
const auditMdPath = path.join(repoRoot, "docs", "validation", "image_qa_review_import_audit.md");

function normalizeDecision(value = "") {
  const text = String(value || "").trim().toUpperCase();
  if (["N", "NO", "REJECT", "REJECTED", "DELETE"].includes(text)) return "rejected";
  if (text === "REVIEW") return "review_needed";
  return "accepted";
}

function cell(row, headers, key) {
  const index = headers.get(key);
  return index ? String(row.getCell(index).value ?? "").trim() : "";
}

function writeGenerated(rows) {
  const body = rows.map(row => `  ${JSON.stringify(row)}`).join(",\n");
  writeFile(blocklistPath, `// Generated by tools/importImageQaReview.js. Do not hand-edit.\n\nexport const imageQaReviewBlocklist = [\n${body}\n];\nexport const imageQaReviewBlockedPaths = new Set(imageQaReviewBlocklist\n  .filter(row => row.status === "rejected")\n  .map(row => row.path));\nexport const imageQaReviewNeededPaths = new Set(imageQaReviewBlocklist\n  .filter(row => row.status === "review_needed")\n  .map(row => row.path));\n`);
}

if (!fs.existsSync(workbookPath)) {
  writeGenerated([]);
  writeFile(auditJsonPath, `${JSON.stringify({ importSkipped: true, reason: "review workbook missing", blocked: 0, reviewNeeded: 0 }, null, 2)}\n`);
  writeFile(auditMdPath, "# Image QA Review Import Audit\n\nReview workbook missing; import skipped.\n");
  console.log("Image QA review workbook missing; created empty blocklist and skipped import.");
  process.exit(0);
}

const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile(workbookPath);
const sheet = workbook.getWorksheet("Review");
if (!sheet) {
  writeGenerated([]);
  console.log("Image QA review sheet missing; created empty blocklist and skipped import.");
  process.exit(0);
}

const headers = new Map();
sheet.getRow(1).eachCell((cellValue, colNumber) => headers.set(String(cellValue.value || "").trim(), colNumber));
const rows = [];
let changedRows = 0;
sheet.eachRow((row, rowNumber) => {
  if (rowNumber === 1) return;
  const status = normalizeDecision(cell(row, headers, "acceptable"));
  const replacementNeeded = cell(row, headers, "replacement_needed").toUpperCase();
  const issueType = cell(row, headers, "issue_type");
  const notes = cell(row, headers, "reviewer_notes");
  if (status !== "accepted" || replacementNeeded === "Y" || issueType || notes) changedRows += 1;
  if (status === "accepted" && replacementNeeded !== "Y") return;
  rows.push({
    imageId: cell(row, headers, "image_id"),
    path: cell(row, headers, "path"),
    area: cell(row, headers, "area"),
    targetWord: cell(row, headers, "target_word"),
    skillId: cell(row, headers, "skill_id"),
    status,
    replacementNeeded: replacementNeeded === "Y",
    issueType,
    severity: cell(row, headers, "severity"),
    reviewerNotes: notes,
    contactSheet: cell(row, headers, "contact_sheet"),
    contactSheetPosition: cell(row, headers, "contact_sheet_position")
  });
});

writeGenerated(rows);
const audit = {
  importSkipped: changedRows === 0,
  reviewPending: changedRows === 0,
  changedRows,
  blocked: rows.filter(row => row.status === "rejected").length,
  reviewNeeded: rows.filter(row => row.status === "review_needed").length,
  replacementRequests: rows.filter(row => row.replacementNeeded || row.status === "rejected").length,
  rows
};
writeFile(auditJsonPath, `${JSON.stringify(audit, null, 2)}\n`);
writeFile(auditMdPath, [
  "# Image QA Review Import Audit",
  "",
  `- Review pending: ${audit.reviewPending ? "yes" : "no"}`,
  `- Blocked images: ${audit.blocked}`,
  `- Review-needed images: ${audit.reviewNeeded}`,
  `- Replacement request candidates: ${audit.replacementRequests}`,
  ""
].join("\n"));
console.log(JSON.stringify(audit, null, 2));
