import fs from "node:fs";
import path from "node:path";
import ExcelJS from "exceljs";

import { hfwQuestionImageReviewRows } from "../src/data/generated/hfwQuestionImageReview.generated.js";
import { writeFile } from "./phonicsRuntimeUtils.js";
import { renderHfwQuestionImageReviewSource } from "./hfwQuestionImageReviewSource.mjs";

const repoRoot = process.cwd();
const workbookPath = path.join(repoRoot, "docs/review/hfw_question_image_review.xlsx");
const outputPath = path.join(repoRoot, "src/data/generated/hfwQuestionImageReview.generated.js");
const auditPath = path.join(repoRoot, "docs/validation/hfw_question_image_review_import_audit.json");
const allowedStatuses = new Set(["pending", "approved", "rejected", "needs_kimi", "no_image_required"]);

function normalizeHeader(value = "") {
  return String(value || "").trim().toLowerCase();
}

function valueText(value = "") {
  if (value && typeof value === "object" && "text" in value) return String(value.text || "").trim();
  return String(value ?? "").trim();
}

function normalizeStatus(value = "") {
  const status = normalizeHeader(value).replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return allowedStatuses.has(status) ? status : "";
}

function nextStatus({ acceptable = "", qaStatus = "", imagePath = "", replacementNeeded = "" } = {}) {
  const accepted = valueText(acceptable).toUpperCase();
  const replacement = valueText(replacementNeeded).toUpperCase();
  if (accepted === "Y") return imagePath ? "approved" : "no_image_required";
  if (accepted === "N") return replacement === "Y" ? "needs_kimi" : "rejected";
  const explicit = normalizeStatus(qaStatus);
  if (explicit) return explicit;
  return imagePath ? "pending" : "no_image_required";
}

function readSheetRows(sheet) {
  const headerRow = sheet.getRow(1);
  const headers = {};
  headerRow.eachCell((cell, colNumber) => {
    headers[normalizeHeader(cell.value)] = colNumber;
  });
  const rows = [];
  sheet.eachRow((row, rowNumber) => {
    if (rowNumber === 1) return;
    const questionId = valueText(row.getCell(headers.question_id).value);
    if (!questionId) return;
    rows.push({
      questionId,
      qaStatus: valueText(row.getCell(headers.qa_status).value),
      acceptable: valueText(row.getCell(headers.acceptable).value),
      rejectionReason: valueText(row.getCell(headers.rejection_reason).value),
      reviewerNotes: valueText(row.getCell(headers.reviewer_notes).value),
      currentImagePath: valueText(row.getCell(headers.image_path).value),
      imageRole: valueText(row.getCell(headers.image_role).value),
      imagePolicy: valueText(row.getCell(headers.image_policy).value),
      replacementNeeded: valueText(row.getCell(headers.replacement_needed).value)
    });
  });
  return rows;
}

if (!fs.existsSync(workbookPath)) {
  writeFile(auditPath, JSON.stringify({ imported: 0, skipped: true, reason: "workbook_missing" }, null, 2) + "\n");
  console.log("HFW question image review workbook missing; import skipped.");
  process.exit(0);
}

const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile(workbookPath);
const reviewedRows = workbook.worksheets.flatMap(readSheetRows);
const reviewedByQuestionId = new Map(reviewedRows.map(row => [row.questionId, row]));
let imported = 0;

const rows = hfwQuestionImageReviewRows.map(row => {
  const reviewed = reviewedByQuestionId.get(row.questionId);
  if (!reviewed) return row;
  imported += 1;
  const currentImagePath = reviewed.currentImagePath || row.currentImagePath || "";
  return {
    ...row,
    currentImagePath,
    imageRole: reviewed.imageRole || row.imageRole || "",
    imagePolicy: reviewed.imagePolicy || row.imagePolicy || "no_image",
    qaStatus: nextStatus({
      acceptable: reviewed.acceptable,
      qaStatus: reviewed.qaStatus,
      imagePath: currentImagePath,
      replacementNeeded: reviewed.replacementNeeded
    }),
    rejectionReason: reviewed.rejectionReason || "",
    reviewerNotes: reviewed.reviewerNotes || ""
  };
});

writeFile(
  outputPath,
  renderHfwQuestionImageReviewSource(
    rows,
    "// Generated by tools/importHfwQuestionImageReviewWorkbook.js. Do not hand-edit unless importing a reviewed workbook."
  )
);
writeFile(auditPath, JSON.stringify({
  imported,
  totalGeneratedRows: rows.length,
  byStatus: rows.reduce((counts, row) => {
    counts[row.qaStatus] = (counts[row.qaStatus] || 0) + 1;
    return counts;
  }, {})
}, null, 2) + "\n");

console.log(JSON.stringify({
  imported,
  generated: path.relative(repoRoot, outputPath),
  audit: path.relative(repoRoot, auditPath)
}, null, 2));
