import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const defaultPackageRoot = path.join(
  repoRoot,
  "outputs",
  "019fa860-9b95-77b1-9e50-ff7ce1c92ea3",
  "production-final",
  "2026-07-28"
);
const packageRoot = path.resolve(process.argv[2] || defaultPackageRoot);
const manifestPath = path.join(packageRoot, "production-manifest.json");
const deliveryRoot = path.join(packageRoot, "delivery");
const generatedModulePath = path.join(
  repoRoot,
  "src",
  "data",
  "generated",
  "ledaProductionAudio.generated.js"
);

function normalizeText(value = "") {
  return String(value || "")
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[’‘]/g, "'")
    .replace(/[“”]/g, "\"")
    .replace(/[–—]/g, "-")
    .replace(/\s+/g, " ")
    .replace(/[.!?]+$/g, "")
    .trim();
}

function sourceReferenceCount(record) {
  return String(record.sourceReferences || "")
    .split(/\r?\n/)
    .filter(Boolean)
    .length;
}

function preferredRecord(current, candidate) {
  if (!current) return candidate;
  const currentReferences = sourceReferenceCount(current);
  const candidateReferences = sourceReferenceCount(candidate);
  if (candidateReferences !== currentReferences) {
    return candidateReferences > currentReferences ? candidate : current;
  }
  return candidate.proposedOutputPath.localeCompare(current.proposedOutputPath) < 0
    ? candidate
    : current;
}

if (!fs.existsSync(manifestPath)) {
  throw new Error(`Leda production manifest not found: ${manifestPath}`);
}

const production = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
const records = (production.records || []).filter(record => (
  record.result === "packaged"
  && record.audioRole !== "phoneme"
  && record.proposedOutputPath
  && record.mp3Path
));

const byRole = new Map();
let copied = 0;
for (const record of records) {
  const relativePublicPath = record.proposedOutputPath.replace(/^\/+/, "");
  const sourcePath = path.join(deliveryRoot, relativePublicPath);
  const destinationPath = path.join(repoRoot, "public", relativePublicPath);
  if (!fs.existsSync(sourcePath)) {
    throw new Error(`Packaged Leda file is missing: ${sourcePath}`);
  }
  fs.mkdirSync(path.dirname(destinationPath), { recursive: true });
  fs.copyFileSync(sourcePath, destinationPath);
  copied += 1;

  const role = String(record.audioRole || "").trim();
  const text = normalizeText(record.spokenText);
  if (!role || !text) continue;
  const roleMap = byRole.get(role) || new Map();
  roleMap.set(text, preferredRecord(roleMap.get(text), record));
  byRole.set(role, roleMap);
}

const generatedRoleMaps = Object.fromEntries(
  [...byRole.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([role, roleMap]) => [
      role,
      Object.fromEntries(
        [...roleMap.entries()]
          .sort(([left], [right]) => left.localeCompare(right))
          .map(([text, record]) => [text, record.proposedOutputPath])
      )
    ])
);

const banner = "// AUTO-GENERATED by tools/installLedaProductionAudio.mjs - do not edit.\n";
const moduleSource = `${banner}
export const LEDA_PRODUCTION_VOICE = ${JSON.stringify(production.defaultVoice || "en-US-Chirp3-HD-Leda")};
export const LEDA_PRODUCTION_AUDIO_BY_ROLE = Object.freeze(${JSON.stringify(generatedRoleMaps)});
export const LEDA_PRODUCTION_AUDIO_ROLES = Object.freeze(${JSON.stringify([...byRole.keys()].sort())});
`;

fs.mkdirSync(path.dirname(generatedModulePath), { recursive: true });
fs.writeFileSync(generatedModulePath, moduleSource);

console.log(JSON.stringify({
  packageRoot,
  copied,
  roles: Object.fromEntries(
    [...byRole.entries()].map(([role, roleMap]) => [role, roleMap.size])
  ),
  generatedModule: path.relative(repoRoot, generatedModulePath)
}, null, 2));
