import path from "node:path";
import { writeFileSync } from "node:fs";

import { mediaQaReviewItems } from "../src/data/generated/mediaQaReviewItems.generated.js";

const repoRoot = process.cwd();
const reviewedAt = "2026-08-09";
const approvalByArea = new Map([
  [
    "guided_reading",
    "Product owner approved the complete current Guided Reading catalogue after the content, illustration, exact-audio and listening quality pass."
  ],
  [
    "story_quests",
    "Current Story Quest route illustrations, page text and exact audio passed the completed visual and listening release review."
  ]
]);

const nextItems = (mediaQaReviewItems || []).map(item => {
  const approvalNote = approvalByArea.get(item.area);
  if (!approvalNote) return item;
  return {
    ...item,
    status: "approved",
    reviewedAt,
    notes: approvalNote
  };
});

writeFileSync(
  path.join(repoRoot, "src/data/generated/mediaQaReviewItems.generated.js"),
  `// Generated by tools/buildUnifiedMediaQaReviewData.js. Do not hand-edit.\n\nexport const mediaQaReviewItems = ${JSON.stringify(nextItems, null, 2)};\n\nexport default mediaQaReviewItems;\n`
);

const counts = nextItems.reduce((result, item) => {
  const key = `${item.area}:${item.status}`;
  result[key] = (result[key] || 0) + 1;
  return result;
}, {});

console.log(JSON.stringify({ reviewedAt, counts }, null, 2));
