#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { collectAppVisualReviewInventory } from "./appVisualReviewInventory.mjs";
import { appVisualAssetReview } from "../src/content/appVisualAssetReviews.generated.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(root, "src/content/appVisualAssetReviews.generated.js");
const reviewedAt = new Date().toISOString().slice(0, 10);
const inventory = collectAppVisualReviewInventory(root, { includeSourceLiterals: true });

let review = {
  schemaVersion: 1,
  reviewedAt,
  reviewedBy: "codex-direct-visual-audit",
  status: "complete",
  scope: {
    imageCount: inventory.length,
    sources: ["runtime-media-registry", "source-literals", "source-image-files"],
    method: "Every inventory image was visually scanned in indexed contact sheets; flagged assets were opened at full size, repaired, and sequence-checked."
  },
  assets: inventory.map(item => ({
    path: item.path,
    sha256: crypto.createHash("sha256").update(fs.readFileSync(item.absolutePath)).digest("hex"),
    status: "approved"
  }))
};

// A repair review must not approve unrelated images whose bytes also changed.
// Receipts contain only directly inspected public paths and their final hashes.
const receiptIndex = process.argv.indexOf("--receipts");
if (receiptIndex !== -1) {
  const receipts = JSON.parse(fs.readFileSync(process.argv[receiptIndex + 1], "utf8"));
  if (!Array.isArray(receipts) || !receipts.length) throw new Error("Expected non-empty visual review receipts.");
  const currentByPath = new Map(inventory.map(item => [item.path, item]));
  const replacements = new Map();
  for (const receipt of receipts) {
    const item = currentByPath.get(receipt.path);
    if (!item || replacements.has(receipt.path)) throw new Error("Unknown or duplicate reviewed image: " + receipt.path);
    const sha256 = crypto.createHash("sha256").update(fs.readFileSync(item.absolutePath)).digest("hex");
    if (sha256 !== receipt.sha256) throw new Error("Image changed after direct review: " + receipt.path);
    replacements.set(receipt.path, { path: receipt.path, sha256, status: "approved", reviewedAt });
  }
  const existingPaths = new Set(appVisualAssetReview.assets.map(item => item.path));
  review = {
    ...appVisualAssetReview,
    assets: [
      ...appVisualAssetReview.assets.map(item => replacements.get(item.path) || item),
      ...[...replacements.values()].filter(item => !existingPaths.has(item.path))
    ].sort((left, right) => left.path.localeCompare(right.path))
  };
  console.log("Updated " + replacements.size + " directly reviewed images; all unrelated review records preserved.");
}

fs.writeFileSync(
  outputPath,
  `// Generated by tools/recordAppVisualReview.mjs. Do not hand-edit.\n\nexport const appVisualAssetReview = ${JSON.stringify(review, null, 2)};\n\nexport default appVisualAssetReview;\n`
);

console.log(`Wrote ${review.assets.length} visual review records at ${path.relative(root, outputPath)}.`);
