#!/usr/bin/env node
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { guidedReadingBooks } from "../src/data/guidedReadingBooks.js";
import {
  buildGuidedReadingAudioInventory,
  stableStringify
} from "./guidedReadingAudioPipelineLib.mjs";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(
  repositoryRoot,
  "src/data/generated/guidedReadingNarrationClearance.generated.js"
);
const writeClearance = process.argv.includes("--write");
const inventory = buildGuidedReadingAudioInventory(guidedReadingBooks, repositoryRoot);

const preflightFailed = Boolean(
  inventory.pageAudioTextMismatchCount || inventory.unresolvedNormalizedCollisionCount
);
if (preflightFailed && writeClearance) {
  console.error(stableStringify({
    error: "Narration clearance refused: page text metadata or normalized keys are ambiguous.",
    pageAudioTextMismatchCount: inventory.pageAudioTextMismatchCount,
    unresolvedNormalizedCollisionCount: inventory.unresolvedNormalizedCollisionCount,
    pageAudioTextMismatches: inventory.pageAudioTextMismatches.map(row => ({
      key: row.key,
      displayedText: row.displayedText,
      pageAudioText: row.declaredPageAudioText
    })),
    collisions: inventory.collisions.filter(row => !row.resolved)
  }, 2));
  process.exit(1);
}

const flagged = inventory.pages.filter(row => row.narrationNeedsRebuild);
// Rebuild the complete clearance ledger, not only entries that happen to be
// open under the previously generated ledger. A delta-only rewrite would drop
// every already-cleared page on the next process load and reopen the corpus.
const clearable = inventory.pages.filter(row => row.exactLedaAudioResolves);
const blocked = flagged.filter(row => !row.exactLedaAudioResolves);
const clearance = Object.fromEntries(clearable.map(row => [row.key, {
  displayedText: row.displayedText,
  displayedTextSha256: row.displayedTextSha256,
  audioPath: row.audioPath,
  audioSha256: row.audioSha256,
  voice: inventory.voice
}]));

if (writeClearance) {
  const moduleText =
    "// AUTO-GENERATED by tools/refreshGuidedReadingNarrationClearance.mjs --write.\n" +
    "// A page is present only when its current visible text resolves to a non-empty exact-text Leda file.\n" +
    "// Consumers must compare both hashes before treating narrationNeedsRebuild as cleared.\n" +
    `export const GUIDED_READING_NARRATION_CLEARANCE = Object.freeze(${stableStringify(clearance, 2)});\n`;
  writeFileSync(outputPath, moduleText);
}

console.log(stableStringify({
  mode: writeClearance ? "write" : "dry-run",
  voice: inventory.voice,
  activeBooks: inventory.activeBookCount,
  activePages: inventory.livePageCount,
  preflightPassed: !preflightFailed,
  pageAudioTextMismatchCount: inventory.pageAudioTextMismatchCount,
  unresolvedNormalizedCollisionCount: inventory.unresolvedNormalizedCollisionCount,
  narrationNeedsRebuild: flagged.length,
  clearable: clearable.length,
  blocked: blocked.length,
  output: writeClearance ? path.relative(repositoryRoot, outputPath) : null,
  // Keep routine output focused on pages that were actually awaiting
  // clearance. The generated ledger above still contains every exact page.
  clearablePages: flagged.filter(row => row.exactLedaAudioResolves).map(row => ({
    key: row.key,
    audioPath: row.audioPath,
    displayedTextSha256: row.displayedTextSha256,
    audioSha256: row.audioSha256
  })),
  blockedPages: blocked.map(row => ({
    key: row.key,
    reason: !row.audioPath
      ? "missing_audio_mapping"
      : !row.audioExists
        ? "missing_audio_file"
        : !row.transcriptMatches
          ? "transcript_mismatch"
          : !row.pageAudioTextMatches
            ? "page_audio_text_mismatch"
      : "not_exact_leda",
    displayedText: row.displayedText
  })),
  ...(preflightFailed ? {
    pageAudioTextMismatches: inventory.pageAudioTextMismatches.map(row => ({
      key: row.key,
      displayedText: row.displayedText,
      pageAudioText: row.declaredPageAudioText
    })),
    unresolvedNormalizedCollisions: inventory.collisions.filter(row => !row.resolved)
  } : {})
}, 2));
if (!writeClearance && preflightFailed) process.exitCode = 1;
