#!/usr/bin/env node

import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { LEDA_PRODUCTION_AUDIO_BY_ROLE, LEDA_PRODUCTION_AUDIO_ROLES } from "../src/data/generated/ledaProductionAudio.generated.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const words = ["vase", "umbrella"];
const voice = "en-US-Chirp3-HD-Leda";
const remakeTag = "clear-child-word-v1";
const endpoint = "https://texttospeech.googleapis.com/v1/text:synthesize";
const projectId = process.env.GOOGLE_CLOUD_PROJECT || "project-3c66c1c8-cc9e-4d6d-bdf";

const hash = value => createHash("sha256").update(value).digest("hex").slice(0, 10);
const publicPathFor = word => `/audio/production/en-US/isolated_word/${word}-${hash(`${voice}|isolated_word|${remakeTag}|${word}`)}.mp3`;
const absolutePathFor = word => path.join(root, "public", publicPathFor(word).replace(/^\//, ""));

function run(command, args, label) {
  const result = spawnSync(command, args, { encoding: "utf8" });
  if (result.status !== 0) throw new Error(`${label}: ${result.stderr || result.stdout || "command failed"}`);
  return result.stdout.trim();
}

function normalizeAudio(sourcePath, outputPath) {
  run("ffmpeg", [
    "-y", "-hide_banner", "-loglevel", "error", "-i", sourcePath,
    "-af", "highpass=f=60,loudnorm=I=-24:TP=-2:LRA=7,afade=t=in:st=0:d=0.015,areverse,afade=t=in:st=0:d=0.025,areverse",
    "-ar", "44100", "-ac", "1", "-codec:a", "libmp3lame", "-b:a", "128k", outputPath
  ], "ffmpeg normalization failed");
}

function validateAudio(filePath) {
  const duration = Number(run("ffprobe", [
    "-v", "error", "-show_entries", "format=duration", "-of", "default=noprint_wrappers=1:nokey=1", filePath
  ], "ffprobe duration check failed"));
  if (!Number.isFinite(duration) || duration <= 0) throw new Error(`Invalid word audio duration: ${filePath}`);
  const loudness = spawnSync("ffmpeg", [
    "-hide_banner", "-nostats", "-i", filePath, "-af", "volumedetect", "-f", "null", "-"
  ], { encoding: "utf8" });
  const peak = Number(loudness.stderr?.match(/max_volume:\s*(-?[\d.]+) dB/u)?.[1]);
  if (loudness.status !== 0 || !Number.isFinite(peak) || peak <= -40) {
    throw new Error(`Word audio is silent or inaudible: ${filePath}`);
  }
  return Number(duration.toFixed(3));
}

function accessToken() {
  return execFileSync("gcloud", ["auth", "application-default", "print-access-token"], { encoding: "utf8" }).trim();
}

async function synthesize(token, word) {
  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json; charset=utf-8",
      "x-goog-user-project": projectId
    },
    body: JSON.stringify({
      input: { text: word },
      voice: { languageCode: "en-US", name: voice },
      audioConfig: {
        audioEncoding: "LINEAR16",
        sampleRateHertz: 24000,
        speakingRate: 0.9,
        pitch: 0
      }
    })
  });
  if (!response.ok) throw new Error(`Google Text-to-Speech ${response.status}: ${(await response.text()).slice(0, 300)}`);
  const audioContent = (await response.json()).audioContent;
  if (!audioContent) throw new Error(`Google Text-to-Speech returned no audio for ${word}`);
  return Buffer.from(audioContent, "base64");
}

const token = accessToken();
const isolatedWord = { ...(LEDA_PRODUCTION_AUDIO_BY_ROLE.isolated_word || {}) };
const durations = {};

for (const word of words) {
  const outputPath = absolutePathFor(word);
  const wavPath = `${outputPath}.tmp.wav`;
  const mp3Path = `${outputPath}.tmp.mp3`;
  await mkdir(path.dirname(outputPath), { recursive: true });
  await rm(wavPath, { force: true });
  await rm(mp3Path, { force: true });
  await writeFile(wavPath, await synthesize(token, word));
  normalizeAudio(wavPath, mp3Path);
  durations[word] = validateAudio(mp3Path);
  await rename(mp3Path, outputPath);
  await rm(wavPath, { force: true });
  isolatedWord[word] = publicPathFor(word);
  console.log(`${word}: ${isolatedWord[word]} (${durations[word]}s)`);
}

const generated = {
  ...LEDA_PRODUCTION_AUDIO_BY_ROLE,
  isolated_word: isolatedWord
};
const generatedPath = path.join(root, "src/data/generated/ledaProductionAudio.generated.js");
const generatedSource = [
  "// AUTO-GENERATED by tools/installLedaProductionAudio.mjs - do not edit.",
  `export const LEDA_PRODUCTION_VOICE = ${JSON.stringify(voice)};`,
  `export const LEDA_PRODUCTION_AUDIO_BY_ROLE = Object.freeze(${JSON.stringify(generated)});`,
  `export const LEDA_PRODUCTION_AUDIO_ROLES = Object.freeze(${JSON.stringify(LEDA_PRODUCTION_AUDIO_ROLES)});`,
  ""
].join("\n");
const generatedTempPath = `${generatedPath}.${process.pid}.tmp`;
await writeFile(generatedTempPath, generatedSource);
await rename(generatedTempPath, generatedPath);

execFileSync(process.execPath, [path.join(root, "tools/generateLedaWordLookup.mjs")], { stdio: "inherit" });
console.log(`Remade ${words.length} Leda word clips.`);
