import { createHash } from "node:crypto";

function collectChunkClosure(bundle, seeds) {
  const selected = new Set();
  const visit = fileName => {
    if (!fileName || selected.has(fileName)) return;
    const item = bundle[fileName];
    if (!item || item.type !== "chunk") return;
    selected.add(fileName);
    for (const imported of item.imports || []) visit(imported);
  };
  for (const seed of seeds) visit(seed);
  return selected;
}

function serviceWorkerSource({ buildId, precache }) {
  return `/* Literacy Path offline shell ${buildId}. Generated by Vite. */
const BUILD_ID = ${JSON.stringify(buildId)};
const SHELL_PREFIX = "lp-shell-";
const SHELL_CACHE = SHELL_PREFIX + BUILD_ID;
const QUEST_MEDIA_CACHE = "lp-quest-media-v1";
const PRECACHE = ${JSON.stringify(precache)};
const QUEST_MEDIA_PREFIXES = [
  "/game-assets/quest-pixel/",
  "/game-assets/sound-seekers/worlds/",
  "/audio/music/quest/"
];

function isQuestMedia(pathname) {
  return QUEST_MEDIA_PREFIXES.some(prefix => pathname.startsWith(prefix));
}

function isCacheable(response) {
  return Boolean(response && response.ok && (response.type === "basic" || response.type === "default"));
}

async function notifyClients(message) {
  const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
  for (const client of clients) client.postMessage({ ...message, buildId: BUILD_ID });
}

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    for (const url of PRECACHE) {
      const response = await fetch(new Request(url, { cache: "reload", credentials: "same-origin" }));
      if (!isCacheable(response)) throw new Error("Offline precache failed: " + url);
      await cache.put(url, response);
    }
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter(name => name.startsWith(SHELL_PREFIX) && name !== SHELL_CACHE)
      .map(name => caches.delete(name)));
    await self.clients.claim();
    await notifyClients({ type: "LP_OFFLINE_SHELL_READY", precached: PRECACHE.length });
  })());
});

async function navigationResponse(request) {
  const shell = await caches.open(SHELL_CACHE);
  try {
    const response = await fetch(request);
    if (isCacheable(response)) await shell.put(request, response.clone());
    return response;
  } catch {
    const direct = await shell.match(request, { ignoreSearch: true });
    if (direct) return direct;
    const url = new URL(request.url);
    const fallback = url.pathname.startsWith("/preview/") ? "/preview/quest.html" : "/index.html";
    return shell.match(fallback, { ignoreSearch: true });
  }
}

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (isCacheable(response)) await cache.put(request, response.clone());
  return response;
}

async function questMediaResponse(request) {
  const cache = await caches.open(QUEST_MEDIA_CACHE);
  const cached = await cache.match(request, { ignoreSearch: true });
  const update = fetch(request).then(async response => {
    if (isCacheable(response)) await cache.put(request, response.clone());
    return response;
  });
  if (cached) {
    update.catch(() => {});
    return cached;
  }
  return update;
}

self.addEventListener("fetch", event => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === "navigate") {
    event.respondWith(navigationResponse(request));
    return;
  }
  if (url.pathname.startsWith("/assets/") || PRECACHE.includes(url.pathname)) {
    event.respondWith(cacheFirst(request, SHELL_CACHE));
    return;
  }
  if (isQuestMedia(url.pathname)) event.respondWith(questMediaResponse(request));
});

self.addEventListener("message", event => {
  const data = event.data || {};
  if (data.type === "LP_OFFLINE_STATUS") {
    event.source?.postMessage({ type: "LP_OFFLINE_SHELL_READY", buildId: BUILD_ID, precached: PRECACHE.length });
    return;
  }
  if (data.type === "LP_OFFLINE_UPDATE_STATUS") {
    event.source?.postMessage({ type: "LP_OFFLINE_UPDATE_READY", buildId: BUILD_ID, precached: PRECACHE.length });
    return;
  }
  if (data.type !== "LP_WARM_QUEST_ASSETS") return;
  event.waitUntil((async () => {
    const urls = [...new Set(Array.isArray(data.urls) ? data.urls : [])]
      .map(value => new URL(value, self.location.origin))
      .filter(url => url.origin === self.location.origin && isQuestMedia(url.pathname));
    const cache = await caches.open(QUEST_MEDIA_CACHE);
    let completed = 0;
    let failed = 0;
    for (const url of urls) {
      try {
        const response = await fetch(new Request(url.href, { credentials: "same-origin" }));
        if (!isCacheable(response)) throw new Error("Uncacheable response");
        await cache.put(url.href, response);
        completed += 1;
      } catch {
        const existing = await cache.match(url.href, { ignoreSearch: true });
        if (existing) completed += 1;
        else failed += 1;
      }
    }
    event.source?.postMessage({
      type: "LP_QUEST_WARM_COMPLETE",
      buildId: BUILD_ID,
      requestId: data.requestId || "",
      chapterId: data.chapterId || "",
      requested: urls.length,
      completed,
      failed
    });
  })());
});
`;
}

export function questOfflinePlugin({ includeQuestPreview = false, buildVariant = "" } = {}) {
  return {
    name: "literacy-path-quest-offline",
    apply: "build",
    generateBundle(_, bundle) {
      const chunks = Object.values(bundle).filter(item => item.type === "chunk");
      const entries = chunks.filter(chunk => chunk.isEntry).map(chunk => chunk.fileName);
      const questEntries = chunks
        .filter(chunk => /QuestRoot|QuestPixelWorld/.test(chunk.fileName)
          || /\/QuestRoot\.jsx$|\/QuestPixelWorld\.jsx$/.test(chunk.facadeModuleId || ""))
        .map(chunk => chunk.fileName);
      const selectedChunks = collectChunkClosure(bundle, [...entries, ...questEntries]);
      const selected = new Set([...selectedChunks].map(fileName => `/${fileName}`));
      selected.add("/index.html");
      if (includeQuestPreview) {
        selected.add("/preview/quest.html");
        selected.add("/preview/quest-evidence.html");
      }

      for (const item of Object.values(bundle)) {
        if (item.type !== "asset" || !item.fileName.endsWith(".html")) continue;
        selected.add(`/${item.fileName}`);
        const html = String(item.source || "");
        for (const match of html.matchAll(/(?:src|href)="(\/[^"?#]+)[^"]*"/g)) {
          if (match[1].startsWith("/assets/")) selected.add(match[1]);
        }
      }
      for (const item of Object.values(bundle)) {
        if (item.type === "asset" && item.fileName.endsWith(".css")) {
          selected.add(`/${item.fileName}`);
        }
      }
      selected.add("/favicon.svg");
      selected.add("/icons.svg");
      selected.add("/manifest.webmanifest");

      const fingerprint = createHash("sha256");
      fingerprint.update(String(buildVariant));
      for (const url of [...selected].sort()) {
        fingerprint.update(url);
        const item = bundle[url.slice(1)];
        if (item?.type === "chunk") fingerprint.update(item.code || "");
        if (item?.type === "asset") fingerprint.update(String(item.source || ""));
      }
      const buildId = fingerprint.digest("hex").slice(0, 16);
      const precache = [...selected].sort();

      const manifest = {
        name: "Literacy Path",
        short_name: "Literacy Path",
        description: "Phonics, reading and Sound Seekers learning journeys.",
        start_url: "/",
        scope: "/",
        display: "standalone",
        background_color: "#f1f5f9",
        theme_color: "#0c6b65",
        icons: [{ src: "/favicon.svg", sizes: "any", type: "image/svg+xml", purpose: "any maskable" }]
      };
      this.emitFile({ type: "asset", fileName: "manifest.webmanifest", source: `${JSON.stringify(manifest, null, 2)}\n` });
      this.emitFile({
        type: "asset",
        fileName: "offline-build.json",
        source: `${JSON.stringify({
          buildId,
          precache,
          executablePolicy: "build-versioned",
          questMediaPolicy: "cache-while-revalidate",
          updatePolicy: "activate-after-existing-clients-close"
        }, null, 2)}\n`
      });
      this.emitFile({ type: "asset", fileName: "sw.js", source: serviceWorkerSource({ buildId, precache }) });
    }
  };
}
