import test from "node:test";
import assert from "node:assert/strict";
import {
  createAdventureRun,
  recordAdventureOutcome,
  feedbackForOutcome,
  cycleQuestResult
} from "../../src/components/elQuest/adventureRunState.js";
import {
  buildStationRounds,
  stationsForCycle
} from "../../src/components/elQuest/elQuestEngine.js";
import { elSkillsBlockCycles } from "../../src/data/elSkillsBlockCycles.js";

const GENERATED_CONSTRUCT_CASES = [
  ["visual_letter_identity", /big|small/],
  ["visual_grapheme_identity", /grapheme|pattern/],
  ["heard_phoneme_grapheme_mapping", /sound|choose/],
  ["heard_ending_sound_family_mapping", /ending|sound/],
  ["initial_phoneme_discrimination", /start/],
  ["ending_grapheme_pattern_discrimination", /end/],
  ["high_frequency_word_recognition", /whole word/],
  ["phoneme_grapheme_encoding", /build|sound/],
  ["onset_substitution", /change|word parts/],
  ["onset_removal", /remove|word parts/],
  ["compound_word_joining", /join|word parts/],
  ["connected_print_tracking", /printed|line/],
  ["supported_cover_title_association", /title|cover/],
  ["letter_formation_practice", /trace/],
  ["grapheme_pattern_formation_practice", /trace/],
  ["orthographic_pattern_sort", /ending|pattern|target/],
  ["grapheme_substitution_chain", /change|grapheme|word/],
  ["supported_phrase_reading", /phrase|line/],
  ["orthographic_memory", /whole heart word|memory|spell/]
];

test("a recovered item keeps its failed first attempt", () => {
  let state = createAdventureRun(2);
  state = recordAdventureOutcome(state, { roundIndex: 0, correct: false, selected: "m" });
  state = recordAdventureOutcome(state, { roundIndex: 0, correct: true, selected: "s" });
  assert.equal(state.firstAttempts[0], false);
  assert.equal(state.completed, 1);
  assert.equal(cycleQuestResult(state).stars, 1);
});

test("seven of ten independent first attempts earn two stars", () => {
  const result = cycleQuestResult({ total: 10, completed: 10, firstAttempts: [true, true, true, true, true, true, true, false, false, false] });
  assert.deepEqual(result, { stars: 2, independentPercent: 70 });
});

test("recording an outcome does not mutate the prior run", () => {
  const state = createAdventureRun(1);
  const next = recordAdventureOutcome(state, { roundIndex: 0, correct: true, selected: "s" });
  assert.notEqual(next, state);
  assert.deepEqual(state.firstAttempts, [null]);
  assert.equal(state.completed, 0);
  assert.deepEqual(next.firstAttempts, [true]);
  assert.equal(next.completed, 1);
});

test("feedback names the selected onset and the target contrast", () => {
  const round = {
    construct: "initial_phoneme_discrimination",
    targetGrapheme: "s",
    answer: "sun",
    objects: [
      { word: "moon", matches: false },
      { word: "sun", matches: true }
    ]
  };
  assert.equal(
    feedbackForOutcome(round, { correct: false, selected: "m" }, 1),
    "m starts moon. Listen for /s/ at the start of sun."
  );
});

test("feedback remains construct-specific on later coaching attempts", () => {
  const round = {
    construct: "ending_grapheme_pattern_discrimination",
    targetGrapheme: "ng",
    answer: "ring"
  };
  const feedback = feedbackForOutcome(round, { correct: false, selected: "ball" }, 2);
  assert.match(feedback, /ball/);
  assert.match(feedback, /ng/);
  assert.match(feedback, /end/);
  assert.doesNotMatch(feedback, /Almost! Try again\./);
});

test("a failed item without supported recovery earns no star", () => {
  const result = cycleQuestResult({
    total: 2,
    completed: 1,
    recoveries: 0,
    firstAttempts: [false, null]
  });
  assert.equal(result.stars, 0);
});

test("every generated construct has selected-target feedback", () => {
  for (const [construct, marker] of GENERATED_CONSTRUCT_CASES) {
    const feedback = feedbackForOutcome(
      { construct, targetGrapheme: "s", answer: "sun", beforeWord: "run", afterWord: "sun", word: "sun" },
      { correct: false, selected: "wrong" },
      1
    );
    assert.match(feedback, /wrong/, `${construct} must name the selected response`);
    assert.match(feedback, marker, `${construct} must name its construct-specific contrast`);
    assert.doesNotMatch(feedback, /Compare it with the target/, `${construct} must not use generic feedback`);
    assert.doesNotMatch(feedback, /Listen for \/s\/ and choose s/, `${construct} must not use sound-choice feedback`);
  }
});

test("feedback coverage matches every construct currently generated by Adventure Map", () => {
  const generatedConstructs = new Set();
  for (const cycle of elSkillsBlockCycles.filter(item => item.cycleNumber)) {
    for (const station of stationsForCycle(cycle)) {
      for (const round of buildStationRounds(cycle, station.id)) {
        generatedConstructs.add(round.construct);
      }
    }
  }

  assert.deepEqual(
    [...generatedConstructs].sort(),
    GENERATED_CONSTRUCT_CASES.map(([construct]) => construct).sort()
  );
});
