import { useEffect, useEffectEvent, useRef, useState } from 'react';
import { createWorld } from '../world.js';
import { createAudio } from '../audio.js';
import { PROJECTS, ACTS, CHAPTER_AUDIO, activityDeck, retryFor } from './content.js';
import { SAVE_KEY, freshChapter, parseChapter, currentAct, currentRound, available, lights, repairs, finishedRounds, judgeChoice, settleChapter, claimReward, selectProject } from './progress.js';
import { CHAPTER_ROADS, guideRoute } from './paths.js';
import { decorateChapter } from './scenery.js';
import { Icon, Flower, Lantern } from './ui.jsx';

function readSave(){try{return parseChapter(localStorage.getItem(SAVE_KEY));}catch{return null;}}

export default function Chapter(){
  const [saved,setSaved]=useState(readSave),[p,setP]=useState(()=>saved||freshChapter());
  const [phase,setPhase]=useState('title'),[paused,setPaused]=useState(false),[mapOpen,setMapOpen]=useState(false);
  const [ready,setReady]=useState(false),[error,setError]=useState(null),[epoch,setEpoch]=useState(0),[gentle,setGentle]=useState(false);
  const [muted,setMuted]=useState(p.settings.muted),[reduced,setReduced]=useState(p.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches),[low,setLow]=useState(p.settings.low);
  const [near,setNear]=useState(false),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(null),[audioNotice,setAudioNotice]=useState(false);
  const [loaded,setLoaded]=useState({}),[pictureError,setPictureError]=useState(false),[imageRevision,setImageRevision]=useState(0);
  const host=useRef(),world=useRef(),audio=useRef(),player=useRef(p.position),marker=useRef(),panel=useRef(),activityTitle=useRef();
  const progress=useRef(p),mode=useRef('title'),stopped=useRef(false),busyRef=useRef(false),mutedRef=useRef(muted);
  const keys=useRef(new Set()),touch=useRef(new Set()),timers=useRef(new Set()),token=useRef(0),correctStarted=useRef(0);
  const act=currentAct(p),round=currentRound(p),job=p.jobs[p.active],reward=ACTS.find(a=>a.id===p.rewardAct);
  const picturesReady=round.kind==='onset'?round.choices.every(c=>loaded[c.picture]):loaded[round.picture];
  const imagePath=source=>source+'?r='+imageRevision;
  const imageLoaded=source=>setLoaded(old=>({...old,[source]:true}));
  function changePhase(value){mode.current=value;setPhase(value);}
  function changePaused(value){stopped.current=value;setPaused(value);}
  function changeBusy(value){busyRef.current=value;setBusy(value);}
  function save(value){const next=typeof value==='function'?value(progress.current):value;const positioned={...next,position:player.current};progress.current=positioned;setP(positioned);try{localStorage.setItem(SAVE_KEY,JSON.stringify(positioned));}catch{/* Restricted storage does not stop local play. */}return positioned;}
  function clearTimers(){token.current++;timers.current.forEach(clearTimeout);timers.current.clear();}
  function delay(fn,ms){const id=setTimeout(()=>{timers.current.delete(id);fn();},ms);timers.current.add(id);}
  function clearInput(){keys.current.clear();touch.current.clear();world.current?.move(0,0);}
  function move(){if(stopped.current||mode.current!=='explore'){world.current?.move(0,0);return;}const held=new Set([...keys.current,...touch.current]);world.current?.move(Number(held.has('right'))-Number(held.has('left')),Number(held.has('down'))-Number(held.has('up')));}
  function speak(cues){if(stopped.current)return Promise.resolve(false);setAudioNotice(false);return audio.current?.sequence(Array.isArray(cues)?cues:[cues])||Promise.resolve(false);}
  function cue(){const now=progress.current;if(mode.current==='activity')return now.jobs[now.active].pending?currentRound(now).correctAudio:currentRound(now).promptAudio;if(mode.current==='reward')return 'done-'+now.rewardAct;if(mode.current==='complete')return 'chapter-finish';return 'story-'+currentAct(now).id;}
  async function replay(){const ticket=token.current;await audio.current?.unlock();if(ticket===token.current&&!stopped.current)speak(cue());}
  function resetUi(){setFeedback(null);setPictureError(false);changeBusy(false);}
  function preloadAct(){const active=currentAct(progress.current);const deck=activityDeck(active,progress.current.seed);audio.current?.preload(['story-'+active.id,'done-'+active.id,...new Set(deck.flatMap(r=>[...r.promptAudio,...r.correctAudio,...r.choices.map(c=>c.audio)]))]);}
  function advance(){if(stopped.current||mode.current!=='activity'||!progress.current.jobs[progress.current.active].pending)return;const next=save(settleChapter(progress.current));resetUi();changePhase(next.mode);speak(next.mode==='reward'?'done-'+next.rewardAct:currentRound(next).promptAudio);}
  function afterCorrect(){const ticket=token.current;const current=()=>ticket===token.current&&!stopped.current&&mode.current==='activity'&&progress.current.jobs[progress.current.active].pending;Promise.resolve(speak(currentRound(progress.current).correctAudio)).then(heard=>{if(current())delay(()=>{if(current())advance();},Math.max(heard?450:0,1600-(performance.now()-correctStarted.current)));});}
  async function pause(value){clearTimers();changePaused(value);clearInput();if(value){audio.current?.stop();return;}const ticket=token.current;await audio.current?.unlock();if(ticket!==token.current||stopped.current)return;if(mode.current==='activity'&&progress.current.jobs[progress.current.active].pending)afterCorrect();else speak(cue());}
  async function toggleMute(value){mutedRef.current=value;setMuted(value);audio.current?.setMuted(value);save(old=>({...old,settings:{...old.settings,muted:value}}));if(mode.current==='title'||stopped.current)return;if(progress.current.jobs[progress.current.active].pending&&mode.current==='activity'){clearTimers();const ticket=token.current;if(!value)await audio.current?.unlock();if(ticket===token.current&&!stopped.current)afterCorrect();}else if(!value)replay();}
  function setOption(key,value){if(key==='reduced')setReduced(value);else setLow(value);save(old=>({...old,settings:{...old.settings,[key]:value}}));}
  async function start(reset=false){clearTimers();const ticket=token.current,unlocked=audio.current?.unlock();let next=settleChapter(reset||progress.current.complete?freshChapter():progress.current);next={...next,settings:{muted:mutedRef.current,reduced,low}};player.current=next.position;world.current?.restore(next.position);save(next);resetUi();setMapOpen(false);changePaused(false);changePhase(next.mode);await unlocked;if(ticket!==token.current||stopped.current)return;preloadAct();speak(next.mode==='explore'?'chapter-welcome':cue());}
  async function openActivity(){if(stopped.current||mode.current!=='explore'||!near&&!gentle)return;clearTimers();clearInput();const ticket=token.current,unlocked=audio.current?.unlock();save(old=>({...old,mode:'activity'}));resetUi();changePhase('activity');preloadAct();await unlocked;if(ticket===token.current&&!stopped.current)speak([...(progress.current.jobs[progress.current.active].round===0?['story-'+currentAct(progress.current).id]:[]),...currentRound(progress.current).promptAudio]);}
  function choose(choice,eventTime){const now=progress.current;if(stopped.current||busyRef.current||mode.current!=='activity'||pictureError||!picturesReady)return;const activeRound=currentRound(now),result=judgeChoice(now,choice.id);if(!result.accepted)return;clearTimers();audio.current?.unlock();save(result.progress);if(!result.correct){const retry=retryFor(activeRound,choice,now.jobs[now.active].built.length);setFeedback({type:'retry',id:choice.id,text:retry.text});speak(retry.audio);audio.current?.sfx('wrong');return;}audio.current?.sfx('correct');if(!result.finished){setFeedback({type:'seed',id:choice.id,text:'Keep going. '+result.progress.jobs[now.active].built.split('').join(' · ')});speak(choice.audio);return;}changeBusy(true);correctStarted.current=eventTime;setFeedback({type:'correct',id:choice.id,text:activeRound.kind==='place'?'The '+activeRound.word+' is '+activeRound.relation.phrase+'.':activeRound.kind==='build'?'You built '+activeRound.word+'.':activeRound.kind==='sort'||activeRound.kind==='onset'?activeRound.word+' starts with /'+activeRound.word[0]+'/.':'The word is '+activeRound.word+'.'});world.current?.burst();afterCorrect();}
  function leaveActivity(){if(busyRef.current)return;clearTimers();audio.current?.stop();resetUi();save(old=>({...old,mode:'explore'}));changePhase('explore');}
  function takeReward(){if(stopped.current||mode.current!=='reward')return;const next=save(claimReward(progress.current));changePhase(next.mode);world.current?.burst();preloadAct();speak(next.complete?'chapter-finish':'story-'+currentAct(next).id);}
  function openMap(){setMapOpen(true);pause(true);}
  function closeMap(){setMapOpen(false);pause(false);}
  function select(id){const next=selectProject(progress.current,id);if(next===progress.current)return;save(next);setNear(false);closeMap();}
  function exit(){clearInput();clearTimers();audio.current?.stop();const next=save(settleChapter(progress.current));resetUi();setMapOpen(false);changePaused(false);changePhase('title');setSaved(next);}
  function retryWorld(){setReady(false);setError(null);setGentle(false);changePaused(false);setEpoch(n=>n+1);}
  function pictureTrail(){setGentle(true);setError(null);setReady(true);pause(false);}
  function touchStart(e,d){if(stopped.current)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch.current.add(d);move();}
  function touchEnd(d){touch.current.delete(d);move();}

  const worldState=useEffectEvent(()=>({phase:mode.current,paused:stopped.current||mode.current==='title',mission:ACTS.indexOf(currentAct(progress.current)),fireflies:progress.current.fireflies,repairs:repairs(progress.current),reduced,low}));
  const settings=useEffectEvent(()=>({reduced,low,chapter:true,landmarks:ACTS,roads:CHAPTER_ROADS,route:guideRoute,decorate:decorateChapter}));
  const readyWorld=useEffectEvent(()=>setReady(true));
  const failedWorld=useEffectEvent(err=>{setReady(false);setError(err.message);pause(true);});
  const snapshot=useEffectEvent(s=>{player.current={x:s.x,z:s.z};setNear(s.near);if(marker.current){marker.current.style.left=s.marker.x+'px';marker.current.style.top=s.marker.y+'px';marker.current.style.visibility=s.marker.visible?'visible':'hidden';}if(host.current){host.current.dataset.playerX=s.x.toFixed(2);host.current.dataset.playerZ=s.z.toFixed(2);host.current.dataset.drawCalls=s.drawCalls;host.current.dataset.triangles=s.triangles;}});
  const collect=useEffectEvent(id=>{save(old=>({...old,fireflies:[...new Set([...old.fireflies,id])]}));audio.current?.sfx('correct');});
  useEffect(()=>{const manager=createAudio({catalog:CHAPTER_AUDIO,onError:()=>setAudioNotice(true)});audio.current=manager;manager.setMuted(mutedRef.current);return()=>{manager.dispose();if(audio.current===manager)audio.current=null;};},[]);
  useEffect(()=>{let live=true,owned=null;createWorld(host.current,{ready(){if(live)readyWorld();},failure(err){if(live)failedWorld(err);},snapshot(s){if(live)snapshot(s);},collect(id){if(live)collect(id);}},settings()).then(instance=>{if(!live){instance.dispose();return;}owned=instance;world.current=instance;instance.restore(player.current);instance.setState(worldState());}).catch(err=>{if(live)failedWorld(err);});return()=>{live=false;owned?.dispose();if(world.current===owned)world.current=null;};},[epoch]);
  useEffect(()=>{world.current?.setState(worldState());},[phase,paused,p.active,p.jobs,p.fireflies,reduced,low,ready]);
  const tick=useEffectEvent(()=>{if(!stopped.current&&!['title','complete'].includes(mode.current))save(old=>({...old,seconds:old.seconds+1}));});
  useEffect(()=>{const interval=setInterval(()=>tick(),1000);return()=>clearInterval(interval);},[]);
  const keyEvent=useEffectEvent((e,down)=>{const dirs={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down'};if(!down){keys.current.delete(dirs[e.key]);move();return;}if(e.key==='Escape'&&mode.current!=='title'){e.preventDefault();if(mapOpen)closeMap();else pause(!stopped.current);return;}if(stopped.current)return;if(mode.current==='explore'&&dirs[e.key]){e.preventDefault();keys.current.add(dirs[e.key]);move();}if(['e','Enter',' '].includes(e.key)&&mode.current==='explore'&&(e.target.tagName==='CANVAS'||e.target===document.body)){e.preventDefault();document.querySelector('[data-world-action]')?.click();}});
  const lostFocus=useEffectEvent(()=>{clearInput();if(!['title','complete'].includes(mode.current))pause(true);});
  useEffect(()=>{const down=e=>keyEvent(e,true),up=e=>keyEvent(e,false),blur=()=>lostFocus(),hidden=()=>{if(document.hidden)lostFocus();};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);};},[]);
  useEffect(()=>{if(!paused)return;const previous=document.activeElement,overlay=panel.current;overlay?.querySelector('button')?.focus();const trap=e=>{if(e.key!=='Tab')return;const items=[...overlay.querySelectorAll('button,input')].filter(el=>!el.disabled);if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);previous?.focus?.();};},[paused,mapOpen]);
  useEffect(()=>{if(phase==='activity')activityTitle.current?.focus({preventScroll:true});},[phase,act.id,job.round]);
  useEffect(()=>{const active=timers.current,run=token;return()=>{run.current++;active.forEach(clearTimeout);active.clear();};},[]);

  const mutedInert=paused?true:undefined, fallback=gentle||!!error;
  return <main className={`game chapter ${reduced?'reduced':''} ${fallback?'gentle':''}`} data-phase={phase} data-project={p.active} data-act={act.id} data-round={job.round} data-finished-rounds={finishedRounds(p)} data-seconds={p.seconds} data-child-surface="sound-seekers-chapter">
    <div className="world" ref={host}/>{fallback&&<div className="gentle-scene chapter-fallback" aria-hidden="true"/>}<div className="vignette"/>
    <div className="topbar" inert={mutedInert}><div className="brand"><Icon name="leaf" size={21}/><span>SOUND SEEKERS</span><small>A WOODLAND HOMECOMING</small></div>{phase!=='title'&&<div className="light-progress" data-child-progress aria-label={`${lights(p)} of 3 lights found`}>{[0,1,2].map(i=><span key={i} className={i<lights(p)?'found':''}><Icon name="lantern" size={22}/><span>{i+1}</span></span>)}</div>}<div className="top-actions"><button className="icon-button" aria-label={muted?'Turn sound on':'Turn sound off'} onClick={()=>toggleMute(!muted)}><Icon name={muted?'quiet':'sound'}/></button>{phase!=='title'&&<button className="icon-button" aria-label="Pause adventure" onClick={()=>pause(true)}><Icon name="pause"/></button>}</div></div>
    {phase==='title'&&<section className="title-screen" inert={mutedInert}><div className="title-copy"><div className="eyebrow"><span/> CHAPTER ONE · A WOODLAND HOMECOMING</div><h1 data-child-title>The lost<br/>little <em>lights.</em></h1><p data-child-instruction>Five little projects. Three lost lights.<br/>Make the woodland feel like home.</p><button className="primary start" data-child-primary disabled={!ready&&!gentle} onClick={()=>start()}>{!ready&&!gentle?'Growing your woodland…':saved&&!p.complete?'Continue adventure':'Let’s explore'}<Icon name="arrow"/></button>{saved&&!p.complete&&<button className="text-button" onClick={()=>start(true)}>Start a new adventure</button>}<div className="title-meta"><span>15 PLACES TO HELP</span><i/><span>SAVES AS YOU PLAY</span></div></div><div className="chapter-stamp"><Icon name="lantern" size={34}/><span>Meadow Pals</span><small>THE WOODLAND CHAPTER</small></div><div className="title-controls"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> or arrow keys</span><span>Tap the ground to walk</span><span>Play with sound</span></div></section>}
    {phase==='explore'&&<div className="explore-ui" inert={mutedInert}><section className="objective"><span className="objective-icon"><Icon name={act.icon} size={27}/></span><div><small>{PROJECTS[act.projectIndex].friend.toUpperCase()} · JOB {act.actIndex+1} OF 3</small><h1 data-child-title>{act.title}</h1><p data-child-instruction>{job.round>0?'Your little job is waiting. '+job.round+' of 8 done.':'Follow the path. '+act.action+'.'}</p></div><button className="replay-small" aria-label="Hear the next adventure" onClick={()=>speak('story-'+act.id)}><Icon name="sound"/></button></section><div className="world-marker" ref={marker}><Icon name={near?'leaf':'lantern'} size={26}/><span>{near?'You’re here!':'This way'}</span></div><div className="explore-bottom"><div className="dpad" role="group" aria-label="Move Bouncy" data-child-choices>{['up','left','down','right'].map(d=><button key={d} className={'direction '+d} aria-label={'Move '+d} onPointerDown={e=>touchStart(e,d)} onPointerUp={()=>touchEnd(d)} onPointerCancel={()=>touchEnd(d)} onLostPointerCapture={()=>touchEnd(d)}><Icon name="arrow"/></button>)}</div><div className="walk-hint"><span>Tap the path to walk</span><small>Choose another job on the map</small></div><div className="world-action-wrap"><button className={`primary world-action ${near||gentle?'can-help':'guide'}`} data-world-action data-child-primary onClick={near||gentle?openActivity:()=>world.current?.guide()}><Icon name={near||gentle?act.icon:'arrow'}/>{near||gentle?act.action:'Follow the path'}</button><span>{near||gentle?'Tap to help · E / Enter':'Explore at your own pace'}</span></div></div><button className="pocket-map-button" aria-label="Open woodland map" onClick={openMap}><Icon name="map"/><span>Map</span></button><div className="firefly-count" aria-label={`${p.fireflies.length} of 5 hidden fireflies found`}><Icon name="star" size={18}/><span>{p.fireflies.length} / 5</span></div></div>}
    {phase==='activity'&&<section className={'activity chapter-activity '+round.kind} inert={mutedInert} aria-label={act.title}><div className="activity-heading"><button className="icon-button" aria-label="Return to woodland" aria-disabled={busy} onClick={leaveActivity}><Icon name="back"/></button><div><div className="eyebrow">{PROJECTS[act.projectIndex].friend} · JOB {act.actIndex+1} OF 3</div><h1 data-child-title ref={activityTitle} tabIndex={-1}>{act.title}</h1></div><div className="round-counter" data-child-progress>{job.round+1}<span> / 8</span></div></div><div className="activity-instruction"><p data-child-instruction>{round.instruction}</p><button className="hear" aria-label="Hear this sound or word again" onClick={()=>speak(round.promptAudio)}><Icon name="sound"/><span>Listen</span></button></div>
      <div className="chapter-stage">
        {round.kind==='onset'?<div className="onset-cue"><span>Listen for</span><strong>/{round.target}/</strong><div className="basket-art" aria-hidden="true"/></div>:<div className="chapter-picture"><button aria-label={'Hear '+round.word} onClick={()=>speak('word:'+round.word)}><img src={imagePath(round.picture)} alt={round.word} onLoad={()=>imageLoaded(round.picture)} onError={()=>setPictureError(true)}/><span><Icon name="sound" size={20}/></span></button></div>}
        {round.kind==='gap'&&<div className="chapter-slots stones" aria-label={'Complete '+[...round.word].map((l,i)=>i===round.gap?'_':l).join('')}>{[...round.word].map((l,i)=><span key={i} className={i===round.gap?'missing':''}>{i===round.gap&&!busy?'?':l}</span>)}</div>}
        {round.kind==='build'&&<div className="chapter-plant"><div className="flower-row">{Array.from({length:8},(_,i)=><Flower key={i} lit={i<job.round||i===job.round&&busy}/>)}</div><div className="chapter-slots planted" aria-label={'Word built so far: '+(job.built||'no sounds yet')}>{[...round.word].map((_,i)=><span key={i} className={i<job.built.length?'filled':i===job.built.length?'waiting':''}>{job.built[i]||'·'}</span>)}</div></div>}
        <div className={'chapter-choices '+round.kind+'-choices'} role="group" aria-label={round.kind==='place'?'Places for the '+round.word:round.kind==='sort'?'First sound baskets':round.kind==='onset'?'Sound pictures':'Sound choices'} data-child-choices data-child-primary>{round.choices.map(choice=>{const used=job.used.includes(choice.id),correct=feedback?.id===choice.id&&feedback.type==='correct';return <div className="chapter-choice-wrap" key={round.id+choice.id}><button className={`chapter-choice ${used?'used':''} ${correct?'correct':''} ${feedback?.id===choice.id&&feedback.type==='retry'?'retry':''}`} aria-label={round.kind==='place'?'Put the '+round.word+' '+choice.label:round.kind==='sort'?'Choose '+choice.label+' basket':round.kind==='onset'?'Choose '+choice.label:'Choose '+choice.label+' sound'} aria-disabled={busy||pictureError||!picturesReady||used} onClick={e=>choose(choice,e.timeStamp)}>
          {round.kind==='place'?<span className={'place-scene place-'+choice.id} aria-hidden="true"><i className="place-ground"/>{choice.id==='mat'?<i className="woven-mat"/>:choice.id==='basket'?<i className="placement-basket"/>:<><i className="table-top"/><i className="table-leg left"/><i className="table-leg right"/></>}{correct&&<img className="placed-object" src={imagePath(round.picture)} alt=""/>}<i className="place-hint"/></span>:round.kind==='sort'?<span className="sorting-basket" aria-hidden="true"><strong>{choice.label}</strong>{correct&&<img src={imagePath(round.picture)} alt=""/>}</span>:choice.picture?<img src={imagePath(choice.picture)} alt="" onLoad={()=>imageLoaded(choice.picture)} onError={()=>setPictureError(true)}/>:<strong>{choice.label}</strong>}{correct&&<span className="choice-tick"><Icon name="check"/></span>}</button>{round.kind==='place'&&<span className="place-label">{choice.label}</span>}{['onset','sort','place'].includes(round.kind)&&<button className="name-object" aria-label={'Hear '+(round.kind==='sort'?choice.label+' basket':choice.label)} onClick={()=>speak(choice.audio)}><Icon name="sound" size={20}/></button>}</div>;})}</div>
      </div><div className={'feedback '+(feedback?.type||'')} role="status">{pictureError?<><span>A picture didn’t load.</span><button onClick={()=>{setPictureError(false);setLoaded({});setImageRevision(n=>n+1);}}>Try loading again</button></>:feedback?<><Icon name={feedback.type==='correct'?'check':'sound'} size={21}/><span>{feedback.text}</span></>:<span>{round.kind==='place'?'Listen. Find its place.':round.kind==='sort'?'Listen for the first sound.':'A little help makes a big difference.'}</span>}</div>
    </section>}
    {phase==='reward'&&reward&&<section className="reward-screen" inert={mutedInert}>{reward.actIndex===2&&PROJECTS[reward.projectIndex].light?<Lantern lit/>:<span className="repair-emblem"><Icon name={reward.icon} size={58}/></span>}<div className="eyebrow">{reward.actIndex===2?'A WOODLAND PROJECT FINISHED':'YOUR HELP CHANGED THE WOODLAND'}</div><h1 data-child-title>{reward.actIndex===2?PROJECTS[reward.projectIndex].reward:reward.title+' · ready!'}</h1><p data-child-instruction>{reward.done}</p><button className="primary" data-child-primary onClick={takeReward}>{p.jobs.tree.act===3?'Gather at the tree':reward.actIndex===2&&PROJECTS[reward.projectIndex].light?'Take the little light':'Back to the woodland'}<Icon name="arrow"/></button><div className="reward-count" data-child-progress>{PROJECTS.filter(j=>p.jobs[j.id].act===3).length} OF 5 PROJECTS FINISHED</div></section>}
    {phase==='complete'&&<section className="ending" inert={mutedInert}><div className="eyebrow">A WOODLAND HOMECOMING</div><h1 data-child-title>You made it<br/>feel like <em>home.</em></h1><div className="ending-lights">{[0,1,2].map(i=><Lantern key={i} lit/>)}</div><p data-child-instruction>The picnic is ready. The paths are open.<br/>The Pals are together, and the little lights are home.</p><div className="ending-stats" data-child-progress><span>5 woodland projects</span><span>{p.fireflies.length} hidden {p.fireflies.length===1?'firefly':'fireflies'}</span></div><button className="primary" data-child-primary onClick={()=>start(true)}>Another adventure<Icon name="arrow"/></button><button className="text-button" onClick={exit}>Back to the beginning</button></section>}
    {audioNotice&&!paused&&<button className="audio-notice" onClick={replay}><Icon name="sound"/>Tap to hear again</button>}
    {paused&&<div className="pause-backdrop">{mapOpen?<section className="chapter-map" role="dialog" aria-modal="true" aria-label="Woodland map" ref={panel}><div className="map-heading"><div><div className="eyebrow">YOUR LITTLE CORNER OF THE WORLD</div><h2>The woodland</h2></div><button className="icon-button" aria-label="Close map" onClick={closeMap}><Icon name="back"/></button></div><div className="chapter-map-paper" aria-hidden="true"><svg viewBox="0 0 280 200"><path className="paper-road" d="M140 187 108 155 52 132 90 105 195 110 190 75 130 66 61 43 105 23 150 17 212 38 190 75"/><path className="paper-river" d="M0 93Q140 130 280 85"/>{PROJECTS.map(project=>{const a=project.acts[Math.min(2,p.jobs[project.id].act)],x=(a.x+28)/56*280,y=(a.z+37)/63*200;return <g key={project.id} transform={`translate(${x} ${y})`}><circle r="12" fill={p.jobs[project.id].act===3?'#648769':available(p,project.id)?'#f5d998':'#a9b7a0'}/><text y="4" textAnchor="middle">{PROJECTS.indexOf(project)+1}</text></g>;})}</svg></div><div className="chapter-map-jobs">{PROJECTS.map(project=>{const done=p.jobs[project.id].act===3,open=available(p,project.id)&&!done;return <button key={project.id} className={p.active===project.id?'selected':''} disabled={!open} onClick={()=>select(project.id)}><span className="job-icon"><Icon name={done?'check':project.icon} size={28}/></span><span><strong>{project.title}</strong><small>{done?'Ready for the gathering':!available(p,project.id)?project.id==='tree'?'Help the four woodland projects first':'Mend the brook crossing first':project.acts[p.jobs[project.id].act].title}</small></span><span className="job-status"><Icon name={done?'check':open?'leaf':'bridge'} size={20}/><small>{p.jobs[project.id].act} / 3</small></span></button>;})}</div><p>Choose a place to help. Your unfinished jobs stay safe.</p></section>:<section className="pause-panel" role="dialog" aria-modal="true" aria-label={error?'Woodland loading help':'Adventure paused'} ref={panel}><Icon name={error?'leaf':'pause'} size={36}/><h2>{error?'Let’s keep exploring':'Take a little breather'}</h2><p>{error?'The 3D woodland could not load. Your progress is safe.':'Your little jobs and lights are safe here.'}</p>{error?<><button className="primary" onClick={retryWorld}>Try the woodland again</button><button className="secondary" onClick={pictureTrail}>Play the picture trail</button></>:<button className="primary" onClick={()=>pause(false)}>Keep exploring<Icon name="play"/></button>}<div className="pause-options"><label><input type="checkbox" checked={muted} onChange={e=>toggleMute(e.target.checked)}/>Sound off</label><label><input type="checkbox" checked={reduced} onChange={e=>setOption('reduced',e.target.checked)}/>Gentle motion</label><label><input type="checkbox" checked={low} onChange={e=>setOption('low',e.target.checked)}/>Lighter graphics</label></div><button className="text-button" onClick={exit}>Save and leave</button></section>}</div>}
  </main>;
}
